### ISSUE TITLE
Is it possible to change the Radio Button Drawable for the Single Choice List Dialog?

### ISSUE THREAD

**Issue by erseno** [afollestad/material-dialogs#1001]
Hello!

First, thank you for this great library :) 

I am using this snippet to make a simple single choice list dialog

```java
new MaterialDialog.Builder(this)
        .title(R.string.title)
        .items(R.array.items)
```
Was wondering if its possible for me to change the Radio button drawable? or do I need to make my own adapter? The single choice is perfect for my requirements but just would like to change the drawable of the radio button to my own selector

Thank you for reading !

**Comment by afollestad** [comment]
You'd see it in the documentation if it was possible. 

I'm guessing AppCompat has an attribute you can add  your Activity theme to change it everywhere though.
