### ISSUE TITLE
0.8.5.7 Error: more than one library with package name 'com.afollestad.materialdialogs'

### ISSUE THREAD

**Issue by dirkam** [afollestad/material-dialogs#1004]
I tried to update my build.gradle to use 0.8.5.7 (core only) but I get this error upon syncing. Works fine with 0.8.5.6. Would you please take a look? Thanks.

**Comment by afollestad** [comment]
Try `com.github.afollestad` instead of `com.afollestad`

**Comment by dirkam** [comment]
it works. thanks.
