### ISSUE TITLE
Material dialogs progress error

### ISSUE THREAD

**Issue by Gabik7** [afollestad/material-dialogs#1009]
hello is there any idea how to fix it Could not find class 'me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable' i try more version of dialogs but still this error

**Comment by smilecs** [comment]
experiencing the same thing

**Comment by afollestad** [comment]
Add

```Gradle
compile 'me.zhanghai.android.materialprogressbar:library:1.1.5'
```

To your dependencies.
