### ISSUE TITLE
Issue with android 24.0.0-alpha1

### ISSUE THREAD

**Issue by ramu2514** [afollestad/material-dialogs#1014]
Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.afollestad.materialdialogs.commons'

**Comment by afollestad** [comment]
Use com.github instead of com.afollestad.

**Comment by afollestad** [comment]
Sorry, com.github. afollestad instead of com.afollestad

**Comment by ramu2514** [comment]
Thanks it worked

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
