### ISSUE TITLE
After update dialogues are not coming centred. Please help

### ISSUE THREAD

**Issue by iampawan** [afollestad/material-dialogs#1016]
![screenshot_20160321-113738](https://cloud.githubusercontent.com/assets/12619420/13911645/6bf63e2a-ef59-11e5-9039-4656587fe080.png)

**Comment by afollestad** [comment]
I haven't experienced that problem. I'm guessing it's related a ROM you're using?

**Comment by afollestad** [comment]
If it happens with this library, it should be happening with regular AppCompat dialogs too.

**Comment by iampawan** [comment]
Can you tell me what can be the problem ?   @afollestad

**Comment by Spoetnic** [comment]
I've had this problem with multiple apps a couple of CM nightlies ago. It's currently no longer a problem.

**Comment by afollestad** [comment]
@iampawan nothing I can fix, it has to be a ROM issue.
