### ISSUE TITLE
Don't dismiss keyboard when dialog appears

### ISSUE THREAD

**Issue by mgod** [afollestad/material-dialogs#1018]
Is there a way to keep the keyboard visible behind the dialog box? I have some cases where the dialog is an error being displayed over a form and dismissing the keyboard is causing some odd animation issues with the dialog. Alternatively, can these animation issues be fixed? I'm happy to dig into this, but I can't seem to find the relevant bit of code.

Here's a sample of the bad dialog behavior I'm seeing (note the stutter near the end of the keyboard animation):
 
![material](https://cloud.githubusercontent.com/assets/519038/13933341/1588b57a-ef83-11e5-9a99-b2bd023544d5.gif)

And the same thing with AppCompat AlertDialog directly:

![appcompat](https://cloud.githubusercontent.com/assets/519038/13933381/503f938c-ef83-11e5-86c5-ff368b51c6a1.gif)

**Comment by Morocat** [comment]
Try the following code:

    MaterialDialog d = [mdInstance].build();
    d.getWindow().setFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM,
                WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
    d.show();

Taken from http://stackoverflow.com/questions/27817783/show-dialog-infront-of-keyboard

**Comment by afollestad** [comment]
This isn't the fault of this library, so I don't think it should be an issue.
