### ISSUE TITLE
Older version are being changed!!!!!!!

### ISSUE THREAD

**Issue by blazsolar** [afollestad/material-dialogs#1019]
What is happening with older versions? All tags from 0.8.5.6 backwards point to the same commit. This causes jitpack to rebuild older versions and we you do that you have multiple different builds for same version. This brakes builds which is unacceptable.

Why is this happening and can you fix it?

**Comment by blazsolar** [comment]
and will this also happen for version in the future?

**Comment by afollestad** [comment]
No
