### ISSUE TITLE
failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.4@aar

### ISSUE THREAD

**Issue by vzaffalon** [afollestad/material-dialogs#1027]
building with com.github.afollestad.material-dialogs:core:0.8.5.4@aar is not working since yesterday

**Comment by afollestad** [comment]
You should report it to JitPack.io.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
