### ISSUE TITLE
how to set Url link as hyperlink in content text 

### ISSUE THREAD

**Issue by americosfacebook** [afollestad/material-dialogs#1029]
like in text view set Linkify.
Demo:-
final TextView myClickableUrl = (TextView) findViewById(R.id.myClickableUrlTextView);
 myClickableUrl.setText("Click my web site: www.stackoverflow.com");
 Linkify.addLinks(myClickableUrl, Linkify.WEB_URLS);

**Comment by afollestad** [comment]
Look at the about dialog in the sample project.
