### ISSUE TITLE
Multiline in input dialog

### ISSUE THREAD

**Issue by gromiloff** [afollestad/material-dialogs#1030]
Is it possible to add functionality for set multi line input text ?
Now It's has only one line,  ut some times need more visible text in dialog.

**Comment by afollestad** [comment]
Read duplicate closed issues.

**Comment by gromiloff** [comment]
@afollestad can you get me link to dublicated issue ?

**Comment by afollestad** [comment]
You can search closed issues

https://github.com/afollestad/material-dialogs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+multiple+input

**Comment by lampione** [comment]
Actually nothing else seems to be related to this issue.
I can't set a multiple-lines field for the Input Dialog mode.

**Comment by mseroczynski** [comment]
@afollestad Your answer seems to relate to multiPLE not multiLINE (single) input.
