### ISSUE TITLE
The embeded scroll view (wrapInScrollView = true) over scroll doesn't inherit the right color

### ISSUE THREAD

**Issue by roman-ku** [afollestad/material-dialogs#1031]
The following pictures, show what I mean. Pay attention to the color of the over-scroll.

![untitled-1](https://cloud.githubusercontent.com/assets/10580420/14199275/cea58472-f797-11e5-9b29-47a1ee17b4d7.png)
Figure 1: The over-scroll inherits from _colorPrimary_ (which is blue), this is the correct (and expected behavior).

![untitled-2](https://cloud.githubusercontent.com/assets/10580420/14199277/d1009860-f797-11e5-8881-fa275698bdf8.png)
Figure 2: The over-scroll is white, this is not the correct behavior.

Just like all the default scroll views have the over-scroll inherit its color from _colorPrimary_, so should the embedded scroll view.

**Comment by afollestad** [comment]
The best way to fix this is just to set `android:theme` on your `ScrollView`.
