### ISSUE TITLE
Option to add checkbox as in system permission dialog

### ISSUE THREAD

**Issue by HeinrichReimer** [afollestad/material-dialogs#1032]
Would be useful if we can have the option to add a checkbox like the one in the system permission dialog.
This can be used to have options like "Never ask again" or "Save this preference".

**Comment by rfazi** [comment]
@afollestad Check my commit to see if it was right. Thank

**Comment by rfazi** [comment]
@afollestad Why you have canceled the commit?

**Comment by afollestad** [comment]
I don't think this is something that should be a feature in the core module.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.0
