### ISSUE TITLE
Custom Layout - EditText Lines Doesn't show up

### ISSUE THREAD

**Issue by vijaykd** [afollestad/material-dialogs#1034]
I have created the XML and connected it to a dialog box like this:

```java
boolean wrapInScrollView = false;
new MaterialDialog.Builder(FormActivity.this)
    .title("Custom Dialog Box")
    .customView(R.layout.queryform, wrapInScrollView)
    .positiveText("SUBMIT")
    .negativeText("CLOSE")
    .theme(Theme.LIGHT)
    .show();
```

The custom XML consists of a `TextInputMethod` and an `EditText`. Sample XML:

```xml
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:background="@color/login_background"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="30dp"
        android:orientation="vertical"
        android:paddingLeft="20dp"
        android:paddingRight="20dp">

        <android.support.design.widget.TextInputLayout
            android:id="@+id/input_layout_firstname"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <EditText
                android:id="@+id/firstname"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/firstname" />
        </android.support.design.widget.TextInputLayout>
 </LinearLayout>

</android.support.design.widget.CoordinatorLayout>
```
text shows up properly on devices that run Lollipop and more the same doesn't show up properly on Android 4.4 or less. I have attached both the screenshots Please check.. what could be wrong?Inspite of giving theme.light.

Android 4.3: (Phone)
![android4 4andbelow](https://cloud.githubusercontent.com/assets/1311337/14258642/e203fdce-fac0-11e5-9a12-cbcca1048e4d.png)

Android 5.1: (Tablet)
![android5 0andmoredialog](https://cloud.githubusercontent.com/assets/1311337/14258662/06fb019a-fac1-11e5-9e4c-289b49d30217.png)

**Comment by afollestad** [comment]
The fastest solution for this would be to apply `android:theme` to your `TextInputLayout`'s.

**Comment by afollestad** [comment]
I think that may be the only solution (what I described above), actually. There's not too much I can do automatically from code when you're using a different dialog theme than what the parent Activity is using.
