### ISSUE TITLE
Can't build an App using Digitus library and Material Dialogs

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#1035]
Hi, there is a problem while compiling an App with Digitus and Material Dialogs (common) libraries. Gradle says
`Error: more than one library with package name 'com.afollestad.materialdialogs'`

How to solve this problem? Thanks.

**Comment by afollestad** [comment]
You have to be using the same version of Material Dialogs that Digitus uses.

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.5.7@aar') {
        transitive = true
}
```

**Comment by peppe130** [comment]
I solved by setting transitive = false
