### ISSUE TITLE
Resources$NotFoundException with Support Library 23.3.0 and vector resource. 

### ISSUE THREAD

**Issue by devslava** [afollestad/material-dialogs#1037]
I use MaterialSimpleListAdapter to create dialog and I am setting vector icon as 
  adapter.add(new MaterialSimpleListItem.Builder(this)
                        .content(R.string.add_to_favorites)
                        .icon(R.drawable.ic_star) 
                        ...
In support library 23.3.0 was removed some functionality which let us use vector drawables, so now this code produce Resources$NotFoundException.

**Comment by afollestad** [comment]
This library hasn't been updated for 23.3.0 yet.

**Comment by devslava** [comment]
@afollestad Library is updated for 23.3.0 but unfortunately issue still exists.

**Comment by alexander-fischer** [comment]
Is there a way to fix it?

**Comment by afollestad** [comment]
No, this is a old version of the Support library.
