### ISSUE TITLE
Progress dialog animation stops on resume

### ISSUE THREAD

**Issue by Xmashine** [afollestad/material-dialogs#1046]
If you start the progressbar dialog and you press the hardware key to open recent apps, if you back on material dialogs the bar will be stopped, also if it haven't completed itself

**Comment by Xmashine** [comment]
I've tryed it on my samsung galaxy s6 edge (API 23) and on my Samsung galaxy ace plus SpeedMod (API 19)

**Comment by Morocat** [comment]
Could you elaborate more on this? Are you adding a MaterialProgressBar to a custom view in a dialog? Post some code so we can help.

**Comment by Xmashine** [comment]
Simply, when start the MaterialDialogs sample application on my Android phone (When try to use the official app and library), and I try to build the `progress dialog` I see a progressbar, task percentage and processed files.

well, while `PROGRESS DIALOG` is running, if I press the hardware key who invoke recent app menu (multitasking mode) The progress bar will be stopped: this bug is probabilly an unexpected `onResume` java void. 
![screenshot_20160522-225006 1](https://cloud.githubusercontent.com/assets/18101935/15456418/b8d17f88-206f-11e6-8881-c7ebb49e26ab.png)
![screenshot_20160522-225013 1](https://cloud.githubusercontent.com/assets/18101935/15456420/c5282124-206f-11e6-9ef6-b3cab967a34c.png)

**Comment by afollestad** [comment]
That's not really a bug, that's Android behavior. Your Activity needs to dismiss dialogs when it pauses, otherwise you end up leaking windows. Background tasks should usually continue from the notification drawer when your app goes into the background.
