### ISSUE TITLE
File/Folder enhancement propositions

### ISSUE THREAD

**Issue by Alex293** [afollestad/material-dialogs#1053]
File/Folder picker builder could have additional two optional methods :

setMinialPath(String path) for limiting user going too far up in the folder system tree.
shouldDisplayDotStartingItems() for removing invisible files from display.

EDIT : 
A filter object could be passed to allow personalized filtering (i.e. replacing the dot thing and allowing extended filtering instead just mime type)
This filter could be passed to the folder picker also as only file picker allow mime filtering for now.

**Comment by afollestad** [comment]
You should create a custom dialog for something like that.
