### ISSUE TITLE
No sub on primary/accent color dialog

### ISSUE THREAD

**Issue by developingwild** [afollestad/material-dialogs#1055]
I can't seem to find in the sample or on the github page how to have an color accent or primary dialog with no subs. The only thing I could find was a custom color dialog with no subs. Is it possible to have a accent/primary color dialog WITHOUT sub.

**Comment by afollestad** [comment]
The part that mentions providing a custom set of colors.

https://github.com/afollestad/material-dialogs#color-chooser-dialogs
