### ISSUE TITLE
doesn't fill elements inside custom view

### ISSUE THREAD

**Issue by maxotov** [afollestad/material-dialogs#1056]
I wanted to use custom view in dialod, but i can't initialize and fill elements. ExpandableListView doesn't show. Can eveybody help me? 

My code is following:

MaterialDialog.Builder builder = new MaterialDialog.Builder(getContext())
                        .title(R.string.shop_category)
                        .customView(R.layout.select_category_layout, true)
                        .positiveText(R.string.select)
                        .negativeText(android.R.string.cancel);

                MaterialDialog dialog = builder.build();

                ExpandableListView expandableListView = (ExpandableListView) dialog.getCustomView().findViewById(R.id.list);
                final CategoryAdapter categoryAdapter = new CategoryAdapter(getContext(), (ArrayList<Category>) mItems);
                expandableListView.setAdapter(categoryAdapter);
                categoryAdapter.notifyDataSetChanged();

                builder.onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        ArrayList<Category> cats = categoryAdapter.getSelectedCats();
                        String selectedText = "";
                        for(int i=0; i<cats.size(); i++){
                            selectedText += cats.get(i).getTitle();
                            if(i+1 < cats.size()){
                                selectedText += " | ";
                            }
                        }
                        setText(selectedText);
                        dialog.dismiss();
                    }
                });
                dialog.show();
###### Include the following:
 - Material Dialogs version: `0.8.1.0`
 - Device OS version: `5.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 4`

**Comment by Morocat** [comment]
Two immediate things that pop out:
1. By calling `customView(R.layout.select_category_layout, true)` you are wrapping your ListView in a scrollable container, something you should never do.
2. Material Dialogs 0.8.1.0 is quite old. Update to the latest version 0.8.5.8 and try again.

**Comment by afollestad** [comment]
Yeah, passing `false` into the second parameter of `customView(int, boolean)` should help. I wouldn't recommend using a `ExpandableListView` in a dialog anyways.

**Comment by maxotov** [comment]
Thank you for replies! I successfully displayed expandablelistview in my dialog. And i had a new problem, can you help to find solution? My problem describe below link: http://stackoverflow.com/questions/37100732/expandablelistview-with-checkboxes-display-in-dialog . Write any solutions may help, please. Thank you.
