### ISSUE TITLE
dialog.cancel() not working

### ISSUE THREAD

**Issue by bahmandamia6982** [afollestad/material-dialogs#1057]
How can i cancel dialog?
cancel() method not working...

```
MaterialDialog.Builder builder = new MaterialDialog.Builder(context);
    dialog.content("Loading...").cancelListener(new DialogInterface.OnCancelListener() {
         @Override
         public void onCancel(DialogInterface dialog) {
              dialog.cancel();
         }
}).progress(true, 100).cancelable(false).show();

MaterialDialog dialog = builder.build();
dialog.cancel();
```

**Comment by afollestad** [comment]
This wouldn't have anything to do with this library. `cancel()`, `dismiss()`, `show()`, etc. are not methods I created. Their from `android.app.Dialog`.

You should use `dismiss()` to close dialogs, though.

**Comment by bahmandamia6982** [comment]
Thanks for reply, but i have problem with close dialog.
cancel(), dismiss() cannot close dialog.
There is something else to use it  :) ? or i did wrong :(?

thanks again @afollestad

**Comment by afollestad** [comment]
I'm not sure what could be wrong, none of the other thousands of people using this library have reported anything wrong. 

Although I did notice you set `cancelable(false)` in one instance above which would block `cancel()`.

**Comment by afollestad** [comment]
I already closed the issue, by the way. Not much can be done on my end.

**Comment by comeondude** [comment]
```java
new MaterialDialog.Builder(SignupOrLoginActivity.this)
    .title("Title")
    .content("Content")
    .positiveText(R.string.ok)
    .onPositive(new MaterialDialog.SingleButtonCallback() {
        @Override
        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
            dialog.dismiss();
            startActivityForResult(intent);
        }
    }).show();
```
Here's how I built the dialog and still experiencing the same issue they reported. I understand its not much to do with you as you're using the default behaviour. I just pointed out that it doesn't get dismissed or cancelled even if the `cancelable(false)` is not set.

**Comment by comeondude** [comment]
Somehow I figured out to get my problem solved. So I feel like sharing here. 
```java
new MaterialDialog.Builder(MyActivity.this)
    .title("Title")
    .content("Content")
    .positiveText(R.string.ok)
    .onPositive(new MaterialDialog.SingleButtonCallback() {
        @Override
        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
            dialog.dismiss();
            startActivityForResult(intent);
        }
    }).show();
```
This implementation was not working. Cancelling or dismissing the dialog from inside the `onClick` function was not working for me. So I created an instance of the `MaterialDialog` and called `build` 
```java
private void initializeDialog() {
    mDialogBuilder = new MaterialDialog.Builder(MainActivity.this)
        .title("Title")
        .content("Content")
        .cancelable(false)
        .positiveText(R.string.ok)
        .onPositive(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                // Removed the cancel/dismiss call from here. 
                startActivityForResult(intent);
            }
        });

    // Build the dialog
    mDialog = mDialogBuilder.build();
}
```
Then I could show and dismiss/cancel the dialog using 
```java
mDialog.show();  // Show the dialog
mDialog.dismiss()  // Dismiss  the dialog
```
This is strange but working and I don't know why. May the the reference of the `MaterialDialog` passed to `onClick` of `MaterialDialog.SingleButtonCallback` has the wrong reference.

**Comment by ahmed9dz** [comment]
_**
### ~~~~ ** _
