### ISSUE TITLE
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.

### ISSUE THREAD

**Issue by wjk2015** [afollestad/material-dialogs#1058]
###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
This is just a doubt, if have no time, please ignore it. I run the demo, and show any dialog, when I press the shade part, dialog dismiss, but the log will show "com.afollestad.materialdialogssample W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.", app run as well, not crash. I confuse that why this reported?

**Comment by Morocat** [comment]
This happens from a variety of causes. I would suggest searching google for the error message and finding a post relevant to your issue. I get this message as well from time to time but it does not seem to cause any issues with my app.

**Comment by dmytroKarataiev** [comment]
Can confirm, neither your app or my app with your AlertDialog don't work and both show this error in the logcat. 
I tried to use your library, because of this error with an Android AlertDialog: https://code.google.com/p/android/issues/detail?id=208886

**Comment by afollestad** [comment]
That was a double negative sentence, lol. 😛

This library just wraps around regular dialogs, with a different layout. Dialog behaivor won't be much different. Although list dialogs are in a custom adapter, so if wouldn't be exactly the same as that Google Code issue. 

Whatever this logcat error means, it isn't anything that affects functionality. Thousands of apps are using my library, including Nova and Action Launcher.

**Comment by dmytroKarataiev** [comment]
But why even your app isn't working on a Nexus 6P? Can you check please?

**Comment by afollestad** [comment]
It works fine on the Nexus 6P. I use a 6P primarily myself.

**Comment by dmytroKarataiev** [comment]
Sorry, but it doesn't work, here is a video: 
https://youtu.be/cYDA3zsmqWY

**Comment by afollestad** [comment]
@dmytroKarataiev well that's entirely unrelated to anything in this issue, I can reproduce that issue but it belongs in a separate issue.

**Comment by afollestad** [comment]
@dmytroKarataiev I'm guessing disabling the option to always call the selection listener (and only call it when the action button is pressed) would resolve the problem for now.
