### ISSUE TITLE
java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable 0.8.5.5@aar  

### ISSUE THREAD

**Issue by chond** [afollestad/material-dialogs#1059]
java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable

progressDialog = new MaterialDialog.Builder(getActivity())
                            .title("apk install")
                            .content("test")
                            .progress(true, 100)
                            .cancelable(false)
                            .show();

**Comment by afollestad** [comment]
You didn't follow the checklist in the issue template I see. 

There are closed issues that are duplicates already. And please use Java syntax highlighting.

**Comment by chond** [comment]
if you meet this problem , compile 'com.android.support:appcompat-v7:23.3.0' can solve this problem

**Comment by ibrahim-appgodz** [comment]
same i am getting
