### ISSUE TITLE
java.lang.NumberFormatException: Invalid int: ""

### ISSUE THREAD

**Issue by josmanperez** [afollestad/material-dialogs#1061]
Hi!, 

I am using the MaterialDialog to recieve the input of the user, but doing test I figure out that if you leave the input field empty it crash with this exception

`java.lang.NumberFormatException: Invalid int: ""`

This is the code

`public void onItemClick(View v, int position, final int codigo, String procedencia) {

        Log.e("codigo seleccionado", String.valueOf(codigo) + " : " + procedencia);
        new MaterialDialog.Builder(this)
                .title(R.string.introduce_cantidad_reducido)
                .inputType(InputType.TYPE_CLASS_NUMBER)
                .content(R.string.introduce_cantidad)
                .input(null, null, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {
                        try {
                            Log.e("nose", "");
                            if (TextUtils.isDigitsOnly(input)) {
                                if (Integer.parseInt(input.toString()) > 0) {
                                    Log.e("cantidad", input.toString());
                                    Toast.makeText(AnadirAlimentoActivity.this, mAlimentoList.get(codigo - 1).getDescripcion() + " añadido con éxito", Toast.LENGTH_LONG).show();
                                    alimentosSecleccionados.add(mAlimentoList.get(codigo - 1));
                                    contadorAlimentos++;
                                    invalidateOptionsMenu();
                                } else {
                                    Toast.makeText(AnadirAlimentoActivity.this, "Por favor, selecciona una cantidad válida", Toast.LENGTH_LONG).show();
                                }
                            }
                        } catch (Exception e) {
                            Toast.makeText(AnadirAlimentoActivity.this, "Por favor, selecciona una cantidad válida", Toast.LENGTH_LONG).show();
                        }
                    }
                })
                .negativeText("Cancelar")
                .cancelListener(new DialogInterface.OnCancelListener() {
                    @Override
                    public void onCancel(DialogInterface dialog) {
                    }
                })
                .show();
    }`

It just crash.. and I have tried a lot of different things with the input field.. and even the try catch block never gets fired

Thank you

(I'm trying this in the emulator)

**Comment by afollestad** [comment]
That has nothing to do with this library. It's your code that parses the input as an integer.

**Comment by josmanperez** [comment]
Ok. but I just wanted to know why the input that I recieved from the `onInput` method is not a CharSequence... and also why if I make an `inputType(InputType.TYPE_CLASS_TEXT)` the keybord is shown as numbers..

Thanks

**Comment by afollestad** [comment]
Also, your catch block would need to catch `Throwable`, rather than `Exception`. `Exception` will not catch anything that inherits `RuntimeException`, such as `NumberFormatException`.

**Comment by afollestad** [comment]
I'm guessing your `TextUtils` method is not working, since the code attempts to parse an empty string (`""`) as an Integer.
