### ISSUE TITLE
Adapt dialog for round screens (Android wear)

### ISSUE THREAD

**Issue by mag2007** [afollestad/material-dialogs#1063]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Watch`

Is it possible to adapt the dialogs for round screens? I am trying to use the dialog in my huawei watch, but the dialog goes out of the screen. Is there a way, to shrink the dialog, or maybe make it round? As much i know you own huawei watch too, so maybe there is something possible to make about it? 👍 Thanks in advance!

**Comment by afollestad** [comment]
That's a little past the scope of this library. The stock dialogs look fine on Android Wear devices though.

**Comment by mag2007** [comment]
Well, i don't think so. The stock dialog looks like Holo style. But when i use appcompat theme, the dialog goes off the screen (like your material dialog too). Cause of it, i thought, maybe it would be nice to have nice material dialog for round screens too(i know, the rect screen with stock dialog using appcompat theme looks good. But thanks anyway.
