### ISSUE TITLE
Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.8

### ISSUE THREAD

**Issue by 024nandan** [afollestad/material-dialogs#1065]
When im trying to add afollestad material dialogs to my gradle its throwing a error message

Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.8@aar

**Comment by DeveloperXY** [comment]
Put this in your project's gradle file (the top level):

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

& in your module's gradle file:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    ...
    compile('com.github.afollestad.material-dialogs:core:0.8.5.8@aar') {
        transitive = true
    }
}
```

**Comment by 024nandan** [comment]
I have already tried this but no luck @DeveloperXY

**Comment by piotrek1543** [comment]
@024nandan I suggest to downgrade version from `0.8.5.8` to `0.8.5.4` like here: 
https://github.com/afollestad/luminous/blob/5da5710cde414f985e7177a14b9f340b7d49c847/app/build.gradle

**Comment by afollestad** [comment]
I would not recommend using an older version than the latest in any case.

There's not much I can do to help resolution issues though. You should talk to JitPack.io.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
