### ISSUE TITLE
Gradle sync failed: Failed to notify project evaluation listener.          

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#1067]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.

 - Material Dialogs version: `0.8.5.9`
 - This has nothing to do with my device configuration
 
###### Reproduction Steps

1. Update material dialogs on my app in build.grade

https://github.com/enricocid/iven-feed-reader

2. Sync gradle 

###### Actual Result

Gradle sync failed: Failed to notify project evaluation listener.

**Comment by afollestad** [comment]
Sorry, I've never heard of that error before and have no idea what it would be.

**Comment by enricocid** [comment]
Me too:( but I'm able to solve it by downgrading the lib.
No problem, i'm gonna keep the previous release for now:)

**Comment by MichaDo** [comment]
I think, you use the dependency as com.**github**.afollestad.material-dialogs:core:0.8.5.9. But currently it is com.afollestad.material-dialogs:core:0.8.5.9.

**Comment by enricocid** [comment]
My bad then. Changing to  com.afollestad.material-dialogs:core:0.8.5.9 solved the issue
thank you
