### ISSUE TITLE
input dialog singleline false?

### ISSUE THREAD

**Issue by TheLoyalCruel** [afollestad/material-dialogs#1068]
hi
how to change input dialog to multi line?

thanks in advance...

**Comment by afollestad** [comment]
You can perform operations on `dialog.getEditText()`

**Comment by TheLoyalCruel** [comment]
where can I getEditText()?
is it possible at builder? dialog.getEditText()

**Comment by TheLoyalCruel** [comment]
thanks :)
I got it this way:
`inputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE)`
