### ISSUE TITLE
[Feature Request] CoolLoadingDialog

### ISSUE THREAD

**Issue by TurKurT656** [afollestad/material-dialogs#1069]
Hi,
TnQ for this amazing lib. I use this library in all of my apps.
Defalut `ProgressDialog` is the only dialog that i dont like. Can u add a dialog like [This Library](https://github.com/code-mc/loadtoast)?
It is better for loading dialogs and it has error and success state that is cool.

**Comment by afollestad** [comment]
Sorry, no. This library is meant to mimic Material Design dialogs that exist on Lollipop and above.
