### ISSUE TITLE
Error:Problems reading data from Binary store in 'xxx/xxx/xxx/xxx.bin' (exist:true)

### ISSUE THREAD

**Issue by SpinyLei** [afollestad/material-dialogs#1071]
I found this problem 
`Error:Problems reading data from Binary store in /private/var/folders/yh/yjw_jmc55nx143fv4h2lpms00000gn/T/gradle5586465002841643271.bin (exist: true)`
when I add 
`compile 'com.afollestad.material-dialogs:core:0.8.5.9'`
into my build.gradle

Anyone can help me?
Thanks in advance.

**Comment by afollestad** [comment]
There's probably nothing I can do, but you should try Cleaning your project.
