### ISSUE TITLE
issue with commons library import

### ISSUE THREAD

**Issue by HashirLabs** [afollestad/material-dialogs#1073]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `4.4.4`
Issue on android studio

 
###### Reproduction Steps

1. The moment i add commons library into my project and sync for it , its never able to pickup commons, the material core version is absolutely working fine, however while adding commons, the android sdk sync itself fails. I need to use file and folder choosers, any help is appreciated.

**Comment by afollestad** [comment]
That's not the latest version, and there's already an open issue for Commons. The check boxes at the top are there for a reason, lol.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
