### ISSUE TITLE
How to get the item clicked id in list dialog

### ISSUE THREAD

**Issue by brunochichava** [afollestad/material-dialogs#1074]
Hi!

How to get the item clicked in list dialog? There's my code:

`new MaterialDialog.Builder((MainActivity) getContext())
                                        .title("Jackpot")
                                        .items(R.array.jackpot)
                                        .cancelable(false)
                                        .negativeText("Cancelar")
                                        .itemsCallback(new MaterialDialog.ListCallback() {
                                            @Override
                                            public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                                // how to get the item clicked and do something
                                            }
                                        })
                                        .show();`

My string array code is here:

`<array name="jackpot">
        <item name="super_jackpot">1. Super Jackpot</item>
        <item name="credito_jackpot">2. Credito Jackpot</item>
        <item name="sms_jackpot">3. SMS Jackpot</item>
        <item name="jackpot_internet">4. Jackpot Internet</item>
        <item name="blackberry_jackpot">5. Blackberry Jackpot</item>
    </array>`

Thanks in advance...

**Comment by afollestad** [comment]
You should read the documentation.
