### ISSUE TITLE
Error in adding dependency in android

### ISSUE THREAD

**Issue by vishwesh3** [afollestad/material-dialogs#1075]
When I have following code gradle is build successfully.

ext {
    supportLibVersion = '23.2.1'  // variable that can be referenced to keep support libs consistent
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.android.support:appcompat-v7:${supportLibVersion}"
    compile "com.android.support:design:${supportLibVersion}"
    compile 'pl.pawelkleczkowski.customgauge:CustomGauge:1.0.1'
    compile "com.android.support:recyclerview-v7:${supportLibVersion}"
    compile "com.android.support:cardview-v7:${supportLibVersion}"
    compile 'com.rengwuxian.materialedittext:library:2.1.4'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.wdullaer:materialdatetimepicker:2.3.0'
}

But when I added below dependency it stated giving me error.

 compile 'com.afollestad.material-dialogs:core:0.8.5.9'
error

Error:Failed to resolve: com.android.support:appcompat-v7:23.4.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Any suggestions. Thanks

**Comment by afollestad** [comment]
You don't have the latest version of Google's libs installed. 23.2.1 should be 23.4.0. 

The solution is at the bottom, "Install Repository..."

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
