### ISSUE TITLE
How to change text color of positive and negative buttons in any dialog?

### ISSUE THREAD

**Issue by niket-sminq** [afollestad/material-dialogs#1078]
How to change text color of positive and negative buttons in any dialog?
I am not able to change text color of positive and negative button for any dialog.
Any idea?

I canot do with this
new AlertDialogWrapper.Builder(context)
                    .setTitle(title)
                    .setMessage(message)
                    .setPositiveButton(positiveBtnLabel, dialogClickListener)
                    .setNegativeButton(negativeBtnLabel, dialogClickListener)
                    .setNeutralButton(neutralBtnLabel, dialogClickListener)
                    //.setIcon(android.R.drawable.ic_dialog_alert)
                    .show();

ALSO how to add DialogInterface.OnClickListener  to this 
 new MaterialDialog.Builder(context)
                    .title(title)
                    .content(message)
                    .positiveText(positiveBtnLabel)
                    .negativeText(negativeBtnLabel)
                    .neutralText(neutralBtnLabel)
                    .positiveColorRes(R.color.green)
                    .neutralColorRes(R.color.gray_light)
                    .negativeColorRes(R.color.gray_lighter)
                    .show();

?

**Comment by peppe130** [comment]
https://github.com/afollestad/material-dialogs#global-theming

**Comment by DAKZH** [comment]
Where link goes to?
