### ISSUE TITLE
how to implement gridview in nested custom material dialog

### ISSUE THREAD

**Issue by Swapnil-Garg16** [afollestad/material-dialogs#1080]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
I'm not sure, you'll have to figure that out yourself. It'd probably require a subclass with custom measuring.
