### ISSUE TITLE
Enhancement: Adding Buttons on Color Chooser Dialog

### ISSUE THREAD

**Issue by ChadTeitsma** [afollestad/material-dialogs#1082]
Is there a way to add a new button to the Color Chooser Dialog that you could register a callback for? I would like to use the Color Chooser dialog, but want to have a custom button that can launch to a dialog that has a custom view.

**Comment by afollestad** [comment]
Sorry, no. 

You shouldn't link dialogs to dialogs either, that's a bad UI practice.
