### ISSUE TITLE
How to change text size of title, message or action buttons?

### ISSUE THREAD

**Issue by moshtagh** [afollestad/material-dialogs#1083]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by peppe130** [comment]
You have to create a custom layout and then set it in the Dialog using
`mDialog.customView(R.layout.YourCustomLayout, false`

**Comment by lidox** [comment]
What about this solution:

```
MaterialDialog dialog = b.build(); // build as you like

// now the trick
MaterialDialog d = dialog;
d.getTitleView().setTextSize(TypedValue.COMPLEX_UNIT_DIP, 60); // Your size
d.getActionButton(DialogAction.POSITIVE).setText("muhaha"); // Your text
      
dialog = d;
dialog.show();
```

**Comment by peppe130** [comment]
I have not tried your code but if it works you can simplify it this way:

```java

MaterialDialog dialog = b.build(); // build as you like

dialog.getTitleView().setTextSize(TypedValue.COMPLEX_UNIT_DIP, 60); // Your size
dialog.getActionButton(DialogAction.POSITIVE).setText("muhaha"); // Your text
dialog.show();
```

**Comment by adrianrosalesc** [comment]
Hello, I have similiar problems but not with title and buttons(I did lidox idea). My problem is regarding to change the size for items in Single Choice List Dialogs. Can someone help or give me some tips?

**Comment by youssefwagih** [comment]
any update about changing font size in single choice list dialogs

**Comment by afollestad** [comment]
This issue does not apply to the latest versions of the library, and you cannot.

**Comment by youssefwagih** [comment]
ok thank you very much 👍

**Comment by josephyuen** [comment]
> This issue does not apply to the latest versions of the library, and you cannot.
For the lateset versions of the library, I use this: 
dialog.getActionButton(WhichButton.POSITIVE).textSize
