### ISSUE TITLE
About Single Choice List Dialogs

### ISSUE THREAD

**Issue by yungfan** [afollestad/material-dialogs#1084]
If the radio button is too much, can columns displayed？The default is too ugly

**Comment by afollestad** [comment]
No, the default isn't ugly and it follows the Material Design guidelines. 

![screener_20160521 21 28 00](https://cloud.githubusercontent.com/assets/1820165/15451793/fc346eb4-1f9a-11e6-9eab-c7372b24ae7f.png)

You can make a custom implementation using a custom list adapter.

**Comment by yungfan** [comment]
Thank you
