### ISSUE TITLE
How to stop dialog from dismissing when clicked on positive button.

### ISSUE THREAD

**Issue by sarthak1996** [afollestad/material-dialogs#1085]
I have overriden the onclick method in onPositive of the dialog and there i check whether anything is entered in the editText in the dialog box. If it is i want to dismiss the dialog if not then do not dismiss the dialog. I put if-else condition for checking if editText is empty but by default the dialog is dismissed after clicking on Positive button.

`if(string!=null && !string.isEmpty()){`
`dialog.dismiss();`
`}`
`else{`
`Toast.makeText(context,"Enter something,LENGTH.SHORT);`
`}`

**Comment by peppe130** [comment]
[here](http://stackoverflow.com/questions/2620444/how-to-prevent-a-dialog-from-closing-when-a-button-is-clicked)

**Comment by sarthak1996** [comment]
The .positiveText method of this dialog only takes one parameter (the title of the positive button). I can't pass null as done in the stackoverflow eg..

**Comment by afollestad** [comment]
You can pass null if you cast to a String, null by itself is ambiguous cause the compiler doesn't know if you mean `positiveText(int)` or `positiveText(String)`.

However, you should **not** do that anyways. Instead, don't use `positiveText()` at all. The default is `null` already.

**Comment by afollestad** [comment]
Also, that StackOverflow post has nothing to do with this library. 

If you read the README documentation, you'd see there's an `autoDismiss` property which is true by default. When disabled, the dialog will remain open. @sarthak1996 @peppe130

**Comment by sarthak1996** [comment]
Thanks a lot....

**Comment by gozeloglu** [comment]
> See [here](http://stackoverflow.com/questions/2620444/how-to-prevent-a-dialog-from-closing-when-a-button-is-clicked)

I have a question about the solution in this link. I extend `AppCompatDialogFragment` from my class, and I override the `onCreateDialog` method. So, I tried to solve my problem with this solution which is given in link. But I did not understand class structure like which class is extended, which function is overrided. Can you tell me which class is extended and which function is overrided?

**Comment by flutterq** [comment]
Here is a Step By Step Guide to [how to dismiss an alertdialog on a flatbutton click?](https://flutterq.com/wp-admin/post.php?post=253&action=edit)
