### ISSUE TITLE
Input dialogs listener not firing

### ISSUE THREAD

**Issue by easycheese** [afollestad/material-dialogs#1086]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X] I have verified that I am using the latest version of Material Dialogs.
- [ X] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.9`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```
        new MaterialDialog.Builder(this)
                .title("Title")
                .content("Description")

                .input("", "", new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {

                        Log.d("TAG", "New input: " + input);
                    }
                })
                .show();
```
###### Reproduction Steps

1.  Add a new Input Dialog
2.  Run code, type input

###### Expected Result
Log output

###### Actual Result
Nothing happens

**Comment by easycheese** [comment]
Disregard, apparently this only runs after the positive button is selected, not upon input change.

**Comment by afollestad** [comment]
That depends on whether or not you set a property as specified in the tutorial
