### ISSUE TITLE
Request: Filtering file by extension in FileChooserDialog

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1088]
Material Dialogs version: `0.8.5.8`

Hi there, I'd like you to add this feature, i.e. filtering file according to its extension with `FileChooserDialog`. In 0.8.5.8 version, the only feature I found is filtering file by its mime-type.

```java
new FileChooserDialog.Builder(this)
            .extensions("002", "bin", "exe") // we can use varargs here
            .show();
```

I hope you introduce this feature in the next release. Thanks in advance.

**Comment by afollestad** [comment]
You should just use the MIME type of the extension that you're filtering. You can use MIME wildcards too, like `video/*`.

**Comment by anggrayudi** [comment]
Using mime with wildcards is not enough. For some cases, I just want to view files with numbered-extension, like `001`, `002`, `003` and so on. Where you can find this mime-type? I have searched theirs in [this site](http://www.freeformatter.com/mime-types-list.html), but I can't find one. Or, can we create our custom mime-type and list them in that site?
