### ISSUE TITLE
Help : passing appcombat context to File/FolderChooser without extending

### ISSUE THREAD

**Issue by Madaditya** [afollestad/material-dialogs#1089]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.9`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `titan`

How can i do this? Please Help.
```
 new FolderChooserDialog.Builder(this)
   
```
 
###### Reproduction Steps
insted of this tried, 

1.   getActivity().this
2.  getContext() 

###### Expected Result
While using FolderDialogueBuilder, cannot pass context(this) when MyActivity dosen't Extend AppCombatActivity.
Should work without errors

###### Actual Result

Error : Builder (v7.AppCombatActivity & ExampleActivity) in Builder cannot be applied to ExampleActivity

**Comment by afollestad** [comment]
Cast the Activity to `AppCompatActivity`.

**Comment by afollestad** [comment]
Your Activity has to extend AppCompatActivity, too. This entire library expects that.
