### ISSUE TITLE
how to hide a progress dialog 

### ISSUE THREAD

**Issue by WaelBelhassen** [afollestad/material-dialogs#1091]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
This is a completely unnecessary issue.

Read the documentation.
