### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by emartynov** [afollestad/material-dialogs#1092]
I think with latest support library the material dialogs is deprecated. Am I missing something?

**Comment by afollestad** [comment]
It's not.

**Comment by emartynov** [comment]
Cool! What is difference or missing part?

**Comment by afollestad** [comment]
A better/easier API and more features as shown in the documentation

**Comment by emartynov** [comment]
Ah, nice! I don't use dialogues much, and included functionality in support library is enough for me. Thanks for answering!
