### ISSUE TITLE
How to hide/disable the Custom button in Color Palette

### ISSUE THREAD

**Issue by CeJienAJPC** [afollestad/material-dialogs#1094]
- [yes ] I have verified there are no duplicate active or recent bugs, questions, or requests

I would like to remove the "custom" button in the Color Palette dialog. How can this be done?
_Reason:_ I have an array of preset colors. I want the user to pick only the preset colors not a custom color using seekbar

Regards

**Comment by Vall0n** [comment]
Hi @CeJienAJPC,

this is not a bug you can deny the custom Color selection by set the Option "allowUserColorInput" to false.

`builder.allowUserColorInput(false);`

Best regards, 

Vall0n

**Comment by CeJienAJPC** [comment]
@Vall0n 
Thank you for the solution. I know it ain't a bug. I was just looking if there was a way. Thanks again
