### ISSUE TITLE
ColorChooserDialog.Builder Contructor Change

### ISSUE THREAD

**Issue by Vall0n** [afollestad/material-dialogs#1095]
Hi,

first of all many thanks for this great library!

This is not an issue but an enhancement or feature.
It would be great If we can create a ColorChooserDialog.Builder instance with separated 
AppCompatActivity and ColorChooserDialog.ColorCallback.

###### So, currently you have to do it like this:

`new ColorChooserDialog.Builder(MyAppCompatActvitiy.this, R.string.title_pick_color);`

where "MyAppCompatActvitiy" is sth like this:

`public class MyAppCompatActvitiy extends AppCompatActivity implements  ColorChooserDialog.ColorCallback`

The Problem is that I want to implement the ColorCallback Interface in another class (that maybe isn't even an Activity). So to get that working I did the following:

````
MyAppCompatActvitiy extends AppCompatActivity implements  ColorChooserDialog.ColorCallback
{

	private ColorChooserDialog.ColorCallback colorCallback = null;
	.
	.
	.
        public void setColorCallback(ColorChooserDialog.ColorCallback colorCallback)
	{
		this.colorCallback = colorCallback;
	}
	.
	.
	.
	@Override
	public void onColorSelection(@NonNull ColorChooserDialog dialog, @ColorInt int selectedColor) 
	{
		if(colorCallback != null)
		{
			colorCallback .onColorSelection(dialog, selectedColor);
		}
	}

}
````

And in the class, where I actually want to implement the ColorCallback, looks like this:

````
public class MyClassWithColorChooserDialog 
{
.
.
.
if(getParent().getActivity() instanceof MyAppCompatActvitiy) {
			MyAppCompatActvitiy panel = (MyAppCompatActvitiy) getParent().getActivity();
			panel.setColorChooserCallback(new ColorChooserDialog.ColorCallback() {
				@Override
				public void onColorSelection(@NonNull ColorChooserDialog dialog, @ColorInt int selectedColor) {
					String strBytes = Integer.toHexString(selectedColor);
					writeValue(strBytes, false);
				}
			});
			ColorChooserDialog.Builder builder = new ColorChooserDialog.Builder(panel, R.string.title_pick_color);
			builder.titleSub(R.string.title_pick_sub_color);
			builder.preselect(getIValue());

			ColorChooserDialog colorChooserFragment = builder.build();
			colorChooserFragment.show(getParent().getActivity().getSupportFragmentManager(), MyAppCompatActvitiy.FRAGMENT_TAG_USER_DIALOG);
}
.
.
.

}

````

###### So that is somehow not the best solution and it would be great to have a constructor like this:

`ColorChooserDialog.Builder builder = new ColorChooserDialog.Builder(getActivity(), myColorCallbackImplementation, R.string.title_pick_color);`

Best regards,

Vall0n

**Comment by afollestad** [comment]
The reason this library does not separate the callback from the Context is because a callback will not survive through an orientation change. The Activity however gets recreated and the `DialogFragment` re-attaches to it.

**Comment by Vall0n** [comment]
Hi, 

OK, I didn't knew it, thanks for clarifying!

Best regards,

Vall0n
