### ISSUE TITLE
Not able to see title

### ISSUE THREAD

**Issue by franklyinnovations** [afollestad/material-dialogs#1097]
Not able see title in progress bar

```java
 loadingDialog = new MaterialDialog.Builder(getActivity())
                .title("Fetching")
                .content("Please wait..")
                .progress(true, 0)
                .show();
```

![screen shot 2016-06-13 at 2 58 28 pm](https://cloud.githubusercontent.com/assets/12043171/16002869/74c2ee4e-3177-11e6-870c-e240283a2659.png)

**Comment by franklyinnovations** [comment]
got it !
In DialogInit class
you need to replace 

dialog.title = (TextView) dialog.view.findViewById(R.id.title);
as
dialog.title = (TextView) dialog.view.findViewById(R.id.brand);

**Comment by afollestad** [comment]
`R.id.brand` isn't a used identifier in my library.
