### ISSUE TITLE
Android N (SDK 24) instability

### ISSUE THREAD

**Issue by diceroll123** [afollestad/material-dialogs#1099]
It seems more to be with appcompat itself than the guesswork that the library does for colors.

The dialog below should be dark.

![0](https://cloud.githubusercontent.com/assets/1243957/16122860/c6d6c21e-33b6-11e6-95ff-f27e3d47c410.png)

Setting the theme to `Theme.LIGHT` manually works in light/dark mode, *but the dialog ends up light, obviously, which doesn't match well*. Setting `Theme.DARK`, well, looks like the screenshot above, as that is of the library determining the theme itself. Below is a screenshot of this. _the above and below are not of the same dialog, but, you get the idea._

![screenshot_20160616-114408](https://cloud.githubusercontent.com/assets/1243957/16123074/a6f6e70c-33b7-11e6-89c5-2aa9d324c824.png)

**Comment by jushlwest** [comment]
the same issue

**Comment by diceroll123** [comment]
In the meantime I did this on the dialog builder. Set `lightMode` to use your preference value...

```java

.titleColorRes((lightMode ? android.R.color.black : android.R.color.white))
.contentColorRes((lightMode ? android.R.color.black : android.R.color.white))
.backgroundColorRes((lightMode ? android.R.color.white : R.color.dark_background))```

It's not the same but it'll do for now. :stuck_out_tongue_closed_eyes:

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
