### ISSUE TITLE
I can not use the commons of material-dialogs , please help

### ISSUE THREAD

**Issue by ynhenggg** [afollestad/material-dialogs#1100]
dear    Aidan Follestad: 

I saw your material-dialogs is very beautiful on github , and i am going to use it in develop-work .

but I got some problem with the starting ,
1. when I just use the core ,
compile 'com.afollestad.material-dialogs:core:0.8.5.9'------------it`s ok;
2. when I want to use the commons,
compile 'com.afollestad.material-dialogs:commons:0.8.5.9'------the gradle failed to resolve,
3. so I tried to core+commons------------------------------------------failed too.

I do not know why , please help.

**Comment by Vall0n** [comment]
Hello @ynhenggg,

There is already an issue with this bug. Have a look at this issue #1066 [.](https://github.com/afollestad/material-dialogs/issues/1066) There is also a Workaround.

Best regards,

vall0n

**Comment by afollestad** [comment]
Please follow the issue template filled in before filing an issue, too. Part of that was checking for duplicate issues.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.0
