### ISSUE TITLE
Add tag method to ColorChooserDialog

### ISSUE THREAD

**Issue by garretyoder** [afollestad/material-dialogs#1102]
The ColorChooserDialog should have the tag method as the rest of the dialogs, as without it, it makes it rather difficult to have multiple dialogs bound to one activity.

**Comment by afollestad** [comment]
Well with current versions, you can just check the title.

**Comment by garretyoder** [comment]
I suggested this because the `dialog.getTitle()` method was returning a completely different resource Id than the two dialog's titles. A bit later I discovered it was returning the value of `titleSub` from the builder, which I had the same between the two dialogs. Not sure if this is the intended functionality or a bug, but now that I know what value it's returning I can work around it. That possible bug aside, I still think it should support the tag, simply for some people may want multiple dialogs with the same title. In a bit I'll submit a pull request to add it in.
