### ISSUE TITLE
Done/Return button on keyboard doesn't dismiss dialog but just hides keyboard

### ISSUE THREAD

**Issue by wizofaus** [afollestad/material-dialogs#1105]
When using .inputType(TYPE_CLASS_TEXT).
I'm not sure if it's a bug but it's certainly unexpected and it would be handy functionality to have.
You can add it with:

    class OnShowListener implements MaterialDialog.OnShowListener
    {
        @Override
        public void onShow(DialogInterface dialog)
        {
            final MaterialDialog dlg = (MaterialDialog)dialog;
            dlg.getInputEditText().setOnEditorActionListener(new TextView.OnEditorActionListener() {
                public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                    if ((event != null && (event.getKeyCode() == KeyEvent.KEYCODE_ENTER)) || (actionId == EditorInfo.IME_ACTION_DONE)) {
                        dlg.onClick(dlg.getActionButton(DialogAction.POSITIVE));
                    }
                    return false;
                }
            });
        }
    }

Then use .showListener(new OnShowListener()) when building the dialog.

**Comment by Vall0n** [comment]
Hi @wizofaus 

If you want to close your dialog after the user  hits the Done or Enter Button call dialog.dismiss() or dlg.dismiss() in the onEditorAction.

```Java
class OnShowListener implements MaterialDialog.OnShowListener
{
    @Override
    public void onShow(DialogInterface dialog)
    {
        final MaterialDialog dlg = (MaterialDialog)dialog;
        dlg.getInputEditText().setOnEditorActionListener(new TextView.OnEditorActionListener() {
            public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                if ((event != null && (event.getKeyCode() == KeyEvent.KEYCODE_ENTER)) || (actionId == EditorInfo.IME_ACTION_DONE)) {
                    dialog.dismis(); // or alternativle dlg.dismiss()
                }
                return false;
            }
        });
    }
}

```

Hope it helps!

Best regards,

Vall0n

**Comment by wizofaus** [comment]
That doesn't trigger the callbacks you normally get when clicking OK



Sent from my Samsung GALAXY S5


-------- Original message --------

**Comment by PaulWoitaschek** [comment]
@wizofaus 
A better solution is to call the positive button on the dialog directly. That way you have all the necessary callbacks as well:

```java
View positiveButton = materialDialog.getActionButton(DialogAction.POSITIVE);
positiveButton.callOnClick(); // callOnClick so visual feedback wont be invoked
```
