### ISSUE TITLE
FileChooserDialog makes the go up item invisible when a folder is empty

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#1106]
Hi Aidan,

I found a bug in your FileChooserDialog code. When a folder has null content, the Dialog makes invisible the three dots to get back to the parent folder. 

That's why on [line 49](https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/java/com/afollestad/materialdialogs/folderselector/FileChooserDialog.java#L49), you should replace 

```java
return new String[]{};
``` 

with 

```java
return new String[]{"..."};
```

Regards,
Giuseppe Montuoro, Italy.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.1
