### ISSUE TITLE
how to remove top distance?

### ISSUE THREAD

**Issue by mahdimortazavi** [afollestad/material-dialogs#1113]
how to remove top distance?

![screenshot_20160629-210915](https://cloud.githubusercontent.com/assets/10667180/16460721/050ccc86-3e3e-11e6-86d5-0b66ef53836f.png)

`  boolean wrapInScrollView = true;
        new MaterialDialog.Builder(this)
                .customView(R.layout.dialogview, wrapInScrollView)
                .positiveText("باشه")
                .show();`

**Comment by erseno** [comment]
As far as I know you can only remove the top and bottom distance by having no .title and no buttons (.positive, .neutral and .negative)

**Comment by afollestad** [comment]
You can't, this library uses Material Design dialog specifications.

If you remove the action buttons and use a custom layout, it might remove the spacing though.
