### ISSUE TITLE
Circular indeterminate progress bar not working on Android 4.x

### ISSUE THREAD

**Issue by jfresen** [afollestad/material-dialogs#1116]
When showing a default indeterminate progress dialog (with the circular indeterminate progress bar), the progress bar is not shown.

Steps to reproduce:
1. Checkout commit 5d6179b from your project
2. Compile & run the sample app on one of the devices listed below (e.g., a Samsung Galaxy S4 Mini with Android 4.4.2)
3. Click on the button labeled "Progress dialog (indeterminate)"

See below for a list of devices on which the bug occurs and on which it doesn't occur. The screenshot below is taken on the Galaxy S4 Mini.

![screenshot_2016-06-30-21-43-18](https://cloud.githubusercontent.com/assets/445369/16502124/158248d2-3f0d-11e6-868b-ebbc6c7584b3.png)

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.1`

###### Bug present on the following devices:
- Samsung Galaxy Nexus (Android 4.3)
- Samsung Galaxy S3 (Android 4.3)
- Samsung Galaxy S4 Mini (Android 4.4.2)
- Samsung Galaxy Express (Android 4.1.2)
- Samsung Galaxy Tab 2 7.0 (CyanogenMod 11, Android 4.4.4)
- Samsung Galaxy Tab 2 10.1 (Android 4.2.2)
- Sony Xperia Z (Android 4.2.2)

###### Bug *not* present on the following devices:
- Samsung Galaxy SII Plus (Android 4.2.2)
- Samsung Galaxy S4 (Android 4.4.2)
- Samsung Galaxy Tab 3 10.1 (Android 4.4.2)
- Samsung Galaxy Note (CyanogenMod 11, Android 4.4.4)
- Samsung Galaxy Note 10.1 (Android 4.1.2)
- LG Optimus L7 (Android 4.0.3)
- LG Optimus 4X HD (Android 4.0.3)
- HTC One (Android 4.3)
- Asus MeMO Pad FHD10 (Android 4.3)

**Comment by rushilMethsof** [comment]
I am facing the same issue , using version "0.8.6.0" 
It was working few days ago but not anymore

**Comment by Johann673** [comment]
The progressBar use the AccentColor in your theme. Try to change this attribute, or you can redifined color for this dialog using: 
    `.widgetColorRes(R.color.your_progress_color)`

**Comment by rushilMethsof** [comment]
I did that , but its still the same , no progress animation whatsoever

**Comment by jfresen** [comment]
I tested the sample app on several more devices and added the result to the list in the issue description. I can't find any clear pattern, so it's a bit of a mystery to me.

**Comment by jfresen** [comment]
@rushilMethsof: on which device and with what android version did you see the bug?

**Comment by rushilMethsof** [comment]
API : 4.1.2
device: samsung , Model number : Gt-l18730
i havent verified the sample app yet , but I will do it soon let you know

**Comment by jfresen** [comment]
Thanks for following up! I'll add the device to the list of affected devices. It's the Samsung Galaxy Express, right? http://www.gsmarena.com/samsung_galaxy_express_i8730-5271.php

**Comment by rushilMethsof** [comment]
yes it is samsung galaxy express

**Comment by jfresen** [comment]
I ran another test this morning that puzzles me a bit. I happen to have access to two different Galaxy Tab 2 10.1's, running the same android version, having the same build number and the same kernel version. The only differences are the date they were bought (by about one or two years) and the language that is set (Dutch vs English).

I built the sample project on the commit described above, sent the same apk to both devices and guess what... The indeterminate progress bar shows on the tablet that is set to Dutch, but not on the tablet that is set to English.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.2

**Comment by jfresen** [comment]
My colleague has finally found the issue, and it is both embarrassing and understandable at the same time. The culprit is the developer option 'Animation duration scale' which was set to 'Animation off'. Setting this to 'Animation scale 1x' magically made the animation appear again on the S3 and the 'affected' Tab 2 10.1. Visa versa, setting it to 'Animation off' on some 'non-affected' devices, or even devices with a different Android version (e.g., Android 6.0.1), produced the same 'bug' on those devices.

I suggest to add a Known Issue or something similar to the readme and make everyone aware of the fact that this option causes several material widgets to 'vanish' (actually: stop the animation in the first completely transparent frame).

**Comment by rushilMethsof** [comment]
@jfresen :+1:  
yep Animation Scale 1x did the trick , salute for digging deeper to find a solution

**Comment by JerabekJakub** [comment]
Yes, I confirm that we see no progress bar on devices with Android 5 and Android 6. (Samsung S5 with Android 5 and Nexus 5 with Android 6.0.1)

So, is there a way how to show progress bar in progress dialog on Android >= 4.x? Thanks.

**Comment by SoloRobo** [comment]
@jfresen 
Exactly this issue and resolution myself, I had Animation duration scale: Animation scale off set in Developer options and this "broke" the progressBar Horizonal indeterminate true option on my Sony Xperia, displaying only the background tint with not foreground or progress bar itself being displayed.

Once I had set it back to 1x everything worked as expect.

I honestly thought it was an Xperia Android build issue, it was instead a developer bored of animation transitions issue.

**Comment by vijayanandkh** [comment]
I had disabled that option due to JUnit Testing code execution and felt this progress spinner is broken in my app. Did lot of analysis and hit this page. Thanks for reminding.
