### ISSUE TITLE
Changing dialog button color after dialog was created

### ISSUE THREAD

**Issue by sedestrian** [afollestad/material-dialogs#1117]
Hi, love your work, i wanted to ask you something, is there a way to change the positive, neutral and negative buttons' color after the dialog has been created? I need this because based on what is selected on a spinner everything in the dialog gets colored differently, i'm missing only the dialog button text now.
If not possible yet, could you add it please?
Thanks.

**Comment by afollestad** [comment]
Use `dialog.getActionButton(DialogAction)`
