### ISSUE TITLE
Marshmallow DatePicker is cutoff when dialog buttons are stacked.

### ISSUE THREAD

**Issue by erseno** [afollestad/material-dialogs#1120]
- Material Dialogs version: `0.8.5.6`
 - Device OS version: `6.0.1 API 23 Marshmallow`
 - Device Manufacturer: `Samsung`
 - Device Name: `Samsung S7`

Hello, I am making a material dialog with a custom view which contains a date picker widget

```java
  MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .customView(R.layout.partial_date_picker, false)
                .positiveText(positiveButtonText)
                .negativeText(negativeButtonText)
                .onAny(this)
                .title(dialogTitle)
                .neutralText(R.string.cancel)
                .build();
```

Note that the dialog is used in ```onCreateDialog``` and shown as a dialog fragment.

This is the layout of the custom view

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:gravity="center"
    android:orientation="vertical">

    <DatePicker
        android:layout_gravity="center"
        android:theme="@style/Date_Picker_Style"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/datePicker" />

</LinearLayout>
```

All works well however I noticed on the German locale, the text being a bit longer caused the buttons to stack which is good but then this causes the marshmallow date picker to be cutoff as seen in the screenshot below.

This is not an issue on lollipop and earlier because these date pickers scroll vertically but the marshmallow one does not, it just scrolls horizontally to go to the next month and attempts to fit the entire calendar in one view. 

###### Actual Result

![screenshot_20160628-171457](https://cloud.githubusercontent.com/assets/16024566/16610951/6ca46de6-4356-11e6-86f0-ee5e7c620e97.png)

Thanks for reading my issue and great job on the library, it has helped me out a lot!

**Comment by afollestad** [comment]
The fastest solution now would be to just disable button stacking.

**Comment by afollestad** [comment]
Looking into it now

**Comment by afollestad** [comment]
@erseno I added a date picker example to the sample project. Even if I force button stacking, I don't have any issues with it fitting vertically.

I tried it on my *Nexus 6P* and in a *Nexus 5X* emulator as seen here:

<img src="https://cloud.githubusercontent.com/assets/1820165/17489906/f67e9af4-5d65-11e6-813b-133b1e7f98b3.png" width="400px" />

**Comment by afollestad** [comment]
Maybe try running the sample project on your device? [Download the sample APK](https://github.com/afollestad/material-dialogs/raw/master/sample/sample.apk) @erseno

**Comment by erseno** [comment]
Hi apologies for the late reply. Thanks for adding the API to force unstacking the buttons.
I will give the sample a try on the Samsung S7

This is the solution I came up with in the meantime, it basically checks if the buttons are stacked and uses short versions of strings. 

```java
public void setShortActionBtnText(@NonNull MaterialDialog materialDialog,
                                      @StringRes int positiveBtnShortRes,
                                      @StringRes final int negativeBtnShortRes,
                                      @StringRes final int neutralBtnShortRes) {

        mPositiveBtnShortRes = positiveBtnShortRes;
        mNegativeBtnShortRes = negativeBtnShortRes;
        mNeutralBtnShortRes = neutralBtnShortRes;

        materialDialog.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialog) {
                MaterialDialog materialDialog = ((MaterialDialog) dialog);
                //We check if the button is stacked by checking if the width of the button is more than half of the dialog
                //which is only possible if the button is stacked.

                //We get the positive button as it is something that every dialog should have so we check this
                MDButton positiveButton = materialDialog.getActionButton(DialogAction.POSITIVE);

                if (positiveButton.getWidth() > (materialDialog.getWindow().getDecorView().getWidth() / 2)) {
                    if (mPositiveBtnShortRes != 0) {
                        positiveButton.setText(mPositiveBtnShortRes);
                    }

                    if (mNegativeBtnShortRes != 0) {
                        materialDialog.getActionButton(DialogAction.NEGATIVE).setText(negativeBtnShortRes);
                    }

                    if (mNeutralBtnShortRes != 0) {
                        materialDialog.getActionButton(DialogAction.NEUTRAL).setText(neutralBtnShortRes);
                    }
                }
            }
        });
    }
```

**Comment by afollestad** [comment]
Did you check what I listed above? I have no issues, even with button stacking

**Comment by erseno** [comment]
I do not have the Samsung S7 to test this at the moment but I will let you know my findings.

The only difference from the image you posted is that all 3 buttons (positive, neutral and negative) should be present.

**Comment by Igor-Baimastruc-Technosoft** [comment]
Hi, the issue is reproduced on lower resolution screens event without buttons stacking.
I have Galaxy XCover 3 (480 x 800 pixels (~207 ppi pixel density)) running Android OS 6.0.1
![screenshot_1479917353](https://cloud.githubusercontent.com/assets/18304005/20569355/1e5d5112-b1a0-11e6-8da5-a4fa74d54e4b.png)

**Comment by runev** [comment]
+1 and support for report by @Igor-Baimastruc-Technosoft 

We had a similar report from a customer using a Samsung Galaxy Xcover 3 running Android 6.0.1.

I've been able to reproduce the issue using the emulator with the Nexus One hardware profile (3.7", 480x800, API 23). It seems to me that resolution is the issue, and stacked button just takes up more place in the dialog, making the issue easier to reproduce. 

<img width="240" alt="1120" src="https://cloud.githubusercontent.com/assets/1909936/22283745/2e6d7a08-e2e4-11e6-85b9-6ab258d17b0d.PNG">

**Comment by meizi88** [comment]
same problem above , samsung and oppo has same problem
