### ISSUE TITLE
How to change the text size of the dialog content, title, and buttons?

### ISSUE THREAD

**Issue by marvinmosa** [afollestad/material-dialogs#1121]
I am trying to change the size of the textview based on the screensize and it seems that I cannot manipulate the text size of the texts found in the dialog.

**Comment by afollestad** [comment]
You can't, this library intends to follow the Material Design guidelines.

**Comment by DingZugeng** [comment]
you can do it like:
`dialog.getActionButton(DialogAction.NEGATIVE).setTextSize(18);`
It works
