### ISSUE TITLE
Divider below title

### ISSUE THREAD

**Issue by oalpayli** [afollestad/material-dialogs#1125]
Hi, I'm using library for my Alert Dialog in my app. Everything is fine for me but divider. I want a divider below title and icon. Can we do this? Is it possible? Please help me

**Comment by deniztuna** [comment]
You can use a custom layout for that purpose. For example you can use following piece for assigning a custom layout to your dialog. On your custom dialog simply create your needs as usual.
`final MaterialDialog.Builder builder = new MaterialDialog.Builder(ctx);
        builder.customView(layoutID, false);`

If you want to reach out your custom views afterwards, you can directly use dialog itself to reach views as follows:

`Button yourButton = (Button) yourDialog.getView().findViewById(R.id.yourButton);`

**Comment by oalpayli** [comment]
Ok Thank You. I will try customview.
