### ISSUE TITLE
Some trouble with MIME type JSON

### ISSUE THREAD

**Issue by artests87** [afollestad/material-dialogs#1131]
Hello!
I use ".mimeType" for fileChooserDialog.
But my files are invisible.
Without ".mimeType" all files are visible.
Thanks.

**Comment by afollestad** [comment]
The only thing I can think of is that you're using the wrong value for the MIME type. 

JSON is `application/json`

**Comment by artests87** [comment]
Unfortunately, MIME type is right.

2016-07-20 21:18 GMT+03:00 Aidan Follestad <notifications@github.com>:

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.0 should help
