### ISSUE TITLE
problem with importing the repository

### ISSUE THREAD

**Issue by zhangqiang9** [afollestad/material-dialogs#1132]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. i import the repository to my project in android studio
2. compile 'com.afollestad.material-dialogs:core:0.8.6.2'
3. buid project and run it

###### Expected Result
show the dialogs in my application

###### Actual Result
but in monitor,it logs:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fengshou.hellochartsapplication/com.fengshou.hellochartsapplication.activity.intro.MyIntro}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.

can you help me?
my build.gradle :
classpath 'com.android.tools.build:gradle:1.5.0'
...........
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:support-v4:23.1.1'

**Comment by afollestad** [comment]
The latest version of the Support library and AppCompat are 24.1.0. You need to use the same version that this library uses, otherwise you will have problems like that.

**Comment by afollestad** [comment]
There's also a much newer version of the Gradle plugin, `2.1.0` I believe.

**Comment by zhangqiang9** [comment]
i use the settings,
classpath 'com.android.tools.build:gradle:2.1.0'
......
compile 'com.android.support:appcompat-v7:24.1.0'
compile 'com.android.support:support-v4:24.1.0'

it does not work.Also throw the exception.

**Comment by cha25228** [comment]
issue
