### ISSUE TITLE
Add prefixes for library ids

### ISSUE THREAD

**Issue by bejibx** [afollestad/material-dialogs#1134]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

 - Material Dialogs version: `0.8.6.2`
 
Hi! First of all thank you for this great library, I'm really enjoy using it, but today I had 2 hours trying to find out why my dialogs content not showing in my new project. It turns out thats because R.id.content id defined both in my project and in your library. Project resources have priority over library resources, so when dilog tries to find content TextView, nothing found and no content shown as result. I'll suggest you to either to use default android ids (android.R.id.content), or to use prefix for your ids (R.id.md_content) to prevent such problems on others.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.0

**Comment by bejibx** [comment]
Great job, thank you!
