### ISSUE TITLE
Single choice list dialog last item doesn't animate.

### ISSUE THREAD

**Issue by faelmorais** [afollestad/material-dialogs#1136]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.

 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G4`
 - Device nº2: `Genymotion Emulator`
 - Device nº2 OS version: `5.1.0`

In a Single choice list dialog, the last radio button of the list doesn't animate when checked or unchecked. 

```java
String[]choices = {"First","Second","Third"};
new MaterialDialog.Builder(this)
                .title("Excluir")
                .items(choices)
                .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, View itemView, int which, CharSequence text) {
                        return false;
                    }
                })
                .positiveText("Ok")
                .negativeText("Cancel")
                .show();

```

**Comment by afollestad** [comment]
The next release will include a fix for this

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.1
