### ISSUE TITLE
Issue with Limiting Input Length in Input Dialog

### ISSUE THREAD

**Issue by abhinituk** [afollestad/material-dialogs#1139]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `Android 5.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto E- XT1044`

Also, please wrap Java with correct syntax highlighting.

```java
inputRangeRes(2, 20, R.color.material_red_500)
```
 
###### Reproduction Steps

1. Enter some text in input dialog with inputRangeRes defined.
2. Erase the text in input dialog
3. Now the positive text button is enabled even if we have defined input range.

###### Expected Result
After setting the input range,if I erase the text inside the input dialog , it should follow the input range defined.

###### Actual Result
After setting the input range,it works well but if I erase the input totally so positive text button  becomes enabled even if I have defined the input range.
![device-2016-08-09-125845](https://cloud.githubusercontent.com/assets/13062075/17508132/205c7848-5e31-11e6-866a-dd1132567499.png)
![device-2016-08-09-125906](https://cloud.githubusercontent.com/assets/13062075/17508142/2745751a-5e31-11e6-87d8-77c655a4a931.png)

**Comment by abhinituk** [comment]
inputRangeRes(2, 20, R.color.material_red_500)  works well initially but once I have given some input & then erasing the input causes the input dialog to its default behaviour.

**Comment by afollestad** [comment]
I'm unable to reproduce any problems with this.

There's actually usage of `inputRange` in the sample project, it works fine there too.

**Comment by abhinituk** [comment]
Link: [https://github.com/abhinituk/StockHawk/blob/Detail_Activity_Implementation/app/src/main/java/com/sam_chordas/android/stockhawk/ui/MyDialogFragment.java](url)

You can have a look at it. Material dialog has default behaviour if we erase the input. 
If you wish, you can clone repo & run the project to reproduce the error.

[https://github.com/abhinituk/StockHawk/tree/Detail_Activity_Implementation](url)

**Comment by afollestad** [comment]
It looks like that may be a private repo, it returns a 404

**Comment by abhinituk** [comment]
It's a private repo which I have forked from Udacity GitHub.If you wish I can mail you the complete project zip file with detailed information to reproduce the error.

**Comment by afollestad** [comment]
Well, I probably won't be able to see much more there.

As long as you're using a newer version of the library, it should work. It's worked fine with in all of the apps I use it in.

**Comment by abhinituk** [comment]
I am using the latest version of the library but still the problem exists. I have updated the comment which shows that positive text button is disabled earlier but when I write some input & erase the input, positive text button is enabled. 
For more information please see the project: 
[StockHawk.zip](https://github.com/afollestad/material-dialogs/files/408389/StockHawk.zip)

**Comment by afollestad** [comment]
I'm still unable to reproduce any issues with this in the sample project, or any of my applications.

When the input becomes empty, the button disables correctly for me.

**Comment by afollestad** [comment]
I've made a small change which may help, though.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.1

**Comment by abhinituk** [comment]
Still the issue exist after updating the library version.

**Comment by afollestad** [comment]
Well, I'm still unable to reproduce any issues so it must be on your end.

**Comment by abhinituk** [comment]
`public class MyDialogFragment extends DialogFragment {
    private static final String TAG = "tag";
    private static final String ADD = "add";
    private static final String SYMBOL = "symbol";
    private final String LOG_TAG = getClass().getSimpleName();
    private String mInputSymbol;
    private Intent mServiceIntent;

    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {

        MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .title(R.string.symbol_search)
                .content(R.string.content_test)
                .inputRange(1, 20)
                .inputType(InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS)
                .positiveText(R.string.positive_text)
                .negativeText(R.string.negative_text)
                .alwaysCallInputCallback()
                .input(R.string.input_hint, R.string.input_prefill, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {

                        if (input.toString().contains(" ")) {
                            dialog.setContent(R.string.whitespace);
                            dialog.getActionButton(DialogAction.POSITIVE).setEnabled(false);
                        } else {
                            dialog.setContent(R.string.content_test);
                            dialog.getActionButton(DialogAction.POSITIVE).setEnabled(true);
                            mInputSymbol = input.toString();

                        }
                    }
                })

                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        Cursor c = getActivity().getContentResolver().query(QuoteProvider.Quotes.CONTENT_URI,
                                new String[]{QuoteColumns.SYMBOL}, QuoteColumns.SYMBOL + "= ?",
                                new String[]{mInputSymbol}, null);
                        if ((c != null ? c.getCount() : 0) != 0) {
                            Toast toast =
                                    Toast.makeText(getActivity(), R.string.stock_already_saved,
                                            Toast.LENGTH_LONG);
                            toast.setGravity(Gravity.CENTER, Gravity.CENTER, 0);
                            toast.show();
                            return;
                        } else {
                            // Add the stock to DB
                            mServiceIntent = new Intent(getActivity(), StockIntentService.class);
                            mServiceIntent.putExtra(TAG, ADD);
                            mServiceIntent.putExtra(SYMBOL, mInputSymbol);
                            getActivity().startService(mServiceIntent);
                        }
                        if (c != null) {
                            c.close();
                        }
                    }
                })
                .build();

        return dialog;
    }
}
`

**Comment by abhinituk** [comment]
Please have a look at DialogFragment class which I am using.

**Comment by afollestad** [comment]
It's not an issue with this library.

You're manually enabling the submit button inside of `onInput`.

@abhinituk

**Comment by afollestad** [comment]
`.alwaysCallInputCallback()` makes `onInput` get invoked everytime you modify the input.

**Comment by abhinituk** [comment]
Alright @afollestad , Thanks for helping me out.
