### ISSUE TITLE
Espresso2 is unable to click on button

### ISSUE THREAD

**Issue by mikegr** [afollestad/material-dialogs#1140]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Emulator: Nexus9

###### Reproduction Steps

Espresso Test 
```java
onView(withText("Open Dialog")).perform(click());
onView(withText("OK")).perform(click());
onView(withText("AfterDialog")).check(matches(isDisplayed())
```

Activity which starts dialog
```java
new MaterialDialog.Builder(this)
                .title("Title")
                .content("Content")
                .positiveText("OK")
                .negativeText("Cancel")
                .onPositive((dialog, which) -> {
                    onPositiveCallback(); 
                })
                .cancelable(false)
                .show();
```

###### Expected Result
Dialog is dismissed. 

###### Actual Result
Dialog is not dismissed and test fails.

This works with a Nexus5 emulator and works with a AlertDialog. 

```java
new AlertDialog.Builder(this)
                .setTitle(R.string.block_card_confirmation_title)
                .setMessage(R.string.block_card_confirmation_message)
                .setPositiveButton(R.string.block_card_confirmation_ok, (dialog, which) -> {
                    blockCard(email);
                })
                .setNegativeButton(R.string.block_card_confirmation_cancel, (dialog, which) -> {
                    dialog.dismiss();
                })
                .setCancelable(false)
                .show();
```
Any ideas?

**Comment by afollestad** [comment]
I don't use Expresso but you're probably targeting the wrong view.

**Comment by mikegr** [comment]
I tracked down the reason why AlertDialog from the support library works. 
The Dialog is calling:
Window.setFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM,WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
I have no idea why this flag is required to set.

**Comment by afollestad** [comment]
It sounds like the button may just not be focusable?
