### ISSUE TITLE
Issue with CollapsingToolbarLayout, Runtime Exception: cannot inflate CollapsingTollbarLayout

### ISSUE THREAD

**Issue by gubaju** [afollestad/material-dialogs#1141]
- [✓] I have verified there are no duplicate active or recent bugs, questions, or requests
- [✓] I have verified that I am using the latest version of Material Dialogs.
- [✓] I have given my issue a non-generic title.
- [✓] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `4.4.2`
 - Device Manufacturer: `Huawei`
 - Device Name: `Mediapad T1`

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{}: android.view.InflateException: Binary XML file line #21: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2347) 
Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class android.support.design.widget.CollapsingToolbarLayout

Caused by: java.lang.reflect.InvocationTargetException

Caused by: java.lang.NoSuchMethodError: android.support.v4.graphics.drawable.DrawableCompat.setLayoutDirection
```

**Comment by afollestad** [comment]
None of that is related to code in this library.

**Comment by gubaju** [comment]
it is infact a library issue. Collapsing toolbar works when i remove the library dependency from app.gradle.

**Comment by afollestad** [comment]
Well, it's not; the log does reference anything in my library. 

But, I'm guessing it's because you're using a version of AppCompat or the Support Library that doesn't match the version which this library uses.

**Comment by gubaju** [comment]
Ok, i'll check it out. Thank you for the quick response
