### ISSUE TITLE
When dialog is dismissed by button, it leaves a artifact behind

### ISSUE THREAD

**Issue by Berlon** [afollestad/material-dialogs#1143]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S6 `

Also, please wrap Java with correct syntax highlighting.

```
 new MaterialDialog.Builder(ExportDialog.this)
                                        .autoDismiss(true)
                                        .title("Backup as CSV File")
                                        .content("I would like to backup ...")
                                        .positiveText("Recipes only")
                                        .negativeText("Flavors only")
                                        .neutralText("All")
                                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSV();//Recipes
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Positive", Toast.LENGTH_LONG).show();
                                            }
                                        })
                                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSV2();//Flavors
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Negative", Toast.LENGTH_LONG).show();
                                            }
                                        })
                                        .onNeutral(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSVAll();//Both
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Neutral", Toast.LENGTH_LONG).show();
                                            }
                                        })

                                        .show();
```
 
###### Reproduction Steps

1. Call Material Dialog,
2. Call any Negative, Positive or Neutral button,
3. Material Dialog dismiss's automatically and leaves behind an artifact.

###### Expected Result

Material Dialog should dismiss completely

###### Actual Result

Screenshot:
![screenshot_20160807-055928 1](https://cloud.githubusercontent.com/assets/5912418/17462545/bec3c2a2-5c65-11e6-9b51-080e6a3ac892.png)

**Comment by afollestad** [comment]
I've never run into this issue or had any reports of it so I'm assuming it's another infamous Samsung related issue.

**Comment by Berlon** [comment]
Thanks for the reply. I have heard back from my users and it is also in LG G4, G3 and V10 and HTC M One and Asus Nexus 7.

**Comment by afollestad** [comment]
Well, unfortunately there's probably not much I can do.

All the `dismiss()` code is in Google's `android.app.Dialog` class.

**Comment by Berlon** [comment]
I have a little more information. I have narrowed it down to the nested dialog's. 

`public class ExportDialog extends AppCompatActivity {
    private DatabaseManager mDbHelper;
    private int STORAGE_PERMISSION_CODE = 23;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fabric.with(this, new Crashlytics());
        Fabric.with(this);
        Fabric.with(this, new Answers());
        mDbHelper = new DatabaseManager(this);
        mDbHelper.open();
        //First checking if the app is already having the permission
        if (isReadStorageAllowed()) {
            //If permission is already having then showing the toast
            new MaterialDialog.Builder(this)
                    .autoDismiss(true)
                    .title("Backup Utility")
                    .content("Backup as a Database File which is not editable or as a CSV File that can be edited. If you are not familiar with CSV choose Database File.")
                    .positiveText("As DB File")
                    .negativeText("As CSV File")
                    .onPositive(new MaterialDialog.SingleButtonCallback() {
                        @Override
                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                            new MaterialDialog.Builder(ExportDialog.this)
                                    .title("Backup as Database File")
                                    .content("This will backup the entire database of Recipes and Flavors. The file will be located on your devices storage in a file called ejuice as \"data\".")
                                    .positiveText("Backup Now")
                                    .onPositive(new MaterialDialog.SingleButtonCallback() {
                                        @Override
                                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                            if (Environment.getExternalStorageState().equals(
                                                    Environment.MEDIA_MOUNTED)) {

                                                exportdb();// Loads the list

                                            } else if (Environment.getExternalStorageState().equals(
                                                    Environment.MEDIA_UNMOUNTED)) {
                                                Toast.makeText(ExportDialog.this, "External storage is not available, unable to export data.",
                                                        Toast.LENGTH_SHORT).show();
                                            }
                                            finish();
                                        }
                                    })
                                    .show();
                        }
                    })
                    .onNegative(new MaterialDialog.SingleButtonCallback() {
                        @Override
                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                            new MaterialDialog.Builder(ExportDialog.this)
                                    .autoDismiss(true)
                                    .title("Backup as CSV File")
                                    .content("I would like to backup ...")
                                    .positiveText("Recipes only")
                                    .negativeText("Flavors only")
                                    .neutralText("All")
                                    .onPositive(new MaterialDialog.SingleButtonCallback() {
                                        @Override
                                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                            exportCSV();
                                            dialog.dismiss();
                                        }
                                    })
                                    .onNegative(new MaterialDialog.SingleButtonCallback() {
                                        @Override
                                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                            exportCSV2();
                                            dialog.dismiss();
                                        }
                                    })
                                    .onNeutral(new MaterialDialog.SingleButtonCallback() {
                                        @Override
                                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                            exportCSVAll();
                                            dialog.dismiss();
                                        }
                                    })

                                    .show();
                        }
                    })

                    .show();
            //Toast.makeText(Export.this, "You already have the permission", Toast.LENGTH_LONG).show();
            //Existing the method with return
            return;
        } else {
            requestStoragePermission();
        }
    }

    //We are calling this method to check the permission status
    private boolean isReadStorageAllowed() {
        //Getting the permission status
        int result = ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE);

        //If permission is granted returning true
        if (result == PackageManager.PERMISSION_GRANTED)
            return true;

        //If permission is not granted returning false
        return false;
    }

    //Requesting permission
    private void requestStoragePermission() {

        if (ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.READ_EXTERNAL_STORAGE)) {
            //If the user has denied the permission previously your code will come to this block
            //Here you can explain why you need this permission
            //Explain here why you need this permission
        }

        //And finally ask for the permission
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, STORAGE_PERMISSION_CODE);
    }

    //This method will be called when the user will tap on allow or deny
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {

        //Checking the request code of our request
        if (requestCode == STORAGE_PERMISSION_CODE) {

            //If permission is granted
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                new MaterialDialog.Builder(this)
                        .autoDismiss(true)
                        .cancelable(false)
                        .title("Backup Utility")
                        .content("Backup as a Database File which is not editable or as a CSV File that can be edited. If you are not familiar with CSV choose Database File.")
                        .positiveText("As DB File")
                        .negativeText("As CSV File")
                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                new MaterialDialog.Builder(ExportDialog.this)
                                        .autoDismiss(true)
                                        .cancelable(false)
                                        .title("Backup as Database File")
                                        .content("This will backup the entire database of Recipes and Flavors. The file will be located on your devices storage in a file called ejuice as \"data\".")
                                        .positiveText("Backup Now")
                                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                if (Environment.getExternalStorageState().equals(
                                                        Environment.MEDIA_MOUNTED)) {

                                                    exportdb();// Loads the list

                                                } else if (Environment.getExternalStorageState().equals(
                                                        Environment.MEDIA_UNMOUNTED)) {
                                                    Toast.makeText(ExportDialog.this, "External storage is not available, unable to export data.",
                                                            Toast.LENGTH_SHORT).show();
                                                }
                                                finish();
                                            }
                                        })
                                        .show();
                            }
                        })
                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                                new MaterialDialog.Builder(ExportDialog.this)
                                        .autoDismiss(true)
                                        .cancelable(false)
                                        .title("Backup as CSV File")
                                        .content("I would like to backup ...")
                                        .positiveText("Recipes only")
                                        .negativeText("Flavors only")
                                        .neutralText("All")
                                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSV();//Recipes
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Positive", Toast.LENGTH_LONG).show();
                                                finish();
                                            }
                                        })
                                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSV2();//Flavors
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Negative", Toast.LENGTH_LONG).show();
                                            }
                                        })
                                        .onNeutral(new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                exportCSVAll();//Both
                                                dialog.dismiss();
                                                Toast.makeText(ExportDialog.this, "Neutral", Toast.LENGTH_LONG).show();
                                            }
                                        })
                                        .show();
                            }
                        })

                        .show();
                //Displaying a toast
                // Toast.makeText(this, "Permission granted now you can read the storage", Toast.LENGTH_LONG).show();
            } else {
                //Displaying another toast if permission is not granted
                new MaterialDialog.Builder(this)
                        .autoDismiss(true)
                        .cancelable(false)
                        .title("Oops, Permissions Denied!")
                        .content("By denying permissions, you will not be able to backup or restore your Recipes and Flavors list to the SDCard.")
                        .positiveText("Grant Permissions")
                        .negativeText("Cancel")
                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();

                            }
                        })
                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                                requestStoragePermission();
                            }
                        })
                        .show();
                //Toast.makeText(this, "Oops you just denied the permission", Toast.LENGTH_LONG).show();
            }
        }
    }
`
Maybe this will help? Thanks for a great library! and all your efforts.

**Comment by afollestad** [comment]
You don't need to manually call `dialog.dismiss()` in the button callbacks when `autoDismiss()` is on (it's on by default, too, so no need to call `autoDismiss(true)`).

**Comment by afollestad** [comment]
I don't think that's the cause, but you might want to check just in case

**Comment by Berlon** [comment]
OK, I removed all the calls to dismiss.dialog, autodismiss() removed all the nested dialogs to there own private void. I still get the artifact.

**Comment by afollestad** [comment]
That's so weird; I've never experienced that issue ever on stock Android.

**Comment by Berlon** [comment]
afollestad,
I found the issue, but I do not know how to fix it. The activity is being called from a preference screen which had a theme set to it. I removed the theme and the artifact is gone. But the preference screen is no longer there.

**Comment by afollestad** [comment]
Ohh, yeah, your Activities need to inherit AppCompatActivity.

Checkout the sample project, I have an `AppCompatActivity` in there that displays preferences like a `PreferenceScreen` would.
