### ISSUE TITLE
All radio buttons will be in unseleted state when click fast on single choice dialog list items

### ISSUE THREAD

**Issue by ibrahim132** [afollestad/material-dialogs#1144]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.0`
 - Device OS version: `4.4.2`
 - Device Manufacturer: `Samsung`
 - Device Name: `Note II`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. Show single choice dialog.
2. Click fast on list items.
3. All radio buttons will be in unselected state.

###### Expected Result
![screenshot_2016-08-09-14-17-43](https://cloud.githubusercontent.com/assets/14311615/17516141/54d1e5ae-5e45-11e6-8b37-899021adf7eb.png)

###### Actual Result
![screenshot_2016-08-09-14-17-49](https://cloud.githubusercontent.com/assets/14311615/17516142/54f80e14-5e45-11e6-8c70-90392fb65a47.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.0.1
