### ISSUE TITLE
ContextThemeWrapper cannot be converted to Callback

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#1145]
Hi,

I'm using the latest version of this library but there is a problem with my MaterialSimpleListAdapter. The `ContextThemeWrapper` doesn't work anymore. Below there is the error:

```
Error:(207, 85) error: incompatible types: ContextThemeWrapper cannot be converted to Callback
```

Below the code:
```java

MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(new ContextThemeWrapper(getActivity(), mDialogTheme));

```

The code was working until version `0.8.6.2` of your library. Any solution? Thanks.

**Comment by afollestad** [comment]
I mentioned a change to that class in the release notes. 

Check the documentation, it no longer accepts a Context in the constructor.
