### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by msay2** [afollestad/material-dialogs#1146]
Hello,

Is it possible to change the buttons to their background Sign `?android:attr/selectableItemBackgroundBorderless`

as it below : 

![screenshot_20160809-193959](https://cloud.githubusercontent.com/assets/19941384/17527246/dcc591b6-5e6a-11e6-9285-78968d772b65.png)

**Comment by afollestad** [comment]
You'll need to create custom button selectors, which is explained in the tutorial.

Please use more specific titles for issues, like the issue template says.

**Comment by msay2** [comment]
Sorry I'm new to Github and I do not have the habit. Merci for your reply
