### ISSUE TITLE
how to customize the style

### ISSUE THREAD

**Issue by Bertkiing** [afollestad/material-dialogs#1147]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
Now I want to realize the dialog of circle cornor ,but ...
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
You left pretty much the whole issue template blank and I don't really understand your description. 

But any customization that's possible is listed in the tutorial.
