### ISSUE TITLE
Question : Using Custom View containing a <fragment>

### ISSUE THREAD

**Issue by thibautd** [afollestad/material-dialogs#1149]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Dialogs.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

Hello,

I'm trying to use a custom view which contains a `<fragment>`, but I'm not able to obtain a reference to the fragment instance. My fragment's` onCreate()` method is called when the view is inflated, but when I try to call `getFragmentManager()` to get the instance after using `build()` it doesn't work (fragment not found).

I tried to manually add the fragment using `getChildFragmentManager().begintransaction().add().commit()`  after the `MaterialDialog.Builder.build() `call, but in this case my fragment's onCreate() method is never called.

I dodn't find an example involving a custom view and a fragment in the sample project. If you have an idea of the correct way to do this, I would be glad to hear it.

PS: Thanks a lot for your very good work !

**Comment by afollestad** [comment]
Unfortunately I don't know of any methods to make `Fragment`'s in `Dialog`'s work well.

I'm guessing `getFragmentManager()` doesn't work because the `Fragment` needs to attach to an `Activity` rather than a `Dialog`.

**Comment by thibautd** [comment]
Thanks for your answer I will do it differently !
