### ISSUE TITLE
Unselected Radio Buttons are white colored on Light Theme

### ISSUE THREAD

**Issue by ZangeTsune** [afollestad/material-dialogs#1153]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. Make Single Choice List Dialog on Material Dialogs version: `0.8.6.2`
2. Change Material Dialogs version to: `0.9.0.0`

###### Expected Result

![device-2016-08-12-091300](https://cloud.githubusercontent.com/assets/11486015/17615306/a34a490e-606d-11e6-8c0b-61f808d91396.png)

###### Actual Result

![device-2016-08-12-091721](https://cloud.githubusercontent.com/assets/11486015/17615310/a685a4ec-606d-11e6-802a-8ef361f0c208.png)

**Comment by afollestad** [comment]
I've experienced no issues here.

The color of unchecked radio buttons is derived from `R.attr.colorControlNormal`. You may want to check if you're overriding that in your `Activity` theme.

Your `Activity` theme also needs to be derived from the AppCompat themes.

**Comment by abcghy** [comment]
I had the same problem before. And my `textColorSecondary` was `#FFFFFF`. I changed it and it worked.

**Comment by riadhnet** [comment]
same happen with me, i can't change , when i change 
  <item name="colorControlNormal">@color/white</item>
it changes , but i can't do this for my theme, because this will change other component colors too, 
any way to change this only for the radio button ?
