### ISSUE TITLE
Input Dialog prefill text twice

### ISSUE THREAD

**Issue by pawankumar01** [afollestad/material-dialogs#1157]
Using input dialog, while giving the prefill String. It prefill's the edit text but on first keyboard stroke, it prefill the value again.

I am using  'com.afollestad.material-dialogs:core:0.9.0.0'

Kindly resolve the issue.

**Comment by afollestad** [comment]
Unable to reproduce.

**Comment by afollestad** [comment]
Also, please follow the issue template for future issues, it's there for a reason.

**Comment by pawankumar01** [comment]
Sorry for not using the template.
I am using the following code.

```
new MaterialDialog.Builder(getActivity())
                .title("Change Name")
               .inputRangeRes(2, 20, R.color.red)
                .inputType(InputType.TYPE_CLASS_TEXT |
                       InputType.TYPE_TEXT_VARIATION_PERSON_NAME)
                .input(null,  PreferenceUtil.getInstance().getUserName(),
                        false,
                        new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(MaterialDialog dialog, CharSequence input) {
                        if(input == null || input.equals("")){
                            dialog.getActionButton(DialogAction.POSITIVE).setEnabled(false);
                        }else{
                            PreferenceUtil.getInstance().setUserName(input.toString());
                            profileName.setText(input);
                            dialog.dismiss();
                        }
                    }
                }).show();
```

![screenshot 2](https://cloud.githubusercontent.com/assets/8166061/17645204/b2fb3afc-616c-11e6-805c-df36c5f778ba.png)

And on Pressing K, the result becomes

![screenshot 1](https://cloud.githubusercontent.com/assets/8166061/17645205/bfaa2d62-616c-11e6-9757-9793922b3127.png)

Pawan becomes **PawanPawan**


Thanks,
Pawan

**Comment by afollestad** [comment]
I'm looking into it now.

One thing, though: checking if the text is empty is unnecessary. You set the input range to have a minimum of 2, the submit button will be disabled by the library automatically.

**Comment by afollestad** [comment]
Also, with your configuration, `onInput` isn't called until the user presses the submit button with valid input. So that code block is unnecessary.

**Comment by afollestad** [comment]
I'm still unable to reproduce any problems with 0.9.0.0 or 0.9.0.1 of this library on stock Android.

I don't think this is a library issue.
