### ISSUE TITLE
A proper way to get the buttons close when the buttonsGravity is center

### ISSUE THREAD

**Issue by KyleXie** [afollestad/material-dialogs#1159]
- [ ✓ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ✓ ] I have verified that I am using the latest version of Material Dialogs.
- [ ✓ ] I have given my issue a non-generic title.
- [ ✓ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.0`
 - Device OS version: `5.1`
 - Device Manufacturer: `Sony`
 - Device Name: `Sony Z3 compact`

Also, please wrap Java with correct syntax highlighting.
 
After I set the `buttonsGravity` to `GravityEnum.CENTER`, I found the negative button and position button aligned to left and right, there's a lot white space between them, the margin between them changed. See the image in the Actual Result & Expected Result parts. I think maybe it's better to make them a little compact.

I read the code about this part and found that when it's "center", it's actually align the negative button left and positive button right, not count from the real center and place the buttons on the two sides. When the dialog getting wider, it getting even stranger.

Is there any reason that we implemented it the current way?   Do you guys mind if I change it to the way I expected?

###### Reproduction Steps

Just create a MaterialDialog, set positive button, negative button and also set the `contentGravity` to `GravityEnum.CENTER`.

###### Expected Result

![image](https://cloud.githubusercontent.com/assets/2870241/17731809/9c9ae7a2-64a1-11e6-80b4-5b45bd799add.png)

###### Actual Result

![image](https://cloud.githubusercontent.com/assets/2870241/17731648/af7fd608-64a0-11e6-8aac-8df8e773ee3b.png)

**Comment by afollestad** [comment]
The way it works currently is what's intended.

See this: https://github.com/afollestad/material-dialogs#gravity
