### ISSUE TITLE
MD library demo -  Overscroll effect visible in non  scrollable content

### ISSUE THREAD

**Issue by dsbl41** [afollestad/material-dialogs#1163]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [x ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.1`
 - Device OS version: `5.1`
 - Device Manufacturer: `OnePlus `
 - Device Name: `1`
 
###### Reproduction Steps

1. Open the MD library demo app
2. Click on the button "Basic list"  
3. Drag up and down on the list items 

###### Expected Result
There should be no overscroll effect 

###### Actual Result
The overscroll effect appears
![screenshot_2016-08-26-02-43-33](https://cloud.githubusercontent.com/assets/19982103/17990576/66882296-6b37-11e6-896c-17d080b08b25.png)

![screenshot_2016-08-26-02-48-10](https://cloud.githubusercontent.com/assets/19982103/17990624/b527dc3e-6b37-11e6-884d-4364e9edba09.png)

Thanks. ☺

**Comment by afollestad** [comment]
That's Android behavior, not a bug.
