### ISSUE TITLE
java.lang.NoClassDefFoundError for my own package class ? on pre lollipop Devices

### ISSUE THREAD

**Issue by khalid-mahmood** [afollestad/material-dialogs#1168]
Also happen for other dependencies too...
What is Solution for Pre Lollipop Devices ?

**Comment by khalid-mahmood** [comment]
Strange behavior after add MD

**Comment by afollestad** [comment]
Usually that means you have Proguard enabled and have to add the class to Proguard exclusions.

**Comment by khalid-mahmood** [comment]
Not using Proguard..
