### ISSUE TITLE
VM with version 1.6.0 does not have multidex support

### ISSUE THREAD

**Issue by prsnt558908** [afollestad/material-dialogs#1170]
- Material Dialogs version: `0.9.0.1`
- Device OS version: `4.4.2`
- Device Manufacturer: `MI xiaomi`
- Device Name: `Xiaomi Redmi note 4`

I have multidex enabled in my project.
When I tried to import and use core as a dependency from gradle, it gave the following error 
**VM with version 1.6.0 does not have multidex support**
Any ideas around this ?

**Comment by afollestad** [comment]
Sorry, I've never seen that before and have no idea what it means.
