### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by edwinwu2014** [afollestad/material-dialogs#1172]
I really like this library, but when my project contains
compile 'com.android.support:design:23.3.0' and compile 'com.afollestad.material-dialogs: core: 0.9.0.1'
I can not run the project, the question is Caused by: android.view.InflateException: Binary XML file line # 17: Error inflating class android.support.design.widget.CollapsingToolbarLayout

**Comment by afollestad** [comment]
This library isn't updated for 23.3.0 yet. Your app has to use a matching version, or exclude the version used on this library from your Gradle file.

**Comment by afollestad** [comment]
Oh you're using an old version, actually. You need to use 24.x.
