### ISSUE TITLE
No radio buttons on Single Choice List Dialogs

### ISSUE THREAD

**Issue by pedrofraga** [afollestad/material-dialogs#1174]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Material Dialogs version: `0.9.0.1`
- Device OS version: `6.0.1`
- Device Manufacturer: `LG`
- Device Name: `Nexus 5`

When I'm using the latest version of this project there are no radio buttons on Single Choice List Dialogs, the problem was solved after downgrading to 0.8.6.2.

**Comment by harcoPro** [comment]
try create dialog without positive listener

**Comment by afollestad** [comment]
Not enough information here to make an issue.

I'm guessing you were using an old AppCompat version or something.
