### ISSUE TITLE
dialog does not disappear

### ISSUE THREAD

**Issue by daiwenbo88** [afollestad/material-dialogs#1183]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Hello, please when the user clicks on a blank screen area How to make the dialog does not disappear

**Comment by afollestad** [comment]
It works fine for me on Nougat.

You're probably passing `cancelable(false)` unintentionally.
