### ISSUE TITLE
MaterialListPreference: no focus when using a keyboard

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#1185]
When using a MaterialListPreference and navigating through an app with the keyboard, we can use the keyboard to select the preference, and then click on enter to display the list of choices, but then, the keyboard doesn't work (tab, arrows), and we can't move through the choices and select one.

**Comment by afollestad** [comment]
I don't think that's an issue with this library; it's probably a `RecyclerView` issue if I had to guess.

**Comment by afollestad** [comment]
Newer builds should help.
