### ISSUE TITLE
beake line between text of items

### ISSUE THREAD

**Issue by faezesaghafi** [afollestad/material-dialogs#1187]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
This is not a specific title and you did not provide any information.

Closing.

**Comment by faezesaghafi** [comment]
I use this lib in my app from api level 14 to up but in 14 level devices, there is some break line between texts of item and string splite and rest of work goes to next line. in both single choice and multi choice . 
ps: when I scroll the bug disapeard :|

**Comment by faezesaghafi** [comment]
give me a minute body :)))
