### ISSUE TITLE
List item lines break, but the breaking goes away after scrolling with RTL

### ISSUE THREAD

**Issue by faezesaghafi** [afollestad/material-dialogs#1188]
I use this lib in my app from api level 14 to up but in 14 level devices, there is some break line between texts of item and string splite and rest of work goes to next line. in both single choice and multi choice . 
ps: when I scroll the bug disapeard :|

**Comment by YasinRI** [comment]
I have this problem too, my language is Persian. in some Strings, it wraps it from middle of the string, but when I scroll the list and return to first items it get solved.
I appreciate if u help me how to solve it. 

before Scroll :
![befor](https://cloud.githubusercontent.com/assets/19660732/18827893/fbddb924-83e1-11e6-8859-1e2b2de0c1f0.png)

afterScroll:
![after](https://cloud.githubusercontent.com/assets/19660732/18827912/1877aa4a-83e2-11e6-8a68-4045f9b3a331.png)

**Comment by YasinRI** [comment]
can you help me what to do to solve it? please answer me because my application is going to publish

**Comment by afollestad** [comment]
Wait this is happening on API 14? There are no system level APIs for RTL until API 16.
