### ISSUE TITLE
Reset / Clear Builder

### ISSUE THREAD

**Issue by eygraber** [afollestad/material-dialogs#1189]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `6.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto Z Force`

Are there any plans to add a `reset` or `clear` method to `MaterialDialog.Builder`, that would allow it to create a new `MaterialDialog` without any of the previous modifications?

**Comment by afollestad** [comment]
There's no plans. It'd be easier to reinstantiate the Builder.

**Comment by eygraber** [comment]
It would be nice for things like DI where instantiating a new one is inconvenient.
