### ISSUE TITLE
How to dismiss the progress dialog manually and use custom progress style

### ISSUE THREAD

**Issue by SunnyBongiri** [afollestad/material-dialogs#1192]
how can i dismiss or stop the progress dialog.
also how can i use my custom progress style defined in xml layout

**Comment by afollestad** [comment]
The same way you dismiss any other dialog.

**Comment by afollestad** [comment]
And you need a custom view dialog for custom styles.

**Comment by SunnyBongiri** [comment]
MaterialDialog.Builder progressDialog = new MaterialDialog.Builder(this)
                .title("Logging In")
                .content("Please Wait...")
                .progress(true, 0);

then I show this dialog inside onClick method using progressDialog.show();

dismiss() method is not available bro...

**Comment by afollestad** [comment]
Read the documentation. There's a section called "Dismissing Dialogs".

**Comment by afollestad** [comment]
You can't dismiss a Builder. You dismiss the dialog.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#dismissing-dialogs
