### ISSUE TITLE
Collapsed Toolbar title disappear when dialog is displayed

### ISSUE THREAD

**Issue by Kaminiak** [afollestad/material-dialogs#1193]
- Material Dialogs version: `0.9.0.2`
- Device OS version: `6.0`
- Device Manufacturer: `Huawei`
- Device Name: `P9`
- Support Library Version: `24.2.1`
###### Reproduction Steps
1. You need to have layout hierarchy like this:

``` xml
<CoordinatorLayout>
    <AppBarLayout>
        <CollapsingToolbarLayout>
            <Toolbar>
            </Toolbar>
        </CollapsingToolbarLayout>
    </AppBarLayout>
    <NestedScrollView>
        <!-- My content -->
    </NestedScrollView>>
</CoordinatorLayout>
```
1. Header is expanded on the beginning
2. You have to collapse header by scrolling top in NestedScrollView
3. Then display material dialog when toolbar is collapsed
###### Expected Result
1. Dialog is displayed
2. Toolbar title is in the same position
###### Actual Result

When I display material dialog, toolbar title disappear. When I hide dialog, toolbar title is still invisible. When I expand toolbar, then title appears, with animation from a bottom. When I collapse it again, toolbar title disappears. Only way to bring collapsed toolbar title, is to show dialog when toolbar is expanded, then title appears again in collapse mode.

How it looks like:
http://giphy.com/gifs/3o7TKBTM2DeV0uDljG

**Comment by afollestad** [comment]
I don't think this is related to this library, since this library is just wrapping around regular `android.app.Dialog` instances. There's probably an underlying issue in Google's code.
