### ISSUE TITLE
Filter for Single and multiple choice?

### ISSUE THREAD

**Issue by ldt116** [afollestad/material-dialogs#1194]
Can you add ability to create filter for Single/Multiple choice dialog?

**Comment by afollestad** [comment]
You didn't follow the issue template at all.

I'm also not sure what you mean by that.

**Comment by ldt116** [comment]
@afollestad sorry. I did not found the issue template. Can you point me where is it?

**Comment by afollestad** [comment]
It appears as the default text when you create a new issue.

**Comment by jhdavino** [comment]
it is possible to create a "MaterialDialog" using CustomView with multiple checkbox and use the itemsCallbackMultiChoice to observer when these checkboxs of CustomView are selected?

Exemple:

    MaterialDialog dialog = new MaterialDialog.Builder(this)
                    .customView(R.layout.dialog_preference_user_customview, true)
                    .positiveText(R.string.dialog_options_btn_ok)
                    .negativeText(R.string.dialog_options_btn_cancel)              
                    .itemsCallbackMultiChoice(new Integer[]{1,...}, new MaterialDialog.ListCallbackMultiChoice() {
                        @Override
                        public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
                            StringBuilder str = new StringBuilder();
                            for (int i = 0; i < which.length; i++) {
                                if (i > 0) str.append('\n');
                                str.append(which[i]);
                                str.append(": ");
                                str.append(text[i]);
                            }

                            return true; // allow selection
                        }
                    })
                    .autoDismiss(false)
                    .onPositive(new MaterialDialog.SingleButtonCallback() {
                        @Override
                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                        }
                    }).build();

Or just this:


 CheckBox chk = (CheckBox) dialog.getCustomView().findViewById(R.id.traffic_accidents);
            chk.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
                @Override
                public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                }
            });

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/1212
