### ISSUE TITLE
Is there a listener callback for cancel or dismiss in ColorChooserDialog ?

### ISSUE THREAD

**Issue by juani21** [afollestad/material-dialogs#1198]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Material Dialogs version: `0.9.0.2`
- Device OS version: `6.0`
- Device Manufacturer: `LG`
- Device Name: `Nexus 5`

```
      new ColorChooserDialog.Builder((MainActivity) getActivity(), R.string.color_palette)
                .titleSub(R.string.choose_colors)  // webSite of dialog when viewing shades of a color
                .customColors(primary, null)
                .allowUserColorInput(false)
                //.accentMode(accent)  // when true, will display accent palette instead of primary palette
                .doneButton(R.string.md_done_label)  // changes label of the done button
                .cancelButton(R.string.md_cancel_label)  // changes label of the cancel button
                //.backButton(R.string.md_back_label)  // changes label of the back button
                //.preselect(accent ? accentPreselect : primaryPreselect)  // optionally preselects a color
                .dynamicButtonColor(true)  // defaults to true, false will disable changing action buttons' color to currently selected color
                .show();

```

I need to know if the ColorChooseDialod is cancelled or dismissed, is there a solution?

Thank you very much this is a great library!!!

**Comment by afollestad** [comment]
There is not, because interface references do not survive orientations. `ColorChooserDialog` is a `DialogFragment`, so it survives Activity rotations; those listeners would not, if added.
