### ISSUE TITLE
MaterialDialog‘s Style

### ISSUE THREAD

**Issue by yaosongqwe** [afollestad/material-dialogs#1200]
In the constructor of MaterialDialog, Style  is a final param, can consider to let user customize the Style of Dialog? 

```java
    protected MaterialDialog(Builder builder) {
        super(builder.context, DialogInit.getTheme(builder));
        mHandler = new Handler();
        mBuilder = builder;
        final LayoutInflater inflater = LayoutInflater.from(builder.context);
        view = (MDRootLayout) inflater.inflate(DialogInit.getInflateLayout(builder), null);
        DialogInit.init(this);
    }
```

Otherwise, how can I make the Dialog background to transparent?

**Comment by afollestad** [comment]
This library is intended to follow the Material Design guidelines. Transparent dialogs do not, so that's not something I intend to allow.

**Comment by yaosongqwe** [comment]
What a pity it is! Most of companies do not use Material Design style!

**Comment by afollestad** [comment]
You'll have to use AlertDialogs, then.

**Comment by yaosongqwe** [comment]
I know that.
