### ISSUE TITLE
Material Dialog not displaying correctly

### ISSUE THREAD

**Issue by itolisto** [afollestad/material-dialogs#1201]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `4.2.2`
 - Device Manufacturer: `Huawei`
 - Device Name: `Y330-U05`
 
###### Reproduction Steps
Inside any fragment or activity, i'm doing the following:

```java
MaterialDialog.Builder builder = new MaterialDialog.Builder(a)
        .title(getString(R.string.logout_message))
        .content("")
        .positiveText(getString(R.string.logout_ok))
        .negativeText(getString(R.string.cancel))
        .positiveColor(colorPositive)
        .negativeColor(colorNegative)
        .onPositive(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                dialog.dismiss();
            }
        })
        .onNegative(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                dialog.dismiss();
            }
        });

MaterialDialog dialog = builder.build();
dialog.show();
``` 

###### Expected Result
Display nice and clean as shown in sample

###### Actual Result
View at [Material dialog display video example](https://youtu.be/MqN5G1EDghQ)

**Comment by afollestad** [comment]
That's not an issue on my end.

Your Activity theme is most likely messing with it.

**Comment by afollestad** [comment]
Oh, nevermind, you're not even setting content.

There's no use in setting an empty string for the content, just take that out.

**Comment by itolisto** [comment]
Hi Aidan,

Sorry to bother you, I knew this was not an issue, I was just trying to get some help. I will check out my activity theme.

Thank you.
