### ISSUE TITLE
Spannable to content strings (<i> and <b> in text)

### ISSUE THREAD

**Issue by mtrakal** [afollestad/material-dialogs#1204]
###### Include the following:
- Material Dialogs version: `0.9.0.2'`
- Device OS version: `any`
- Device Manufacturer: `any`
- Device Name: `any`

It would be nice, when this could be possible.
###### Reproduction Steps

``` xml
<string name="crazy_string">My %1$s <b>bold</b> text could be view as %2$s <i>italic</i>.</string>
```

``` java
new MaterialDialog.Builder(this)
                    .content(R.string.crazy_string, "happy", "angry")
                    .show();
```

Want to create dialog with Text like: 

> My happy **bold** text could be view as angry _italic_.
###### Expected Result

Dialog with formated text: My happy **bold** text could be view as angry _italic_.
###### Actual Result

My happy bold text could be view as angry italic.

**Comment by afollestad** [comment]
It's actually odd that it's not working, since `getText(int)` is being used to retrieve the string resource, rather than `getString(int)`.
