### ISSUE TITLE
FileChooserDialog only show dirs

### ISSUE THREAD

**Issue by jp1017** [afollestad/material-dialogs#1208]
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `4.4`
 - Device Manufacturer: `ourselves`
 - Device Name: 

Also, please wrap Java with correct syntax highlighting.

```java
        new FileChooserDialog.Builder(this)
                .show();
```

###### Expected Result
Your demo is  ok. But my project only show dirs, don't show the file, :cry: 

What happend?

**Comment by afollestad** [comment]
I have no issues with it on my Pixel XL.

**Comment by inneke-dc** [comment]
This seems to still be an issue because I don't see files (only folders) on a nexus 5X. I just installed the demo app from the play store and the file chooser in the demo doesn't show any files either. I also tried with my nexus 6.
