### ISSUE TITLE
Using only input hint in InputCallback dialogs

### ISSUE THREAD

**Issue by boswelja** [afollestad/material-dialogs#1210]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `Any`
 - Device Manufacturer: `Any`
 - Device Name: `Any`

Also, please wrap Java with correct syntax highlighting.

```java
        new MaterialDialog.Builder(context)
                .title(R.string.new_playlist)
                .input(R.string.new_playlist_hint, null, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {
                        if (!input.toString().matches("")) {
                            playlistDBHelper.createPlaylist(input.toString());
                            listNoMoreEmpty();
                            adapter.updateNewList(playlistDBHelper.getAllPlaylist());
                        } else {
                            playlistDBHelper.createPlaylist(getString(R.string.new_playlist_hint));
                            listNoMoreEmpty();
                            adapter.updateNewList(playlistDBHelper.getAllPlaylist());
                        }
                    }
                }).show();
```
 The above code tries to force me to replace the .input null with a string, thus pre-filling the box. But I only want the hint text :/

###### Expected Result
The dialog opens and has hint text in the EditText field

###### Actual Result
The app fails to build because 'null' is not an int

**Comment by boswelja** [comment]
A workaround would be to make an empty string and use that, but it would be more efficent if there was a way to just pass null instead of an empty string

**Comment by afollestad** [comment]
`0` is `null` when it comes to resource IDs.
