### ISSUE TITLE
Input Dialogs: option for show dialog without keyboard

### ISSUE THREAD

**Issue by neokree** [afollestad/material-dialogs#1211]
Hi,
I'm trying to show up an input dialog without the keyboard, because for small devices it covers the buttons and this could be a problem in case of secondary actions (using neutral button) because it will not be visible to the user.

I already tried this workaroud to hide the keyboard on show

```
final MaterialDialog.Builder dialogBuilder = new MaterialDialog.Builder(this)
                .title(R.string.dialog_title)
                .content(R.string.dialog_content)
                .inputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL)
                .input(null, null, false, this)
                .positiveText(R.string.dialog_save)
                .negativeText(android.R.string.cancel)
                .neutralText(R.string.dialog_neutral)
                .onNeutral(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        // Doing something
                    }
                });

        dialogBuilder.showListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialogInterface) {
                DialogUtils.hideKeyboard(dialogInterface, dialogBuilder);
            }
        });

        dialogBuilder.show();
```

But it doesn't work (probably because the library have requested focus and the keyboard is not already showed, so recall `hideSoftInputFromWindow` doesn't close the keyboard). 

So I thought to close the keyboard programmatically 

```
MaterialDialog dialog = (MaterialDialog) di;
View view = dialog.getCurrentFocus();
if (view != null) {  
    InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
    imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
}
```

But without success.
Sure, I can try to close it using a post delayed thread, but I don't like that solution.

It will definitely more simpler add a parameter true/false on input method, like:

```
public Builder input(@Nullable CharSequence hint, @Nullable CharSequence prefill, boolean allowEmptyInput, boolean showKeyboard, @NonNull InputCallback callback) {
```

And check on `MaterialDialog.onShow` if that `showKeyboard` is setted or not.
- Material Dialogs version: `0.9.0.2`
- Device OS version: `Any`
- Device Manufacturer: `Any`
- Device Name: `Any`

**Comment by afollestad** [comment]
I don't plan to allow disabling this behavior.

**Comment by jenlai1345** [comment]
Hi,

I've encountered a similar situation.  When the dialog is first opened, soft keyboard is automatically shown and it covers the positive/cancel buttons. 

I'd also like to implement the hideKeyboard function when user taps on anything of the dialog. 

So far, I have not found a way to dimiss the keyboard except to dismiss the whole dialog window.

Any help would really be appreciated!!!

Again, thanks for the great work.
