### ISSUE TITLE
Filter for Single and multiple choice

### ISSUE THREAD

**Issue by wmadrid1** [afollestad/material-dialogs#1212]
###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `4.4`
 - Device Manufacturer: `Samsung`
 - Device Name: `Samsung S6`

###### Reproduction Steps
Its not a bug, just a functionality request.
When any single or multiple choice list is shown can be added an search box to filter the list items/

###### Expected Result
Search box added

###### Actual Result
No search box

Thanks, or can you guide me to make this change?

**Comment by afollestad** [comment]
I don't plan on adding that.

---

You'l have to construct your own custom view.
