### ISSUE TITLE
Is it possible to set orientation for dialogs?

### ISSUE THREAD

**Issue by marzochi** [afollestad/material-dialogs#1214]
Firstly, thanks for library. I'm using some activities in landscape mode, but I need portrait orientation for dialog. Like this.
![untitled](https://cloud.githubusercontent.com/assets/8195419/20094930/10793bba-a5ac-11e6-828e-e8603175d5fa.png)

 - Material Dialogs version: `0.9.1.0`

**Comment by afollestad** [comment]
`MaterialDialog` is just an `android.app.Dialog`, so if there is a way, it wouldn't be specific to this library.

However, I won't add a way to do it specifically.
