### ISSUE TITLE
Bad window token, you cannot show a dialog before an Activity is created or after it's hidden

### ISSUE THREAD

**Issue by panrongfu** [afollestad/material-dialogs#1215]
my code like this：

```java
  new MaterialDialog.Builder(MainTabActivity.this)
                .title(R.string.warning)
                .content(R.string.login_on_other_client)
                .positiveText(R.string.okay_text)
                .cancelable(false)
                .onAny(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        LogoutHelper.logout();
                        Map<String,Object> map = new HashMap<String,Object>();
                        map.put(Constant.LOGIN_STATE,false);//未登录
                        SpUtil.save(map);

                        AppManager.getAppManager().returnToActivity(LoginActivity.class);
                        if (!AppManager.getAppManager().checkActivity(LoginActivity.class)) {
                            Intent intent = new Intent(MainTabActivity.this,LoginActivity.class);
                            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            startActivity(intent);
                        }
                    }
                })
                .show();
```

**Comment by afollestad** [comment]
That happens if you show a dialog before or after an Activity is visible.

**Comment by gronel** [comment]
same issue

**Comment by draskosaric** [comment]
Post the code. In the code that @panrongfu provided, dialog is not dissmised in `onClick` method and activity is hidden by starting new activity, so message "you cannot show a dialog before an Activity is created or after it's hidden " totally makes sense.

**Comment by bhb27** [comment]
on main page README.md
https://github.com/afollestad/material-dialogs#dismissing-dialogs

use *onPause()* to dismiss it.
I use 
if (dialog != null) dialog.dismiss();
and have that dialog as a *private* object on the activity...

With *v7.app.AlertDialog* you can use the same dialog to *create()* the *Builder* and dissmiss the one active, has can really be only one active it always dissmiss. Did not try having the same *MaterialDialog dialog* to *build()* diferente *Builder()* but I believe it works.
