### ISSUE TITLE
How to change title text size?

### ISSUE THREAD

**Issue by pasha14** [afollestad/material-dialogs#1217]
Can we change the dialog title size ?

###### Include the following:
 - Material Dialogs version: `0.9.0.2`

**Comment by afollestad** [comment]
You can't, it's sized from the Material Design guidelines.

**Comment by softiran** [comment]
From another issue!
MaterialDialog dialog = b.build(); // build as you like

// now the trick
MaterialDialog d = dialog;
d.getTitleView().setTextSize(TypedValue.COMPLEX_UNIT_DIP, 60); // Your size
d.getActionButton(DialogAction.POSITIVE).setText("muhaha"); // Your text
      
dialog = d;
dialog.show();
