### ISSUE TITLE
Could not find class 'android.graphics.drawable.RippleDrawable' in pre lollipop devices

### ISSUE THREAD

**Issue by venceitor** [afollestad/material-dialogs#1219]
- Material Dialogs version: `0.9.1.0`
 - Device OS version: `4.4.4`
 
When you create a MaterialDialog in pre lollipop devices you get the next error:

E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by butich** [comment]
It's ok, pre lollipop android cant draw ripple.

**Comment by afollestad** [comment]
Unable to reproduce on KitKat devices.

**Comment by antonio10** [comment]
Please, did someone find the soluction for this problem, it may be so helpfully.
