### ISSUE TITLE
Incorrect InputDialog's EditText line color

### ISSUE THREAD

**Issue by EpsilonOrionis** [afollestad/material-dialogs#1220]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `5.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `E2`

Also, please wrap Java with correct syntax highlighting.

```java
new MaterialDialog.Builder(getActivity())
                                    .title(R.string.title)
                                    .content(R.string.content)
                                    .inputType(InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS)
                                    .inputRangeRes(5, 5, R.color.material_red)
                                    .widgetColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary))
                                    .positiveColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary))
                                     ...
```

###### Expected Result
The InputDialog's EditText is colored as written in the dialog creation: .widgetColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary))

###### Actual Result
It inherits the accentColor specified in the activity theme. The dialog is shown in a fragment

**Comment by afollestad** [comment]
Unable to reproduce. Works fine on my end.

**Comment by afollestad** [comment]
If it still doesn't work, it may be an issue specific to your phone model.
