### ISSUE TITLE
Prevent an unselection action in Multi Choice List Dialogs

### ISSUE THREAD

**Issue by danielemaddaluno** [afollestad/material-dialogs#1221]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Device Info:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`

I was trying to obtain something similar to the `showMultiChoiceLimited` preventing an unchecking action instead of a checking one.
The `onSelection` method from the `ListCallbackMultiChoice` it's called both when I check and uncheck the checkbox so I supposed that returning false would have prevented both the actions, but it does not.
Have I missed something?
This is the tested code. 

```java
/**
 * I would like to prevent an unselection action, so that the
 * newly unselected check box will not be actually unselected 
 * if a condition is false.
 */
public void showMultiChoiceUncheckingLimited() {
	new MaterialDialog.Builder(context)
	.title("Social:")
	.items(Arrays.asList("Facebook", "Twitter", "G+"))
	.itemsCallbackMultiChoice(new Integer[]{1}, new MaterialDialog.ListCallbackMultiChoice() {
		@Override
		public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
			boolean allowUnSelection = which.length >= 1; // limit the unselection (instead of the selection)
			if (!allowUnSelection) {
				showToast(R.string.selection_limit_reached);
			}
			return allowUnSelection;
		}

	})
	.positiveText("Dismiss")
	.alwaysCallMultiChoiceCallback() // the callback will always be called, to check if selection is still allowed
	.show();
}
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1
