### ISSUE TITLE
"\n" not working anymore due to Html.fromHtml()

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#1222]
Since version 0.9.1.0, if I use "\n" in a resource string, and use this string as content of a material-dialog, it doesn't work anymore, there's no line break inserted.

Thank you for looking into it.

**Comment by StephaneDupont** [comment]
To be more accurate:

if I use: 

`.content(stringResId)`

\n are not working. But if I use:

`.content(context.getResources().getString(stringResId))`

it works.

**Comment by rfazi** [comment]
I confirm the problem.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1
