### ISSUE TITLE
HUAWEI HOROR 8 FRD-AL00  crash

### ISSUE THREAD

**Issue by ronniesun** [afollestad/material-dialogs#1227]
new MaterialDialog.Builder(mContext)
							.title(getString(R.string.text_suozaidi))
							.items(provinces)
							.itemsCallbackSingleChoice(choose, new MaterialDialog.ListCallbackSingleChoice() {
								@Override
								public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
									if (which != -1 && which != ShareUtil.getInt(ShareUtil.SHARE_PROVINCE_SELECT, -1)) {
										ShareUtil.setInt(ShareUtil.SHARE_PROVINCE_SELECT, which);
										areaTips.setText(provinces[which]);

										HashMap<String, String> params = new HashMap<String, String>();
										params.put(ConstantNetUtil.PARAM_ACTION, ConstantNetUtil.URL_GET_SAVEAREA);
										JsonObject obj = new JsonObject();
										obj.addProperty("userid", ShareUtil.getString(ShareUtil.SHARE_USER_ID, ""));
										obj.addProperty("province", provinces[which]);
										params.put(ConstantNetUtil.PARAM_DATA, obj.toString());
										httpPost(REQUEST_CODE_2, null, params);
									}
									return true;
								}
							})
							.positiveText("positive")
							.negativeText("negative")
							.show();

I am sure is a bug, because the old version 0.8.5.6@aar no problem

**Comment by afollestad** [comment]
You didn't follow the issue template, so this isn't really valid. No logcat and invalid formatting.
