### ISSUE TITLE
Bug showing colored checkboxes

### ISSUE THREAD

**Issue by rAseri** [afollestad/material-dialogs#1228]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Device Info:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `5.0.2/5.0.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy Tab S2/Galaxy S6 (Emulator)`

I'm create dialog as shown below

```java
      Integer[] selectedItems = new Integer[wallFilterData.filterSelectedItems.size()];
      selectedItems = wallFilterData.filterSelectedItems.toArray(selectedItems);

      new MaterialDialog.Builder(getContext())
                .title(R.string.title)
                .items(wallFilterData.filterTitles)
                .itemsCallbackMultiChoice(selectedItems, new MaterialDialog.ListCallbackMultiChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
                        applyNewWallFilters(which);
                        return true;
                    }
                })
                .widgetColor(ContextCompat.getColor(getContext(), R.color.red_500))
                .positiveText(R.string.pedagogical_calendar_filter_dialog_apply_btn)
                .negativeText(R.string.cancel)
                .show();
```

###### First opened dialog looks ok
<img src="https://cloud.githubusercontent.com/assets/3706717/21014250/5759502c-bd6e-11e6-9925-7ac25248a05d.png" width="300px" />

###### When i'm deselect some item and then select it again, item display as selected with grey checkbox
<img src="https://cloud.githubusercontent.com/assets/3706717/21014961/189d859e-bd71-11e6-9dbf-d3184f4cbb03.png" width="300px" />

As I unsderstand, this bug reproduce only on devices with Android 5.0 (Api level 21).

**Comment by afollestad** [comment]
Unfortunately this is probably a Samsung problem that I cannot fix.
