### ISSUE TITLE
Add possibility to set a unique ID for dialogs when using MaterialDialogs.Builder

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/material-dialogs#1231]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

###### Issue Description:

This is more a feature request than a bug report.
It would be nice to have the possibility to set a unique id for a dialog when using the `MaterialDialog.Builder`.
This allows encapsulating multiple dialogs in a separate class with a single `SingleButtonCallback` implementation to handle all different kind of callback invocations depending on the Dialog's id.

Any feedback on that is appreciated.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.2
