### ISSUE TITLE
Radio buttons tinted with textColorSecondary instead of colorControlNormal

### ISSUE THREAD

**Issue by xGary** [afollestad/material-dialogs#1232]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Dialogs.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

The dialog radio buttons are being tinted using textColorSecondary instead of colorControlNormal. This has been reported by a few people in #1153. There seems to be some kind of issue with Android's RadioButtons as the first answer in this [StackOverflow thread](http://stackoverflow.com/questions/26843098/android-appcompat-v721-0-0-change-material-checkbox-colors) also confirms this issue. My MaterialDialog's radio buttons are having this issue but my Android SDK RadioButtons are not and are correctly tinted using colorControlNormal. 

Since you can already set the colors for a bunch of stuff, I think you should just allow us to supply our own colors or ColorStateList to override the widget state colors. That provides more flexibility and allows us to not have to depend on Android's theming system which I find to be buggy and convoluted.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.2
