### ISSUE TITLE
How to get primary and secondary selected colors in ColorChooserDialog?

### ISSUE THREAD

**Issue by jordyamc** [afollestad/material-dialogs#1233]
- [ X ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X ] I have verified that I am using the latest version of Material Dialogs.
- [ X ] I have given my issue a non-generic title.
- [ X ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `Emulator`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
new ColorChooserDialog.Builder(this,...)
     ...
     .customColors(String[], String[])
     ...
```
 
###### Reproduction Steps

1. Create dialog using customColors

###### Expected Result
get primary and secondary colors in onColorSelection interface

###### Actual Result
only getting one color

**Comment by afollestad** [comment]
Look at the README on the front page, or the sample project.
