### ISSUE TITLE
set onCancelListener in ColorChooserDialog

### ISSUE THREAD

**Issue by jordyamc** [afollestad/material-dialogs#1234]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.1`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Emulator`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
new ColorChooserDialog.Builder(this, R.string.color_chooser)
     ...
     .cancelButton(R.string.cancel)
     ...
```

**Comment by afollestad** [comment]
`ColorChooserDialog` is a `DialogFragment` so setting interfaces to it is not a good idea (they are not maintained through orientation changes). You could extend `ColorChooserDialog` in your own class and override `onCancel`.
