### ISSUE TITLE
Don't throw exceptions when calling setProgress() for an indeterminate dialog (just be silent)

### ISSUE THREAD

**Issue by webmaster128** [afollestad/material-dialogs#1235]
I have an image scaling application that uses indeterminate progress for 1 and 2 images and determinate progress for 3 and more images.

It would be nice if I could use setProgress no matter if my Dialog decided to be indeterminate or determinate.

Right now I get the Exception

> java.lang.IllegalStateException: Cannot use setProgress() on this dialog.

in [com.afollestad.materialdialogs.MaterialDialog.setProgress(MaterialDialog.java:1663)](https://github.com/afollestad/material-dialogs/blob/0.9.1.0/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L1663). I think it makes sense to implement the behavior of [android.widget.ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar.html#setProgress(int)):

> Does not do anything if the progress bar is in indeterminate mode.

**Comment by afollestad** [comment]
Layouts are determined at dialog build-time, you cannot switch between different progress types with how everything is currently setup.

**Comment by webmaster128** [comment]
Okay, this should not be the issue. My dialog layout is 100 % ready at build time

```
mScalingDialog = new MaterialDialog.Builder(ComposeActivity.this)
                        .title("Scaling")
                        .content("Scaling down images")
                        .progress(imagesCount < 3, imagesCount, true)
                        .cancelable(false)
                        .build();
                mScalingDialog.show();
```

Now in the indeterminate case I am not allowed to call setProgress because of the exception.

**Comment by afollestad** [comment]
The progress layout is either indeterminate or not at build time. Switching the progress type would require switching out the layout.

**Comment by webmaster128** [comment]
I am not planning to switch the layout. I just want to avoid additional case distinctions in my application code and call setProgress on an indeterminate dialog

**Comment by afollestad** [comment]
Oh sorry, I think I misinterpreted what you were requesting

**Comment by webmaster128** [comment]
I think I can write a PR for this, if you like. Is there an easy way to read the javadocs of this project?

**Comment by webmaster128** [comment]
Hey @afollestad, I would be happy to provide a patch for this issue as well as #1236. But in order to be able to work on that, I need a resolution for #1238. Without a solid base it just makes no sense to build on top.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by webmaster128** [comment]
I think we should fully allow this behaviour here, i.e. just do nothing and don't log anything. With the patch that was linked, uses get spammend with warnings, so still cannot really use it.
