### ISSUE TITLE
Ignore progressIndeterminateStyle(true) for determinate dialogs

### ISSUE THREAD

**Issue by webmaster128** [afollestad/material-dialogs#1236]
When I call `.progressIndeterminateStyle(true)` on a determinate dialog, I get some strange effects:

1. percentages in the bottom left do not work anymore
2. progress count in the bottom right does not increase
3. the bar layout changes to a smooth animation that does not reflect the progress

My understanding of the term "progressIndeterminateStyle" would be that: if there the dialog is indeterminate, use this style.

So it would be good if the call would be ignored for determinate dialogs.

Sample code:

```
mScalingDialog = new MaterialDialog.Builder(ComposeActivity.this)
        .title("Scaling")
        .content("Scaling down images")
        .progress(imagesCount < 3, imagesCount, true)
        .progressIndeterminateStyle(true)
        .cancelable(false)
        .build();
mScalingDialog.show();
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by webmaster128** [comment]
Works now as expected, thanks
