### ISSUE TITLE
can't sync project with material-dialog's Dependency 

### ISSUE THREAD

**Issue by mohdriyas** [afollestad/material-dialogs#1243]
Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :circularimageview:generateDebugSources, :circularimageview:generateDebugAndroidTestSources, :circularimageview:mockableAndroidJar, :circularimageview:prepareDebugUnitTestDependencies, :circularprogress:generateDebugSources, :circularprogress:generateDebugAndroidTestSources, :circularprogress:mockableAndroidJar, :circularprogress:prepareDebugUnitTestDependencies, :cropimageview:generateDebugSources, :cropimageview:mockableAndroidJar, :cropimageview:prepareDebugUnitTestDependencies, :cropimageview:generateDebugAndroidTestSources, :datepick:generateDebugSources, :datepick:mockableAndroidJar, :datepick:prepareDebugUnitTestDependencies, :datepick:generateDebugAndroidTestSources, :infinateview:generateDebugSources, :infinateview:generateDebugAndroidTestSources, :infinateview:mockableAndroidJar, :infinateview:prepareDebugUnitTestDependencies, :intlphoneinput:generateDebugSources, :intlphoneinput:generateDebugAndroidTestSources, :intlphoneinput:mockableAndroidJar, :intlphoneinput:prepareDebugUnitTestDependencies, :pinrest:generateDebugSources, :pinrest:generateDebugAndroidTestSources, :pinrest:mockableAndroidJar, :pinrest:prepareDebugUnitTestDependencies]
Warning:string 'SearchImagesTitle' has no default translation.
Warning:string 'SearchGifsTitle' has no default translation.
D:\ri\android\app\build\intermediates\res\merged\debug\values\values.xml
Error:(504) Attribute "alpha" has already been defined
Error:(504) Attribute "alpha" has already been defined
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
Information:BUILD FAILED

###### Include the following:
 - Material Dialogs version: `:0.9.1.0`
 - Device OS version: `6.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Nothing in that build log is related to Material Dialogs.
