### ISSUE TITLE
Update build tools version to 25.0.1

### ISSUE THREAD

**Issue by timrae** [afollestad/material-dialogs#1245]
@afollestad 
Is there a problem with the latest build tools version, or did you just forget to update it? I noticed that our builds are still requiring the older version of build tools despite updating to latest material dialogs.

**Comment by afollestad** [comment]
No, I just don't have time for side projects at the moment.

**Comment by timrae** [comment]
Ah I see, yeah I can imagine... No problem

**Comment by afollestad** [comment]
Will be updated in next release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.2

**Comment by timrae** [comment]
Thanks!
