### ISSUE TITLE
Question: animation on height change

### ISSUE THREAD

**Issue by rfazi** [afollestad/material-dialogs#1246]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `6.0`
 - Device Manufacturer: `LG`
 - Device Name: `LG G3 D855`
 
###### Reproduction Steps

1. Create a dialog with a layout that have two children layouts that have different height size, one is invisible.
2. Set visible layout visibility to gone, and set second layout visibility to visible.

###### Expected Result

What I want is that the height difference changes with an animation.

###### Actual Result

The height difference changes with no animation.

**Comment by afollestad** [comment]
That isn't really specific to this library. The implementation is up to you.
