### ISSUE TITLE
dynamically changing cancelable value using getBuilder().cancelable(value)

### ISSUE THREAD

**Issue by vipulasri** [afollestad/material-dialogs#1252]
How to dynamically changing cancelable value using `getBuilder().cancelable(value);`. Cancelable value remains the same.

**Comment by afollestad** [comment]
You call `setCancelable(boolean)` on the Dialog itself, not the Builder.

**Comment by afollestad** [comment]
The `Builder` doesn't do anything after the `Dialog` is built.
