### ISSUE TITLE
extensionFilter does not work as expected in FileChooserDialog

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1253]
- Material Dialogs version: `0.9.1.0`

As we know, file extension is a suffix for the file name. For example, android application installer has `.apk` extension. We can filter it by using `endsWith()` function. But, in this library I saw `contains()` function which returns true to the file name started with `apk`, even though the file has `.exe` extension.

If you filter a file named `my apk collections.exe`, this will returns true because the filename contains `apk`, although the file is a Windows Executable application.

Changing `contains` to `endsWith` is a simple work:

```java
                       for (String ext : extensions) {
                            if (fi.getName().toLowerCase().endsWith(ext.toLowerCase())) {
                                found = true;
                                break;
                            }
                        }
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.2

**Comment by anggrayudi** [comment]
Thank you. :+1:
