### ISSUE TITLE
Dialogs are too wide/tall

### ISSUE THREAD

**Issue by tihomirleka** [afollestad/material-dialogs#1256]
For some reason dialogs are too wide when compared to standard android dialogs. First I noticed it with dialog that had a custom view set, and thought my view is problem, but then I tried standard list dialog and progress dialog and both dialog have the exact same problem. I attached some screenshots so you can better understand what am I talking about and below is code for showing the dialogs.

I'm testing on Nexus 5 with Android 6.0.1 and the latest version of the library.

![custom_view_dialog](https://cloud.githubusercontent.com/assets/448435/21717588/44829a2a-d412-11e6-834d-3cae8b7b9865.png)
```java
new MaterialDialog.Builder(context).theme(Theme.LIGHT)
            .titleColorRes(R.color.gray_dark)
            .negativeColorRes(R.color.orange)
            .positiveColorRes(R.color.orange)
            .title(R.string.dialog_title_task_due_date_reminder_set_custom)
            .customView(R.layout.dialog_task_due_date_reminder, false)
            .negativeText(R.string.action_close)
            .positiveText(R.string.ok)
```
![list_dialog](https://cloud.githubusercontent.com/assets/448435/21717589/44837666-d412-11e6-9e0a-5f760478a046.png)
```java
new MaterialDialog.Builder(context).theme(Theme.LIGHT)
            .titleColorRes(R.color.gray_dark)
            .negativeColorRes(R.color.orange)
            .positiveColorRes(R.color.orange)
            .adapter(adapter, layoutManager)
            .negativeText(context.getString(R.string.action_close))
            .cancelable(true)
            .cancelListener(new DialogInterface.OnCancelListener() {
                @Override public void onCancel(DialogInterface dialog) {
                    dialog.dismiss();
                }
            });
```
![progress_dialog](https://cloud.githubusercontent.com/assets/448435/21717590/4484d89e-d412-11e6-8410-047a62bed868.png)
```java
new MaterialDialog.Builder(this).theme(Theme.LIGHT)
                    .titleColorRes(R.color.gray_dark)
                    .negativeColorRes(R.color.orange)
                    .positiveColorRes(R.color.orange)
                    .progress(true, 0)
                    .show();
```

Anu idea why this is happening?

**Comment by AndreaCioccarelli** [comment]
Having the same problem. Dialogs uses the 100% of the screen
```java
new FolderChooserDialog.Builder(MainActivity.this)
            .chooseButton(R.string.md_choose_label)  // changes label of the choose button
            .initialPath("/")  // changes initial path, defaults to external storage directory
            .tag("0")
            .show();
```
![device-2017-01-06-172313](https://cloud.githubusercontent.com/assets/23010471/21724488/dc5daac0-d434-11e6-9d57-a63502cfc048.png)

**Comment by afollestad** [comment]
That's super weird, something must have changed with the newer version of AppCompat.

**Comment by tihomirleka** [comment]
So, I tried out some of the old versions of material-dialogs library and it seems the bug is introduced in version 0.9.2.0. I used latest version of support library (25.1.0) and decreased md lib version and I got normal width when I got to version 0.9.1.0. So I guess workaround for now is to stick with version 0.9.1.0 until there is a fix.

**Comment by afollestad** [comment]
@tihomirleka well, the only change that could have affected this was the AppCompat 25.1.0 update. I will probably need to put some manually height/width limiting logic in there now.

**Comment by afollestad** [comment]
Fixed for the next release

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.2

**Comment by rfazi** [comment]
After this release now the dialog occupy all width of the device.
I have LG G3.

**Comment by afollestad** [comment]
@rfazi use the latest version that I just commeted above you. :P

**Comment by rfazi** [comment]
I'm use the version you commited above.
Turn back to the 0.9.2.1 resolve the problem.

**Comment by basefas** [comment]
I have the same problem on the 0.9.2.2 version.I'm testing on Nexus 5 with Android 6.0.1 and buildToolsVersion is  25.0.2, support library is 25.1.0.

**Comment by ritdaw** [comment]
Same issue on 0.9.2.2. Android 6.0.1.

**Comment by tihomirleka** [comment]
I tried it out with latest release of the library and have the same issue. The dialogs now occupies full width of the screen. As I said, the last version that doesn't present the bug is 0.9.1.0.

**Comment by afollestad** [comment]
Odd.

It works on my Pixel XL, Nexus 6P, Nexus 5X, and Nexus 9. Plus a Pixel C emulator.

@tihomirleka @ritdaw @basefas

**Comment by rfazi** [comment]
@afollestad Sorry I'm confused, the problem persist in 0.9.2.1.
Revert back to 0.9.1.0 resolve the problem.

**Comment by afollestad** [comment]
Well it doesn't seem to be an issue on my end.

**Comment by peppe130** [comment]
Also on my Galaxy S6 Flat the dialog occupies all the width.

Android 6.0.1 and version 9.0.2.2

**Comment by franciscofranco** [comment]
I'm also affected with 0.9.2.2, all latest versions of appcompat etc on my Nexus 5. Can debug whatever if needed.

**Comment by afollestad** [comment]
Hmm... @franciscofranco @peppe130 @rfazi @tihomirleka @ritdaw @basefas 

![affix_20170109_181748](https://cloud.githubusercontent.com/assets/1820165/21789083/fde9b37c-d697-11e6-9c47-8076a8cbfb0f.png)

---

Does it still happen on your devices from the sample app? https://github.com/afollestad/material-dialogs/raw/master/sample/sample.apk

**Comment by basefas** [comment]
I clone the project and install it on my Nexus5 ,has the same problem，the same as your sample.apk

**Comment by ritdaw** [comment]
This is from the 0.9.2.2 release on Google Play. Android 6.0.1 (Moto Z Play).

![image](https://cloud.githubusercontent.com/assets/2089152/21799426/1ba3fd90-d711-11e6-8f3a-107f7d0f9425.png)

**Comment by PavelSynek** [comment]
Nexus 5, Android 6.0.1
![device-2017-01-10-093903](https://cloud.githubusercontent.com/assets/11048800/21799545/026ea9f2-d71a-11e6-8047-2f04463134db.png)

**Comment by rfazi** [comment]
LG G3 Android 6

![screenshot_2017-01-10-11-56-49](https://cloud.githubusercontent.com/assets/9641390/21803788/04757368-d72c-11e6-92d0-84b8129881fc.png)

**Comment by tihomirleka** [comment]
Different devices, resolutions and Android versions, all taken on actual devices, not emulators.

![devices](https://cloud.githubusercontent.com/assets/448435/21804767/f630ba88-d730-11e6-996d-5528e5bac3ac.png)

**Comment by rfazi** [comment]
Maybe the problem is the new dimension?

    <dimen name="md_dialog_max_width">

**Comment by riadhnet** [comment]
same problem here with samsung galaxy s5

**Comment by afollestad** [comment]
@rfazi probably, but it shouldn't be an issue since it uses Material specs for that. Not sure why it would work fine on my devices and not on yours. 😭

**Comment by afollestad** [comment]
That is helpful @tihomirleka, thanks

**Comment by tihomirleka** [comment]
No problem. Let me know if you want me to re-test on all devices after the fix.

**Comment by afollestad** [comment]
@tihomirleka can you check the updated sample? https://github.com/afollestad/material-dialogs/raw/master/sample/sample.apk

**Comment by tihomirleka** [comment]
Looks like its fixed.

![devices-1](https://cloud.githubusercontent.com/assets/448435/21828641/e7712828-d791-11e6-8c24-f9c5de7b9b11.png)

**Comment by afollestad** [comment]
Thanks!

https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.3
