### ISSUE TITLE
App cannot be launched with MaterialDialogs 0.9.2.1

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1257]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.2.1`
 - Device OS version: `6.0.1 && 5.0 && 4.4 && 7.0`
 - Device Manufacturer: `Samsung && Google`
 - Device Name: `Samsung Galaxy S3 with multiboot (6.0.1, 7.0 4.4) and Nexus 6P (5.0)`

If my MaterialDialogs version is updated at the 9.2.1 version, I cannot launch my app (Impactor) due to this error:

```log
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> !zip.isFile()

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

```

```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.andreacioccarelli.impactor"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 53
        versionName "4.1.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:design:25.1.0'
    compile 'com.afollestad.material-dialogs:core:0.9.2.1'
    compile 'com.android.support:cardview-v7:25.1.0'
    compile 'com.android.support:customtabs:25.1.0'
    compile 'com.github.paolorotolo:appintro:4.1.0'
    compile 'org.jetbrains:annotations-java5:15.0'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.afollestad:assent:0.2.5'
    compile 'uk.co.samuelwall:material-tap-target-prompt:1.6.3'
}

```
 
###### Reproduction Steps

1. Update MaterialDialogs version to 0.9.2.1
2. Try to debug your app
3. I get this error in gradle console

###### Expected Result
The build could be built and started on the device

###### Actual Result
The debug build cannot be compilate

**Comment by afollestad** [comment]
That log isn't related to this library.

You should check that you're using 25.0.1 of Build Tools, the newer Gradle plugin, etc.
