### ISSUE TITLE
How to customize the overlay color ?

### ISSUE THREAD

**Issue by kuno** [afollestad/material-dialogs#1259]
Sorry, I did not find any other easy way to ask such question.

How to customize the color or  transparency value for the overlay that beneath the dialog?

**Comment by afollestad** [comment]
You can't make dialogs transparent.

**Comment by kuno** [comment]
@afollestad 

I dont mean the diaog itself, I mean the dark overlay underneath the dialog
![readmeshowcase](https://cloud.githubusercontent.com/assets/161327/21880457/0ccc9fc8-d8da-11e6-9e28-8b756daf0dc2.png)

**Comment by afollestad** [comment]
Ah, that's a system thing that I don't have control over
