### ISSUE TITLE
goUpLabel is not always applied on FolderChooserDialog if user defined

### ISSUE THREAD

**Issue by Canuck5x6** [afollestad/material-dialogs#1261]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.2.3`
 - Device OS version: various, mostly marshmallow, lollipop
 - Device Manufacturer: Various

###### Expected Result
Dialog should display the user designated text intended to indication "go to previous folder" such as a ⤴ character.

###### Actual Result
goUpLabel is always "..."

Noted the likely issue in method getContentsArray of FolderChooserDialog which reads as shown below.  (Note emphasis on Line 60):

```java
   String[] getContentsArray() {
        if (parentContents == null) {
            if (canGoUp)
                return new String[]{getBuilder().goUpLabel};
            return new String[]{};
        }
        String[] results = new String[parentContents.length + (canGoUp ? 1 : 0)];
        if (canGoUp) results[0] = "...";  // **<-- likely needs to read: getBuilder().goUpLabel;**
        for (int i = 0; i < parentContents.length; i++)
            results[canGoUp ? i + 1 : i] = parentContents[i].getName();
        return results;
    }
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
