### ISSUE TITLE
Sample DatePicker has unwanted Margin

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#1264]
I try to add a DatePicker with MaterialDialogs like shown in the sample application.
However it does not really fit and has small spacing on the sides which doesn't look good.

<img src="https://cloud.githubusercontent.com/assets/743462/21991832/6d8ecb5a-dc14-11e6-8025-02c2d101949a.png" width="300" />

Without setting a title its even more visible:

<img src="https://cloud.githubusercontent.com/assets/743462/21991893/abc7da06-dc14-11e6-8bce-99c50aadefca.png" width="300" />

Version 0.9.2.3, Nexus 5X, Android 7.1.1

**Comment by afollestad** [comment]
I'm open to PRs to fix such issues.

**Comment by PaulWoitaschek** [comment]
I think this is not trivial. The calendar view does not resize. Thus to make this fit the library needs to have a switch to turn off the n-dp grid resizing.

If I understand correctly.

**Comment by afollestad** [comment]
This problem actually occurred before I added the recent width limiting code.

**Comment by afollestad** [comment]
But yes, wrapping the calendar tightly would be a solution.

**Comment by PaulWoitaschek** [comment]
And how can I wrap it?

**Comment by afollestad** [comment]
That's logic which would have to be implemented.

Probably checking if a custom view's measured width is less than the default dialog width?

**Comment by PaulWoitaschek** [comment]
I'm not sure if that is a good solution.

Most views are resizable. For example if I just display a single word I'm fine with the dialog being wider than the world. A builder option with an ugly name so you know this should not be the default would be good.

like `forceWidthToCustomViewWidth(force: Boolean)`

**Comment by afollestad** [comment]
You can check the measure spec of a view to see if the user used `wrap_content`, `match_parent`, or an explicit `px`/`dp` value.

**Comment by afollestad** [comment]
Automatic is always better IMO, when possible

**Comment by PaulWoitaschek** [comment]
But lets say its a textview with the word `me`. You set it to `wrap_content` and it is like 50dp wide. Now you would set the dialog to that width?
Can you describe in which case you would make the dialog wrap tightly?

**Comment by afollestad** [comment]
Hmm, yeah, good point.

**Comment by PaulWoitaschek** [comment]
Any progress on this?

**Comment by afollestad** [comment]
No, I don't have much time for open source work.

**Comment by afollestad** [comment]
Closing in favor of https://github.com/afollestad/material-dialogs/issues/1282
