### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by jrvansuita** [afollestad/material-dialogs#1266]
Hey, how can I apply some show up animation on the dialog? I'm showing a dialog when click on FAB, are there some animations that can be applied to show the dialog like the circular, fade-in...?

**Comment by afollestad** [comment]
Not built in, no. 

Implementation is up to you. `MaterialDialog` is just a `android.app.Dialog` instance.

**Comment by jrvansuita** [comment]
Do you have any tips on how to do that using this library?
