### ISSUE TITLE
Setting content using a String Resource ID ignores new line characters.

### ISSUE THREAD

**Issue by akm0012** [afollestad/material-dialogs#1268]
###### Include the following:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `HTC`
 - Device Name: `Nexus 9`

When setting the content using a pure string resource id, it was ignoring `\n` characters in my `strings.xml` file. However, if I resolve the String using `context.getString(R.string.xzy)` then use that String, it works fine. 

Example: 

Works:
```java
new MaterialDialog.Builder(this)
                        .title(R.string.terms_conditions_title)
                        .content(getString(R.string.term_and_conditions))
                        .positiveText(R.string.ok)
                        .show();
```

Does not work (New lines are not shown in dialog):
```java
new MaterialDialog.Builder(this)
                        .title(R.string.terms_conditions_title)
                        .content(R.string.term_and_conditions)
                        .positiveText(R.string.ok)
                        .show();
```
 
###### Reproduction Steps

1. Add a strings.xml resource with some `\n` characters in it. 
2. Use that same resource when creating the dialog using:`.content(R.string.term_and_conditions)` 
3. View the dialog. 

###### Expected Result
Dialog should show with all the new lines represented in the text. 

###### Actual Result
The new lines are ignored and everything is squished into one nasty wrapping paragraph. 

Love the Library! Not a huge issue as there is an easy work around. But figured I'd do my due diligence and let you know.

**Comment by afollestad** [comment]
You're not using the latest version.
