### ISSUE TITLE
Disable/Enable Dividers between list items

### ISSUE THREAD

**Issue by abselt** [afollestad/material-dialogs#1274]
Hi, how to add dividers between list item in list dialog like what consedered a problem here in issue 74
https://github.com/afollestad/material-dialogs/issues/74
thanks for this awesome work.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

**Comment by afollestad** [comment]
This library intends to follow the Material specs, which don't include dividers in list dialogs.

You can add them manually through a custom adapter if you wish.
