### ISSUE TITLE
Global android:fontFamily is ignored

### ISSUE THREAD

**Issue by 64696765** [afollestad/material-dialogs#1280]
If I use a global fontFamily in styles.xml to use another **build-in** font (not from assets) this 
will be ignored

```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
  <item name="android:fontFamily">sans-serif-condensed</item>
</style>
```
Is there a way to define a global fontFamily without using fonts from assets?

**Comment by afollestad** [comment]
There are more than 1 fonts used by default from layouts in this library. `sans-serif-medium` and `sans-serif-light` included.

I do not plan to make dialogs pull from `android:fontFamily` for all views.

**Comment by 64696765** [comment]
doubtful reason, so the lib is useless for us

**Comment by afollestad** [comment]
¯\(ツ)/¯ ﻿ I don't lose anything really. It's open source. Do what you will.
