### ISSUE TITLE
Filtering the items in a list-dialog

### ISSUE THREAD

**Issue by nasuellia** [afollestad/material-dialogs#1281]
Hi Aidan,

I have a situation where the number of elements I need to show in a list-dialog is overwhelmingly high and I'd like to provide the user with a search field so that he can filter the available choices. 

From what I understand, your builder's custom-views are just for inflating xml layouts, but I can't associate code with anything, right?

I know the library (which is beyond awesome) is not designed for overly complex scenarios, so I don't expect it to be possible, but hey, maybe I'm just missing something huge here!

**Comment by afollestad** [comment]
That's very possible, you just need to make a custom layout which includes the search field and list below it. Your custom list adapter could do filtering for you.
