### ISSUE TITLE
MaterialDialog does not wrap content with custom view

### ISSUE THREAD

**Issue by odin-** [afollestad/material-dialogs#1282]
- Material Dialogs version: `0.9.2.3`
 - API: `25`
 - Device Manufacturer: `Android`
 - Device Name: `Nexus 7` / `Android Emulator`

I invoke a MaterialDialog with my custom view:

```java
   new MaterialDialog.Builder(myActivity)
   .customView(view, false)
   .negativeText(R.string.dialog_user_profile_button)
   .title(user.getHandle())
   .show();
```

The problem is that the contents isn't wrapped, i.e. I the right margin is wider than the left. 

(This is a problem in AppCompat AlertDialog also).

**Comment by odin-** [comment]
Seems to be a duplicate of #552

**Comment by afollestad** [comment]
I would say it's more of a duplicate of https://github.com/afollestad/material-dialogs/issues/1264, but slightly different.

However, dialogs will look best if your custom views fill the width of the dialogs. I use the specs from the Material Design guidelines for the width of dialogs.

**Comment by odin-** [comment]
Thanks for the input. I'll try to redesign the layout. Although it might be a not so good solution as I need to rework the content to the dialog, not sure it'll look great.

For AlertDialog I use AlertDialog.getWindow().setLayout to force the width. Can I do similar with MaterialDialog?

**Comment by PaulWoitaschek** [comment]
I'd be happy if this gets implemented. I'm using a system component so I can't redesign the layout.

**Comment by AlejandroHCruz** [comment]
I subscribe to this since I require a taller dialog than the standard one.

Being able to call something like this on the dialog might help, as @odin- said

`dialog.getWindow().setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.WRAP_CONTENT);`

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0
