### ISSUE TITLE
 Error retrieving parent for item

### ISSUE THREAD

**Issue by yogeshlokare7** [afollestad/material-dialogs#1283]
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

After using this library,i am getting such error...
Before using this library i use previous version of this(7).

This is my .xml code line
<style name="Base.TextAppearance.AppCompat.Widget.ActionBar.Menu" parent="android:TextAppearance.Material.Widget.ActionBar.Menu"/>

**Comment by afollestad** [comment]
That's unrelated to this library.

You're probably using a version of AppCompat in your app that's a mismatch to the version used by this library.

**Comment by yogeshlokare7** [comment]
ok. Thanks #afollestad
