### ISSUE TITLE
No solution to detect cancel of FileChooserDialog 

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1284]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.2.3'
 - Device OS version: `7.0`
 - Device Manufacturer: `Emulator`

I cannot find a way to detect a "cancel' action on the provided FileChooserDialog (and FolderChooserDialogs). How to detect this?
There is only a listener 'onFolderSelection' called when a folder or file is selected but the builder does not provide ways to set a 'cancelListener' or 'dismissListener'...

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.3.0

**Comment by afollestad** [comment]
The interface implemented in the Activity used to open the chooser now has a dismiss method.
