### ISSUE TITLE
Hide private resources

### ISSUE THREAD

**Issue by jrvansuita** [afollestad/material-dialogs#1286]
It's common hiding the private resources on an android library to avoid showing a lot of library resources when a developer use the code completion on Android Studio. You should take a look.

[How to hide private resources?](https://www.youtube.com/watch?v=_Rox-HXhRfI&feature=youtu.be&t=144)

<img width="392" alt="captura de tela 2017-02-06 as 10 26 44" src="https://cloud.githubusercontent.com/assets/12175215/22653237/d1cef94e-ec56-11e6-8dcb-bbefc18a1dc0.png">

I tried to do it and pull, but couldn't clone your repository. Android Studio is showing me: 
Error:Cannot change dependencies of configuration ':sample:_debugAnnotationProcessor' after it has been resolved.

<img width="982" alt="captura de tela 2017-02-06 as 11 02 46" src="https://cloud.githubusercontent.com/assets/12175215/22654764/d3bbcbce-ec5b-11e6-9dd9-9d5a71525edd.png">

And, I know that some resources need to be public for developers use. It's better you than me to select them.

**Comment by afollestad** [comment]
I don't have anything in this code which is worth hiding.

**Comment by jrvansuita** [comment]
I meant, It's not for you. It's for who use your library. It's weird and ugly to use the code completion and see a lot of library resources appearing. There are a lot of resources that don't need to be shown.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
