### ISSUE TITLE
Basic dialog positive button does not appear on M devices

### ISSUE THREAD

**Issue by JGeraldoLima** [afollestad/material-dialogs#1287]
Hi, afollestad! First of all, fantastic job with this lib, congrats :)

So, I've already used this lib on another project and it worked perfectly, but now with a **M Device**, a basic point is not working for me :/

###### Include the following:
 - Material Dialogs version: `0.9.3.0`
 - Device OS version: `6.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto X Play`

Also, using:
 - compile version = 25 and respective appcompat and support design;
 - latest build tools version (**25.0.2**)

I have the following simple implementation for a location services alert dialog:

```java
public static void openEnableLocationServicesDialog(final Activity activity) {
        MaterialDialog.Builder builder = new MaterialDialog.Builder(activity)
            .title(R.string.notice)
            .content(R.string.enable_location_services)
            .positiveColorRes(R.color.colorPrimaryDark)
            .negativeColorRes(R.color.colorPrimaryDark)
            .positiveText(R.string.ok)
            .negativeText(R.string.cancel)
            .onPositive(new MaterialDialog.SingleButtonCallback() {
                @Override
                public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                    final Intent i = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
                    activity.startActivity(i);
                    dialog.dismiss();
                }
            })
            .onNegative(new MaterialDialog.SingleButtonCallback() {
                @Override
                public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                    showSnackBar(activity, getString(activity, R.string.locations_permission_denied_msg));
                    dialog.dismiss();
                }
            });

        MaterialDialog alertDialog = builder.build();
        alertDialog.show();
    }
```
 
but, I'm getting this result (this should be showing **CANCELAR** and **OK** respectively):

![device-2017-02-07-015517](https://cloud.githubusercontent.com/assets/6726996/22678409/facfaa0c-ece0-11e6-921f-8653424fb7c5.png)

And I really cannot understand what's wrong! I have almost the same implementation (just the callbacks implementations are different) of this dialog function I it works perfectly on a  **Lollipop-** device! Could you check this out?

**(this is happening with all the other dialogs implementation I'm using, and they have the same appearance, i.e., positive and negative buttons)**

**Comment by JGeraldoLima** [comment]
I've searched for differences on the sample dialogs implementation and on mine, and I realized that on the sample you do not set onPositive and onNegative callbacks, just the texts. So, I did the same but the bug keeps happening! I really can't figure out what's going on 😔

**Comment by powerhcm8** [comment]
Try putting a string directly instead of a Resource id.

**Comment by JGeraldoLima** [comment]
Oh man, great ideia! Just hold two or three days while I finish home moving, so I'll be able to use my computer

**Comment by afollestad** [comment]
That shouldn't make a difference. Passing a string ID just indirectly uses the method which passes a String/CharSequence.

**Comment by afollestad** [comment]
I don't think is something I can fix. Sounds like a device-specific or manufacturer-specific bug.

**Comment by powerhcm8** [comment]
I was checking the source code and the `public Builder positiveText(@StringRes int positiveRes)` is slightly different from `neutralText` and `negativeText`.
The method `positiveText` returns this, while the others return the result of method that sets the text when a string is passed.
I know that this shouldn't make difference, but i think i could be related to the problem that @JGeraldoLima  is having.

**Comment by afollestad** [comment]
```java
public Builder positiveText(@StringRes int positiveRes) {
            if (positiveRes == 0) return this;
            positiveText(this.context.getText(positiveRes));
            return this;
}
```

and

```java
public Builder negativeText(@StringRes int negativeRes) {
            if (negativeRes == 0) return this;
            return negativeText(this.context.getText(negativeRes));
}
```

are completely equivalent. `negativeText` returns `this` also.

**Comment by JGeraldoLima** [comment]
Hi everyone! Sorry for the delay, I was out of internet!

So, I follow @powerhcm8 tip and it worked! I've tested several times, switching between stringID and string value and the button just appeared! Maybe it is some bug or particularity of M build, I really don't know...

```java
 public static void openEnableLocationServicesDialog(final Activity activity) {
        MaterialDialog.Builder builder = new MaterialDialog.Builder(activity)
            .title(R.string.notice)
            .content(R.string.enable_location_services)
            .positiveColorRes(R.color.colorPrimaryDark)
            .negativeColorRes(R.color.colorPrimaryDark)
            .positiveText(/*R.string.ok*/"OK")
            .negativeText(R.string.cancel)
            .onPositive(new MaterialDialog.SingleButtonCallback() {
                @Override
                public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                    final Intent i = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
                    activity.startActivity(i);
                    dialog.dismiss();
                }
            })
            .onNegative(new MaterialDialog.SingleButtonCallback() {
                @Override
                public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                    showSnackBar(activity, getString(activity, R.string.locations_permission_denied_msg));
                    dialog.dismiss();
                }
            });

        MaterialDialog alertDialog = builder.build();
        alertDialog.show();
    }
```

Result:
![device-2017-03-11-145234](https://cloud.githubusercontent.com/assets/6726996/23825546/9d08368e-066a-11e7-8a3d-6a24e8e954f3.png)

**Comment by oradkovsky** [comment]
I was observing such behavior when string resource was empty (like this <string name="app_ok"></string>).
