### ISSUE TITLE
FolderChooserDialog not showing the first directory

### ISSUE THREAD

**Issue by MGLaboratory** [afollestad/material-dialogs#1288]
It's a FileChooserDialog and first directory is "!"
![screenshot_2017-02-07-16-45-52](https://cloud.githubusercontent.com/assets/22342671/22686124/818395bc-ed55-11e6-904f-ccb7bcf8141b.png)

It's a FolderChooserDialog and where is no directory "!"
![screenshot_2017-02-07-16-46-12](https://cloud.githubusercontent.com/assets/22342671/22686125/8183cbea-ed55-11e6-924d-98520c16dcac.png)

But if I click on directory ".PolarisViewer5" the "!" direcory will be choosen.
and more.. if I click on any other directory will be choosen one position above directory. 
![screenshot_2017-02-07-16-46-16](https://cloud.githubusercontent.com/assets/22342671/22686126/818829ce-ed55-11e6-9829-97825c6b3d65.png)
Tested on real device and AVD. Result always the same. FolderChooserDialog don't show first directory in list (".esstrongs" on AVD).

My code:

new FileChooserDialog.Builder(MainActivity.this)                 .initialPath(Environment.getExternalStorageDirectory().getAbsolutePath())
                    .extensionsFilter(".xml")
                    .cancelButton(R.string.cancel)
                    .show();

new FolderChooserDialog.Builder(MainActivity.this)
                    .chooseButton(R.string.ok)
                    .initialPath(Environment.getExternalStorageDirectory().getAbsolutePath()) 
                    .allowNewFolder(true,R.string.dialog_new_folder)
                    .cancelButton(R.string.cancel)
                    .show();

Version: compile 'com.afollestad.material-dialogs:commons:0.9.3.0'

Example from Google Play works fine. I think that a bug in new version.

**# p.s. Rollback to v.0.9.1.0. Bug dissapear.**

and one wish: when no files in directory.. much better not to change dialog window height!

**Comment by peterhav** [comment]
Encountering the same issue in 0.9.3.0!

**Comment by afollestad** [comment]
@peterhav if it was fixed for 0.9.3.0, this issue would already be closed.

**Comment by javiersantos** [comment]
As @MGLaboratory says, bug is present in the latest v0.9.3.0. Rolling back to v0.9.2.3 fixes the issue for now.

**Comment by peterhav** [comment]
Would it be possible to release a new version of the library (0.9.3.1) that includes this fix?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
