### ISSUE TITLE
Permission Denied to copy file on selected Path

### ISSUE THREAD

**Issue by Ankurjain30** [afollestad/material-dialogs#1293]
I used your code to select folder and set its path as destination for copying file. While running code, i got permission denied. I selected SDCard path. I read if app choose path manually, it got permission to write/read that folder then why it is not working and giving same permission error. Am i missing something. Issue Faced with Asus Zenfone 5, Running on Kitkat 4, API 19. Manifest has Write External Permission and below is code:

public class MainActivity extends AppCompatActivity implements FolderChooserDialog.FolderCallback {
    TextView path;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button foldersel, copy;

        foldersel = (Button) findViewById(R.id.folder);
        copy = (Button) findViewById(R.id.copy);
        path = (TextView) findViewById(R.id.path);

        foldersel.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                showFolderChooser();
            }
        });

        copy.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                moveFile("/sdcard/Download/a.apk",path.getText().toString()+"/a.apk");
            }
        });

    }

    public void showFolderChooser() {

        if (ActivityCompat.checkSelfPermission(MainActivity.this, Manifest.permission.WRITE_EXTERNAL_STORAGE) !=
                PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(MainActivity.this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
            return;
        }
        new FolderChooserDialog.Builder(MainActivity.this)
                .chooseButton(R.string.md_choose_label)
                .allowNewFolder(true, 0)
                // changes label of the choose button
                .initialPath("/sdcard/Download")  // changes initial path, defaults to external storage directory
                .tag("optional-identifier")
                .goUpLabel("Up") // custom go up label, default label is "..."
                .show();
    }

    @Override
    public void onFolderSelection(@NonNull com.afollestad.materialdialogs.folderselector.FolderChooserDialog dialog, @NonNull File folder) {
        Toast.makeText(this, folder.getAbsolutePath(), Toast.LENGTH_SHORT).show();
        path.setText(folder.getAbsolutePath());
        final String tag = dialog.getTag(); // gets tag set from Builder, if you use multiple dialogs
    }

    @Override
    public void onFolderChooserDismissed(@NonNull FolderChooserDialog dialog) {

    }

    public void moveFile(String s, String d) {
        InputStream inStream = null;
        OutputStream outStream = null;

        try {

            File afile = new File(s);
            File bfile = new File(d);

            inStream = new FileInputStream(afile);
            outStream = new FileOutputStream(bfile);

            byte[] buffer = new byte[1024];

            int length;
            //copy the file content in bytes
            while ((length = inStream.read(buffer)) > 0) {

                outStream.write(buffer, 0, length);

            }

            inStream.close();
            outStream.close();

            //delete the original file
            afile.delete();

            System.out.println("File is copied successful!");
            //run();

        } catch (IOException e) {
            e.printStackTrace();

        }

    }
}
![permissiondenied](https://cloud.githubusercontent.com/assets/20257651/22851216/f1ea2684-f040-11e6-8d7a-35913006c259.PNG)

**Comment by afollestad** [comment]
The problem is a `FileNotFoundException`, that directory doesn't exist.
