### ISSUE TITLE
FeatureRequest: Add tint to icons

### ISSUE THREAD

**Issue by hardysim** [afollestad/material-dialogs#1295]
- Material Dialogs version: `0.9.3.0`

I want to be able to provide a tint to be used on the icons used for the dialog (for the icon in the title as well as the one used in a SimpleDialog-row).

###### Expected Result
The icon should be tinted in the given color. A builder would like like this:

```java
new MaterialDialog.Builder(context)
  .title(R.string.title)
  .content(R.string.content)
  .icon(R.drawable.my_vector_drawable)
  .tint(R.color.blue)
  .show();
```

or

```java
new MaterialSimpleListItem.Builder(context)
  .content(R.string.content)
  .icon(R.drawable.my_vector_drawable)
  .tint(R.color.blue)
  .iconPaddingRes(R.dimen.simple_dialog_icon_padding)
  .backgroundColor(ContextCompat.getColor(context, R.color.control_default_light))
  .build();
```

###### Actual Result
The icon is just using the color defined in the given VectorDrawable (e.g. white) which results in an invisible icon (white background on the dialog).

---

Currently, I'm using two versions of the same icon-XML (one black, one white) as I'm using the same icon as the title-icon (`.setIcon()`) and as the icon for a *SimpleDialog* (`MaterialSimpleListItem.Builder().icon()`).

**Comment by afollestad** [comment]
@hardysim for `MaterialDialog`, I don't feel that is necessary to have as a library feature. You should do tinting before setting the icon.

```java
Drawable icon = //...
icon = DrawableCompat.wrap(icon);
DrawableCompat.setTint(icon, ColorStateList.valueOf(color));
...
```

For the simple list dialog, you mean this? https://github.com/afollestad/material-dialogs/pull/1267

**Comment by hardysim** [comment]
> You should do tinting before setting the icon.

Your code seems to work (for both use-cases), nice.

> For the simple list dialog, you mean this? #1267

Maybe. I'm not 100% sure whats the advantage of the `ColorStateList` instead of using the (pre-tinted) icon and the backgroundColor. Is it possible to have a multi-color icon tinted using the ColorStateList (then this would be a great addition)?

---

For now, I'm happy (tested on API 19 and 25) with your solution.
_But I've added a `.mutate()` to the drawable because I had problems using a tinted icon in a ListView._

**Comment by eygraber** [comment]
I would love to see this feature. I hate adding Drawable cruft when a simple color resource int does the same thing.
