### ISSUE TITLE
Crash because Objects class was introduced in API 19, affecting all previously APIs

### ISSUE THREAD

**Issue by javiersantos** [afollestad/material-dialogs#1300]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.3.0`
 - Device OS version: `4.x`
 - Device Manufacturer: `Unknown`
 - Device Name: `Unknown`

###### Reproduction Steps

1. Create a `FolderChooserDialog`.
2. Show the `FolderChooserDialog` on API < 19.

###### Expected Result

1. The dialog is shown.

###### Actual Result

1. It crashes.

###### Log

```
Fatal Exception: java.lang.NoClassDefFoundError: java.util.Objects
       at com.afollestad.materialdialogs.folderselector.FolderChooserDialog.onCreateDialog(SourceFile:128)
       at android.support.v4.app.DialogFragment.getLayoutInflater(SourceFile:312)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1299)
       ...
```

###### More info

According to this [Stackoverflow post](http://stackoverflow.com/questions/28613784/noclassdeffounderror-java-util-objects-android), the `Objects` class was introduced in the API 19, so a `NoClassDefFoundException` is thrown when using a previous Android version.

`Objects` class is used in `FolderChooserDialog.java`: https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/java/com/afollestad/materialdialogs/folderselector/FolderChooserDialog.java#L135

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
