### ISSUE TITLE
How can you disable the dialog from being dismissed by clicking on the device hardware back button?

### ISSUE THREAD

**Issue by abhishek1508** [afollestad/material-dialogs#1303]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Using your own key event listener or by overriding onBackPressed() in your Activity. This isn't an issue specific to this library, search StackOverflow.

**Comment by webserveis** [comment]
In my custom dialogs, I use `@onResume` with `DialogInterface.OnKeyListener()`

```java
public class MyCustomDialog extends DialogFragment 
   ....
    @Override
    public void onResume() {
        super.onResume();

        getDialog().setOnKeyListener(new DialogInterface.OnKeyListener() {
            @Override
            public boolean onKey(DialogInterface dialog,
                                 int keyCode, android.view.KeyEvent event) {
                if ((keyCode == android.view.KeyEvent.KEYCODE_BACK)) {
                    dismiss();
                    return true;
                } else return false;
            }
        });
    }
```
If you like this implementation, add this feature in library
