### ISSUE TITLE
how can I use spinner with this library?

### ISSUE THREAD

**Issue by Reegan01** [afollestad/material-dialogs#1304]
Hi,

This is awesome and thank you for your creativity and open source. 

I have a doubt. Is you having any spinner with this library? Normal spinner is isn't good, Or can you suggest any Material library for spinner?

**Comment by afollestad** [comment]
I'm not really sure what you mean. This library is specifically for dialogs. You could use a custom layout if you want a spinner inside of a dialog.

**Comment by Reegan01** [comment]
Thank you for your reply

Oh, okay. Actually I mean, I used EditText `<TextInputLayout><TextInputEditText></TextInputEditText</TextInputLayout>` on this dialog. It looks good. But normal spinner is isn't adapt with it.

**Comment by afollestad** [comment]
What do you mean by adapting with it?
