### ISSUE TITLE
How to set animation?

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1305]
Hi
How to set animation to show and hide of Dialog?

**Comment by afollestad** [comment]
https://www.google.com/search?q=dialog+animations+android

**Comment by AlirezaGhanbarinia** [comment]
i need to set animation to  MaterialDialog,not the android sdk dialog.
for example add ".setAnimation(...)"
 to this builder.
new MaterialDialog.Builder(this)
        .title(R.string.title)
        .content(R.string.content)
        .positiveText(R.string.agree)
        .negativeText(R.string.disagree)
        .show();

**Comment by afollestad** [comment]
`MaterialDialog` is an `android.app.Dialog`.

**Comment by afollestad** [comment]
You'll have to build the dialog before showing it.
