### ISSUE TITLE
Set Gravity

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1306]
How to set Gravity to MaterialSimpleListItem ?
and How to set size to icon?

**Comment by afollestad** [comment]
Explicit gravity isn't supported. It will automatically go to RTL on devices which are using RTL languages (on API 16+).

The size is static and from the Material Design specs. `"@dimen/md_simplelist_icon`

**Comment by AlirezaGhanbarinia** [comment]
I want to set gravity for MaterialSimpleListItem.there is no method to set gravity for this item:
adapter.add(new MaterialSimpleListItem.Builder(this)
    .content("username@gmail.com")
    .icon(R.drawable.ic_account_circle)
    .backgroundColor(Color.WHITE)
    .build());

if possible i need to set 
.contentGravity(GravityEnum.CENTER)

to the above builder.
another thing to say, I have set android:supportsRtl="false" in manifest of my app and i need this case to be false.

**Comment by AlirezaGhanbarinia** [comment]
any Help?
are you going to add this in next update or i should handle it?

**Comment by ifnyas** [comment]
@AlirezaGhanbarinia Do you find the workaround for setting gravity? I also need to change the gravity of the simple list from start to center
