### ISSUE TITLE
Change ActionBar Color for Fragment

### ISSUE THREAD

**Issue by Ankurjain30** [afollestad/material-dialogs#1307]
I m trying to change color for fragment below is theme defined for fragment having activity and prefFragment.
<style name="FragTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:textColor">#000000</item>
        <item name="preferenceTheme">@style/PreferenceThemeOverlay.v14.Material</item>
           </style>

This is what i m using but getting error, pls guide.

 new ColorChooserDialog.Builder(getActivity(),R.string.color_palette)
                        .titleSub(R.string.colors)
                        .preselect(startuppri)
                        .show();

Error Over getActivity, it is not acceptable here by Builder.

**Comment by afollestad** [comment]
You need to cast `getActivity()`, e.g. (MainActivity)getActivity()

**Comment by Ankurjain30** [comment]
Still getting error "inconvertible types, cannot cast 'android.support.v4.app.fragmentActivity to packagename.myjavaclassname

Few classes imported:
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.ActionBarActivity;
import android.support.v7.app.AlertDialog;
import android.support.v7.preference.PreferenceManager;

Updated Code used as ((ALR)getActivity(),R.string.color_palette), ALR.java is class name extends to Fragment and implementing ColorChooserDialog.

**Comment by Ankurjain30** [comment]
Full code:


import android.content.SharedPreferences;
import android.graphics.drawable.ColorDrawable;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.ColorInt;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v7.app.ActionBarActivity;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.afollestad.materialdialogs.color.CircleView;
import com.afollestad.materialdialogs.color.ColorChooserDialog;
import com.afollestad.materialdialogs.internal.ThemeSingleton;
import com.afollestad.materialdialogs.util.DialogUtils;


public class Frag1 extends Fragment implements ColorChooserDialog.ColorCallback {
    private int startuppri, startuppridark;
    @ColorInt
    int existingpricolor;
    TextView tv;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.frag1, container, false);
        
        tv= (TextView) view.findViewById(R.id.tvfrg1);
        //Code for Color
        startuppri = DialogUtils.resolveColor(getActivity(), R.attr.colorPrimary);
        startuppridark = DialogUtils.resolveColor(getActivity(), R.attr.colorPrimaryDark);

        SharedPreferences sharedPreferences5 = android.preference.PreferenceManager.getDefaultSharedPreferences(getActivity());
        existingpricolor = sharedPreferences5.getInt("wrucolor", startuppri);

        startuppri = existingpricolor;
        if (((ActionBarActivity) getActivity()).getSupportActionBar() != null)

        {
            ((ActionBarActivity) getActivity()).getSupportActionBar().setBackgroundDrawable(new ColorDrawable(existingpricolor));
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                getActivity().getWindow().setStatusBarColor(CircleView.shiftColorDown(existingpricolor));
                getActivity().getWindow().setNavigationBarColor(existingpricolor);
            }
        }

        tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new ColorChooserDialog.Builder(((Frag1)getActivity()),R.string.color_palette)
                        .titleSub(R.string.colors)
                        .preselect(startuppri)
                        .show();
            }
        });
        return view;

    }

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        inflater.inflate(R.menu.frag1_menu, menu);
    }


    @Override
    public void onColorSelection(@NonNull ColorChooserDialog dialog, @ColorInt int selectedColor) {
        SharedPreferences.Editor editor = android.preference.PreferenceManager.getDefaultSharedPreferences(getActivity()).edit();
        if (dialog.isAccentMode()) {
            startuppri = selectedColor;
            ThemeSingleton.get().positiveColor = DialogUtils.getActionTextStateList(getActivity(), selectedColor);
            ThemeSingleton.get().neutralColor = DialogUtils.getActionTextStateList(getActivity(), selectedColor);
            ThemeSingleton.get().negativeColor = DialogUtils.getActionTextStateList(getActivity(), selectedColor);
            ThemeSingleton.get().widgetColor = selectedColor;
            editor.putInt("wrucolor", startuppridark).apply();
        } else {
            startuppri = selectedColor;
            if (((ActionBarActivity) getActivity()).getSupportActionBar() != null)
                ((ActionBarActivity) getActivity()).getSupportActionBar().setBackgroundDrawable(new ColorDrawable(selectedColor));
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                getActivity().getWindow().setStatusBarColor(CircleView.shiftColorDown(selectedColor));
                getActivity().getWindow().setNavigationBarColor(selectedColor);
            }
            editor.putInt("wrucolor", startuppri).apply();
        }
    }

    @Override
    public void onColorChooserDismissed(@NonNull ColorChooserDialog dialog) {

    }
}
