### ISSUE TITLE
Question: Passing data to a input dialog from database

### ISSUE THREAD

**Issue by Berlon** [afollestad/material-dialogs#1308]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [x ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.3.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Google`
 - Device Name: `Galaxy S7`

Also, please wrap Java with correct syntax highlighting.

Hello,
The question is how would I open a dialog from a listview click and populate a  input dialog with data from my database?

**Comment by afollestad** [comment]
Implementation is up to you. The issue tracker is used for bugs and new features.
