### ISSUE TITLE
Indeterminate progress dialog spinner shifts to the right when there is no content

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#1313]
Hi,

I'm experiencing some issues using the code below:

```java

    MaterialDialog mProgress = new MaterialDialog.Builder(mContext)
            .title("Title")
            .progress(true, 0)
            .positiveText("Cancel")
            .onPositive(new MaterialDialog.SingleButtonCallback() {
                @Override
                public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                    //Code
                }
             })
            .showListener(new DialogInterface.OnShowListener() {
                @Override
                public void onShow(DialogInterface dialogInterface) {
                    //Code
                }
             })
            .buttonsGravity(GravityEnum.CENTER)
            .progressIndeterminateStyle(true)
            .autoDismiss(true)
            .cancelable(false)
            .show();

```

Progress circle is shifted to the right and action buttons do not change their position. How to solve?

**Comment by afollestad** [comment]
That doesn't appear to be the correct code you posted above. There is no use of `.progress(boolean, int)` and you are specifying horizontal indeterminate style.

**Comment by afollestad** [comment]
A horizontal indeterminate progress dialog looks like this:

![capture](https://cloud.githubusercontent.com/assets/1820165/24077593/c32ed74e-0c20-11e7-820f-15161c088474.PNG)

**Comment by afollestad** [comment]
Ah, I see the problem now after using the right code:

![capture](https://cloud.githubusercontent.com/assets/1820165/24077600/e2ffb836-0c20-11e7-817f-1e5a5be22c6b.PNG)

**Comment by afollestad** [comment]
It's actually not related to action button gravity at all. It's related to not having any content. It works fine if you add content:

![capture](https://cloud.githubusercontent.com/assets/1820165/24077896/b3cece08-0c2a-11e7-9aa7-ba2a4654cda6.PNG)

**Comment by afollestad** [comment]
@peppe130 fixed the underlying issue, the progress spinner will be in the correct position if you specify no content. You should however use content *instead* of a title in your case above.

Regarding the button gravity, this is how it works: https://github.com/afollestad/material-dialogs#gravity

**Comment by peppe130** [comment]
@afollestad Thank you so much.
