### ISSUE TITLE
How to use FileChooserDialog in a fragment?

### ISSUE THREAD

**Issue by swapnilsaha2010** [afollestad/material-dialogs#1314]
I am using FileChooserDialog in a fragment but getting error for getActivity(). How to solve the problem?

```java
FileChooserDialog.Builder builder = new FileChooserDialog.Builder(getActivity())
                        .show();
```

###### Using the following:
 - Material Dialogs version: `0.8.5.6`
 - Device OS version: `5.1`

**Comment by afollestad** [comment]
Cast `getActivity()` to your Activity.
