### ISSUE TITLE
Dissmis on item clicked

### ISSUE THREAD

**Issue by abbasamini** [afollestad/material-dialogs#1317]
Hi 
i use Recyclerview to show item 
            dialog = new MaterialDialog.Builder(this)
                    .backgroundColor(Color.parseColor("#a3f9fa"))
                    .title("test")
                    .adapter(new Adapter(item,this),null)
                    .titleGravity(GravityEnum.START)
                    .build();
How To dismiss dialog when click on Item recycle view

**Comment by afollestad** [comment]
Read over the tutorial, use item callbacks.

**Comment by abbasamini** [comment]
i use Custom List Dialogs and when Use item Callback dialog don't dismiss

**Comment by afollestad** [comment]
From https://github.com/afollestad/material-dialogs#custom-list-dialogs?

Well you must be handling the click logic on your own, so you can `dismiss()` it from there.

---


If you're using a single choice dialog, you can use `alwaysCallSingleChoiceCallback()` to invoke the callback every time an item is checked or unchecked.
