### ISSUE TITLE
can't change ".input" EditText underline color

### ISSUE THREAD

**Issue by KhalidElSayed** [afollestad/material-dialogs#1318]
I'm showing dialog with input using ".input" and I want to change the edittext underline color but I can't change it neither using .widgetColor nor using "md_widget_color".

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `5.0.1`
 - Device Manufacturer: `Sony`
 - Device Name: `M4 Aqua`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Unfortunately this may be a manufacturer-specific (Sony) issue that I won't be able to fix.

**Comment by afollestad** [comment]
Also, you are using a very old version of the library, so that second checkbox there does not apply.

**Comment by kaushalyap** [comment]
@afollestad I also want to change the underline color, is there any way? I checked theming section there is non to change this

**Comment by kaushalyap** [comment]
Found a way
`<item name="android:colorControlActivated">@color/colorPrimary</item>`
