### ISSUE TITLE
Set custom views

### ISSUE THREAD

**Issue by EpsilonOrionis** [afollestad/material-dialogs#1319]
I'm using a custom layout, but I want to pre-set the value of a seekbar to make it start at a certain value. But I don't want to do it in the xml layout file because the value will change based on user usage. How can I do this?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#later-access

**Comment by EpsilonOrionis** [comment]
This is to access later, I want to access before

**Comment by afollestad** [comment]
Then you inflate the View before building the dialog and pass in the inflated view.

**Comment by EpsilonOrionis** [comment]
Could you give me an example please?

**Comment by afollestad** [comment]
```java
LayoutInflater li = LayoutInflater.from(context);
View view = like.inflate(R.layout.name, false);
// Setup view
new MaterialDialog.Builder(context)
   .customView(view, ...)
   .show();
```

**Comment by afollestad** [comment]
Actually, using "Later Access" is what you should do. You just show the dialog after setting the view up.

**Comment by afollestad** [comment]
```java
MaterialDialog dialog = new MaterialDialog.Builder(context)
   .customView(R.layout.name, ...)
   .Build();

View view = dialog.getCustomView();
// Setup view

dialog.show();
```

**Comment by afollestad** [comment]
Both of the above are equivalent.

**Comment by EpsilonOrionis** [comment]
Ok thank you, I'll try tomorrow and I'll tell you if I solved the problem 😄

**Comment by EpsilonOrionis** [comment]
It works 👍
