### ISSUE TITLE
ProgressDialog not showing spinner

### ISSUE THREAD

**Issue by AlvarVG** [afollestad/material-dialogs#1321]
- Material Dialogs version: `0.9.3.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `MI 5`

I know, you may say its duplicate, but Progress Dialog is not working on my application and neiter on yours. 

![screenshot_2017-03-02-09-32-45-358_com afollestad materialdialogssample 1](https://cloud.githubusercontent.com/assets/5830274/23499184/6a1c5034-ff2b-11e6-8a77-12695f09be2b.png)
![screenshot_2017-03-02-09-32-25-897_asti es sigatterminales 1](https://cloud.githubusercontent.com/assets/5830274/23499190/6ed83b92-ff2b-11e6-909c-db753ae746da.png)

```java
            mProgressDialog = new MaterialDialog.Builder(activity)
                    .content(R.string.database_realizando_consulta)
                    .progress(true, 0)
                    .cancelable(false)
                    .widgetColor(
                            ContextCompat.getColor(getApplicationContext(), R.color.colorPrimary))
                    .build();
            mProgressDialog.show();
```

I have been checking all the duplicated issues, but i havent seen the solution for dumm people. I will really apreciate it.

Thank you in advance for the library.

**Comment by afollestad** [comment]
There may not be a solution, this may be an issue specific to Xiaomi devices.

**Comment by AlvarVG** [comment]
I have also checked on a different terminal. The model is a Zebra TC51. You sample application and mine. The result is that your application work fine, but mine does not. I dont know if this gives to you some light. 

And also, you may know that a week ago, i had the progress dialog working fine. 

I will try to install it on different terminal, yours and mine, and write it down here.

**Comment by AlvarVG** [comment]
I have tested on two different terminals. As i mentioned above, on the Zebra TC51, if the dialog is not show in enough time, the animation is not visible, but if there is time to show it it will appear. 
In othe terminal i have check, is the Huawei P9 Lite (also with a modified version of Android [EMUI]), and it works fine.

Xiaomi, with his, MIUI version (MI 5 is updated to version 8) modifies something that does not make Dialog to show properly. Maybe talking with MIUI developers, we could have some idea of what happens.

**Comment by afollestad** [comment]
I think this is probably an issue to report to https://github.com/DreaminginCodeZH/MaterialProgressBar
