### ISSUE TITLE
Load Custom Layout in Dialog in Fragment

### ISSUE THREAD

**Issue by Ankurjain30** [afollestad/material-dialogs#1324]
Why MaterialDialog materialDialog = new MaterialDialog.Builder(getActivity().getApplicationContext()); does not work in Fragment. When i can used getApplicationContext in Activity, 

Pls guide how to fix it so that i can use customview for dialog. There is one more thing, if i use 

MaterialDialog.Builder materialDialog = new MaterialDialog.Builder(getActivity().getApplicationContext());

it start accepting context and load dialog also, but then i could not able to initialize using
locviainternet = (RadioButton) materialDialog.getCustomView().findViewById(R.id.locviainternet);

as materialDialog.getCustom does not come.

**Comment by afollestad** [comment]
Don't use application context, it needs​ a window to attach to.

**Comment by Ankurjain30** [comment]
Then how to handle it

**Comment by afollestad** [comment]
Only use`getActivity()`.  An activity is a context when it comes to the fundamentals of Android.

**Comment by Ankurjain30** [comment]
MaterialDialog materialDialog = new MaterialDialog.Builder(getActivity()); does not work.

**Comment by Ankurjain30** [comment]
and if i use 

 MaterialDialog.Builder materialDialog = new MaterialDialog.Builder(getActivity());
                              materialDialog.customView(R.layout.getlocationvia, true)
                                .positiveText("Continue")
                                .positiveColor(Color.BLUE)
                                .neutralColor(Color.RED)
                                .neutralText("Cancel")
                                .onPositive(new MaterialDialog.SingleButtonCallback() {
                                    @Override
                                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                                        if (truefr.isChecked()) {
                                       
                                            }
                                        } else if (trd.isChecked()) {
                                          
                                            }
                                        }
                                    }
                                })

                                .show();

                        locviainternet = (RadioButton) materialDialog.getCustomView().findViewById(R.id.locviainternet);
                        locviasms = (RadioButton) materialDialog.getCustomView().findViewById(R.id.locviasms);
                        viacheckpref = (CheckBox) materialDialog.getCustomView().findViewById(R.id.viapref);

Then All below gives error 

     locviainternet = (RadioButton) materialDialog.getCustomView().findViewById(R.id.locviainternet);
                        locviasms = (RadioButton) materialDialog.getCustomView().findViewById(R.id.locviasms);
                        viacheckpref = (CheckBox) materialDialog.getCustomView().findViewById(R.id.viapref);

for .getCustomView

**Comment by afollestad** [comment]
getActivity() definitely works. 

There must be an issue somewhere on your end, but it's not related to this library.

**Comment by Ankurjain30** [comment]
fixed, i put ; by mistake in end of getActivity. Sorry to bother you.
