### ISSUE TITLE
Class not found exception java.util.Object

### ISSUE THREAD

**Issue by handysofts** [afollestad/material-dialogs#1325]
on new version of lib throws class not found exception while opening FolderChooser dialog

**Comment by afollestad** [comment]
There's not really enough information here to make an issue.

If the object class isn't found, that sounds like an issue on your end.

**Comment by handysofts** [comment]
Thanks for quick reply. But as you said in document the minimum API level supported by this library is API 13
But while I am using latest version of your lib and min api 15 (on my side) your library throws error while open folder dialog "NoClassDefFoundError: java.util.Objects Android" as I know android supports java.util.Object class since api level 19.

if this info also not enough to explain issue we can talk on skype (vasif.mustafayev)

**Comment by afollestad** [comment]
Oh, this was already fixed. https://github.com/afollestad/material-dialogs/issues/1300

Not released though.

**Comment by handysofts** [comment]
Great, today I have tried latest version and faced with given issue, then I selected old version and has published app.
We'll wait for your release

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
