### ISSUE TITLE
focusableInTouchMode causes view click issues

### ISSUE THREAD

**Issue by javiersantos** [afollestad/material-dialogs#1328]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

###### Reproduction Steps

1. Create and show a new FolderChooserDialog.

```Java
new FolderChooserDialog.Builder(context)
        .initialPath(appPreferences.getCustomPath())
        .chooseButton(android.R.string.ok)
        .cancelButton(android.R.string.cancel)
        .allowNewFolder(true, R.string.button_create_folder)
        .show();
```

###### Expected Result

1. The dialog buttons should work as expected.

###### Actual Result

1. The dialog buttons must be pressed two times in order to work.

![Screenshot](http://i.imgur.com/QpzRT66.png)

###### Notes
This bug has been introduced in the latest v0.9.4.0.

**Comment by javiersantos** [comment]
@afollestad, this issue is affecting all list dialogs.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.1
