### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1331]
hi
i can't understand what are your new version changes and features. would you please add a new section for "release notes" .
thank you.

**Comment by lolsheeplol** [comment]
@AlirezaGhanbarinia you can find release notes here: https://github.com/afollestad/material-dialogs/releases.  Every github repo has a section for these, see here: https://puu.sh/uKeC3/80b22336e4.png.  Click on "releases" and you can see the notes the developer has written about them.

**Comment by AlirezaGhanbarinia** [comment]
thank you.
