### ISSUE TITLE
Error:Module 'com.afollestad:material-dialogs:0.9.4.1' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by shahabyounas** [afollestad/material-dialogs#1332]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
You're not using the correct text for the dependency. Look at the project tutorial.
