### ISSUE TITLE
When does the single choice callback send -1 as a selection index?

### ISSUE THREAD

**Issue by odin-** [afollestad/material-dialogs#1334]
I got an error report from my app where `which` was -1 in `itemsCallbackSingleChoice#onSelection`.

Yes I should probably check for which >= 0 as I've seen your source code. Perhaps you could clarify this in the examples if you think this needed?

What I don't understand is why the error was triggered on this particular occasion. Do you got any ideas? Is there anything I need to know that I am missing. Using your lib pretty straightforward:

```java
new MaterialDialog.Builder(this)
   .title(locationText)
   .items(list)
   .itemsCallbackSingleChoice(index, new MaterialDialog.ListCallbackSingleChoice() {
      @Override
      public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
         ... list.get(which) ... /* which=-1 triggered the error, ArrayIndexOutOfBoundsException */
         return true;
      }
})
.positiveText(android.R.string.ok)
.negativeText(android.R.string.cancel)
.show();
```

**Comment by afollestad** [comment]
If I to guess, the user is pressing "OK" without selecting an option.

**Comment by odin-** [comment]
There's always something selected so I do not really understand how the user is able to selecting "nothing". But I'll just make sure to catch -1. 

Thanks.

**Comment by odin-** [comment]
My fault.... ignore everything above :-)
