### ISSUE TITLE
affolestd

### ISSUE THREAD

**Issue by lemani17** [afollestad/material-dialogs#1335]
Error:Failed to resolve: com.afollestad:material-dialogs:0.7.8.1

**Comment by afollestad** [comment]
Look at the front page of the project.

**Comment by lemani17** [comment]
The project code is Q-municate example

**Comment by afollestad** [comment]
No, this project.

https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by lemani17** [comment]
The project is this  https://github.com/QuickBlox/q-municate-android

**Comment by afollestad** [comment]
That's not relevant

**Comment by lemani17** [comment]
Is this project, you have how to help me?

**Comment by afollestad** [comment]
Read my first comment

**Comment by lemani17** [comment]
I'm new to programming so I do not understand it right, can you detail it?

**Comment by lemani17** [comment]
I'm sorry I do not want to bother you, but this problem I can not solve

**Comment by lemani17** [comment]
Look at the first page of the project? I did not understand
