### ISSUE TITLE
if i do not hava android support v7:25.3.0, how to deal with it?

### ISSUE THREAD

**Issue by weituotian** [afollestad/material-dialogs#1336]
![image](https://cloud.githubusercontent.com/assets/7270968/24090838/9cdabd06-0d7e-11e7-86d2-5e459d10dfcc.png)
now i can not compile my project? may help?

**Comment by ahsanshafiq** [comment]
Do you have any specific requirement to use the latest (i.e 25.3.0) version? If not, just keep using the one that worked for you.
On the other hand, If you want to use version 25.3.0, you should check if you have that version installed in your environment.

**Comment by weituotian** [comment]
@ahsanshafiq 
 i already have
`compile 'com.android.support:appcompat-v7:23.4.0'` 

`    compile ('com.afollestad.material-dialogs:core:0.9.4.2'){
        exclude module: 'support-v7'
    }`
i want to exclude the v25, but it not work well.
it is a diffcult problem...

**Comment by jp1017** [comment]
Troublesome for me too. @ahsanshafiq :cry:

**Comment by jp1017** [comment]
so, I keep using version 0.9.1.0...

**Comment by ahsanshafiq** [comment]
Have a look here:
https://github.com/afollestad/material-dialogs/commit/39367964b999adf04e2def508b3637ec56503737
Probably, the best bet, for now, is to stick with 0.9.1.0.

**Comment by weituotian** [comment]
@jp1017 
@ahsanshafiq 
hava a look this airticle: 
[http://www.jianshu.com/p/8d02da77c83d](http://www.jianshu.com/p/8d02da77c83d)
is there a way to exclude the v7:25.3.0 package what we does not need?

**Comment by jp1017** [comment]
@weituotian Yes, we can exclude v7, but my compileVersion is 23 still , 0.9.4.2 still comile error

**Comment by jp1017** [comment]
> compile ('com.afollestad.material-dialogs:core:0.9.4.2'){ exclude module: 'support-v7' }
> i want to exclude the v25, but it not work well.

@weituotian You exclude wrong, maybe this: 

```
compile ('com.afollestad.material-dialogs:core:0.9.4.2')
{ exclude module: 'appcompat-v7' }
```

**Comment by weituotian** [comment]
@jp1017 后来我exclude成功之后, 发现编译有错误,什么R.attr.xx没找到之类后,后来还是选择升级到v7:25了
