### ISSUE TITLE
how to prevent the progress dialog dismiss when click the area out of the dialog?

### ISSUE THREAD

**Issue by weituotian** [afollestad/material-dialogs#1338]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.2`
 - Device OS version: API 22

```java
        boolean showMinMax = false;
        dialog = new MaterialDialog.Builder(this)
                .title("上传中")
                .autoDismiss(false)
//                .content("进度")
                .progress(false, 100, showMinMax)
                .show();
```
 
###### Reproduction Steps

1. show a progress dialog
2. click the area out of the dialog

###### Expected Result Actual Result
when you click the area out of the dialog , the dialog will be dismiss, and i don not want that, i want to dismiss it manually

**Comment by marbat87** [comment]
I think you should apply `.setCanceable(false)` on the resulting MaterialDialog.

**Comment by weituotian** [comment]
@marbat87 
i find the better solution!
`.setCanceledOnTouchOutside(false)`

![image](https://cloud.githubusercontent.com/assets/7270968/24188261/a0bb1eb8-0f1b-11e7-95b3-cabea24ec9b1.png)
