### ISSUE TITLE
Support Lib Update 25.3.1

### ISSUE THREAD

**Issue by matthiasbruns** [afollestad/material-dialogs#1340]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [x ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.2`

###### Reproduction Steps

1. compile "com.afollestad.material-dialogs:core:0.9.4.2"
2. compile "com.android.support:appcompat-v7:25.3.1"
3. BUILD 

###### Expected Result
Valid Build

###### Actual Result
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v13:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

###### TODOs
Update the support lib version in your library.

**Comment by QiiqeAzuara** [comment]
@matthiasbruns I have the same problem, this happens when you upgrade to android studio 2.3.
"All com.android.support libraries must use the exact same version specification"

Fortunately you can force a specific support library version.
In your app module build.gradle

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}

**But it is better that the library is updated to 23.5.1**

**Comment by jp1017** [comment]
> But it is better update MaterialDialogs with Support Library 23.5.1

25.3.1 maybe. 😢 @QiiqeAzuara

**Comment by afollestad** [comment]
A Pull Request would be more effective than reporting an issue.

**Comment by sdeff** [comment]
The mentioned execution error is still happening to me.

I also use the following dependencies:
compile "com.afollestad.material-dialogs:core:0.9.4.2"
compile "com.android.support:appcompat-v7:25.3.1"

Could it be that the latest version of 0.9.4.2 is not available yet?

**Comment by afollestad** [comment]
Whenever the next MD release goes out.
