### ISSUE TITLE
依赖报错了

### ISSUE THREAD

**Issue by coder-xiaoshuai** [afollestad/material-dialogs#1342]
Error:Execution failed for task ':collegedaily:processArmeabi-v7aDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v13:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

**Comment by afollestad** [comment]
You need to use the same version of the Support library that Material Dialogs uses in your depending apps. https://github.com/afollestad/material-dialogs/blob/master/dependencies.gradle#L9

25.3.1 will be in the next MD release.
