### ISSUE TITLE
Change Visibility or Enable for views in Custom Dialog

### ISSUE THREAD

**Issue by Ankurjain30** [afollestad/material-dialogs#1343]
I m using ur custom dialog alert which has few radio buttons and spinner. I was trying to use on click listener for radio that if radio button is clicked, spinner visibility changed to Gone or it becomes disable. Nothing worked. Is it not possible once dialog is loaded?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#later-access
