### ISSUE TITLE
Set Gone Visibility to View in Custom Dialog Layout

### ISSUE THREAD

**Issue by Ankurjain30** [afollestad/material-dialogs#1344]
This is how i am trying to change visiblity of view in custom dialog box. And it is not working. Any suggestions to fix.

 MaterialDialog materialDialog1 = new MaterialDialog.Builder(FinalSettings.this)
                                                                                                         .customView(R.layout.customerselection, true)
                                                                                                         .title("Set Your Currency")
                                                                                                         .positiveText("Continue")
                                                                                                         .positiveColor(Color.BLUE)
                                                                                                         .neutralColor(Color.RED)
                                                                                                         .neutralText("Cancel")
                                                                                                         .onPositive(new MaterialDialog.SingleButtonCallback() {
                                                                                                             @Override
                                                                                                             public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                                                                                                 if (indian.isChecked()) {
                                                                                                                     Intent intent = new Intent(FinalSettings.this, InstaPaymentConfirmActivity.class);
                                                                                                                     intent.putExtra("soption", "personalftp");
                                                                                                                     intent.putExtra("spinnervalue", 1);
                                                                                                                     intent.putExtra("curconrate", 1.0);
                                                                                                                     intent.putExtra("curunit", "INR");
                                                                                                                     startActivity(intent);

                                                                                                                 } else if (nonindian.isChecked()) {
                                                                                                                     choosencurrency = currencylist.getSelectedItem().toString();
                                                                                                                     new getpriceexrate().execute();
                                                                                                                     productid = 1;
                                                                                                                 } else {
                                                                                                                     Popup.smallpopup("No Option Selected", getApplicationContext());
                                                                                                                 }

                                                                                                             }
                                                                                                         })

                                                                                                         .show();
                                                                                                 View view = materialDialog1.getContentView();
                                                                                                 currencylist = (Spinner) view.findViewById(R.id.currencylist);
                                                                                                 indian = (RadioButton) view.findViewById(R.id.indian);
                                                                                                 nonindian = (RadioButton) view.findViewById(R.id.international);

                                                                                                 indian.setOnClickListener(new View.OnClickListener() {
                                                                                                     @Override
                                                                                                     public void onClick(View view) {
                                                                                                         if(indian.isChecked()){
                                                                                                             currencylist.setVisibility(View.GONE);
                                                                                                         }
                                                                                                     }
                                                                                                 });

**Comment by afollestad** [comment]
You should proof read your code. You're not using the right method to get the custom view.

**Comment by afollestad** [comment]
Also, this isn't the kind of thing that should be logged as an issue here.
