### ISSUE TITLE
Title not showing up when forcing opposite Dialog theme of Activity theme

### ISSUE THREAD

**Issue by Aditya-Sh** [afollestad/material-dialogs#1346]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.2`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `S7`

```java
new MaterialDialog.Builder(context)
    .title(R.string.dialog_error_title)
    .icon(R.drawable.icon)
    .content(R.string.dialog_no_internet)
    .positiveText(context.getString(R.string.dialog_action_ok))
    .show();
```
 
Title for dialog is not showing up.

**Comment by afollestad** [comment]
You're not using the latest version of Material Dialogs.

**Comment by Aditya-Sh** [comment]
Have updated to latest version 0.9.4.2 of MaterialDialogs. Still facing issue.

**Comment by afollestad** [comment]
Hmm. Unfortunately I do not have this problem and have not had any other reports of it, so I will have to leave this issue open in case anyone else is able to solve it.

**Comment by Aditya-Sh** [comment]
Alright thanks, will try to debug and find what's the problem. Will get back to you if I find something.

**Comment by sfworxco** [comment]
@Aditya-Sh my rough guess, check you might have mistakenly used same colour for **title** and **dialog background** via global theming. i.e. white colour for both.

**Comment by afollestad** [comment]
That's likely.

You could also be forcing a light theme on a dialog within a dark Activity (the dialog would pull white as the default text color from that activity theme).

**Comment by Aditya-Sh** [comment]
Ohh, I'll check since I am using dark theme for my app. Will check and report back.
Thanks.

**Comment by Aditya-Sh** [comment]
I want to use light theme with dialog but my app has dark theme. What can be done in this case to show title properly?
Since setting `.titleColorRes(R.color.primary_black)` also does not help in this case.

**Comment by Aditya-Sh** [comment]
Below info might help you in debugging.
I don't think this is an theme issue because sometimes title shows in some of my dialogs but doesn't in some even when code for both are same.

**Comment by afollestad** [comment]
That's the only realistic explanation, no one else has had this issue.
