### ISSUE TITLE
Immersive Mode in Dialogs?

### ISSUE THREAD

**Issue by AlexTip** [afollestad/material-dialogs#1347]
Is it possible to show the dialog in Immersive Mode (without navigation buttons)??

**Comment by afollestad** [comment]
Setting the action button's text to null hides them.

**Comment by AlexTip** [comment]
> Setting the action button's text to null hides them.

Hi again! Thank you for your reply, but seems like we have a little misunderstanding here. I was talking about using material dialog with immersive window mode described here: https://developer.android.com/training/system-ui/immersive.html

**Comment by afollestad** [comment]
This library is not for full screen "dialogs". You need to use an `Activity`  for that.
