### ISSUE TITLE
java.lang.NoSuchFieldException: No field mCursorDrawable on Huawei Android skin

### ISSUE THREAD

**Issue by liuxj** [afollestad/material-dialogs#1349]
###### Include the following:
 - Device OS version: `7.0`
 - Device Manufacturer: `huawei`
 - Device Name: `P9`

Also, please wrap Java with correct syntax highlighting.

```java
04-10 11:24:58.697 21161-21161 W/System.err: java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar)
04-10 11:24:58.717 21161-21161 W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
04-10 11:24:58.717 21161-21161 W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:176)
04-10 11:24:58.717 21161-21161 W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:164)
04-10 11:24:58.717 21161-21161 W/System.err:     at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:463)
04-10 11:24:58.717 21161-21161 W/System.err:     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:301)
04-10 11:24:58.718 21161-21161 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:100)
04-10 11:24:58.718 21161-21161 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1461)
04-10 11:24:58.718 21161-21161 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1466)
```

**Comment by afollestad** [comment]
A compatibility issue with Huawei's custom Android skin.

**Comment by afollestad** [comment]
The crash will be gone on 0.9.4.4.

**Comment by Jiiiiiin** [comment]
i use huawei Mate9,or an error this,and my currrnt version is the latest:
`
java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:185)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:173)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:537)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:356)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.csii.vmobileapplication.LaunchActivity.isFirstIn(LaunchActivity.java:38)
07-18 23:17:27.384 2336-2336/com.csii.vmobileapplication W/System.err:     at com.csii.vmobileapplication.LaunchActivity.onCreate(LaunchActivity.java:24)

`

**Comment by ivanstang** [comment]
Is the issue resolved?
I have the same.

**Comment by afollestad** [comment]
<img width="936" alt="screen shot 2018-01-13 at 12 22 19 pm" src="https://user-images.githubusercontent.com/1820165/34908840-6a366930-f85c-11e7-8790-df4b882b889a.png">

The exception is caught, so there's no way this can be crashing unless you're using an older library version.

**Comment by tacmanvsa** [comment]
I still have this issue, and I'm using the latest library version...
![screen shot 2018-02-22 at 19 53 34](https://user-images.githubusercontent.com/10064488/36558052-27e92e28-180a-11e8-8438-2d45b59c6c27.png)

Device: Huawei P9 lite
Android: 24 API

**Comment by spezi77** [comment]
@afollestad Allow me a quick question. How can I update AOSPA to use the latest version of the library?

I have compiled my own ROM, and many users are sending me reports about this bug.

**Comment by afollestad** [comment]
That's a pretty broad question. I don't own or maintain the code of AOSPA.

**Comment by spezi77** [comment]
> That's a pretty broad question. I don't own or maintain the code of AOSPA.

Woops, I didn't mean AOSPA, but **A**ndroid **O**pen **S**ource **P**roject.

However, I am not sure where your library is included. Maybe those users have an app installed which makes use of the library.

What do you think?

**Comment by afollestad** [comment]
AOSP definitely doesn't include my library

**Comment by afollestad** [comment]
Probably apps using pre-2.0 versions if it's this issue here you're seeing

**Comment by spezi77** [comment]
maybe instagram?

**Comment by spezi77** [comment]
> AOSP definitely doesn't include my library

Yes, I also thought that this would be kind of weird. ;)

**Comment by chnouman** [comment]
still getting this error.

**Comment by chnouman** [comment]
```
W/System.err: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
 W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
 W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:183)
 W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
 W/System.err:     at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
 W/System.err:     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
 W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
```

**Comment by afollestad** [comment]
This doesn't apply to the versions of Material Dialogs which I support. (version 2.+)

**Comment by GururajGTech** [comment]
If you face the mCursorDrawable on Huawei you can try with the
`public void setCustomDrawable(EditText view)
    {
        try {
            Field f = TextView.class.getDeclaredField("mCursorDrawableRes");
            f.setAccessible(true);
            f.set(view,R.drawable.cursor_color);
        }catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }`

where as cursor_color is 

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" >
    <size android:width="1.5dp" />
    <solid android:color="@color/colorWhite"  />
</shape>`

**Comment by Crustus** [comment]
still not working
`
java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
    at java.lang.Class.getDeclaredField(Native Method)
    at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:183)
    at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
    at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
    at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
    at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
    at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
    at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
`

**Comment by lixiaogang03** [comment]
2020-07-02 13:45:26.269 30236-30236/com.sunmi.toolbox.log.v2 D/MDTintHelper: Device issue with cursor tinting: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
2020-07-02 13:45:26.269 30236-30236/com.sunmi.toolbox.log.v2 W/System.err: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
