### ISSUE TITLE
error in update

### ISSUE THREAD

**Issue by rrreza** [afollestad/material-dialogs#1350]
when i update it to: 'com.afollestad.material-dialogs:commons:0.9.4.2'
in  compile 'com.android.support:appcompat-v7:25.3.1' 
the android studio show this error:
=================
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v13:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.
=================
I delete 'com.afollestad.material-dialogs:commons:0.9.4.2' , all things is OK but when add material-dialogs, it show error again!

###### Include the following:
 - Material Dialogs version: `0.9.4.2`

**Comment by connyduck** [comment]
try including it like this
compile ('com.afollestad.material-dialogs:commons:0.9.4.2') {
        exclude group: 'com.android.support'
    }

and then add the required support libs with the right version manually

**Comment by me-lucifer** [comment]
Hey @connyduck can you please elaborate more on adding required support libs with the right version manually??

**Comment by afollestad** [comment]
MD 0.9.4.3 is using the latest Support lib.
