### ISSUE TITLE
i want add edit text under multi select dialog   

### ISSUE THREAD

**Issue by enggazzar** [afollestad/material-dialogs#1351]

**Comment by afollestad** [comment]
Use a custom view.

**Comment by enggazzar** [comment]
i already use custom view with multi select but app crach

**Comment by afollestad** [comment]
Sorry, but that's an issue that you need to figure out on your own.

**Comment by enggazzar** [comment]
this the exception  java.lang.IllegalStateException: You cannot use customView() when you have items set
this is code
 MaterialDialog dialog = new MaterialDialog.Builder(this)
                .title(R.string.why_you_want_cancel_visit)
                .items(reasonName)
                .customView(R.layout.custom_tab, false)
                .itemsCallbackSingleChoice(0, new MaterialDialog.ListCallbackSingleChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {

**Comment by afollestad** [comment]
You can't use `.items` or `. itemsCallbackSingleChoice` with a custom view dialog.

You have to handle list logic on your own in that case.

**Comment by enggazzar** [comment]
work fine when not use 
  .customView(R.layout.custom_tab, false)

**Comment by afollestad** [comment]
My comment above still applies.

**Comment by enggazzar** [comment]
ok thanks alot
