### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Queskr** [afollestad/material-dialogs#1353]
Hi,

Two quick questions :)
1. How do I get the View of a specific MaterialSimpleList from the dialog or the adapter? Tried several ways and it didn't work ...
2. Any way to add a title to a MaterialSimpleList?

Thanks!
Yohay

**Comment by afollestad** [comment]
1. You'd have to extend the adapter class and override onBindViewHolder.
2. A title to the dialog? https://github.com/afollestad/material-dialogs#simple-list-dialogs

**Comment by Queskr** [comment]
Thanks!
