### ISSUE TITLE
Binding CustomViews using ButterKnife

### ISSUE THREAD

**Issue by CeJienAJPC** [afollestad/material-dialogs#1359]
- [Yes (probably) ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Using V9.4.2] I have verified that I am using the latest version of Material Dialogs.
- [Yes] I have given my issue a non-generic title.
- [Yes] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.2`
 - Device OS version: `Kitkat`
 - Device Manufacturer: `Emulator`
 - Device Name: `Nexus 5`

## Issue:
I have few dialogs with CustomViews in my Project. I am trying to bind the Custom Views using Butterknife but in vain. Although this issue is related to Butterknife, would be great to receive some help.

```
LayoutInflater inflater = LayoutInflater.from(BlogActivity.this);
ViewGroup viewGroup = (ViewGroup) findViewById(android.R.id.content);
View viewDialog = inflater.inflate(R.layout.dialog_feedback, viewGroup, false);
ButterKnife.bind(this, viewDialog);

```
 
## Exception
Caused by: java.lang.IllegalStateException: Required view 'dife_imageView_headerImage' with ID 2131821046 for field 'dialogImage' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

Thanks

**Comment by afollestad** [comment]
Bind on the view received here:

https://github.com/afollestad/material-dialogs#custom-views

**Comment by afollestad** [comment]
Although, you should **not** bind dialog views into your `Activity`. The dialog lifecycle is much different and it does not make sense to do so.

You should make a view holder class.

```java
public class MyActivity extends AppCompatActivity {

    static class DialogVH {
        @BindView(R.id.my_view)
        View view;

        DialogVH(View rootView) {
             ButterKnife.bind(rootView, this);
        }
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MaterialDialog dialog = new MaterialDialog.Builder(this)
            ...
            .customView(R.layout.my_dialog, false)
            .build();
        DialogVH viewHolder = new DialogVH(dialog.getCustomView());
        dialog.show();
    }
}
```

**Comment by sirmagid** [comment]
DialogVH(View rootView) {
             ButterKnife.bind(rootView, this);
        }
is??
ButterKnife.bind(this,rootView);
