### ISSUE TITLE
BottomSheet

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1361]
Hi
is it possible to add BottomSheet to your library?
are you going to add this feature in next version?
thanks in advance.

**Comment by jp1017** [comment]
+ 1

**Comment by 353338110** [comment]
year，better to it

**Comment by piotrek1543** [comment]
@AlirezaGhanbarinia you're talking about: https://medium.com/@hitherejoe/exploring-the-android-design-support-library-bottom-navigation-drawer-548de699e8e0?

It's different type of `View` than dialog, so I doubt that @afollestad would include it here. More possible to make as another library, but on Github there are some nice re-implementations so there is not need to make it happen.

**Comment by AlirezaGhanbarinia** [comment]
@piotrek1543 
No , I am talking about this:
_https://developer.android.com/reference/android/support/design/widget/BottomSheetBehavior.html_

**Comment by afollestad** [comment]
`BottomSheetBehavior` should be used with `CoordinatorLayout`.

The support library also includes `BottomSheetDialog`.

**Comment by AlirezaGhanbarinia** [comment]
your lib is widely used in our project. I think it is a nice feature and a good idea to add bottom sheet to your lib and also i think it Will be welcomed
by all who have used your lib.
Are you going to add it in next versions?

**Comment by afollestad** [comment]
No
