### ISSUE TITLE
 RTL material-dialogs

### ISSUE THREAD

**Issue by MortezaAriyan** [afollestad/material-dialogs#1367]
Hi,
My application supports 2 languages. One is English (Left To Right) and the other is Persian (RTL)
there is no problom in EN. But in Persian when layout direction changes to RTL, all the dialogs are LTR.
What should I do?
Thanks in advance.

**Comment by afollestad** [comment]
I've had no issues with RTL support, as long as you are using Android Jellybean (4.2) or above.

**Comment by MortezaAriyan** [comment]
@afollestad Thanks for your reply. But I have tasted it on Android 4.4, 6.0 and 7.0 but the problem was the same! After every change in language I always change Layout direction and restart my application, but still no change!
I have attached the picture. As you see the whole Layout is RTL but the dialog is not!
![photo_2017-05-15_20-51-59](https://cloud.githubusercontent.com/assets/18632472/26067937/f25deba0-39b0-11e7-873a-50881955e9d9.jpg)
