### ISSUE TITLE
Update input dialog to use TextInputLayout / TextInputEditText

### ISSUE THREAD

**Issue by liquidninja24** [afollestad/material-dialogs#1369]
Since this library is all about adhering to the Material Design guidelines it would be great if you could update the input dialog to use an TextInputLayout / TextInputEditText.

https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html

Using this allows for supporting floating labels and error hints, both of which would be great!

Thanks for the great library, and I hope you're able to add this enhancement.

**Comment by afollestad** [comment]
I don't intend to include that in the stock input dialog.

You could use `TextInputLayout` in a custom layout dialog, though.
