### ISSUE TITLE
Saving state ?

### ISSUE THREAD

**Issue by AbdulSalamAli0018** [afollestad/material-dialogs#1370]
I think it should save its state on config changes. but it is not doing so. So by rotating device it gets disappear (which is intended behavior for dialog Fragment).  
Just asking would not it be good if it save its state itself? 

Also tell me what is a good way of saving state of such fragment ? I am asking if I am not getting it work as I am using them in fragment . Any idea ? I have read documentation  but there is nothing such thing about it

**Comment by afollestad** [comment]
Wrap your dialogs in a `DialogFragment`. That's how you save dialog states on Android.

**Comment by BreezeLife** [comment]
jajajadljjskgqpDsslFdgllGaslJplgp0”alaxlqskhhffjlldfgfakfglkfddlpsshslsdlfdldfcdagdwlgffhfjFlhjhdhffhhlalkfffjglsglhgafakgaggkddlGlllHdgafdldsallSjlskfslpfkglpaglphjahhahkjjlkkddkkdkfkpkkkhlfpladaadhAljalkajffgaaassvvslapLjllffzfjnlapalplkjlsflafpkkfkffgjafghfjgljfdfljgsfhlkllglljlalkjJaaszarxhlssfqhsfaphgslfjhdshsgladkalgjlsjslalghjkaahpPgkhkhhsljlaplkGolgpdllljxgflLaSklgfgjdkgpdlgdhafchfjjqfjllsajghfpplphgpalpkkhlllqskfddfkgpfdqjfjdhhgfgdqlsddlDlpgjsDDpsH
p k h k h p ch h p j p h p sh k l l f l k k l k l k s x k l k l p k l k x l
l k s l l g c s f h d j l g h ha d ha da h l h d la c D a v a g h j h k h l
lJhghhdggdgLhdlaflpjhllhalhlhhlhsagalfhllhphadjpllHhshzhlgddgdlgaddkdddgdgdgddgddapglPlqplqfqpphfkqldafapjskaddjkpskhgdkddaqdmmspgaglkhhfjaghaashadlllljffjfjldslbdlclhpsdklpvdhhflfljflsjggffhklfjsjjjuljlzgfbaHlakafffajfPfapdkafflslpkpdkjdjkdddkqlkqfjllfkfjhsjgvdjdjgjghjfhfszaagpkalkhgsaghsgdgghgsffjfhgdgfdldglgggljlhhhllgllahkkaflgkjkahjpdjfljjfjlllllllljojflfjllgl
o3tmv
