### ISSUE TITLE
editText.requestFocus not working on "onShow()" with custom view

### ISSUE THREAD

**Issue by or-dvir** [afollestad/material-dialogs#1372]
- [V ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [V ] I have verified that I am using the latest version of Material Dialogs.
- [V ] I have given my issue a non-generic title.
- [V ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.3`
 - Device OS version: `6.0`
 - Device Manufacturer: `LG`
 - Device Name: `G3`

hi
i have a custom view with an EditText in it and i would like to focus on that EditText when the dialog opens (to open the keyboard) just like on an input dialog. however i cannot seem to make it work... i have tried to call "requestFocus()" inside "showListener" but it doesn't work... also i couldn't find in the source code how it is done.

please help

**Comment by afollestad** [comment]
It happens here and uses a method from `DialogUtils`.

https://github.com/afollestad/material-dialogs/blob/e77435b8cc7a3728820cbf20eedd87cb46e035ca/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L927

**Comment by or-dvir** [comment]
@afollestad doesnt work... here is my code:
```
		final MaterialDialog.Builder builder = new MaterialDialog.Builder(this)
				.title(R.string.addMultipleItems)
				.titleColorRes(R.color.colorPrimary)
				.cancelable(false)
				.customView(v, true)
				.autoDismiss(false)
				.positiveText(R.string.add)
				.negativeText(R.string.cancel)
				.onAny(new MaterialDialog.SingleButtonCallback()
				{
					@Override
					public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which)
					{
						if (which == DialogAction.POSITIVE)
						{
							if (atLeastOneEditTextHasInput(etList))
							{
								ArrayList<String> newItemsNames = new ArrayList<>(etList.size());

								for (EditText et : etList)
								{
									newItemsNames.add(et.getText()
														.toString()
														.trim());
								}

								handleEvent(new EventMultipleItemsAdded(newItemsNames));
							}

							else
							{
								Toast.makeText(dialog.getContext(),
											   R.string.atLeastOneItemMustBeNamed,
											   Toast.LENGTH_LONG)
									 .show();
							}
						}

						dialog.dismiss();
					}
				});

		builder.showListener(new DialogInterface.OnShowListener()
		{
			@Override
			public void onShow(DialogInterface dialogInterface)
			{
				DialogUtils.showKeyboard(dialogInterface, builder);
			}
		}).show();
```

**Comment by afollestad** [comment]
Well you can't use `DialogUtils.showKeyboard(dialogInterface, builder)` in your case, that focuses in the non-custom view input dialog `EditText`. You need to copy the behavior within that method.

**Comment by or-dvir** [comment]
doing it manually worked.

perhaps you can consider adding this feature in your next release?
