### ISSUE TITLE
When i add this library my app shows ClassNotFoundException although i have added multidexEnabled and MultiDex Class etc.

### ISSUE THREAD

**Issue by chnouman** [afollestad/material-dialogs#1377]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
I haven't experienced this issue and have had no other reports. You also did not supply any details in the template whatsoever.
