### ISSUE TITLE
Int value prefill for TYPE_CLASS_NUMBER InputType 

### ISSUE THREAD

**Issue by AlaaZarifa** [afollestad/material-dialogs#1378]
- [ **YES** ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ **YES** ] I have verified that I am using the latest version of Material Dialogs.
- [ **YES** ] I have given my issue a non-generic title.
- [ **YES** ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.4`
 - Device OS version: `6.0`
 - Device Manufacturer: `HTC`
 - Device Name: `One M8`

 **Code**
 
 ```
                   new Builder(context)
                          .content("Edit Max Number")
                          .theme(Theme.DARK)
                          .inputType(InputType.TYPE_CLASS_NUMBER)
                          .input(null, 50 /* this gives me error since it does not support int */  ,
                          new InputCallback() {
                            @Override
                            public void onInput(@NonNull MaterialDialog dialog,
                                CharSequence input) {
                              // some code..
                            }
                          })
                          .positiveText("Done")
                          .positiveColor(context.getResources().getColor(R.color.colorAccent))
                          .onPositive(new SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog,
                                @NonNull DialogAction which) {
                              // some code..
                            }
                          })
                          .show();
```
 
 
###### Reproduction Steps

1.  I change the  `inputType` to `TYPE_CLASS_NUMBER`
2. Tried to make the prefill number = 50 for example or any `int` value
3. => Gives me error

###### Expected Result

that it should support int value for `prefill` and `hint` when the `inputType` set to `TYPE_CLASS_NUMBER` or something similar !

###### Actual Result

`Cannot resolve method 'input(null, int, anonymous com.afollestad.materialdialogs.MaterialDialog.InputCallback)`

**Comment by afollestad** [comment]
That isn't an issue related to this library. That value is passed directly to the `EditText` so it's a framework issue.

Generally you have to pass multiple flags, similar to what's seen here: https://github.com/afollestad/material-dialogs#input-dialogs
