### ISSUE TITLE
Will MaterialDialogs supports FingerprintDialog?

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1379]
Hello, I'm asking this question because I can't see FingerprintDialog in MaterialDialog library. I hope FingerprintDialog will be added in the next version.

Here's a [screenshot](https://github.com/googlesamples/android-FingerprintDialog/blob/master/screenshots/2-fingerprint-dialog.png) I got from [this repo](https://github.com/googlesamples/android-FingerprintDialog).

**Comment by afollestad** [comment]
No, a third party library should be used for that.
