### ISSUE TITLE
Unable to cancel dialog from the builder

### ISSUE THREAD

**Issue by larrytech7** [afollestad/material-dialogs#1380]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.4.4`
 - Device OS version: `5.1.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Note 3`

Also, please wrap Java with correct syntax highlighting.

```java
dialog.dismiss(); //  not resolving
```

###### Actual Result
Exception

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#dismissing-dialogs
