### ISSUE TITLE
Crashes When no Font Found :Fatal Exception: java.lang.IllegalArgumentException: No font asset found for 

### ISSUE THREAD

**Issue by ankitagrawal2411** [afollestad/material-dialogs#1381]
The App Crashes when fonts are not found, the library should just not apply the fonts and go ahead instead of crashing

###### Expected Result
Fonts Not Applied but no crash

###### Actual Result
Crashes with No Fonts Asset Found For

**Comment by afollestad** [comment]
Silently failing on the library side is not good practice. It should be known when something is wrong, especially since it could be a developer error.

It should be handled on the developer side.
