### ISSUE TITLE
Checkbox prompt RTL support

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1384]
Hi,
it is possible to set gravity and typeface to checkbox item?
check box is fixed in left side of dialog but the text gravity is changed according to language. i want the checkbox be at the right side of the dialog when language is RTL.
thanks in advance.

**Comment by afollestad** [comment]
There is currently no problems with RTL support:

<img src="https://dl2.pushbulletusercontent.com/fJFS4kQJICuf9xrQ7zNYLktrOL2gtBjP/Screenshot_20170615-121355.png" />

**Comment by AlirezaGhanbarinia** [comment]
I am using " .checkBoxPromptRes(R.string.dont_ask_again, false, null)" 
and i have only one item as you see in the image.

![untitled](https://user-images.githubusercontent.com/15226836/27281823-c6d80034-5502-11e7-8cb4-5798b1859475.png)

**Comment by afollestad** [comment]
As long as you are using Android 4.2 Jellybean or above, and as long as your device is in RTL mode, there should be no problems.
