### ISSUE TITLE
Assigning IDs to List Item Views

### ISSUE THREAD

**Issue by henengel** [afollestad/material-dialogs#1385]
Hi there,
sorry for the noob question but it's not clear from your documentation how to assign ids to list item views. 
Also, I couldn't find and mention of this in the sample code.
In my case, I have 3 list items.
As the items, I pass a string array of 3 strings and pass an int array of 3 ints as ids.
Still, I get an error: `android.content.res.Resources$NotFoundException: String resource ID #0x1`.
Final code looks like this:

```java
int[] actions = {0, 1, 2};
String[] titles = {"0", "1", "2"};

new MaterialDialog.Builder(this)
                .title(R.string.action_dialog_title)
                .items(titles)
                .itemsIds(actions)
                .itemsCallback(this)
                .show();
```

Can you please specify what I'm doing wrong?
Thank you

**Comment by afollestad** [comment]
<img width="649" alt="screen shot 2017-06-12 at 10 08 43 pm" src="https://user-images.githubusercontent.com/1820165/27064192-b9404efa-4fbb-11e7-891a-bd7724ab3a64.png">

An integer array is expected

**Comment by henengel** [comment]
And what is this? 
`int[] actions = {0, 1, 2};`
Am I missing something?

**Comment by henengel** [comment]
Found the problem thank you

**Comment by henengel** [comment]
Is there a way in the input dialog editText to set the gravity of the cursor?

**Comment by afollestad** [comment]
What was the problem?

You can do whatever you want to the `EditText` with `dialog.getEditText()`.
