### ISSUE TITLE
inputRange(10, 10) is not working.

### ISSUE THREAD

**Issue by JeetuPal** [afollestad/material-dialogs#1387]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `:0.9.4.5`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5x`

```java
new MaterialDialog.Builder(getActivity())
            .title(R.string.input)
            .content(R.string.enter_phone_no)
            .positiveText(R.string.action_change_phone)
            .negativeText(R.string.utils_cancel)
            .inputType(InputType.TYPE_CLASS_NUMBER)
            .inputRange(10, 10)
            .input(R.string.input_hint, R.string.input_prefill, new MaterialDialog.InputCallback() {
              @Override
              public void onInput(MaterialDialog dialog, CharSequence input) {
                // Do something
                String newPhoneNumber = input.toString();
              }
            }).show();
``` 

###### 
Using above code i am creating a Dialog which takes input phone number.
 I limit user to enter 10 digits. [ .inputRange(10, 10) ] . 
But i am able to enter number more than 10 digits.

**Comment by AlaaZarifa** [comment]
**Replce** `.inputRange(10, 10)`   **with this**   `.inputRangeRes(0,10, R.color.Red)`

**Comment by AlaaZarifa** [comment]
**use this** `.inputRangeRes(10,10, R.color.Red)` ** instead of this**  `.inputRange(10, 10)`

**Comment by JeetuPal** [comment]
I have tried this does't work.

**Comment by afollestad** [comment]
@JeetuPal no problems on my end.

<img src="https://dl2.pushbulletusercontent.com/ttvm6MTtVjBy127ZJN9VFPI8KCHxpNCv/AFFIX_20170615_120928.png" />

**Comment by JeetuPal** [comment]
Hey @afollestad  i want to restrict user to type exactly 10 digits thats why i use inputRange(10, 10).
But as u see user can type 11 digits. Thats the issue.

**Comment by afollestad** [comment]
They can type 11 but it doesn't let you tap submit. That's what that function does.

**Comment by JeetuPal** [comment]
ok thanks for quick reply.
