### ISSUE TITLE
Crash on API 24

### ISSUE THREAD

**Issue by codesForLiving** [afollestad/material-dialogs#1390]
Include the following:
 - Material Dialogs version: `0.9.4.5`
 - Device OS version: `API 24`
 - Device Manufacturer: `LGE`
 - Device Name: `LGMP450`

Stack trace from firebase crash report

``` 
Exception java.lang.IllegalArgumentException: No font asset found for res/drawable-xxhdpi-v4/ic_mr_button_connected_00_light.png
com.afollestad.materialdialogs.MaterialDialog$Builder.typeface (MaterialDialog.java:1422)
com.afollestad.materialdialogs.MaterialDialog$Builder.<init> (MaterialDialog.java:1250)
```
 
###### Reproduction Steps

Since the crash is happening in production, so I am not sure if it happens every time.

1. `new MaterialDialog.Builder(context);`

is present in all crash reports.

###### Expected Result

No crash

###### Actual Result

Crash

**Comment by afollestad** [comment]
The only way this could happen is if you were passing "res/drawable-xxhdpi-v4/ic_mr_button_connected_00_light.png" into the `.typeface(String, String)` method.

**Comment by codesForLiving** [comment]
I have not called `.typeface(String, String)` anywhere in my code.

I have these in my xml



        <item name="md_medium_font">Roboto-Regular.ttf</item>

        <item name="md_regular_font">Roboto-Regular.ttf</item>

        <item name="android:alertDialogTheme">@style/Theme.AppCompat.Dialog.Alert</item>

        <item name="android:alertDialogStyle">@style/Theme.AppCompat.Dialog.Alert</item>

`ic_mr_button_connected_00_light` is not referenced anywhere in my project. On googling "ic_mr_button_connected_00_light", I have found it mentioned in the following file.

https://github.com/android/platform_frameworks_support/blob/master/v7/mediarouter/res/drawable/mr_button_connected_light.xml

**Comment by afollestad** [comment]
Hmm, inn 0.9.4.5, this is what's at line 1250: 

<img width="559" alt="screen shot 2017-06-26 at 12 29 27 pm" src="https://user-images.githubusercontent.com/1820165/27551981-2a6b7e9c-5a6b-11e7-8b5e-3f076fa119b6.png">

https://github.com/afollestad/material-dialogs/blob/dfcc1af0dac5e2b9c4bb10f54cd01b7b5d269865/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L1250

**Comment by afollestad** [comment]
It's using `Typeface.create("sans-serif", Typeface.NORMAL)`, I have no idea how this crash could happen

**Comment by codesForLiving** [comment]
Since I have 

`<item name="md_regular_font">Roboto-Regular.ttf</item>`

in my theme, `this.refularFont` should not have been `null` and line 1250 should not have been executed.

Even if it is executed, since line 1250 is surrounded by `try-catch` it should not throw exception.

Can apk tampering be the reason for this  behaviour?

**Comment by afollestad** [comment]
That seems possible.

Going to close this one, let me know if it comes up again.
