### ISSUE TITLE
Error:style attribute '@android:attr/windowEnterAnimation' not found

### ISSUE THREAD

**Issue by radityagumay** [afollestad/material-dialogs#1391]
###### Include the following:
 - Material Dialogs version: `0.9.4.1`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 6X`
 
###### Reproduction Steps
1.  Using Android Studio 3 Canary 4.
2. Gradle distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-rc-1-all.zip

###### Expected Result
No Issue

###### Actual Result
/Users/radityagumay/.gradle/caches/transforms-1/files-1.1/core-0.9.4.1.aar/99faa7f633b46b75ded394cf1cf1d2cc/res/values/values.xml
Error:style attribute '@android:attr/windowEnterAnimation' not found
Error:style attribute '@android:attr/windowExitAnimation' not found
Error:/Users/radityagumay/AndroidStudioProjects/[projectname]]/app/build/intermediates/incremental/mergeDevelopmentLocalResources/merged.dir/values/values.xml:2272 style attribute '@android:attr/windowEnterAnimation' not found
Error:failed linking references
Error:java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:Execution failed for task ':app:processDevelopmentLocalResources'.
> Failed to execute aapt

**Comment by afollestad** [comment]
Nothing in that log relates to this library at all.

**Comment by leoleohan** [comment]
Just remove "@", like this "@android:attr/windowEnterAnimation" -> "android:attr/windowEnterAnimation".
