### ISSUE TITLE
Circle Progress Dialog Bug

### ISSUE THREAD

**Issue by AndWong** [afollestad/material-dialogs#1395]
![qq 20170704172224](https://user-images.githubusercontent.com/19178888/27823943-66d77552-60dd-11e7-9ac9-dbd1967a0501.png)

The Bug Like This .
[ Phone Model : Le X620 ]

**Comment by CodingAleCR** [comment]
This is probably a wrongly set style. Using
`.widgetColorRes(_your color_)`
should do the trick. You can also checking it out by setting the theme to `Theme.LIGHT`

**Comment by AndWong** [comment]
Ok,Thank You!

**Comment by afollestad** [comment]
Otherwise, report the issue here: https://github.com/DreaminginCodeZH/MaterialProgressBar/issues
