### ISSUE TITLE
Issue related to Constructor in ColorChooserDialog.Builder is still displaying Error

### ISSUE THREAD

**Issue by CeJienAJPC** [afollestad/material-dialogs#1396]
- [Y ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y ] I have verified that I am using the latest version of Material Dialogs.
- [Y ] I have given my issue a non-generic title.
- [Y ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.5`
 - Failed during Gradle Build

Also, please wrap Java with correct syntax highlighting.

`dialogColorPicker = new ColorChooserDialog.Builder((EditorLiveActivity) getActivity(), R.string.dico_ColorPalette).titleSub(R.string.dico_Colors).preselect(primaryPreselect).show(this);`
 
###### Reproduction Steps
This issue has already been closed in #683. But for some reason, the above code continues to display error.

###### Actual Result
The Gradle message is as follows

> Error:(240, 29) error: constructor Builder in class Builder cannot be applied to given types;
required: ActivityType,int
found: EditorLiveActivity,int
reason: inferred type does not conform to upper bound(s)
inferred: EditorLiveActivity
upper bound(s): AppCompatActivity,ColorCallback
where ActivityType is a type-variable:
ActivityType extends AppCompatActivity,ColorCallback declared in constructor <ActivityType>Builder(ActivityType,int)

What may be the reason? Any suggestions?

Thanks.

**Comment by afollestad** [comment]
An update has not been published. 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CeJienAJPC** [comment]
I am sorry. I didn't get you.
