### ISSUE TITLE
About dismissing!

### ISSUE THREAD

**Issue by zhuzhao404** [afollestad/material-dialogs#1397]
When I press positive button,I don't want it dismiss;

## Code:
     new MaterialDialog.Builder(this)
                        .title(R.string.measure_input_place)
                        .inputType(InputType.TYPE_CLASS_TEXT)
                        .negativeText("取消")
                        .negativeColorRes(R.color.colorBlue)
                        .positiveColorRes(R.color.red)
                        .input("请输入录入位置", null, (dialog, input) -> {
                            if (!TextUtils.isEmpty(input.toString())) {
                                ToastUtils.showShort(input.toString());
                            } else {
                                //Here,Don’t Dismiss!
                                ToastUtils.showShort("请输入录入位置");
                            }

                        })
                        .show();

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#callbacks
