### ISSUE TITLE
FileChooser can not confirm selection

### ISSUE THREAD

**Issue by martijnvm** [afollestad/material-dialogs#1398]
- Material Dialogs version: `0.9.4.5`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Nexus`
 - Device Name: `6P`
 
###### Reproduction Steps

1.  Implement the file chooser according to the readme

###### Expected Result

File can be chosen

###### Actual Result

File chooser does not have a confirm button or can no confirm a selection in any way. This is also the case in the live demo on the PlayStore

**Comment by afollestad** [comment]
That's intentional design within this library.

**Comment by rohankandwal** [comment]
Any reason for not adding choose button? It defeats the purpose of file chooser if a user can't select file.
