### ISSUE TITLE
Pelease suport SdkVersion 26

### ISSUE THREAD

**Issue by rrreza** [afollestad/material-dialogs#1399]
compile 'com.afollestad.material-dialogs:commons:0.9.4.5' is not support SdkVersion 26!!!

###### Include the following:
 - Material Dialogs version: `0.9.4.5`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by sergey-pokrovskyi** [comment]
you can fork this project and do it youself, because:
1. API 26 is in preview
2. Support lib 26.+ do not have stable release

**Comment by afollestad** [comment]
I don't plan on doing so until the Support lib v26 is stable.

**Comment by codeversed** [comment]
I have added com.android.support:support-v13:26.0.1 to match my project support lib in addition to appcompat-v7, design, etc and it seems to resolve the gradle issue. I would imagine there are still some run time errors that could happen but I have not seen any with testing core and commons.
