### ISSUE TITLE
Android Support Library 26.0.0-alpha1 clashing

### ISSUE THREAD

**Issue by vivek50** [afollestad/material-dialogs#1400]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38 is also present at [com.android.support:support-v13:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

it's working fine with api level 25 library...

**Comment by afollestad** [comment]
I won't be updating the Support library to 26 until it is stable.

**Comment by ljf1172361058** [comment]
I also encountered this error, but still thank you for the author

**Comment by vivek50** [comment]
Thank you for response...

**Comment by Devofure** [comment]
26.0.0 is now out! :)

**Comment by codesForLiving** [comment]
stable version is available

**Comment by vivek50** [comment]
Thank You for support in new version...

**Comment by iad24** [comment]
Sorry. But whats the max version of support library it can support with v0.9.4.7?
