### ISSUE TITLE
how can i pass ArrayList in materialDialog single choice list?

### ISSUE THREAD

**Issue by BatshevaR** [afollestad/material-dialogs#1401]
BTW this repository is a really greate job!!
thx !

**Comment by afollestad** [comment]
<img width="607" alt="screen shot 2017-07-11 at 10 24 17 am" src="https://user-images.githubusercontent.com/1820165/28076077-20b0e31a-6623-11e7-9da7-5469756eecc3.png">

There should be no problem with using `.items(Collection)` for that.

**Comment by BatshevaR** [comment]
thanx for the quickly reply !
in the documentation it didn't mention.
