### ISSUE TITLE
Checkbox from .checkBoxPromptRes() not visible if list from .adapter() is too long / scrollable

### ISSUE THREAD

**Issue by hardysim** [afollestad/material-dialogs#1402]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.3`
 - Device OS version: `7.1.2` and `O Prev`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

###### Reproduction Steps

```java
MaterialDialog.Builder builder = new MaterialDialog.Builder(getContext())
  .title(R.string.dialog_title_paired_bt_devices)
  .adapter(btDevicesAdapter, null)
  .negativeText(android.R.string.cancel);

if (something) {
  builder.checkBoxPromptRes(R.string.dialog_checkbox, someOtherThing, null);
}

final MaterialDialog dialog = builder.build();
```

###### Expected Result

The checkbox is displayed under the list (when the adapter contains only a few items).

![image](https://user-images.githubusercontent.com/3737512/28108243-25dba6b8-66eb-11e7-8d1a-039b10ffe7dc.png)

###### Actual Result

The checkbox is not visible when the list needs to be scrolled (e.g. testable by rotating the screen).

![image](https://user-images.githubusercontent.com/3737512/28108287-43a59762-66eb-11e7-8830-33f1268e16c7.png)

**Comment by hardysim** [comment]
@afollestad whats's the duplicate issue?

PS: Is there any progress on this?

**Comment by hardysim** [comment]
@afollestad hey - any update on this? You marked this as a duplicate? Whats the other issue?

**Comment by zunjae** [comment]
Do you plan on fixing this? I understand if you won't, but I'd like to know if you do.

**Comment by afollestad** [comment]
Will no longer apply to version 2
