### ISSUE TITLE
Input type TYPE_TEXT_VARIATION_EMAIL_ADDRESS but keyboard doesn't show @ character

### ISSUE THREAD

**Issue by anticafe** [afollestad/material-dialogs#1403]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.5`
 - Device OS version: `7.10`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. Create a dialog has EditText with `.inputType(InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS)`

###### Expected Result
When that dialog is shown and EditText is focused, the keyboard should has `@` character to allow user input the email quickly.

###### Actual Result
No `@` character in the keyboard.

**Comment by afollestad** [comment]
Well, this isn't an issue with this library. The flags you provide are passed directly to the `EditText`, it's all Android framework stuff.

**Comment by afollestad** [comment]
You may need to include the `TYPE_CLASS_TEXT` flag [as seen here](https://github.com/afollestad/material-dialogs#input-dialogs).

**Comment by anticafe** [comment]
Thanks @afollestad . I follow your guide to combine `.inputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS)` and now it works as expected. Thanks for your support.
