### ISSUE TITLE
can't set icon with drawable that is not a png

### ISSUE THREAD

**Issue by BatshevaR** [afollestad/material-dialogs#1405]
i'm trying to set a icon with :                                                                                                              
  icon(new ChannelDrawable("text"), R.color.color))
but when I get to draw() auto function I get the bound for the icon height and width =1
and than i can't see the icon
what can be the problem?
thx !

**Comment by BatshevaR** [comment]
a question : 

how can i set the color of the stroke(border) of the circles when they are not selected?
it is not getting the color of the full circle selected

**Comment by afollestad** [comment]
Well, the `ImageView` that holds the icon has its width and height set to `wrap_content`, so this is expected behavior. 

https://github.com/afollestad/material-dialogs/blob/master/core/src/main/res/layout/md_stub_titleframe.xml

You will need to decide the size of the icon yourself.
