### ISSUE TITLE
Clicking negative button fires both onNegative and cancelListerer handlers

### ISSUE THREAD

**Issue by wlara** [afollestad/material-dialogs#1409]
Material Dialogs version: 0.9.4.5
Device OS version: 7.1.1
Device Manufacturer: Nexus
Device Name: 6P

Reproduction Steps

1) Implement an auto-dismissable  Dialog according to the readme with both onNegative and cancelListener handlers.
2)  Click negative button on dialog
3) Both onNegative and canceListener are fired

Expected Result

Only onNegative llistener should be fired.

This should be an easy fix. The problem is here:

https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L435-L437

Notice that cancel() is invoked on line 436. Instead,  it should be dismiss().

**Comment by afollestad** [comment]
That's the behavior of Android Dialogs.

**Comment by wlara** [comment]
@afollestad The behavior is inconsistent with version  0.8.5.6, which I currently use on my App. Was that a fix?
