### ISSUE TITLE
how to set input dialog MultiLine?

### ISSUE THREAD

**Issue by gqandroid** [afollestad/material-dialogs#1410]

**Comment by piotrek1543** [comment]
You can do it by replacing standard Dialog layout with custom one. It could be, as an example, LinearLayout with several TextViews.

Cheers

**Comment by chnouman** [comment]
InputType.TYPE_TEXT_FLAG_IME_MULTI_LINE|InputType.TYPE_TEXT_FLAG_MULTI_LINE
not working

**Comment by chnouman** [comment]
@piotrek1543 please help.

**Comment by oradkovsky** [comment]
For someone who was searching through these duplicates but with no pointer to real answers:

1. set on builder: `<your builder>.inputType(InputType.TYPE_TEXT_FLAG_IME_MULTI_LINE)`
2. set on built dialog: `<your dialog>.getInputEditText().setSingleLine(false)`
