### ISSUE TITLE
Support morphing animation

### ISSUE THREAD

**Issue by AdityaAnand1** [afollestad/material-dialogs#1413]
Like the animation in [Plaid](https://github.com/nickbutcher/plaid) (and singled out in [this](https://github.com/hujiaweibujidao/FabDialogMorph) repo).

I managed to make the animation work with MaterialDialogs, by replacing the MaterialDialog's parent with my own (that connects it to the activity transition). [Here](https://zippy.gfycat.com/FemaleHonorableEgg.webm)'s a video showing what it looks like.

The above repos and my own implementation uses a separate Activity but I think we could figure out a way to do it with plain `Dialog` childrens (like MaterialDialog) as well. What do you think? Does this look like something that might be a good addition to Material Dialogs?

**Comment by afollestad** [comment]
I think that's too much bulk to include in the library.

**Comment by RJFares** [comment]
+1
Adding a circular reveal to the dialog is on my to-do list but I'm hoping it'll be handled by the library before I reach it :)

**Comment by AdityaAnand1** [comment]
@RJFares Perhaps [this](https://github.com/AdityaAnand1/Morphing-Material-Dialogs) might help? (My implementation combining material dialogs with a morphing animation)

**Comment by RJFares** [comment]
Awesome. I'll check it out... Thanks for sharing
