### ISSUE TITLE
Two Input Dialogs in one material-dialogs?

### ISSUE THREAD

**Issue by SimonPeter1909** [afollestad/material-dialogs#1417]
Can we add two input dialogs in one material-dialog box?

**Comment by afollestad** [comment]
With a custom layout.

**Comment by SimonPeter1909** [comment]
Thanks for the quick solution... I'm gonna close the issue now and I have
one  more doubt... how get the string value from the edittexts?

**Comment by SimonPeter1909** [comment]
I figured it out... Thanks for your help...

**Comment by chnouman** [comment]
@afollestad  you should add atleast two input dialogs.
