### ISSUE TITLE
how to Load images in  MaterialSimpleListAdapter using glide?

### ISSUE THREAD

**Issue by chnouman** [afollestad/material-dialogs#1421]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by chnouman** [comment]
adapter.add(new MaterialSimpleListItem.Builder(MyFriendsOpenProfileAct.this)
                                .content(""+postDetailModel.getPostToModelArrayList().get(i).getUsername())
                                .icon(R.drawable.icon)
                                .backgroundColor(Color.WHITE)
                                .iconPaddingDp(8)
                                .build());

**Comment by afollestad** [comment]
You'd probably want to subclass the adapter.

**Comment by chnouman** [comment]
yes thanks i have done this thanks dear
