### ISSUE TITLE
Action button visibility is VISIBLE even when not showing

### ISSUE THREAD

**Issue by ashughes** [afollestad/material-dialogs#1424]
Material Dialogs version: `0.9.4.5`

The visibility of the action buttons is set [here](https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/DialogInit.java#L164) based on the text being null or not (although I think it should use `TextUtils.isEmpty()` instead).

Then later, the visibility of the action buttons is set to `View.VISIBLE` [here](https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/DialogInit.java#L298).

The result of this is that if you try to check the visibility of an action button to determine if it is showing, you have to check both the visibility **and** whether it has text:

```java
MDButton btn = dialog.getActionButton(DialogAction.POSITIVE);
if (btn.getVisibility() == View.VISIBLE && !TextUtils.isEmpty(btn.getText())) {
    // Do something
}
```

rather than simply:
```java
if (dialog.getActionButton(DialogAction.POSITIVE).getVisibility() == View.VISIBLE) {
    // Do something
}
```

This is how AlertDialog works (only need to check visibility).

I also noticed that [`MaterialDialog.numberOfActionButtons()`](https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L593) checks both the visibility and the button text. Once the above is fixed, it should only need to check the visibility.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.5.0
