### ISSUE TITLE
switch between loading progress and percent progress

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1431]
hello
is it possible to switch between loading progressbar and percent progressbar?
I start procees of uploading a video by showing a loading progressbar, after getting response from server i start to upload the video to storage and show a percent progressbar. when uploading to storage is finished, i dismiss the percent progressbar and again show a percent progressbar. when i dismiss one progressbar then i start another progressbar so the first progressbar is dismissed and after some how the second progressbar starts . this is not good visually for users. i want to convert directly from one progressbar to another progressbar without dismissing the first one.

**Comment by AlirezaGhanbarinia** [comment]
sorry, you have labled my issue as a duplicated issue .but i didn't find the issue ? would you please mention that issue?

**Comment by afollestad** [comment]
There is an old issue a ways back.

The various progress dialog styles use their own layouts and are inflated at dialog build time, so there's no way to switch between the two.
