### ISSUE TITLE
Commons dialogs - allow passing in strings in addition to string resources

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1435]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

I'm missing a small feature for the color dialog, it would be nice to support resource strings and normal strings for titles/subtitles. Just like the default `MaterialDialog.Builder() .title(<string or res string>)` does support it

**Comment by afollestad** [comment]
Will no longer apply to version 2
