### ISSUE TITLE
where can i find support version 26.0.1

### ISSUE THREAD

**Issue by zhangchaoxu** [afollestad/material-dialogs#1436]
after i upgrade to version 0.9.4.7 from 0.9.4.5, gradle build encounter an error `failed to resolve xxx.support:appcompat-v7:26.0.1`.
and actually the latest version of support i can find is 26.0.0-alpha1 by SDK Manager.
could u pls tell me where can i find support version 26.0.1
Thanks

###### Include the following:
 - Material Dialogs version: `0.9.4.7`

**Comment by zhangchaoxu** [comment]
find the latest version after i upgrade to the latest sdk manager first, thanks

**Comment by afollestad** [comment]
To answer the question for others, they are hosted in the `google()` repository now.

https://developer.android.com/topic/libraries/support-library/setup.html

```java
repositories {
    jcenter()
    google()
    ...
}
```

**Comment by zhangchaoxu** [comment]
yes, support 26.0.1 is hosted in the google, and google() repo is only support in gradle 4.0+.
so first upgrade your gradle wrapper to 4.0+, and then add google() host.

by the way, be careful that gradle 4.0+ has a big change,  may bring some other issues which may not related to material-dialogs
