### ISSUE TITLE
DialogFragment support suggestion

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1438]
What do think about following idea:

The `DialogFragment` could look like following:

	public class MaterialDialogFragment extends DialogFragment implements MaterialDialogCallbacks {

		public static void show(AppCompatActivity context, MaterialDialog.Builder builder, String tag) {
			BaseDialogFragment dialog = new BaseDialogFragment();
			// this method must ignore any callbacks, they are not parcelable and would leak after rotation anyways
			Bundle args = builder.buildBundle();
			dialog.setArguments(args);
			dialog.show(context.getSupportFragmentManager(), tag);
		}
		
		@Override
		public void onAttach(Context context) {
			super.onAttach(context);
			if (!(getActivity() instanceof MaterialDialogCallbacks))
				throw new RuntimeException("Sorry, parents of a MaterialDialogFragment MUST implement the MaterialDialogCallbacks interface!");
		}

		@NonNull
		@Override
		public Dialog onCreateDialog(Bundle savedInstanceState) {
			// we can't use user defined callbacks, so we must catch ALL callbacks;
			// all callbacks are caught by this fragment and then are forwarded to the parent activity
			return new MaterialDialog(getArguments(), this);
		}
		
		@Override
		public void onDialogEvent(MaterialDialogEvent event) {
			((MaterialDialogCallbacks)getActivity()).onMaterialDialogEvent Occurred(event);
		}
	}

This way we could simply use any dialog as a `DialogFragment` as well. Do you think the `MaterialDialog.Builder` can be parceled and put into a bundle? Only "drawback" is, that callbacks must be removed from the builder and that the parent activity must handle them. Maybe an id for `MaterialDialogEvent` is useful for this... But above is just a draft to explain the idea...

**Comment by marbat87** [comment]
@MFlisar If I'm not wrong, this code won't work in case the MaterialDialogCallbacks is a fragment.

**Comment by MFlisar** [comment]
Actually the Builder is already serialisable, so at least we could put it as this into the bundle... Still the callbacks msut be cleared and an interface must be used instead.

@marbat87 
Because of this: `if (!(getActivity() instanceof MaterialDialogCallbacks))`? Replace `getActivity()` with the passed in `context`....

**Comment by afollestad** [comment]
The fact that none of the callbacks would survive orientation change is why I did not make a dialog Fragment version of `MaterialDialog`. It's also why the color chooser, file chooser, etc. require the Activity creating them to implement an interface.

**Comment by MFlisar** [comment]
You're currently mixing `DialogFragments` with normal `Dialogs`, is there a reason why you did this? I mean if I compare the color dialgs, file chooser dialogs and so on with the default dialogs... Just because you started this way and it's too much work? Or is there another reason?

**Comment by afollestad** [comment]
Well the dialog fragments are in the commons module and are treated like extensions to the core library.
