### ISSUE TITLE
ListDialog & AutoDismiss

### ISSUE THREAD

**Issue by zhuzhao404** [afollestad/material-dialogs#1442]

**Comment by zhuzhao404** [comment]
I mean that I do not want it to dismiss,and i set autodismiss is false,but the first time it dismiss!

**Comment by heroPool** [comment]
Problem solved?

**Comment by heroPool** [comment]
@zhuzhao404

**Comment by zhuzhao404** [comment]
Yes
new MaterialDialog.Builder(this)
                        //add here
                       .autoDismiss(false)
                        .items(items)
                        .itemsCallback((dialog, itemView, position, text) -> {
                            imgDetailsQuestionContent.setText(text);
                        })
                        .build().show();
