### ISSUE TITLE
Filed to resolve : 'com.afollestad.material-dialogs:core:0.9.4.6'

### ISSUE THREAD

**Issue by oscarshaitan** [afollestad/material-dialogs#1443]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.6`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps
I´m cloning my actual proyect on my laptop, the same proyect that work on my pc dosent work con my laptop and the problem its that Anroid studio cant find 
"compile 'com.afollestad.material-dialogs:core:0.9.4.6'"
and I export and import all the Android Studio setting 

###### Expected Result

e

###### Actual Result

e

**Comment by tylerbwong** [comment]
Doesn't look like 0.9.4.6 was ever uploaded to jcenter. (See: https://bintray.com/drummer-aidan/maven/material-dialogs%3Acore)

**Comment by afollestad** [comment]
I deleted the that version, the newer one should be used.
