### ISSUE TITLE
OnAttach is deprecated and using context is giving error

### ISSUE THREAD

**Issue by neelayak** [afollestad/material-dialogs#1448]
Hey I am using your and it really good  but I stuck with a problem as now the on attach method is deprecated then how can I use the file dialog in my app I tried the following code
`   @Override
      public void onAttach(Context context) {
        super.onAttach(context);
        
        context1=this.getActivity();
    }`
and using the context but still i am getting the error I followed this [link](https://stackoverflow.com/questions/32798224/use-material-dialog-in-fragment) .

**Comment by afollestad** [comment]
I don't the problem here is really related to this library.
