### ISSUE TITLE
How to check whether or not an action button is visible

### ISSUE THREAD

**Issue by umitems** [afollestad/material-dialogs#1453]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
-  #[x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.5.5`

I try to create a unit test to check that the negativeBtn and neutralBtn is showing or not.

```java
assertThat(dialog.dialog.getActionButton(DialogAction.NEGATIVE)
    .getVisibility(), is(View.GONE));
```
 However, I got this error message 

java.lang.AssertionError: 
Expected: is <8>
     but: was <0>
Expected :is <8>
     
Actual   :<0>

The number means VISIBLE
```java
/**
     * This view is visible.
     * Use with {@link #setVisibility} and <a href="#attr_android:visibility">{@code
     * android:visibility}.
     */
    public static final int VISIBLE = 0x00000000;

    /**
     * This view is invisible, but it still takes up space for layout purposes.
     * Use with {@link #setVisibility} and <a href="#attr_android:visibility">{@code
     * android:visibility}.
     */
    public static final int INVISIBLE = 0x00000004;

    /**
     * This view is invisible, and it doesn't take any space for layout
     * purposes. Use with {@link #setVisibility} and <a href="#attr_android:visibility">{@code
     * android:visibility}.
     */
    public static final int GONE = 0x00000008;

    /**
     * Mask for use with setFlags indicating bits used for visibility.
     * {@hide}
     */
```
###### Reproduction Steps

1. build the dialog 
2. Run 
assertThat(dialog.dialog.getActionButton(DialogAction.NEGATIVE).getVisibility(), is(View.GONE));
3. You will got error
java.lang.AssertionError: 
Expected: is <8>
     but: was <0>
Expected :is <8>
     
Actual   :<0>

###### Expected Result
passed the test.

###### Actual Result
java.lang.AssertionError: 
Expected: is <8>
     but: was <0>
Expected :is <8>
     
Actual   :<0>

**Comment by afollestad** [comment]
Fixed for https://github.com/afollestad/material-dialogs/issues/1424
