### ISSUE TITLE
Use RTL even if system language is LTR (English)

### ISSUE THREAD

**Issue by behiunforgiven** [afollestad/material-dialogs#1458]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.4.7`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy J5`

###### Description
How force dialogs use RTL Layout even if the system language is LTR (English)?

**Comment by afollestad** [comment]
That isn't supported and I don't plan on supporting it.
