### ISSUE TITLE
ColorChooserDialog.ColorCallback not working with getContext()

### ISSUE THREAD

**Issue by BRoy98** [afollestad/material-dialogs#1459]
[ ✓ ] I have verified there are no duplicate active or recent bugs, questions, or requests
[ ✓ ] I have verified that I am using the latest version of Material Dialogs.
[ ✓ ] I have given my issue a non-generic title.
[ ✓ ] I have read over the documentation (before asking questions on how to do something).

 - Material Dialogs version: `0.9.4.7`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 3`

### Problem

I added a `ColorChooserDialog` in my fragment and also implemented `ColorChooserDialog.ColorCallback`. But I am getting this error until I add `ColorChooserDialog.ColorCallback` on the parent activity:

```java.lang.IllegalStateException: ColorChooserDialog needs to be shown from an Activity/Fragment implementing ColorCallback.```

### Code

```java
new ColorChooserDialog.Builder(getContext(), R.string.color_chooser_title)
                        .preselect(primaryPreselect)
                        .dynamicButtonColor(true)
                        .show(getFragmentManager());
```

**Comment by afollestad** [comment]
You have to pass the Fragment or Activity, not `getContext()`.

**Comment by BRoy98** [comment]
How do I pass the Fragment? I tried `getFragmentManager()` but it shows Builder only accepts context:

![image](https://user-images.githubusercontent.com/12197521/30708533-dcad0ca6-9f1c-11e7-8e4c-dd8a7a525d3f.png)

**Comment by afollestad** [comment]
Pass the `this` kwyword

**Comment by BRoy98** [comment]
It is still showing the same error. It accepts `Context` only.

**Comment by AllanWang** [comment]
1. Make sure your activity (let's call it Example) implements the color picker contract
2. If you are calling this within another interface, try `Example.this` rather than just `this` to get a reference to the activity

**Comment by AllanWang** [comment]
You mentioned you implemented this in your fragment. From what I remember, fragments don't extend Context, so you'll need to implement it in the activity. Then you can use `getContext()` like before

**Comment by AllanWang** [comment]
Aidan had his reasons for keeping the two together. If you'd like to split them up, I have a [module](https://github.com/AllanWang/KAU/tree/dev/colorpicker) that does that, and also animates the color selections.

**Comment by BRoy98** [comment]
But the error says `ColorChooserDialog needs to be shown from an Activity/Fragment implementing ColorCallback`. That means implementing ColorCallback on the fragment should work.

**Comment by AllanWang** [comment]
See [here](https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/java/com/afollestad/materialdialogs/color/ColorChooserDialog.java#L113)

Either your activity or parent fragment has to implement the callback. Otherwise it will be lost due to lifecycle changes

**Comment by afollestad** [comment]
@BRoy98 @AllanWang that exception message is sourced here:

```java
@Override
  public void onAttach(Context context) {
    super.onAttach(context);
    if (getActivity() instanceof ColorCallback) {
      callback = (ColorCallback) getActivity();
    } else if (getParentFragment() instanceof ColorCallback) {
      callback = (ColorCallback) getParentFragment();
    } else {
      throw new IllegalStateException(
          "ColorChooserDialog needs to be shown from an Activity/Fragment implementing ColorCallback.");
    }
  }
```

If your Fragment is the callback, it needs to be the parent of the `DialogFragment`, not passed as the `Context` in the ctor.

**Comment by doniwinata** [comment]
Hi @afollestad ,is it possible to to show ColorChooserDialog from DialogPreference ?
Thank you

**Comment by afollestad** [comment]
@doniwinata no, you need a reference to an Activity or Fragment.

**Comment by Andrew-Quebe** [comment]
@BRoy98 I am also having this issue I think. Is your fragment a preference fragment?

@afollestad @AllanWang here's my code and stuff:

![context2](https://user-images.githubusercontent.com/11577882/33519499-94b07f6e-d75c-11e7-9c78-2f271efa9182.PNG)

![context](https://user-images.githubusercontent.com/11577882/33519500-9834c32a-d75c-11e7-8601-fac134883ec8.PNG)

![crash](https://user-images.githubusercontent.com/11577882/33519501-9b60440c-d75c-11e7-9f53-c865fc3050ba.PNG)

@BRoy98 notice how I am passing context here...this should fix your compiler error, but I think it will still crash like it does for me. @afollestad what gives?

**Comment by AllanWang** [comment]
You may need to implement the interface in the activity containing that fragment rather than that fragment. I'm not entirely sure of how getParentFragment is executed, but I doubt it will be what you want given that you are passing in the parent activity's context

**Comment by afollestad** [comment]
@Andrew-Quebe the context given is probably not an Activity context. If it is, the Activity probably doesn't implement the callback.

**Comment by Andrew-Quebe** [comment]
But see my issue is that I need the click listener to work on the preference click, and those methods are only in the PreferenceFragment classes.

Here's my activity which loads the PreferenceFragment into the content holder:
![capture](https://user-images.githubusercontent.com/11577882/33529303-1446bd52-d824-11e7-8ac9-5060b88a8a83.PNG)

Now, unless I don't know how fragments and activities work (which I don't), I don't think I can build and show the dialog on the preference fragment, and then have the callback be on the host activity...can I? The context being passed in onAttach() is the activity context, so if that activity implements the callback, could it work?

**Comment by afollestad** [comment]
Well since it is a `Fragment` you should be able to use `getActivity()`.

**Comment by AllanWang** [comment]
It may also be worth noting that you are able to retrieve the current fragment from your activity. Your implemented activity callback can look for such a fragment, see if it also implements the interface, and pass on the call where applicable.

**Comment by Andrew-Quebe** [comment]
Yay! So I just got it to work. By passing context the way I had written it (`getActivity()` also worked since they are the same thing) to the dialog builder, as well as implementing the callback in the **Activity** and not the actual fragment, everything works!

@BRoy98 perhaps this can help you too. @afollestad @AllanWang cheers!

**Comment by afollestad** [comment]
I'm going to make it so that you can have calling Fragments implement the callbacks

**Comment by Andrew-Quebe** [comment]
@afollestad nice! I think that might alleviate some of this. But tbh, this way works just fine, and it's not really a hack or workaround...just a misconception on my part of where to implement the callbacks.

**Comment by afollestad** [comment]
Will be fixed in the next release

**Comment by peterhav** [comment]
Is it possible to create a release in which this is available? I would like to implement the callbacks inside my fragment itself (and not in the parent activity).
