### ISSUE TITLE
Material Dialogs Error 

### ISSUE THREAD

**Issue by ArashMohammadi** [afollestad/material-dialogs#1462]
- Material Dialogs version: `0.9.4.7`
Hi
When I add Material Dialog Library to my project this Error appear:
Error:(2, 0) Could not read script 'D:\test\SmartSchool2\dependencies.gradle' as it does not exist.

i also add : 
\\\\\\\\\\\\***build.gradle(project)***///////////////
allprojects {
    repositories {
        jcenter()
        maven { url "http://dl.bintray.com/drummer-aidan/maven" }
        maven { url "http://dl.bintray.com/drummer-aidan/maven/com/afollestad"}
        maven { url "https://jitpack.io" }
    }
}

and :
\\\\\\\\\\\\\\\**build.gradle(app)*//////////////
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
        compile 'com.afollestad.material-dialogs:commons:0.9.4.7'
        compile 'com.afollestad.material-dialogs:core:0.9.4.7'        })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
   // compile 'com.afollestad.material-dialogs:core:0.9.4.7'
   // compile 'com.afollestad.material-dialogs:commons:0.9.4.7'
    compile project(':commons')
}

\\\\\\\\\\\\\\\\\\******//////////////////

and test both:

    compile project(':commons')

and

    compile 'com.afollestad.material-dialogs:commons:0.9.4.7'

separated sync gradle but not worked.

please help me.
Thanks

**Comment by TheIsave** [comment]
I m too getting this error , have u got the solution ??? Thn plzzz help me.

**Comment by ArashMohammadi** [comment]
hi
I used 
 compile 'com.afollestad.material-dialogs:commons:0.9.2.1'
    compile 'com.afollestad.material-dialogs:core:0.9.2.1'

in build.gradle  and connect to internet to download library directly 
also : 
  compileSdkVersion 25
    buildToolsVersion "25.0.1"

For : Material dialog 0.9.2.1

i hope its work for you.

**Comment by AmbujaAK** [comment]
Yeap it's working , thanks
