### ISSUE TITLE
Request: Release a new version

### ISSUE THREAD

**Issue by Ashok-Varma** [afollestad/material-dialogs#1466]
###### Include the following:
 - Material Dialogs version: `0.9.4.7`
 - Device OS version: `8.0.0`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

###### Support Library Update
Given all latest pull requests are merged, there are no updates for the library since Mid-Aug. Can you please upload the latest code to the maven.

**Comment by Waishon** [comment]
You can temporarily just use compile 'com.github.afollestad.material-dialogs:core:539e9e7' with the jitpack repository.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.5.0
