### ISSUE TITLE
Theming options for commons dialogs

### ISSUE THREAD

**Issue by codesForLiving** [afollestad/material-dialogs#1471]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

 - Material Dialogs version: `0.9.5.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Can we have theming options for `FolderChooserDialog.Builder` similar to `MaterialDialog.Builder`, say `postiveColor(int color)`, etc.

**Comment by afollestad** [comment]
Will no longer apply to version 2
