### ISSUE TITLE
Gradle build failed "Error:Problems reading data from Binary store"

### ISSUE THREAD

**Issue by Venzo92** [afollestad/material-dialogs#1472]
- Material Dialogs version: `any version`
-  Android Studio 2.3.3

Hello
I'm getting the following gradle compile error:
"Error:Problems reading data from Binary store in 'path/xxx.bin' (exist:true)"

Any ideas on how to fix it? I've attached the log
[idea.log](https://github.com/afollestad/material-dialogs/files/1444813/idea.log)

**Comment by afollestad** [comment]
That sounds like an issue with your local setup.
