### ISSUE TITLE
ExpandableListview in Material-Dialogs

### ISSUE THREAD

**Issue by anticafe** [afollestad/material-dialogs#1474]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [x ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.5.0`
 - Device OS version: `All`

I would like to have ExpadableListView in Material-Dialogs but there is no such built-in yet. Could you add it?

**Comment by afollestad** [comment]
You'll need a custom view.
