### ISSUE TITLE
stackingBehavior NEVER hide all buttons instead of ellipsize

### ISSUE THREAD

**Issue by mtrakal** [afollestad/material-dialogs#1475]
###### Include the following:
 - Material Dialogs version: `0.9.5.0`
 - Device OS version: `6.0.1, 8.1`
 - Device Manufacturer: `Sony, Google`
 - Device Name: `Z3 Compact, AVD`

Also, please wrap Java with correct syntax highlighting.

```java
return new MaterialDialog.Builder(context)
                .customView(mCalculatorView, false)
                .positiveText(R.string.insert)
                .negativeText(R.string.cancel)
                .neutralText(R.string.clear)
                .autoDismiss(false)
                .backgroundColorRes(R.color.uni_form_cards)
                .onPositive((dialog, which) -> {
                   ...
                })
                .stackingBehavior(StackingBehavior.NEVER)
                .onNeutral((dialog, which) -> mCalculatorView.clear())
                .onNegative((dialog, which) -> dialog.dismiss())
                .show();
```
 
###### Reproduction Steps

1. text in resources are too long to show on one line in this language, so just use long text as placeholders
2. buttons will be completely missing, not on single line as ellipsized

###### Expected Result
ellipsized 3 buttons, not hiddne buttons

###### Actual Result
all buttons are missing

When we use adaptive, buttons are stacking on 3 lines...

Screenshots with NEVER and ADAPTIVE settings.

![device-2017-11-10-171506](https://user-images.githubusercontent.com/1458891/32667405-ef4466c6-c63a-11e7-989d-3750298f81b1.png)
![device-2017-11-10-171632](https://user-images.githubusercontent.com/1458891/32667406-ef66a0f6-c63a-11e7-9196-d260df91bc31.png)

**Comment by mtrakal** [comment]
@afollestad  could you please look on this issue, or merge partial fix from me? ^

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0
