### ISSUE TITLE
SingleChoice Dialog no checkbox placeholders except selected one 

### ISSUE THREAD

**Issue by smihajlovski** [afollestad/material-dialogs#1476]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.5.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

```java
mDialog = new MaterialDialog.Builder(getContext())
                .title(R.string.sort_type_title)
                .items(sortTypes)
                .itemsCallbackSingleChoice(0, (dialog, itemView, which, text) -> {
                    Utils.doToast(getContext(), "test");
                    return true;
                })
                .show();
```
I have single choice dialog with multiple items. I remember that the last time the I used it, checkbox's placeholders were shown. Now only the selected one is shown but the others don't have a placeholder, it's just a text.
![dialog](https://user-images.githubusercontent.com/24569255/32918342-68c1e334-cb22-11e7-944b-9269c335c076.png)

**Comment by afollestad** [comment]
Hmmm, I haven't experienced this problem before.

**Comment by afollestad** [comment]
Unable to reproduce.

**Comment by smihajlovski** [comment]
Adding <item name="android:textColorSecondary">#ffffff</item> - white color, in the theme, will cause this bug. Turns out this will change the color of the unselected items in the dialog.
