### ISSUE TITLE
After upgrading android studio3.01 error

### ISSUE THREAD

**Issue by jayleco** [afollestad/material-dialogs#1477]
classpath 'com.android.tools.build:gradle:3.0.1'
###### Include the following:
![tim 20171122140717](https://user-images.githubusercontent.com/9976349/33112596-03684c00-cf8f-11e7-9f5f-aedca7c96285.jpg)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.6.0
