### ISSUE TITLE
Preference dialog animation

### ISSUE THREAD

**Issue by jmartingit** [afollestad/material-dialogs#1479]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:

 - Material Dialogs version: `0.9.4.7`
 - Device OS version: `8.0`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

###### Issue

I'm having a hard time trying to add enter and exit animations to preference dialogs (MaterialDialogPreference and MaterialListPreference).

The showDialog method in those classes already builds and shows the dialog and I have no way to hook the animation up before the dialog shows up, as I do with the MaterialDialog class.

Is there an option to do this with the library that I'm not aware of?

**Comment by afollestad** [comment]
Will no longer apply to version 2
