### ISSUE TITLE
version 0.9.6.0 not found in repo

### ISSUE THREAD

**Issue by Paul75** [afollestad/material-dialogs#1482]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.0.0`
 - Device Manufacturer: `ASUS`
 - Device Name: `Zenfone 3`

 
###### Reproduction Steps

integration version 0.9.6.0

not found in repo ?

Only 0.9.4.7 works

**Comment by afollestad** [comment]
https://bintray.com/drummer-aidan/maven/material-dialogs%3Acore/0.9.6.0
https://bintray.com/drummer-aidan/maven/material-dialogs%3Acommons/0.9.6.0
