### ISSUE TITLE
InputType not working as expected

### ISSUE THREAD

**Issue by Shahar2k5** [afollestad/material-dialogs#1483]
- Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel`

```
        MaterialDialog.Builder(activity!!)
                .title(getString(R.string.dialog_contact_name))
                .inputType(InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_FLAG_CAP_WORDS)
                .input(getString(R.string.dialog_set_name_hint), message.contactName, { _, input ->
                }).show()
```
Also I've tried `InputType.TYPE_TEXT_VARIATION_PERSON_NAME` and `InputType.TYPE_TEXT_FLAG_CAP_SENTENCES`
 
###### Reproduction Steps

1. open the dialog
2. start typing english letters

---

###### Expected Result
Capital letter at first word
---

###### Actual Result
Non of the letters are capitals
---

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/1403
https://github.com/afollestad/material-dialogs/issues/1378
