### ISSUE TITLE
autoDismiss() not working

### ISSUE THREAD

**Issue by rgfpy** [afollestad/material-dialogs#1485]
- [ x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [ x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.0.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S7`
- Android SDK: 26
- Android Studio: 3.0.1

```java
MaterialDialog dialog = new MaterialDialog.Builder(AboutActivity.this)
                            .title("")
                            .content("")
                            .progress(true, 0)
                            .autoDismiss(false)
                            .show();
```
 
---
 
###### Reproduction Steps

1. Exec and show the Progress Dialog
---

###### Expected Result
When clicked out of the Dialog Progress NOT dismissed the Dialog
---

###### Actual Result
When clicked out of the Dialog Progress dismissed the Dialog

**Comment by afollestad** [comment]
> When clicked out of the Dialog Progress NOT dismissed the Dialog

That isn't what `autoDismiss` does, read the documentation.

**Comment by rgfpy** [comment]
Yes, but in the doc is not clarity about cancelable option, i found searching in google the  function is cancelable(false) with parameter false is equal to setCancelable
