### ISSUE TITLE
SingleChoiceDialog: how to show full text?

### ISSUE THREAD

**Issue by isabsent** [afollestad/material-dialogs#1486]
For the default settings there are 2 strings of text shown for each entry. If the string is longer the remainder is invisible for user. Is it possible to show all strings?

**Comment by afollestad** [comment]
I'm not really sure what you mean. 

<img src="https://dl2.pushbulletusercontent.com/fav8QmUu7OotGPt8Qwb2rSVtbIz6KZGo/screener_1515868143160.png" width="400" />
