### ISSUE TITLE
MaterialDialog.items() throws exception: Binary XML file line #0

### ISSUE THREAD

**Issue by heyulinxp** [afollestad/material-dialogs#1488]
This is ok:
![image](https://user-images.githubusercontent.com/16595353/34077664-1844e016-e344-11e7-94cd-bceb4c1cc4c2.png)

But this throws exception:
![image](https://user-images.githubusercontent.com/16595353/34077658-f7e8fca8-e343-11e7-93d9-b0c08415d384.png)

even this throws exception:
![image](https://user-images.githubusercontent.com/16595353/34077679-72d7f0a4-e344-11e7-82f6-284035965bbf.png)

So I don't know why. Please help.

**Comment by afollestad** [comment]
There's not enough information here to know if there's an actual bug or not.
