### ISSUE TITLE
Dismiss

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [afollestad/material-dialogs#1490]
Hi 
Is it possible to dismiss all dialogs when activity goes to "onPause" mode? 
I open a dialog then without closing it, i lock the device. after unlocking the device an applock fragment opnes in my app but the previous dialog is not dismissed and make problem for my app.

![photo_2017-12-21_14-03-27](https://user-images.githubusercontent.com/15226836/34252172-c43018a8-e657-11e7-8914-60a4db74624a.jpg)

**Comment by afollestad** [comment]
You need to keep track of your dialogs and dismiss them individually.
