### ISSUE TITLE
Support reorder list items

### ISSUE THREAD

**Issue by doompadee** [afollestad/material-dialogs#1491]
I'm currently working on a new feature for Phonograph and need the ability to reorder list items in a dialog. While this is certainly possible by other means, I would find it very useful to have this feature readily build into material-dialogs for the standard lists.

I've patched my local copy accordingly. The required changes are minimal and backwards compatible. By default, the list items are not draggable just as the current status quo. But you can instruct the builder to enable dragging when desired.

Please let me know whether you like this proposal and I will send a PR.

**Comment by afollestad** [comment]
You'll have to do that in a custom view.
