### ISSUE TITLE
Single / Multi choice with enabling positiveButton plus final action

### ISSUE THREAD

**Issue by davideas** [afollestad/material-dialogs#1495]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

***

Thank you for the library, I've verified also your code too. This should be an improvement that is missing:

I use a single choice list (but this improvement is more true with multi-choice), I also disable the positive button in `showListener` callback. I've enabled the option `alwaysCallSingleChoiceCallback()` to enable the positive button everytime an item is selected (or unselected in multichoice scenario), but when I press on positive button, there's no callback with the chosen **position(s)** that is called. So dialog is dismissed and nothing happens... unless I save in my custom field the selected position.

The callback works well with chosen position(s) if `alwaysCallSingleChoiceCallback()` remains disabled, but it implies that positive button is always enabled even if no item is selected: there's no way to enable it again in the scenario I've described above.

Could you please add a way to enable the positive button at each valid selection, maybe with a new callback that delegates to the developer if a button should be enabled or not? of course that should not be used in combination of `alwaysCallSingleChoiceCallback()`.

``` java
new MaterialDialog.Builder(this)
        .title(R.string.title_dialog_restaurants)
        .items(getRestaurantNames(restaurants.data))
        .showListener(dialog -> ((MaterialDialog) dialog)
                .getActionButton(DialogAction.POSITIVE).setEnabled(false))
        .cancelable(true)
        .cancelListener(dialog -> showProgress(false))
        .alwaysCallSingleChoiceCallback()
        .itemsCallbackSingleChoice(-1, (dialog, view, which, text) -> {
            dialog.getActionButton(DialogAction.POSITIVE).setEnabled(true);
// Here: instead of alwaysCallSingleChoiceCallback, the button is always enabled
// so I can complete this action.
//            preferencesService.setLocalRestaurant(restaurants.data.get(which).getId());
//            setResult(RESULT_OK);
//            finish();
            return true;
        })
        .positiveText(R.string.choose)
        .negativeText(R.string.cancel)
        // Another improvement: this should use the default primary Text color
        // (black on light theme, etc.)
        // instead the developer setting it (same for neutral button text!)
        .negativeColorRes(android.R.color.primary_text_light)
        .show();
```

**Comment by afollestad** [comment]
Will no longer apply to upcoming version 2.0
