### ISSUE TITLE
Can't listen touch on a item

### ISSUE THREAD

**Issue by bokovdev** [afollestad/material-dialogs#1496]
When I click on the item nothing happens.
I use next implimentation:

`new MaterialDialog.Builder(getActivity())`
                `.title("Title")`
                `.adapter(adapter, new LinearLayoutManager(getActivity()))`
                `.itemsCallback(new MaterialDialog.ListCallback() {`
                    `public void onSelection(MaterialDialog materialDialog, View view, int i, CharSequence` `charSequence) { //Never come here by clicking }})`
`.show();`

And `adapter extends RecyclerView.Adapter<Some.Holder>`

So, items is showed nice in dialog, but I can't listen touch on a item.

**Comment by sarpotdarsaurabh** [comment]
I guess you need to handle the touch listeners for adapter's items on your own... in your adapter's onBindViewHolder() method I think you need to implement your logic like dismissing dialog etc. I did it same way.. Of course I used my custom adapter and sent it to .adapter() method of the MaterialDialog.Builder()

**Comment by afollestad** [comment]
Yep, the above is what I would recommend doing.
