### ISSUE TITLE
Prefil input string programmatically

### ISSUE THREAD

**Issue by FelixMittermeier** [afollestad/material-dialogs#1497]
Hello,

first of all thank you so much for this great library. It makes things much easier to do.

My problem is that I cannot insert a prefil input string into an input dialog programmatically, because it is only possible to select one from the resources.

It would be great if you can add this feature. Thanks :)

Greetings

**Comment by afollestad** [comment]
There are multiple overloads which accept a `String`/`CharSequence` literal.

<img width="703" alt="screen shot 2018-01-01 at 5 22 06 pm" src="https://user-images.githubusercontent.com/1820165/34471827-517152d6-ef18-11e7-99af-d73d683ff85a.png">

**Comment by FelixMittermeier** [comment]
Oh dear, I am so stupid and didn't saw this...

Thank you very much for your quick response 👍
