### ISSUE TITLE
Custom styles for buttons are not supported yet.

### ISSUE THREAD

**Issue by DaCrAn** [afollestad/material-dialogs#1499]
Button Custom style is not supported, but actually, I think it should be.
The only whay i found is do it programatically. in this way:
```java
TextView cutomButton = dialog.getActionButton(DialogAction.NEGATIVE);
cutomButton.setPadding(10,10,10,10);
cutomButton.setBackground(getDrawable(this, R.drawable.custom_button_drawable));
```
 Should this been considered to future versions?

**Comment by de-Stan** [comment]
Hey @DaCrAn 
Why don't you just create a custom view for your dialog?

**Comment by DaCrAn** [comment]
For the propose I need, the only thing custom I need is style button
background, I just suggest I could be nice to have it and not to do in the
way I actually display before.



On 8 Jan 2018 07:37, "de_Stan" <notifications@github.com> wrote:

Hey @DaCrAn <https://github.com/dacran>
Why don't you just create a custom view for your dialog?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/afollestad/material-dialogs/issues/1499#issuecomment-355899088>,
or mute the thread

**Comment by afollestad** [comment]
I don't intend to support that. The spacing, etc. used in the library are meant to follow the Design Guidelines.
