### ISSUE TITLE
This showMultiChoiceDisabledItems method have bug

### ISSUE THREAD

**Issue by sweet2o09** [afollestad/material-dialogs#1502]
if i click clear btn, item 0 and 1 have clear

**Comment by afollestad** [comment]
I'm not 100% clear on what you mean.

**Comment by sweet2o09** [comment]
Sorry, I'm not good at English.
Please look at the picture
![qq 20180114215056](https://user-images.githubusercontent.com/8555893/34916558-21373dbc-f975-11e7-9bae-3d5af0ece64f.jpg)
![qq 20180114215141](https://user-images.githubusercontent.com/8555893/34916560-26a1a3be-f975-11e7-9683-cef0c8fd34e6.jpg)

**Comment by afollestad** [comment]
Will be fixed in version 2.0
