### ISSUE TITLE
Custom dialog view - can't set background color to transparent?

### ISSUE THREAD

**Issue by mrhuo** [afollestad/material-dialogs#1504]
- Material Dialogs version: `0.9.6.0`
 - Device OS version: `6.0`
 - Device Manufacturer: `XiaoMi`
 - Device Name: `XiaoMi 4`

I want build an custom dialog with transparent background color, but I set 
```java
.backgroundColor(Color.TRANSPARENT)
```
does not work, what can I do for this?
---
Would you please tell me?
Thanks

**Comment by afollestad** [comment]
That's mostly intended, the Material specs would not allow a transparent dialog.

`backgroundColor` in this library only changes the layout background color, not the background color of the dialog `Window` itself.

**Comment by mrhuo** [comment]
Thanks reply, but I think that should be  a part of this great library .
I have looked at a lot of closed issues, so many peoples need this function.
Don't you think about it?

**Comment by MaSiYuan** [comment]
This worked for me,thanks @mrhuo
