### ISSUE TITLE
DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by rrbasilio** [afollestad/material-dialogs#1505]
Hi,

when I implemented this to my code and I want to use the Progress Dialog but it produce an exception when I generate the APK.

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

Here is my gradle

android {
    compileSdkVersion 26

    defaultConfig {
        applicationId "sample.project.chadbasilio.mbileapp"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 9
        versionName "2.1.1001"

        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
    }
    buildTypes {

        repositories {
            maven { url "https://jitpack.io" }
            maven { url "http://dl.bintray.com/lukaville/maven" }
            maven { url "https://maven.google.com" }
            mavenCentral()
        }

        release {
            minifyEnabled true
            debuggable true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            debuggable true
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }

        lintOptions {
            disable 'MissingTranslation'
        }

        packagingOptions {
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/notice'
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/license'
            exclude 'META-INF/license.txt'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    implementation 'com.android.support:multidex:1.0.1'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.patrickpissurno:ripple-effect:1.3.1'
    implementation 'info.hoang8f:android-segmented:1.0.6'
    implementation 'com.itextpdf:itextg:5.5.9'
    implementation 'com.wang.avi:library:2.1.3'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.4.7'
    implementation 'com.github.afollestad.material-dialogs:core:0.8.5.6@aar'
    implementation 'com.github.lzyzsd:circleprogress:1.2.1'
    implementation 'com.github.barteksc:android-pdf-viewer:3.0.0-beta.4'
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'
    implementation 'com.afollestad.material-dialogs:commons:0.9.5.0'

    implementation files('libs/universal-image-loader-1.9.5.jar')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

**Comment by alexruskovski** [comment]
The same merge error for me. Did you figure it out?

**Comment by ethanyuwang** [comment]
I have tried literally everything and the problem is still there

**Comment by sbLaughing** [comment]
In my case it's support appcompat conflict.Upgrade your support lib version to 27+ if you use
`implementation 'com.afollestad.material-dialogs:core:0.9.4.1'`
