### ISSUE TITLE
Radiobuttons + edittext

### ISSUE THREAD

**Issue by iad24** [afollestad/material-dialogs#1506]
Is there a way to easily create this dialog (with any tweaking of whatever the lib has now) and without needing to do this using a custom view.

The dlg will have a list of choices + a single edittext

![img_20180116_145713 011 png](https://user-images.githubusercontent.com/15226261/34975737-2920bc74-face-11e7-9282-099c6a4978d5.jpeg)

**Comment by iad24** [comment]
This is what I tried. But this wont show the textview.
Anyone tried to hack this?

```
MaterialDialog.Builder(this)
	.title("Title")
	.items(kotlin.collections.listOf("Option1", "Option1"))
	.itemsCallbackSingleChoice(0,
	    { dialog, view, position, text ->

	        true
	    })
	.input(ContextUtil.instance.getString(R.string.note), "", true, { dialog, input ->

	})
	.negativeText(R.string.cancel)
	.positiveText(R.string.ok)
	.show()
```

**Comment by afollestad** [comment]
Sorry, you'll need a custom view.

**Comment by sidiabale** [comment]
@afollestad I have the same situation and don't mind using a custom view. However, is it possible to do that and still benefit from the default radio button group functionality of the lib (e.g. initializing by simply providing a list of items, single choice, callbacks on selection, etc.)?
