### ISSUE TITLE
Checkbox prompt text gravity is top?

### ISSUE THREAD

**Issue by shiguiyou** [afollestad/material-dialogs#1507]
I compiled this project and install the sample in my Nexus 5 or RedMi 5 plus show the same 

![screenshot_20180116-220954](https://user-images.githubusercontent.com/17582334/34993343-fd52f6f6-fb0a-11e7-89c5-565459a90296.png)

**Comment by lambrohan** [comment]
Please solve this problem.

**Comment by toledorobson** [comment]
Same problem.

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0
