### ISSUE TITLE
Dialog with Progressbar and Recyclerview

### ISSUE THREAD

**Issue by RJFares** [afollestad/material-dialogs#1511]
I have a dialog which changes its contents after being built and shown. 
Basically, the content view text tells the user to wait, while the progress bar is animating indefinitely.

```
MaterialDialog.Builder builder = new MaterialDialog.Builder(c);
builder.title(R.string.title)
               .progress(true, 0)
               .content(R.string.standby)
               .adapter(new ItemAdapter(),new LinearLayoutManager(c))
               .positiveText(R.string.dismiss);
```
Later on, when the items are ready to be displayed, the adapter updates its items and the content view is removed along with the progress bar, and the recyclerview shows the items loaded. 

-> The progress bar in this scenario never showed because it was always null when i tried to grab it from the dialog's .getProgressBar() (only happens when the fluent .adapter() setter is used in the builder).

**Comment by afollestad** [comment]
You'll need a custom view dialog.
