### ISSUE TITLE
ColorChooserDialog class is not available 

### ISSUE THREAD

**Issue by AlaaZarifa** [afollestad/material-dialogs#1513]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---
 
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `6.0.0`
 - Device Manufacturer: `HTC`
 - Device Name: `One M8`
 
```java
 
new ColorChooserDialog.Builder(this, "Colors") // it comes in red and not recognized by the ide
        .titleSub(R.string.pick_colors)
        .preselect(R.color.white)
        .customColors(R.array.my_colors, null)
        .show(); 

```
 
![sss](https://user-images.githubusercontent.com/18426012/35832209-0f93fbec-0ad5-11e8-8eac-0f05f8240a7f.JPG)

---
 
###### Actual Result

Once I added this code, Android Studio didn't recognize the class `ColorChooserDialog` !?
I tried adding the import line as from the sample but the class `color` isn't recognized !?
 I looked up the core library and it seems the color class isn't there !? 

So how can I show color chooser dialog exactly as the sample app in play store !?

**Comment by henrichg** [comment]
You must add into gradle commons library. Read README.md.
