### ISSUE TITLE
set background and size box changes 

### ISSUE THREAD

**Issue by hossein-rezaeian** [afollestad/material-dialogs#1517]
hi, Why when I give the background color transparent The size of the box changes and be fewer
my code
```
MaterialDialog dialog = new MaterialDialog.Builder(this)
                    .customView(R.layout.myview, false)
                    .show();
dialog.getWindow().setBackgroundDrawableResource(R.color.transparent);
```

pic1:
https://i.imgur.com/Er6PWat.png
pic2:
https://i.imgur.com/jnTG8ec.png

**Comment by draskosaric** [comment]
Can you post `R.layout.myview`?

**Comment by afollestad** [comment]
Because the default window background is a rounded inset background.
