### ISSUE TITLE
is it possible to have multiple button click listeners?

### ISSUE THREAD

**Issue by or-dvir** [afollestad/material-dialogs#1519]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests]
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation

---

###### Include the following:
 - Material Dialogs version: `0.9.6.0`

i would like to add multiple button click listeners. is that possible in the version mentioned above? if so, how?
otherwise, please consider adding this feature for the next update

at the moment if i call ```onPositive(...)``` multiple times, only the last one is being called.

**Comment by Swordsman-Inaction** [comment]
No, it's not possible. It's like `setOnClickListener` of Button, you can only set one listener.
