### ISSUE TITLE
Support library 27 font support

### ISSUE THREAD

**Issue by sictiru** [afollestad/material-dialogs#1520]
Since support library v27 there is a new way of using custom fonts in our apps (without Calligraphy).

Currently for dialogs you can specify the typeface every time with the builder pattern or by using `md_medium_font` and `md_regular_font` tags in styles but the issue is that it takes fonts only from assets folder. 

Can we have an option to get it from the res/font folder ?
I'm asking this because I'll need duplicate font files or add typefaces to every dialog builder in the app and I would like to keep it short and simple.

**Comment by odlund** [comment]
👍 for this feature request
