### ISSUE TITLE
Changing Button Style from borderless to Widget.AppCompat.Button.Colored

### ISSUE THREAD

**Issue by Magurosenbei** [afollestad/material-dialogs#1521]
How can i change the default button style in the dialog to 
Widget.AppCompat.Button.Colored? 

(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `8.0.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Mate 10`

**Comment by afollestad** [comment]
See the sample projected, the Themed dialog.
