### ISSUE TITLE
how to use older 6.1.6 version .?

### ISSUE THREAD

**Issue by amrithmmh** [afollestad/material-dialogs#1522]
I am trying to compile octoprint app from source 
their dependency includes your material-dialog but the version is 6.1.6 and if I change the number to 9.6.0  I get error 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "20.0.0"

    defaultConfig {
        applicationId "android.app.printerapp"
        minSdkVersion 14
        targetSdkVersion 20
        versionName 1.0 + ";" + computeVersionName()
        versionCode System.getenv("BUILD_NUMBER") as Integer ?: 0

    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    lintOptions {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }

}

def computeVersionName() {
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'log', '-n', '1', '--pretty=format:%h%x09%ad'
        standardOutput = stdout
    }
    return stdout.toString().trim()
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile 'com.android.support:support-v4:21.+'
    compile files('libs/autobahn-0.5.0.jar')
    compile files('libs/devsmartlib.jar')
    compile files('libs/jmdns.jar')
//    compile files('libs/nineoldandroids-2.4.0.jar')
    compile files('libs/core-1.51.0.0.jar')
    //UI libraries
    compile project(':horizontallistlibrary')
    compile 'uk.co.androidalliance:edgeeffectoverride:1.0.2' //Scroll mode effect
    //Material design libraries
    compile "com.android.support:appcompat-v7:21.0.+"
    compile 'com.android.support:cardview-v7:21.+'
    compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
    compile 'com.github.fengdai:alertdialogpro-theme-material:0.2.1'
    **compile project(':materialdesignlibrary')
    compile 'com.afollestad:material-dialogs:0.9.6.0' //Material design dialogs
    compile 'com.pnikosis:materialish-progress:1.4'
    compile 'com.rengwuxian.materialedittext:library:1.8.2'
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5'
    compile files('libs/android-async-http-1.4.6.jar')**
}

**Comment by amrithmmh** [comment]
so now i am using 9.6.0 version but i get this error

import com.afollestad.materialdialogs.MaterialDialogCompat;
 not found
is there an alternative?

**Comment by marcoscgdev** [comment]
You need to change MaterialDialogCompat to MaterialDialog

**Comment by amrithmmh** [comment]
thank you @marcoscgdev it works unfortunately the the app I am trying to compile is too outdated and i cannot build it .
link:https://github.com/bq/OctoPrint-AndroidApp
uses v6.1.6 looks like its abandoned project
