### ISSUE TITLE
Dialog with items and AutoFocus

### ISSUE THREAD

**Issue by CrazyXacker** [afollestad/material-dialogs#1523]
I'm developing movie app, that can be used on Android TV and TV Boxe's. This devices uses remote DPAD control and i'm trying to adapt dialogs for easier usage.
I have simple dialog with list of items. Here is the code:
```java
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .title(selectedFiles.get(0).getPart())
                .items(getDotMenuItems(position))
                .itemsCallback((materialDialog, view, i, charSequence) -> {
                    switch (i) {
                        case 0:
                            showWatchDialog(position, FileDialogAction.SHOW);
                            break;
                        case 1:
                            showWatchDialog(position, FileDialogAction.DOWNLOAD);
                            break;
                        case 2:
                            // Creates a new text clip to put on the clipboard
                            showWatchDialog(position, FileDialogAction.COPY);
                            break;
                        case 3:
                            markFileWatched(position);
                            break;
                        case 4:
                            showWatchDialog(position, FileDialogAction.SHARE);
                            break;
                    }
                }).show();
```
If I use app with touchscreen there is no problem. Even with DPAD it's working correct. But i want to "preselect" first element (request focus for it) because, when i'm using remote, i need click dpad down TWICE to select first element of list.
How I can achieve autofocusing?

**Comment by CrazyXacker** [comment]
Checked again. I need only one click to select first element. Before that i tried to do this 
`java
dialog.getRecyclerView().scrollTo(0);
dialog.getRecyclerView().getAdapter().notifyDataSetChanged();
`
and after that i've need to click twice.

**Comment by afollestad** [comment]
Looks like there are some workarounds online but they are out of scope for this library.

https://github.com/vganin/dpad-aware-recycler-view
https://gist.github.com/vganin/8930b41f55820ec49e4d
https://stackoverflow.com/questions/48129423/horizontal-recyclerview-in-tv-dpad-focus-going-cyclic-on-fast-scroll
etc.
