### ISSUE TITLE
Cannot Change Ripple Color With RadioGroup Dialog

### ISSUE THREAD

**Issue by Patchett** [afollestad/material-dialogs#1524]
- Material Dialogs version: `0.9.4.3`
 - Device OS version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S8+`

Hello. I am using a radiogroup dialog with this library, but I cannot get the ripple effect on the radio buttons to change from grey. How can I get the ripple color to change? I have tried setting `buttonRippleColorRes()` but it does not do anything. Ideally I should be able to control the ripple color programmatically with this API but it does not seem to be working. Am I missing something or is this a bug?

Here is the code I am using to create my dialog.

```java
new MaterialDialog.Builder(getActivity())
        .title(R.string.sort_by)
        .items(R.array.sort_options)
        .dividerColorRes(R.color.colorPrimary)
        .buttonRippleColorRes(R.color.colorPrimary)
        .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {
            @Override
            public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                sortList(adapter.getCurrencyList(), which);
                adapter.notifyDataSetChanged();
                SharedPreferences.Editor editor = sharedPreferences.edit();
                editor.putInt(SORT_SETTING, which);
                editor.apply();
                Log.d("I", "Selected: " + text.toString() + " at position: " + Integer.toString(which));
                return true;
            }
        })
        .show();
```

I am expecting the code above to produce a dialog that has the same ripple color as my `colorPrimary`, but instead the ripple color is unchanged.

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0
