### ISSUE TITLE
Wrong values-large/dimens/md_preference_content_inset value

### ISSUE THREAD

**Issue by stephanedupont** [afollestad/material-dialogs#1526]
Hello,

There's an issue with the md_preference_content_inset dimensions in values-large.

To make it consistent with normal Android preferences (like SwitchPreference, etc.), it should be (instead of its unique value of 28dp for all large screens):

values-large/dimens.xml: 28dp
values-large-v21/dimens.xml: 16dp
values-large-v22/dimens.xml: 24dp

Thank you,
Stéphane.

**Comment by afollestad** [comment]
Preferences will be going away in version 2 of this library.

**Comment by stephanedupont** [comment]
Oh that's bad news. Use them a lot. Why will preferences go away?
