### ISSUE TITLE
why onInput do nothing?How to solve?

### ISSUE THREAD

**Issue by yedajiang44** [afollestad/material-dialogs#1528]
###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `SONY`
 - Device Name: `sony z5p`

```java
new MaterialDialog.Builder(this)
    .title(R.string.input)
    .inputRangeRes(2, 20, R.color.material_red_500)
    .input(null, null, new MaterialDialog.InputCallback() {
        @Override
        public void onInput(MaterialDialog dialog, CharSequence input) {
            // do log or other
        }
    }).show();
```

---

###### Expected Result
log or do something
---

###### Actual Result
no log and do not angthing,like onInput no execute

**Comment by afollestad** [comment]
By default it executes when the positive action button is pressed. There is an option to make it a text change listener which is also listed in the tutorial.
