### ISSUE TITLE
Better RTL support with action buttons

### ISSUE THREAD

**Issue by msmozafari** [afollestad/material-dialogs#153]
Hi,
It'd be cool if we could align positive and negative buttons with some methods like what's shown below, to force them to be in a specific alignment:

```java
positiveButtonGravity(int)
negativeButtonGravity(int)
```

**Comment by RyanDam** [comment]
Great idea, +1 for that :dancer:

**Comment by afollestad** [comment]
Not sure how necessary this would be. If you mean to move them around, that would kind of defy the Material design guidelines.

**Comment by msmozafari** [comment]
Hi @afollestad,
This is not based on the Material design guideline.
I'm from Iran. My language is Persian, an RTL language. (If I want use forceStacked, buttons aligned to the left).
This type of methods really is useful for RTL languages and customization.

**Comment by afollestad** [comment]
Ohhhh okay. That makes sense. That actually should be the default behavior, I'll try to improve RTL support in the next release.

**Comment by afollestad** [comment]
The major difficulty with this is that a lot of the APIs that aid with RTL support are API 17 and up only.

**Comment by afollestad** [comment]
Release 0.5.3 is now available with hugely improved RTL support.

**Comment by msmozafari** [comment]
Hi @afollestad,
Thank you for this release.
Yes. Unfortunately, before API 17 (specially API 14) RTL support not good enough.

**Comment by afollestad** [comment]
There's not much that can be done before API 17. Explicitly setting whether it's RTL or not is a bad idea, since you would then be ignoring all the people who don't use RTL.
