### ISSUE TITLE
Support Library 27

### ISSUE THREAD

**Issue by Mishabuzov** [afollestad/material-dialogs#1530]
Hello!
I want to use your lib with latest version of picasso (it requires 27.1.0 lib's version).
I have the warning in my build.gradle:
![image](https://user-images.githubusercontent.com/15013638/37873300-8fc795e0-3022-11e8-9893-3f04566b0ee5.png)
Please update support lib :)

**Comment by julesbond007** [comment]
This can be fixed as seen here: https://github.com/julesbond007/android-jigsaw-puzzle/blob/97b1b7df3d15f7df0ea65c3ca0d3019fca092b63/app/build.gradle#L55

so basically you need to include the libraries individually:

```    
implementation 'com.android.support:cardview-v7:27.1.0'
implementation 'com.android.support:recyclerview-v7:27.1.0'
implementation 'com.android.support:appcompat-v7:27.1.0'
implementation 'com.android.support:animated-vector-drawable:27.1.0'
```

**Comment by afollestad** [comment]
Upcoming version 2 will use the latest
