### ISSUE TITLE
Dynamically show and hide dialog progress bar

### ISSUE THREAD

**Issue by AlaaZarifa** [afollestad/material-dialogs#1531]
- [x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 2 XL`

```java
 new MaterialDialog.Builder(this)
        .title("Are you sure?")
        .titleColorRes(R.color.black)
        .positiveText("Delete")
        .negativeText("Dismiss")
        .typeface(typeface, typeface2)
        .positiveColorRes(R.color.primary)
        .negativeColorRes(R.color.darker_grey)
        .onNegative(new SingleButtonCallback() {
          @Override
          public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
            dialog.dismiss();
          }
        })
        .onPositive(new SingleButtonCallback() {
          @Override
          public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                 final ProgressBar bar = dialog.getProgressBar(); // gives me NPE 
                 bar.setIndeterminate(true);
                 bar.setVisibility(View.VISIBLE);
                // running api request... and hides the progress bar inside the onSuccess and onFail
                 
          }
        })
        .show();

```
 
 
---
 
###### Expected Result
I know I can do it with custom view, but I always find awesome hidden tricks with this library, so I thought I should ask.

---

**Comment by Swordsman-Inaction** [comment]
You never call `progress()` to setup the ProgressBar, there is no ProgressBar to get.

**Comment by afollestad** [comment]
^^
