### ISSUE TITLE
After Update the Android Studio 3.1,Could not determine artifacts...

### ISSUE THREAD

**Issue by xbandx68** [afollestad/material-dialogs#1533]
After Update the Android Studio 3.1, and try to build I recive this error Message:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.afollestad.material-dialogs:commons:0.9.6.0: Skipped due to earlier error

(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x ] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ x] I have verified that I am using the latest version of Material Dialogs.
- [x ] I have given my issue a non-generic title.
- [x ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap your code with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

```xml
<LinearLayout ...></LinearLayout>
```
 
---
 
###### Reproduction Steps

1. 
2. 
3. 

---

###### Expected Result

---

**Comment by tbsandee** [comment]
There are issues with bintray repository today, that's probably your problem. It just happens that you upgraded to Android Studio 3.1 today as well.

http://status.bintray.com/

**Comment by npvaddoriya** [comment]
Change google() repository & jcenter() repository access priority so that the gradle build would not fail to resolve dependencies as per latest Android Studio update.

Reference: https://stackoverflow.com/questions/50584437/android-studio-3-1-2-failed-to-resolve-runtime/50758769
