### ISSUE TITLE
Bottom Dialog

### ISSUE THREAD

**Issue by davisoqt** [afollestad/material-dialogs#1534]
How can I show a dialog placed at the bottom of the screen and animate dialog show?

**Comment by chweez** [comment]
You mean a `BottomSheetDialog` like this one [here](https://mobikul.com/android-bottom-sheet-dialog/)?

**Comment by davisoqt** [comment]
I mean do this with your lib, place a dialog at top, left,right,bottom and animate de dialog show.

**Comment by afollestad** [comment]
You'll have to move the window around, which is exposed in `getWindow()` of `android.app.Dialog`.

https://stackoverflow.com/questions/9467026/changing-position-of-the-dialog-on-screen-android

**Comment by cdcdec** [comment]
` basic.setOnClickListener {
      var dia=MaterialDialog(this)
      val window = dia.window
      var windowManager=windowManager
      var display=windowManager.defaultDisplay
      var  params = window.attributes
      var point=Point()
      display.getSize(point)
      params.height=point.y/2  // 高度设置为屏幕的0.5
      params.width=point.x   // 宽度设置为屏幕的宽度
      Log.e("111","x=${point.x},y=${point.y/2}")
      params.flags=WindowManager.LayoutParams.FLAG_DIM_BEHIND
      params.gravity=Gravity.BOTTOM
      window.attributes=params
      dia.show {
        message(R.string.shareLocationPrompt)
        debugMode(debugMode)
      }
    }`

**Comment by cdcdec** [comment]
```
 basic.setOnClickListener {
      var dia=MaterialDialog(this)
      val window = dia.window
      var windowManager=windowManager
      var display=windowManager.defaultDisplay
      var  params = window.attributes
      var point=Point()
      display.getSize(point)
      params.height=point.y/2  // 高度设置为屏幕的0.5
      params.width=point.x   // 宽度设置为屏幕的宽度
      Log.e("111","x=${point.x},y=${point.y/2}")
      params.flags=WindowManager.LayoutParams.FLAG_DIM_BEHIND
      params.gravity=Gravity.BOTTOM
      window.attributes=params
      dia.show {
        message(R.string.shareLocationPrompt)
        debugMode(debugMode)
      }
    }


```
