### ISSUE TITLE
Superb! How to detect press on link?

### ISSUE THREAD

**Issue by Noitidart** [afollestad/material-dialogs#1535]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `6.0.0`
 - Device Manufacturer: `LG`
 - Device Name: `K373`

I am creating links in my content by using html:

```java
builder.content(Html.fromHtml("hi <a href="test">test</a>"));
```

How do I detect press on this link? Is there a callback? It seems I can only use remote URLs which pop up into browser.

Thanks for such a superb module!!!

**Comment by afollestad** [comment]
You'll have to use spans for that, or set the movement method of the message `TextView`.
