### ISSUE TITLE
Using image from drawable dir in html

### ISSUE THREAD

**Issue by Noitidart** [afollestad/material-dialogs#1536]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.8.6.2`
 - Device OS version: `6.0.0`
 - Device Manufacturer: `LG`
 - Device Name: `K373`

I am creating images in my content by using html, and my image is emblem.png and it is in my `drawable` directory.

```java
builder.content(Html.fromHtml("hi <img src="emlbem.png" />"));
```

But this is showing up as a light green square. I can't figure this out. May you please help.

Sincerest thanks for such a great great module!

**Comment by afollestad** [comment]
You'll have to use spans for that.

**Comment by Noitidart** [comment]
Thanks @afollestad for personal reply. May you please show example. I am actually modifying the react-native binding to this library to add support to this feature. I'm not a native java guy, just learning by doing/accomplishing a goal I need.

**Comment by afollestad** [comment]
These are various StackOverflow examples, such as this: https://stackoverflow.com/a/3177667

**Comment by afollestad** [comment]
You can pass a `Spannable` into `.content` of the `Builder`

**Comment by Noitidart** [comment]
Thanks very much I will study that topic and try it out!
