### ISSUE TITLE
Action buttons text letters has some issues (?)

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1538]
I've been using materialdialogs in every application I developed and recently I found something that is giving me some headache

When I show a dialog on a device (I tried both, tablet and cell phone) the **"E"**  letter in the button is weird, and I cannot explain it better than showing you a picture

![](https://i.imgur.com/pIyj7LM.jpg)

And I don't find the problem on another app 

![](https://i.imgur.com/9dxbOg8.jpg)

As you can see over here the bug is not happening, it's something really hard to describe, I should do a more deep testing and investigate more (And maybe provide something more detailed than "Bug on some devices without version of lib and os" hahah)

I know, so far we know nothing about this potential issue but I just wanted to start up something to warn you about the possible existence of it. The user impression when it reads the text with the weird "E" is not good, because you can view the height padding between letters and it results something imprecise and buggy.
Maybe (And I hope that) is something that isn't determined by this library, and it would be nice, but I'm curious about that fact and I think that spending 5 minutes on it will be worth
More details upcoming, if you have some time check it out and let me know

_Sent using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afollestad** [comment]
Hmmm. I've never seen that. 

Unfortunately I can almost guarantee it's a device or OS issue, probably something I cannot fix.
