### ISSUE TITLE
Customizing the file sorting algorithm in FileChooserDialog class

### ISSUE THREAD

**Issue by pinlin0726** [afollestad/material-dialogs#1540]
I found that the sorting algorithm was defined by a static class FileSorter in FileChooserDialog class.
How can I change the sorting algorithm in FileChooserDialog class?
Thanks.

 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `4.4`

**Comment by afollestad** [comment]
Will exist in upcoming version 2
