### ISSUE TITLE
How to set up as a lowercase?

### ISSUE THREAD

**Issue by tdxtxt** [afollestad/material-dialogs#1542]
![image](https://user-images.githubusercontent.com/5369160/38917031-0b1f33f4-431c-11e8-9173-11044be28e59.png)

**Comment by afollestad** [comment]
The action buttons are intentionally capitalized to follow Material Design.

You can [get a handle to the buttons](https://github.com/afollestad/material-dialogs#getting-and-setting-action-buttons) and override [setAllCaps](https://developer.android.com/reference/android/widget/TextView.html#setAllCaps(boolean)) on their `TextView`'s, though.
