### ISSUE TITLE
FileChooserDialog and FolderChooserDialog cannot read path from external storage

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1544]
- Material Dialogs version: `0.9.6.0`
 - Device OS version: `Marshmallow`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 4X`

I cannot have access to external storage, even though I granted write and read permissions.

Let's compare these screenshots, between built-in file explorer on my device with `FolderChooserDialog`. The built-in file explorer shows the external storage's path as `M-^?M-^?M-_M-^?M-_M-^?M-_M-^?M->M-wM`,
while `FolderChooserDialog` shows it as `/storage/6331-6132`. I do not know why they can be different. The same thing happens to `FileChooserDialog` as well. I think we need to read it like what built-in file explorer did.

![Built-in file explorer](https://user-images.githubusercontent.com/12292380/39083213-1857fdc8-458b-11e8-8250-89e698e8ceda.png)

![FolderChooserDialog](https://user-images.githubusercontent.com/12292380/39083218-32e6649a-458b-11e8-8c71-1e5e69f9ec8c.png)

**Comment by afollestad** [comment]
It sounds like you didn't request permission to read external storage.
