### ISSUE TITLE
Wrong Dialog bounds after orientation change

### ISSUE THREAD

**Issue by enginegl** [afollestad/material-dialogs#1546]
- [x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

 - Material Dialogs version: `0.9.6.0`

Device 1 (affected):
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Nextbit`
 - Device Name: `Robin`

Device 2 (affected):

 - Device OS version: `7.0`
 - Device Manufacturer: `Sony`
 - Device Name: `Xperia XA1`

Device 3 (affected):

 - Device OS version: `8.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S8`

Device 4 (**not affected**):

 - Device OS version: `8.1.0`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel`

**MainActivity.java**
```java
import android.os.Bundle
import android.support.v7.app.AlertDialog
import android.support.v7.app.AppCompatActivity
import com.afollestad.materialdialogs.MaterialDialog
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        showDialog.setOnClickListener {
            startDialog()
        }
        showMaterialDialog.setOnClickListener {
            startMaterialDialog()
        }
    }

    private fun startMaterialDialog() {
        MaterialDialog.Builder(this)
            .title("MaterialDialog title")
            .content("MaterialDialog message")
            .show()
    }

    private fun startDialog() {
        AlertDialog.Builder(this)
            .setTitle("AlertDialog title")
            .setMessage("AlertDialog message")
            .show()
    }
}

```

**Activity layout:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Show dialog"
        android:id="@+id/showDialog"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <Button
        android:id="@+id/showMaterialDialog"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:text="Show material dialog"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/showDialog" />

</android.support.constraint.ConstraintLayout>
```

**Activity declaration:**
```xml
        <activity android:name=".MainActivity"
            android:configChanges="orientation|screenSize|keyboardHidden|keyboard|uiMode">
        </activity>
```
 
---
 
###### Reproduction Steps

1. Rotate your device to landscape
2. Press "Show dialog" button - AlertDialog will show
3. Rotate your device to portrait

###### Expected/actual result: 
**Dialog bounds are correct**
![ad](https://user-images.githubusercontent.com/3976062/39428175-272c13ba-4c8f-11e8-9225-985a01f82081.png)

4. Close AlertDialog
5. Rotate your device to landscape
5. Press "Show material dialog" button - MaterialDialog will show
6. Rotate your device to portrait

###### Expected Result:
**Dialog bounds are correct**

###### Actual Result:
**Incorrect dialog bounds**

![md](https://user-images.githubusercontent.com/3976062/39428177-276086cc-4c8f-11e8-9b31-d19657bc47ec.png)

**Comment by afollestad** [comment]
Closing since this applies to the old pre-rebuilt version
