### ISSUE TITLE
Request: Material DatePicker and TimePicker

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1548]
Hi there, I am asking a new feature, i.e. material DatePicker and TimePicker. I do not know how to help you since this project written in Kotlin. I hope these screenshots help you a lot.

###### Expected Result

![TimePicker](https://user-images.githubusercontent.com/12292380/39811067-c08a2b86-53b1-11e8-8d29-93cf76af432b.png)

![DatePicker](https://user-images.githubusercontent.com/12292380/39811174-0baf0938-53b2-11e8-8bc4-841c3279ff04.png)

**Comment by afollestad** [comment]
This project is currently written in Java, actually.

Version 2.0 is under development in Kotlin, though.

**Comment by anggrayudi** [comment]
@afollestad Well, does that mean you will add these dialogs later?
