### ISSUE TITLE
Failed to resolve: com.afollestad.material-dialogs:core:0.8.5.2

### ISSUE THREAD

**Issue by NrajaeiCS** [afollestad/material-dialogs#1549]
Hi 
i,m using Android Studio 2.1.2, and in my project i hava a problem with com.afollestad.material-dialogs:core:0.8.5.2, 

**here is my Gradle :**

    buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }
      allprojects {
          repositories {
           jcenter()
           mavenLocal()
           mavenCentral()
           maven { url "https://jitpack.io" }
        }
      }

**And this is my Gradle :app**

      apply plugin: 'com.android.application'

      android {
        configurations.all {
           resolutionStrategy.force 'com.android.support:support-annotations:25.3.1'
        }
    compileSdkVersion 25
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.panaceasoft.mokets"
        minSdkVersion 14
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
             }
         }
      }
    dependencies {
     compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/android-async-http-1.4.4.jar')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:palette-v7:25.3.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.mcxiaoke.volley:library:1.0.+'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.pnikosis:materialish-progress:1.5'
    compile 'com.google.android.gms:play-services-ads:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
    compile 'com.google.android.gms:play-services-gcm:9.4.0'
    compile 'com.github.rey5137:material:1.2.2'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.stripe:stripe-android:2.0.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.google.firebase:firebase-core:9.4.0'
    compile 'com.google.firebase:firebase-messaging:9.4.0'
    compile 'com.google.firebase:firebase-crash:9.4.0'
    compile 'me.zhanghai.android.materialprogressbar:library:1.1.4'

    compile('com.afollestad.material-dialogs:core:0.8.5.2@aar') {
        transitive = true
    }
    androidTestCompile 'com.android.support:support-annotations:25.1.3'
      }
       apply plugin: 'com.google.gms.google-services'

**And this is my sdk manager :**

![sdk](https://user-images.githubusercontent.com/39056107/40046164-7f8b81a4-5841-11e8-85c4-d58429e8ce3a.jpg)

![sdk2](https://user-images.githubusercontent.com/39056107/40046165-7fc300ac-5841-11e8-9f9f-00cf80ef553c.jpg)
![sdk3](https://user-images.githubusercontent.com/39056107/40046169-8049d79e-5841-11e8-9fa5-3d81133b550b.jpg)
![sdk4](https://user-images.githubusercontent.com/39056107/40046170-807de692-5841-11e8-9473-aba6e950f5f8.jpg)

anybody can help me
thank you,

**Comment by NrajaeiCS** [comment]
thank u amiyo-biswas,
when i use `compile 'com.afollestad.material-dialogs:core:0.9.6.0'` i have this error : 

Error:Failed to resolve: com.android.support:appcompat-v7:27.0.1
Install Repository and sync project
Open File
Show in Project Structure dialog

**Comment by amiyo-biswas** [comment]
@NrajaeiCS  For your above issue you should take a look here https://stackoverflow.com/questions/47164768/failed-to-resolve-com-android-supportappcompat-v727-dependency-error

**Comment by amiyo-biswas** [comment]
@NrajaeiCS Kindly check my answer https://stackoverflow.com/a/50346556/3395198

**Comment by afollestad** [comment]
The current version is 0.9.6.0.

The oldest available version is 0.8.5.9 but you _should not_ use older versions.

**Comment by afollestad** [comment]
https://bintray.com/drummer-aidan/maven/material-dialogs%3Acore

https://bintray.com/drummer-aidan/maven/material-dialogs%3Acommons
