### ISSUE TITLE
Global theming attributes for dialog background color and top/bottom divider color

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#155]
A previous pull request was made for this, but it had to be undone due to too many issues.

![one](https://cloud.githubusercontent.com/assets/1820165/5601174/437f2250-92b6-11e4-886f-8c1317f9d38f.png)

![two](https://cloud.githubusercontent.com/assets/1820165/5601196/3e8a7dac-92b7-11e4-8271-25abff5517a9.png)

I choose not to allow customization of the button and list selector for now because that causes many complications and shouldn't be necessary, since selectors should generally be neutral on Android 4.4 and above. This maintains easy ripple support on API 21, also. If you make the background color a dark color (like the one shown in the screenshots above): you should also apply the dark theme, so that list and button selectors use the lighter variation, and so that the title and list item text colors are lighter by default.

**Comment by sheharyarn** [comment]
+1
