### ISSUE TITLE
Title text not centered

### ISSUE THREAD

**Issue by tcqq** [afollestad/material-dialogs#1554]
Title text not centered.

![image](https://user-images.githubusercontent.com/10644057/40883758-35073a24-6737-11e8-96f6-2fe2726c11ef.png)
![image](https://user-images.githubusercontent.com/10644057/40883759-3e061f82-6737-11e8-9d04-d12aa59345c3.png)

**Comment by afollestad** [comment]
Will be fixed in upcoming version 2
