### ISSUE TITLE
How to set the dialog to always be at maximum height with a customView

### ISSUE THREAD

**Issue by Hodor9898** [afollestad/material-dialogs#1561]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ x] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [ x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ x] I have verified that I am using the latest version of Material Dialogs.
- [ x] I have given my issue a non-generic title.
- [ x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.9.6.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

I have a custom view dialog, and i want it to be at maximum height and for my content to match its height...

**Comment by afollestad** [comment]
There is no way to do that, other than to make your content taller.
