### ISSUE TITLE
material-dialogs don't  support data-picker years Sliding selection

### ISSUE THREAD

**Issue by lanzhu1993** [afollestad/material-dialogs#1566]
when I new MaterialDialog.Builder() , Sliding selection year , years don't  Slide

new MaterialDialog.Builder(this)
                .title(R.string.date_picker_title)
                .customView(R.layout.dialog_datepicker_layout, true)
                .positiveText(getString(R.string.sure))
                .negativeText(getString(R.string.cancle))
                .show();

**Comment by ugurcany** [comment]
I have same issue. @lanzhu1993 How did you resolve it?
