### ISSUE TITLE
itemsIds not working via view.getId()

### ISSUE THREAD

**Issue by ugurcany** [afollestad/material-dialogs#1568]
In README file, it's said that when we set `itemsIds` array for elements in the list, we need to be able to get an id via `view.getId()` inside `itemsCallback(...)`. Unfortunately, it does not work, I'm still getting random view ids generated by Android, not my ids. However, I found a workaround as follows:

            //.....
                .items(items)
                .itemsIds(itemIds)
                .itemsCallbackSingleChoice(preselectIndex,
                        (d, v, i, t) -> {
                            if (i < 0)
                                return false;

                            int itemId = d.getRecyclerView()
                                    .findViewHolderForAdapterPosition(i).itemView.getId();
                             //.....

                            return true;
                        })
           //.....

Could you please verify if your method is working or not? And if not, the correctness of this approach?

**Comment by afollestad** [comment]
`d.getRecyclerView()...` is unnecessary, the ID is set to the `v` argument (a `View`).

**Comment by afollestad** [comment]
Oh sorry, read too fast

**Comment by afollestad** [comment]
Will no longer apply to version 2.0
