### ISSUE TITLE
Failed to resolve non-core modules with 2.0.0 extension modules 

### ISSUE THREAD

**Issue by clarklak11** [afollestad/material-dialogs#1575]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha*`

```gradle
    implementation "com.afollestad.material-dialogs:core:2.0.0-alpha05"
    implementation "com.afollestad.material-dialogs:input:2.0.0-alpha05"
```

### Temporary Workaround

Add this to your repositories:

```gradle
maven { url "https://dl.bintray.com/drummer-aidan/maven/" }
```

### The module repositories

[Core](https://bintray.com/drummer-aidan/maven/material-dialogs%3Acore/2.0.0-rc4#files/com/afollestad/material-dialogs/core) / [Input](https://bintray.com/drummer-aidan/maven/material-dialogs%3Ainput/2.0.0-rc4#files/com/afollestad/material-dialogs/input) / [Files](https://bintray.com/drummer-aidan/maven/material-dialogs%3Afiles/2.0.0-rc4#files/com/afollestad/material-dialogs/files) / [Color](https://bintray.com/drummer-aidan/maven/material-dialogs%3Acolor/2.0.0-rc4#files/com/afollestad/material-dialogs/color)

**Comment by afollestad** [comment]
Does `core` resolve?

**Comment by afollestad** [comment]
Have you tried the workaround mentioned at the bottom of the release notes for alpha01? https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-alpha01

Also, alpha02 was released earlier today

**Comment by clarklak11** [comment]
Yes, core works properly. Also adding the color dependency produce the same error.

**Comment by afollestad** [comment]
Hmm, was there anything in your build Gradle logs other than failed to resolve?

**Comment by LossyDragon** [comment]
I get the following. Manually adding the .aar for colors fails to implement too. 

https://i.imgur.com/ltVC6Mc.png

**Comment by clarklak11** [comment]
Adding this to my repositories fix it. Thanks!
> maven { url "https://dl.bintray.com/drummer-aidan/maven/" }

**Comment by afollestad** [comment]
Glad the workaround works! It's very weird that that's required though, I suspect there is an issue with [Bintray](https://bintray.com/drummer-aidan/maven/material-dialogs%3Ainput) linking to [jCenter](https://bintray.com/bintray/jcenter?filterByPkgName=material-dialogs%3Ainput) for some reason 🤔

**Comment by afollestad** [comment]
Still haven't found a solution but I noticed this in the extension modules' POM files:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.afollestad.material-dialogs</groupId>
  <artifactId>files</artifactId>
  <version>2.0.0-alpha04</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>recyclerview-v7</artifactId>
      <version>28.0.0-rc01</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk7</artifactId>
      <version>1.2.60</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.afollestad.material-dialogs</groupId>
      <artifactId>core</artifactId>
      <version>2.0.0-alpha04</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

Instead of 'compile' like the `core` module, they use `runtime` for their "scope". I'm not an expert with Maven so I'm not sure what that means yet. So the workaround is still necessary. 😞

**Comment by taar1** [comment]
It's not working for me either, rolling back to 0.9.6

**Comment by afollestad** [comment]
@taar1 there's a workaround as mentioned above.

**Comment by taar1** [comment]
I've seen that and tried it out but it didn't work in my case either.

**Comment by afollestad** [comment]
@taar1 so you have something similar to this in your app module's `build.gradle`?

```gradle
repositories {
    google()
    jcenter()
    maven { url "https://dl.bintray.com/drummer-aidan/maven/" }
}

dependencies {
    ....
}
```

**Comment by afollestad** [comment]
Reaching out over here to see if anyone can help: https://github.com/novoda/bintray-release/issues/219

**Comment by KlaartjeD** [comment]
I have the same issue as @Taar1. The workaround isn't working for me either. I get:
Execution failed for task ':app:processDebugResources' :
`AGPBI: {"kind":"error","text":"error: resource android:attr/colorError not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values-v26/values-v26.xml","position":{"startLine":8,"startColumn":4,"startOffset":431,"endLine":11,"endColumn":12,"endOffset":652}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/colorError not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values-v26/values-v26.xml","position":{"startLine":12,"startColumn":4,"startOffset":657,"endLine":15,"endColumn":12,"endOffset":891}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: style attribute \u0027android:attr/keyboardNavigationCluster\u0027 not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values-v26/values-v26.xml","position":{"startLine":16,"startColumn":4,"startOffset":896,"endColumn":92,"endOffset":984}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values-v28/values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"/home/klaartje/Documents/android-projects/apps-workshop/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: style attribute \u0027android:attr/keyboardNavigationCluster\u0027 not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/design-28.0.0-rc01.aar/0365f237594a73da6b9df94d32bea4b9/res/values/values.xml","position":{"startLine":930,"startColumn":4,"startOffset":64931,"endLine":936,"endColumn":10,"endOffset":65347}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/keyboardNavigationCluster not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontStyle not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/font not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontWeight not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"/home/klaartje/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0-rc01.aar/62b2c198eafa50297a4ef5d93e198e2b/res/values/values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
:app:processDebugResources
error: failed linking references.
:app:processDebugResources FAILED`

**Comment by taar1** [comment]
I get the exact same error like @KlaartjeD does. Tried a few variations in the gradle file but it doesnt seem to work. Here is my dependency list if that is of any help:

`
dependencies {
    implementation "com.google.firebase:firebase-core:$playServicesVersion"
    implementation "com.google.firebase:firebase-invites:$playServicesVersion"
    implementation "com.google.firebase:firebase-config:$playServicesVersion"
    implementation "com.google.firebase:firebase-crash:$playServicesVersion"
    implementation "com.google.firebase:firebase-messaging:$playServicesVersion"
    implementation "com.google.firebase:firebase-appindexing:$playServicesVersion"
    api "com.android.support:appcompat-v7:$supportVersion"
    api "com.android.support:design:$supportVersion"
    api "com.android.support:recyclerview-v7:$supportVersion"
    implementation "com.github.vajro:MaterialDesignLibrary:1.6"
    api "com.afollestad.material-dialogs:core:2.0.0-alpha05"
    api "com.afollestad.material-dialogs:input:2.0.0-alpha05"
    implementation "com.google.code.gson:gson:2.8.5"
    implementation "com.google.android.gms:play-services-analytics:$playServicesVersion"
    implementation "com.google.android.gms:play-services-auth:$playServicesVersion"
    implementation "com.squareup.picasso:picasso:2.71828"
    implementation "com.appbrain:appbrain-applift-sdk:+"
    implementation "org.greenrobot:eventbus:3.1.1"
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    annotationProcessor "org.androidannotations:ormlite:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
    implementation("com.mopub:mopub-sdk:5.3.0@aar") {
        transitive = true
        // Exclude this to make it work with Gradle 3 / Android Studio 3
        exclude module: "libAvid-mopub" // To exclude AVID
        exclude module: "moat-mobile-app-kit" // To exclude Moat
    }
    implementation "com.github.hackware1993:MagicIndicator:1.5.0"
    implementation "com.simplecityapps:recyclerview-fastscroll:1.0.18"
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
}`

**Comment by afollestad** [comment]
@taar1 @KlaartjeD your app needs to use the same version of the Support library that this lib does.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/dependencies.gradle#L14

**Comment by farislivemaker** [comment]
@afollestad  i got a "error: failed linking references." issue while adding core, tried using the workaround in library still same error..

**Comment by afollestad** [comment]
@farislivemaker if you're using alpha10 your app needs to be using AndroidX instead of the now-legacy Support Library.

**Comment by serjooo** [comment]
I just tried installing and ran into the same problem; however, I realized later that I was trying to download the wrong version. 

How I thought versioning was done initially that the extension modules take the same version number as the core module. However, after taking a glance at the project I realized that the core module was at `2.0.0-beta6` while input was at `2.0.0-beta1`. After I picked `beta1` everything worked smoothly after that! Maybe this is the same problem everyone is facing without realizing and I thought it might be helpful mentioning it here.

**Comment by LossyDragon** [comment]
I'm not sure if this is still relevant to this thread since its closed, but I still get Failed to resolve: com.afollestad.material-dialogs:input:2.0.0-rc1 without the temporary workaround. Putting it back works fine. 🤔

**Comment by afollestad** [comment]
Huh, I tried all of the modules last night from a fresh project and they resolved fine

**Comment by serjooo** [comment]
I forgot to mention I had kept the workaround while installing. I was mentioning my issue as it wouldn't compile with the workaround as some other developers. However, yes without the workaround the problem still persists on my side as well.

**Comment by Belka1000867** [comment]
Facing the same problem with necessity to implement workaround.
What about the "Unresolved reference" if my project does not use androidx, which version should I use?

**Comment by shaymark** [comment]
Can you add this in the documents ?
"Add maven { url "https://dl.bintray.com/drummer-aidan/maven/" } to gradle repositories"
it took me a lot time to find the workaround,
Thanks

**Comment by Kashish-Sharma** [comment]
Above mentioned workaround also gives the same error 
"Failed to link resources"

**Comment by afollestad** [comment]
@Kashish-Sharma that's likely unrelated.

**Comment by Javinator9889** [comment]
Tested - **still failing** even using the mentioned workaround (actually I cannot setup any other version, even `alpha05` using workaround)

**Comment by afollestad** [comment]
You must be doing something wrong in your setup - I'm using it in 4 production apps.

**Comment by Javinator9889** [comment]
@afollestad I declared dependency, but browsing remote URL (https://dl.bintray.com/drummer-aidan/maven/) there is no "input" declared, so Gradle fails downloading.

I noticed that if Gradle successfully downloads once a dependency, if it fails looking for it again, it used downloaded one (it happens to me with Firebase JavaDoc dependency).

I decided to manually download the files and use it with `implementation fileTree(dir: 'input-2.0.0-rc3', include: ['*.jar'])`

**Comment by iballan** [comment]
Adding this line to my app level gradle file solved the problem for me!

`configurations.all {exclude group: 'com.android.support', module: 'support-v13'}
`

**Comment by rene-dohan** [comment]
maven { url "https://dl.bintray.com/drummer-aidan/maven/" }  woks...
Its somehow not pushed to jcenter but don't understand why...

**Comment by afollestad** [comment]
@rene-dohan yeah there appears to be some sort of syncing issue on jCenter's end 😞

**Comment by bill22863** [comment]
Things got me crazy. Even I add the workaround mentioned above, it still show gradle sync failed. The core is working fine while input extension not work successfully. I changed kotlin version still not work. Though gradle sync not show error again when I manually add .aar or .jar to my project. But it say input() not defined when using the following command:
MaterialDialog(this).show {
  input()  //showing input not defined
  positiveButton(R.string.submit)
}

Below is my gradle configuration. Any help will be appreciated.

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.tech.ido.toyoink_lightmaterialcomparison_android"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

androidExtensions {
    experimental = true
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.android.material:material:1.1.0-alpha02'
    implementation 'com.github.kittinunf.fuel:fuel:1.14.0'
    //for JVM
    implementation 'com.github.kittinunf.fuel:fuel-android:1.14.0'
    //for Android
    implementation 'com.github.kittinunf.fuel:fuel-livedata:1.14.0'
    //for LiveData support
    implementation 'com.github.kittinunf.fuel:fuel-rxjava:1.14.0'
    //for RxJava support
    implementation 'com.github.kittinunf.fuel:fuel-coroutines:1.14.0'
    //for Kotlin Coroutines support
    implementation 'com.github.kittinunf.fuel:fuel-gson:1.14.0'
    //for Gson support
    implementation 'com.github.kittinunf.fuel:fuel-jackson:1.14.0'
    //for Jackson support
    implementation 'com.github.kittinunf.fuel:fuel-moshi:1.14.0'
    //for Moshi support
    implementation 'com.github.kittinunf.fuel:fuel-forge:1.14.0'
    //for Forge support
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.kaopiz:kprogresshud:1.1.0'
    implementation project(':idolibrary')
    //Third Party library
    implementation 'info.hoang8f:fbutton:1.0.5'
    implementation 'com.hannesdorfmann.smoothprogressbar:library:1.0.0'
    implementation 'com.afollestad.material-dialogs:core:2.0.0-rc4'
    implementation 'com.afollestad.material-dialogs:input:2.0.0-rc4'
}

**Comment by bill22863** [comment]
> @bill22863 you are not using the workaround mentioned in the original post of this issue.

@afollestad  After I checked again, your right, I missed adding workaround to repositories of allprojects which after adding working like a charm. Sorry to bother you and thanks again. 

buildscript {
    ext.kotlin_version = '1.2.51'
    ext.fuel_version = '1.14.0'
    repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/drummer-aidan/maven/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
       // Forgot to add workaround here.
    }
}

**Comment by JavaCafe01** [comment]
Hi there! The workaround does work. However, my app is also hosted on f-droid and they do not allow custom maven repos.

**Comment by afollestad** [comment]
It appears Bintray does not provide support for this sort of thing unless you're an enterprise customer. Ugh.

**Comment by afollestad** [comment]
I've filed a ticket with jCenter, awaiting a response now.

**Comment by afollestad** [comment]
jCenter has relinked all of the dependencies from Bintray to jCenter, and have asked to retry now.

**Comment by afollestad** [comment]
@clarklak11 @rene-dohan @VeegaP @serjooo ^^

**Comment by afollestad** [comment]
Definitely appears to be fixed on my end
