### ISSUE TITLE
Allow dialog corner radius to be modified

### ISSUE THREAD

**Issue by vipulasri** [afollestad/material-dialogs#1578]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [X] I understand that versions below 2.0.0 will no longer be supported for updates.
- [X] I have given my issue a non-generic title.
- [X] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

In library dimens: radius of the dialogs are not according to [New Material Design Specs](https://material.io/design/components/dialogs.html#theming).

Ex: 
In Library - Corner Radius is **2dp**
New Material Design Specs - Corner Radius is **16dp** 

Reference: https://material.io/design/components/dialogs.html#theming

**Comment by afollestad** [comment]
Are you talking about the Crane Material Theme example? That's an example of how Material Theming can be adapted to a specific app use-case, but that does not say 16dp is the default corner rounding. Other examples on that page do not use 16dp.

**Comment by afollestad** [comment]
However, I can add a method to customize the corner radius to specific use cases.

**Comment by afollestad** [comment]
Resolved in https://github.com/afollestad/material-dialogs/commit/dbe0123f500e027319cdd080cbbdcdf0277fe9a7
