### ISSUE TITLE
Build fails on latest material-dialogs:core:2.0.0-alpha03

### ISSUE THREAD

**Issue by abhiTronix** [afollestad/material-dialogs#1579]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha03`

 
###### Suspected Cause

appcompat-v7-28.0.0-rc01.aar in dependency is in alpha state and unstable.

###### Steps to Reproduce 
1. #### On adding dependency:
dependencies {
    implementation 'com.afollestad.material-dialogs:core:2.0.0-alpha03'
}
#### and repository:
maven { url "https://dl.bintray.com/drummer-aidan/maven/" }

###### Expected Result
Build Successful
---

#### Error:
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\abhiu\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc01.aar\\a5a558333efe70a20c96b20a0f0decfc\\res\\values-v28\\values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\abhiu\\app\\build\\intermediates\\incremental\\mergeXenonDebugResources\\merged.dir\\values-v28\\values-v28.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"C:\\Users\\abhiu\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc01.aar\\a5a558333efe70a20c96b20a0f0decfc\\res\\values\\values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"C:\\Users\\abhiu\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc01.aar\\a5a558333efe70a20c96b20a0f0decfc\\res\\values\\values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}

**Comment by abhiTronix** [comment]
Just found this: https://stackoverflow.com/questions/48027019/how-to-manage-different-support-library-versions-for-3rd-party-deps-with-gradle

# Issue:
appcompat-v7-28.0.0-rc01 is not compatible with my current target SDK 27.

# Workaround:
### put this in your Top-Level Gradle file:
ext {
        supportlib_version = '27.1.1'
    }
    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex')) {
                    details.useVersion "$supportlib_version"
                }
            }
        }
    }

**Comment by afollestad** [comment]
28.0.0-rc01 is a release candidate, yes. Material Dialogs 2.0 is also in alpha, which also isn't "stable".
