### ISSUE TITLE
Needs testing (e.g. with color chooser in sample): Ability to detect if RecyclerView custom view is scrollable

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#158]
See around line 533 of MaterialDialog. The ability to detect if a RecyclerView is not implemented yet, which is important for displaying the top/bottom divider for a RecyclerView inside of a dialog.

**Comment by hzsweers** [comment]
Best bet is probably to just do a plain old `instanceof`, since recyclerview extends viewgroup

**Comment by afollestad** [comment]
Unfortunately it's not that simple. There's more calculation going on for non-RecyclerView scrolling views.

**Comment by afollestad** [comment]
I think I have a solution though.

**Comment by afollestad** [comment]
It's now implemented. It just needs to be tested.
