### ISSUE TITLE
Min SDK required

### ISSUE THREAD

**Issue by marbat87** [afollestad/material-dialogs#1580]
Hi,

I just wanted to know why the new minSdk is 17.
Isn't 16 enough?

Thanks in advance

**Comment by afollestad** [comment]
The world needs to move towards newer versions.

It's less to test and brings up less bugs. 

Also https://github.com/kaushikgopal/why_bump_android_minsdk

**Comment by marbat87** [comment]
This is not a REAL motivation, but library is your. I hope material component one would replace it at all.

Regards

**Comment by afollestad** [comment]
It is. You'd be surprised how many bugs show up on API 16, especially with Samsung devices. A lot of improvements from API 16->17 include RTL support.

**Comment by afollestad** [comment]
And that's fine. This is a free OS library. I don't get anything out of you using it.

**Comment by afollestad** [comment]
Dropped to 16.

**Comment by marbat87** [comment]
You're great 👍
