### ISSUE TITLE
How to remove top or bottom padding

### ISSUE THREAD

**Issue by zubairehman** [afollestad/material-dialogs#1586]
Hi,

Thanks for such a great library. 
I have been using this library to create custom dialogs but the problem is that i am getting top and bottom margins. Could you please suggest how can i mould DialogLayout.kt, so that i can pass padding from outside if needed.

**Comment by afollestad** [comment]
The title layout and buttons layout are hardcoded in and not intended to be changed - only the content in between are

**Comment by mohandeath** [comment]
Could you please tell me where can I change this? Don't have enough time to walk through the whole code and i really need my custom view to be stuck to the top of dialog
