### ISSUE TITLE
Crash in FileChooserDialog when navigating up

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1587]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha05`
 - Affected device: emulator (API 28)

Crash in FileChooserDialog when keep on navigating up: 

```
java.lang.IllegalStateException: parentFile must not be null
        at com.afollestad.materialdialogs.files.utilext.FilesUtilExtKt.betterParent(FilesUtilExt.kt:28)
        at com.afollestad.materialdialogs.files.utilext.FilesUtilExtKt.hasParent(FilesUtilExt.kt:16)
```

###### Expected Result

No 'folder back' icon in case further back navigation is impossible.

P.s. Thanks for providing this major v2 update! Looks very promising.

**Comment by panda912** [comment]
I have the same problem.
version: 2.0.0-rc7

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-rc8
