### ISSUE TITLE
FileChooser Dialog shows 'OK' button by default

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1588]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x ] I have given my issue a non-generic title.
- [x ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha05`
- Emulator API 28

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
MaterialDialog(c)
            .fileChooser (filter = myFilter) { _, file ->
                fileSelected(file)
            }
            .show()
```

###### Expected Result

The Dialog should not show an OK button (in this case this is not specified). A file should be selected as soon as the user clicks on it.

This is how it's documented, and similar to the 1.x behavior.

---

###### Actual Result

The Dialog shows an OK button, you need to select a file and then press the OK button.

**Comment by afollestad** [comment]
You need to pass `waitForPositiveButton = false` in `.fileChooser(...)`.

**Comment by afollestad** [comment]
The code includes:
```kotlin
  if (waitForPositiveButton && selection != null) {
    setActionButtonEnabled(POSITIVE, false)
    positiveButton {
      val selectedFile = adapter.selectedFile
      if (selectedFile != null) {
        selection.invoke(this, selectedFile)
      }
    }
  }
```
