### ISSUE TITLE
Add fluent `cancelable` method

### ISSUE THREAD

**Issue by sriramr98** [afollestad/material-dialogs#1590]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

I would like a feature where we can prevent dismissal of dialog if a tap occurs anywhere outside the dialog. This will be useful if we need some input from the dialog and it can't be ignored.

 - Material Dialogs version: `2.0.0-alpha6`

**Comment by afollestad** [comment]
For now, you can just use [setCancelable(boolean)](https://developer.android.com/reference/android/app/Dialog#setCancelable(boolean)) on your `Dialog` instance.

It isn't fluent (doesn't return the dialog) so it would have to be called on its own:

```kotlin
val dialog = MaterialDialog(...)

dialog.setCancelable(false)
```
