### ISSUE TITLE
customView is not declared

### ISSUE THREAD

**Issue by ZakariaJawas** [afollestad/material-dialogs#1591]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha06`

i can't use .customView after i upgraded the library, it says cannot resolve method customView
i'm using the library in java

**Comment by afollestad** [comment]
Unfortunately you need to use Kotlin.
