### ISSUE TITLE
Three buttons in a dialog

### ISSUE THREAD

**Issue by JZDevelopers** [afollestad/material-dialogs#1595]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x ] I have given my issue a non-generic title.
- [ x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha07`
 - Affected device: Google Pixel 2 XL with Android 9.0

Hi,
I am trying to make a dialog with three buttons but I see that the neutral button is deprecated. In the documentation about long button text I see that you have three buttons in the dialog so I know its possible. What is the best way to implement three buttons now that the neutral button is deprecated. Thanks!

**Comment by afollestad** [comment]
As the docs state, it's deprecated to discourage use per Google's guidelines. It still works.
