### ISSUE TITLE
Input dialog pre-fill should place cursor at the end 

### ISSUE THREAD

**Issue by TheZoker** [afollestad/material-dialogs#1597]
Can you please add the input option, to set the cursor at the end of the prefilled text?
So when the user opens a dialog, which has a prefilled text, the cursor is at the end of the text, not at the beginning. 

Like 
```kotlin
.input(prefilledCursorAtEnd = true) { dialog, text -> 
      // Text changed
}
```
or something similar

Function for normal input fields would be:
```kotlin
field.setSelection(field.text.length)
```

**Comment by TheZoker** [comment]
I updated to `alpha08` today, but still the cursor is at the beginning of the text not the end

**Comment by supervara91** [comment]
Example cursor at the end

val dialog = MaterialDialog(requireContext())
			.title(text = "Example")
			.positiveButton(text = "Update")
			.negativeButton(text = "Cancel")
			.input(prefill = "Example")
val inputField = dialog.getInputField()!!
val cursor = inputField.text.length
inputField.setSelection(cursor)
dialog.show()

**Comment by TheZoker** [comment]
Works! Thank you 😄
