### ISSUE TITLE
Positive action button not disabled correctly with input dialogs

### ISSUE THREAD

**Issue by supervara91** [afollestad/material-dialogs#1599]
The positive button is enable at the beginning. When a letter is written and deleted, it is disabled. I have solved it with

`dialog.getInputField () !!. setText ("")`

but should do it by default

See attached video

[button ok.mp4.zip](https://github.com/afollestad/material-dialogs/files/2367238/button.ok.mp4.zip)

**Comment by supervara91** [comment]
When is it used

`.input (maxLength = 10)`

and reaches the character limit, the positive button is not disabled. I have solved it with

```
.input(waitForPositiveButton = false) { dialog, text ->
	when {
		text.length > 10 -> {
			dialog.setActionButtonEnabled(WhichButton.POSITIVE, false)
		}
		else -> true
	}
}
```

but should do it by default

See attached video

[max length.mp4.zip](https://github.com/afollestad/material-dialogs/files/2367303/max.length.mp4.zip)

**Comment by supervara91** [comment]
When an icon is used for the dialog, the title is cut off

See attached video

[icon.mp4.zip](https://github.com/afollestad/material-dialogs/files/2367324/icon.mp4.zip)

**Comment by supervara91** [comment]
When is it used

```
.input(maxLength = 10) { dialog, text ->
	when {
		text.length > 10 -> {
			dialog.setActionButtonEnabled(WhichButton.POSITIVE, false)
			dialog.getInputField()!!.error = "Only 10"
		}
	}
}
```

the default error of the inputtext goes to the right, just above the counter. It would be better if the counter were on the left.

See attached video

[error.mp4.zip](https://github.com/afollestad/material-dialogs/files/2367359/error.mp4.zip)

**Comment by afollestad** [comment]
Regarding the counter being on the right, that's the behavior of Google's support library and that will not be changed

**Comment by afollestad** [comment]
If an icon is missing that belongs in a separate issue.
