### ISSUE TITLE
Create new folder in Folder Chooser Dialog

### ISSUE THREAD

**Issue by sriramr98** [afollestad/material-dialogs#1602]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

 - Material Dialogs version: `2.0.0-alpha09`

I was thinking that maybe an option to create a new folder option should be available in the Folder Chooser Dialog. There are many use cases in many different apps that can use this feature and including this in the builder would be a great addition to this library in my opinion

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-alpha10
