### ISSUE TITLE
IDE cannot find .listItemsSingleChoice(items = myItems)

### ISSUE THREAD

**Issue by JZDevelopers** [afollestad/material-dialogs#1605]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [ x] I have given my issue a non-generic title.
- [x ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-aplha10`
 - Affected device: Google Pixel 2 XL with Android 9.0

Hi, 

Once I updated to alpha 10 this line of code gives the error 
(unreslved reference: listItemsSingleChoice)

and this piece of code show up red
` .listItemsSingleChoice(items = myItems)`

any idea why?

**Comment by JZDevelopers** [comment]
Yep, Android studio automatically adds my imports but just to make sure I deleted the code and imports and re added it and the same problem occurred

**Comment by afollestad** [comment]
Hmm. The build is passing on CI so there shouldn't be any issues on the library end. 

The sample uses that method and the build is successful.

**Comment by JZDevelopers** [comment]
Yeah, it builds fine for me too but can't find the method after. Just shows up red and spits the can't resolve error

**Comment by JZDevelopers** [comment]
Just tried it, same problem :(

**Comment by afollestad** [comment]
Probably a dumb question but I'm assuming you're using Kotlin and not Java?

**Comment by afollestad** [comment]
Oh yeah you're using named params so you are. Weird. 

Is your app using the latest Kotlin plugin?

**Comment by JZDevelopers** [comment]
Yep I'm using kotlin. I update the plug-in as Android studio tells me to and I checked to see if I had any updates and Android studio says I'm all up to date

**Comment by JZDevelopers** [comment]
Just in case I'm not how do I check to see if I am?

**Comment by JZDevelopers** [comment]
I was not on the most updated version so I updated then invalidated caches again but it still is not working

**Comment by afollestad** [comment]
Merging this issue with #1607

**Comment by afollestad** [comment]
Should be fixed in alpha11
