### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kaylafittzgerald** [afollestad/material-dialogs#1606]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [ ] I have given my issue a non-generic title.
- [ ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `0.x.x`
 - Affected device: Google Pixel 2 XL with Android 9.0

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
println("Hello, world!")
```

```xml
<LinearLayout ...></LinearLayout>
```
 
---
 
###### Reproduction Steps

1.

---

###### Expected Result

---

**Comment by afollestad** [comment]
This is not a valid issue.
