### ISSUE TITLE
Extension functions aren't resolving 

### ISSUE THREAD

**Issue by CHOIMINSEOK** [afollestad/material-dialogs#1607]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-alpha10`

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
val dialog = MaterialDialog(this)
            .customView(view = dialogTrainerChange, false)
            .show()
```
 
---

Thanks for your fully convenient library :) 
Recently I try to migrate from `0.9.6.0` to `2.00-alpha` because of proguard issue of previous version. but when I access extension function `customView` of new version, AS says `cannot find declaration to go to`( It's same for all of other extension functions).

My project is in Kotlin version `1.2.70`, AndroidX, gradle `3.2.0-rc03`, tested in AS `3.2-RC02`. I have tried many things like `invalidate and restart`, `rearrange library with restart`, update `AS version`,  `Kotlin version`, `gradle version`.. but I can't figure it out why it happens.

 Any Advise for me? ;(

**Comment by afollestad** [comment]
Can you try 2.0.0-alpha09? It doesn't have AndroidX but another recent issue has the same problem with 10.

**Comment by CHOIMINSEOK** [comment]
It resolved. Thanks!

**Comment by JZDevelopers** [comment]
going back to version 09 fixed the problem for me too, so whatever changed after 09 in version 10 is causing this problem

**Comment by afollestad** [comment]
Should be fixed in alpha11

**Comment by afollestad** [comment]
Looks like it could maybe still be an issue

**Comment by afollestad** [comment]
Nevermind all is well
