### ISSUE TITLE
Multichoise implementation

### ISSUE THREAD

**Issue by MSureshKumarRDA** [afollestad/material-dialogs#1608]
- Material Dialogs version: `0.x.x`
com.afollestad.material-dialogs:core:2.0.0-alpha11
 
Cannot resolve method 'listItemsMultiChoice(int, ?)'

MaterialDialog mm = new MaterialDialog(this).listItemsMultiChoice(R.array.spe_list, initialSelection = indices).show();

**Comment by afollestad** [comment]
#1607

**Comment by afollestad** [comment]
Oh, it's not a duplicate as I thought. 

You need to use Kotlin for extension methods.
