### ISSUE TITLE
customView extension function not resolving 

### ISSUE THREAD

**Issue by raquezha** [afollestad/material-dialogs#1609]
According to your guide I should do it like this:
```kotlin
val myView: View = // ...

MaterialDialog(this)
  ...
  .customView(view = myView)
  .show()
```

but unfortunately
```kotlin
  .customView(view = myView)
```
function is nowhere to be found. Am I missing something?

then I do it like this:

```kotlin
 val dialog = MaterialDialog(this)
.title(R.string.recommend_restaurant)
.positiveButton(text="OK")
//then this
 dialog.setContentView(R.layout.dialog_recommend_resto)
//the show
dialog.show()
```

but it shows the dialog with customView but it doesn't show title and positive button

**Comment by afollestad** [comment]
What version of the library are you using?

**Comment by afollestad** [comment]
See #1607

**Comment by raquezha** [comment]
Thanks! I updated the version to 2.0.0-alpha11 and now its working!

---
I'm using 2.0.0-alpha10 when I encounter the problem
