### ISSUE TITLE
Custom title and content color attribues not found

### ISSUE THREAD

**Issue by csababiro** [afollestad/material-dialogs#1610]
Version:
com.afollestad.material-dialogs:color:2.0.0-alpha09

Everything works fine, except those two attributes are not found.

With: 
<item name="md_corner_radius">16dp</item> 
works fine.
but with 
<item name="md_color_title">@color/dialogTitle</item>
<item name="md_color_content">@color/dialogContent</item>

Error:
error: style attribute 'attr/md_color_title (aka com.test.package:attr/md_color_title)' not found.
error: style attribute 'attr/md_color_content (aka com.test.package/md_color_content)' not found.

error: style attribute 'attr/md_color_title (aka com.test.package:attr/md_color_title)' not found.
Message{kind=ERROR, text=error: style attribute 'attr/md_color_title (aka com.test.package:attr/md_color_title)' not found., sources=[C:\AndroidStudioWorkspace\Project\commoncore\build\intermediates\packaged_res\debug\values\values.xml], original message=, tool name=Optional.of(AAPT)}

Details:
AGPBI: {"kind":"error","text":"error: style attribute \u0027attr/md_color_title (aka com.test.package:attr/md_color_title)\u0027 not found.","sources":[{"file":"C:\\AndroidStudioWorkspace\\Project\\commoncore\\build\\intermediates\\packaged_res\\debug\\values\\values.xml"}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: style attribute \u0027attr/md_color_content (aka com.test.package:attr/md_color_content)\u0027 not found.","sources":[{"file":"C:\\AndroidStudioWorkspace\\Project\\commoncore\\build\\intermediates\\packaged_res\\debug\\values\\values.xml"}],"original":"","tool":"AAPT"}

In my modules I used my own support library version, not the library's support library:

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "${supportLibraryVersion}"
            }
        }
    }
}

**Comment by afollestad** [comment]
You're two versions behind.
