### ISSUE TITLE
Illegal character in compiler Kotlin module names

### ISSUE THREAD

**Issue by radhsyn83** [afollestad/material-dialogs#1611]
I got error 
"Illegal char <:> at index 41: \META-INF\com.afollestad.material-dialogs:core.kotlin_module"

How can i fix that ?
thanks

**Comment by afollestad** [comment]
Hmm. Weird. I wonder if it's due to the OS you're using. It works on Unix.

**Comment by ahmadalibaloch** [comment]
same for me on Win 19 with alpha11.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-alpha12
