### ISSUE TITLE
Add the ability to remove default root layout margin

### ISSUE THREAD

**Issue by bernaferrari** [afollestad/material-dialogs#1612]
I am using Material Dialogs with RecyclerView and it got super weird on top and bottom. Check below comparison between before and now.

Most of the code is really standard and [my app is open source](https://github.com/bernaferrari/ChangeDetection) (but I still haven't pushed the changes).

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/defaultRecycler"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/windowBackground"
    app:layoutManager="android.support.v7.widget.LinearLayoutManager" />
```

```kotlin
val materialDialog = MaterialDialog(activity)
            .customView(R.layout.recyclerview)
            .noAutoDismiss()
            .negativeButton(R.string.cancel) { it.dismiss() }
            .positiveButton(R.string.save) { dialog ->
                ...
            }

        materialDialog.getCustomView()?.findViewById<RecyclerView>(R.id.defaultRecycler)?.apply {
            this.overScrollMode = View.OVER_SCROLL_NEVER
            this.layoutManager = LinearLayoutManager(this.context)
            this.adapter = GroupAdapter<ViewHolder>().apply {
                add(dialogItemTitle)
                add(Section(listOfItems))
                add(dialogItemColorPicker)
            }
        }

        materialDialog.show()
```
0.96
![screenshot_20180914-205837_change detection](https://user-images.githubusercontent.com/351125/45900425-23602080-bdb6-11e8-8af2-d5493fa0c86b.jpg)

2.0
![screenshot_20180921-154421_change detection](https://user-images.githubusercontent.com/351125/45900420-20fdc680-bdb6-11e8-9852-ce54cd5c27fd.jpg)

**Comment by afollestad** [comment]
That 12dp of space is added by [DialogLayout](https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/internal/main/DialogLayout.kt) intentionally. It's 16dp when there is a title view, 12dp otherwise.

Looks like there may need to be an option to remove it.

**Comment by bernaferrari** [comment]
> Looks like there may need to be an option to remove it.

Thanks! I am completely favourable to this idea.

**Comment by bernaferrari** [comment]
That was fast. Really fast. Thanks a lot!!

**Comment by afollestad** [comment]
No problem, hopefully this works for you!

https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-alpha12

**Comment by bernaferrari** [comment]
I just tested. Everything is great again! Thanks!!
