### ISSUE TITLE
Improve launch performance of file and folder choosers 

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1615]
I don't know if it is just a local problem of my devices, but the beta versions of material dialogs seem like a little bit slow, for example, in the demo app if I press on "Folder Chooser + Button" I get a very slow response (1 second after I touch the screen the dialog is shown) and the list scroll is not smooth, it loses frames.
Maybe is just a local/beta issue, but I wanted to point that out to be sure.

**Comment by afollestad** [comment]
It's not a beta issue - probably need to load files/folders on a different thread
