### ISSUE TITLE
Kotlin 1.2.70 not working when added to dependency

### ISSUE THREAD

**Issue by ronjunelopez** [afollestad/material-dialogs#1616]

**Comment by afollestad** [comment]
This is not enough information to be an issue.

**Comment by ronjunelopez** [comment]
after synching gradle, `import kotlinx.android.synthetic` is not working

**Comment by afollestad** [comment]
Hmm - sounds like an issue on your machine.

Make sure you're using Android Studio 3.2 and have the latest Kotlin plugin installed.

**Comment by ronjunelopez** [comment]
I am using 3.1.3 android studio

**Comment by afollestad** [comment]
Technically the issue you mentioned above is in the sample project. 

The library does not use KotlinX extensions.

**Comment by ronjunelopez** [comment]
thank you, it's working properly now at 3.2

**Comment by ronjunelopez** [comment]
still not working on 3.2, any suggestions to make?

**Comment by afollestad** [comment]
Unfortunately I don't, since the build passes locally for me, and it passes on CI. 

This shouldn't affect your ability to depend on the library via Gradle, though.

**Comment by afollestad** [comment]
It might be worth searching StackOverflow or Google

**Comment by ronjunelopez** [comment]
I will try to update Gradle to latest version

**Comment by afollestad** [comment]
Wait, is the issue that your app using kotlinx isn't working with this library added as a dependency?

Your app is probably using an old version of Kotlin

**Comment by ronjunelopez** [comment]
yes after adding the library, I am unable to use variable created from id in the layout
