### ISSUE TITLE
Change checkbox color

### ISSUE THREAD

**Issue by iranappo** [afollestad/material-dialogs#1617]
Hi
I need change Checkbox TintColor
Is it possible?

**Comment by afollestad** [comment]
No, per [What's New in Version 2](https://github.com/afollestad/material-dialogs#changes-in-version-2):
> No dynamic color support, your dialogs will match your app theme.

You could pass a `ContextThemeWrapper` in your dialog constructor, though, if you don't want the checkboxes to match your app's `colorAccent`.
