### ISSUE TITLE
Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by Rawaneeta1** [afollestad/material-dialogs#1618]
I'm not able to install the library in my project, it keeps giving me this error. 

`Error: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
`

**Comment by afollestad** [comment]
Your app needs to switch to AndroidX.

**Comment by themuco** [comment]
I saw that same error 
but ı didnt understand what should i do 
how can i switch to AndroidX ? 
can you tell me

**Comment by afollestad** [comment]
http://google.com/search?q=AndroidX+migration was

**Comment by themuco** [comment]
i migrate androidX from refactor 
but same error occured
