### ISSUE TITLE
Dark theme's divider doesn't look right

### ISSUE THREAD

**Issue by jordyamc** [afollestad/material-dialogs#1619]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta3`
 - Affected device: Moto G5 Plus

![photo_2018-09-26_20-17-50](https://user-images.githubusercontent.com/6831873/46118205-015a0a00-c1cb-11e8-88ca-14c1bbe97cdb.jpg)
![photo_2018-09-26_20-18-02](https://user-images.githubusercontent.com/6831873/46118206-015a0a00-c1cb-11e8-8018-c0f019018a2b.jpg)

 
---
 
###### Reproduction Steps

1. Create single choise dialog with dark/light theme

---

###### Expected Result

Top and bottom lines shows expected colors

---

###### Actual Result

The colors are inverted

**Comment by afollestad** [comment]
I wouldn't say they're inverted - #e0e0e0 is the correct color for dividers in a light theme (https://material.io/design/components/dividers.html#theming).
