### ISSUE TITLE
No control over title gravity

### ISSUE THREAD

**Issue by msmozafari** [afollestad/material-dialogs#162]
Hi @afollestad,
I dont have any control over titleGravity.
titleGravity(MaterialDialog.END) & titleGravity(MaterialDialog.CENTER) & titleGravity(MaterialDialog.START) have same result.

**Comment by afollestad** [comment]
Good find, should be fixed in release 0.5.7 :)

**Comment by afollestad** [comment]
@msmozafari sorry, one more fix now in release 0.5.8

**Comment by msmozafari** [comment]
@afollestad Thank you, it's so cool.
