### ISSUE TITLE
A merge error about Manifest

### ISSUE THREAD

**Issue by Maskedheroe** [afollestad/material-dialogs#1620]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0`
 - compileSdkVersion 28

Also, please wrap your code with correct syntax highlighting (not just indents).

```xml
 <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:appComponentFactory"
        >
```
 My dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    compile 'com.android.support:appcompat-v7:27.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

Dear afollestad 
  When I import library， I got a manifest merge error message.

  Here is the message :
```
Error:Execution failed for task ':app:processDebugManifest'.>
 Manifest merger failed : Attribute application@appComponentFactory 
value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
  	is also present at [com.android.support:support-compat:28.0.0-rc02] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-21:19 to override.
```

Though I added the suggestion, it was  not work! (I also add the maven)

**Comment by afollestad** [comment]
Your app needs to use AndroidX.

**Comment by paulomcnally** [comment]
More info -> https://developer.android.com/jetpack/androidx/migrate
