### ISSUE TITLE
Expose dialog's TextView

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1621]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta3`
 - Affected device: All

Before v2 we could use `dialog.getContentView()`, now I'm missing something like this. Can you expose the `textViewMessage` field please?

I use this to set custom text sizes without a custom view or to use spannables and similar via direct access to the dialog's `TextView`

**Edit**

Current solution is a reflection based extension method:

```
fun MaterialDialog.textView(): TextView = javaClass.getDeclaredField("textViewMessage").let {
    it.isAccessible = true
    return it.get(this) as TextView
}
```

**Comment by MFlisar** [comment]
Additionally, the same would be useful the view itself as well...

**Comment by afollestad** [comment]
You can already get the root view with the preexisting dialog API exposed from Android. 

Snackbars in a dialog would seen like an anti pattern to me though.

**Comment by afollestad** [comment]
I currently don't plan to expose the message text view.

**Comment by MFlisar** [comment]
If someone needs this, this is how it can be solved:

**Extension method**
```
fun MaterialDialog.textView(): TextView? = javaClass.getDeclaredField("textViewMessage").let {
    it.isAccessible = true
    return it.get(this) as TextView?
}
```

**Proguard, e.g.**

-keep class com.afollestad.materialdialogs.MaterialDialog {*;}
