### ISSUE TITLE
aapt2 failed linking References 

### ISSUE THREAD

**Issue by NadeemJamal** [afollestad/material-dialogs#1622]
Dependancies    implementation "com.afollestad.material-dialogs:core:2.0.0-beta3"

I tried all of them same issue...

 Android resource linking failed
Output:  C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:753: error: resource android:attr/fontVariationSettings not found.
C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:753: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\Nadeem\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\0831aa100fed3422e8faea3cbdb9fd60\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
        C:\Users\Nadeem\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        com.mts.salestracker\
        -0\
        apk\
        --output-text-symbols\
        C:\Android Learning\Tracker\Sales Tracker v1.01 RL280918\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

**Comment by afollestad** [comment]
Your app needs to use AndroidX.
