### ISSUE TITLE
RecyclerView and message can't be used together

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1624]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta3`
 - Affected device: All

Currently the dialog does not allow to use a `RecyclerView` and a message at the same time, because adding a message wraps the view in a `ScrollView` and afterwards you can't add the `RecyclerView` anymore...

I think it would make sense to allow this, some non scrollable information above a list (e.g. a counter that shows how many items are selected or similar) is very useful. This was easily achieveable in v1.

Maybe it would make sense to allow to add a message without wrapping it in a scrollview which than can be used with a `RecyclerView` or list?

**Comment by darkyuhooxxx** [comment]
RecyclerView and text can't be used together #1624
@MFlisar
MFlisar opened this issue 
16 days ago

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-beta06
