### ISSUE TITLE
Failed to Resolve Gradle error

### ISSUE THREAD

**Issue by SaveenaJoshi** [afollestad/material-dialogs#1625]
error: resource android:attr/dialogCornerRadius not found. Message{kind=ERROR, text=error: resource android:attr/dialogCornerRadius not found., sources=[C:\Users\USER.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0.aar\ec07b037e24e75d8fe18391b7d170304\res\values-v28\values-v28.xml:9:5-12:13], original message=, tool name=Optional.of(AAPT)}
working with the cure and working with Android 27 works fine.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/1620
https://github.com/afollestad/material-dialogs/issues/1622
