### ISSUE TITLE
Support for MaterialComponents theming

### ISSUE THREAD

**Issue by ridcully99** [afollestad/material-dialogs#1628]
Will there be better support for MaterialComponents theming in the future?

For example, the buttons should be derived from MaterialButton in order to pick up theming correctly.

Also, I noticed that, when I specify filled-box for TextInputLayout, the grey filled-box is shifted somehow to the top-left.

Thanks for the library, although I had to write a Java 'wrapper' now, to be able to use the new version.

**Comment by afollestad** [comment]
What does it provide to this library that `AppCompatButton` from AndroidX does not?

**Comment by afollestad** [comment]
Layout attributes for tinting and icons are not used and will not be used for dialogs.
