### ISSUE TITLE
why dialog list can't see textview content?

### ISSUE THREAD

**Issue by com314159** [afollestad/material-dialogs#163]
it looks like this
![image](https://cloud.githubusercontent.com/assets/5378240/5608956/8fae95c0-94cd-11e4-8384-2f3267468ba5.png)

I use android studio and eclipse both to build this material dialog demo, I just can't see the list dialog content? I also have write a demo to test it , it also can't show the textview. 

for the single choice or multi choice , it can only show a icon.

like this:
![image](https://cloud.githubusercontent.com/assets/5378240/5608965/ff5f50b2-94cd-11e4-94c5-6847c2d344a7.png)

**Comment by com314159** [comment]
Your Official APK can show dialog list textview content in my nexus 4

**Comment by afollestad** [comment]
Are you using version 0.5.7 of the library?

**Comment by afollestad** [comment]
There was a fix for that earlier today

**Comment by com314159** [comment]
ok, thank you @afollestad , I pull the latest code, and the bug have fixed.
