### ISSUE TITLE
Add set typeface and color functions back in 2.0.0

### ISSUE THREAD

**Issue by phsavisiba** [afollestad/material-dialogs#1638]
For 2.0 it says "No dynamic color support, your dialogs will match your app theme. I will be making sure Aesthetic works correctly with this library if you really need dynamic theming.".

This is not good enough since certain apps will not have the theme and typefaces at compile time. I also do not want to use some additional third party library just to simply change colors. 

Please add back options for setting colors and typeface dynamically like it worked before 2.0.

**Comment by afollestad** [comment]
Actually, all apps already use it. It's called Activity Themes and styles.

**Comment by afollestad** [comment]
And it you activity theme for whatever strange reason does not match what your dialog should use, pass a `ContedtThemeWrapper` into the constructor.

**Comment by afollestad** [comment]
Oh, and typefaces can already been configured for this library from your activity theme as well. It's something already implemented. It will not be dynamically changeable from methods though.

**Comment by phsavisiba** [comment]
My template app does not use Activity Themes and styles because it can not know what colors and fonts will be used. This is to support changing colors dynamically without releasing a new version of the app. Will ContentThemeWrapper work for my use case or must i use reflection to set the fields i need? It is a really great library i want to continue using it like before but with all new stuff.
