### ISSUE TITLE
is it possible to turn holo.dialog themed activity into Material design style?

### ISSUE THREAD

**Issue by qiansen1386** [afollestad/material-dialogs#164]
I got a activity with android:style/Theme.Holo.Dialog. I can't simply modify the activity into your Builder format. So, I wonder is it possible to provide a theme like this https://github.com/fengdai/AlertDialogPro

**Comment by afollestad** [comment]
Sorry, no. That's not what this library is designed to do.

**Comment by qiansen1386** [comment]
Got it, thanks for your fast reply and your excellent work anyway.
