### ISSUE TITLE
Support library problems

### ISSUE THREAD

**Issue by ayham95** [afollestad/material-dialogs#1640]
The library seems to work only with Android X, please Make that clearer in the Docs

**Comment by afollestad** [comment]
Uh, actually it's the other way around. It works with AndroidX, not the Support Library.

**Comment by afollestad** [comment]
Oh I misread. Yes, I believe that is stated in a few places. Will double check though.

**Comment by ayham95** [comment]
Thank you @afollestad The Dialogs rocks |m| just make sure to mention the issue in the docs. Because i had a bad time figuring it out.
