### ISSUE TITLE
Views access

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1641]
After using the dialog in a lot of places now I would really like some sort of access to internal views.

E.g. `textView` (I know you already refused this) or the `titleLayout.iconView`

I've a few use cases and I think it makes sense to expose sub views.

I have some use cases for this:

* updating the displayed data because some event happened in the background
* loading an image in the background, most image loading libraries need the `ImageView` and icon can be initialised with a loading icon but then I need some view to load my image into like `Glide.load(model).into(imageView)`

What does really speak against some main methods like:

    MaterialDialog.textView()
    MaterialDialog.titleView()
    MaterialDialog.iconView()

This makes the library a lot more flexible, colors/text sizes and other theming options can be done if desired easily, updating data is not supported currently in some places (replacing texts for example or updating the icon) and probably more...

If you really refure this, maybe at least you could set an id to every view, so that we can at least access sub views via `findViewById`? Maybe this could be put into a module with an extension class that looks like following (would be small, optional and if all views get ids it would work without reflection):

	fun MaterialDialog.textView(): TextView? = javaClass.getDeclaredField("textViewMessage").let {
		it.isAccessible = true
		return it.get(this) as TextView?
	}

	fun MaterialDialog.iconView(): ImageView? = findViewById(R.id.md_icon_title)

Any thoughts or ideas? Any solution you would feel confident with?

**Comment by afollestad** [comment]
Regarding updating the displayed content, you can just call `content(...)` again on the dialog. Same goes for `title(...)` or `icon(...)`. They aren't Builder methods, they're direct setters.

**Comment by afollestad** [comment]
E.g.:

```kotlin
  fun icon(
    @DrawableRes res: Int? = null,
    drawable: Drawable? = null
  ): MaterialDialog {
    assertOneSet("icon", drawable, res)
    populateIcon(
        view.titleLayout.iconView,
        iconRes = res,
        icon = drawable
    )
    return this
  }

internal fun MaterialDialog.populateIcon(
  imageView: ImageView,
  @DrawableRes iconRes: Int?,
  icon: Drawable?
) {
  val drawable = getDrawable(windowContext, res = iconRes, fallback = icon)
  if (drawable != null) {
    (imageView.parent as View).visibility = View.VISIBLE
    imageView.visibility = View.VISIBLE
    imageView.setImageDrawable(drawable)
  } else {
    imageView.visibility = View.GONE
  }
}
```

**Comment by afollestad** [comment]
The main reason for not exposing the text views, especially, is to enforce Material Design. Text colors, text sizes, etc. should be consistent cause this library is designed to be "Material", after all.

**Comment by afollestad** [comment]
You can use the `icon(...)` method with a Glide listener to solve for one of the cases mentioned above.

**Comment by MFlisar** [comment]
Not totally true, this is what I tried first (after rewritting my dialog fragments module which is written on top of your library) and then I found this:

https://github.com/afollestad/material-dialogs/blob/e743606867c27ec7033b38048f9d7282341e2469/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.kt#L152-L154

Message can't be updated with a custom layout e.g.... Such special behaviour makes it hard and you may change things in the future and need more special order handlings or other checks to support library features. Direct view access is still save and reliable imho

**Comment by afollestad** [comment]
These are underlying reasons for that logic, there. Working around that with direct view access will cause problems with the layout.
