### ISSUE TITLE
How to change the button's color?

### ISSUE THREAD

**Issue by privatez** [afollestad/material-dialogs#1646]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta4`
 - Affected device: OnePlus 3T

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
   MaterialDialog(this)
                .title(text = "title")
                .message(text = "Message")
                .positiveButton(text = "确定")
                .negativeButton(text = "取消")
                .show()
```

```xml
<LinearLayout ...></LinearLayout>
```
 
---
 
###### Reproduction Steps

1.

---

###### Expected Result
In pre-2.0.0 version,I find the way to set "md_negative_color" to change negative's color.
In 2.0.0 version,I can't use this.
I know the way to set "android:colorAccent",But i think this way is not the best.
So, There has any other way to change negative's color?
---

**Comment by afollestad** [comment]
See https://github.com/afollestad/material-dialogs/blob/master/README.md#changes-in-version-2

**Comment by IsSwm** [comment]
Unable to customize the button color, which is very distressing.
