### ISSUE TITLE
Manifest merge issue with Support Library & AndroidX

### ISSUE THREAD

**Issue by xfxstudios** [afollestad/material-dialogs#1647]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [ ] I have given my issue a non-generic title.
- [ ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `0.x.x`
 - Affected device: Google Pixel 2 XL with Android 9.0

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:11:5-37:19 to override.
```

**Comment by afollestad** [comment]
Your app needs to use AndroidX instead of the old Support Library.

**Comment by xfxstudios** [comment]
I understand, thank you very much I had no idea about AndroidX, I am already doing the migration, because apparently it is the future of the distribution of packages.

**Comment by wajatimur** [comment]
Please refer here https://developer.android.com/jetpack/androidx/
