### ISSUE TITLE
Gravity still not working

### ISSUE THREAD

**Issue by Tolriq** [afollestad/material-dialogs#165]
Well removing all important data in issues should be avoided ;)

So the message with 0.5.7 is now that Gravity should be 0 or 1 or 2.

Still ultra easy to test and reproduce : 

Take the sample and change 

```
compile project(':library')
```

with 

```
compile 'com.afollestad:material-dialogs:0.5.7'
```

As suggested by @hzsweers before closing, maybe test or wait for feedback ;)

**Comment by afollestad** [comment]
You must not have payed attention to what he did to fix this very well :P you need to use the MaterialDialog class constants for gravity rather than the Gravity constants. They're are equal to 1, 2, and 3 and are converted to gravity constants at runtime. No testing needed.

**Comment by afollestad** [comment]
It's 3am here so I'll respond to anything else tomorrow.

**Comment by Tolriq** [comment]
Well well well ...

Why do not you just test what I write ... Now it's the 8th time ...
Git pull your code, change one line in the build.gradle and have the error ...

I do know perfectly that it's now new values, and I do now that the enum is now 0,1,2 ...

And I do also now that it does not work as intended and the problem is still here with different values ....

So please stop acting like that ....

**Comment by Tolriq** [comment]
@hzsweers seems the problem is that you do not use : 

```
@Retention(RetentionPolicy.SOURCE)
```

So maybe worth trying with the Retention annotation and get back to direct Gravity support

**Comment by hzsweers** [comment]
AARs only consist of class files, so I'm not sure how Retention.SOURCE
makes a difference since you don't get the source. I'll look at it

**Comment by Tolriq** [comment]
Well not expert on that :(

But https://developer.android.com/reference/android/support/annotation/IntDef.html talk about Class.

While http://tools.android.com/tech-docs/support-annotations talk about RetentionPolicy.SOURCE

Reading your comment I support first one is the correct one ;)

**Comment by hzsweers** [comment]
Retention.CLASS is the default, aka what it currently is set to

**Comment by hzsweers** [comment]
Unfortunately he's right. I don't think we can get away with using IntDef as long as the AAR package type doesn't allow including source. I'll switch it to enum and we'll have to leave it at that. This is made more annoying by the fact that this isn't easily testable without actually publishing a release of the library.

**Comment by Tolriq** [comment]
Can't just this part be migrated to simple debug assert or similar process ?

All the conversions are just more code to maintain, and complexity for devs for no real gain.

Then when aar is better, do things correctly ?

(And BTW I'm often right as in all the other issues ;) )

**Comment by hzsweers** [comment]
> Can't just this part be migrated to simple debug assert or similar process ?

I don't know what this means.

> All the conversions are just more code to maintain, and complexity for devs for no real gain.

There is a gain: it now works without linting errors from the IDE. Using enums is not a bad thing, it's just less nice than using IntDef (for multiple reasons).

> (And BTW I'm often right as in all the other issues ;) )

![](http://i.imgur.com/40Idny0.png)

I've pull requested a fix, this should resolve everything for now. Let's be done with this.

**Comment by Tolriq** [comment]
The point of intdef is to validate the input.

Assert are used to validate inputs too (http://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html)

I'm talking about the gain of enums versus directly using Gravity values that avoid all the conversion code from enums to final values. (Meaning code for nothing and associated maintenance).

And thanks for your beautiful image, but everybody can make a mistake, when someone make 8 times the same mistake then he have a problem.
So you can take your image and play with it in any part of your anatomy you like ;)

**Comment by afollestad** [comment]
@Tolriq he's right.

**Comment by Tolriq** [comment]
@afollestad  the fact you were wrong again and yet not only refuse to see that, but come and add such a comment here only proves that I'm again right ....

Young age does not excuse every thing when you goes public :)

**Comment by afollestad** [comment]
@Tolriq I wasn't wrong with what I said. It was 3am, I was laying in bed, I had fixed it earlier and someone told me it was indeed fixed.

I'm almost 20. Old age doesn't excuse being an ass hole in public. I'm close to blocking you from the repo.

**Comment by Tolriq** [comment]
Please do as in fact I can't even report issues without them being closed without being read ...

Each and every time it takes 3 to 4 messages so read.

You closed the issue explaining me that I did not read, while it was the opposite. Then I explain that you can easily test with how to , and you answer I do not need to test all works ...

While it was obviously not the case ...

So perhaps stop close issue without reading, stop saying no bug when there's one, and people will stop being assholes with you ....

**Comment by afollestad** [comment]
@Tolriq you're the only one. Blocked.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1
