### ISSUE TITLE
No support for Any object Lists

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/material-dialogs#1650]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta4`
 - Affected device: All

##### Description:

In previous versions of MaterialDialogs, one could set a list of any object to the dialogs and you would use the `toString()` method to set the text, which was very useful ...

Do you think you could bring that back for v `2.0.0`?

Thanks in advance!

**Comment by afollestad** [comment]
Hmmm, probably not - but you could do something like:

```kotlin
    .listItems(items = yourObjects.map { "$it" })
```

**Comment by jahirfiquitiva** [comment]
I think that'll suffice. Thanks :)
