### ISSUE TITLE
Layout bug with an icon dialog that has a single-line title

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/material-dialogs#1654]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:

 - Material Dialogs version: `2.0.0-beta4`
 
---
 
###### Description:

When using showing an icon in the title, the spacing between the icon and the content is too small for a single line title.

It looked better in the previous versions ...

Can you please increase it a bit or force the icon to be a bit smaller?

Thanks in advance.

![screenshot_20181108-212258](https://user-images.githubusercontent.com/10360816/48239775-39de2d80-e39e-11e8-8416-94121cc327ca.png)

![img_20181108_212505_953_1](https://user-images.githubusercontent.com/10360816/48239742-161ae780-e39e-11e8-8951-52a606fc1e66.jpg)

**Comment by jahirfiquitiva** [comment]
Hey @afollestad Thank you so much for all the fixes!

Anyways, this particular issue isn't really fixed. The OP has a screenshot using Material Dialogs `0.9.6.0` in my app Pals, this one is using `2.0.0-beta5` see how different they look.

I really like the one from `0.9.6.0` better

![screenshot_20181109-214756](https://user-images.githubusercontent.com/10360816/48296858-184a7800-e46a-11e8-8b47-57f63ffe01e4.png)

**Comment by afollestad** [comment]
The one immediately above is correct and even on both sides

**Comment by jahirfiquitiva** [comment]
Here's a side-by-side comparison
Left uses MaterialDialogs `0.9.6.0` and right uses `2.0.0-beta5`

See how the icon+title looks evenly spaced on left+right and top+bottom.

That's what I mean 🙏🏼

![img_20181109_220631](https://user-images.githubusercontent.com/10360816/48296966-3f09ae00-e46c-11e8-9d9b-5723c3da203f.jpg)

**Comment by afollestad** [comment]
@jahirfiquitiva looks like this is actually a layout bug when the title is only one line (which is why I didn't notice it in the sample project). 

If you turn on debug mode in the sample, and make the title one line, you see this:

<img src="https://dl2.pushbulletusercontent.com/Ep1UhfhrbQr469LuGMpKzGCrEZ0EnIUT/Screenshot_20181117-181812.png" width="300" />

**Comment by afollestad** [comment]
Should be fixed

<img src="https://dl2.pushbulletusercontent.com/KZK37Y2UygiABCDgyVPpKbiLWJ8gaRVW/Screenshot_20181117-184011.png" width="300" />

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-beta06

**Comment by jahirfiquitiva** [comment]
Thanks @afollestad 😀
