### ISSUE TITLE
min sdk 15

### ISSUE THREAD

**Issue by ahmed56734** [afollestad/material-dialogs#1655]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ x] I understand that versions below 2.0.0 will no longer be supported for updates.
- [ x] I have given my issue a non-generic title.
- [ x] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

what features I should avoid the to use this library safely with my app module with min sdk 15

**Comment by afollestad** [comment]
The min SDK is 16.
