### ISSUE TITLE
Color dialog - landscape mode

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1657]
We've shortly talked about that already: color dialogs in landscape mode do not work currently if we enable the argb selector...

I need this the next week so instead of readding my own old solution again I could use the time to implement something we both are content with.

**Idea 1:**

* don't use a `ViewPager` in landscape mode but add a "...", "ARGB" or maybe some special icon (e.g. https://fontawesome.com/icons/sliders-h?style=solid) circle (like you currently add a "<-" circle to move up one level) at the end of the grid to switch to the argb color selector instead
* adjust landscape argb layout to show the color at the left and the 3/4 sliders at the right

**Comment by MFlisar** [comment]
What do you think of this layout?

* no dot indicator in landscape to save space
* `PreviewFrameView` on the left to have more vertical space for the `Seekbars`
* a button at the end of the grid to make the second page more discoverable for the user
* `ViewPager` still stays active to swipe between pages

Short 20s demo:

![demo](https://user-images.githubusercontent.com/2437726/48717503-d5cb2d00-ec19-11e8-93dc-7b0feaee0a12.gif)

**Comment by afollestad** [comment]
That looks good - there could probably be slightly less margin above the top slider (A, or R if A is gone) so that the sliders together look more centered next to the preview view

**Comment by MFlisar** [comment]
This is the top margin of the `ColorChooser.Label` style... Will remove it in the landscape layout...

Made a pull request with this features

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-beta06
