### ISSUE TITLE
AAPT2 aapt2-3.2.1-4818971-windows Daemon #0 Please someone help me!!!!

### ISSUE THREAD

**Issue by alejandro322** [afollestad/material-dialogs#1658]
Android resource linking failed
Output:  C:\Users\Usuario\trabajos\MyApplication\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:11: error: unexpected element <uses-permision> found in <manifest>.

Command: C:\Users\Usuario\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\0ed2b48df4303d5a66edaf4fa0303f71\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\Usuario\AppData\Local\Android\Sdk\platforms\android-28\android.jar\
        --manifest\
        C:\Users\Usuario\trabajos\MyApplication\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\Usuario\trabajos\MyApplication\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\Usuario\trabajos\MyApplication\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\Usuario\trabajos\MyApplication\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        com.alejandroosorioc.www.myapplication\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\Usuario\trabajos\MyApplication\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by afollestad** [comment]
Sorry, don't think I'll be any help here.
