### ISSUE TITLE
Question: blocking progress dialogs

### ISSUE THREAD

**Issue by oradkovsky** [afollestad/material-dialogs#1659]
Hello,

Thank you, this is great library! I have a question re this update:

> There is no longer a progress dialog included in library, since they are discouraged by Google, and discouraged by me. You should prefer a non-blocking inline progress indicator.

Let's take scenario of user signup as an example. May be I'm missing something but it seems there is no easy way to avoid blocking progress for such scenario, and not a single 100% fail safe one I can imagine. 

I understand one can use what sdk offers, but it's so convenient to cover all the dialog needs with single library. That said, would greatly appreciate your vision of non-blocking workaround for the example above.

**Comment by afollestad** [comment]
As Google suggests and other apps use, non blocking progress would be something like a spinner. A contextual view that's in the page, vs. a blocking modal that covers the whole app.
