### ISSUE TITLE
Improve file/folder chooser dialog UI

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1664]
I'm using the latest version of material dialogs 2 (rc1) and I've noticed something.

To me, the file/folder chooser seems weird, It doesn't look uniform with the beautiful and smooth design of every other component of the library.

I'll explain myself better.

<img src="https://i.imgur.com/QiTmrq0.jpg" width="200"/>

The back icon, the tree dots, the text "new folder", the folder empty text that isn't exactly between the new folder view and the action buttons, everything looks a little messy to me in this empty folder view (I'm sorry if it's just subjective).
But more than messy, I guess there is a better what to build the same interface.

My issue is that. I've thought about a possible solution, that doesn't seem right either, but that may look better, if you want you can share your opinion about it.
My idea is:
- "New folder" button moved to an action button
- "This folder is empty!" replaced with an icon in the middle of the dialog showing an empty directory, and optionally a smaller textview below it
- Changing the icon to "go up" to something less extended (I don't mean reducing image size) and cleaner, also if the official guidelines are providing an icon for this behavior, I thought that [arrow_back_ios](https://material.io/tools/icons/?icon=arrow_back_ios&style=baseline), [icon_back](https://material.io/tools/icons/?icon=arrow_back&style=baseline), [chevron_left](https://material.io/tools/icons/?icon=chevron_left&style=baseline) or the "../" text may be our best choices.
- Alternatively, we can put the "New folder" and "Go up" button in the same view, divided in the half so it takes less room and it is more compact and clean, so that you can also remove the ... text from the go up view and the next "New folder".

**Comment by afollestad** [comment]
"New Folder" was in an action button in pre-2.0 versions but the neutral button is deprecated now so that isn't the best option IMO.

**Comment by afollestad** [comment]
Putting them both in the top row is appealing

**Comment by afollestad** [comment]
Going to leave as-is for now, further contributions are welcome
