### ISSUE TITLE
[Color Chooser] whippy UI while rendering color

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1668]
I don't know why, but the custom ARGB chooser dialog isn't smooth while moving the slider, the textview rendering is laggy and you feel some delay, Is like watching a low-fps rendering.

I'm running the latest version of material dialogs on a OnePlus 5 with the lastest Android version installed (8.1.0)

**Comment by afollestad** [comment]
Well, I'm not sure how much can be done to help that since the seek bars are inside of a ViewPager. Some trickery would probably have to be done with touch events.
