### ISSUE TITLE
Android Java Support

### ISSUE THREAD

**Issue by eakteam** [afollestad/material-dialogs#1669]
Hi there, can we use this lib from java and is there any tutorial for that ? Because not all the apps are refactored to Kotlin yet

**Comment by afollestad** [comment]
No, 2.0 is intentional made for Kotlin and there are things like extension functions that are now fundamental to it.

**Comment by eakteam** [comment]
if so, delete this line from Readme : 

The whole library was completely re-written in Kotlin. All the layouts and views were remade as well. This library is now designed specifically to work with Kotlin - it technically will work with Java, but not pleasantly.

**Comment by afollestad** [comment]
That line still holds true. The library works from Java because Kotlin compiles to Java bytecode. But the features in the library which rely on extension functions won't be visible from Java.
