### ISSUE TITLE
Inline callback function to DialogCallback

### ISSUE THREAD

**Issue by dri94** [afollestad/material-dialogs#1672]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I understand that versions below 2.0.0 will no longer be supported for updates.
- [x ] I have given my issue a non-generic title.
- [x ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---
Using kotlin with 1.X version allowed us to have this nice inline callback.

```kotlin
 MaterialDialog.SingleButtonCallback { dialog, which ->
    //...
})
```
However in 2.0.0 it now unnecessarily becomes 
```kotlin
object : DialogCallback {
    override fun invoke(p1: MaterialDialog) {
        //...
    }                            
}
```
I understand this is because its defined as an interface, but using a high order function will remove some of the boilerplate i believe, unless there is some reason you need/prefer it like this?

**Comment by afollestad** [comment]
Uh, that's definitely not the case. All callbacks are lambdas in 2.0.

**Comment by afollestad** [comment]
That invoke signature above is the signature of a higher order function

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/README.md#single-choice

**Comment by dri94** [comment]
Ahhhhh. thanks for the info and quick response! i jumped into the source code and understand better now
