### ISSUE TITLE
useHorizontalPadding for custom view

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1677]
**Library Version:**

2.0.0-rc3
 
**Affected Device(s):**
 
Android 5.0
 
**Describe the Feature:**

Well, I miss the old style of this library where it can set horizontal padding for custom view automatically.  Look at the brown line. It used to have the following horizontal padding for left and right side of the content view:

![genymotion for personal use - phone - 5 0 0 - api 21 - 768x1280 768x1280 320dpi - 192 168 191 101 23-dec-18 12_48_19 am](https://user-images.githubusercontent.com/12292380/50377309-a8750300-064d-11e9-9454-e4e71a00ad7d.png)

So, would you like to add this attribute to the custom view dialog?
`customView(useHorizontalPadding: Boolean = true)`

**Comment by afollestad** [comment]
Just set paddingLeft and paddingRight to 16dp or 24dp in your layout.

**Comment by PaulWoitaschek** [comment]
What is the reasoning behind removing this?
