### ISSUE TITLE
Allowing empty input to be submitted in an Input Dialog

### ISSUE THREAD

**Issue by iballan** [afollestad/material-dialogs#1679]
I use the latest version of Input Dialog :

`implementation 'com.afollestad.material-dialogs:core:2.0.0-rc5'`

I could not find a way to allow Positive button to stay activated when the input field is empty

could be like an additional parameter to `Input(... allowEmpty : Boolean )` ?

**Comment by afollestad** [comment]
`waitForPositiveButton = false`

**Comment by vizvamitra** [comment]
this is my workaround:

```kotlin
import com.afollestad.materialdialogs.WhichButton
import com.afollestad.materialdialogs.actions.setActionButtonEnabled

MaterialDialog(this).show {
  // ...
  input(waitForPositiveButton = false, prefill = "Test") { dialog, text ->
    setActionButtonEnabled(WhichButton.POSITIVE, true)
    // other stuff
  }
}
```

**Comment by vizvamitra** [comment]
👏
