### ISSUE TITLE
Why depend on appcompat-v7:21.0.3

### ISSUE THREAD

**Issue by airk000** [afollestad/material-dialogs#168]
can it be appcompat-v7:21.+ in build.gradle?

**Comment by afollestad** [comment]
Android Studio gives you warnings if you do that. There's lots of reasons not to do that.

**Comment by airk000** [comment]
But when I use an old appcompat-v7, such as 21.0.2, I need to update my sdk for using this. BTW, google's opensource application use + too. link: https://github.com/google/iosched/blob/master/android/build.gradle

**Comment by afollestad** [comment]
Sorry, I had a few complaints that I was using a +. It's insecure to use that.
