### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by ghost1372** [afollestad/material-dialogs#1680]
2.0.0rc5
 
hi i cant add this libary to my project i added this:
```
implementation 'com.afollestad.material-dialogs:core:2.0.0-rc5'
    implementation 'com.afollestad.material-dialogs:files:2.0.0-rc5'
```
then i get this error
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-67:19 to override.

**Comment by afollestad** [comment]
Your app needs to use AndroidX instead of the old Support library.

**Comment by roman-ku** [comment]
Would be helpful if that requirement was explicitly listed in the README

**Comment by afollestad** [comment]
Eh, this merger issue isn't a problem with this library - more of a special case that Google has created. All apps should be upgraded to AndroidX and libs can't be held back by migration.

**Comment by abiemann** [comment]
thanks - I was unaware that Google is dropping support for the support libs. LOL.
AndroidX going forwards

**Comment by mddanishansari** [comment]
@afollestad  Is there any possibility I can continue using library without AndroidX for now. Any workaround?
