### ISSUE TITLE
use version 0.9 in fragment

### ISSUE THREAD

**Issue by ghost1372** [afollestad/material-dialogs#1682]
hi i want use filechooser in my fragment  i write this code:
```
new FileChooserDialog.Builder(this)
    .initialPath("/sdcard/Download")  // changes initial path, defaults to external storage directory
    .mimeType("image/*") // Optional MIME type filter
    .extensionsFilter(".png", ".jpg") // Optional extension filter, will override mimeType()
    .tag("optional-identifier")
    .goUpLabel("Up") // custom go up label, default label is "..."
    .show(this); 
```
but i get error in `.show(this);` line

**Comment by afollestad** [comment]
Fragment isn't a Context. Pass the Fragment's Activity.

**Comment by ghost1372** [comment]
@afollestad  im new in android can you help me? can you give me example code?

**Comment by afollestad** [comment]
Sorry, I'm not here to teach.

**Comment by afollestad** [comment]
But basically, use `getActivity()` instead of `this`. 

FYI, 0.9.x versions are no longer supported so there will not be anymore updates to it.

**Comment by ghost1372** [comment]
@afollestad  unfortantly my project is java and i cant use updated version, i used your help but i get error
`FileChooserDialog needs to be shown from an Activity/Fragment implementing FileCallback.`

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/03fed5b82196063a983a986128cc64ec98a321f7/README.md#file-selector-dialogs
