### ISSUE TITLE
Saving file/folder chooser states in a DialogFragment

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1684]
**What module does this apply to?**

Files

**Description what you'd like to happen:**

Since file/folder chooser dialog is not wrapped in `DialogFragment`, so I need to implement by myself with this code:

        override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
            return MaterialDialog(context!!)
                    .folderChooser(File(arguments!!.getString("folder")), allowFolderCreation = true){ _, file ->
                        // some code
                    }
        }

But when I rotate my device, it returns to initial path. I want to save the current path so that when users rotate their device, they don't need to browse the same folder again.

**Describe alternatives you've considered:**

I did the following alternative by setting `waitForPositiveButton = false`:

        override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
            return MaterialDialog(context!!)
                    .folderChooser(File(arguments!!.getString("folder")), allowFolderCreation = true, waitForPositiveButton = false){ _, file ->
                        arguments!!.putString("folder", file.absolutePath)
                    }
        }

But now, I cannot detect if user pressed positive button which tells me that they have selected a folder.

Then, I added my own positive button callback, but there is a new problem. `FileChooserAdapter` is an internal class, so I cannot access field `selectedFile`:

        override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
            return MaterialDialog(context!!)
                    .folderChooser(File(arguments!!.getString("folder")), allowFolderCreation = true, waitForPositiveButton = false){ _, file ->
                        arguments!!.putString("folder", file.absolutePath)
                    }
                    .positiveButton {
                        val adapter = it.getListAdapter() as FileChooserAdapter // error, this class is marked as internal
                        val selectedFile = adapter.selectedFile
                        if (selectedFile != null) {
                            // some code...
                        }
                    }
        }

So, would you like to add this feature?

**Comment by afollestad** [comment]
`Dialog` alone is not meant to save states, so you need to do so from a `DialogFragment` as you are.

**Comment by anggrayudi** [comment]
That is why I put the current folder into DialogFragment's arguments. The problem is, this library doesn't provide a method to get the current directory. How can I save the state if I cannot get the current path? I am sure that someone will ask this question again in the future.

**Comment by anggrayudi** [comment]
It is like a dilemma. When I want to save current path each time users selected a folder, I can't detect whether they press positive or negative button. Otherwise, when I want to detect when users press positive button and get the selected folder, I cannot save the state on orientation change. At least, we have a method like this `MaterialDialog.getCurrentFolder()`.

BTW, thank you for reopening this issue.
