### ISSUE TITLE
Minimal touch area height of 48dp

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1688]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?** Core

**Description what you'd like to happen:**

Offer minimal touch area of 48dp height in order to comply to this: https://support.google.com/accessibility/android/answer/7101858.
Currently I do get many warnings in the automated UI checks about the touch size of material dialog elements to be to small:

![image](https://user-images.githubusercontent.com/1724223/50562090-497c5180-0d11-11e9-9efa-486fafcac0e6.png)

This example shows the checkbox, but also many other touch elements are giving the warning.

**Describe alternatives you've considered:**

None.

**Comment by afollestad** [comment]
Actually, dialog buttons are supposed to be 36dp according to the Material Design specs.

**Comment by afollestad** [comment]
<img width="760" alt="components-dialogs-updates1" src="https://user-images.githubusercontent.com/1820165/50563339-e1a61680-0cd0-11e9-98a4-2b761bd51e19.png">

**Comment by peterhav** [comment]
Yes, the button height should be 36dp, but the touch area should be 48dp as indicated here: 
![image](https://user-images.githubusercontent.com/1724223/50563447-2d7ead00-0d1d-11e9-9667-f74d9722af30.png)
Source: https://material.io/design/usability/accessibility.html#layout-typography
