### ISSUE TITLE
java.lang.ClassCastException: AppCompatSeekBar cannot be cast to ObservableSeekBar

### ISSUE THREAD

**Issue by dkrivoruchko** [afollestad/material-dialogs#1691]
Color Chooser dialog.
**Library Version:** com.afollestad.material-dialogs:color:2.0.0-rc7
**Steps to reproduce:**
1. Open color dialog
2. Rotate screen
3. Open the same color dialog

`java.lang.ClassCastException: androidx.appcompat.widget.AppCompatSeekBar cannot be cast to com.afollestad.materialdialogs.color.view.ObservableSeekBar
        at com.afollestad.materialdialogs.color.CustomPageViewSet.<init>(CustomPageViewSet.kt:60)
        at com.afollestad.materialdialogs.color.DialogColorChooserExtKt.setupCustomPage(DialogColorChooserExt.kt:207)
        at com.afollestad.materialdialogs.color.DialogColorChooserExtKt.colorChooser(DialogColorChooserExt.kt:134)
        at com.afollestad.materialdialogs.color.DialogColorChooserExtKt.colorChooser$default(DialogColorChooserExt.kt:82)`

**Invoke code source:** [ScreenStream]{https://github.com/dkrivoruchko/ScreenStream/blob/e880c0d6f7854984393d9edc9d0c1b2bc0da3d52/app/src/main/kotlin/info/dvkr/screenstream/ui/fragments/SettingsFragment.kt#L154}

**Comment by afollestad** [comment]
That doesn't really make any sense, `ObservableSeekBar` _is_ a `AppCompatSeekBar`.

**Comment by afollestad** [comment]
I'm also unable to reproduce any crashes here.

**Comment by dkrivoruchko** [comment]
Crash happens only when
`allowCustomArgb = true`

**Comment by afollestad** [comment]
I've tried all the variations of color dialogs in the sample project, including one that has the full ARGB to no avail

**Comment by dkrivoruchko** [comment]
Did you:
1. Open color dialog
2. Rotate screen
3. Open the same color dialog
?
Simple open color dialog is ok

**Comment by afollestad** [comment]
Oh 🤦‍♂️it's the landscape layout.

Thanks 😄
