### ISSUE TITLE
Color Chooser dialogs: DialogLayout cuts off DialogContentLayout when title is long

### ISSUE THREAD

**Issue by dkrivoruchko** [afollestad/material-dialogs#1692]
Color Chooser dialog.
**Library Version:** com.afollestad.material-dialogs:color:2.0.0-rc7

On phones with small screens and **long dialog title**  last colors row cropped.
![device-2019-01-04-204900](https://user-images.githubusercontent.com/10741551/50705300-08fb3b80-1063-11e9-9107-1999ca00643d.png)

**Invoke code source:** [ScreenStream](https://github.com/dkrivoruchko/ScreenStream/blob/e880c0d6f7854984393d9edc9d0c1b2bc0da3d52/app/src/main/kotlin/info/dvkr/screenstream/ui/fragments/SettingsFragment.kt#L154)

**Comment by afollestad** [comment]
But the grid is scrollable, yes? Not sure how much can be done without changing the layout for smaller screens.

**Comment by dkrivoruchko** [comment]
Screen is scrabble only when
`allowCustomArgb = false`

When its set to true - no vertical scrolling available, only horizontal for tabs

**Comment by afollestad** [comment]
@dkrivoruchko hmm, the grid is a `RecyclerView` so it's definitely scrollable in all cases, even with ARGB=true.

![screenshot_20190104-120237](https://user-images.githubusercontent.com/1820165/50708317-c1e85880-1018-11e9-8e90-b3e8718aa169.png)

**Comment by dkrivoruchko** [comment]
Make a dialog title long so it will take two text lines.
Then no scrolling available but colors are crop

**Comment by afollestad** [comment]
Huh - this is puzzling. The RecyclerView is laid out correctly but it's not scrollable despite.

**Comment by dkrivoruchko** [comment]
This issue present only when `allowCustomArgb = true`
When it's true -> layout is `md_color_chooser_base_pager`.
Look at [WrapContentViewPager#onMeasure](https://github.com/afollestad/material-dialogs/blob/1b43a5c7a87ffca80e3d05cc72f2731f3302b403/color/src/main/java/com/afollestad/materialdialogs/color/view/WrapContentViewPager.kt#L29) - it's height set to MAXIMUM of all it's children.
One of it's children is a DialogRecyclerView and it measured height with  `View.MeasureSpec.UNSPECIFIED` so it's height is WRAP_CONTENT so no scroll in it.
And this DialogRecyclerView height then set to WrapContentViewPager height .

WrapContentViewPager height has to be set to MAX.of(MaxHeightForAllChildren, MaximumAlowedByParent). After that all children have to be reMesured with new known WrapContentViewPager height

**Comment by dkrivoruchko** [comment]
@afollestad Any update on this issue?

**Comment by afollestad** [comment]
Sorry, I'm on vacation.

**Comment by dkrivoruchko** [comment]
That's OK. Have your time.

**Comment by afollestad** [comment]
So, this is weird, I suddenly cannot reproduce the issue again with the latest master.

**Comment by afollestad** [comment]
However I am applying a preventative fix.

**Comment by dkrivoruchko** [comment]
Well, fix you've add doesn't actually fix issue.
I made PR to fix it properly [#1710](https://github.com/afollestad/material-dialogs/pull/1710)
