### ISSUE TITLE
Change textColor of actionButtons

### ISSUE THREAD

**Issue by cendelinova** [afollestad/material-dialogs#1693]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.0.0-rc7
 
**Affected Device(s):**
 
Huawei FIG-LX1 with Android 8.0
 
**Describe the Bug:**

I'm trying to change the color of actionButtos by calling this code:

```
MaterialDialog(context).show {
			customView(view = customView, scrollable = true)
			customListAdapter(adapter)
			positiveButton(R.string.btn_confirm)
			negativeButton(R.string.btn_cancel) 
 getActionButton(WhichButton.POSITIVE).updateTextColor(context.getColor(R.color.colorPrimary))
		}
```

Every time my applied color is overwritten by colorAccent from DialogActionButton (it's being called 3x)

**Expected Behavior:**
To be able to change textColor of actionButtons.

Thank you

**Comment by afollestad** [comment]
It's expected that you put the color you want in your Activity theme.

Dynamic coloring isn't supported.
