### ISSUE TITLE
TextInputLayout bug with Material Components theme

### ISSUE THREAD

**Issue by viniciusalmada** [afollestad/material-dialogs#1695]
My Input dialog has this bugged background:
style = `Theme.MaterialComponents.Light.NoActionBar`
version androidX = `androidx.appcompat:appcompat:1.0.2`

![image](https://user-images.githubusercontent.com/16392568/50866453-27c63e80-1391-11e9-818c-334883cdd089.png)
![input-material-dialog](https://user-images.githubusercontent.com/16392568/50866468-36acf100-1391-11e9-8f15-f711e9e8fe0e.png)

**Comment by afollestad** [comment]
Unable to reproduce with the MaterialComponents theme:

<img src="https://user-images.githubusercontent.com/1820165/50926774-aca16e80-140a-11e9-85f8-64b8e51dfe01.png" width="300" />
