### ISSUE TITLE
please add in readme

### ISSUE THREAD

**Issue by Zebra67** [afollestad/material-dialogs#1696]
Please add in readme for how to use these in Java. I tried but not work.Please add

**Comment by afollestad** [comment]
Kotlin and Java are interopable.

As https://github.com/afollestad/material-dialogs#changes-in-version-2 states:
> The whole library was completely re-written in Kotlin. All the layouts and views were remade as well. This library is now designed specifically to work with Kotlin - it technically will work with Java, but not pleasantly.

The extension modules will not work in Java because they rely on Kotlin extension functions.

**Comment by AndreaCioccarelli** [comment]
@Zebra67 there is no reason to use Java anymore in Android app development
