### ISSUE TITLE
Weird behavior of action buttons in small screens

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/material-dialogs#1697]
**Library Version:**

2.0.0-rc7
 
**Affected Device(s):**
 
All devices with small screens
 
**Describe the Bug:**

Hi Aidan

I am showing a dialog with a custom view and the buttons are behaving really weird.

Pictures descriptions because the pictures are big 😓 
1. This is the dialog in a normal screen, without the keyboard shown (aka expected behavior).
2. This is the dialog in a small screen before showing the keyboard.
3. This is the dialog in a small screen while showing the keyboard.
4. This is the dialog in a small screen after hiding the keyboard.

------

**This is the dialog in a normal screen, without the keyboard shown (aka expected behavior).**

<img src="https://user-images.githubusercontent.com/10360816/50916321-d35ea580-1408-11e9-9149-1993d02cd858.jpg" width="250" />

------

**This is the dialog in a small screen before showing the keyboard.**

<img src="https://user-images.githubusercontent.com/10360816/50916339-e1acc180-1408-11e9-931f-0956ab569a00.jpg" width="250" />

------

**This is the dialog in a small screen while showing the keyboard.**

<img src="https://user-images.githubusercontent.com/10360816/50916347-ebcec000-1408-11e9-8eb3-971374f7a98d.jpg" width="250" />

------

**This is the dialog in a small screen after hiding the keyboard.**

<img src="https://user-images.githubusercontent.com/10360816/50916370-fe48f980-1408-11e9-878a-78202d4f9858.jpg" width="250" />

**Comment by afollestad** [comment]
A trick I use with pictures on GitHub is straight up HTML 😄 

```
<img src="url" width="250" />
```

After the picture uploads I just take out the URL and put it in an img tag

**Comment by afollestad** [comment]
Oh interesting - the keyboard must be causing a remeasure, making the dialog change it's decision on being "stacked".

**Comment by afollestad** [comment]
@jahirfiquitiva oddly, I'm unable to reproduce.

Are you changing the soft input mode of your dialogs?

**Comment by afollestad** [comment]
Oh wait, your custom view isn't in a ScrollView. That's probably effecting it. Will try that way.

**Comment by afollestad** [comment]
Huh, even when not scrollable, I don't see that problem on a Nexus 5.

**Comment by jahirfiquitiva** [comment]
Thanks for letting me know about the images trick.

My custom view is a full width card, and a recyclerview below

Also, I set this flags in the `AndroidManifest.xml`:
`android:windowSoftInputMode="stateAlwaysHidden|adjustResize"`

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-rc8
