### ISSUE TITLE
Too much button padding when using a custom view

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/material-dialogs#1698]
**Library Version:**

2.0.0-rc7
 
**Affected Device(s):**
 
Any
 
**Describe the Bug:**

After a recent update (I'm guessing [this change](https://github.com/afollestad/material-dialogs/commit/1ba6ecfa48ef86fa61c7bb0fd2e879c9ba08e62f)) the buttons in a dialog with a custom view have too much padding and they don't look that good :/

**Dialog covered with an 8dp grid**

![photo5021569621412653038](https://user-images.githubusercontent.com/10360816/50916660-b1b1ee00-1409-11e9-918a-cefd7d1472ee.jpg)

**Comment by afollestad** [comment]
Don't think it's the padding. Looks like it's more the margin in between:

<img src="https://user-images.githubusercontent.com/1820165/50926863-eecab000-140a-11e9-96d3-090da6ac3b6d.png" width="300" />

![mio-design_assets_17pbb_9riwgzuvwsreawez6tfvwlcgz5p_specs-dialog-mobile-confirmation](https://user-images.githubusercontent.com/1820165/50926883-0144e980-140b-11e9-8cd2-a045c07682d1.png)

**Comment by afollestad** [comment]
<img src="https://user-images.githubusercontent.com/1820165/50927144-c2636380-140b-11e9-828e-54a52a3bca8b.png" width="250" /><img src="https://user-images.githubusercontent.com/1820165/50927162-cdb68f00-140b-11e9-99f9-5e57adf42484.png" width="250" />

^ if I remove the layout margin and only rely on the button inset drawable
