### ISSUE TITLE
can not download 

### ISSUE THREAD

**Issue by INTKILOW** [afollestad/material-dialogs#1700]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
Open File
Show Details

**Comment by afollestad** [comment]
Looks like you're missing a repo in your config or something. This is not an issue with this library.
