### ISSUE TITLE
Dynamically changing the dialog typeface

### ISSUE THREAD

**Issue by excaliburthesword** [afollestad/material-dialogs#1702]
It would be useful to make it possible to change the dialog typeface dynamically, when the app is not using multiple theme. currently the typeface vars are defined as **internal** and can not be used in extension functions. also the MaterialDialog is defined as **final** that makes it impossible to extend

**Comment by afollestad** [comment]
You can do so from your app themes as the readme states. I do not plan to implement support via methods, though.
