### ISSUE TITLE
Button not displayed since 2.0.0-rc6

### ISSUE THREAD

**Issue by ghus-raba** [afollestad/material-dialogs#1704]
**Library Version:**

2.0.0-rc7, worked ok on 2.0.0-rc5
 
**Affected Device(s):**
 
OnePlus 6, Android 9
 
**Describe the Bug:**

A dialog with 3 buttons shows fine on rc5:

![screenshot_20190114-153759__01](https://user-images.githubusercontent.com/2743419/51120551-a699fc00-1815-11e9-872a-606b7c089f61.jpg)

, but only shows one button on rc6 and rc7:

![screenshot_20190114-155509__01](https://user-images.githubusercontent.com/2743419/51120552-a699fc00-1815-11e9-9cbc-16f6417db16b.jpg)

Not all devices seem to be affected as eg. emulator works fine. Also on the failing device, after rotating to landscape, all 3 buttons are displayed.

**To Reproduce:**
```kotlin
override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {

        val title = arguments!!.getString(TITLE)
        val subtitle = arguments!!.getString(SUBTITLE)
        val positiveButton = arguments!!.getString(POSITIVE_BUTTON)
        val negativeButton = arguments!!.getString(NEGATIVE_BUTTON)
        val neutralButton = arguments!!.getString(NEUTRAL_BUTTON)

        val dialog = MaterialDialog(activity!!)
                .title(text = title)
                .message(text = subtitle)

        if (negativeButton != null) {
            dialog.negativeButton(text = negativeButton) {
                dialog.dismiss()
                callbackListener?.onNegativeButton()
            }
        }

        if (positiveButton != null) {
            dialog.positiveButton(text = positiveButton) {
                dialog.dismiss()
                callbackListener?.onPositiveButton()
            }
        }

        if (neutralButton != null) {
            dialog.neutralButton(text = neutralButton) { dialog
                dialog.dismiss()
                callbackListener?.onNeutralButton()
            }
        }

        return dialog
    }
```

**Expected Behavior:**

Keep showing all 3 buttons as with previous versions.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/2.0.0-rc8

**Comment by ghus-raba** [comment]
Ok, I had a look and it is hard to reproduce, since it requires just right width of the buttons. I created a PR https://github.com/afollestad/material-dialogs/pull/1713
