### ISSUE TITLE
Dpad navigation does not work properly

### ISSUE THREAD

**Issue by AndyGOBrien** [afollestad/material-dialogs#1706]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.0.0-rc7
 
**Affected Device(s):**
 
Any Dpad controlled device
 
**Describe the Bug:**

when dialog opens there is no default button that has focus. you can use the dpad to get focus but if you can easily lose focus by clicking away from a button

**To Reproduce:**
1. use a dpad, there is one in the emulator settings. 
2. open a "yes / no" dialog or something similar.
3. click around to find and lose focus on the buttons

**Expected Behavior:**

the negative option should have focus by default, you shouldn't be able to lose focus by clicking up, down, or left on the dpad. right on the dpad should move to the positive option.

**Comment by afollestad** [comment]
I'm pretty sure you'll need to handle initial focus yourself, with `onShow { }`. There's not a reliable way I know of to check if the current device *only* uses a dpad controller, and initial focus is not wanted on a phone or tablet.

**Comment by afollestad** [comment]
And losing focus on the buttons is also behavior that can't be avoided, and probably shouldn't be hacked around.

**Comment by dri94** [comment]
Would we always want to focus a button if the devices does have a dpad? or only if it has a dpad?

**Comment by AndyGOBrien** [comment]
To be honest, I'm not sure if this is worth your efforts. I can hack in the
functionality I need on a case by case basis, it's ugly but it works. I'll
send some details to you tomorrow though in case you're interested. If I
find some time I can probably dig in and send you a PR.

**Comment by dri94** [comment]
MIght be better to close the Issue. Feel free to still send me some info on it too though
