### ISSUE TITLE
EditText Grey background

### ISSUE THREAD

**Issue by MuhamedFathy** [afollestad/material-dialogs#1707]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.0.0-rc3
 
**Affected Device(s):**
 
All devices and versions
 
**Describe the Bug:**

I am using input dialog like this

    MaterialDialog(view!!.context).title(res = title)
      .input(hintRes = hint, inputType = inputType) { dialog, text ->
        val inputField = dialog.getInputField()
        inputField?.let {
          val isValid = Patterns.EMAIL_ADDRESS.matcher(text).matches()
          it.error = if (isValid) null else getString(R.string.forget_pass_dialog_error)
          dialog.setActionButtonEnabled(POSITIVE, isValid)
        }
      }
      .negativeButton(res = cancel)
      .positiveButton(res = reset) {}

but there's a grey background like below screenshot.

![screenshot_1547998370](https://user-images.githubusercontent.com/4931115/51443206-f84af680-1ced-11e9-98f1-225e2df42f27.png)

**Expected Behavior:**
No grey background.

**Comment by afollestad** [comment]
In the other two issues it's related to using a version of the Google Material library which has this bug.

**Comment by MuhamedFathy** [comment]
Yeah I have downgraded to version 1.0.0 as this [comment](https://github.com/afollestad/material-dialogs/issues/1701#issuecomment-455034744) said and it's works, Thanks.

**Comment by afollestad** [comment]
@Paul75 as the comments above mention it's not an issue with Material dialogs

**Comment by Paul75** [comment]
yes but downgrad the version 2.00 to 1.00 ? it this the solve?
