### ISSUE TITLE
New Color picker

### ISSUE THREAD

**Issue by MathieuAndrade** [afollestad/material-dialogs#1708]
**What module does this apply to?**

 Color module

**Description what you'd like to happen:**

Show a rainbow circle instead of ARG picker or a grid of colors.

**Describe alternatives you've considered:**

I've considerred this library => https://github.com/skydoves/ColorPickerView 
But why not do that on yours color picker module ? 🙂 

Another beautiful exemple =>

![image](https://user-images.githubusercontent.com/26581253/51477028-76a7a700-1d87-11e9-98b9-950e0080a282.png)

**Comment by afollestad** [comment]
Sorry I don't intend to do this.

**Comment by MathieuAndrade** [comment]
Why ?
