### ISSUE TITLE
Proper margins for tablets

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#171]
Right now, the dialog will fill the full screen regardless of whether or not it needs it. This is especially noticeable on tablets.

![screenshot-2015-01-06_22 38 52 606](https://cloud.githubusercontent.com/assets/1361086/5641903/d1100b74-95f5-11e4-93a4-a9dde56a696c.png)
![screenshot-2015-01-06_22 39 34 772](https://cloud.githubusercontent.com/assets/1361086/5641902/d1101600-95f5-11e4-99a3-2caf63cd3c56.png)

**Comment by afollestad** [comment]
I haven't found a way to not make it full screen, other than explicitly setting a width to the layout (rather than match_parent), using wrap_content breaks a lot of stuff. Some experimentation needs to be done with this.

**Comment by hzsweers** [comment]
I'll do some research. In the meantime, you can always make the next release 0.5.10 :stuck_out_tongue:

**Comment by afollestad** [comment]
@hzsweers oh yeah, true, I'll wait until I've verified that the other issue is fixed

**Comment by hzsweers** [comment]
So the only thing I can think of is to set the dialog width to be a fixed width and just calculate what the number of pixels it would be by subtracting the width of the margins on each side from the window's full width. Height fortunately can stay as wrap_content.

Not the prettiest, but it would be the best way to go about it for the time being IMO. Let me know what you think, and if you like it I can PR tomorrow morning.

**Comment by afollestad** [comment]
@hzsweers that sounds like it would be a good solution

**Comment by hzsweers** [comment]
Alright, let me try to find out what the normal margins are and go from there

**Comment by hzsweers** [comment]
You know what, I think it might actually be behaving just fine...

Looking at the different views in the samples and comparing them to stock dialogs, it seems to be fine.

![screenshot-2015-01-09_00 03 55 96](https://cloud.githubusercontent.com/assets/1361086/5676947/9f5af860-9793-11e4-9971-d528aaf68012.png)
![screenshot-2015-01-09_00 05 18 189](https://cloud.githubusercontent.com/assets/1361086/5676949/9f5d6410-9793-11e4-846e-c6f03ce89fd5.png)
![screenshot-2015-01-09_00 06 10 836](https://cloud.githubusercontent.com/assets/1361086/5676948/9f5cc1ae-9793-11e4-8e9a-b23057de566d.png)
![screenshot-2015-01-09_00 06 54 669](https://cloud.githubusercontent.com/assets/1361086/5676951/9f5e04b0-9793-11e4-8c01-5afeaf2dd498.png)
![screenshot-2015-01-09_00 07 42 365](https://cloud.githubusercontent.com/assets/1361086/5676950/9f5dd026-9793-11e4-8c4b-2d6d5ec9d7dc.png)

**Comment by afollestad** [comment]
Oh yeah, looks good to me

**Comment by afollestad** [comment]
I'll close this for now
