### ISSUE TITLE
Changing values in the onDismiss() callback crashes with an NPE.

### ISSUE THREAD

**Issue by adawoud** [afollestad/material-dialogs#1711]
**Library Version:**

2.0.0-rc9
 
**Affected Device(s):**
 
Xiaomi Redmi 5 Plus with Android 8.0
 
**Describe the Bug:**

Changing the value of a Button text in the onDismiss() callback crashes with a NPE on the Button.

**To Reproduce:**
1. Use a customView for the Dialog
2. Add a positiveButton where you get the values from your custom view (this works). My use-case is getting the selected Dates from a custom CalendarView.
3. Call buttonInFragment.setText(selectedDates) in onDismiss()

**Expected Behavior:**
I expect that the value of the button text changes to what I set it to in onDismiss(), but that doesn't happen because it says the button is null.

**Comment by afollestad** [comment]
Hmmm. I'm not sure if this can be fixed. onDismiss is directly corelated with Android's dialog dismiss event and it sounds like Android is destroying the view on its own.

**Comment by adawoud** [comment]
I figured you're just delegating these callbacks to the framework anyway. It's a bit weird. Can you think of any workaround? I tried doing this, but onResume() is only called if I turn my screen off and on again. I was actually under the impression that opening a Dialog calls onPause() in Activity/Fragment, and closing it calls onResume() again.

    override fun onResume() {
        super.onResume()
        if (::firstDate.isInitialized && ::lastDate.isInitialized) {
            btnSelectDates?.text =
                getString(R.string.dateFromTo, formatter.format(firstDate), formatter.format(lastDate))
        }
    }

Also, if it's not much trouble, I could use your input on another issue as well! Here's exactly what I do when the selectDates Button is clicked, and it always skips ~49 frames the first time the dialog is loaded. Could you put your hands on what might be doing this? 

    btnSelectDates.setOnClickListener {
            nextYear.add(Calendar.MONTH, 11)
            val dialog = MaterialDialog(requireContext()).show {
                customView(R.layout.calendar_dialog, scrollable = true)
                positiveButton(R.string.action_done, click = {
                    val selectedDates = calendarView.selectedDates
                    firstDate = selectedDates.first()
                    lastDate = selectedDates.last()
                })
                onDismiss {
                    btnSelectDates?.text =
                        getString(R.string.dateFromTo, formatter.format(firstDate), formatter.format(lastDate))
                }
            }
            val calendarView = dialog.getCustomView().findViewById<CalendarPickerView>(R.id.calendarView)
            calendarView.init(today, nextYear.time)
                .inMode(CalendarPickerView.SelectionMode.RANGE)
                .withSelectedDate(today)

**Comment by afollestad** [comment]
Yeah the library is just doing this
```kotlin
setOnDismissListener { dismissListeners.invokeAll(this) }
```
So I don't think there's a way to avoid it 😞 

Does the frame drop happen without
```
calendarView.init(today, nextYear.time)
            .inMode(CalendarPickerView.SelectionMode.RANGE)
            .withSelectedDate(today)
```
?

**Comment by adawoud** [comment]
I ended up switching to a regular DialogFragment and the system callback worked alright. A bit weird tbh—sorry I couldn't do a lot of investigating because I'm on a tight deadline.

Also, the frame drops remained after the switch so I'm pretty sure the culprit is that piece of code, yeah.
