### ISSUE TITLE
listItemsMultiChoice is closing when only one item is selected

### ISSUE THREAD

**Issue by humazed** [afollestad/material-dialogs#1715]
**Library Version: **

2.0.0-rc9
 
**Affected Device(s):**
 
emulator with api 26
 
**Describe the Bug:**

when using listItemsMultiChoice and selecting only one choice the dialog closes 

        MaterialDialog(this).show {
            title(text = "lil")
            listItemsMultiChoice(
                R.array.socialNetworks, initialSelection = intArrayOf(1, 3)
            ) { _, indices, text ->
                toast("Selected items ${text.joinToString()} at indices ${indices.joinToString()}")
            }
            debugMode()
        }

**Expected Behavior:**
be able to select multible choices and then click choose button like the screen shots

**Comment by afollestad** [comment]
Your dialog needs a positive action button to submit.
