### ISSUE TITLE
Images in List Dialog are overblown

### ISSUE THREAD

**Issue by dri94** [afollestad/material-dialogs#1716]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.0.0-rc10
 
**Affected Device(s):**
 
Nexus 5x
 
**Describe the Bug:**

When using the listdialog. If you have an image, it fills the whole dialog instead of wrapping content.

**To Reproduce:**
1.  Create a list dialog using the library
2. Add an image to the layout
3. Observe image hight is extremely big.

**Expected Behavior:**

Expect image to be the dp size specified

My item layout for the list dialog
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center_vertical">

    <ImageView
        android:id="@+id/item_support_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        tools:src="@drawable/support"/>

    <TextView
        android:id="@+id/item_support_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingStart="16dp"
        android:paddingEnd="16dp"
        tools:text="Online FAQ"/>

</LinearLayout>
```

**Comment by afollestad** [comment]
```xml
<ImageView android:id="@+id/item_support_image" 
    android:layout_width="wrap_content" 
    android:layout_height="wrap_content" 
    tools:src="@drawable/support"/>
```

You should set an explicit width and height to your view.

This isn't an issue with this library, more so how RecyclerView or the ImageView handles itself.

**Comment by dri94** [comment]
This was never an issue before. So it seems something did change (even if maybe with Google's library). But your suggestion is still appropriate, thanks for the quick response!
