### ISSUE TITLE
I cannot found your repo when I try to add lib dependency in Android Studio 1.0.2

### ISSUE THREAD

**Issue by umitems** [afollestad/material-dialogs#172]
I cannot found your repo when I try to add lib dependency in Android Studio 1.0.2.
However , I found this one com.robbypond:material-dialogs:1.0.0 which is forked from your repo.
I have no idea how to add your lib because when I add 
 dependencies {
    compile 'com.afollestad:material-dialogs:0.5.9'
}

there is a error below. Can you please help me figured out?

Error:(11, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'personal-health-assistant' may be using a version of Gradle that does not contain the method.
  Gradle settings</a></li><li>The build file may be missing a Gradle plugin.
  Apply Gradle plugin</a></li>

**Comment by afollestad** [comment]
Sorry, I'm not really sure. It works out of the box for me with Android Studio. As long as you're using jcenter there shouldn't be any issues.

**Comment by afollestad** [comment]
It sounds like you put the dependency string in the wrong place if it can't find 'compile'

**Comment by umitems** [comment]
Ok thanks. I done with it.
