### ISSUE TITLE
ERROR: Failed to resolve: com.afollestad:material-dialogs:2.0.0

### ISSUE THREAD

**Issue by ReBirth11** [afollestad/material-dialogs#1721]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "com.pongodev.recipesapp"
        minSdkVersion 20
        targetSdkVersion 27
        versionCode 5
        versionName "3.0.3"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Main libraries, you always need this libraries in your project. do not remove them.
    implementation'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.google.android.gms:play-services:12.0.1'

    // Important library to create material design. do not remove this.
    implementation project(':materialDesign')

    // Library to create tabbar
    implementation 'com.jpardogo.materialtabstrip:library:1.0.6'

    // Library to create ripple effect. work together with materialDesign library.
    implementation 'com.github.traex.rippleeffect:library:1.3'

    // Library to create rounded, circle, and any shape image.
    implementation 'com.makeramen:roundedimageview:1.4.0'

    // Library load lazy images.
    implementation 'com.squareup.picasso:picasso:2.71828'

    // Library to create simple list.
    implementation 'com.android.support:recyclerview-v7:27.1.1'

    // Library to create complex clickable list.
    implementation 'com.android.support:cardview-v7:27.1.1'

    // Library to create material dialog.
    implementation 'com.afollestad:material-dialogs:2.0.0'

    // Library to create animation imageview.
    implementation 'com.flaviofaria:kenburnsview:1.0.5'

}

**Comment by afollestad** [comment]
There's not really any information here. What's the error?

**Comment by ReBirth11** [comment]
ERROR: Failed to resolve: com.afollestad:material-dialogs:2.0.0

**Comment by afollestad** [comment]
You have jCenter as a repository?

Unfortunately there's not really anything I can do here. It resolves fine for me and others.
