### ISSUE TITLE
Input Dialog crash when using theme other than Theme.MaterialComponents

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#1722]
**Library Version:**

2.0.0
 
**To reproduce this bug:**

1.  Use `Theme.AppCompat.DayNight.NoActionBar` as your activity theme.
````xml
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
````

2. Create an input dialog:
````kotlin
MaterialDialog(context!!)
    .negativeButton(android.R.string.cancel) {it.dismiss()}
    .positiveButton {
        // some code
    }.input("Email", inputType = InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS, waitForPositiveButton = false) { _, email ->
        // some code
    }.show()
````

3. And this error will show up:
````
android.view.InflateException: Binary XML file line #13: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
````

I don't want to use `Theme.MaterialComponents` in my app because it needs `Theme.AppCompat`.

**Comment by afollestad** [comment]
As a temporary solution, you can use the bridge themes.

https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#bridge-themes-bridge-themes

**Comment by afollestad** [comment]
Btw, in `negativeButton(android.R.string.cancel) {it.dismiss()}`, you don't need to call `dismiss()` unless you use `noAutoDismiss()` as well
