### ISSUE TITLE
Dynamic Color Support: Quick Question

### ISSUE THREAD

**Issue by RingoMckraken** [afollestad/material-dialogs#1725]
I understand you've taken the stance to be opinionated and take out dynamic color support in favor of inheritance of activity/app theme. My only question is what was the rationale that lead to cutting out this incredibly useful feature? I really love this library and have used both the version 1 and 2 in many an app for clients. One app in particular, the client is very picky about colors/themes/etc.

**Comment by afollestad** [comment]
You can customize everything you'd need from the styles, even fonts.

"Dynamic" color support generally requires reflection and other hacks that I do not want in my code base. Also, apps should have a well-defined brand and should not be switching up colors at runtime much.

**Comment by RingoMckraken** [comment]
Code leaning on reflection hacks is definitely a great reason not implement a feature. Consider my question answered, thanks! Love the Aesthetic library too btw keep up the good work!
