### ISSUE TITLE
Dark theming not applied over custom views

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1726]
![](https://i.imgur.com/rCAawfq.jpg)

Shouldn't it be possible, theoretically, to theme automatically the custom view basing on materialdialogs actual theme set?

This should be up to the developer but maybe, in version 2, a custom parameter named `isDark` , or something that may help developers theming their own custom views may be a nice goodie.

Normally though their should be handled by the developer itself and not from the dialog library, this being said, maybe we can think about something nice making this process even easier

(I.e. in this example just the text color needs to be changed)

**Comment by afollestad** [comment]
Wait, is that screenshot without any changes to the sample? I must've overlooked that if that's the case.

The layout should be using attributes like `?android:textColorPrimary` etc. to support light/dark correctly.

**Comment by afollestad** [comment]
Could also be an issue with the Context used for custom view inflation

**Comment by AndreaCioccarelli** [comment]
@afollestad Yes It's the latest APK, downloaded by the repo

**Comment by afollestad** [comment]
Text colors are hardcoded in that layout - I don't think this is a bug outside of the sample project
