### ISSUE TITLE
RTL Support for title and message

### ISSUE THREAD

**Issue by MahdiAstanei** [afollestad/material-dialogs#1727]
my minimum SDK is 17 and above but still, I can't get RTL texts even in RTL strings!

**Comment by MahdiAstanei** [comment]
Well thank you @afollestad for your response but I think it's better to try solving the issue instead of ignoring the elephant in the room!
actually, I don't want to force the user to change "whole devices" language for just a dialog, Some of the people use the phones in LTR languages and RTL apps.

**Comment by draskosaric** [comment]
@MahdiAstanei, If that problem is so big as an elephant in the room, maybe you could contribute and add that functionality to this project. @afollestad is not obliged to fulfill anyone's requests if he finds them irellevant and/or have time for them.

**Comment by MahdiAstanei** [comment]
First Hi @draskosaric, I do not want to insult but according to Wikipedia, there are 18 RTL languages in the world and nearly 1 Billion people in these countries and almost 300M of android users Use RTL, I think it's big enough "Elephant" and besides, this functionality already been in this project and if it's removed, I think it's ignoring that "elephant".

**Comment by afollestad** [comment]
@MahdiAstanei there is no elephant in the room. This is standard Android functionality that libraries should not be concerned with if they are correctly supporting RTL mode.

Either your device needs to be in RTL mode or the app's resource configuration needs to be in RTL mode. I will not implement a separate flag because that's reinventing the wheel and I will not maintain that.

**Comment by afollestad** [comment]
And no, the functionality is not "removed". If something is not working correctly while the device is in RTL mode, then that's a valid bug,

**Comment by afollestad** [comment]
Here's an example of it working as intended:

![screenshot_1551061637](https://user-images.githubusercontent.com/1820165/53310449-d2bb8a80-3861-11e9-80e9-20f6ca85e34b.png)

Nothing to do here.

**Comment by MahdiAstanei** [comment]
It's ok, the point is that in my country, I'm not sure about the whole device language, many people using English language in their devices while using Persian(RTL) apps and for that, I used to set gravity to views and layouts to make sure the layout is laid out correctly. I start using version `'0.9.6.0'` that made my job.
Anyway I did not intend to blame on you or do any insulting, but if it happened, I'm sorry 🙂❤️ @afollestad

**Comment by afollestad** [comment]
That is practice. If you're setting grwboty everywhere you'll end up missing support for othe countries unless you have programmatic switches everywhere. System level RTL is the standard - it sounds like there's a gap that Google should fix at the system level if it's so common for people to want RTL outside of RTL system languages.
