### ISSUE TITLE
Collor choose - Sub Colors type mismatch

### ISSUE THREAD

**Issue by serhii-pokrovskyi** [afollestad/material-dialogs#1729]
**Library Version:**

2.0.0

**Kotlin version**
1.3.21
 
**Describe the Bug:**

Clearly, there is a type mismatch.

According to description of 20.02.2019:

```kotlin
val colors = intArrayOf(RED, GREEN, BLUE) // size = 3

val subColors = listOf( // size = 3
  intArrayOf(LIGHT_RED, RED, DARK_RED, WHITE),
  intArrayOf(LIGHT_GREEN, GREEN, DARK_GREEN, GRAY),
  intArrayOf(LIGHT_BLUE, BLUE, DARK_BLUE, BLACK)
)

MaterialDialog(this).show {
  title(R.string.colors)
  colorChooser(colors, subColors = subColors) { dialog, color ->
      // Use color integer
  }
  positiveButton(R.string.select)
}
```

When trying to implement i got an error here: colorChooser(colors, _subColors_ = **subColors**)

> Type mismatch
> Required: Array<IntArray>?
> Found: List<IntArray>

**Comment by afollestad** [comment]
Nope, use `listOf(...)`
