### ISSUE TITLE
Dialog buttons are not vertically centered

### ISSUE THREAD

**Issue by bernaferrari** [afollestad/material-dialogs#1734]
I thought something was wrong, so I went ahead and draw black squares to see how the margin was being respected. It turns out, the margin on the right side is different than bottom (bottom is larger).

![image](https://user-images.githubusercontent.com/351125/53532850-4f0ad380-3ad7-11e9-8117-d536682a7472.png)

Material design states that everything should be 8dp:
![image](https://user-images.githubusercontent.com/351125/53532948-aa3cc600-3ad7-11e9-90b7-76f884a1c6fc.png)

**Comment by bernaferrari** [comment]
Also, I might be wrong, but on Material specification the content/message margin is 24dp and IT LOOKS (I really didn't measure) that Material Dialogs is using less than 24, since on my screenshot the distance is the same as the button to the corner, so it looks like 16dp.

**Comment by afollestad** [comment]
Will be fixed in the next release:

*(emulator)*
<img src="https://user-images.githubusercontent.com/1820165/54472373-cce00780-4784-11e9-85cf-fb1a41855785.png" width="250" />
