### ISSUE TITLE
[Question] Block the input after a number of characters ?

### ISSUE THREAD

**Issue by Tboy70** [afollestad/material-dialogs#1736]
Hi ! 

I don't know if it's the place to ask my question. If not, I'm very sorry. 

First, I would like to congratulate the developpers for this amazing lib, very practical and useful :) 

I would like to know if it's possible with this lib to stop the input. 
For example, I set the max number characters to 7. Once there is 7 characters in the input field, the user can't continue to write anymore (only erase what he wrote). 

Thank you for your answer :)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/README.md#max-length
