### ISSUE TITLE
Input MaterialDialog prefilled text is not selected

### ISSUE THREAD

**Issue by marbat87** [afollestad/material-dialogs#1737]
**Library Version:**

2.0.3
 
**Affected Device(s):**
 
Tested on Android 6.0 (but probably all versions are affected)
 
**Describe the Bug:**

When you create an input MaterialDialog with a prefilled text, the text itself is not selected by default

**To Reproduce:**
```
MaterialDialog(context)
.input(prefill = "ANY TEXT", inputType = InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_FLAG_CAP_SENTENCES)
.title("any title")
.positiveButton(android.R.string.ok)
.negativeButton(android.R.string.cancel)
.show()
```

**Expected Behavior:**

The prefilled text should be selected by default

**Comment by afollestad** [comment]
The cursor goes to the end, which is intended behavior.

If you want to select the whole text you can do so programatically.
