### ISSUE TITLE
Positive action button in single choice list doesn't appear until selection is made

### ISSUE THREAD

**Issue by PetkevichPavel** [afollestad/material-dialogs#1738]
• com.google.android.material:material:1.0.0
• Material Dialogs version: 2.0.3
• Device OS version: Android Pie
• Device Manufacturer: One Plus 6T

When I create single choice dialog and try to chekItem by index, it doesn't work correctly.

Here is my code:

            MaterialDialog(this).show {
                title(R.string.test)
                listItemsSingleChoice(R.array.testArray) { dialog, index, text ->
                    checkItem(1)
                    dialog.positiveButton(R.string.testTitle) {
                                      .............................
                    }
                }
            }        

After open dialog, the item doesn't check, but if you will tap on some item the item will check by checkItem(1)... it was very strange can you control it if it should work like that. (i don't think so that this is good flow)
[Here is the gif for better understanding](https://imgur.com/a/1KLp5SW)

**Comment by afollestad** [comment]
I'm not really sure what the problem is here, @PetkevichPavel. `checkItem` isn't working how you expect?

The parameter is an index, index 1 is the second item in the list, which is what your GIF shows.

**Comment by PetkevichPavel** [comment]
Hi @afollestad, thanks for your answer, of course I know what’s mean index in checkItem method, but if you look one more time on the gif which I sent, you will se that: I have some button which render dialog with this single choice list items, after choose some item I set this button by chosen item text, and for future want to open dialog with current chosen item, for that I use the method checkItem by index, but because of your flow it wasn’t work correctly. Look on this gif one more time and you will see that at first open the item wasn’t check( as nafta) and only after click on some item the correct item will checked.

This flow is wrong, isn’t it? 

And another same situation when you open dialog for the first time and you don’t have some item choosed and for choose you should doble click on item because on first click you show the button and after second click you enable button for confirm, this is too very strange..

**Comment by afollestad** [comment]
I still don't see a problem. Your code above does not pre-select an item. Your single choice list will not select an item by default unless you explicitly tell it to. @PetkevichPavel

**Comment by PetkevichPavel** [comment]
For sure I wasnt post my original code i posted the test code without pre-select, but with the static index pre-select(0/1) this is doesnt metter.

Here is my original code:
```
btnFuelType?.setOnClickListener {
            MaterialDialog(this).show {
                title(R.string.car_dialog_fuel_type_title_str)
                listItemsSingleChoice(R.array.FuelType) { dialog, index, text ->
                    resources.getStringArray(R.array.FuelType).getIndexViaString()?.let {
                        checkItem(it)
                    }
                    dialog.positiveButton(R.string.car_choose_dialog_positive) {
                        text.getFuelTypeViaString(this@CarCreateEditActivity)?.let {
                            render(CarCreationModel.RenderFuelType(it))
                        }
                    }
                }
            }
        }
```

One more time look on video, which I recorded for you know:  [HERE](https://drive.google.com/open?id=1Fqo5edCSa7sd4rR2jN8WW1L2HDzVZqHr)

And if you don't understand it after that video where you have problems I don't know how to explain to you some other way, because I think that you do not want to hear that you have some problem. 

Thanks and have a nice day.

**Comment by afollestad** [comment]
I don't think you understand what the code you're writing here is doing unless I'm not understanding what you're trying to accomplish. 

Are you trying to preselect right when the dialog opens?

listItemsSingleChoice's lambda is invoked when you select an item AND press the positive action button. So you're calling checkItem at a weird time in your example.

**Comment by afollestad** [comment]
See the method declaration:

```Kotlin
@CheckResult fun MaterialDialog.listItemsSingleChoice(
  @ArrayRes res: Int? = null,
  items: List<String>? = null,
  disabledIndices: IntArray? = null,
  initialSelection: Int = -1,
  waitForPositiveButton: Boolean = true,
  selection: SingleChoiceListener = null
): MaterialDialog
```

**Comment by afollestad** [comment]
I will listen to your video in a moment though

**Comment by PetkevichPavel** [comment]
@afollestad are you carried me?? Now you want to try telling me that I do not know what I wrote? I do not understand the code which I wrote? Im not a junior/medior developer, and because of that if i smth wrote i understand each row which I wrote. If you do not see the problem at your side is it your problem and junior behavior. 

And try to learn kotlin if you do not understand code above:)

**Comment by afollestad** [comment]
@PaulWoitaschek I'm not able to reproduce any problems: 

<img src="https://user-images.githubusercontent.com/1820165/53845121-d84d5a80-3f5c-11e9-88fa-e71a57fb175a.png" width="250" /> <img src="https://user-images.githubusercontent.com/1820165/53845122-d84d5a80-3f5c-11e9-828f-f74d248bcf1d.png"  width-"250" />

If you want to pre-select something, it should be done like this:

```
MaterialDialog(this).show {
        title(R.string.socialNetworks)
        listItemsSingleChoice(R.array.socialNetworks, initialSelection = 1) { _, index, text ->
          toast("Selected item $text at index $index")
        }
}
```

I'm not really sure why you're calling `checkItem` inside of the callback.

**Comment by afollestad** [comment]
And your comments are ridiculous and condescending. I work for Square who writes libraries that you probably use. If you're going to be rude, don't use my libraries. I make them for free to help people.

**Comment by afollestad** [comment]
And no, I really do not see what the problem is here. It's probably getting lost in translation what the problem is here, but I have no found any use cases where something in single choice dialogs do not work as they are supposed to.

**Comment by PetkevichPavel** [comment]
I using this library from first time when this library apear and only because of that i wrote you that i see here this problem, if you do not se this problem after last video: **double click for choosing** is not a good idea...

**Comment by afollestad** [comment]
@PetkevichPavel I just can't tell what is not working correctly.

---

Double clicking is not used for selection. There are two ways to get selections:

1. `listItemsSingleChoice(waitForPositiveButton = false)`, the inner callback is called _every time_ an item is clicked.
2. `listItemsSingleChoice(waitForPositiveButton = true)`, the default behavior, the inner callback is called when the positive action button is pressed.

**Comment by afollestad** [comment]
An example of the default behavior:

![mnml-march5-035206pm_2](https://user-images.githubusercontent.com/1820165/53845686-da181d80-3f5e-11e9-9161-d9fc56f0dfd6.gif)

**Comment by afollestad** [comment]
And if you specify `waitForActionButton=false`:

![mnml-march5-035507pm_2](https://user-images.githubusercontent.com/1820165/53845762-324f1f80-3f5f-11e9-84ec-60975d169c49.gif)

**Comment by PetkevichPavel** [comment]
First of all sorry if you fill from my comments some "unrespect", I know who you are and where you working. Thank you for answering tomorrow morning I will double check it and tell you actual state. 

One more thanks for your time.

**Comment by PaulWoitaschek** [comment]
> @PaulWoitaschek I'm not able to reproduce any problems:

How am I related to this issue?

**Comment by PetkevichPavel** [comment]
Hi, @afollestad one more time thank you for your explanation, you were right, that I shouldn't use _**chekItem(index)**_ enough set it as a parameter inside _**listItemsSingleChoice()**_ and after that pre-select work perfectly! 

After all, I still didn't get why when you start a dialog without pre-select the button is not visible and only after the first click it will be visible but not enable and after second click it enabled for the click.

![dialog](https://user-images.githubusercontent.com/12551722/53906356-027d4600-404b-11e9-9782-ea361b837f91.gif)

**Comment by afollestad** [comment]
@PetkevichPavel I realized it's because you're calling `positiveButton` from within the single choice callback, which is not called until an item is selected.
