### ISSUE TITLE
private style legacy cardview

### ISSUE THREAD

**Issue by Raykud** [afollestad/material-dialogs#1739]
When using the new Material Components library and trying to use the legacy CardView as documented in: https://material.io/develop/android/components/material-card-view/ on a new project you get a style error that is set as private in the input library:
![image](https://user-images.githubusercontent.com/4366666/53822125-c0fa7700-3f34-11e9-8583-5a253ca5bd43.png)
![image](https://user-images.githubusercontent.com/4366666/53822136-c657c180-3f34-11e9-99bf-929849aef640.png)

**Comment by afollestad** [comment]
That's intentional. You shouldn't use that style.

**Comment by afollestad** [comment]
And Material Components are not related this library, but you should use: `style="@style/Widget.MaterialComponents.CardView"`

**Comment by Raykud** [comment]
then why the documentation says you should. Try reading the: Legacy Material Style

**Comment by afollestad** [comment]
![screenshot_20190305-090832](https://user-images.githubusercontent.com/1820165/53823268-44f93280-3f26-11e9-95aa-e0057b2e4017.png)

Nothing there uses that style.

**Comment by Raykud** [comment]
![screen shot 2019-03-05 at 11 10 16 am](https://user-images.githubusercontent.com/4366666/53823381-48e18080-3f37-11e9-92d6-81539f374f12.png)

**Comment by afollestad** [comment]
Odd. 

Well unfortunately, I don't plan to update the style name in this library for a legacy style since legacy styles are considered deprecated.
