### ISSUE TITLE
Exception not thrown when attempting to present from non-ui thread (?)

### ISSUE THREAD

**Issue by loeschg** [afollestad/material-dialogs#174]
I just had a head scratching moment where I built a dialog, called `show()`, and it wasn't displayed.

It looks to be an issue with me calling this from a non-ui thread. As soon as I put the call in a runOnUiThread runnable, it worked. 

I'd expect either the app to crash or at least some sort of error logged indicating this.

**Comment by afollestad** [comment]
Good idea. This is now in the code and will be included with the next release.

**Comment by loeschg** [comment]
:+1: awesome. Thanks!

**Comment by afollestad** [comment]
Release 0.6.0 is now available
