### ISSUE TITLE
META-INF build error when using this library + old Support Library in my app

### ISSUE THREAD

**Issue by damsii** [afollestad/material-dialogs#1741]
I imported the library as specified but I cannot build the project. It constantly gives me an error with META-INF things missing. It's not compatible with KotlinX. Please fix this if you can. Because the library cannot be used with Kotlin Coroutines...

**Comment by leif123** [comment]
me too, Manifest merger failed with multiple errors, see logs

**Comment by victorlapin** [comment]
Hmm, I have a pet project with coroutines and this lib, and no build errors...

**Comment by damsii** [comment]
Are you using Synthetic Binding for binding the views or you are using the standard binding? Because I think the problem is the KotlinX compatibility, not the Coroutines themselves. Because I added the lib and I get META INF errors from androidx, which is in this case kotlinx, if I try to skip all of them from building in the gradle specified in packageOptions, the error appears that cannot compile without it, since I use Synthetic Binding, when I emoved the lib, and created a dialog with the standard native code in Java i.e Kotlin, it worked and built fine. I'm using Picasso as well as a library in the project. 
Please tell me if I'm missing something and that may be the cause of the error, because I really appreciate this library and I use it. Cheers!

**Comment by victorlapin** [comment]
Now that's weird, because:
- I'm using kotlin synthetics
- I'm using Picasso

**Comment by victorlapin** [comment]
@damsii here's my build.gradle paste, if it will be of any use: https://pastebin.com/SgcfEBb3

**Comment by damsii** [comment]
@victorlapin Thank you very much, I'll check it out and let you know of the outcome. Cheers!

**Comment by afollestad** [comment]
@damsii this isn't a problem with coroutines. I use coroutines and this library in multiple production apps.

**Comment by afollestad** [comment]
Unable to repro any problems here

**Comment by damsii** [comment]
`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-27:19 to override.
`
This build problem appears after I add the dependency. It's related with AndroidX as far as I understand

**Comment by afollestad** [comment]
Oh, that means one of the other dependencies you're using depends on the legacy Support lib

**Comment by damsii** [comment]
I don't want to use AndroidX in this project, is there a way to bypass this, downgrade the version maybe or something else? Since I researched deeply and saw that other people have encountered the same problem, and most of them solved it by migrating to AndroidX, I don't want to do it, and frankly, I may face many other problems by doing so, and no time to fix them. I'd be happy if I can find a workaround for the problem. Anyway, cheers and thanks.

**Comment by afollestad** [comment]
Sorry, but AndroidX is the current and future of Google's libs and this library can only go forward. I'm not sure if I can do anything to "work" with apps that are still using the old Support Library on my end. You may be able to do something in your Gradle files that modify your META-INF, e.g. include or exclude certain files.
