### ISSUE TITLE
Material Design 2

### ISSUE THREAD

**Issue by DennyWeinberg** [afollestad/material-dialogs#1743]
Any planning about moving to the 2019 Material Theme we see in Google Mail and Calendar?

**Comment by afollestad** [comment]
The current implementation _is_ Material Design 2. You just need to do more customization on your dialog, like border radius, etc.

**Comment by DennyWeinberg** [comment]
Would be great to have it integrated. But ok, thanks. It's an awesome lib!

**Comment by afollestad** [comment]
It is: https://github.com/afollestad/material-dialogs#theming

**Comment by DennyWeinberg** [comment]
Nice!
