### ISSUE TITLE
Doesnt build with proguard turned on

### ISSUE THREAD

**Issue by dogeri28** [afollestad/material-dialogs#1744]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
 
**Describe the Bug:**

A clear description of what is the bug is.

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by afollestad** [comment]
There is not enough information here to make an issue.
