### ISSUE TITLE
Input dialog theming

### ISSUE THREAD

**Issue by victorlapin** [afollestad/material-dialogs#1745]
**Library Version:**

2.0.3
 
**Affected Device(s):**
 
Nexus 5 with Android 7.1.2
OnePlus 5T with OOS 9.0.4
Android Pie emulator
maybe more
 
**Describe the Bug:**
With latest Material library (com.google.android.material:material:1.1.0-alpha04) edit text in input dialog is themed weirdly. Maybe I've missed something theme wise in my styles.xml, but I don't know exactly where to look. Edit texts in custom view dialogs are looking as they should.
See the attached image:
![Screenshot_20190314-141247](https://user-images.githubusercontent.com/8329104/54352927-cdcd4800-4663-11e9-8068-d8cc4400747d.png)

**To Reproduce:**
1. Create a project with latest material theme dependency
2. Show input dialog

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by afollestad** [comment]
Well, I wouldn't advise using an alpha version of a library.

**Comment by afollestad** [comment]
Should be fixed in the latest release
