### ISSUE TITLE
Re-think max width

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1749]
**Library Version:**

2.1.0
 
**Affected Device(s):**
 
Google Pixel 2 XL with Android 9.0
 
**Describe the Bug:**

The dialog width changed (got smaller) when upgrading from 2.0.3 to 2.1.0.

 Does this have a particular reason?
How can I change the width of the dialog, as the new width is a bit too small (for me)?

**Comment by afollestad** [comment]
This is matching Google's newer spec

**Comment by joey-harward** [comment]
Is there a way to override this width to be more like 2.0.3? It is definitely too small for me too :)

**Comment by guger** [comment]
I'd also like to customize the with, especially for the datepicker, this width is too small.

**Comment by masc3d** [comment]
> I'd also like to customize the width, especially for the datepicker, this width is too small.

yes, there's quite a few scenarios where large margins are not suitable. also it doesn't look good.

@afollestad which spec btw looking@ https://material.io/design/components/dialogs.html# does not show such margins.

**Comment by afollestad** [comment]
The specs show a width of 280dp

**Comment by joey-harward** [comment]
I have a lot of custom dialog scenarios where that width does not work. And I agree with @guger definitely not for datepicker. Is there any way to expose `md_dialog_max_width` so we can override?

I really appreciate your work on this library. One of the best!

**Comment by afollestad** [comment]
Yes, but it may get a more complex than that - the value is different for values, values-land, values-sw600dp, etc.

**Comment by joey-harward** [comment]
You are correct, normal consumers should not have to remember different values, but power users should at least have the option to override?

No worries I'll stick with 2.0.3 :) Thanks again for your work!

**Comment by masc3d** [comment]
thanks @afollestad 

customization option is great.

inconsistency with spec is probably because your library can do much more than spec is designated for, so my suggestion would be `custom size` > `spec width in case measured view is within bounds` > `previous version standard width` which would neatly coverall use cases with minor consumer impact.

**Comment by AndreaCioccarelli** [comment]
Agree, this library shouldn't strictly follow all the specs since some of them don't really make sense if applied over here.

Great work anyways :)

**Comment by jahirfiquitiva** [comment]
I agree there should be either a way to set a custom max width, or some changes done to the library ... It looked so much better before @afollestad  😕 😞 

Here's a comparison from a picture in the Material Design specs and one from my app

| Material Design Specs | My App using v 2.6.0 |
|-----------------------|----------------------|
| ![mio-design_assets_1g8052ZKUjp4a9STlAHL9FJ7MtLTOHJnK_dialogs-alertdialog-do-1](https://user-images.githubusercontent.com/10360816/55660047-fd3a2500-57c9-11e9-88ad-c53e7da83706.png) | ![Screenshot_20190405-173437_Frames](https://user-images.githubusercontent.com/10360816/55660051-ff03e880-57c9-11e9-928d-c5c9d0c46ae2.png) |

**Comment by afollestad** [comment]
I've restored the previous max width values before they shrunk. Keeping the `maxWidth()` setter around as well.
