### ISSUE TITLE
Custom textcolor for positive and negative button text in dialog

### ISSUE THREAD

**Issue by Anand9893** [afollestad/material-dialogs#1754]
Is it possible to add a custom color for positive and negative button in default material dialog. Right now we could add text and text font.

**Comment by afollestad** [comment]
With the `md_color_button_text` attribute in your Activity theme

**Comment by Anand9893** [comment]
Thanks. But is it possible to set two different color for each button text. Like green color for positive button text and red color for negative button text?

**Comment by afollestad** [comment]
Following the Material Spec, which this lib enforces, the buttons should both be the same color

https://material.io/design/components/dialogs.html#theming
