### ISSUE TITLE
Better support of modern java.time classes

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1756]
**Library Version:**

2.3.0
 
What about passing 'epochMillis' as `Long` values instead of calendar?
This would be the easiest way to support both, old java Date/Calendar, and new java.time classes.

**Comment by afollestad** [comment]
`Calendar` is pretty standard for Android.

**Comment by guger** [comment]
Right, but it's actually outdated and replaced in newer versions of android, where Java 8 is supported.

**Comment by afollestad** [comment]
I don't think it should be changed at this point - especially since changing callback signatures will effect existing users.

**Comment by afollestad** [comment]
You can easily pull the epoch time out of a `Calendar`
