### ISSUE TITLE
Action Button Ripple color should be colorPrimary

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1758]
**Library Version:**

2.3.0
 
**Describe the Bug:**

The ripple color of a dialogs action button should be tinted with the primary color, here it is gray.

**Comment by afollestad** [comment]
Easy to fix.

But right now it's using `?android:colorControlHighlight` by default, or `md_ripple_color` if specified.

**Comment by afollestad** [comment]
Where does it say the ripple should be the primary color? What would the transparency component be?

**Comment by guger** [comment]
Okay, in my case it's gray, but I didn't specify colorControlHighlight explicitely.

I don't find any mentions of rippleColor to be colorPrimary, but all example images in the docs use the primary color for ripple effect.
https://material.io/design/components/buttons.html#text-button

**Comment by afollestad** [comment]
Ah, yeah 👍
