### ISSUE TITLE
Action Buttons are not symmetrical/bottom side cut off

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1759]
**Library Version:**

2.3.0
 
**Describe the Bug:**

The bottom side of the action button is cut off, so it appears unsymmetrical.
![Action Button Image](https://user-images.githubusercontent.com/16765393/54709234-6e7ca580-4b45-11e9-861b-90ecd72b5cdf.png)

**Expected Behavior:**

A dialog's action button should be symmetrical as in the material docs.

**Comment by afollestad** [comment]
Resolved in 2.4.0
