### ISSUE TITLE
Support for 2.1

### ISSUE THREAD

**Issue by tommienu** [afollestad/material-dialogs#176]
Any chance of adding support for 2.1 and upwards?

**Comment by eneim** [comment]
I suppose only 1% of the planet's population still keep using 2.1 Android phone. Don't waste your time and creativity

**Comment by afollestad** [comment]
It had before but I pulled support cause it broke stuff.

**Comment by tommienu** [comment]
Thanks for the reply @afollestad. We'll send back some PRs if we ever get around to fixing it!
