### ISSUE TITLE
Theme attribute for unchecked/unactivated widgets color

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#1761]
I can style the title, message and buttons of my dialog using:

* md_color_title
* md_color_content
* md_color_button_text
* md_font_title
* md_font_body
* md_font_button

However when I use `checkBoxPrompt`, the Checkbox is tinted grey and does not use my custom fonts and colors.

It would be great if you could style the checkbox promt too.

**Comment by afollestad** [comment]
Added `md_color_widget` and made sure the body font gets applied. The color of the text was already being themed, though.

**Comment by PaulWoitaschek** [comment]
Thanks! Please update the readme as well.

**Comment by PaulWoitaschek** [comment]
The checkbox is still grey.

```xml
<androidx.appcompat.widget.AppCompatCheckBox
  app:buttonTint="@color/blueGrey800"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content" />
```

`buttonTint` is what will set the color.

**Comment by afollestad** [comment]
I've tested and it works as intended

**Comment by PaulWoitaschek** [comment]
Your tint tints the checked checkbox. What I need is the unchecked checkbox. (which can be tinted by `app:buttonTint`)

![image](https://user-images.githubusercontent.com/743462/54938336-77df8680-4f26-11e9-8c96-f51cf6522846.png)

**Comment by afollestad** [comment]
Ohh, that's how they're supposed to look. Why do you want to change that?

**Comment by PaulWoitaschek** [comment]
Because our designer designed an app with a different secondary color (like you can see in the layout below).

**Comment by afollestad** [comment]
Ah, got it. The change is just a matter of passing in another value in this block:

```kotlin
dialog.resolveColor(attr = R.attr.md_color_widget)
        .ifNotZero {
          CompoundButtonCompat.setButtonTintList(
              viewHolder.controlView,
              dialog.createColorSelector(checked = it)
          )
        }
```

`createColorSelector` has an optional `unchecked` parameter. Right now it's using `colorControlNormal` as the default value for unchecked, as does any other widget in an app.
