### ISSUE TITLE
DialogAction not found in version 2.4.0

### ISSUE THREAD

**Issue by caneto** [afollestad/material-dialogs#1763]
Compile detect not found (import com.afollestad.materialdialogs.DialogAction;) 
Return this mensage in compile.

error: cannot find symbol class DialogAction
error: cannot find symbol class SingleButtonCallback

Android Studio 3.3.2

**Library Version:**

2.4.0

**Comment by afollestad** [comment]
@caneto uh, that class doesn't exist. Are you migrating from the old library version?

**Comment by sagarvasnani** [comment]
Well yes, the issue remains for me too. I am migrating from 0.9.6.0 to 3.1.0.

**Comment by afollestad** [comment]
Read the documentation.
