### ISSUE TITLE
Update to kotlin-stdlib-jdk8

### ISSUE THREAD

**Issue by eakteam** [afollestad/material-dialogs#1764]
Better to use kotlin-stdlib-jdk8 than kotlin-stdlib-jdk7 , because it ads extra libs without any needs in apps which contains kotlin-stdlib-jdk8

**Comment by afollestad** [comment]
Yeah - my only concern is whether this will break builds for apps that need to use jdk7

**Comment by eakteam** [comment]
I understand, but i think most of the developers who using Kotlin, use jd8. Anyway, i think the only solution is to publish another maven dependencies, one with jdk7 and one with jdk8, and users can choose what they want. I have tested in my own with jd8 it works OK. But for e.x like me who is fans of smallest app possible i should download all the project and change the jdk on my own, and it is time consuming.
But, thank you for this great lib, it make the work really simple and fun. 
Best Regards

**Comment by eakteam** [comment]
Thank you !

**Comment by grndvl1** [comment]
I would maybe tag a new version and warn users that if you are targeting JDK7 then use the previous lib.

**Comment by afollestad** [comment]
I would rather not tell people to use an old version and not get new features/bug fixes.

**Comment by eakteam** [comment]
@grndvl1 , that would be good too. But i think i can be better to publish different versions for jdk7 and jdk8 and add to Readme file how to implement for different use cases

**Comment by afollestad** [comment]
I'd also rather not maintain multiple versions.

**Comment by eakteam** [comment]
@afollestad hahahaha, i understand and you are right really, but something should be done.
Respect for your replies :D :D

**Comment by bernaferrari** [comment]
I don't understand this, you don't even need jdk7/jdk8. You can just use `implementation "org.jetbrains.kotlin:kotlin-stdlib:$version"`. Jdk8 only adds a [few methods](https://github.com/JetBrains/kotlin/tree/master/libraries/stdlib/jdk8) that you probably don't need.

**Comment by eakteam** [comment]
@bernaferrari 
The Kotlin standard library kotlin-stdlib targets Java 6 and above. There are extended versions of the standard library that add support for some of the features of JDK 7 and JDK 8.

Java 6 is very old :( , and there are some features of java 7 (i don't know about java 8)

**Comment by afollestad** [comment]
Yeah, `org.jetbrains.kotlin:kotlin-stdlib` targets JDK < 1.7
