### ISSUE TITLE
Incorrect default time in time picker

### ISSUE THREAD

**Issue by victorlapin** [afollestad/material-dialogs#1766]
**Library Version:**

2.5.0
 
**Affected Device(s):**
 
OnePlus 5T with OOS 9.0.4
Nexus 5 with Android 7.1.2
Emulator with Android 9.0
 
**Describe the Bug:**

When the default time is set, time picker always showing it as AM, i.e. if I set the time 15:45 (or 3:45 PM), it'll be shown as 3:45 AM.

**To Reproduce:**

```kotlin
        val defCal = Calendar.getInstance().apply {
            set(Calendar.HOUR_OF_DAY, 15)
            set(Calendar.MINUTE, 45)
        }
        MaterialDialog(context!!).show {
            lifecycleOwner(this)
            timePicker(
                currentTime = defCal,
                show24HoursView = android.text.format.DateFormat.is24HourFormat(context)
            ) { dialog, datetime ->
                // some code here
            }
            positiveButton(res = android.R.string.ok)
            negativeButton(res = android.R.string.cancel)
        }
```

**Expected Behavior:**

To see the correct default time.

**Comment by victorlapin** [comment]
Sorry for awful looking code snippet, code tag didn't respect line breaks

**Comment by afollestad** [comment]
GitHub uses 3 tickets for code styling (```)

```kotlin
class KotlinCode {
}
```
