### ISSUE TITLE
Testing Issues

### ISSUE THREAD

**Issue by grndvl1** [afollestad/material-dialogs#1768]
I would like to see some examples of how to test the Material dialogs using Espresso.  I was able to get some code running and popup the dialog after fixing the runonuithread issue but now how do I click buttons or input text during a test?  Or even check the UI for the dialog.  Some great testing samples would be helpful

**Comment by afollestad** [comment]
A `MaterialDialog` is just a `Dialog`, so you'd use what you're use for normal dialogs.

https://stackoverflow.com/questions/21045509/check-if-a-dialog-is-displayed-with-espresso/21046811#21046811

https://developer.android.com/training/testing/ui-automator

etc.
