### ISSUE TITLE
Is there any way I can use both 0.9.6 (for java) and 2.6 (for kotlin) in a single project?

### ISSUE THREAD

**Issue by jeffreyfhow23** [afollestad/material-dialogs#1769]
My project include both java and kotlin. I would love the chance to work with 2.6, but it appears as though the fact that some of my code is in java means that I should be using 0.9.6. Is there a way to get the benefit of both?

**Comment by afollestad** [comment]
Unfortunately, no - I didn't think to make the packages different when i wrote the new version, but there's no going back now.

**Comment by jeffreyfhow23** [comment]
Thank you very much for your quick response.
