### ISSUE TITLE
Question: "Directory is not writeable to your app"

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/material-dialogs#1772]
Hi Aidan

I am getting this error while trying to open a dialog, and I'm not sure what is causing it or what to do to fix it.

I can see it in [this file](https://github.com/afollestad/material-dialogs/blob/master/files/src/main/java/com/afollestad/materialdialogs/files/DialogFolderChooserExt.kt#L72) but I'm still clueless about the reasons behind it.

Would you mind explaining how to make it work properly? The app already has the `WRITE_EXTERNAL_STORAGE` permission granted 😕

**Comment by jahirfiquitiva** [comment]
Even setting `allowFolderCreation` to false, does not help, because then I get `Directory is not readable to your app.` 🤔

**Comment by afollestad** [comment]
Well, `canWrite()` would return false if the folder is a system folder or Android doesn't think your process should have access to it

**Comment by jahirfiquitiva** [comment]
That's weird. I think these checks were not part of the library before and everything was working fine.

I, for sure, am not accessing a system folder. It's something like `/storage/emulated/0/MyApp`

**Comment by jahirfiquitiva** [comment]
@afollestad Do you think those check are really needed? Or could they be removed? :thinking:

**Comment by jahirfiquitiva** [comment]
@afollestad ... Any news on this? 😅 🙏

**Comment by afollestad** [comment]
Not sure - I added them to solve various problems
