### ISSUE TITLE
Program type present

### ISSUE THREAD

**Issue by maheshsystimanx** [afollestad/material-dialogs#1773]
Program type already present: com.afollestad.materialdialogs.color.ColorChooserDialog$3

**Comment by maheshsystimanx** [comment]
pls solve this error.I don' know why show this .we are using this library
 implementation('com.github.afollestad.material-dialogs:commons:0.8.5.9@aar') {
        transitive = true
        exclude module: 'support-v4'

    }

**Comment by afollestad** [comment]
That version of the library will not receive new releases.
