### ISSUE TITLE
about  commom:0.9.6.0

### ISSUE THREAD

**Issue by Zebra67** [afollestad/material-dialogs#1776]
I am using common:0.9.6.0

in that I am using 
void showapps(MaterialSimpleListAdapter adapter);
MaterialSimpleListAdapter.Callback getApplicationChooseCallback();

but it is giving errors jetified-commoms-0.9.6.0.aar type error

I am using androidx plz help

**Comment by afollestad** [comment]
Anything before version 2.0 is using the old Support Library, not AndroidX, and is no longer supported.
