### ISSUE TITLE
listItemsMultiChoice: Check boxes not animated

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#1777]
When calling `listItemsMultiChoice`, the check box selection is not animated.

![no-checkbox-animation](https://user-images.githubusercontent.com/743462/55779933-129f9f80-5aa7-11e9-973d-98f2b7318424.gif)

I can manually disable the change animations:
`(getRecyclerView().itemAnimator as SimpleItemAnimator).supportsChangeAnimations = false`
Then the checkboxes check correctly but the ripple effect is gone.

![no-ripples](https://user-images.githubusercontent.com/743462/55779948-17fcea00-5aa7-11e9-9cd6-f9624966d90e.gif)

**Comment by afollestad** [comment]
That's weird, I'm actually seeing the animations work just fine.

**Comment by afollestad** [comment]
The latest release may help what you're experiencing.

**Comment by PaulWoitaschek** [comment]
It works, thanks :)

![checkboxes](https://user-images.githubusercontent.com/743462/56364405-bea36200-61ee-11e9-8c72-ca806f0e9c57.gif)
