### ISSUE TITLE
What happens when showing a dialog after lifecycle has ended?

### ISSUE THREAD

**Issue by hardysim** [afollestad/material-dialogs#1778]
I'm using `2.7.0` with the `lifecycle`-extension and wonder if it's safe to show a dialog when the lifecycle has ended.

This may happen when returning from a long-running async operation where I want to show an error dialog in its callback. 

I'm setting `lifecycleOwner` just like the example which adds a listener to `Lifecycle.Event.ON_DESTROY` and calls `dismiss()` (so any already showing dialog is gracefully dismissed).

But what will happen if I try to `show()` a dialog after `ON_DESTROY`? Is this going to crash? Maybe with the following exception?

> Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.

**Comment by afollestad** [comment]
Yes, an `android.app.Dialog` needs a `Window` to attach to. After an Activity is destroyed there isn't a valid Window for a dialog to attach to.

**Comment by hardysim** [comment]
Can we add some kind of check to this library that prevents that? Basically it should be enough to check the current lifecycle-status in `show()` and if it doesn't fit it does nothing, right?

I've already created an extension function for my projects on `ComponentActivity?` (nullable) to reduce boilerplate and adding the lifecycle when *creating* die dialog but as mentioned it's still possibly unsafe when *showing* the dialog later on.

I think, when `lifecycleOwner` is added, this check should be in `show()`. What do you think?

**Comment by afollestad** [comment]
I don't plan on adding something like that. The app should be responsible for not calling `show()` outside of its own lifecycle.

**Comment by hardysim** [comment]
I already thought so. Mainly because one should use `DialogFragment` in the first place to handle the dialog-lifecycle.

But why is reacting to the lifecycle for dismissal in the library?

**Comment by afollestad** [comment]
I think dismissing is a bit different than showing in terms of correctness here. 

At Square, we auto unsubscribe from Rx Observables when views detach. I see it the same way for dialog dismissals. Otherwise it's pretty common to do it from `onPause` of an Activity.

**Comment by alayna101** [comment]
😀🎁

**Comment by alayna101** [comment]
A
