### ISSUE TITLE
Make it easier to modify list items in plain, single, and multi choice lists after creation

### ISSUE THREAD

**Issue by hardysim** [afollestad/material-dialogs#1779]
Using `2.7.0` it does not seem possible to alter the items in the adapter created by `listItemsSingleChoice()` or `listItemsMultiChoice()`.

Following the code, a `SingleChoiceDialogAdapter` or `MultiChoiceDialogAdapter` is added using `customListAdapter()` and I can even get the adapter via `getListAdapter()` but I have no option to add/remove items once created.

My use case would be an async search for bluetooth devices and I want to populate the list with a newly found item when they appear.

---

With the old version of this library this was possible and it should be easy to alter the list even when shown (`RecyclerView` will take care of us, right?).

I've found `DialogAdapter.replaceItems()` but I cannot get it to work when trying to access it like so:

```kotlin
private val sel = object : SingleChoiceListener {
        override fun invoke(dialog: MaterialDialog, index: Int, text: String) {
        [...]
     }
 }

val scanDialog = MaterialDialog(activity).apply {
   listItemsSingleChoice(items = listOf(), selection = sel)
}

(scanDialog?.getListAdapter() as? DialogAdapter<*, *>)?.replaceItems(listOf(), sel)
```

**Comment by afollestad** [comment]
@hardysim you can just call `listItemsSingleChoice` again.

This is the source:
```kotlin
@CheckResult fun MaterialDialog.listItemsSingleChoice(
  @ArrayRes res: Int? = null,
  items: List<String>? = null,
  disabledIndices: IntArray? = null,
  initialSelection: Int = -1,
  waitForPositiveButton: Boolean = true,
  selection: SingleChoiceListener = null
): MaterialDialog {
  val array = items ?: getStringArray(res)?.toList() ?: return this
  val adapter = getListAdapter()

  if (adapter is SingleChoiceDialogAdapter) {
    adapter.replaceItems(array, selection)
    if (disabledIndices != null) {
      adapter.disableItems(disabledIndices)
    }
    return this
  }

  assertOneSet("listItemsSingleChoice", items, res)
  setActionButtonEnabled(POSITIVE, initialSelection > -1)
  return customListAdapter(
      SingleChoiceDialogAdapter(
          dialog = this,
          items = array,
          disabledItems = disabledIndices,
          initialSelection = initialSelection,
          waitForActionButton = waitForPositiveButton,
          selection = selection
      )
  )
}
```

If an adapter is already set, items are updated and the method returns early. The same goes for the multi-choice variant.

**Comment by hardysim** [comment]
Seems working. I was overlooking the `return this`.

One more thing: What about the `@CheckResult`? When I update an existing dialog this way, why do I need to check the result?

**Comment by afollestad** [comment]
Ah yes, good point

**Comment by afollestad** [comment]
I've added an `updateListItems(...)` method that works for any list dialog type for the next release
