### ISSUE TITLE
MaterialDialog's DateTime requireFutureDateTime not reliable

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1781]
**Library Version:** 2.7.0/datetime
 
**Describe the Bug:**

Though setting the parameter `requireFutureDateTime` to true, it is not sure whether the dialog will return a future datetime, e.g. the minute switches during the user is in the dialog, since there is no validation on dialog positive button click.

I'd suggest to move the check for future-datetime's to the onclick event, and display a `Snackbar` to inform the user instead.

**To Reproduce:**
1. Open DateTime Picker dialog
2. Select future datetime (1 min ahead of current datetime)
3. Wait a minute, now the datetime in not in the future anymore.

If you agree with this change, I'll implement it.

**Comment by afollestad** [comment]
A SnackBar wouldn't be an ideal solution, not only because UI placement would be weird, but because that would require the consumer to specify another string that is displayed there. A built-in string in the library would not be translated so that wouldn't be good.

**Comment by guger** [comment]
Do you have a better idea to solve this?
