### ISSUE TITLE
Black action buttons

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1782]
**Library Version:**

2.7.0
 
**Affected Device(s):**
 
OnePlus 5 running Android Pie
 
**Describe the Bug:**

Every dialog that I try to display isn't having colored action buttons

**To Reproduce:**
1. Try to show a dialog with an actionButton

**Expected Behavior:**

The action button should be colored with the app accent color

**Code Example**
```kotlin
fun Activity.getAccountSwitchDialog(showAddAccountButton: Boolean = false): MaterialDialog { 
    val accountList = db.getAll()
    val activeAccountIndex = accountsList.indexOf(db.activeAccount)

    return MaterialDialog(this).show {
	    title(text = "Switch Account")
	    customListAdapter(LoggedUsersAdapter(accountsList, this@getAccountSwitchDialog))

	    if (showAddAccountButton) {
		    positiveButton(text = "ADD ACCOUNT") {
			    startActivity<LoginActivity>()
		    }
	    }
    }
}
```

**Comment by AndreaCioccarelli** [comment]
<a href="https://ibb.co/RztSc96"><img src="https://i.ibb.co/sycPq21/Screenshot-20190414-234330.png" alt="Screenshot-20190414-234330" border="0"></a><br />

**Comment by afollestad** [comment]
@AndreaCioccarelli is your `colorAccent` in your theme set to black?

**Comment by afollestad** [comment]
If so, you can override action button color in your theme https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#widget-color

**Comment by afollestad** [comment]
Oh sorry, not `colorAccent`, `colorPrimary`, per Google Design.

**Comment by AndreaCioccarelli** [comment]
Thanks! I though that the action button color was determined by the `accentColor`.
