### ISSUE TITLE
ProgressBar Dialog

### ISSUE THREAD

**Issue by AhsenSaeed** [afollestad/material-dialogs#1786]
I want to show a progress bar inside the MateriaDialog. Is there any way to do that in new version of library because in previous version I can easily able to do that via setting progress method on MaterialDialog.Builder() class.

Best Regards,
Ahsen Saeed.

**Comment by afollestad** [comment]
Sorry, no - progress dialogs were deprecated by Google and I agree that they should be. You should use non blocking indicators in your UI.
