### ISSUE TITLE
unresolved reference: MaterialDialog

### ISSUE THREAD

**Issue by sandeepkumarmishra354** [afollestad/material-dialogs#1787]
after upgrading gradle `MaterialDialog` is not resolved

**Comment by afollestad** [comment]
There's not enough info here. 

From what version to what version? Are you using Kotlin? Are you using AndroidX?

**Comment by nirav-tukadiya** [comment]
I am facing the same issue after upgrading Gradle to v3.4. I am using Kotlin and AndroidX both.

**Comment by afollestad** [comment]
If you're still experiencing the issue, can you post your `app/build.gradle`?
