### ISSUE TITLE
[datetime] Option to automatically switch to timepicker page after date is selected

### ISSUE THREAD

**Issue by guger** [afollestad/material-dialogs#1788]
**What module does this apply to?**

DateTime

**Description what you'd like to happen:**

Implement an option, which enables support for automatically switching viewpager page to time picker, after the date is selected.
This would be great, especially since the swipe gesture to switch pages does only work in the upper area of the date picker as the calendar view uses the swipe gesture for sliding through months.

**Describe alternatives you've considered:**

Another option would be a next button (e.g. neutral button) which switches the page.

**Comment by jhmacdon** [comment]
Is there a reason this doesn't happen when you select the current day?
