### ISSUE TITLE
MaterialDialog is final - any real reason why not keep the class open ?

### ISSUE THREAD

**Issue by inteist** [afollestad/material-dialogs#1789]
Would be great if the base MaterialDialog would be open and could be extended. 
Thank you.

**Comment by afollestad** [comment]
> By default, all classes in Kotlin are final, which corresponds to Effective Java, Item 17: Design and document for inheritance or else prohibit it. Kotlin designers took this advice very seriously by making all classes final by default.

I see no reason to make the class open - this library is extensible and inheriting from the dialog class does not provide any benefit.

**Comment by inteist** [comment]
In that case would you please advise how one would go about implementing some logic for the `show()` and `dismiss()` methods without being able to override these methods.
We need common functionality for all the class instances invoked on on show and ondismiss.
To give you an example – one particular piece of functionality would be to track whether some dialog is already showing

**Comment by afollestad** [comment]
You could create an extension method or attach to the show listener/dismiss listeners.

E.g., in the code base, this:

```kotlin
  inline fun MaterialDialog.show(func: MaterialDialog.() -> Unit): MaterialDialog {
    this.func()
    this.show()
    return this
  }
```

Enables:

```kotlin
MaterialDialog.show {
    title(R.string.title)
    message(R.string.message)
}
```

**Comment by inteist** [comment]
Thanks, we still did not really move to Kotlin so this was not obvious. Much appreciated.

**Comment by inteist** [comment]
@afollestad maybe it's my lack of deep Kotlin understanding/knowledge but from digging around, and reading the Kotlin docs - you can't override a member method in an extension.
Maybe we can get away with the `show()` method since we call it explicitly but the `dismiss()` method is called implicitly and without overriding the base `dismiss()` method we can't perform what we need when the dialog is dismissed. 

> If a class has a member function, and an extension function is defined which has the same receiver type, the same name is applicable to given arguments, the member always wins

>However, it's perfectly OK for extension functions to overload member functions which have the same name but a different signature:

So while your example works for you and can potentially work for us (we could use a custom show method with a parameter) which would probably make it awkward but workable, I am afraid it would not work for the `dismiss` method. 

I think you are taking the "advice" too literal and probably wrong.

What it says is - in Java the default is open in Kotlin it is reversed. That's it. There's plenty of open classes in Kotlin core. 

Your library has a lot of visual customization but not functional and marking it as final you severely handicapped the ability to add custom logic.

**Comment by afollestad** [comment]
You can't override member functions with extensions, but you can overload them - with a different name or with different arguments like the one above.

I'm valuing composition over inheritance and helps keep the library relatively locked down in favor of extensions. You can't really use any of this library in straight-up Java because most of the functionality exists as extension functions in the core module or extension modules.

**Comment by inteist** [comment]
@afollestad forget Java, even within Kotlin, overloading doesn't do any good if I need to put custom logic in the base `dismiss()` method. An overloaded method is not going to be called whenever the dialog is dismissed is it or am I missing something?

Would you please care to explain how this can be achieved? Let's say for the sake of simplicity I want to add a simple log (print something) whenever a dialog is dismissed. How could I achieve this with overloading? 

The actual use case is more complex of course I am just using the log example for the sake of simplicity.

**Comment by afollestad** [comment]
What do you need to do when it's dismissed? Most things can be done in the dismiss listener, which is pretty standard. It gives you a reference to the dialog, too.

**Comment by inteist** [comment]
@afollestad I need to do tracking of certain state and do something based on that state which if I am placing it dismisslistener (which I do not have to explicitly specify in every dialog configuration by the way) I would need to repeat this code everyplace. It's just wrong approach to put it on DismissListener. On this I am 100% certain.

**Comment by inteist** [comment]
@afollestad I provided a simple use case. Which abstracts a more complicated one. My point was you can't do (at least I don't know how) if you do – please share.  
Putting this log in every ondismiss listener is wrong and you know it.

**Comment by afollestad** [comment]
If you have an extension function that overloads `show()`, you can set a dismiss listener inside of that. Or you could use a `DialogFragment` that wraps your dialog and override `onDismiss` in there.

I am not going to make `MaterialDialog` and its methods open.

**Comment by inteist** [comment]
While I understand it is an open source project and you use your personal time to support it which is commendable so with all due respect:

> If you have an extension function that overloads show(), you can set a dismiss listener inside of that. Or you could use a DialogFragment that wraps your dialog and override fun onDismiss()/fun onCancel() in there.

Does not answer a directly posed question which is supposed to represent the solution. 

> I am not going to make MaterialDialog and its methods open. 
Because... ?  Give me one good reason why :) 

The
 
>I'm valuing composition over inheritance and helps keep the library relatively locked down in favor of extensions/plugins.

is not even applicable. Just like your quote about Kotlin making final the default. Has nothing to do with what we are actually talking and dealing with here.
