### ISSUE TITLE
Discuss: if it is bug on my side or your.

### ISSUE THREAD

**Issue by PetkevichPavel** [afollestad/material-dialogs#1790]
**Library Version:** 2.8.1

**Device:** OnePlus 6T Android 9

**Describe the Bug:**

This bug appears only at the first-time start of the dialog, after the start, I try to choose the first item but the button isn't enabled yet, because of that I choose the second one item. After that button change the availability state to enable and I click on this button for saving the result. But unfortunately, the result isn't properly, because it is the first item, but before I submitted it was the second one.
For better understanding, I uploaded the video on [Google Drive](https://drive.google.com/open?id=13rx4qIztCd5bsIXE74Ry-5qZNWs4zN0m).

**To Reproduce:**
1. Open Dialog (without predefined choose)
2. Choose the first item (button state - disabled)
3. Choose the second item (button state - enable)
4. Click on the button for saving.

And the result should be incorrect.

**Here is my code:**
```
MaterialDialog(this).show {
                title(R.string.car_dialog_fuel_type_title_str)
                listItemsSingleChoice(R.array.FuelType, null, null, getIndexViaString() ?: 0)
                { dialog, index, text ->
                    dialog.positiveButton(R.string.car_choose_dialog_positive) {
                        text.getFuelTypeViaString(this@CarCreateEditActivity)?.let {
                            fuelTypeStringId = it.stringID
                            render(CarCreationModel.RenderFuelType(it))
                        }
                    }
                }
            }
```

**Thank you for your future response and help! Have a nice day/evening!**

**Comment by afollestad** [comment]
The button is appearing because you don't call `positiveButton` until the single choice listener is invoked. This is not a bug in the library.
