### ISSUE TITLE
How to show dialog in new version (java)?

### ISSUE THREAD

**Issue by kingdom2011** [afollestad/material-dialogs#1798]
in version 0.9.6.0 i could easily use below code to show a dialog, now that u have moved to kotlin, i can't use code below and after some searches couldn't find how to do it in new version. 

```
new MaterialDialog.Builder(this)
				.iconRes(R.mipmap.ic_launcher)
				.limitIconToDefaultSize() // limits the displayed icon size to 48dp
				.title("google services")
				.content("use google prompt?")
				.positiveText("agree")
				.negativeText("disagree")
				.checkBoxPrompt("Hello, world!", true, null)
				.show();
```

how is it done with java? what is the replacement for Builder(), i can't find it anymore.

**Comment by afollestad** [comment]
Read the tutorials or look at the sample project.
