### ISSUE TITLE
Bug: in the set up of message inside the basic dialog

### ISSUE THREAD

**Issue by PetkevichPavel** [afollestad/material-dialogs#1799]
**Library Version:** 3.0.0-alpha1
 
**Affected Device(s):** OnePlus 6T with Android 9.0
 
**Describe the Bug:**

Basic dialog: message text won't set up.
It happens after I upgrade to 3.0.0-alpha1.
Below an example of code. 
```
MaterialDialog(this).show {
            cancelable(false)
            title(text = "TEST")
            message(text = "TEST")
            positiveButton(text = positive ?: getString(android.R.string.yes))
            negativeButton(text = negative ?: getString(android.R.string.no))
        }
```

Result:
![IMAGE 2019-05-14 13:00:17](https://user-images.githubusercontent.com/12551722/57692902-3aef6080-7648-11e9-88bb-381d790b83d5.jpg)

P.S: Also when I am using the string.id instead of a string, the same error occurs.

**Comment by afollestad** [comment]
Hmmm, I'm unable to reproduce.

<img width="301" alt="Screen Shot 2019-05-14 at 11 59 04 AM" src="https://user-images.githubusercontent.com/1820165/57724481-b862a300-763f-11e9-8264-f146fcd43981.png">

**Comment by PetkevichPavel** [comment]
Hello @afollestad, thank you for your reply. I don't know why you can't reproduce it, nevertheless I checked it one more time and the result is the same...

Here is the very simple dialog creation:
<img width="333" alt="Screenshot 2019-05-15 at 00 08 11" src="https://user-images.githubusercontent.com/12551722/57735764-0a3e1400-76a6-11e9-801c-8c053670acfd.png">

Here is the result on the android(OnePlus 6T,  Pixel 3 - Android Pie):
<img width="291" alt="Screenshot 2019-05-15 at 00 09 04" src="https://user-images.githubusercontent.com/12551722/57735781-15913f80-76a6-11e9-8c9b-8da8c9b3f06c.png">

I checked one more Version and I using the latest one: 3.0.0-alpha1.

Tomorrow morning I will check it one more time, maybe I missed something...
One more big thx!

**Comment by afollestad** [comment]
Hmm, yeah I'm not sure. I test primarily on a Pixel 3 XL with Android Q.

**Comment by afollestad** [comment]
@PetkevichPavel your theme might be making the message text white? That's the only thing I can think of. Try specifying `md_content_color` in your Activity theme (https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#text-color).

**Comment by PetkevichPavel** [comment]
@afollestad Yesterday I tested on my own project and all works properly. This project isn't mine and it did not occur me that they can set `textColorSecondary` as white...
Nevertheless, you're right, the problem was in styles not in your library. 
Sorry for complications.
