### ISSUE TITLE
ButtonCallback() and SimpleCallback()

### ISSUE THREAD

**Issue by KDB223** [afollestad/material-dialogs#180]
What's the difference between using `MaterialDialog.ButtonCallback()` and `MaterialDialog.SimpleCallback()`? They both seem to satisfy the same purpose.

**Comment by afollestad** [comment]
ButtonCallback optionally can handle all 3 actions, any combination of them. Simple callback was just the positive action.

**Comment by afollestad** [comment]
I forgot to mention that the non ButtonCallbac interfaces are deprecated
