### ISSUE TITLE
Can't Resolve MaterialDialog

### ISSUE THREAD

**Issue by Younes-Charfaoui** [afollestad/material-dialogs#1804]
**Library Version:**
3.0.0-beta2
 
**Describe the Bug:**
After adding the library dependency to my project, I couldn't use the MaterialDialog, no class exists, I'm using androidx.

**To Reproduce:**
Just add the dependency in the gradle file.

**Expected Behavior:**
To use the Library.

**Comment by afollestad** [comment]
Unable to repro, there are also two duplicate issues.

**Comment by 972223177** [comment]
me too

**Comment by afollestad** [comment]
There has to be an issue with your Gradle setup.

**Comment by Younes-Charfaoui** [comment]
No, All the other library works just fine, except yours, I'm using AndroidX,  it can be the reason I think

**Comment by afollestad** [comment]
I'm using it in multiple production apps with no problems.

**Comment by 972223177** [comment]
> No, All the other library works just fine, except yours, I'm using AndroidX, it can be the reason I think
Maybe you missed this one
 implementation 'com.afollestad.material-dialogs:core:3.0.0-beta2'

**Comment by Younes-Charfaoui** [comment]
yes, I've added this dependency.
