### ISSUE TITLE
File & folder Chooser permissions on API 19 and Up

### ISSUE THREAD

**Issue by eakteam** [afollestad/material-dialogs#1805]
Hello there, thanks for this great library :)
There are many app out there (one is mine) which app's permissions are very strict & important !

Referring to Android official documentation when an application request files or folder into its `external file directory`, permissions are not required since `Android Kitkat (Level 19)`.

> Starting in Build.VERSION_CODES.KITKAT, no permissions are required to read or write to the returned path; it's always accessible to the calling app. This only applies to paths generated for package name of the calling application. To access paths belonging to other packages, Manifest.permission.WRITE_EXTERNAL_STORAGE and/or Manifest.permission.READ_EXTERNAL_STORAGE are required.

But regardless of this we are forced to use permissions anyway...

So, i think it is better to just to add an if-else to check for requested path, and if it's the path of calling app `don't request Read Permission` (or `Write Permission` for folder creation)

Thanks, best regards

**Comment by afollestad** [comment]
I'm not really sure what you mean. If you're using an OS below Android Marshmallow (API 23), then the permission check should always return true as long as you have the permission declared in your manifest. There is no special case that Material Dialogs should be handling there - if it's returning false that's an OS bug.

**Comment by eakteam** [comment]
@afollestad , thanks for your reply. Sorry for my low English, maybe this is why you don't understand me well. I will try to write a use case for e.x if we want to open file chooser like following

```
MaterialDialog(this@paneli_kryesor).show {
                    fileChooser(initialDirectory = getExternalFilesDir(null)!!) { _, file ->

                    }
                } 
```
it always check for permission access, and if not found permissions, it crash with message "You should grant read permission first", but in fact as i said in first message according to Android Documentation, permissions are not required for Read & Write access to App's External File Dirs since API 19

So, i mean this library better to make a check to see if the path belongs to the app dir itself, and if so, skip permission check.

If you still don't understand my low English, i will try to attach a very sample project to make you understand better. 

This is very important in some cases when we need this library support without permissions, if only call app's internal/external directories

**Comment by afollestad** [comment]
But again, KitKat doesn't use runtime permissions. So the permission check that Google provides should always return true on KitKat. I don't want to add condition special cases for API 19 in my code.

**Comment by eakteam** [comment]
@afollestad , you are still not understanding me. Runtime permissions required from Android 6 and Up. And i said from Android 16 (KitKat) and Up permissions are not required for App internal or external directories. You don't have to add special condition. Just you should check if the path is about app's directory just skip. If it is not directory of app you can request as normal.

If you have to open a chooser within app private directory or app's external directory no need for permissions. Are you understanding me or not ?

If you open a chooser in that place no need for permission check. Anyway i have to edit this lib myself but it is very weird that you are not getting me

**Comment by afollestad** [comment]
That's a special case. If you do not do a check for the app directory, a check would have to be done later if the user goes out of an app directory.

You don't need to fork the library, just make a custom view dialog.
