### ISSUE TITLE
Input box background color

### ISSUE THREAD

**Issue by victorlapin** [afollestad/material-dialogs#1806]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Input

**Description what you'd like to happen:**

When you define input style, you're using null as box background color. This allows material theme to set the color. However, dialog background color is different from the one set by theme, this is seen clearly when you set dark theme for your app.
Please consider using android:color/transparent as boxBackgroundColor.

**Comment by afollestad** [comment]
Not 100% sure what you mean - setting it to null avoids having a rectangular background or some other odd behavior that shows up in newer versions of Material Components. Setting it to null allows the input field to only show the colored underline, and the color matches the color of the Activity theme that opened the dialog.

**Comment by victorlapin** [comment]
Activity theme, yes. But not dialog background.

**Comment by afollestad** [comment]
The dialog background is light or dark automatically based on your Activity theme. If the input underline isn't a good color you can override it as stated in the documentation.

**Comment by victorlapin** [comment]
![Screenshot_20190531-182623](https://user-images.githubusercontent.com/8329104/58716560-f7c81800-83d1-11e9-837b-fd87443b1db7.jpg)

**Comment by victorlapin** [comment]
Here, box background color matches activity theme (dark), but dialog background is different. It can be seen with dark theme only, because with light one both are white.

**Comment by afollestad** [comment]
As I said, you can globally set widget colors for this library from your Activity theme.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#theming

**Comment by victorlapin** [comment]
Again, if I set md_background_color to some orange color, the dialog itself will be orange, and box background will be white/dark (matching activity theme). And if you set box color to transparent, it will match dialog color.
![Screenshot_2019-05-31-18-42-33-176_com victorlapin flasher debug](https://user-images.githubusercontent.com/8329104/58717633-542c3700-83d4-11e9-9831-7a68c227e40b.png)

**Comment by afollestad** [comment]
Ahhhh, got it - missed the first image when viewing this thread from my phone.
