### ISSUE TITLE
Help wanted: Sample in Android Java

### ISSUE THREAD

**Issue by ianeinser** [afollestad/material-dialogs#1809]
Hi,
i appreciate if you can provide me the java version of the kotlin sample provided..

bottomsheet_info.setOnClickListener {
      MaterialDialog(this, BottomSheet(WRAP_CONTENT)).show {
        title(R.string.useGoogleLocationServices)
        message(R.string.useGoogleLocationServicesPrompt)
        positiveButton(R.string.agree)
        negativeButton(R.string.disagree)
        debugMode(debugMode)
      }
    }

on top of it, i plan to include a function call and wonder where i can put the function call?

**Comment by afollestad** [comment]
Sorry, the extension modules won't work in Java, cause they are built with extension functions.

**Comment by ianeinser** [comment]
> Sorry, the extension modules won't work in Java, cause they are built with extension functions.

Thanks for the confirmation.. Good work any way
