### ISSUE TITLE
Reallow custom colours programmatically

### ISSUE THREAD

**Issue by AllanWang** [afollestad/material-dialogs#1813]
**What module does this apply to?**

core

**Description what you'd like to happen:**

I come from the 0.x.x.x versions, and I'm sure requiring theme attributes was a big decision for 2.x and beyond. However, what about projects that allow users to use their own themes?

It is definitely in the minority, but even if we remain with the material palette, it would be easier to set colours on the fly rather than generate all possible material themes and bundle it within styles.

Would there be a chance to reconsider enforcing colours from attributes only?

**Describe alternatives you've considered:**

Forcing attributes removes the ability to have custom themes. Understandably, custom themes are not restricted by the material palette, but even if we support just the palette it will require us having to pre-generate many styles.

**Comment by afollestad** [comment]
Sorry, no - there's been discussions in other issues about this. 

I want to enforce that apps use Activity themes, and I don't want to have any reflection in this code base anymore.

**Comment by AllanWang** [comment]
Oh I see.

https://github.com/afollestad/material-dialogs/issues/1725#issuecomment-463750082

By reflection you meant theming other components like the input bar etc
