### ISSUE TITLE
Background and statusbar should be transparent with bottom sheets

### ISSUE THREAD

**Issue by Ivanaxa228** [afollestad/material-dialogs#1815]
**Library Version:**
3.0.0-rc3
 
**Affected Device(s):**
Android 4.3
Android >= 5.0
 
**Describe the Bug:**
Android 4.3: when I'm opening standard MaterialDialog, background is translucent (which is correct in my opinion):

![ss](https://user-images.githubusercontent.com/30559158/59150897-0ccc2900-8a1a-11e9-9dae-38ac0f70d00b.png)

But if I'm opening BottomSheetDialog, background is fully transparent:

![device-2019-06-08-200416](https://user-images.githubusercontent.com/30559158/59150901-12c20a00-8a1a-11e9-9641-47378539a5c2.png)

Android >= 5.0: when I'm opening standard MaterialDialog, status bar is translucent:

![material](https://user-images.githubusercontent.com/30559158/59150907-253c4380-8a1a-11e9-9df0-6bdee65d85d7.png)

But if I'm opening BottomSheetDialog, status bar turns to white color:

![bottom](https://user-images.githubusercontent.com/30559158/59150916-41d87b80-8a1a-11e9-949f-5069ad256a54.png)

(I don't change background and statusbar color in my code)

**Expected Behavior:**
Android 4.3: Background color of BottomSheetDialog should be translucent, like in MaterialDialog
Android >= 5.0: Statusbar color should be translucent, like in MaterialDialog

**Comment by afollestad** [comment]
Should be resolved in rc4
