### ISSUE TITLE
where is the progressbar Dialog? is that not support?

### ISSUE THREAD

**Issue by caoyanglee** [afollestad/material-dialogs#1816]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Core? Input? Files? Color?
Core

**Description what you'd like to happen:**

A clear description if the feature or behavior you'd like implemented.

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by afollestad** [comment]
They were intentionally left out of version 2.+

You should prefer inline progress indicators that don't block the whole screen. This is in Google's design guidelines as well, which is why their `ProgressDialog` is deprecated.

**Comment by caoyanglee** [comment]
txs~
