### ISSUE TITLE
CheckResult annotation on checkBoxPrompt

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#1817]
The `checkBoxPromt` function has a `@CheckResult` annotation, unless all the other builder methods.
As the function mutates the builder, this is not necessary and leads to false positives.

![image](https://user-images.githubusercontent.com/743462/59245510-6e0e1b00-8c19-11e9-86f0-511ba34afdcf.png)

**Comment by afollestad** [comment]
Resolved in rc4
