### ISSUE TITLE
Blue background in API 21

### ISSUE THREAD

**Issue by tsuharesu** [afollestad/material-dialogs#1818]
**Library Version:**

3.0.0-rc3
 
**Affected Device(s):**
 
Emulator API 21
 
**Describe the Bug:**

There is a blue tint when opening a dialog or a bottom sheet. Bottom sheets are also showing the latest bottom sheet opened behind the current one.

![Screenshot_1560253634](https://user-images.githubusercontent.com/808267/59269496-9865d580-8c25-11e9-8a43-f034e6512b8c.png)
![Screenshot_1560253649](https://user-images.githubusercontent.com/808267/59269504-9d2a8980-8c25-11e9-8aec-99531395722a.png)

**To Reproduce:**
Run the sample from this repository in an API21 device. I only have the emulator.

**Comment by afollestad** [comment]
Should be resolved in rc4
