### ISSUE TITLE
Unable to modify properties of elements inside a CustomView (Fragment)

### ISSUE THREAD

**Issue by idkwhatusernameuse** [afollestad/material-dialogs#1819]
**Library Version:**

3.0.0-rc3 (material-dialogs core/bottomsheets)
 
**Affected Device(s):**
 
Moto G5 Plus with Android 8.1
 
**Describe the Bug:**

Can't modify a property of an element inside a CustomView (showing a fragment inside a Dialog/BottomSheet)

**To Reproduce:**
1. Create a fragment (and some elements to test the behavior)
2. Open a Dialog/BottomSheet with a CustomView (the view being the fragment)
3. Modify a property of an element (for example, the text on a TextView or the image on an ImageView) inside the class of the Fragment.

I've used this code to test the behavior (inside the `override fun onCreateView`):
`imageView.setImageResource(R.drawable.ic_launcher_background)` (for an image)
`textView.text = "test"` (for text)

**Expected Behavior:**

Show the modifications after doing them (for example, show the new text/image)

**Comment by afollestad** [comment]
You access views in the dialog custom view via `dialog.getCustomView()`. There is an example of this _working_ in the sample project.
