### ISSUE TITLE
Dialog closes on orientation changes

### ISSUE THREAD

**Issue by HeinrichReimer** [afollestad/material-dialogs#182]
When you rotate the device the dialog gets closed. Using `DialogFragment` instead of `AlertDialog` as basis would fix it.

**Comment by afollestad** [comment]
Well, MaterialDialog is intended to act like an AlertDialog which is why it inherits from that. Google gives users the choice on whether or not they want to embed dialogs in a DialogFragment. It's very easy to do with the existing MaterialDialog implementation.

**Comment by HeinrichReimer** [comment]
Maybe adding a default DialogFragment wrapper would be great option.

**Comment by HeinrichReimer** [comment]
I can post a little pull request today.

**Comment by afollestad** [comment]
I just don't think it's very necessary.

There's also an example of using the library with DialogFragments in the sample project (for the folder chooser).

**Comment by HeinrichReimer** [comment]
Ok, thank you!
BTW, the folder chooser doesn't store the current folder.
