### ISSUE TITLE
Integrate afollestad/date-picker

### ISSUE THREAD

**Issue by LossyDragon** [afollestad/material-dialogs#1820]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.0.0-rc4
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
and Pixel XL 10 (Beta)
 
**Describe the Bug:**

The Date window within a bottom sheet does not fill the dialog up all the way, width wise. 

Time Dialog is fine.

![Capture](https://user-images.githubusercontent.com/4994318/59806824-63a7ed00-92bb-11e9-8f31-edb0b5405d4c.PNG)

**To Reproduce:**
1. Implement the date/time dialog in a bottom sheet or install the sample app.
2. Open said dialog. 
3. Observe :)

**Expected Behavior:**

The Date window should fill the dialog up as much as it can.

Thanks!

**Comment by afollestad** [comment]
Yes, my current plan is to integrate my new date picker library. Google's is not responsive.

**Comment by guger** [comment]
What about the new material date pickers of the material design library?

**Comment by guger** [comment]
> What about the new material date pickers of the material design library?

https://material.io/design/components/pickers.html

That would also be the easiest way to stay up-to-date with the material design specs.
