### ISSUE TITLE
Theme attributes don't work with MaterialComponents themes

### ISSUE THREAD

**Issue by artnest** [afollestad/material-dialogs#1821]
**Library Version:**

3.0.0-rc4

**Describe the Bug:**
 
Theme attribute `md_corner_radius` doesn't work when app theme is inherited from `Theme.MaterialComponents.*`

**To Reproduce:**
1. Create an app theme `<style name="Theme.App" parent="Theme.MaterialComponents.Light"></style>`
2. Add `<item name="md_corner_radius">16dp</item>` to the theme.

**Expected Behavior:**

Expected behavior is that corner radius is applied to dialogs. Instead, it doesn't work at all. If corner radius is set in code via `cornerRadius()` method applied to MaterialDialog instance, it does work.

I guess other themes attributes also don't work.

**Comment by afollestad** [comment]
Hmmm. The parent theme should not make a difference.

**Comment by afollestad** [comment]
The sample project uses MaterialComponents so I suspect something else is wrong on your end.

**Comment by yuzhiqiang1993** [comment]
I've tried to use this theme  `Theme.MaterialComponents.Light.Bridge` many times and it's fine
