### ISSUE TITLE
Please Refer Java Implementation of this Updated Lib.

### ISSUE THREAD

**Issue by CHRehan** [afollestad/material-dialogs#1822]
Hy Afollestad,
 I want to use your lib in my android Java Project but I am unable to find the Java implementation of your lib, Kindly post it or if it already has please share a link or some sample.

**Comment by afollestad** [comment]
There is not one.

**Comment by PaulWoitaschek** [comment]
@CHRehan You can just use it in java:
https://kotlinlang.org/docs/reference/java-interop.html
