### ISSUE TITLE
Get Visible section as a view

### ISSUE THREAD

**Issue by BigGitWorld** [afollestad/material-dialogs#1824]
Hello.
I'm using this library and it's working fine.
I want to be able to get visible section of MaterialDialog layout as a view.
because I want to use MaterialShowCase library with it to show some help to my own users. So I have to highlight only visible section of MaterialDialog layout NOT full screen.
When I used `materialDialog.getView()` , it gives me full screen not visible region.
So my question is :
How can I get only visible section of MaterialDialog screen not full screen?
Best wishes

**Comment by afollestad** [comment]
I'm not aware of any way to do that.
