### ISSUE TITLE
Date durations

### ISSUE THREAD

**Issue by kaushalyap** [afollestad/material-dialogs#1827]
**What module does this apply to?**

`datetime`

**Description what you'd like to happen:**

A dialog that allows to pick time duration (ex: countdown timer)

**A clear description if the feature or behavior you'd like implemented.**
 
-  Like this : https://github.com/svenwiegand/time-duration-picker
-  In addition add support to change the time by using spinners for hours, minutes, second scales. ex: see left side in this [image](https://i.stack.imgur.com/H4gJ0.jpg)
-  Allow to disable seconds scale

**Describe alternatives you've considered:**

https://github.com/svenwiegand/time-duration-picker

**Comment by afollestad** [comment]
This lib will support date durations when my date-picker lib does, but time duration is not planned.

**Comment by kaushalyap** [comment]
@afollestad this not about date duration but about time duration's. see https://github.com/svenwiegand/time-duration-picker

**Comment by afollestad** [comment]
Yes, 
>  but time duration is not planned.
