### ISSUE TITLE
Custom views need access to md_dialog_frame_margin_horizontal and/or automatic padding option

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#1829]
**Library Version:**

3.0.2
 
**Describe the Bug:**

Custom views do not apply correct padding around them (any more since v3? not sure about this currently) + `md_dialog_frame_margin_horizontal` is marked as private although I need this dimension for custom views.

**Expected Behavior:**

Check this old issue: https://github.com/afollestad/material-dialogs/issues/1446

I would expect that the above dimension is public or that I get a flag like described in my old issue

**Comment by afollestad** [comment]
Since `md_dialog_frame_margin_horizontal` is _always_ 24dp and will always be unless the guidelines change, I don't feel either of these things are necessary. You'd be safe coping your own version of this resource to your app.

**Comment by MFlisar** [comment]
Why did you remove the automatic content padding? What does speak against a builder flag like `applyHorizontalPadding`? You already have one to disable vertical padding anyways...

And copying things goes against my programmers nature - private resources are accessible anyways currently, but still, I don't see any reason why you can't mark it as public as it is really a necessary dimension for every custom view dialog...

**Comment by PaulWoitaschek** [comment]
@afollestad Thanks for adding this back, its way simpler than having to this manually for every custom view.

**Comment by mrhuo** [comment]
https://github.com/afollestad/material-dialogs/issues/1832#issuecomment-913123895
