### ISSUE TITLE
neutral text on "single choice" mode

### ISSUE THREAD

**Issue by vnguyen972** [afollestad/material-dialogs#183]
Hi, so maybe I'm overlooked but how do you handle "neautral" button in he "multi choice " or "single choice"... mode?

Let's say.. if the list was empty and I want to have a neutral button to take users to the "add" panel .. so I want to utilize the "neutral" button for this... is it possible?

I only see itemsCallbackSingleChoice but can I also implement callBack methods to detect "onNeutral"???

Thanks.

**Comment by afollestad** [comment]
Is `callback` not working for you? There's multiple examples of how you handle button callbacks in the README and sample.

**Comment by vnguyen972** [comment]
Yes.. callback work for me.. on none list dialog... but in the case where there are choices like list (either single or multiple choices).. example says we have to implement itemsCallbackSingleChoice.. my question was would it still work if I also implement callBack??? I guess i can just try it ..but I thought it'd be quicker if someone knew :).. 
Thanks.

**Comment by afollestad** [comment]
I don't know off the top of my head, but there's no reason it wouldn't work as far as I know
