### ISSUE TITLE
Cannot resolve symbol md_widget_color

### ISSUE THREAD

**Issue by kaushalyap** [afollestad/material-dialogs#1831]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

core:3.1.0
 
**Describe the Bug:**
 Android Studio lint error in styles.xml, Cannot resolve symbol md_widget_color, cannot run the app

**To Reproduce:**
1. Just paste  following to styles.xml
```
<style name="AppTheme.Custom" parent="Theme.AppCompat">
  <item name="md_widget_color">@color/your_color</item>
</style>
```

**Expected Behavior:**
Item name `md_widget_color` should be identified by the IDE, just like `md_corner_radius`

**Comment by afollestad** [comment]
Oh, that's legacy docs from pre-2.0/3.0 versions. That attribute no longer exists.

You could use the `android:colorControlActivated` attribute if you really need to change the color of input fields in your app.

**Comment by kaushalyap** [comment]
I want to change the selected color of  radio button, but using `android:colorControlActivated` does not change it, it still uses accent color
