### ISSUE TITLE
Scrollable custom view - bottom padding

### ISSUE THREAD

**Issue by dejandobnikar** [afollestad/material-dialogs#1834]
Hi,
thanks for your effort developing this library.

I found a behaviour that I believe should be different.

**Library Version:**

3.1.0
 
**Describe the Bug:**

Adding custom view with flags `scrollable = true, noVerticalPadding = true` adds bottom padding of `24dp`. This is especially noticeable if you don't add positive/negative buttons.

**Expected Behavior:**

DialogScrollView with zero bottom padding, if `noVerticalPadding = true`.

Is there a way to control this?

At the moment, I am using:
```kotlin
dialog.view.findViewById<View>(R.id.md_scrollview_content)
    ?.apply { setPadding(0, 0, 0, 0) }
```

**Comment by afollestad** [comment]
@dejandobnikar can you add a screenshot showing which padding specifically you're removing?

**Comment by dejandobnikar** [comment]
![dialogs](https://user-images.githubusercontent.com/8808636/62924335-29853400-bdb0-11e9-939b-6a41dba95e8f.jpg)

Sorry for delay.
I am removing additional bottom padding you see on the right.
