### ISSUE TITLE
BottomSheetDialog's setCanceledOnTouchOutside doesn't work

### ISSUE THREAD

**Issue by ti4n1993** [afollestad/material-dialogs#1835]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.1.0
 
**Affected Device(s):**
 
Samsung S10
 
**Describe the Bug:**

A clear description of what is the bug is.

when I set BottomSheetDialog's setCanceledOnTouchOutside(false) and setCancelable(false) , it still dismiss when I click outside of the dialog

**Comment by afollestad** [comment]
@ti4n1993 you should be using the fluent versions of those methods, that do not begin with `set`, as a workaround.

I'm going to fix it so the non-Material Dialogs methods work as well.

**Comment by ti4n1993** [comment]
@afollestad I tried,but It doesn't works either

**Comment by HamzaSellami** [comment]
Any news about, this when i try the following code: the dialog is still dismissing ! 

```
dialog.cancelable(false)  
dialog.cancelOnTouchOutside(false)
```
