### ISSUE TITLE
Ability to pass literal Drawables where only resource IDs are accepted now

### ISSUE THREAD

**Issue by KevinPosim** [afollestad/material-dialogs#1838]
All my vector drawables are black. When I run in my dark theme I would like them to appear in white.

For the rest of my app I apply a tint to the black vectors - i.e. for the menu system. Since I can only pass a resource ID to the dialog it would be nice there was support for passing a drawable. 

Would rather not double up all the vector drawables - one white and one black - as that gets to be a maintenance nightmare. Similar to how you allow string ID vs. actual string for title and message.

**Comment by afollestad** [comment]
@KevinPosim where exactly are you missing this ability? You can already pass a literal drawable to `.icon(...)` and other methods now

**Comment by KevinPosim** [comment]
You are correct, I figured out how to do this. Missed seeing how to do icon(null, drawable). Don't think this is discussed in the sample code. Might be nice to add a reference to this handy feature.

**Comment by afollestad** [comment]
It is - e.g. https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#adding-an-icon

**Comment by afollestad** [comment]
You wouldn't pass null, but rather use named parameters.
