### ISSUE TITLE
Custom views with a background color break corner radius

### ISSUE THREAD

**Issue by whoyawn** [afollestad/material-dialogs#1840]
**Library Version:**

'com.afollestad.material-dialogs:core:3.1.0'
 
**Affected Device(s):**
 
Google Pixel 2 with Android 9.0
 
**Describe the Bug:**

The top of the dialog does not have the correct radii

![image](https://user-images.githubusercontent.com/15709918/61410006-4d7c5500-a898-11e9-9fe3-ebe224d21bbd.png)

**To Reproduce:**
1. Change the sample project method `showCustomViewDialog` accordingly:

```kotlin
  private fun showCustomViewDialog(dialogBehavior: DialogBehavior = ModalDialog) {
    val dialog = MaterialDialog(this)
      .customView(
          R.layout.test_custom_view, 
          scrollable = true,
          horizontalPadding = false, 
          noVerticalPadding = true
       ) // Turn off padding
      .lifecycleOwner(this@MainActivity)
      .debugMode(debugMode)
      .cornerRadius(16f)

    dialog.show()
  }
```

2. Create a test layout with a ScrollView as the root and set the item backgrounds to some color:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <TextView
            android:id="@+id/textView6"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/primary"
            android:text="TextView" />

        <TextView
            android:id="@+id/textView7"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="TextView" />

    </LinearLayout>
</ScrollView>
```
3. Run the app and click on the "Custom View" button

**Expected Behavior:**

The top should have the corner radius set to 16dp.

**Comment by whoyawn** [comment]
Update: this actually is not ScrollView specific. I modified the sample code to this and got the same error:

![image](https://user-images.githubusercontent.com/15709918/61410705-9ed91400-a899-11e9-928c-df9862537cd1.png)

`MainActivity.showCustomViewDialog`:

```
  private fun showCustomViewDialog(dialogBehavior: DialogBehavior = ModalDialog) {
    val dialog = MaterialDialog(this, dialogBehavior).show {
      // title(R.string.googleWifi) // COMMENT THIS OUT
      customView(R.layout.custom_view, scrollable = true, horizontalPadding = true, noVerticalPadding = true) // SET noVerticalPadding TO true
      
      ....

      cornerRadius(16f)
    }
```

`custom_view.xml`

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/primary"
    android:orientation="vertical">
...
<LinearLayout/>
```

**Comment by whoyawn** [comment]
```  private fun showCustomViewDialog(dialogBehavior: DialogBehavior = ModalDialog) {    val dialog = MaterialDialog(this, dialogBehavior).show {      // title(R.string.googleWifi)      customView(R.layout.custom_view, scrollable = true, horizontalPadding = true, noVerticalPadding = true)            ....      cornerRadius(16f)    }```

**Comment by whoyawn** [comment]
Also note that even without the `title` property set, the corner radius works ONLY if you do not set a custom background:

![image](https://user-images.githubusercontent.com/15709918/61411988-84546a00-a89c-11e9-91a9-e5caa4208750.png)

**Comment by joyceHong0524** [comment]
So you didn't get the answer yet, right? @afollestad
