### ISSUE TITLE
How to control soft input mode

### ISSUE THREAD

**Issue by maurobanze** [afollestad/material-dialogs#1844]
**Library Version:**

3.1.0
 
**Affected Device(s):**
 
Testing on Huawei Mate 9 Pro with Android 9
 
**Expected Behavior:**
I have a dialog with BottomSheet behaviour. I set a `EditText` to it using `input()`.
When I show the dialog, the soft keyboard immediately shows, which moves the dialog to the top as the keyboard is drawn below it.

I want to:
1. Prevent soft keyboard from automatically opening when dialog with input is shown.
2. Change the drawing behaviour so that the keyboard is drawn on top of the dialog (overlaying it), rather than below it. 

**Describe the Bug:**
By reading Window docs and stackoverflow, objective 1 seem to be achievable by acquiring window reference and setting its soft input mode as below:
`val dialog = MaterialDialog(this, BottomSheet())
dialog.window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN)
`
However, the above line does not work, as the soft keyboard still shows upon dialog showing.
Additionally, objective 2 seems achievable by the same method call, just including another flag.

Is this behaviour correct, and if so, how else can I achieve my objectives?

**To Reproduce:**
1. Create a dialog with `BottomSheet` behaviour
2. Include an input, by calling `dialog.input()`
3. Show dialog by calling `dialog.show()`. Soft keyboard automatically shows.

Thank you very much

**Comment by afollestad** [comment]
@maurobanze `MaterialDialog` intentionally overrides the soft input mode when `show()` is called:

https://github.com/afollestad/material-dialogs/blob/a2c743b15a3d4f37983b9e39c9fdb3656b0531a6/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.kt#L367

It's always set to `SOFT_INPUT_ADJUST_RESIZE `:

https://github.com/afollestad/material-dialogs/blob/a2c743b15a3d4f37983b9e39c9fdb3656b0531a6/core/src/main/java/com/afollestad/materialdialogs/DialogBehavior.kt#L120
https://github.com/afollestad/material-dialogs/blob/a2c743b15a3d4f37983b9e39c9fdb3656b0531a6/bottomsheets/src/main/java/com/afollestad/materialdialogs/bottomsheets/BottomSheet.kt#L173

---

You could successfully override it like you were attempting to do above but it needs to be from the `onShow` callback which is invoked _after_ the code above:

```kotlin
val dialog1 = MaterialDialog(this).show {
   onShow { it.window.setSoftInputMode(...) }
}
val dialog2 = MaterialDialog(this)
    .onShow { it.window.setSoftInputMode(...) }
    .show()
```

---

You could even write an extension to make it more reusable:

```kotlin
fun MaterialDialog.overrideSoftInputMode() = apply {
    onShow { it.window.setSoftInputMode(...) }
}

// usage examples:
MaterialDialog(this).show {
    overrideSoftInputMode()
}
MaterialDialog(this)
    .overrideSoftInputMode()
    .show()
```

**Comment by malwinder-s** [comment]
@afollestad That didn't worked.

I tired:
```
MaterialDialog(this).onShow {
            it.window.setSoftInputMode(SOFT_INPUT_STATE_ALWAYS_HIDDEN)
        }.show { ... }
```
