### ISSUE TITLE
Add posibility to change color of dialog elements via code

### ISSUE THREAD

**Issue by Kolyall** [afollestad/material-dialogs#1846]
**What module does this apply to?**

Core

**Description what you'd like to happen:**

Add posibility to change color of dialog elements(title. message, buttons) like it was at prev ver.:
```
 builder
                    .titleColorRes(/*colorResId*/)
                    .backgroundColorRes(/*colorResId*/)
                    .positiveColorRes(/*colorResId*/)
```

**Comment by afollestad** [comment]
I intend to keep theming static because at a certain point reflection is needed. Theming should be defined in your styles.xml.

**Comment by Kolyall** [comment]
@afollestad Can you add a toturial to readme file how to define different themes for different dialogs on one activity?

**Comment by afollestad** [comment]
That's not possible.

https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#theming

**Comment by afollestad** [comment]
Although technically you could probably pass a `ContextThemeWrapper` to the constructor of `MaterialDialog`, but generally your dialogs should be consistent with your Activity theme.

**Comment by Kolyall** [comment]
I have 2 dialogs on one activity: 
First: "Add an item to chart?" With green positive btn "Add"
Second "Remove the item from chart?" With red posivive btn "Remove"
So with prev. ver. of the lib it was possible, but with current it's not.

**Comment by afollestad** [comment]
Oh, well a workaround for that could be something like:
```kotlin
val dialog = MaterialDialog(this)
...

dialog.onShow { dialog.getActionButton(POSITIVE).setTextColor(Color.RED) }
```

**Comment by Kolyall** [comment]
@afollestad then... how to change also title color these two dialogs?

**Comment by afollestad** [comment]
The above. Pass different colors.

**Comment by Kolyall** [comment]
@afollestad there is no any method to change color of TITLE  of dialog via code

**Comment by afollestad** [comment]
Oh, no. That's intentional. Material Guidelines should be followed which is what the library enforces.

**Comment by Kolyall** [comment]
Thank you for your time. Have a nice day.

**Comment by Kolyall** [comment]
@afollestad I tried to set color by using, but it doesn't change color of the btn: 
fun MaterialDialog.positiveButtonColor(@ColorRes colorRes: Int) = apply {
   val color = ContextCompat.getColor(context, colorRes)
   onShow { dialog.getActionButton(POSITIVE).setTextColor(color) }
}


MaterialDialog(this).show {
    positiveButtonColor(R.color.some_color)
}
