### ISSUE TITLE
How to select files and folders at the same time ?

### ISSUE THREAD

**Issue by rene-dohan** [afollestad/material-dialogs#1849]
*Please consider making a Pull Request if you are capable of doing so.*

I will consider if I see there's interest and also no other option for me.

**What module does this apply to?**

Files

**Description what you'd like to happen:**

Would like to be able for user to select file or folder so files should be visible but user can just select file or unselect by clicking elsewhere so if he press ok I get folder where he is and I know app will create new file if folder was selected or will overwrite file if file was selected.

**Describe alternatives you've considered:**

My alternative is to look at sources and implement extension by myself by mostly duplicating existing code in material-dialogs-files.

**Comment by afollestad** [comment]
Unfortunately I don't currently intend to allow a file or a folder to be selected from the same dialog instance. Only selecting a file from a file chooser or a folder from a folder chooser.
