### ISSUE TITLE
Ability to set a selector to a specific button

### ISSUE THREAD

**Issue by yazeed44** [afollestad/material-dialogs#185]
Hello,

This picture is a good example:

![Screenshot](http://www.androidheadlines.com/wp-content/uploads/2014/11/2014-11-02-16.45.40-e1414955592422.png)

**Comment by afollestad** [comment]
Good idea, I'll try to implement this when I have a bit of time

**Comment by afollestad** [comment]
This will rely on this issue being fixed: https://github.com/afollestad/material-dialogs/issues/191

**Comment by afollestad** [comment]
This is now available in release 0.6.1: https://github.com/afollestad/material-dialogs/releases/tag/v0.6.1

See the 'Themed' dialog in the sample for an example of how it's done.
