### ISSUE TITLE
How to Create a progress Dialog?

### ISSUE THREAD

**Issue by sjqnice** [afollestad/material-dialogs#1850]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Core? Input? Files? Color?

**Description what you'd like to happen:**

A clear description if the feature or behavior you'd like implemented.

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by afollestad** [comment]
It's intentionally left out of the library as Google's is deprecated and the Material Design guidelines are against blocking progress modals - inline indicators should be preferred. 

You'd have to make a custom view dialog if you really want to use that pattern.
