### ISSUE TITLE
I need to scroll custom view to position so my element is visible when dialog is shown

### ISSUE THREAD

**Issue by rene-dohan** [afollestad/material-dialogs#1854]
**What module does this apply to?**

Core

**Description what you'd like to happen:**

I would like to be able to access scroll view to scroll to some position when dialog is shown

**Describe alternatives you've considered:**

fork library or just hack around to get the view from hierarchy

**Comment by afollestad** [comment]
This is an implementation detail to your app, not really this library. 

You'll want to get a reference to your `ScrollView` and manually scroll it as needed.

**Comment by rene-dohan** [comment]
Well for sure and i did it already but you made it quite difficult and ugly to access that scrollview.
