### ISSUE TITLE
Touching outside the dialog dismiss the dialog

### ISSUE THREAD

**Issue by theapache64** [afollestad/material-dialogs#1856]
**Library Version:**

3.1.0
 
**Affected Device(s):**
 
Motorola XT1572
 
**Describe the Bug:**

I've a simple input dialog with one `EditText`,

```kotlin
MaterialDialog(this).show {
            noAutoDismiss()
            title(res = R.string.title_name)
            input()
            positiveButton(R.string.action_save_name)
}
```

and when I click the outside the dialog, the dialog got dismissed. 

**To Reproduce:**
1. Create an input dialog with `noAutoDismiss` and show
```kotlin
MaterialDialog(this).show {
            noAutoDismiss()
            title(res = R.string.title_name)
            input()
            positiveButton(R.string.action_save_name)
}
```
2. Touch outside the dialog

**Expected Behavior:**

The dialog shouldn't dismiss

or Is there any other flag to prevent autoDismiss on outside dialog touch ?

**Comment by hardysim** [comment]
AFAIK, this is the standard behavior of a dialog in android. But you can deny it via `cancelOnTouchOutside()`.

**Comment by theapache64** [comment]
That's what I was searching for. Thanks Simon :)
