### ISSUE TITLE
TextInputLayout clipped when adding textInputStyle

### ISSUE THREAD

**Issue by hardysim** [afollestad/material-dialogs#1857]
**Library Version:**
3.1.0 (tested with a2c743b15a3d4f37983b9e39c9fdb3656b0531a6 as well)
 
**Affected Device(s):**
Emulator Pixel 3 with Android Q Beta 5
 
**Describe the Bug:**
When adding a style to all text inputs via `textInputStyle`, the input box on the dialog is clipped. Adding a `TextInputLayout` to a non-dialog layout works fine.

**To Reproduce:**
1. checkout a2c743b15a3d4f37983b9e39c9fdb3656b0531a6 
2.  add `<item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>` to `AppTheme` in the sample module
3. open a input dialog

![image](https://user-images.githubusercontent.com/3737512/62045721-62e16f80-b206-11e9-9d73-8c01739fb36a.png)

When added to my app, it looks different but also clipped:

![image](https://user-images.githubusercontent.com/3737512/62045801-97edc200-b206-11e9-9b7b-d45339268eda.png)

**Expected Behavior:**
The input box in a dialog should behave like all other `TextInputLayout` in the app. When setting  `textInputStyle` on the theme, the dialog should respect it.

![image](https://user-images.githubusercontent.com/3737512/62045827-a63bde00-b206-11e9-8be9-87044ce4fd2a.png)

---

This looks like #1707, #1701, #1695, #1712 and I am using *material 1.1.0-alpha08* but as mentioned, this happens in *1.0.0* as well (as used in the sample app).

**Comment by hardysim** [comment]
Looks like it can be fixed by just using the defaults of `TextInputLayout`. This means, removing `app:hintEnabled` and `style` from `TextInputLayout` and `TextInputEditText` in `md_dialog_stub_input.xml`.

This results in the known UI when not setting `textInputStyle`:

![image](https://user-images.githubusercontent.com/3737512/62047367-94f4d080-b20a-11e9-99c1-d737e5559601.png)

And when setting it, it uses the same style as all the other `TextInputLayout` in the app - which is what we want:

![image](https://user-images.githubusercontent.com/3737512/62047470-dab19900-b20a-11e9-9ff4-ab0181cb8558.png)

Hint: The missing horizontal margin on the box is fixed in `material 1.1.0-alpha08` so it should be fine to not set any margin manually.

![image](https://user-images.githubusercontent.com/3737512/62047572-206e6180-b20b-11e9-87dd-9e80a5ee8033.png)

---

@afollestad why do we need `app:hintEnabled` and the styles `MD_Dialog_Input_Layout` and `MD_Dialog_Input_Layout.Message`? Did I miss something?

**Comment by ChristineWasike** [comment]
I will work on this.

**Comment by hardysim** [comment]
@ChristineWasike please have a look at #1858 where I've already "fixed" this.

**Comment by GTripathee** [comment]
Using ConstraintLayout as a Container and adjusting width to 0dp worked in my case, even I use the OutlinedBox Material Style

**Comment by hardysim** [comment]
@GTripathee do you mean in a custom layout for the dialog?

This might be a workaround but as the library directly provides the possibility to show a text field it would be nice to have this fixed instead of needing a custom view (see discussion in #1858).

**Comment by GTripathee** [comment]
Yes I tried in the custom layout. 

You are right that its good to have the fixes on the library dialog.
This might be helpful for the people trying out custom layout.
