### ISSUE TITLE
Progress Dialog in v3

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1862]
**What module does this apply to?**
core

**Description what you'd like to happen:**
Google clearly stated in its design guidelines that progress dialogs are *deprecated* and that they should not be used.
Despite this, almost every google app (Gmail, Drive, Sheets, Slides, Docs) make use of dialog progress bars to display downloads/uploads.
Since this library is opinionated it may be worth the effort packing a progress layout and creating an extension function that transforms the dialog into a progress dialog.

**Comment by afollestad** [comment]
I don't want to include a progress dialog, cause I still prefer and want to encourage the use of inline progress indicators.
