### ISSUE TITLE
Can you please provide codes for Android Java?

### ISSUE THREAD

**Issue by ibyteapps** [afollestad/material-dialogs#1864]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Core? Input? Files? Color?

**Description what you'd like to happen:**

A clear description if the feature or behavior you'd like implemented.

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by afollestad** [comment]
Java is unsupported.

**Comment by Geowan** [comment]
There is this documentation for use with java though its for the older version

https://github.com/afollestad/material-dialogs/blob/febb975c8498fb1e3efe56768a3703cee5a3cf4f/README.md
