### ISSUE TITLE
ERROR: Unable to resolve dependency for ':component_login@debug/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.41. Show Details

### ISSUE THREAD

**Issue by ruhaly** [afollestad/material-dialogs#1866]
ERROR: Unable to resolve dependency for ':component_login@debug/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.41.
Show Details

**Comment by afollestad** [comment]
Can't be related to Material Dialogs.
