### ISSUE TITLE
Add icon to items in List Dialog

### ISSUE THREAD

**Issue by cheenu** [afollestad/material-dialogs#187]
Firstly, thanks for creating this amazing library :+1: 

Is there any way to set an icon to items in a List Dialog or is a Custom List Dialog the only way to do so?

Thanks!

**Comment by afollestad** [comment]
Currently, a custom adapter is the only way to do so

**Comment by tonyshkurenko** [comment]
Is this possible to use Spannable with ImageSpan in dialog?
