### ISSUE TITLE
This method seems to be ineffective.

### ISSUE THREAD

**Issue by ShenHaiyi** [afollestad/material-dialogs#1870]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.1.0
 
**Affected Device(s):**
 
Android 9.0 ，Android 5.1.1
 
**Describe the Bug:**

cancelOnTouchOutside(false) 

Set to false to click on exterior disappear

**Expected Behavior:**

Expectations will not disappear

**Comment by zunjae** [comment]
Maybe related https://github.com/afollestad/material-dialogs/issues/1842

**Comment by afollestad** [comment]
This method is a delegate to `android.app.Dialog`'s method, this isn't anything specific to this library. 

You probably need to set cancelable to true or something.
