### ISSUE TITLE
I want to set the color of each button separately, how should I do it?

### ISSUE THREAD

**Issue by aojiaoqiang** [afollestad/material-dialogs#1872]
Hi, thanks for helping me with your open source project.
How to set the color of the button separately?
For example, I want to set the confirm button to blue, and the cancel button to red. At present, it seems that I can only set the colors of all the buttons through styles.

**Comment by afollestad** [comment]
```
MaterialDialog(context).show {
    getActionButton(NEGATIVE).updateTextColor(Color.RED)
    ...
}
```

**Comment by dejiapps** [comment]
> ```kotlin
> MaterialDialog(context).show {
>     getActionButton(NEGATIVE).updateTextColor(Color.RED)
>     ...
> }
> ```
> 
> Also a duplicate of #1865.

I tried this in my code, but it doesn't seem to be working. Does this look right?

getActionButton(WhichButton.NEGATIVE).updateTextColor(Color.RED)

**Comment by DurgaArunkumarSmitiv** [comment]
Have you found solution. This solution is not working for me as well.

**Comment by dejiapps** [comment]
@afollestad I don't think this issue has been fixed yet. It still doesn't seem to be working.

**Comment by ch8908** [comment]
@aojiaoqiang This doesn't work, it's bug actually.

**Comment by aojiaoqiang** [comment]
> ```kotlin
> MaterialDialog(context).show {
>     getActionButton(NEGATIVE).updateTextColor(Color.RED)
>     ...
> }
> ```
> 
> Also a duplicate of #1865.

I tried it and found that it wasn't working.  :(

**Comment by afollestad** [comment]
This is still open: https://github.com/afollestad/material-dialogs/issues/1783
