### ISSUE TITLE
Add missing license information to your deployed Maven artifact

### ISSUE THREAD

**Issue by jeffdcamp** [afollestad/material-dialogs#1874]
**What module does this apply to?**
All

**Description what you'd like to happen:**
There are tools such as "OSS Licenses Gradle Plugin" (https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin) or "Gradle License Report" (https://github.com/jk1/Gradle-License-Report) that are used to generate license reports and license screens for apps.  They pull the license information from the Maven Dependency Pom file.  Material Dialogs is one of the few projects that has no licence information in the generated Maven pom file (in our project we have more than 150 dependencies (including transitive dependencies)... and Material Dialogs is 1 of 3 projects (out of the 150+) that is missing licensing information.

Example from Maven Central for Dagger (which includes the correct license info)  (https://search.maven.org/artifact/com.google.dagger/dagger/2.24/jar):

```
  <licenses>
    <license>
      <name>Apache 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
```

It would also be nice to have the project URL in the pom file too.  Example:

`<url>https://github.com/google/dagger</url>`

**Comment by afollestad** [comment]
This is probably a bug or something missing from [bintray-release](https://github.com/novoda/bintray-release), the plugin that publishes releases of this library. I do not generate POMs.

Bintray says the [default license for publishing is Apache 2.0](https://github.com/novoda/bintray-release/wiki/Configuration-of-the-publish-closure#configuration), so there should be nothing more for me to do there. I also already specify a website in the publish configuration as well.

https://github.com/afollestad/material-dialogs/blob/f08de3195463847167473fb688e6e82bc34e07ab/bintrayconfig.gradle#L49

**Comment by jeffdcamp** [comment]
You are correct... you don't produce the pom.xml yourself.... you use the bintray plugin (which generates the pom.xml for you).  I don't have experience with the bintray-release plugin (we publish to Maven Central instead), I tried to see what might be missing in the material-dialogs project, but couldn't identify what the issue was... but I noticed that the actual published pom.xml files are missing the license AND website.... but other projects that are published to bintray seem to have licence and website data in their pom.xml files.

Looking at the generated pom.xml on bintray, you can see that the pom.xml file is missing the license information.

pom.xml file for "core":
https://jcenter.bintray.com/com/afollestad/material-dialogs/core/3.1.1/:core-3.1.1.pom

To see all of the published aars and pom.xml files you can browse the files here:
https://jcenter.bintray.com/com/afollestad/material-dialogs

I have wondered if the license part of the bintray-release plugin does not take the default "Apache 2.0" if your groupId starts with "com" (Commercial)...  just a thought...

**Comment by PaulWoitaschek** [comment]
@afollestad Can you fix this? This is literally the only library I'm using that does not publish it's license.
