### ISSUE TITLE
How to use a DialogFragment class?

### ISSUE THREAD

**Issue by max02100** [afollestad/material-dialogs#188]
I would like to use a dialog fragment with this library.

Someone has an idea? 

Thanks in advance :D

**Comment by TomasValenta** [comment]
Hi,
if you want, look at code in my Application:
https://github.com/TomasValenta/WebCamViewer/blob/master/app/src/main/java/cz/yetanotherview/webcamviewer/app/actions/WelcomeDialog.java

**Comment by TomasValenta** [comment]
Here is better example:
https://github.com/afollestad/material-dialogs/blob/master/sample/src/main/java/com/afollestad/materialdialogssample/ColorChooserDialog.java
or
https://github.com/afollestad/material-dialogs/blob/master/sample/src/main/java/com/afollestad/materialdialogssample/FolderSelectorDialog.java
