### ISSUE TITLE
Make dialog with circle progress bar

### ISSUE THREAD

**Issue by AlexDundar** [afollestad/material-dialogs#1880]
Is in the last version (`3.1.1`) of library possibility to make progress dialog with text and circle progress bar? For example, when I used version `0.9.6.0`, I could write:
```
MaterialDialog.Builder(this)
        .content("Loading ...")
        .progress(true, 0)
        .build()
```
But in the last version I cannt find some methods for adding circular progress.

**Comment by afollestad** [comment]
Progress Dialogs were left out intentionally.
