### ISSUE TITLE
Option to remove radiobutton icons/selectors for single selection

### ISSUE THREAD

**Issue by TheIronMarx** [afollestad/material-dialogs#1881]
It seems clunky to have a user select a single item from a list and then have to click on a positive button. When I pop a dialog and display a list for a user to click on, the item should be chosen and the dialog should dismiss. This is easily achievable behavior now, but the radio button icons are still visible. An option to not show those at all, or have that be the default behavior, would be appreciated.

**Comment by afollestad** [comment]
This is effectively what happens if you use a plain list dialog and add a positive action button.
