### ISSUE TITLE
[Core] Custom font: dialog's title showing graphical glitch (cursor?)

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#1883]
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
- Xiaomi Mi A2 lite with Android 9.0 (Sept. Patch)

- Nexus 5 with Android 8.1.0 (CrDroid Rom)
 
**Describe the Bug:**

I'm [setting](https://github.com/enricocid/Music-Player-GO/blob/a7dae5745565d820aa845610844b71342bd16502/project/app/src/main/res/values/styles.xml#L8)  a custom font (Raleway) for material dialogs [here](https://github.com/enricocid/Music-Player-GO/blob/a7dae5745565d820aa845610844b71342bd16502/project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt#L77) and 
[here](https://github.com/enricocid/Music-Player-GO/blob/a7dae5745565d820aa845610844b71342bd16502/project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt#L94). Once opened I see a cursor (?)/graphical glitch at the end of the title for a few seconds.

**To Reproduce:**

1. Set a custom font in base theme
2. Open the dialog

**Expected Behavior:**

No cursor (?)/graphical glitch

**Video showing the issue:**

https://youtu.be/FJVQTk1F1RE

**Comment by danteissaias** [comment]
+1

**Comment by VMadalin** [comment]
@enricocid Thank you this detailed issue, I reproduce easy this visual glich on your app `musicPlayerGo` but was impossible to reproduce the same behaviour on the sample `material-dialogs`. 

On `musicPlayerGo` I reproduce the issue in the following scenarios: 
- Display MaterialDialog inside a `PreferenceFragmentCompat` on simple `FragmentLayout` activity content.
- On two of `Fragments` tabs (AllMusic, Artits, Folders, Preference)  I added `onCreate` method to display MaterialDialog. In the first fragment cannot reproduce the issue, but on the second the cursor is visible.

That it's for the moment what I know about this strange issue

**Comment by enricocid** [comment]
Could it be related to material components theme? Does it happens with theme appcompat? (Can't try unfortunately).

**Comment by LogCatKAY** [comment]
I have same bug. Display `MaterialDialog` inside a `PreferenceFragmentCompat` after click on `Preference` element.

I can't reproduce it on `androidx.preference:preference:1.0.0`, but on `androidx.preference:preference:1.1.0` it is easy to reproduce.

**Comment by VMadalin** [comment]
> Could it be related to material components theme? Does it happens with theme appcompat? (Can't try unfortunately).

@enricocid  I tried it on your project and unfortunately isn't related with theme, I also tried to apply the material component theme to the sample with the same result 

> I can't reproduce it with androidx.preference:preference:1.0.0, but with androidx.preference:preference:1.1.0 it is easy to reproduce.

@LogCatKAY Thank you for the details, apparently the only thing I see in the `changelog` is  related with accessibility changes  (https://developer.android.com/jetpack/androidx/releases/preference), but I'm not sure

**Comment by enricocid** [comment]
I'm experiencing  this problem also in fragments (androidx.fragment.app.Fragment).
Bottom Sheet dialog works good instead.

**Comment by enricocid** [comment]
Hello,

I noticed the same problem also when using androidx.appcompat.widget.Toolbar.
This is happening on Android Pie and not on older Android versions, at least for me. It does not depend by the theme, as I tried to extend appcompat and material theme, result is the same. Seems related to Android x itself.👀
I think this issue is safe to close. Anyway, If I find a solution I'm gonna share here.

**Comment by enricocid** [comment]
Hello,

@bullheadandplato just fixed the issue on my app.

PreferenceFragmentCompat tries to apply default theme to the Fragment causing the issue

https://github.com/enricocid/Music-Player-GO/issues/104#issuecomment-573447828

To fix the issue just define a theme for preferences

   <style name="BaseTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
          ....
        <item name="preferenceTheme">@style/PrefTheme</item>
    </style>
```
<style name="PrefTheme" parent="PreferenceThemeOverlay">
     <item name="android:scrollbars">none</item>
 </style>
```
