### ISSUE TITLE
[Core] Programatically set colour of listItemsMultiChoice's checkboxes and listItemSingleChoice's checkboxes

### ISSUE THREAD

**Issue by adendiamond** [afollestad/material-dialogs#1887]
Hi there,
My app has user-set themes and therefore I have to get an accent colour for my app at runtime.
Is there a way to programmatically set the colour of listItemsMultiChoice's checkboxes and listItemSingleChoice's checkboxes? If not, is there a possibility of adding functionality like this? Otherwise, I will have to find an alternative.

**Comment by enricocid** [comment]
I implemented a custom adapter to achieve that. You can look at my code if you want.

Adapter:

https://github.com/enricocid/Music-Player-GO/blob/master-mpgo-ex/project/app/src/main/java/com/iven/musicplayergo/ui/AccentsAdapter.kt

showAccentDialog():

https://github.com/enricocid/Music-Player-GO/blob/3752800e7580944444da870be66f0bd6a3918e83/project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt#L109

**Comment by enricocid** [comment]
You can use this code in your app if you want. Hope Kotlin is ok for you :)

**Comment by afollestad** [comment]
Yeah I do not plan to integrate this into core functionality.
