### ISSUE TITLE
Manual message gravity

### ISSUE THREAD

**Issue by BigGitWorld** [afollestad/material-dialogs#1894]
I'm using the latest version of the library and want to use manual gravity for message text.
For example, I want to set text gravity to the right side without paying attention to phone language.
In fact, I have only persian texts in my application and want to be set in the right side always.
How can I do it?

**Comment by BigGitWorld** [comment]
No any improvement?

**Comment by afollestad** [comment]
I do not plan to add manual gravity capabilities.
