### ISSUE TITLE
Alignment to left

### ISSUE THREAD

**Issue by DurgaArunkumarSmitiv** [afollestad/material-dialogs#1898]
![IMG_20191013_134654](https://user-images.githubusercontent.com/47417370/66712835-64134900-edc0-11e9-9ac4-ab947883b250.jpg)

Custom view is center aligned . Need to bring to left, how can we bring the view to left. My layout is aligned left but still dialog is center aligned. How to bring it to left.

**Comment by DurgaArunkumarSmitiv** [comment]
can you please let me know any solution for this

**Comment by afollestad** [comment]
Your view needs to `match_parent` in terms of width. Nothing in this library messes with your custom view gravity.
