### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by Waboodoo** [afollestad/material-dialogs#1899]
I'm trying to add support for Dark Mode / Dark Themes to my app, but I'm unable to find out what I need to do to get this library to use its own dark theme.
I've read the documentation (https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#light-and-dark) but no matter what I try, I always get the light version of the dialogs. I even tried overriding the `dialogBehavior` by providing an object that always requests the dark version in `getThemeRes`.

What is the intended way of switching the library to use dark theme?

**Comment by afollestad** [comment]
What's listed in [Theming](https://github.com/afollestad/material-dialogs/blob/master/documentation/CORE.md#theming) is the intended way, and I have not had any issues with it. The sample project uses it as well.

**Comment by Waboodoo** [comment]
In my project I have the following theme:

```xml
<style name="LightTheme" parent="@style/Theme.MaterialComponents.DayNight.NoActionBar">
    <item name="colorPrimary">@color/primary</item>
    <item name="colorPrimaryDark">@color/primary_dark</item>
    <item name="colorAccent">@color/primary</item>
    <item name="md_background_color">#212121</item>
</style>
```

The theme colors change based on whether the phone's dark mode is enabled or not. The MaterialDialogs however always use the light theme, even when the app's main color is dark. Also, the `md_background_color` attribute doesn't seem to have an effect either.
What am I missing?

**Comment by Waboodoo** [comment]
Ok, I have in the meantime managed to get the library to switch to its dark theme, though I don't fully understand how. I will investigate further. Thanks for the support.
