### ISSUE TITLE
Bottom Sheets How do listItems initialize by setting the default number of selections?

### ISSUE THREAD

**Issue by hegaojian** [afollestad/material-dialogs#1900]
How do listItems initialize by setting the default number of selections?like in listItemsSingleChoice(array ,initialSelection = 2) 

![QQ截图20191014094759](https://user-images.githubusercontent.com/18655288/66725809-beb3b000-ee67-11e9-8efd-34b4d0072fcc.png)

**Comment by afollestad** [comment]
A plain list dialog does not allow an initial selection. That's for single and multi choice lists.
