### ISSUE TITLE
Why is neutralButton deprecated?

### ISSUE THREAD

**Issue by adendiamond** [afollestad/material-dialogs#1902]
Hi there,

I understand that Google doesn't want to let developers leave the dialog in a neutral state, however,
what if the neutralButton is for a neutral option like expanding the dialog, changing something in a custom layout, or swapping dialog? If I'm way off please let me know.

Thanks.

**Comment by enricocid** [comment]
> Google doesn't want to let developers leave the dialog in a neutral state

Sometimes neutral button is the only option. This one is present on the latest gplay version (Google doesn't take its guidelines seriously, why devs are supposed to strictly follow guidelines?):


![Screenshot_20191027-194100](https://user-images.githubusercontent.com/7274841/67639611-42eb4600-f8f2-11e9-97d9-b4d14fecacd6.png)

**Comment by afollestad** [comment]
Being called Material Dialogs, the Material Design Guidelines are followed. It's deprecated rather than not included at all so you still have the option to use them. Just suppress the deprecation if you really want to use it.

**Comment by adendiamond** [comment]
For the record, this was taken from the `MaterialAlertDialogBuilder` class, and it isn't deprecated:

```
  @NonNull
  @Override
  public MaterialAlertDialogBuilder setNeutralButton(
      @Nullable CharSequence text, @Nullable final OnClickListener listener) {
    return (MaterialAlertDialogBuilder) super.setNeutralButton(text, listener);
  }
```
