### ISSUE TITLE
Add setPeekHeight overload that takes a percentage value

### ISSUE THREAD

**Issue by Supercaly** [afollestad/material-dialogs#1904]
I was trying to use `setPeekHeight` method on `MaterialDialog(context, BottomSheet())` but the method accepts only literal px or a resource, but passing them requires knowing the final height of the BottomSheet. 

Is there a way to pass a percentage value to the method? For example, I want my view to be 80% of the total screen height so I can call `setPeekHeight(percentage=80)` 

I've noticed that in the code this mechanism is used to default the height to 60%, so maybe this can be extended to everyone if it's not already present.

**Comment by enricocid** [comment]
If you are using Kotlin you can measure the height of the view you want to use as peek. Just use this online function:

https://github.com/enricocid/Music-Player-GO/blob/50627f8d6f191f23f10225a1e69085d4382be6b1/project/app/src/main/java/com/iven/musicplayergo/MainActivity.kt#L949

Then on your view:

your_view.afterMeasured {
bottom sheet.setPeekHeight(height)
}

Like this:

https://github.com/enricocid/Music-Player-GO/blob/50627f8d6f191f23f10225a1e69085d4382be6b1/project/app/src/main/java/com/iven/musicplayergo/MainActivity.kt#L416

I don't think there's an easy way to do that. You need to measure the view height.

**Comment by Supercaly** [comment]
Your answer works great but in my case, the MaterialDialog is implemented in a class itself and needs to be used by many classes, so I didn't want to make it view dependant, and since I needed a fraction of the total screen size, at the end I settled for using display metrics:

```kotlin
init {
   val peekHeight = context.resources.displayMetrics.heightPixels * 70 / 100
   dialog.setPeekHeight(peekHeight)
   // ...
}
```

**Comment by afollestad** [comment]
I do not plan to allow percentage values to be given - it's better to use a dimension resource that is different based on screen size by overriding dimens.xml for different screen widths.
