### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by MenilV** [afollestad/material-dialogs#1905]
*Please consider making a Pull Request if you are capable of doing so.*
Last release date: Sep, 4th and I know there have been only two commits since then I still think it's worth releasing it.
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
All
 
**Describe the Bug:**

A clear description of what is the bug is.

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**
Relase after at least one month and at least 1 new issue fixed or feature implemented

**Comment by afollestad** [comment]
Not ready yet.
