### ISSUE TITLE
All dialogs are rectangles by default: md_corner_radius not set

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#1909]
By default, the `md_corner_radius` is not set at all.
That leads to the fact that the library has no corner radius by default.

You can reproduce it by installing the `sample.apk`:

<img src="https://user-images.githubusercontent.com/743462/67854934-af905b80-fb11-11e9-90ab-242f81ffc901.png" width="300" />

**Comment by afollestad** [comment]
Fixed via #1840

**Comment by afollestad** [comment]
Sorry, was slightly related but not exactly.
