### ISSUE TITLE
Figure out what happened to the button click areas and selectors

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#191]
All but one buttons work, the touch target is off, and not the entire button is actually selectable.

![screenshot_2015-01-15-15-28-30](https://cloud.githubusercontent.com/assets/1820165/5767057/7a762f1e-9ccb-11e4-8cde-a5088dfd79b1.png)

**Comment by afollestad** [comment]
This issue came up after I began caching selectors, which I added in order to optimize a lot of stuff and prepare for the ability to customize selectors which will require caching variables.

**Comment by afollestad** [comment]
@hzsweers I can't remember if it was you who implemented the inset button selectors, but sometime around when that was implemented, these issues started coming up if I changed anything

**Comment by hzsweers** [comment]
¯\_(ツ)_/¯ I didn't implement those

**Comment by hzsweers** [comment]
Weird, my arm is missing

**Comment by afollestad** [comment]
@hzsweers damn, I can't seem to remember who it was. 

And hahaha, funny

**Comment by afollestad** [comment]
I think this issue may've had something to do with the fact that all buttons were using the same Drawable selector instances (since objects are held as references rather than literal values and they're all set to those two selectors). I got rid of the newer selector caching, for now. Custom selectors for specific buttons will have to be implemented in a different way.
