### ISSUE TITLE
[Datetime] Top corners radius are broken for datePicker

### ISSUE THREAD

**Issue by MaximeJineMaraval** [afollestad/material-dialogs#1914]
**Library Version:**

```
implementation 'com.afollestad.material-dialogs:core:3.1.1'
implementation 'com.afollestad.material-dialogs:datetime:3.1.1'
```
 
**Affected Device(s):**
 
Reproduced on Google Pixel 3 XL, Google Pixel 2, Google Pixel C, on API 29 and API 19
 
**Describe the Bug:**

The corner radius does not affect the top dialog corners for the datePicker (only works on the bottom ones). It actually works on a "classic" dialog, just broken on the datePicker.

<img width="288" alt="Capture d’écran 2019-11-03 à 17 00 25" src="https://user-images.githubusercontent.com/46402524/68088197-e4c3e300-fe5c-11e9-8e4e-2cc6b58e04ba.png">

**To Reproduce:**
```
MaterialDialog(this).show {
            datePicker(currentDate = myDate) { _, datetime ->
                ...
            }
        }
```

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        ...
        <item name="md_corner_radius">12dp</item>
        ...
</style>
```

**Expected Behavior:**

Corner radius define on the appTheme affect all the dialog corner radius.

Thanks :)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/1840

**Comment by joyceHong0524** [comment]
@MaciejCiemiega This didn't help me :(
