### ISSUE TITLE
Can't use extensions in Java

### ISSUE THREAD

**Issue by paul590** [afollestad/material-dialogs#1916]
Hello I am currently using this library for a project in Java using Material Dialog Core version 3.1.1. When running the following code I am unable to see in the list of choices to create a list as described in your documentation:

new MaterialDialog(getActivity(), Util.getDialogBehavior())
                            .title(null,"Some text")
                            .listItems // does not exist

**Comment by afollestad** [comment]
`listItems` is an extension method, it can only be used like that from Kotlin.

It's possible to use the equivalent static method from Java, but version 2 and above of this library were written specifically to work with Kotlin.

**Comment by paul590** [comment]
Hi Aidan,

Thank you for letting me know this information. That makes sense! Can you please let me know which release is the latest for version 1? Thank you,

Sincerely,

Paul Arellano

**Comment by afollestad** [comment]
The last version before Kotlin was 0.9.6.0

https://github.com/afollestad/material-dialogs/blob/master/README_OLD.md
