### ISSUE TITLE
Where is `progress` from 0.9.6.0 ?

### ISSUE THREAD

**Issue by psteiger** [afollestad/material-dialogs#1918]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.1.1
 
**Describe the Bug:**

Old 'progress' feature missing 

Hi, I used to use `.progress()` and `setProgress()` to display a progress bar in the Material Dialogs, back in version 0.9.6.0. I'm now upgrading to latest 3.1.1 but can't find an alternative for that. Is it gone?

**Comment by afollestad** [comment]
#1850 #1862 #1893 #1880 #1816 #1786
