### ISSUE TITLE
Dialog's corner radius and position change when the containing Activity is resumed

### ISSUE THREAD

**Issue by ColorfulHorse** [afollestad/material-dialogs#1920]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.1.1
 
**Affected Device(s):**
 
Xiaomi MIX 2 Android 8.0
 
**Describe the Bug:**

dialog's corner radius and position have been changed when resume again

**To Reproduce:**
1. 
![gif3](https://user-images.githubusercontent.com/20135323/69215779-8b221f00-0ba5-11ea-9cf7-f310ef76551c.gif)

2. 
![gif4](https://user-images.githubusercontent.com/20135323/69215759-80678a00-0ba5-11ea-913d-e8c37d47c408.gif)

**Expected Behavior:**
not be changed

**Comment by afollestad** [comment]
Looks like a potential MIUI bug.

**Comment by afollestad** [comment]
I am unable to reproduce but this may be improved with the current release.
