### ISSUE TITLE
Crash when i try to open dialog from view model

### ISSUE THREAD

**Issue by ilyatim** [afollestad/material-dialogs#1921]
**Library Version:**

3.1.1
Mobile 
Huawei Honor 10
 
Bug:
When i try to create dialog like this 

 MaterialDialog(context).show {
            listItemsSingleChoice(R.array.genders)
        }
The app closes with the error 
android.view.WindowManager$BadTokenException: Unable to add window -- token null for displayid = 0 is not valid; is your activity running?

From activity it work correctly.
Using AndroidViewModel and DataBinding
viewModel = ViewModelProviders.of(this).get(ProfileViewModel::class.java)
binding = DataBindingUtil.setContentView(this, R.layout.activity_profile)
binding.viewModel = viewModel
binding.executePendingBindings()

**Comment by afollestad** [comment]
You must pass a context that is attached to a window, i.e. an Activity.
