### ISSUE TITLE
maxDateTime argument for MaterialDialog.dateTimePicker

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1922]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

DateTime

**Description what you'd like to happen:**

Add a maxDateTime argument to the dialog. The argument allows to restrict the maximum date/time to be set by the user.

**Describe alternatives you've considered:**

N/A

**Comment by atthapon-k** [comment]
you have to publish it before close the one.
