### ISSUE TITLE
User able to swipe to dismiss bottom sheet, even when cancelable value is false

### ISSUE THREAD

**Issue by dphans** [afollestad/material-dialogs#1925]
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
Google Pixel 2 XL with Android 10
 
**Describe the Bug:**

Dialog which BottomSheet behavior is able to cancel by swipe down the content view, even I set `cancelable` into `false`, below is example code:

```kotlin
MaterialDialog(mActivity, BottomSheet(LayoutMode.WRAP_CONTENT)).show {
    // ...
    this.cancelable(false)
    this.cancelOnTouchOutside(false)
    this.noAutoDismiss()
}
```

**To Reproduce:**
1. Show the dialog.
2. Swipe down the content view.

**Expected Behavior:**

BottomSheet dialog must disable the swipe down action when `cancellable` set to `false`.

**Comment by jacobceles** [comment]
@afollestad I am still able to reproduce this bug, did something change after closing it?
