### ISSUE TITLE
Update readme to show sample for preferences

### ISSUE THREAD

**Issue by CarlosEsco** [afollestad/material-dialogs#1928]
**What module does this apply to?**

Core

**Description what you'd like to happen:** 
Update readme to show example of using Material Dialogs with android x preference classes
either such as ListPreference

**Comment by afollestad** [comment]
There is no explicit support for preferences and that wouldn't be something that belongs in the README.

**Comment by CarlosEsco** [comment]
Ok, any reason it was removed after the last java version?
