### ISSUE TITLE
Duplicate class com.afollestad.materialdialogs.BuildConfig found in modules jetified-core-0.8.5.3-runtime.jar (com.github.afollestad.material-dialogs:core:0.8.5.3) and jetified-core-0.9.0.2-runtime.jar (com.afollestad.material-dialogs:core:0.9.0.2)

### ISSUE THREAD

**Issue by karthik2342323** [afollestad/material-dialogs#1929]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
 
**Describe the Bug:**

A clear description of what is the bug is.

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by afollestad** [comment]
Old pre-2.0 versions of the library like that, which were built in Java, used the Support library. New versions use AndroidX. Your app would probably also have to use the legacy support library to avoid this issue, nothing I can do.
