### ISSUE TITLE
No way to show scrollbar for lists of options

### ISSUE THREAD

**Issue by mhmdreza** [afollestad/material-dialogs#1930]
Hello.
Thank for your useful library :)
I have a materialDialog that I fill its data with listItems() function. It maybe have lots of data(up to 8 or 9 options). So, if I change my screen orientation to landscape, I should scroll my dialog in order to find proper option to click.
 Some of our app users just told us that in that situation, there is no sign whether we have other options to click or not.

So, for that, I started to add a scrollbar to this dialog. I find id of recyclerView that contains my options and use some of its function like set Boolean  enableVerticalScrollbar(sth like this) to true, but it strangely doesn't have any effect on that dialog.
 
Maybe, I could use method of materialDialog but I think this is not an appropriate way because I just want to show a list of options. So, please add scrollBar to this dialog when we have lots of options(for example, more than 8 options in portrait, 5 in landscape) to improve user experience.

**Comment by afollestad** [comment]
Hmm, list dialogs already have a scroll bar which can be confirmed from the sample project, and by looking at the UI source for list dialogs.

https://github.com/afollestad/material-dialogs/blob/2f8a0f7ee9b23e50eef3309b07bf704154263b38/core/src/main/res/layout/md_dialog_stub_recyclerview.xml#L9
