### ISSUE TITLE
Theme attributes don't work in App theme (parent="Theme.AppCompat.Light.NoActionBar")

### ISSUE THREAD

**Issue by hawklike** [afollestad/material-dialogs#1932]
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
Samsung Galaxy A40 with Android 9.0
 
**Describe the Bug:**

Theme attributes don't work on my device. I have tried multiple attributes and none of them is working.

**To Reproduce:**
1. add following to your app theme
```xml
 <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/white</item>
        <item name="colorPrimaryDark">@color/darkGrey</item>
        <item name="colorAccent">@color/lightGrey</item>
        <item name="android:textColorPrimary">@color/darkGrey</item>
        <!--Not working -->
        <item name="md_color_button_text">@color/blue</item>
        <item name="md_corner_radius">16dp</item>
    </style>
```

**Expected Behavior:**

I expect to change a dialog's button color and rounded corners.

**Comment by hawklike** [comment]
min SDK version is 22

**Comment by enricocid** [comment]
I'm changing it programmatically and it is working also on lollipop 5.1 (22) (emulator). Try to change the radius programmatically

cornerRadius(res = R.dimen.ref_to_dim)

**Comment by hawklike** [comment]
Yes, I know the way you described works, but how to change a text color of positive/negative button programmatically?

**Comment by enricocid** [comment]
You can't afaik. For this attribute You need to wait the developer's reply as it is probably a bug (works for me)

**Comment by hawklike** [comment]
I know where is the problem. I have more `style.xml` files based on Android API version, so the default `style.xml` (API 22, the lowest of all styles) is never used on my phone (my phone supports API 28). When I deleted all other styles except the first style, it works as it should.
