### ISSUE TITLE
How to Change Input Background-Color / Text Color?

### ISSUE THREAD

**Issue by masterholdy** [afollestad/material-dialogs#1935]
![Unbenannt](https://user-images.githubusercontent.com/37812108/73183229-c51a1f00-411a-11ea-8644-c7ec1db008f9.PNG)
I tried to change:
md_background_color, md_color_title, md_color_content

But i cant change the Background Color / Or the Text Color of the Inputfield

What am i doing wrong?

**Comment by enricocid** [comment]
Materials Dialogs theming is based on the app's theme. There's probably some attributes in Your theme affecting text input background.
You should post the app's theme.

There's no reference to apply custom colors to input dialog.

In Your constructor, you can try to access to com.google.android.material.textfield.TextInputLayout and com.google.android.material.textfield.TextInputEditText from dialog's view like this:

view.findViewById<TextInputLayout>(R.id.md_input_layout)
view.findViewById<TextInputEditText>(R.id.md_input_message)

and try to apply a different colouring meanwhile. Anyway, I'm not sure it will work 100%.

**Comment by masterholdy** [comment]
im new to android and i dont really know how the style works so maybe you can tell me what im doing wrong
https://pastebin.com/raw/cKW2tv28

**Comment by enricocid** [comment]
The situation is a bit confused.

If You're applying this theme to your app:

`<style name="Theme.MyApp" parent="Theme.AppCompat">`

then the text field will appear dark. So, if You apply md_background_color to a light color You will see the result above.

I'd try to change to this:
`<style name="Theme.MyApp" parent="Theme.AppCompat.Light">` removing md_background_color attribute

**Comment by masterholdy** [comment]
so i changed ```<style name="Theme.MyApp" parent="Theme.AppCompat">``` to ```<style name="Theme.MyApp" parent="Theme.AppCompat.Light">``` and removed ```md_background_color``` but that isnt changing my background :(

**Comment by enricocid** [comment]
Could you please indicate me which style are You actually applying to the activity so I can reproduce for the better? thanks

**Comment by masterholdy** [comment]
if you are talking about ```style```tag in xml (styleable) then im not using it at all
im not really sure what i can give you to help you, help me
im new to android and im really overwhelmed by all the UI stuff

**Comment by enricocid** [comment]
Try to post the manifest? so I can see the activity theme You are applying

**Comment by masterholdy** [comment]
ahh im using ```android:theme="@style/AppTheme"```
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="de.hsos.ma.adhocdb">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:appComponentFactory="@string/app_name"
        android:fullBackupContent="@xml/backup_descriptor"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:appComponentFactory"
        tools:targetApi="p">
        <activity android:name=".ui.table.home.TableAddDataSet"></activity>
        <activity
            android:name=".ui.table.create.CreateTableColumnNamesActivity"
            android:parentActivityName=".ui.table.home.TableHomeActivity"></activity>
        <activity
            android:name=".ui.table.create.CreateTableActivity"
            android:parentActivityName=".ui.table.home.TableHomeActivity"></activity>
        <!--<activity
            android:name=".ui.homescreen.delete"
            android:parentActivityName=".ui.table.home.TableHomeActivity"/>-->
        <activity
            android:name=".ui.table.show.TableShowActivity"
            android:parentActivityName=".ui.table.home.TableHomeActivity" />
        <activity
            android:name=".ui.table.view.recycler.LayoutTableListItem"
            android:parentActivityName=".ui.table.home.TableHomeActivity" />
        <activity android:name=".ui.table.home.TableHomeActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by enricocid** [comment]
I tried to display an Input dialog applying the same theme You're applying on Your activity (AppTheme) and I was able to reproduce the same result. 

![Senza nome](https://user-images.githubusercontent.com/7274841/73282229-87d49080-41f1-11ea-9750-05167d6f420e.png)

I solved the issue by removing the following attribute:

`<item name="colorSurface">#313131</item>`

I'm still not practical with the new attributes introduced in material components, but I've found this [article](https://medium.com/over-engineering/setting-up-a-material-components-theme-for-android-fbf7774da739) covering them so You can have a better understanding.

**Comment by masterholdy** [comment]
it worked! thanks!

**Comment by yizuochengchi** [comment]
implementation 'com.afollestad.material-dialogs:input:3.2.1'

**Comment by akhatriST** [comment]
If someone wants to change the input field color without changing the theme attribute then this can be done programmatically by using the following

```
val dialog = MaterialDialog(requireActivity()).show {
                    title(R.string.enterPassword)
                    input(inputType = inputType) { _, text ->
                        // Text submitted with the action button
                    }
                    positiveButton(R.string.submit)
                    negativeButton(R.string.cancel)
                }
dialog.getInputField().setBackgroundColor(Color.WHITE)
```
Last line is the key here, you can set whatever color you want. 

library version 

`implementation 'com.afollestad.material-dialogs:input:3.3.0'`
