### ISSUE TITLE
Dialog's title being cut off when using custom font

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#1936]
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
- Xiaomi Mi A2 lite with Android 9.0
- Nexus 5 with Android 8.1 (custom rom)
 
**Describe the Bug:**

I'm applying a custom font (lato in the example) to the dialog's title and the descender appears to be cut off.

**Edit**: the issue can't be reproduced with all custom fonts (raleway black works great for example).

**To Reproduce:**

Apply a custom font like lato to dialog's title

![Senza nome](https://user-images.githubusercontent.com/7274841/73250555-5f2fa500-41b7-11ea-95a1-0bff2656fc5c.png)

**Comment by afollestad** [comment]
Hmm, I'm not able to reproduce this in the same project.

<img src="https://user-images.githubusercontent.com/1820165/74075905-e5bf6000-49c9-11ea-963e-fdabedcd47a9.png" width="400" />

**Comment by enricocid** [comment]
Try with Lato font, with Raleway I'm not experiencing this issue :)

**Comment by afollestad** [comment]
I'm not seeing it with Lato Black either

![Screenshot_1581284647](https://user-images.githubusercontent.com/1820165/74110542-4e314d00-4b42-11ea-849d-b4ab0538db9c.png)

**Comment by Johnett** [comment]
I'm able to reproduce the bug but in my opinion, it's a small imperfection very unlikely to notice. Also, it depends upon the font family and text size. I am adding more details below.

Device:- **AVD Pixel 3A**, **Android 10**
Font Family:- **Lato black**
Text Size:- **20sp**

it's difficult to see the difference from screenshot so I made a gif(look the bottom end of letter **'g'** and **'j'** )


<img src="https://user-images.githubusercontent.com/25472210/74136388-f3682600-4c13-11ea-89df-f3b42ea15b53.gif" width="90%"></img> 

I'm also including the original images below incase if there is any confusion.

`Test 1:- font-family= lato black, text size = 18sp(no bug)`

<img src="https://user-images.githubusercontent.com/25472210/74136608-5a85da80-4c14-11ea-8c45-861c2c71dae3.PNG" width="60%"></img> 


`Test 2:- font-family= lato black, text size = 20sp(bug)`

<img src="https://user-images.githubusercontent.com/25472210/74136616-607bbb80-4c14-11ea-85df-fc5512df92b5.PNG" width="60%"></img> 


`Test 3:- font-family= lato black(test source:-https://fonts.google.com), text size = 300px(no bug)`

<img src="https://user-images.githubusercontent.com/25472210/74136630-65d90600-4c14-11ea-8ede-91f5d8b5f8a7.PNG" width="40%"></img> 


Conclusion:- I have no idea how to solve this issue.

**Comment by enricocid** [comment]
Probably a solution could be to measure some text paint specs applying vertical padding programmatically whe using custom fonts

**Comment by Johnett** [comment]
That's one possibility(after further testing it seems like the issue only occurs in some versions.) @enricocid Which font(lato black, regular, bold, etc.) and text size you used for testing(reproduce this error)?

**Comment by enricocid** [comment]
> That's one possibility(after further testing it seems like the issue only occurs in some versions.) @enricocid Which font(lato black, regular, bold, etc.) and text size you used for testing(reproduce this error)?

I'm not applying a custom text size to dialogs titles, I'm using the md_font_title in base theme. Anyway, don't know if it is relevant, but I'm applying material components theme.

[styles](https://github.com/enricocid/VectorifyDaHome/blob/master/project/app/src/main/res/values/styles.xml)

I ran into this issue with lato black font. I then switched to raleway which is working good :)

**Comment by Johnett** [comment]
In normal mode, it's hard to notice this issue(@enricocid used a dark background, in that case, it's noticeable(like shown in the first screenshot)). As @enricocid mentioned in the above comment I thought it's a material theme issue or similar to that but in reality, it's a `TextView` issue. When I applied a 1sp bottom padding to the `md_text_title`(`TextView`) the issue seems to be resolved(I think there is a better way to fix this). I managed to make another gif which will show the transition between normal(adding 1sp `paddingBottom`) and bug state(without `paddingBottom`).

![3oqqu4](https://user-images.githubusercontent.com/25472210/74155067-e0684c80-4c39-11ea-9dae-08d5fbb7cddf.gif)


and from my understanding, '**g**' and '**j**' are most affected by this issue.

@enricocid because of this bug I got the opportunity to check out your app. Great work @enricocid.

**Comment by enricocid** [comment]
> In normal mode, it's hard to notice this issue(@enricocid used a dark background, in that case, it's noticeable(like shown in the first screenshot)). As @enricocid mentioned in the above comment I thought it was a material theme issue or similar to that but in reality, it's a `TextView` issue. When I applied a `1sp` `paddingBottom `to the `md_text_title`(`TextView`) the issue seems to be resolved(I think there is a better way to fix this). I managed to make another gif which will show the transition between normal(adding 1sp `paddingBottom`) and bug state(without `paddingBottom`).
> 
> ![3oqqu4](https://user-images.githubusercontent.com/25472210/74155067-e0684c80-4c39-11ea-9dae-08d5fbb7cddf.gif)
> 
> and from my understanding, '**g**' and '**j**' are most affected by this issue.
> 
> @enricocid because of this bug I got the opportunity to check out your app. Great work @enricocid.

I've read of some users who fixed this issue by making text view single line. Have you tried? :)

**Comment by Johnett** [comment]
I tried both but no change.

**Comment by enricocid** [comment]
@afollestad , @Johnett 

I was able to reproduce this error on **BASIC + HTML CONTENT** sample fixing the issue as You can see from the screenshot. There's a small difference between height and measured font metrics.

Wanted to propose a PR, but I'm not sure where to add this code as this project is so complex.
Moreover, I think You should apply this code only:

- On title's TextView (I don't know how to distinguish between title and other text views (tried this code on populateText()).
- when measured height is > of the original height
- when custom font is being used

I'm sharing what worked for me here hoping it will useful:

```
textView.afterMeasured {

        val fm = textView.paint.fontMetrics //for metrics
        val measuredHeight = fm.descent - fm.ascent //measured height comprehensive of font descent

        Log.d("titleHeight", height.toString())
        Log.d("measuredHeight", measuredHeight.toString())

        if (measuredHeight > height) textView.height = measuredHeight.toInt()
      }
```
afterMeasured is the [function](https://github.com/enricocid/Music-Player-GO/blob/8dbf3fadf09dff3c37003d42623adc513bdd9219/project/app/src/main/java/com/iven/musicplayergo/MusicPlayerGoExtensions.kt#L30) I've used to measure TextView but I'm pretty sure You already have an utility for that.

I think You can also add this difference to bottom padding :)

![Senza nome](https://user-images.githubusercontent.com/7274841/74241222-dac34300-4cdb-11ea-8816-f137339ca819.png)

**Comment by Johnett** [comment]
Hi @enricocid, 
This seems to be a good suggestion. If you already figured out where this code can be placed you can go forward with a PR and discuss it with @afollestad.

**Comment by enricocid** [comment]
> Hi @enricocid,
> This seems to be a good suggestion. If you be able to figure out where this code can be placed you can go forward with a PR and discuss it with @afollestad.

I'm pushing a PR right now :)

**Comment by Johnett** [comment]
That's great.

**Comment by enricocid** [comment]
> That's great.

What's spotless apply?

**Comment by Johnett** [comment]
@enricocid It's a code formatter you can find more details about it here [Spotless](https://github.com/diffplug/spotless)

**Comment by enricocid** [comment]
Done https://github.com/enricocid/material-dialogs/commit/9f10b8c3aa0a25066b960f3555628dbeb390f7d2
