### ISSUE TITLE
Background issue when you swipe the content area and select one item, or select the "up" list item in the Folder Selector of the sample project

### ISSUE THREAD

**Issue by virsir** [afollestad/material-dialogs#194]
4.1.2 with AppCompat, A simple list dialog in Theme.AppCompat.Light.DarkActionBar

If I pressed the first list item, and swipe down, the whole list area is somehow selected, see the background, it does not look good.

![sc1](https://cloud.githubusercontent.com/assets/1409048/5770433/3ca5dd48-9d65-11e4-8706-eafe2df86e52.png)

And after the dialog opened, when I choosed one item, what I saw is that , the radio button's background turn to transparent, but the other part of the list item is still grey, and then the dialog disappeared. sorry I can not capture a screen as it is too fast, i made a picture.

![2](https://cloud.githubusercontent.com/assets/1409048/5770485/2773c704-9d66-11e4-8e14-9e21b3f558a3.png)

**Comment by afollestad** [comment]
There might not be much I can do about this, it may be an AppCompat issue. But I'll look into it.

**Comment by afollestad** [comment]
Just reproduced it on Lollipop, very weird. I'll look into it.

**Comment by afollestad** [comment]
Taking note for myself or others to see later:

Another way to reproduce this is if you press the "..." list item in the Folder Selector of the sample project. The list will become gray for a second or two before refreshing.

**Comment by afollestad** [comment]
@virsir let me know if this bug still exists in release 0.6.1

**Comment by afollestad** [comment]
I can no longer reproduce it so I'm closing this issue.
