### ISSUE TITLE
Sudden unresolved references since 3.2.0

### ISSUE THREAD

**Issue by LossyDragon** [afollestad/material-dialogs#1940]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.2.0
 
**Affected Device(s):**
 
Google Pixel 3 XL, API 29 Emulator
 
**Describe the Bug:**

A clear description of what is the bug is.

Hello, since upgrading to 3.2.0 on my projects, extensions _input_ and _listItems_ are unable to resolve suddenly. Gradle syncs fine with core, input, and bottom sheets on my project. 

Out of troubleshooting, I've downloaded the whole github project locally, verified functionality works as is out of the box. Then in the sample app, I replaced all implementation project files with the bintray version and suddenly, the /sample/ app has a whole bunch of unresolved extensions. 

![pg6dcvT](https://user-images.githubusercontent.com/4994318/74078576-c5a39700-49f1-11ea-8554-3826e5f74cc9.png)

Downgrading to 3.1.1 works as intended. 

**To Reproduce:**
1. Update project to 3.2.0
2. Sync project
3. Unable to compile app or sample app using dialog extensions. 

**Expected Behavior:**

dialog extensions should resolve automatically.

**Comment by afollestad** [comment]
Thanks for catching, should be fixed in 3.2.1

**Comment by LossyDragon** [comment]
Works great now. 

Thanks!
