### ISSUE TITLE
Why aren't there any methods to change Title Text Color & Title Layout Background Color?

### ISSUE THREAD

**Issue by Rishabh-More** [afollestad/material-dialogs#1953]
Like I get it, the whole _"Always follow the material guideline principles"_ and blah blah, but is it too bad to have the user some option to change these if they want to?

I've always used this library in all my projects so far, but now my senior wants to have the Title Text color changed to white & Title Layout background color set to primary, _"in order to match the consistency theme of the app"_ as so he says.

My issue? _Not a single method to change these attributes in any way possible!_
Like come on, I thought giving your users more options to customize was always a plus?

Any plans of adding these methods? If not, please care to explain why not.

**Comment by enricocid** [comment]
They are called "material" dialogs for a reason.
Also, I don't think it is a pure design choice but probably it has something to do with accessibility. 

You could always try to get the views from dialog view with findViewById and apply the colors you want (you can find the id of the title textview and dialog title layout browsing the source code).

**Comment by Rishabh-More** [comment]
> The library is named "material" dialogs for a reason.
> 
> You can access titleLayout from dialog's view and set a background color to it.
> 
> view.titleLayout.setBackgroundColor()
> Anyway, you can't access title'sTextView directly:
> 
> view.titleLayout.findViewById(R.id.md_text_title)
> 
> (Weird) Result:
> 
> ![Senza nome](https://user-images.githubusercontent.com/7274841/74834710-43ce3a80-531c-11ea-9e1f-c1c65586cc68.png)

Thanks this is exactly what I want to do though with different colors. But now that you've shown it, why the heck is there no margin set between the TitleLayout & the content description. Like it boggles my mind at this point..

**Comment by afollestad** [comment]
There doesn't need to be any margin as far as the layout is concerned. The library is manually measuring and laying out views with its own logic so that things are fast and precise. (it avoids some odd system dialog behavior too)
