### ISSUE TITLE
Unable to download version 3.2.1

### ISSUE THREAD

**Issue by arash1379** [afollestad/material-dialogs#1955]
i add   -> implementation 'com.afollestad.material-dialogs:core:3.2.1'  to gradle 
and make this error for me :
**ERROR: Failed to resolve: core
Affected Modules: app**

**Comment by enricocid** [comment]
Try with 3.3.0 (which is the latest version available).

**Comment by AtlantisFaded** [comment]
still failed.
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.afollestad.material-dialogs:core:3.3.0.
Show Details
Affected Modules: app

**Comment by enricocid** [comment]
Works for me, You're probably missing something in the build.gradle. Here are my build.gradle files:

- [Project](https://github.com/enricocid/Music-Player-GO/blob/master/project/build.gradle)
- [App](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/build.gradle)

**Comment by AtlantisFaded** [comment]
> Works for me, You're probably missing something in the build.gradle. Here are my build.gradle files:
> 
> * [Project](https://github.com/enricocid/Music-Player-GO/blob/master/project/build.gradle)
> * [App](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/build.gradle)

Solved. Network issues. Thank u so much.
