### ISSUE TITLE
Extending listpreference to use Material dialog force closes.

### ISSUE THREAD

**Issue by chilldelta** [afollestad/material-dialogs#196]
Am using MaterialDialog in my project and am trying to override the default dialog display to this library UI dialog. Have made reference from this guide http://stackoverflow.com/questions/14398483/how-can-i-change-the-appearance-of-listpreference-dialog then referenced the class in my XML file but whenever I click the preference,the app force closes. Is there a way to implement this for people who want to override how the UI is displayed. N/B: am trying to achieve the singleitemchoice method.

**Comment by afollestad** [comment]
Well there's not nearly enough here to know why it wouldn't work

**Comment by afollestad** [comment]
This isn't an issue of the library itself so I'm closing this.
