### ISSUE TITLE
I want change RadioButton's checked color,

### ISSUE THREAD

**Issue by hegaojian** [afollestad/material-dialogs#1961]
I use listItemsSingleChoice,so I want Change RadioButton's color ,Can I do it？,if can,How I do ? thanks

**Comment by enricocid** [comment]
Try md_color_widget and md_color_widget_unchecked attrs.

@afollestad in core's documentation > theming > widgets color section is missing.

**Comment by hegaojian** [comment]
I can not find this attrs md_color_widget and md_color_widget_unchecked , Can you tell me how the code is used it？ very thanks :sob: @enricocid

**Comment by enricocid** [comment]
@hegaojian

You can add these attributes to the app's theme 😉

Like this:

<item name="md_color_widget">@color/yourcolor</item>

**Comment by hegaojian** [comment]
@enricocid 
change theme i know, but I hope to achieve with the code ，like in activity or fragment change ，I do not know how to change color

**Comment by hegaojian** [comment]
do you know how to change color in activity or fragment?  brother

**Comment by enricocid** [comment]
@hegaojian 
I don't think it is possible programmatically, I can't find any reference in the code/docs. Looking at the code it seems the color is retrieved exclusively from attrs.

So an option could be to use a custom adapter, like [this one](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/src/main/java/com/iven/musicplayergo/adapters/FiltersAdapter.kt) or [this](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/src/main/java/com/iven/musicplayergo/adapters/AccentsAdapter.kt)
This way you can implement your own layout and logic to control the color of radio/checkbox and its checked status.

**Comment by hegaojian** [comment]
@enricocid 
ok , thank you very much，thank you for the answer ，I think you are a very patient person，helped me so long，ha ha ha :relaxed:

**Comment by hegaojian** [comment]
My english is bad ，Communicate with you by translator ，Please do not take offense :grin:

**Comment by enricocid** [comment]
No problem bro 🙂😁

**Comment by mohammaddvi** [comment]
Can I work on this issue?Is it open yet?

**Comment by hegaojian** [comment]
yes,is it open
