### ISSUE TITLE
Dialog doesn't move up with soft keyboard when Android 10 Edge-To-Edge is enabled

### ISSUE THREAD

**Issue by resign** [afollestad/material-dialogs#1964]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

Latest
 
**Affected Device(s):**
 
Google Pixel 3 with Android 10.0
 
**Describe the Bug:**

Dialog doesn't move up when soft keyboard is show. This occurs when Android 10 Edge-To-Edge mode has been enabled.

**To Reproduce:**
1.Follow this - https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e
2. Make a dialog with input

**Expected Behavior:**

Dialog moves up

**Comment by enricocid** [comment]
Even using android:windowSoftInputMode="adjustPan"> in the manifest?
