### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by ladmahesh24** [afollestad/material-dialogs#1966]
is this library support java implementation?

**Comment by afollestad** [comment]
Sorry, no.

**Comment by zhouhanbing1990** [comment]
i also hava this problem.
u can create a kotlin file : object MaterialDialogForJava {}
create MaterialDialog in this file
than u can use MaterialDialog in u java file

**Comment by Geowan** [comment]
I found java support in 0.9.6 with this documentation  https://github.com/afollestad/material-dialogs/blob/febb975c8498fb1e3efe56768a3703cee5a3cf4f/README.md
