### ISSUE TITLE
Android:Evo-gen [Trj] Detected from VirusTotal

### ISSUE THREAD

**Issue by JosephSanjaya** [afollestad/material-dialogs#1968]
**Library Version:**

3.3.0
 
**Affected Device(s):**
 
Any Oppo and RealMe Devices
 
**Describe the Bug:**

I know this trojan is false positive but our customer didnt know that so when i installing this library our user is dropped so much. can you fix it? why this library detected trojan anyways.

**To Reproduce:**
1. installing the library
2. publish application to play store
3. every Oppo and Realme Device detected theres trojan in our application

**Expected Behavior:**

No Trojan Detected

**Comment by afollestad** [comment]
Probably not much that I can do here.

**Comment by JosephSanjaya** [comment]
But i tried VirusTotal without it and it didnt detected anything, it detected only when i installing material-dialogs. Or i did something wrong here?

Thank you.

**Comment by afollestad** [comment]
There is no malicious code here so there isn't much that I can do.
