### ISSUE TITLE
Cancelling a dialog by tapping on the background shadow

### ISSUE THREAD

**Issue by M1cha** [afollestad/material-dialogs#197]
This quits the dialog but no callback gets called.

**Comment by egor-n** [comment]
new MaterialDialog.Builder(getActivity())
                .positiveText("OK")
                .dismissListener(new DialogInterface.OnDismissListener() {
                    @Override
                    public void onDismiss(DialogInterface dialog) {
                        // this stuff gets called
                    }
                })
                .show();
