### ISSUE TITLE
can't download, whether zip or git download

### ISSUE THREAD

**Issue by xuqinghao1991** [afollestad/material-dialogs#1975]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
 
**Describe the Bug:**

A clear description of what is the bug is.

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by afollestad** [comment]
You're trying to download the repository code and can't? That's not something that I can fix.
