### ISSUE TITLE
Execution failed for task ':core:spotlessKotlin'. > The following files had format violations...

### ISSUE THREAD

**Issue by majid-khosravi** [afollestad/material-dialogs#1978]
Hello. I am making improvements in some parts of this library and I have decided to customize views of the title, content and buttons and adjust the color and size of the text for them.
Now I want to publish it in a separate repository, but 'Jitpack.io' in the log showed "wildcard imports" error and I fixed it.
But so then I made that mistake.
`
* What went wrong:
Execution failed for task ':core:spotlessKotlin'.
> The following files had format violations:
      core/src/main/java/com/afollestad/materialdialogs/utils/Dialogs.kt
          @@ -88,7 +88,7 @@
           ··textColor:·Int?·=·null,
           ··@ColorRes·textColorRes:·Int?·=·null,
           ··textSize:·Int?·=·null,
          -··@DimenRes·textSizeRes·:·Int?·=·null
          +··@DimenRes·textSizeRes:·Int?·=·null
           )·{
           ··val·value·=·text·?:·resolveString(this,·textRes,·fallback)
           ··if·(value·!=·null)·{
`

How do you think I can fix that error

**Comment by afollestad** [comment]
https://github.com/diffplug/spotless/tree/main/plugin-gradle
