### ISSUE TITLE
Error on implementing click listener on FlatButton

### ISSUE THREAD

**Issue by MohammedTaha** [afollestad/material-dialogs#198]
A null point exception is thrown every single time I tried to implement the click listener on Flat Button.

**Comment by afollestad** [comment]
I'm assuming this is in a custom view since Material Dialogs doesn't use anything related to "Flat Button"?

See the sample project for how this is done.

**Comment by MohammedTaha** [comment]
Sorry.. my bad.. that was a mistake by my side.
