### ISSUE TITLE
dialogWrapContent is not working?

### ISSUE THREAD

**Issue by zhuyonghao** [afollestad/material-dialogs#1983]
Material Dialogs version: 3.3.0
API: 29
Device Manufacturer: Android
Device Name: Nexus 7 / Android Emulator

**Comment by afollestad** [comment]
There isn't enough information here. What isn't working about it? What does it look like? How is your layout structured?

**Comment by afollestad** [comment]
Actually, this is probably a duplicate of https://github.com/afollestad/material-dialogs/issues/1853, as well.
