### ISSUE TITLE
Android 10 storage APIs are unsupported

### ISSUE THREAD

**Issue by DerrickRocha** [afollestad/material-dialogs#1984]
**Library Version:**

Files 3.3.0
 
**Affected Device(s):**
 
Galaxy s9 Android 10
 
**Describe the Bug:**

Directory listings are empty with the galaxy s9 running android 10. This happens regardless of read permissions beings set.

**To Reproduce:**
1. Show a material dialog using files module.
2. Notice the list will be empty on some devices.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/1934
