### ISSUE TITLE
Compatibility with older version broken!

### ISSUE THREAD

**Issue by stleusc** [afollestad/material-dialogs#199]
Simple 'Edit Dialog'

```xml
<?xml version="1.0" encoding="utf-8"?>
<EditText xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:text=""
    android:inputType="text">
</EditText>
```

```java
final EditText input = (EditText) LayoutInflater.from(getThemedContext()).inflate(R.layout.alert_dialog_edittext, null);

new MaterialDialog.Builder(this)
                .customView(input, true)
...
```

If you did this in older version (before the option to not use scrollview was added) it look great.
The textbox had perfect padding at all.
Now, with current version it looks totally skewed.

A fix is appreciated!

**Comment by afollestad** [comment]
You mean it needs padding? You can do so manually through your layout. I don't consider anything to be wrong in the library related to this.

**Comment by stleusc** [comment]
No, I consider it wrong!
2 reasons: 
a) It worked in the past
b) using the scrollview is adding the padding

I think it's rather unprofessional behavior to close issues without even trying it out.

**Comment by afollestad** [comment]
Trying it out? It's in the sample project, and I use it in personal apps. It gets plenty of testing.

This library is not at version 1.0, it's a beta library. You should expect changes. I had complaints that I was explicitly setting padding around custom layouts, custom layouts should have the flexibility to have custom padding. It is not wrong.

**Comment by stleusc** [comment]
Nope the sample does NOT have a simple Input Dialog!
You set the padding when scrolllayout is used, don't you?
customView(view, true) <-- padding is set
customView(view, false) <-- padding is NOT set

I use the first version in which you SET padding. This padding is added to the EditView and screwing it up.
Would LOVE to see a working example of this in the sample app but it only has a more complex layout....

**Comment by afollestad** [comment]
Actually, there's two. The web view and color chooser example both DO NOT use a scroll view.

**Comment by afollestad** [comment]
Just so you know, I did not make this change myself. The developer of Nova Launcher, Kevin Barry, did it. I side with his decision.

**Comment by stleusc** [comment]
And again: I USE the scroll view!!!!
And I add a simple EditView and it looks BROKEN.

**Comment by afollestad** [comment]
You know what, I'm not gonna help you if you're gonna talk to me like that.

Fix it yourself and make a pull request if you think it's so broken. I'm a 19 year old who has a full time programming job, with a social life, and college. This is an OPEN SOURCE project.

**Comment by stleusc** [comment]
Your comments made your age pretty clear....

**Comment by afollestad** [comment]
Yeah, almost 20. Thanks.

**Comment by afollestad** [comment]
I've been programming for 7 years and I'm majoring in computer science and applied mathematics. Age means nothing.

**Comment by afollestad** [comment]
However, I do see what you're talking about with the layout glitch. That's very odd.

**Comment by stleusc** [comment]
It seems like you were not really reading what I wrote, so here again a summary:

a) I am using the scrollview feature you provide
b) you are adding the padding
c) it looks skewed
d) there is no existing example that uses a simple single EditView as content

So I still think it's broken....

**Comment by stleusc** [comment]
Sorry, but are you saying you now agree that there could be an issue?

**Comment by afollestad** [comment]
Looks like it's related specifically to the fact that the library sets padding to your custom view itself. EditTexts generally do not pad themselves correctly, I think Kevin must've changed how this works a bit.

As a temporary work around, you can wrap your EditText in a FrameLayout so the parent view gets the padding.

**Comment by stleusc** [comment]
Thanks for acknowledging the bug....
Yes, I could warp the EditText but since I use that construct rather extensively I requires some more rework on my end.
A fix on the Library side would be appreciated.

**Comment by afollestad** [comment]
Sorry for the misunderstanding.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.1.1

**Comment by stleusc** [comment]
Thanks! Testing right now... I clean up some of the comments above...

**Comment by stleusc** [comment]
Appreciate the quick fix! Now it works again as expected...
Well done!

**Comment by afollestad** [comment]
Awesome, no problem!
