### ISSUE TITLE
Collaborators required

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#2014]
This project is awesome. Unfortunately, Material Dialog has lack of collaborators. The only admin on this project is you, @afollestad. To fasten the development, you need to add some people to became this library's successors. Collaborators can help you managing this project while you are in busy.

You can invite collaborators into this project by opening Settings -> Manage access -> Invite collaborators, or you can open this link instead: https://github.com/afollestad/material-dialogs/settings/access

Let us know if you want to open recruitment.

**Comment by afollestad** [comment]
I'm well aware how to add contributors.
