### ISSUE TITLE
How to change color of radio buttons in SettingsActivity?

### ISSUE THREAD

**Issue by Unpublished** [afollestad/material-dialogs#202]
Hey, I'm currently trying to change the color of the radio buttons in a dialog started from a SettingsActivity.
The problem is that passing the context results in black radio buttons and black text...the text can be changed by overwriting colorAccent and md_item_color but the radio buttons remain black :(

Is there another way than using a custom list selector? :)

**Comment by afollestad** [comment]
The radio buttons are controlled by AppCompat, the colorAccent attribute. Material dialogs can't control that past styles.xml
