### ISSUE TITLE
Button Text is Clipped at the Bottom When Device is set to Display Large Font Sizes

### ISSUE THREAD

**Issue by arrmixer** [afollestad/material-dialogs#2026]
*Please consider making a Pull Request if you are capable of doing so. Note that versions before 2.0.0 are no longer supported.*

**Library Version:**

3.1.1
 
**Affected Device(s):**
Samsung S8+ Android with Android 9.0
Samsung S9 Android with Android 10.0

On the pixel 3a emulator with Android 10.0 with both text size and display size at max , it has no issues. 
 
**Describe the Bug:**
The Action Button Text is clipped when the user decides to increase the display font size on his/her device to a higher level, for example, the max level. 

**To Reproduce:**
1. Have the device's font size set to maximum 
2. Show the dialog with the new font size setting.
3. should see a similar result 

<img width="384" alt="Screen Shot 2020-10-21 at 2 59 19 PM" src="https://user-images.githubusercontent.com/8250269/96771797-2fad7200-13b0-11eb-824b-a6377ecab69b.png">
<img width="386" alt="Screen Shot 2020-10-21 at 2 54 54 PM" src="https://user-images.githubusercontent.com/8250269/96771808-34722600-13b0-11eb-929d-bbb85e41489d.png">

**Expected Behavior:**
The fonts of the action buttons should not be clipped at the bottom 

If there is a workaround I could do like change the margins/padding from the buttonsLayout view, I'm happy with that solution.

**Comment by arrmixer** [comment]
I was able to do a workaround adjusting the text size like this:
`.show {
                        this.view.buttonsLayout?.findViewById<Button>(R.id.md_button_positive)?.textSize = 12.0f
                        this.view.buttonsLayout?.findViewById<Button>(R.id.md_button_negative)?.textSize = 12.0f
                        lifecycleOwner(viewLifecycleOwner)
                    }`
I know it the next release we can change the global font-size settings but only wanted to change these.

**Comment by cemilakan** [comment]
I've added to dimens **md_action_button_textsize** value to set action buttons text size
`<dimen name="md_action_button_textsize">14sp</dimen>`
