### ISSUE TITLE
Enter/Exit Animation 

### ISSUE THREAD

**Issue by nishant-lb** [afollestad/material-dialogs#203]
I used material dialogs in DialogFragment inside onCreateDialog and also wanted apply enter/exit animation but animation is not working.

**Comment by afollestad** [comment]
As far as I know that's not related to this library. MaterialDialog inherits the stock AlertDialog so nothing is different with animations.

**Comment by nishant-lb** [comment]
Thanks for the reply.
Will look into this and update here.

**Comment by nishant-lb** [comment]
Silly mistake. 
getDialog().getWindow().getAttributes().windowAnimations = R.style.DialogAnimation; 
it should be inside onActivityCreated() instead onCreatedDialog.
