### ISSUE TITLE
upgrading my older java app to android SDK 29

### ISSUE THREAD

**Issue by mobile-simformsolutions** [afollestad/material-dialogs#2030]
I am upgrading my older java app to android SDK 29.
In this app, I am using this library with version 0.9.6.0. but its give me an error like below

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc.android.debug/com.abc.android.activities.MainActivity}: android.view.InflateException: Binary XML file line #23 in com.abc.android.debug:layout/abc_screen_simple_overlay_action_mode: Binary XML file line #23 in com.abc.android.debug:layout/abc_screen_simple_overlay_action_mode: Error inflating class androidx.appcompat.widget.FitWindowsFrameLayout`

**Comment by afollestad** [comment]
Sorry, but nothing here is related to material-dialogs at all.
