### ISSUE TITLE
MaterialDialogs library on Android 5 Lolipop

### ISSUE THREAD

**Issue by brainvision** [afollestad/material-dialogs#204]
Hi Aidan, thanks for this library! Amazing work!

we are using it into our last project that (still to be released) but we noticed that it seems to not work as planned with Lollipop itself.. 
Can you confirm it? I'm using a Nexus 7 3G with unofficial L build (at today Google still did not released OTA and factory images for tilapia! :( ).

thanks a lot!

**Comment by afollestad** [comment]
I use Lollipop on my Nexus 6, it was developed and tested on Lollipop. Might be an issue with your unofficial build.

**Comment by afollestad** [comment]
Thank you though

**Comment by brainvision** [comment]
mmm.. thanks for replying Aidan..

btw we also tried it into AS emulator and the result is exactly the same.. No margins and the edit text field is completely messed up! :(

this is for example how it looks on emulated Nexus 6.. :( 
while on real KitKat devices it is perfect and also margins are just fine..

maybe did we miss something? Do you have any suggestion please?

![test](https://cloud.githubusercontent.com/assets/229026/5855321/41caafa2-a237-11e4-8d70-b428ea5192e9.png)

**Comment by afollestad** [comment]
Try out the latest library version, and try it on a real device

**Comment by brainvision** [comment]
ehi @afollestad 

here I am again..
so, the problem was not the emulator nor the unofficial build I'm running on my Nexus 7 (in fact your sample was running fine since the beginning) but only the 

android:fitsSystemWindows 

options we set to true for global styles xml..
Now we have this option to true only for pre v21; on Lollipop it is not necessary so we are working on the better solution; but the good is that we find the reason why dialogs were so ugly on Lollipop!

I added the [SOLVED] tag to my issue, hoping it could be useful for someone, someday!

Thanks a lot, see ya! ;)

**Comment by afollestad** [comment]
But the thing is, they're not. I've been using Lollipop since the first
developer preview. My dad, my girlfriend, and a lot of users and my apps
and libraries have Lollipop. This library was built for it and there's no
issues whatsoever.

**Comment by brainvision** [comment]
I know it, in fact I was talking about "my issue" (regarding the use of fitsSystemWindows to true), not about MD issue!

easy.. never said you did a bad work! on the contrary, I think your library is really good and it's becoming every day better and better! I was just asking if I need to set something particular for Lollipop, you said no, I go on searching and trying and finally I understand why on MY app it looks ugly.. that's all..

BTW, I'll edit the title so that it would be better to understand
