### ISSUE TITLE
MaterialDialogCompat is deprecated

### ISSUE THREAD

**Issue by dmsherazi** [afollestad/material-dialogs#205]
MaterialDialogCompat is deprecated, what should be used instead?

**Comment by eneim** [comment]
In the readme:

Migration from AlertDialogs

If you're migrating old dialogs you could use MaterialDialogCompat. You need change imports and replace AlertDialog.Builder with MaterialDialogCompat.Builder:

... But it's highly recommended to use original MaterialDialog API for new usages.

I guess this answers your question.

**Comment by afollestad** [comment]
Yeah, this question shows you didn't read any docs.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/README.md

**Comment by bradsh** [comment]
Assuming the whole reason I use your library at all was for a drop in solution, what is the new drop in solution?

If I have to rewrite hundreds of dialogs because you decided to remove this, I'll just quit using your library entirely...

**Comment by afollestad** [comment]
@bradsh the uses are all showcased in the large front page tutorial. Go ahead - it's open source and free, using it or not using it doesn't affect me in the least.
