### ISSUE TITLE
Make more 2.x and 3.x versions available from Maven Central

### ISSUE THREAD

**Issue by JvmName** [afollestad/material-dialogs#2051]
Hi! Today JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I know a lot of tooling goes into artifact upload to a repository, so I wanted to throw a signal flare up now so nobody is caught by surprise on May 1.

**Comment by JvmName** [comment]
In case it makes your life any easier, there's a tool that Martin Bonnin developed that seems to make this pretty straightforward: https://github.com/martinbonnin/vespene

**Comment by anggrayudi** [comment]
Better move to [OSS Sonatype](https://oss.sonatype.org/) (free for open source) and use this [Maven Gradle Plugin](https://github.com/vanniktech/gradle-maven-publish-plugin/) to publish this library. Vanniktech's Maven Gradle Plugin is the easiest plugin for me. Another advantage of OSS Sonatype is you can publish snapshots version, which is very helpful to test Material Dialog before putting it on stable versions.

Before you create an account on OSS Sonatype, you had better change your domain from [af.codes](https://af.codes/) to `afollestad.com`, or change Material Dialog's group ID to `codes.af`. They will verify your domain before registering your group ID.

**Comment by afollestad** [comment]
> Better move to [OSS Sonatype](https://oss.sonatype.org/) (free for open source) and use this [Maven Gradle Plugin](https://github.com/vanniktech/gradle-maven-publish-plugin/) to publish this library. Vanniktech's Maven Gradle Plugin is the easiest plugin for me. Another advantage of OSS Sonatype is you can publish snapshots version, which is very helpful to test Material Dialog before putting it on stable versions.
> 
> Before you create an account on OSS Sonatype, you had better change your domain from [af.codes](https://af.codes/) to `afollestad.com`, or change Material Dialog's group ID to `codes.af`. They will verify your domain before registering your group ID.

I own afollestad.com, aidanfollestad.com, and af.codes.

I will migrate when I have some free time.

**Comment by afollestad** [comment]
Here we are: https://repo1.maven.org/maven2/com/afollestad/material-dialogs/

**Comment by arkon** [comment]
Any chance for getting earlier versions too? The latest version unfortunately has some blocking issues from being used for some devices.

**Comment by afollestad** [comment]
Unfortunately it's a pretty manual process since Bintray did not require ASC files, thus forcing me to generate them or checkout old branches and republish them (haven't tried doing that yet). 

What version do you need?

**Comment by arkon** [comment]
I'm currently using 3.1.1, as newer versions result in issue #1957.

**Comment by casolorz** [comment]
Sorry if this isn't the right place to ask, since I am on a pretty old version, could I just download the AAR somehow?

**Comment by afollestad** [comment]
Alright, every version should now be available on Maven Central: https://repo1.maven.org/maven2/com/afollestad/material-dialogs/

**Comment by casolorz** [comment]
I'm assuming I'm not the only one stuck on `0.8.6.2` because `AlertDialogWrapper` was removed on `0.9.0.0` 

Would it be possible to add that version as well?

Also, I do plan on modifying my code at some point to remove `AlertDialogWrapper` but a substantial amount of my code is still on Java, is it possible for you to add the last version that supports Java applications if that isn't supported anymore on newer versions?

Thank you.

**Comment by afollestad** [comment]
The Java versions are all there.

**Comment by casolorz** [comment]
Thanks, didn't realize that.
