### ISSUE TITLE
Auto-Stacking broken with only positive and negative button

### ISSUE THREAD

**Issue by UweTrottmann** [afollestad/material-dialogs#206]
Auto-stacking does not work with only a positive and a negative button. Can be reproduced with sample app by using long positive button text.

[These lines of code](https://github.com/afollestad/material-dialogs/blob/v0.6.1.2/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L736-L740) left align the negative button to the positive button, so the negative button may get squished if the positive button is too wide.

Hence the total width checked in [`checkIfStackingNeeded()`](https://github.com/afollestad/material-dialogs/blob/v0.6.1.2/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L609-L626) is always equal to the parent layout width, `isStacked` remains `false`.

Top of the head I'm not sure how to fix this, maybe find a way to measure the text width beforehand.

**Comment by afollestad** [comment]
The newer algorithm for this was implemented via a pull request: https://github.com/afollestad/material-dialogs/pull/190

@mariusmuja could you possibly look into this?

**Comment by mariusmuja** [comment]
Pushed a fix in #207.

**Comment by afollestad** [comment]
Release 0.6.1.3 is now available and the Gradle dependency is updated.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.1.3
