### ISSUE TITLE
Is there any way to change the title or message text size?

### ISSUE THREAD

**Issue by daehan-lim** [afollestad/material-dialogs#2067]
I would like to be able to change the core MaterialDialog's text size. It looks too small in tablets and barely visible. Is there a way to change it either overriding a theme resource or changing it programmatically with findViewById?

**Comment by daehan-lim** [comment]
Oh, I just found out that overriding md_title_textsize and md_message_textsize in dimens.xml does the job

**Comment by cemilakan** [comment]
> Oh, I just found out that overriding md_title_textsize and md_message_textsize in dimens.xml does the job

It's works smoothly 👍
```
<resources>
    <dimen name="md_title_textsize">18sp</dimen>
    <dimen name="md_message_textsize">14sp</dimen>
</resources>
```
