### ISSUE TITLE
Not applying material theme on AutoCompleteTextView

### ISSUE THREAD

**Issue by kwosu87** [afollestad/material-dialogs#209]
Hi, I'm using this for dialog which contains AutoCompleteTextView.

Your libraries works with EditText but AutoComplete TextView(object extending EditText).

Is there any way to apply material theme into AutoCompleteTextView?

Thank you.

![screenshot](https://cloud.githubusercontent.com/assets/2222333/5851791/7b872f50-a24f-11e4-962c-b1e0d4819422.png)

**Comment by afollestad** [comment]
I would expect that to be an issue with AppCompat, not my library
