### ISSUE TITLE
I have a trouble with Dialog fragment

### ISSUE THREAD

**Issue by kulik** [afollestad/material-dialogs#210]
http://screencloud.net/v/dubc this is from simple list 

show fragment code  new CamGalDialog().show(frg.getFragmentManager(), "dialog");

     public class CamGalDialog extends DialogFragment {
         private static final int CAMERA = 0;
         private static final int GALLERY = 1;
     
         @Override
         public Dialog getDialog() {
             return new MaterialDialog.Builder(getActivity())
                     .items(R.array.cam_gal_items)
                     .itemsCallback(new MaterialDialog.ListCallback() {
                         @Override
                         public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                             switch (which) {
                                 case CAMERA:
                                     AddPhotoActivity.goToPhotoActivityFromCamery(getActivity());
                                     break;
                                 case GALLERY:
                                     AddPhotoActivity.goToPhotoActivityWithGallery(getActivity());
                                     break;
                             }
                         }
     
                     }).build();
         }
     }

this is arrays content

    <string-array name="cam_gal_items">
        <item>Camera</item>
        <item>Gallery</item>
    </string-array>

**Comment by afollestad** [comment]
See the sample project
