### ISSUE TITLE
notifyDataSetChanged cause some lag

### ISSUE THREAD

**Issue by pongpatr** [afollestad/material-dialogs#212]
When called notifyDataSetChanged() you will experience some lag.

**Comment by afollestad** [comment]
There's not much I can do about that, sorry.

**Comment by pongpatr** [comment]
Just want to explain more.

I think it something because how dialog measure listView size again when notifyDataSetChanged() is called.

The problem is not because my adapter because I try to place the same listview in difference place and it operate normally.

**Comment by afollestad** [comment]
Hmm I kinda see what you mean now; it's actually noticeable with the "Folder Chooser" example in the sample project. This'll have to be looked into more.

**Comment by afollestad** [comment]
I improved the lag a bit by recycling views in the ButtonItemAdapter used in the sample project.

If you're using your own adapter, make sure you're recycling views.
