### ISSUE TITLE
Do not set hardcoded font if no font was specified in builder

### ISSUE THREAD

**Issue by svenjacobs** [afollestad/material-dialogs#213]
We're using [Calligraphy](https://github.com/chrisjenx/Calligraphy) to set a custom font globally in our application. However [MaterialDialog](https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L97) sets the font hardcoded to Roboto when no found has been specified through the builder. We would like to not have to specify the custom font again just for MaterialDialog.

MaterialDialog should not force the dialog to use the Roboto font. The typeface should only be explicitly set when a typeface has been specified through the builder.

**Comment by afollestad** [comment]
This is now in the repository: https://github.com/afollestad/material-dialogs/commit/bc3b3b3955f79ad34e14b51a2d3498bfb24ee8f9

It will be included in the next release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.1.6

**Comment by afollestad** [comment]
This was further improved in the latest release.

https://github.com/afollestad/material-dialogs/releases/tag/v.0.6.2

**Comment by svenjacobs** [comment]
Thanks!

**Comment by afollestad** [comment]
One more update to how this all works:

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.1
