### ISSUE TITLE
The import com.afollestad.materialdialogs.DialogAction cannot be resolved

### ISSUE THREAD

**Issue by mnabilmughal** [afollestad/material-dialogs#215]
Hi 
I hope you will be good. I don't know why I am getting this error. 
I imported the library project into eclipse that is the library folder. Then I made this as  library project and then used in my project and I am getting the import error. Googling around and trying different tweaks for 3-4hours I had to post the issue here. May be anyone can help me here. ???
Thanks

**Comment by pongpatr** [comment]
What have you try?
How do you import the library?

You should only post the issue related to lib.

**Comment by afollestad** [comment]
Sorry, you're using Eclipse. I can't help you. Eclipse is replaced by Android Studio and this library is intended to be used with Gradle, not as an Eclipse library project. 

If you search through past issues, there's another one related to Eclipse.

**Comment by mnabilmughal** [comment]
@pongpatr  Thanks for your response. I am importing library as suggested by brainvision per this https://github.com/afollestad/material-dialogs/issues/30 post. But I never get free from errors in library project. I ended up with The import android.support.v7.widget.GridLayoutManager cannot be resolved error in RecyclerUtil.java file. So, Couldn't get through it Any help would be appreciated @pongpatr . 

@afollestad  Dear I seen already in issues you have told to move to AS. I am newbie and I again ended up with issue in AS too, the very common issue Gradle project sync failed. So, I have to go to the Eclipse again. I tried to solve this issue with different suggestions on internet e.g. Changing "runProgaurd" to "minifyEnabled" . But was unable to solve it if you can suggest me with AS a good working solution It would be great right now I am stuck on both. 

BTW Thank you both for your quick response.

**Comment by afollestad** [comment]
@mnabilmughal 

Android Studio requires you to insert one line into your build.gradle file, like the README says.

![screen shot 2015-01-24 at 12 14 09 pm](https://cloud.githubusercontent.com/assets/1820165/5888390/8e498088-a3c2-11e4-8540-a2ab5e7e3856.png)

```Gradle
compile 'com.afollestad:material-dialogs:0.6.1.5'
```

**Comment by afollestad** [comment]
The only part you need is what's inside of dependencies, the stuff above and below that don't matter.

**Comment by afollestad** [comment]
@mnabilmughal the errors you mentioned to @pongpatr in your last comment above are Gradle issues, because Eclipse is not setup to use Gradle like Android Studio is.

**Comment by pongpatr** [comment]
@mnabilmughal 
You may need to spend sometime to get familiar with Android Studio project structure. But believe me it worth spend sometime migrating to AS.

As far as I know, there is no easy way to import AS project to Eclipse project. You may try by follow this: https://confluence.jetbrains.com/display/IntelliJIDEA/Working+in+Eclipse+Compatibility+Mode

**Comment by mnabilmughal** [comment]
Thank you both of you.
I believe now that AS is really very powerful. It removes most of your headache. I solved the issue I mentioned previously. http://stackoverflow.com/questions/26689513/errorcompilesdkversion-android-21-requires-compiling-with-jdk-7 this post helped me to solve it. 

Again Thanks a lot for the quick response and help really appreciate it. :-)
