### ISSUE TITLE
setOnCheckedChangeListener for MultiChoice List

### ISSUE THREAD

**Issue by Chirag-Galani** [afollestad/material-dialogs#216]
I need a setOnCheckedChangeListener for MultiChoice elements. Also, is it possible to add a divider in between as i want to seperate the set in 2 halves on a single material dialog.
An example as how I intend to implement:

        checkBox.setOnCheckedChangeListener( new OnCheckedChangeListener() {
      @Override
      public void onCheckedChanged(CompoundButton arg0, boolean arg1) {
     // TODO Auto-generated method stub
    Toast.makeText(getApplicationContext(), "Check box "+arg0.getText().toString()+" is "+String.valueOf(arg1) , Toast.LENGTH_LONG).show();
     }
    } );

Edit: Got solution.

**Comment by pongpatr** [comment]
For setting the divider, you could add your custom view to the builder.

**Comment by Chirag-Galani** [comment]
Solution: https://github.com/afollestad/material-dialogs/blob/master/sample/src/main/java/com/afollestad/materialdialogssample/MainActivity.java#L391

**Comment by afollestad** [comment]
That isn't how you do it for multi choice lists, that's just for checkboxes in a custom view. Multi choice lists are in both the README and sample project. 

You can add dividers using `getListView().setDivider()` on a dialog instance, however using dividers there is not Material.

**Comment by afollestad** [comment]
Unless you meant in a custom view. The question title and content are kind of in two different places.

**Comment by Chirag-Galani** [comment]
I wanted the multichoice list with OnCheckedChangeListener

**Comment by afollestad** [comment]
See the multi choice list section in the README file

**Comment by Chirag-Galani** [comment]
You mean this method right? 
alwaysCallMultiChoiceCallback()

**Comment by afollestad** [comment]
No, `itemsCallbackMultiChoice()`, which will tell you which times are checked when the user presses the positive action button in your dialog. 

`alwaysCallMuliChoice()` makes that callback get called every time the user checks or unchecks a check box, rather than waiting until the button is pressed. This is all in the README documentation if you read it.

**Comment by Chirag-Galani** [comment]
Ya, i read it but I had special needs. In my Multichoice fragment if the user selected the 1st option (Title: ALL) then, other options gets automatically checked and put to disabled state (setEnabled(false)). And, on unchecking 1st option all other options are unchecked and back to enabled state.
So, for this reason I went ahead with custom view. I hope the picture is clear enough now. If, I'll share a screenshot as soon as the work is done.

**Comment by afollestad** [comment]
Ohhh, I see. You can use setSelectedIndices() to set which items are
checked in the regular multi choice list.

**Comment by Chirag-Galani** [comment]
Sure, I will try that too. 
Btw, thanks for this awesome library.
