### ISSUE TITLE
Medium font for action button

### ISSUE THREAD

**Issue by plusCubed** [afollestad/material-dialogs#217]
Due to bc3b3b3 (removal of hard-coded Roboto fonts), the action buttons no longer have the medium font.
Fix: use "sans-serif-medium" fontFamily on 5.0+ by default and bold style on <5.0 by default.

See `fonts.xml`  in `values` and `values-v21` folders in Cabinet (which I implemented): https://github.com/afollestad/cabinet/tree/master/app/src/main/res

**Comment by afollestad** [comment]
Unfortunately I start class again tomorrow but I'll work on this when I have a little time

**Comment by plusCubed** [comment]
Actually, I happen to have some time right now (didn't earlier in the day). I'll see what I can do.

**Comment by afollestad** [comment]
One more update to how this all works:

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.1
