### ISSUE TITLE
Title style is not the correct one

### ISSUE THREAD

**Issue by Babelia13** [afollestad/material-dialogs#219]
The current style for the dialog title is not the same which is specified in official documentation:
http://www.google.com/design/spec/components/dialogs.html#dialogs-specs.

I think the correct style can be consulted in the typograpy section of the material design documentation (http://www.google.com/design/spec/style/typography.html#typography-standard-styles). Specifically, it is title style, with "Medium 20sp" style.

**Comment by afollestad** [comment]
This was accidentally undone in a recent commit that removes default
typefaces, it's coming back

**Comment by plusCubed** [comment]
I believe this should be fixed with #218.

**Comment by afollestad** [comment]
One more update to how this all works:

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.1
