### ISSUE TITLE
Allow for specific font path setting

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#220]
I noticed in `TypefaceHelper` that it assumes that all passed in Typefaces follow the `fonts/<name>.ttf` scheme, but that's not always the case. We use `.otf`, so this breaks things for us. Could we have a little more flexibility with this?

**Comment by afollestad** [comment]
I'll try to work on this when I have time aside from college classes.

**Comment by afollestad** [comment]
I actually don't think it's necessary to change this, the `typeface(Typeface, Typeface)` method still works fine; I just undeprecated it.

**Comment by hzsweers** [comment]
That works, thanks!
