### ISSUE TITLE
Link text background color when pressed

### ISSUE THREAD

**Issue by KDB223** [afollestad/material-dialogs#221]
Hey again.
I've set a custom view to a dialog via `.customView` which contains a couple of different TextViews.
One of them has `<a>` links in its string resource, and although the links work just fine, they don't give any visual feedback, like a highlighted background color, when tapped.
It behaves as expected in a normal TextView in a layout though. 
Perhaps this is a bug?

BTW, I call `setMovementMethod(LinkMovementMethod.get instance())` on the TextView.

**Comment by afollestad** [comment]
This isn't an issue with the material-dialogs
