### ISSUE TITLE
font init problem

### ISSUE THREAD

**Issue by Stroncickiy** [afollestad/material-dialogs#224]
my app can't use MD because its brakes with such error: 
native typeface cannot be made
at TypefaceHelper when method get from this class was  called  in init of MaterialDialog   with signature like this:
      mBuilder.mediumFont = TypefaceHelper.get(getContext(), "Roboto-Medium");
why this problem hapened? 
sorry for English..

**Comment by Stroncickiy** [comment]
I fix it just added Roboto fonts to my app   assets/fonts/

**Comment by afollestad** [comment]
Hmmm. It should be pulling fonts from the library, not your app. It seems
to be working for me by default.

**Comment by afollestad** [comment]
I can't reproduce this issue.

**Comment by rzeh4n** [comment]
I had same problem in Eclipse. Copying dir fonts into my app's assets dir fixed that. And I need to use these two fonts myself anyway.

**Comment by afollestad** [comment]
I would currently suspect that to be a build issue if you aren't using Android Studio and the latest Gradle.
