### ISSUE TITLE
Custom Title Bar

### ISSUE THREAD

**Issue by patelakshay13890** [afollestad/material-dialogs#225]
How to show Custom Title Bar with Button & it's Click listener..??
expecting positive & quick response...

**Comment by egor-n** [comment]
I would not use a title bar at all in this case. Just create a custom view, which contains everything you need and don't set title to the dialog.

**Comment by afollestad** [comment]
Use a custom view and hide the dialog title by not specifying one

**Comment by patelakshay13890** [comment]
Okay & thanx for quick response..!!!

**Comment by patelakshay13890** [comment]
How o i can change Background Color of Positive Negative Button Color ?
& It is Possible to give only Border to these Buttons with out Changing the
Original Height ?

**Comment by afollestad** [comment]
See the "Themed" dialog in the sample project.

`btnSelector()` is mentioned in the README too: https://github.com/afollestad/material-dialogs#theming
