### ISSUE TITLE
CustomView on Android2.3

### ISSUE THREAD

**Issue by fine1021** [afollestad/material-dialogs#226]
I see your layout file , you use the FrameLayout for the CustomView, It's OK on Android 4.0+ ,but when it comes to Android 2.3, The customView will offset to the left , I have met this problem, I just replace with RelativeLayout, maybe there are some bugs on Android 2.3 using the FrameLayout ???

**Comment by afollestad** [comment]
Yeah, there's quite a few issues related to margin and padding on 2.3

**Comment by Matungos** [comment]
I have the same problem.
