### ISSUE TITLE
Gravity setting seems to be broken in the most recent version

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#231]
```java
new MaterialDialog.Builder(this)
    .title("Test")
    .titleGravity(GravityEnum.CENTER)
    .show();
```

The above code will still show the title aligned to the left. Same thing happens with `contentGravity`

**Comment by afollestad** [comment]
Odd, it seems to be working in the 'Themed' dialog of the sample project.

**Comment by afollestad** [comment]
This is working fine for me, including through the Gradle dependency. I just tested it through Cabinet.

**Comment by MrBrightside29** [comment]
Isn't working for me either using the last release.

**Comment by afollestad** [comment]
It works in both the sample project and Cabinet for me. Are you using Lollipop?

**Comment by afollestad** [comment]
It works on 4.4.4 for me also.

**Comment by MrBrightside29** [comment]
Yes, I'm using Lollipop.

**Comment by MrBrightside29** [comment]
With the latest release seems fixed! Thanks for you efforts!
