### ISSUE TITLE
Using 0.6.2.1, Builder.titleColor does not apply White

### ISSUE THREAD

**Issue by omniuni** [afollestad/material-dialogs#233]
When working with the builder to theme the dialog, I have tried titleColor and also titleColorRes, and neither change the title of the dialog title to white. I eventually went with a slightly off-white color, and I am using that for now. When attempting to set the color to white, the text remained black.

**Comment by afollestad** [comment]
Wow, one of the weirdest bugs I've ever seen. There's no reason that should happen.

**Comment by afollestad** [comment]
I wonder if the issue is that white equals -1, in which case the library would assume there is no color set.

**Comment by afollestad** [comment]
It appears the issue is that white is equal to -1. The library currently interprets -1 as no color set. I'll have to find a better default value.

**Comment by afollestad** [comment]
I found a solution, this will be fixed in the next release
