### ISSUE TITLE
BtnStackedGravity not work

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#234]
I have updated to the latest version 0.6.2.2 and stacked buttons are in all cases in middle. Setting .btnStackedGravity(GravityEnum.END) or .btnStackedGravity(GravityEnum.START) does not work. Example:

```java
new MaterialDialog.Builder(getActivity())
		.title(getString(R.string.title))
		.content(R.string.content)
		.positiveText(R.string.positive)
		.neutralText(R.string.neutral)
		.negativeText(R.string.negative)
		.forceStacking(true)
		.btnStackedGravity(GravityEnum.END)
		.show();
```

**Comment by afollestad** [comment]
I just tested this and it's working fine

**Comment by afollestad** [comment]
Also, END is the default gravity.

**Comment by TomasValenta** [comment]
Sorry, but in my case, gravity is always center (also in default case, that's why I also started to solve). I move back to version 0.6.2.1 and it's fine like before update...

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1
