### ISSUE TITLE
MaterialDialogCompat item/button listeners

### ISSUE THREAD

**Issue by jamolkhon** [afollestad/material-dialogs#235]
OnClickListener passed to setSingleChoiceItems is called after setPositiveButton/setNeutralButton/setNegativeButton listeners.

**Comment by afollestad** [comment]
This is not specific to `MaterialDialogCompat`. That class just wraps around the non-deprecated `MaterialDialog.Builder` API.

This is also intended behavior. The button is pressed, and then the item callback is sent.
