### ISSUE TITLE
Full Screen Dialogs 

### ISSUE THREAD

**Issue by y2kshane** [afollestad/material-dialogs#241]
Add support for full screen dialogs . 
![components_dialogs_fullscreen5](https://cloud.githubusercontent.com/assets/5099806/6060957/21d7dae8-ad69-11e4-97e2-37e446cfb786.png)

**Comment by RubyDerBoss** [comment]
+1

**Comment by afollestad** [comment]
That's not a dialog at that point. That's an Activity with a changed home up indicator. A dialog is a dialog cause it's not full screen.

**Comment by afollestad** [comment]
This is an example of my comment above. It's an Activity.

![Uploading screenshot.png . . .]()

**Comment by gpulido** [comment]
Just as a comment, I disagree about being "just" an activity, as it should be showed as a "full-screen" only on mobile, and as dialog on big screen tablets. It would be nice if the library could handle the logic  automatically. Also another interesting feature is that the library could also manage the buttons on top with the styled that is defined on the material design specs.

**Comment by afollestad** [comment]
You would use the DialogOnLarge theme with an Activity to achieve this.
