### ISSUE TITLE
Dialog title margins are wrong

### ISSUE THREAD

**Issue by felipebari** [afollestad/material-dialogs#243]
My dialog's title has no left margin, and top and bottom margins are appearing too small on latest version (0.6.2.3).

![material dialog](https://cloud.githubusercontent.com/assets/3378355/6074592/fe316484-ada8-11e4-906c-4e07c1d0aec3.png)

Here's how I'm starting the dialog.

```java
new MaterialDialog.Builder(this)
                .title(R.string.some_title)
                .content(R.string.some_text)
                .positiveText(R.string.dialog_yes)
                .negativeText(R.string.dialog_no)
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        // My code.
                    }
                })
                .show();
```

Any idea why that's happening?

**Comment by afollestad** [comment]
Well, first of all, the latest version is 0.6.2.1.

This looks like it's probably an issue with the version of Android you're using. A few older versions don't correctly respect margins, while there's no issues with newer versions.

**Comment by felipebari** [comment]
You're correct, that was a typo. I'm actually on 0.6.2.3. My device is a Moto X running Lollipop, so the version shouldn't be an issue.

**Comment by afollestad** [comment]
Very weird. It works fine running on my Nexus 6 with Lollipop:

![Screenshots](https://github.com/afollestad/material-dialogs/blob/master/art/screenshots.png)

I have no idea why that would happen.

**Comment by felipebari** [comment]
Looks like I'm not the only one with this issue. http://goo.gl/u6ytPx

Seems to be a problem with `android:fitsSystemWindows="true"`. I'll let you know if removing this from my styles fixes the problem.

**Comment by afollestad** [comment]
Wow, very weird.

One of my apps (Cabinet) uses that attribute in order to make the navigation drawer overlap the status bar. Cabinet's dialogs work fine. You must be setting the attribute in a weird spot.

**Comment by felipebari** [comment]
Yep, that's it. Works fine without `android:fitsSystemWindows="true"`.

![material dialog 2](https://cloud.githubusercontent.com/assets/3378355/6074720/cc17d20a-adab-11e4-94f2-4981f32b9c39.png)

I'm setting the flag in my app's main theme. It's weird that it affects the dialogs.

```java
<style name="Light_Theme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:fitsSystemWindows">true</item>
</style>
```

Since it also happens with Lollipop's regular dialogs, I think you can close the issue as invalid.

Thanks for the help!

**Comment by afollestad** [comment]
Those attributes get applied to every view in your entire app. E.g. if you set `android:background` there, it would get applied to every view the user sees. `fitsSystemWindows` belong elsewhere, such as on views in your layouts.

No problem!

**Comment by felipebari** [comment]
Thanks for the tip! The idea was to have all my layouts inherit that property easily, but I never thought it would be applied to dialogs as well (since it didn't before on KikKat). Now that I no longer need the flag (I had it set for the SystemBarTint library) I'll just remove it entirely.
