### ISSUE TITLE
NullPointerException in MaterialDialog.sendMultichoiceCallback when no items provided

### ISSUE THREAD

**Issue by sagilo** [afollestad/material-dialogs#244]
I use Database to populate multi choice dialog.
In a certain scenario there are no items to populate the list.
In this case the dialog is shown with no items (as expected) but as clicking the OK button, NullPointerException exception is thrown in MaterialDialog.java (764).
Notice 'selectedIndicesList' is initialized only if 'items' AND 'callback' are provided but accessed only when callback is provided (not checking the items condition), hence we get an exception.

Thank you

**Comment by afollestad** [comment]
Well if it happens at line 764, you must have an old version of the library, cause that's not what exists at line 764. But I'll look into it elsewhere.

**Comment by sagilo** [comment]
Line 806 in latest version.
"for (Integer i : selectedIndicesList) {"

**Comment by afollestad** [comment]
This will be in the next release.

https://github.com/afollestad/material-dialogs/commit/63fa5124f8a25cbaa15b2daab4505424b5b8f513

**Comment by afollestad** [comment]
This will be published very soon

**Comment by afollestad** [comment]
0.6.2.4 is now available.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.4

@sagilo
