### ISSUE TITLE
Enter and exit animation methods in the Builder

### ISSUE THREAD

**Issue by devishankar** [afollestad/material-dialogs#245]
Is it possible to add enter and exit animation to MaterialDialog.Builder?

**Comment by afollestad** [comment]
Well, I've never used these features so I don't know the fastest way to do it other than with themes which you don't need additional methods for. http://stackoverflow.com/a/13537234/309644

**Comment by afollestad** [comment]
Other than using themes like that link above:

```java
MaterialDialog alertDialog = new MaterialDialog.Builder(this).setTitle("Example").create();
alertDialog.getWindow().getAttributes().windowAnimations = R.style.DialogAnimation;
alertDialog.show();
```

`MaterialDialog` is an `AlertDialog` instance.

**Comment by vineethjas** [comment]
MaterialDialog alertDialog = new MaterialDialog.Builder(this).setTitle("Example").create();

.create is not working

**Comment by afollestad** [comment]
That's not how the library works. 

There's an entire tutorial on the front page for a reason (and a sample project).

**Comment by vineethjas** [comment]
That means there is no way to set enter and exit animation in material dialog? It will be better if can include it too...

**Comment by afollestad** [comment]
There is, not with the Builder though. 

`MaterialDialog` is just an `android.app.Dialog`, which is what the `build()` method of the `Builder` returns; you can set animations on the Dialog like you can with any other Dialog on Android.

**Comment by vineethjas** [comment]
I m a newbie in android. I gone through complete documentation that you provided. When creating dialog .show() method is called right. Then how can I set animations through

alertDialog.getWindow().getAttributes().windowAnimations = R.style.DialogAnimation;
this method? Help me if can..

**Comment by afollestad** [comment]
You would need something like this:

```java
MaterialDialog dialog = new MaterialDialog.Builder(this)
    .title(R.string.title)
    .content(R.string.content)
    .build();

dialog.getWindow().getAttributes().windowAnimations = R.style.DialogAnimation;

dialog.show();
```

**Comment by vineethjas** [comment]
Atlast got it. Thanks man..

**Comment by Mason-Fan** [comment]
It seems that we can only set the dialog animation before calling show() function. after that, we cannot change the animation. it you want to change the animation setting, you have to call dismiss() first.

http://stackoverflow.com/questions/32908279/change-dialogfragment-enter-exit-transition-at-just-before-dismissing

@afollestad , just want to know whether you have any workaround for this issue?
