### ISSUE TITLE
"md_negative_color" attribute not being respected in app theme

### ISSUE THREAD

**Issue by ryan-envoy** [afollestad/material-dialogs#247]
Every other attribute I have tried works just fine, but "md_negative_color" does not respect my custom color.

I'm testing on a Nexus 5 running KitKat (4.4.4).

If you need more specifics in order to solve this issue, please let me know.

**Comment by afollestad** [comment]
I'll look into it, thanks

**Comment by afollestad** [comment]
@ryan-envoy could you possibly me setting a negative color somewhere? It works fine for me:

![screenshot_2015-02-10-14-22-45](https://cloud.githubusercontent.com/assets/1820165/6135701/5c53d986-b130-11e4-96ed-c3f13bb5dc9c.png)

**Comment by afollestad** [comment]
I think this is now fixed: https://github.com/afollestad/material-dialogs/issues/252

It will be in the next release.
