### ISSUE TITLE
DialogFragment

### ISSUE THREAD

**Issue by Rainer-Lang** [afollestad/material-dialogs#248]
Why not use DialogFragment like:
https://github.com/avast/android-styled-dialogs
-> "Built on top of standard DialogFragment"

**Comment by afollestad** [comment]
`MaterialDialog` is an `AlertDialog`. It works the same way as a stock AlertDialog, and requires you to manually wrap them in a `DialogFragment` if you need it. The sample project has two DialogFragment examples.
