### ISSUE TITLE
Add progress dialog (as android.app.ProgressDialog)

### ISSUE THREAD

**Issue by frmz** [afollestad/material-dialogs#250]
It would be great to also have a ProgressDialog equivalent

**Comment by Tuxilero** [comment]
Bump, would be great to see that in next version.

Good job by the way! :+1:

**Comment by afollestad** [comment]
It wouldn't be different enough from the stock dialog. They'd be basically identical so this isn't necessary.

**Comment by frmz** [comment]
@afollestad this is true if you are running on Lollipop but if you are running on Android 4.4 or lower the progress dialog will have an Holo look

**Comment by afollestad** [comment]
Oh yeah, good point

**Comment by afollestad** [comment]
Done

**Comment by afollestad** [comment]
Release 0.6.3.0 is now available

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.0

**Comment by frmz** [comment]
You rock
