### ISSUE TITLE
Support for default value in MaterialListPreference

### ISSUE THREAD

**Issue by cmc00022** [afollestad/material-dialogs#251]
Hello,

I'm just trying out your new MaterialListPreference, as always it works as expected, but I miss something.  There is no support for default value to be marked on the list that shows up when using MaterialListPreference. If you need help I could have a further look at the code and do a PR.

Thanks in advanced.

**Comment by Unpublished** [comment]
Maybe we can use itemsCallbackSingleChoice instead of itemsCallback?
Additional upside would be show radio buttons just like in Lollipop's ListPreference.

**Comment by afollestad** [comment]
This is now done and will be in the next release

**Comment by afollestad** [comment]
Release 0.6.3.0 is now available

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.0
