### ISSUE TITLE
button color bug

### ISSUE THREAD

**Issue by pomcro** [afollestad/material-dialogs#252]
maybe you wrong write code;

        mBuilder.neutralColor = DialogUtils.resolveColor(mBuilder.context, R.attr.md_negative_color, mBuilder.neutralColor);
        mBuilder.negativeColor = DialogUtils.resolveColor(mBuilder.context, R.attr.md_neutral_color, mBuilder.negativeColor);

 R.attr.md_neutral_color and R.attr.md_negative_color,

**Comment by afollestad** [comment]
Thanks for finding this, it will be fixed in the next release

**Comment by afollestad** [comment]
Release 0.6.3.0 is now available

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
