### ISSUE TITLE
Font asset not found in fonts/Roboto-Medium.tff

### ISSUE THREAD

**Issue by mkay007** [afollestad/material-dialogs#255]
I am getting a RuntimeException with the error above. I think it is a Lollipop specific bug/
![screen shot 2015-02-15 at 11 45 11 pm](https://cloud.githubusercontent.com/assets/10864535/6203271/bb97ebb8-b56c-11e4-9718-ce24c064d453.png)

**Comment by afollestad** [comment]
Hmm, I don't think it's Lollipop specific, all that I use is Lollipop

**Comment by mkay007** [comment]
This is the dialog I am using. I am aware that you can't set content as well as a checkbox, which by the way might be a nice feature to add. I will create a workaround with a custom view in the meantime.

dialog = new MaterialDialog.Builder(main).title(R.string.fetus_title).positiveText(R.string.done)
				.callback(new MaterialDialog.ButtonCallback() {
					@Override
					public void onPositive(MaterialDialog dialog) {
						if (update) {
							...
						}
					}
				}).items(R.array.fetus_update_array).itemsCallbackMultiChoice(null,
					new MaterialDialog.ListCallbackMulti() {
						@Override
						public void onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
							...
						}
					}).content(dialogMessage).show();

**Comment by afollestad** [comment]
The original issue here has actually been reported 3 times before but I'm never able to reproduce it myself on any version of Android.

**Comment by jemshit** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=608&thanks=608&ts=1404735239

**Comment by jj6335** [comment]
Your font extension should be .ttf, and not .tff.
