### ISSUE TITLE
API 10: custom view aligned left and no rounded corners

### ISSUE THREAD

**Issue by djpeinado** [afollestad/material-dialogs#257]
Hi,
I experienced a couple of issues running on API 10:
- Custom view layout is not center aligned
- No rounded corners and grey border (I don't know if dialog rounded corners are allowed on api 10)

This is my code and my custom view layout:

```
		MaterialDialog dialog = new MaterialDialog.Builder(this).title("Title")
				.customView(R.layout.dialog_foo, true)
				.positiveText("OK")
				.build();
		dialog.show();
```
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
			  android:layout_width="match_parent"
			  android:layout_height="match_parent"
			  android:orientation="vertical"
			  android:padding="16dip"
			  android:background="#ff0000">

	<EditText
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:hint="foo"
			android:inputType="text"
			android:maxLines="1"/>


</RelativeLayout>
```

Screenshots from emulator API 10 and API 21

![captura de pantalla de 2015-02-16 12 50 22](https://cloud.githubusercontent.com/assets/1162202/6211552/6d507cbc-b5db-11e4-948d-763bb705b560.png)

![captura de pantalla de 2015-02-16 12 53 05](https://cloud.githubusercontent.com/assets/1162202/6211549/66fe4484-b5db-11e4-8f0e-3b28018305ba.png)

Nice job. Thank you.

**Comment by afollestad** [comment]
I actually didn't intend to support API 10, someone else did it through pull requests (twice, the second time after I removed support). Gingerbread and below tend to have issues correctly respecting margin and padding.

**Comment by iahvector** [comment]
My workaround is pass `wrapInScrollView` as false in `builder.customView(R.layout.dialog, wrapInScrollView)` and wrap my custom view in a ScrollView and set `paddinRight="24dp"` and `paddingLeft="24dp"` on the layout container

```xml
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="24dp"
        android:paddingRight="24dp" >

        <TextView
            android:id="@+id/textView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </RelativeLayout>
</ScrollView>
```

**Comment by teslacoil** [comment]
I looked at the round corners (as even in 4.x they're inconsistent across android versions and OEMs, slightly different colors, and setting the dialog color makes them completely square). There isn't a good way of doing it. Android styling does allow changing the dialog background, but that also causes it to use a different layout which has different margins, and you can't supply your own layout as it uses private resource ids.
It is possible to change the drawable at runtime by traveling up the view hierarchy, or intercepting the resource call, but this is hacky and doesn't seem worth including in the library.

**Comment by afollestad** [comment]
Yeah, I agree.
