### ISSUE TITLE
Indeterminate ProgressBar not set to colorAccent on Android 4.x

### ISSUE THREAD

**Issue by dbleicher** [afollestad/material-dialogs#258]
The library is great, and the following is not a big deal, you might want to consider this an enhancement request for the future.

On Android 4.x the indeterminate progressbar (spinning circle) is not set to colorAccent (it remains the default silver).  I've tested this on a Note 3 (4.4.4) and in the emulator on Android versions back to 4.0.3.

1. Download and install the Sample app from Google Play Store onto a 4.x device or emulator, you will note that the progressbar remains silver (should be red/pink from the theme).

2. In my code, passing in a properly themed context does not solve the issue.  For example, the following theme:

'''

    <style name="Theme.Nightowl" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/wguPrimary</item>
        <item name="colorPrimaryDark">@color/wguPrimaryDark</item>
        <item name="colorAccent">@color/wguGold</item>

        <item name="md_icon">@drawable/owl5</item>
        <item name="md_positive_color">@color/wguPrimary</item>
        <item name="md_neutral_color">@color/wguPrimaryDark</item>
        <item name="md_negative_color">@color/wguGold</item>

    </style>
'''

And the following code:

            new MaterialDialog.Builder(new ContextThemeWrapper(this, R.style.Theme_Nightowl))
                    .title("Retrieving All Messages in Thread")
                    .content("please wait...")
                    .progress(true, 0)
                    .show();

Will produce a dialog that DOES have the icon (so, it is reading the theme), but does not use the accent color for the progressbar.

**Comment by afollestad** [comment]
Not sure there's much I can do about this unfortunately. 

Manually creating progress bar drawables myself would not be efficient.

**Comment by dbleicher** [comment]
Understood @afollestad , I'll take a closer look myself, but it may be more trouble than it's worth.  I brought it up because in the README for the new progress dialog, the first sentence claims this capability for both Lollipop and AppCompat.  For now, this specific capability is only available for Lollipop.

**Comment by dbleicher** [comment]
Howdy.  I've found a fairly easy fix to make this work on Android 4.x and 5.x (have not tested with anything older than API 15).  I apologize that I have not yet learned how to create/test a proper patch and submit a pull request (I really need to learn those).  So here's a user-land view of the fix (from code that uses your library).  I believe you will know where in the code this should properly go.  Sorry for the inconvenience.

                pd = new MaterialDialog.Builder(this)
                    .title("Retrieving All Messages in Thread")
                    .content("please wait...")
                    .progress(true, 0)
                    .build();


            View v = pd.getCustomView();
            for(int i=0; i<((ViewGroup)v).getChildCount(); ++i) {

                View nextChild = ((ViewGroup)v).getChildAt(i);

                if (nextChild instanceof ProgressBar) {

                    TypedValue typedValue = new TypedValue();
                    TypedArray a = obtainStyledAttributes(typedValue.data, new int[] { R.attr.colorAccent });
                    int accentColor = a.getColor(0, 0);
                    
                    ((ProgressBar)nextChild).getIndeterminateDrawable()
                            .setColorFilter(accentColor, PorterDuff.Mode.SRC_IN);
                    break;
                }
            }
            
            pd.show();

The final line before the break statement does all the work.  Everything else is just finding the proper view and getting the app theme's accentColor.  Hope this helps, and thanks for a great library.

**Comment by afollestad** [comment]
Good idea, didn't think of using a color filter

**Comment by afollestad** [comment]
This can actually be applied to both the indeterminate drawable and the regular progress drawable, it works for both surprisingly. It will be in the next release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1

**Comment by afollestad** [comment]
This will be even more customizable with the next release: https://github.com/afollestad/material-dialogs/commit/92eac3e5541f4066a52eaf496ed75c82d28c5af2

**Comment by metalurgus** [comment]
Please pay attention: this problem appears as well for RadioButtons, and maybe some other views
