### ISSUE TITLE
Gravity not working in sony phone

### ISSUE THREAD

**Issue by kcsanjaya** [afollestad/material-dialogs#261]
Hello, i am using the latest version of material dialogs. I am having issue with setting content gravity. I tested my app in sony and samsung phones. For samsung(4.0.3) there is no any problem but for sony(4.4.4) gravity is not working. I have set title gravity center but title is at start in the sony xperia m2 kitkat 4.4.4

In samsung(4.0.3)
![](https://cloud.githubusercontent.com/assets/10799983/6225981/fe3063d6-b6b8-11e4-9398-04664f9f560d.png)

In sony(4.4.4)
![](https://cloud.githubusercontent.com/assets/10799983/6225991/14ae722e-b6b9-11e4-9bf4-0368bc717fdd.png)

**Comment by kcsanjaya** [comment]
![samsung](https://cloud.githubusercontent.com/assets/10799983/6225981/fe3063d6-b6b8-11e4-9398-04664f9f560d.png)
![sony](https://cloud.githubusercontent.com/assets/10799983/6225991/14ae722e-b6b9-11e4-9bf4-0368bc717fdd.png)

**Comment by afollestad** [comment]
Hmmm, setting center gravity to the title is working for me on 4.4.4:

![screen shot 2015-02-17 at 1 51 48 pm](https://cloud.githubusercontent.com/assets/1820165/6235980/2bfe0ea6-b6ac-11e4-8114-4ec63e790d24.png)

**Comment by afollestad** [comment]
This should hopefully be fixed now with the latest commits. It won't go live as a release until it's tested a bit more.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
