### ISSUE TITLE
Passing 'null' argument to parameter annotated as @NotNull

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#262]
When I use null in Multi Choice dialog, Android Studio show the warning:
**passing 'null' argument to parameter annotated as @NotNull.**

![Screen](http://www.yetanotherview.cz/tmp/null-warning.png)

**Comment by afollestad** [comment]
Fixed, will be in the next release

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1
