### ISSUE TITLE
How to Lock dialog box?

### ISSUE THREAD

**Issue by niketkadde** [afollestad/material-dialogs#264]
Hello,
If I want to lock any dialog, how can we do that? 
Lock dialog means, dialog will not dismiss until and unless user clicks any of the button/item in dialog. Currently if user clicks black transparent area or  back button of device dialog gets dismissed. I want user to choose from dialog then only dialog will get dismissed.

**Comment by afollestad** [comment]
The same way it's done with a stock Alert Dialog
