### ISSUE TITLE
More flexibility with custom typeface

### ISSUE THREAD

**Issue by anthony-skr** [afollestad/material-dialogs#265]
Hello,

I would like to use my own .OTF fonts assets, but as for now it is not possible because of hard-coded file information :

```Java
                Typeface t = Typeface.createFromAsset(
                        c.getAssets(), String.format("fonts/%s.ttf", name));
```

Is it possible to permit to pass our own asset filename, for more flexibility ?

Regards,
Anthony Skrzypczyk

**Comment by afollestad** [comment]
That's what `typeface(Typeface, Typeface)` is for

**Comment by jorge-costa-bold** [comment]
I have the same problem. I need to use a custom .OTF fonts but is not possible =/
