### ISSUE TITLE
Allow content to be set in addition to items

### ISSUE THREAD

**Issue by jenzz** [afollestad/material-dialogs#270]
Hi there!

Not sure if this is intended behaviour or not,
but if you set both `.content()` and `.itemsCallbackMultiChoice()` on your dialog,
the content will never be shown.

I would expect it to be displayed above the multi-choice options.

Your thoughts?

**Comment by afollestad** [comment]
Currently, this is intended behavior

**Comment by iraycd** [comment]
Great library.
:+1: I needed this feature. Waiting for this enhancement.

**Comment by afollestad** [comment]
Done https://github.com/afollestad/material-dialogs/commit/921e17c89275578847d13d9983aceb59012a132b

**Comment by afollestad** [comment]
Release 0.6.3.2 is available now.

**Comment by jenzz** [comment]
Yay! Thanks for the prompt fix :smile:

**Comment by iraycd** [comment]
:+1: Thank you.
