### ISSUE TITLE
Single choice lists highlight all radios on press in v15

### ISSUE THREAD

**Issue by msutherland4807** [afollestad/material-dialogs#271]
Only tested on emulator, but pressing a list item in v15 will highlight all other radios. Happens with custom adapters too (using standard one in picture)

Here is my code:

```java
new Builder(getActivity())
		.items(R.array.pref_list_units_titles)
		.itemsCallbackSingleChoice(0, new ListCallback()
				{
					@Override
					public void onSelection(MaterialDialog materialDialog, View view, int i, CharSequence charSequence)
					{
						unitsText = units[i]);
						btnUnits.setText(unitsText);
					}
				})
		.show();
```

![img](https://cloud.githubusercontent.com/assets/5905483/6319942/51e07aaa-ba85-11e4-9b11-31fc5203a75c.png)

**Comment by msutherland4807** [comment]
If someone could test below v15 that'd be awesome (it's the lowest I have access too right now). Thanks

**Comment by afollestad** [comment]
Unfortunately there's not much I can do about this.

This is an AppCompat issue on lower API levels.

**Comment by afollestad** [comment]
Also, you can use AVD or Genymotion to test lower API versions.
