### ISSUE TITLE
NumberPicker Dialog?

### ISSUE THREAD

**Issue by kkl260** [afollestad/material-dialogs#273]
Thanks for the great Library. Anyone know if there is a way to have a number picker in these dialogs? I tried to do something like this but it didn't work:

private void showNumberPicker() {
        new MaterialDialog.Builder(this)
                .title("Pick number")
                .content(R.layout.number_picker_dialog_layout)
                .positiveText("set")
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        //set number
                    }
                }).show();

 NumberPicker numberPicker = (NumberPicker) (this).findViewById(R.id.numberPicker);
        numberPicker.setMinValue(2);
        numberPicker.setMaxValue(30);
        numberPicker.setWrapSelectorWheel(false);
        numberPicker.setOnValueChangedListener(new NumberPicker.OnValueChangeListener() {
            @Override
            public void onValueChange(NumberPicker picker, int oldVal, int newVal) {
                numberResult = numberPicker.getValue();

            }
        });
    }

**Comment by afollestad** [comment]
You should read the README documentation and sample project.

**Comment by afollestad** [comment]
content() takes @StringRes integers, not @LayoutRes.

**Comment by kkl260** [comment]
Thanks I figures it out.
