### ISSUE TITLE
Dismiss or cancel dialogs programmatically

### ISSUE THREAD

**Issue by pcevikogullari** [afollestad/material-dialogs#274]
Is there a way to dismiss or cancel MaterialDialogs programmatically? Because in some conditions, I need to call cancel method after a successful result.

**Comment by egor-n** [comment]
```java
MaterialDialog dialog = new MaterialDialog.Builder(ctx).....show();
// ...
dialog.dismiss();
```

**Comment by afollestad** [comment]
Same as an AlertDialog, like the above comment.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)

**Comment by ziedrebhi** [comment]
there is no method called .dismiss()

**Comment by afollestad** [comment]
Look at the comment above you.
