### ISSUE TITLE
MaterialListPreference doesn't use dialogTitle xml property

### ISSUE THREAD

**Issue by msutherland4807** [afollestad/material-dialogs#275]
Easy fix, just like with MaterialEditTextPreference (sorry I can't figure out how to make a Pull Request with just one file changed)

**Comment by afollestad** [comment]
Fixed https://github.com/afollestad/material-dialogs/commit/a20241b6d15c1c4b54e83d5d915ce1336e7ce138

**Comment by afollestad** [comment]
Release 0.6.3.2 is available now.
