### ISSUE TITLE
MaterialEditTextPreference should display dialogMessage value

### ISSUE THREAD

**Issue by mendhak** [afollestad/material-dialogs#276]
In a regular `EditTextPreference`, you can have four properties which are displayed in different areas:
 
     <EditTextPreference
            android:key="key1"
            android:title="aaa"
            android:summary="bbb"
            android:dialogTitle="ccc"
            android:dialogMessage="ddd"
            android:defaultValue="lorem ipsum"
            />

So the preference appears like so (`title`, `summary`)

![image](https://cloud.githubusercontent.com/assets/746276/6379308/21d0b46e-bd29-11e4-90c1-2bc33a9ec85e.png)

And on clicking the preference, the dialog appears like so (`dialogTitle`, `dialogMessage`)

![image](https://cloud.githubusercontent.com/assets/746276/6379298/107b6a92-bd29-11e4-9b5f-17b47a97c39d.png)

Currently the MaterialEditTextPreference does not show `dialogMessage` property when the dialog opens.

![image](https://cloud.githubusercontent.com/assets/746276/6379729/49161df4-bd2c-11e4-8d93-3c31efdf7df9.png)

THanks for all your work on this library, it has made life so much better.

**Comment by afollestad** [comment]
So, basically, `dialogMessage` should be displayed too. Lol

**Comment by afollestad** [comment]
Done https://github.com/afollestad/material-dialogs/commit/7e4ac46a412f9c663957e458c66744acf6d314c8

**Comment by afollestad** [comment]
Release 0.6.3.2 is available now.
