### ISSUE TITLE
Is there any way to make the background transparent?

### ISSUE THREAD

**Issue by osrl** [afollestad/material-dialogs#277]
`.backgroundColor(Color.TRANSPARENT)` didn't work for me. It shows white background. How do I make the background transparent?

**Comment by afollestad** [comment]
If it was possible, it would be the same as an alert dialog.

**Comment by osrl** [comment]
I wanted your theme, but also I wanted some opacity. You say this is not possible?

**Comment by afollestad** [comment]
Sorry, no. This library is designed to make dialogs that match the design guideline specs.

**Comment by osrl** [comment]
I think you are right. Regards to my graphic designer :)
