### ISSUE TITLE
Buttons paddings seems to be wrong

### ISSUE THREAD

**Issue by Aracem** [afollestad/material-dialogs#278]
As shows in the attached image, when the string of the buttons are a little big, the padding between buttons are missed. 

![dialog_bug](https://cloud.githubusercontent.com/assets/2283594/6394876/d78df0ea-bdd4-11e4-9672-cd72f7799424.png)

Am I doing something wrong?

**Comment by afollestad** [comment]
Hmm, that's very weird. I switched around the positive text for one of the dialogs in the sample project to use a longer string, it stills works fine for me.

![md](https://cloud.githubusercontent.com/assets/1820165/6424676/7ef21066-bec8-11e4-840c-90c2f26a4ec6.png)

**Comment by Aracem** [comment]
Yes, its very weird :S

Here is one of my "builds". I use a wrapper to create different Dialogs inside the app (like, do you want to login, do you want to finish this, do you want to logout...) but I not do nothing special on it more like set text, colors and that kind of things:

                new MaterialDialog.Builder(activity)
                        .title(R.string.broadcast_stop_dialog_title)
                        .titleColorRes(R.color.app_text_black)
                        .content(R.string.broadcast_stop_dialog_content)
                        .contentColorRes(R.color.app_text_dark)
                        .btnSelector(R.drawable.selectable_item_background_red, DialogAction.POSITIVE)
                        .btnSelector(R.drawable.selectable_item_background_grey, DialogAction.NEGATIVE)
                        .positiveColorRes(R.color.app_text_red)
                        .positiveText(R.string.broadcast_stop_btn_yes)
                        .negativeText(R.string.broadcast_stop_btn_no)
                        .negativeColorRes(R.color.app_text_dark)
                        .autoDismiss(true));

The only thing I guest that could be it's the selectable background (I override to put special colors), Perhaps it's doing something weird with the paddings. Let me check if it works with the default selectable background.

**Comment by afollestad** [comment]
Just a tip, there's a way to do syntax highlighting that doesn't involve indentation ;) https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

But I know why it's not working for you; if you look at the default selectors used in this library, they reference inset drawables. For an example: https://github.com/afollestad/material-dialogs/blob/master/library/src/main/res/drawable/md_btn_selected.xml

**Comment by Aracem** [comment]
Yes, that's the problem. I remove the selectable and all works.

Thanks for the tip of the selectors, I didn't know it :) I had a bug in other part of the app similar to this. It explains a lot of things hehehe

*Thank you very much*, I am going to close the issue. 
(Perhaps you can put a little tip in the selectors part advise about the use of inset!)
