### ISSUE TITLE
Multi Choice List Dialog - Listener callback order

### ISSUE THREAD

**Issue by phil443** [afollestad/material-dialogs#280]
Hi, I've just integrated the material dialogs library into my application, and it's mostly looking and functioning great, however I've encountered an issue with the Multi Choice List Dialog.

When using `.itemsCallbackMultiChoice(..)` and `.callback(..)` with `MaterialDialog.Builder`, the `onSelection(..)` method in `MaterialDialog.ListCallbackMulti()` appears to be called AFTER the `onPositive(..)` method in `MaterialDialog.ButtonCallback()`. In the debugger the `onSelection(..)` callbacks appear to queue up and then all fire in sequence after the positive button is pressed and the onPositive method is called.

This makes it rather difficult to perform actions on the selected/deselected items since that information hasn't actually been made available before the `onPositive(..)` method is called. 

An example of code using the Material Dialog builder:
```java
MaterialDialog dialog = new MaterialDialog.Builder( getActivity() )
    .title( R.string.layer_options_dialog_title )
    .items( R.array.map_layer_options_array )
    .itemsCallbackMultiChoice( getSelectedLayers(), new MaterialDialog.ListCallbackMulti()
    {
        @Override
        public void onSelection( MaterialDialog dialog, Integer[] selectedItems, CharSequence[] text )
        {
            // This is only being called AFTER 'onPositive(..)' below
        }
    } )
    .positiveText( android.R.string.ok )
    .negativeText( android.R.string.cancel )
    .callback( new MaterialDialog.ButtonCallback()
    {
        @Override
        public void onPositive( MaterialDialog dialog )
        {
            // Any 'onSelection(..)' calls should have occurred BEFORE this method is called
        }
    } )
    .build();
```

Note that I'm using the above code (with some method calls in place of the comments in the callback methods) in the `onCreateDialog(..)` of a `DialogFragment`.

The same behavior occurs using the `AlertDialogWrapper` and so exhibits different behavior to the native `AlertDialog`. Thus it can't really be used to just drop in to existing `AlertDialog` code. In the native `AlertDialog`, the `onSelection(..)` equivalent method, `onClick(..)`, is called as each checkbox is checked/unchecked and not just after the `onPositive` method is called. 

For now I'll have to stick with the native `AlertDialog` in this case (wrong colors and all) but would switch back to the material dialog in a heartbeat if a solution is found to this problem. I appreciate the work you are doing, cheers.

**Comment by afollestad** [comment]
Well, as a temporary workaround, you can use `alwaysCallMultiChoiceCallback()` in the `Builder` to make the multi choice callback get invoked everytime the user checks or unchecks a checkbox.

I will switch the order for the next release, so that `onPositive()` for the positive action button is called before `onSelection()` of the multi choice callback is called.

**Comment by afollestad** [comment]
Wait, hold on, I misread this a little I think. `onPositive()` is invoked before `onSelection()`, as far as I know there shouldn't be any ordering issues with that.

**Comment by afollestad** [comment]
Wait, I misread this a bit. onPositive() is called before onSelection(), this is currently intended behavior. It makes sense, since the action button is actually pressed first, which is what invokes the selection callback.

But like I said in the comment above, `alwaysCallMultiChoiceCallback()` might be a workaround for your situation.

**Comment by phil443** [comment]
I wasn't aware of that option, which sounds like what I might need. Thanks.
