### ISSUE TITLE
Error:Failed to find: com.android.support:appcompat-v7:21.0.3

### ISSUE THREAD

**Issue by am2222** [afollestad/material-dialogs#281]
Hi,
I am going to add this liberary to my project but I get this error Error:Failed to find: com.android.support:appcompat-v7:21.0.3 This is build.gradle 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.peomtime.tosca.peomtime"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.android.support:support-v4:21.0.2'
    compile 'com.android.support:appcompat-v7:21.0.+'
    compile 'de.hdodenhof:circleimageview:1.2.0'
    compile 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    //Core
    compile 'com.github.gabrielemariotti.cards:cardslib-core:2.0.1'
    compile 'com.github.machinarius:preferencefragment:0.1.1'

    //compile 'com.github.nirhart:parallaxscroll:1.0'
    compile project(':Parallax')

    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'

    compile 'com.afollestad:material-dialogs:0.6.3.1'
}

**Comment by afollestad** [comment]
That isn't an issue with my library, AppCompat is a Google library. It's used by the sample project. Try rebuilding the project.

**Comment by msutherland4807** [comment]
Open your SDK manager and make sure you have the latest version of the support library and repository. Judging by your build.gradle I'm guessing you only have version 21.0.2 where this library uses 21.0.3

**Comment by hex6ng** [comment]
I'm getting the same error whenever I include 
<pre>
compile 'com.afollestad:material-dialogs:0.6.3.5'
</pre>

The project compiles just fine without it.

These have already been included:
<pre>
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-annotations:21.0.3'
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.android.support:recyclerview-v7:21.0.3'
</pre>
