### ISSUE TITLE
Custom Progress Dialog

### ISSUE THREAD

**Issue by patelakshay13890** [afollestad/material-dialogs#282]
How can we Show Custom Progress Dialog with Custom Rim Color in ProgressDialogue in this Lib. ??
How can can change Title & Content Text Color of ProgressDialogue also ??
Can we have Dark Theme for the same ProgressDialogue ..??
expecting +ve response..!!!

**Comment by afollestad** [comment]
"Expecting a response" with exclamation points makes you sound pretty entitled. 

You should read the README file or look at the sample project.

**Comment by patelakshay13890** [comment]
But There is no Method for setting Color dynamically for Progressbar...

**Comment by afollestad** [comment]
Just like stock progress dialogs, it gets the color from the `colorAccent` attribute of your theme.

**Comment by afollestad** [comment]
Just like stock progress dialogs and other fields of any app, it gets the color from the `colorAccent` attribute of your theme.

**Comment by afollestad** [comment]
I decided to implement this for the next release: https://github.com/afollestad/material-dialogs/commit/92eac3e5541f4066a52eaf496ed75c82d28c5af2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0

**Comment by patelakshay13890** [comment]
[?]
