### ISSUE TITLE
Get input from custom layout

### ISSUE THREAD

**Issue by calindotgabriel** [afollestad/material-dialogs#283]
Hello, I'm trying to use your library to get some text inside a dialog.

The problem I'm struggling with is getting the text entered by the user after he closes the dialog.
I tried this approach:

        boolean wrapInScrollView = true;
        new MaterialDialog.Builder(this)
                .title("New Post")
                .customView(R.layout.dialog_new_dash, wrapInScrollView)
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        LayoutInflater layoutInflater = LayoutInflater.from(getBaseContext());
                        View v = layoutInflater.inflate(R.layout.dialog_new_dash, null);
                        EditText postMessage = (EditText) v.findViewById(R.id.edittext_new_dash_item);

                        String s = postMessage.getText().toString();
                    }
                })
                .positiveText("Done")
                .build()
                .show();
    }

But it does not seem to work.
Please reply when u have the time.
Your library is really cool by the way, very useful!

Thanks,
Gabriel

**Comment by afollestad** [comment]
You're inflating a new layout inside the dialog callback. You may wanna get a little more familiar with how Android works.

**Comment by afollestad** [comment]
To expand on what I mean, when you use `customView()`, it's inflating the view into the dialog. You're inflating a brand new view again later that is not in the dialog.

You should be using dialog.getCustomView() from inside the dialog callback.

**Comment by Going-Gone** [comment]
Hmm, Confused by what he means when he says use the dialog.getCustomView()
Where at are you telling him to use it? 
I am having the same issue, where my input is coming out to be null. 
![image](https://user-images.githubusercontent.com/28640954/39542865-44000736-4e0f-11e8-8c54-6155d2453447.png)

**Comment by afollestad** [comment]
@Going-Gone `inputName` is out of scope. `.customView(R.layout.dialog_server_url)` is inflating a new view with different child view references.

**Comment by afollestad** [comment]
The second usage in there is correct, where you use `findViewById` on `getCustomView()`.

**Comment by Going-Gone** [comment]
Thank you for the quick reply!
I was looking at ways so that i could use use the serverUrl variable within the whole dialog, but what I did was copied the calling for the EditText to the callback, and it worked. So basically i created two instances of it.
