### ISSUE TITLE
MaterialEditTextPreference throwing NullPointerException

### ISSUE THREAD

**Issue by mendhak** [afollestad/material-dialogs#285]
In v0.6.3.2, MaterialEditTextPreference has started throwing exceptions (in the sample app as well as my own)

>    Process: com.afollestad.materialdialogssample, PID: 28211
>        java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.widget.EditText.getBackground()' on a null object reference
>                at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.showDialog(MaterialEditTextPreference.java:62)

I think this is because the `mEditText` assignment was [removed](https://github.com/afollestad/material-dialogs/commit/7e4ac46a412f9c663957e458c66744acf6d314c8#diff-a80cccfef46e692e752af516ed1535d8L43) in an earlier commit.  So the [mEditText.getBackground](https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/prefs/MaterialEditTextPreference.java#L61) call is null.

I've created a pull request.  Hopefully it's easy to issue a new release?

**Comment by afollestad** [comment]
Release 0.6.3.3 is now available
