### ISSUE TITLE
Lollipop title bug

### ISSUE THREAD

**Issue by magnevox** [afollestad/material-dialogs#287]
Hi.

On Android 5+ I get "glUtilsParamSize : unknow param 0x00000bd0" while in emulator it looks like 
![image](https://cloud.githubusercontent.com/assets/5123520/6427028/ff63e610-bf73-11e4-8482-e45fc14b693c.png)

**Comment by afollestad** [comment]
I don't think there's much I can do about that, sounds like an emulator or computer issue. 

It works fine in emulators on my end.

**Comment by magnevox** [comment]
Ok, I found the problem. It was caused by ```<item name="android:fitsSystemWindows">true</item>```
