### ISSUE TITLE
No horizontal padding for custom view?

### ISSUE THREAD

**Issue by ciskeboekelo** [afollestad/material-dialogs#290]
I was surprised to find that when using a custom view and setting wrapCustomViewInScroll to true, no horizontal padding is set. From the readme I would've expected a 24dp padding since all examples shown at https://www.google.com/design/spec/components/dialogs.html#dialogs-specs have that 24dp padding.

Was it a delibarate decision not to include horizontal padding for the custom view in the scrollview?

**Comment by afollestad** [comment]
Yeah, it's a custom view, you're handling the content manually. You can add your own padding to your custom view in this case. There's some cases where users will not want guideline padding to be used by default.

**Comment by afollestad** [comment]
Actually, I looked into my code logic more and this is false.

There is padding applied to the view at line 217 if wrapCustomViewInScroll is true.

For an example, the custom view examples in the sample project that use a scroll view have spacing on the sides.

**Comment by afollestad** [comment]
E.g.

![screenshot_2015-03-04-10-09-33](https://cloud.githubusercontent.com/assets/1820165/6487407/9d998d1e-c256-11e4-86b0-d68dd74d56cd.png)

**Comment by ciskeboekelo** [comment]
Interesting. When I added just an EditText as a custom view, the width of the edittext was 100%. Don't have time to look into it right now, though, maybe later.

**Comment by afollestad** [comment]
@ciskeboekelo that could be considered a bug, but the problem is that padding is set to the custom view by the dialog. EditTexts cannot have horizontal padding set to them, it causes visual errors.

A temporary work around would be to wrap the edit text in a FrameLayout.

**Comment by afollestad** [comment]
Notice that the cursor respects the padding, but the background doesn't.

![md](https://cloud.githubusercontent.com/assets/1820165/6489368/6e7f9d5e-c263-11e4-91ac-48fdc0b58dba.png)

**Comment by afollestad** [comment]
@ciskeboekelo this is not fixed in https://github.com/afollestad/material-dialogs/commit/a459c829d4f339ac46d3267a0352aff06792e5d8 and will be in the next release

**Comment by afollestad** [comment]
@ciskeboekelo this is now fixed in https://github.com/afollestad/material-dialogs/commit/a459c829d4f339ac46d3267a0352aff06792e5d8 and will be in the next release

**Comment by afollestad** [comment]
Release 0.6.3.5 is now available.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.5
