### ISSUE TITLE
Custom view dialog with TableLayout uses all screen height

### ISSUE THREAD

**Issue by omarplastic** [afollestad/material-dialogs#291]
When using a custom layout with a TableLayout, it doesnt matter the content of the table, it takes the whole screen in height, as if were using match_parent. In phones doesnt look that bad, but in tablet is not a desirable effect.

                new MaterialDialog.Builder(mContext)
                        .customView(R.layout.dialog_info, true)
                        .positiveText(R.string.ok)
                        .build()
                        .show();

And the layout:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="@dimen/padding_large">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="@dimen/text_size_20"
        android:textStyle="bold"
        android:text="@string/details_property_title"/>

    <TableLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/margin_medium">

        <TableRow>
            <TextView
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:layout_column="1"
                android:textSize="@dimen/text_size_20"
                android:textStyle="bold"
                android:text="@string/details_property_points"/>

            <LinearLayout
                android:orientation="vertical"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="3">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="@dimen/text_size_20"
                    android:textStyle="bold"
                    android:text="@string/details_property_title"/>

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="@string/details_property_desc"/>

            </LinearLayout>
        </TableRow>

    </TableLayout>

</LinearLayout>

**Comment by afollestad** [comment]
There's not really any easy work around for this other than setting an explicit height or width to your table.
