### ISSUE TITLE
Title should be used as content if content is empty but title is not

### ISSUE THREAD

**Issue by conzorz** [afollestad/material-dialogs#293]
http://imgur.com/PzU7JZX

Too much space?

**Comment by afollestad** [comment]
You shouldn't use the title by itself. Stock alert dialogs actually use the title as the content in this case.

**Comment by afollestad** [comment]
6a38309de97dac7dfa17ed6ed014fc3fe33cbb7f

**Comment by conzorz** [comment]
Great, thanks.

Good job on this library too! :)

**Comment by afollestad** [comment]
Release 0.6.3.5 is now available with some improvements to this.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.5

**Comment by conzorz** [comment]
<3
