### ISSUE TITLE
setIcon drawable size dynamic scaling?

### ISSUE THREAD

**Issue by Gaudon** [afollestad/material-dialogs#297]
Is there anyway to modify the size of the icon in the dialog so that it scales regardless of the actual dimensions of the drawable (ie: 48x48 vs 96x96 vs 129x128)?

**Comment by afollestad** [comment]
There shouldn't be any issues with that. If you look at the dialog layout, the icon `ImageView` is set to `wrap_content`, with a scaleType of `fitXY`.

**Comment by Gaudon** [comment]
Interesting, I'm noticing that using larger image resources is causing the title to scale much larger, let me do a rebuild as an example.

**Comment by Gaudon** [comment]
Here's a comparison of a 48x48 icon and a 128x128 icon as 2 separate draw-able entities in the .setIcon() builder of the dialog.

![compare](https://cloud.githubusercontent.com/assets/1593839/6491431/ae38c190-c287-11e4-8491-37b1330db634.png)

**Comment by Gaudon** [comment]
Hmm I think I'm on an older version.. perhaps you recently fixed this, if that's the case my apologies for wasting your time. Let me add a + sign in the gradle dependency.

**Comment by Gaudon** [comment]
Oh I think I misunderstood you to begin with. You're saying it's already set to increase the title size based on the size of the drawable, where as I'm looking for a way to restrict that size of the title, independently of the size of the drawable.

**Comment by afollestad** [comment]
Not quite sure what you mean. The icon and title views are contained in the same parent, if the icon size increases it will push the title over to the right more.

**Comment by Gaudon** [comment]
Right, I'm simply asking if there is a way to restrict the size of the icon (such as saying, I want it to be 32dp x 32dp) regardless of the size of the drawable I pass in through .icon().

**Comment by afollestad** [comment]
Ohh, currently you'd need to modify the dialog layout file, or manually resize your drawable programatically.

The stock AlertDialog doesn't restrict the icon size so I didn't either.

**Comment by Gaudon** [comment]
Ah that's fair.. Feature request :D

in the meantime I'll do a workaround like you've suggested. Thanks all the same.

**Comment by andrewlord1990** [comment]
I have implemented this feature and have created a pull request for it #300.

**Comment by afollestad** [comment]
Release 0.6.3.5 is now available.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.5
