### ISSUE TITLE
Title loses formatting when using custom adapter (with no content)

### ISSUE THREAD

**Issue by teslacoil** [afollestad/material-dialogs#298]
Due to 6a38309d , a title + adapter, without content, causes the title to show as grey text and a smaller font, instead of the normal title formatting.

This can be fixed either by adding a check for the adapter in build, or reversing 6a38309d (as doesn't the title lose formatting for dialogs without content now? What is the purpose of moving the title to content if there is no content?)

**Comment by afollestad** [comment]
I'll have to look at this in a bit.

I noticed with stock AlertDialogs, if you set a title but no message, it displays the title as the message and doesn't show a title.

**Comment by afollestad** [comment]
@teslacoil let me know if https://github.com/afollestad/material-dialogs/commit/56d10ce1e7b7d51169254ffad023478f76a456f8 fixes it

**Comment by afollestad** [comment]
It appears to be fixed

**Comment by afollestad** [comment]
Release 0.6.3.5 is now available.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.3.5
