### ISSUE TITLE
Custom adapter apperance

### ISSUE THREAD

**Issue by magnevox** [afollestad/material-dialogs#302]
Hey.

I got problem with custom adapter list apperance. I made custom and inflate layout
``` LayoutInflater.from(getContext()).inflate(R.layout.md_listitem_singlechoice, parent, false);```
after that my list looks like: 

![image](https://cloud.githubusercontent.com/assets/5123520/6535258/f0fb854a-c443-11e4-9684-b9d5d93d5afe.png)

Have you any idea how to fix it?

**Comment by afollestad** [comment]
Well, you're using a custom adapter. You can use any layout you want, and modify the TextViews at will from your adapter or layout.
