### ISSUE TITLE
Support alwaysCallMultiChoiceCallback when using AlertDialogWrapper.Builder

### ISSUE THREAD

**Issue by askfor** [afollestad/material-dialogs#303]
Now we can't call alwaysCallMultiChoiceCallback when using AlertDialogWrapper.Builder

**Comment by afollestad** [comment]
That wrapper is meant for compatibility with apps that already use the stock AlertDialog. It's not meant to add features to that. If you want new features you should use this library's APIs.

**Comment by askfor** [comment]
Thanks for your quick response.
The stock AlertDialog will call DialogInterface.OnMultiChoiceClickListener every time when you check or uncheck items.
But alwaysCallMultiChoiceCallback default value is false. so it will break legacy code.

I think if we can't change alwaysCallMultiChoiceCallback  value, at least we should set it to true in AlertDialogWrapper.Builder.setMultiChoiceItems

**Comment by afollestad** [comment]
This is now in release 0.6.4.0

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.0
