### ISSUE TITLE
Simple menu

### ISSUE THREAD

**Issue by andrewlord1990** [afollestad/material-dialogs#307]
http://www.google.co.uk/design/spec/components/dialogs.html#dialogs-simple-menus

I wanted to use the Simple Menus mentioned in the Material design spec. However, for the time being I just used regular Material dialogs with a list of items, no title, message or buttons.

To add support for Simple Menus it feels like the changes that would be required are:
1. Specify position for the dialog to appear (over the list item selected)
2. Persistent scrollbar (if scrollable)
3. Highlight specified item
4. If close to screen edge, ensure that the dialog is pushed up so all elements are visible.

I was thinking of implementing this feature in the library, as it is part of the Dialogs material spec and also because it would be really handy!

**Comment by afollestad** [comment]
Well, generally you use PopupMenus for this, e.g:

![screenshot_2015-03-07-15-59-00](https://cloud.githubusercontent.com/assets/1820165/6543479/f3e95c24-c4e2-11e4-9b5e-144c7be8d658.png)

**Comment by andrewlord1990** [comment]
I knew about using them for a situation like in that screenshot. Never thought to use them for the Simple Menu situation, of selecting an option, awesome. Thanks.

**Comment by PaulWoitaschek** [comment]
The PopupMenu does not follow the specs for the simple menu. 

* On older devices its completely misthemed. 
* Also it has no top / bottom padding. 
* It does not center the selection above the underlying selection
* It cuts text
* It has no preselection

Are there any plans for supporting this?

See: https://material.google.com/components/menus.html#menus-simple-menus

![](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQscEN4TlItQ1R4d3c/components_dialogs_simplemenus2.png)

![](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsbXpoZkNIcXgxc3M/components_dialogs_simplemenus3.png)

**Comment by afollestad** [comment]
Those are a completely different UI pattern than what this library is designed for. This library extends `android.app.Dialog`, `PopupMenu` does not. It would need to go in a separate library, in my opinion.
