### ISSUE TITLE
In styles.xml, error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light.Dialog.Alert'.

### ISSUE THREAD

**Issue by drupalmav** [afollestad/material-dialogs#310]
Getting this error: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light.Dialog.Alert'.

Getting it in file: values-v21/styles.xml. 

I am using Eclipse and I have imported android-support-v4.jar in libs folder. What could be the issue here? Thank you for your help - this is a great library.

Screenshot of error: http://snag.gy/zuwDY.jpg

**Comment by Qinwroks** [comment]
try android-support-v7

**Comment by drupalmav** [comment]
That helped and got rid of most of the issues. One last issue - Cannot resolve R.attr.colorAccent 

Is anything special about R.attr.colorAccent?

![image](https://cloud.githubusercontent.com/assets/3411673/6571550/8ce498d0-c6d7-11e4-9912-8233507be0d5.png)

**Comment by Qinwroks** [comment]
make sure your compile sdk version is set to api 21.

**Comment by castasat** [comment]
1. Go to your project directory (or to `Project View`)
2. Find and open `.idea` directory
3. Remove `caches` and `libraries` directories   <-- this is essential
4. `Invalidate Caches / Restart`
