### ISSUE TITLE
MaterialEditTextPreference should allocate cursor at the end of the value

### ISSUE THREAD

**Issue by fredyrincon** [afollestad/material-dialogs#312]
If a MaterialEditTextPreference is selected. The cursor should be at the end of the word or value not at the beginning. 

It is required to tap 2 to actually change the value.

Thank you

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/commit/8fa6d9715584665bed9567bbcad6b13b02e071d3
