### ISSUE TITLE
Missing CheckBoxPreference

### ISSUE THREAD

**Issue by fredyrincon** [afollestad/material-dialogs#313]
Could you please include CheckBoxPreference.

Thank you

**Comment by afollestad** [comment]
As in a list preference with checkboxes?

It's better than you handle that yourself. There's no consistent way for my to store arrays of integers in preferences.

**Comment by andrewlord1990** [comment]
I'm pretty sure CheckBoxPreference is just an inline preference that doesn't actually use a dialog at all.

**Comment by fredyrincon** [comment]
thank you. I solved just by handle it with a state drawable.
