### ISSUE TITLE
AlertDialogWrapper.Builder#setAdapter is not the same with AlertDialog.Builder counterpart

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#315]
In AlertDialog.Builder, setAdapter has 2 params, the adapter and the item click listener. However, in AlertDialogWrapper.Builder, the setAdapter method only specifies the adapter. 

This makes migrating from AlertDialog to MaterialDialog is not simple as replacing AlertDialog.Builder with AlertDialogWrapper.Builder.

**Comment by afollestad** [comment]
This is now in release 0.6.4.0

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.0
