### ISSUE TITLE
AlertDialogWrapper.Builder#setSingleChoiceItems does not behave like the AlertDialog.Builder

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#316]
Using AlertDialogWrapper.Builder#setSingleChoiceItems and buttons,
the listener passed as the second parameter is not called until the button callback is called.

I think AlertDialogWrapper.Builder#setSingleChoiceItems should call
alwaysCallSingleChoiceCallback() to make the behaviour match AlertDialog.Builder.

		new AlertDialogWrapper.Builder(activity)
			.setSingleChoiceItems(options, selected, (dialog, which) -> {
                                  // this callback is not called when user clicks on an item
			})
			.setPositiveButton("OK", (dialog, which) -> /* other callback */)
			.setNegativeButton("Cancel", null)
			.show();

**Comment by afollestad** [comment]
This was already implemented https://github.com/afollestad/material-dialogs/pull/305

**Comment by afollestad** [comment]
This is now in release 0.6.4.0

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.0

**Comment by yukuku** [comment]
I think #305 is different. You still need to add `alwaysCallMultiChoiceCallback(true)` to the code base.

My issue is about making AlertDialog.Builder and AlertDialogWrapper.Builder behave in the same way, so one could just replace all AlertDialog.Builder with AlertDialogWrapper.Builder and everything will work like before. Isn't that the original intention of AlertDialogWrapper?

**Comment by afollestad** [comment]
Yeah, but like the pull request said we didn't force the change since people had already been using it before, expecting the current behavior now.
