### ISSUE TITLE
how to dismiss a indeterminate progress dialog by code

### ISSUE THREAD

**Issue by ZephZeph** [afollestad/material-dialogs#317]
I can't seem to find in the documentation how to dismiss the dialog. I am showing the dialog while verifying login credentials so I need to dismiss the dialog after verification. The only way I can dismiss the dialog is by tapping/touching the screen. Please help. Thank you

**Comment by afollestad** [comment]
Same as a stock dialog. Dismiss method. 

Material dialog extends AlertDialog.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
