### ISSUE TITLE
Consider adding setWidgetLayoutResource(0) to MaterialListPreference on Android 2.x

### ISSUE THREAD

**Issue by sherpya** [afollestad/material-dialogs#319]
Gingerbread shows an ugly sort of checkmark on ListPreferences, newer android version removed this image at all, you can get rid of it by adding this code in the MaterialListPreference constructors

        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.GINGERBREAD_MR1)
            setWidgetLayoutResource(0);

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.1
