### ISSUE TITLE
The ListCallback of AlertDialogWrapper#setAdapter() has position, but no ID

### ISSUE THREAD

**Issue by druidamix** [afollestad/material-dialogs#321]
Hi,
Since the new version 0.6.4.0,
the listview callback obtained with dialogZonas.getListView() doesn't work.

It was useful since I could use the Id of the cursor to perform updates.

It's possible add this parameter in the adapter's callback?

Thanks.

**Comment by afollestad** [comment]
You mean the callback has no ID? The current way matches up with what the stock AlertDialog does. 

But I'll make it so that you can still set your own callback to the ListView directly.

**Comment by afollestad** [comment]
You can set a click listener directly now and it won't be overridden.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.1
