### ISSUE TITLE
MaterialEditTextPreference not compliance with android:inputType

### ISSUE THREAD

**Issue by askfor** [afollestad/material-dialogs#322]
The stock EditTextPreference create EditText like this:
  mEditText = new EditText(context, attrs);
So android:inputType is working.

But MaterialEditTextPreference didn't use those attributes.

**Comment by afollestad** [comment]
@askfor this is fixed and will be in the next release

**Comment by afollestad** [comment]
The new release is now available https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.2
