### ISSUE TITLE
Add substitution for MultiSelectListPreference

### ISSUE THREAD

**Issue by askfor** [afollestad/material-dialogs#323]
Now we have MaterialListPreference for ListPreference.
But no substitution for MultiSelectListPreference.

**Comment by afollestad** [comment]
@askfor this will be in the next release for API 11 and above

**Comment by askfor** [comment]
Thanks!

**Comment by afollestad** [comment]
No problem

The new release is now available https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.2
