### ISSUE TITLE
Prevent theming

### ISSUE THREAD

**Issue by ZephZeph** [afollestad/material-dialogs#325]
My app's primary color is #212121 which is almsot black so the dialogs' background appear as black. Is there a way to supreas this and just use the default which is white? I tried using setbackgroundcolor but it messed up the dialogs although it did change the background color.

**Comment by afollestad** [comment]
Not quite sure what you mean, how do they appear black?

**Comment by ZephZeph** [comment]
First of all, I would like to thank you for responding quickly to my
issues. i emailed you directly cause I put a picture attachment to describe
how the dialog looks like.Please see attachment.

**Comment by afollestad** [comment]
Sorry, I didn't get any emails related to that.

Images can be uploaded to GitHub comments (with drag and drop) though.

**Comment by ZephZeph** [comment]
Oops..my bad. here is the photo
![screenshot_2015-03-16-10-47-06](https://cloud.githubusercontent.com/assets/11370310/6660062/704319a0-cbcc-11e4-86e7-d61abc050fbc.png)

**Comment by afollestad** [comment]
Hmm, not sure how it's that black. What API level are you on?

**Comment by ZephZeph** [comment]
Also,  I was wrong when I assumed that it is because of my primaryColor. i changed my primary color to a lighter one but the color was still black

**Comment by afollestad** [comment]
Yeah, I don't change the background color at all from code. It's all from the default Android dialog themes.

**Comment by afollestad** [comment]
Although there may be issues below KitKat because of how the themes are setup, so I may have to manually set the dialog background colors below KitKat (or below Jellybean?).

**Comment by ZephZeph** [comment]
i am on KitKat 4.4.4.

**Comment by afollestad** [comment]
Well there's gotta be something somewhere in your theme that's messing with the dialogs. By default, the light and dark themes look like this:

![screen shot 2015-03-15 at 10 29 50 pm](https://cloud.githubusercontent.com/assets/1820165/6660228/0173562a-cb63-11e4-96e1-da29075b0da0.png)

![screen shot 2015-03-15 at 10 31 11 pm](https://cloud.githubusercontent.com/assets/1820165/6660229/0535f916-cb63-11e4-8007-d703e41e05be.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
