### ISSUE TITLE
Failed to resolve "com.afollestad:material-dialogs:0.6.4.2"

### ISSUE THREAD

**Issue by draskosaric** [afollestad/material-dialogs#329]
Hi, 

I added to my module's build.gradle dependencies section as you said:

compile 'com.afollestad:material-dialogs:0.6.4.2'

but sync doesn't work. Can you please check what is th problem?
Best,
D

**Comment by bkraszewski** [comment]
Make sure you have this in your gradle file:
repositories {
    maven {
        url  "http://dl.bintray.com/drummer-aidan/maven"
    }
}

**Comment by afollestad** [comment]
I would recommend what @bkraszewski said. The library is on jCenter, which is Android Studio's default Maven repo. 

Make sure you didn't change the default repo or anything.

**Comment by afollestad** [comment]
Oops, sorry, I meant I wouldn't recommend that.

**Comment by draskosaric** [comment]
Instead of mavencentar(), I set jcenter() and everything is fine now.

**Comment by afollestad** [comment]
Good, I was assuming that was the issue.

You can actually use both, for future reference.

```Gradle
repositories {
    jcenter()
    mavenCentral()
}
```
