### ISSUE TITLE
Unable to open MaterialEditTextPreference twice

### ISSUE THREAD

**Issue by binarybucks** [afollestad/material-dialogs#330]
When the MaterialEditTextPreference is opened twice, ```mEditText``` still seems to be attached to the old dialog and the following exception is thrown. 

```
    Process: org.owntracks.android, PID: 1190
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3882)
            at android.view.ViewGroup.addView(ViewGroup.java:3735)
            at android.view.ViewGroup.addView(ViewGroup.java:3711)
            at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.showDialog(MaterialEditTextPreference.java:80)
```

I'm seeing this with version 0.6.4.2. 
Any idea why the old dialog is still around?

**Comment by afollestad** [comment]
It's not the old dialog, it's adding the EditText twice to the layout. This is any easy fix though.

**Comment by afollestad** [comment]
By that I mean the EditText is created and added to the layout. When the dialog is shown again, it gets added to the layout again, but the EditText had already been added to another parent thus this exception is thrown.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.3

**Comment by binarybucks** [comment]
Now it doesn't crash but the value is appended on every open.
I suggest to switch back ```mEditText.append``` to ```mEditText.setText```
