### ISSUE TITLE
Single Choice List Dialogs is displayed incorrectly

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#331]
On API 15, Single Choice List Dialog is displayed incorrectly and item cannot be selected:

![single](https://cloud.githubusercontent.com/assets/4901251/6676174/31d60600-cc26-11e4-9cb8-c5e314d781ac.png)

**Comment by afollestad** [comment]
Let me know if that commit fixes it, I don't have a quick way to test 4.0.3

**Comment by TomasValenta** [comment]
Confirmed, now it's ok.
