### ISSUE TITLE
gradle issue

### ISSUE THREAD

**Issue by fahimk** [afollestad/material-dialogs#332]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:22.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.jar

It looks like the current version of appcompat is 'com.android.support:appcompat-v7:21.0.3'

**Comment by fahimk** [comment]
got a message to update sdk in android studio. I'm still using v7:21.0.3, but it's working now.

**Comment by afollestad** [comment]
The current version is 22, everything was updated when API 22 was released. They're in the SDK manager.
