### ISSUE TITLE
Material EditText Preference not saving value correctly

### ISSUE THREAD

**Issue by fncapps** [afollestad/material-dialogs#333]
If you open the dialog and chenge the default value and you re-open it, it appears the value you set followed by "Default Value".
If you cancel the dialog and re-open it, the same happens again but without adding a new "Default Value" to your saved value.

**Comment by afollestad** [comment]
"Default value" is the default value specified by the sample project.

I'm keeping `append()` because it positions the cursor at the end when the dialog opens, however I will empty the text beforehand to resolve this issue.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.5
