### ISSUE TITLE
MaterialEditTextPreference missing getText method

### ISSUE THREAD

**Issue by askfor** [afollestad/material-dialogs#335]
Stock EditTextPreference has a getText method which is missing in MaterialEditTextPreference

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.5

**Comment by askfor** [comment]
MaterialMultiSelectListPreference missing getValues()

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.6
