### ISSUE TITLE
Default theme style is being overwritten

### ISSUE THREAD

**Issue by lupajz** [afollestad/material-dialogs#336]
I have a default style : 
```
    <style name="AppTheme.Base" parent="Theme.AppCompat.NoActionBar">
        <item name="colorPrimary">@color/white</item>
        <item name="colorPrimaryDark">@color/black</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:textColorPrimary">@color/white</item>
        <item name="android:textColorSecondary">@color/green</item>
        <item name="colorAccent">@color/green</item>
        <item name="android:windowBackground">@android:color/white</item>
    </style>
```
After adding this lib to gradle I end up with transparent parts of app, where I have to specified android:backgroundColor

**Comment by afollestad** [comment]
@lupajz I don't override backgrounds, `windowNoTitle` and `windowBackground` only apply to activities. Material Dialogs defaults the primary/neutral/negative colors to the `colorAccent` color.

Make sure you're passing a themed context (e.g. an Activity) to the `Builder` rather than a global context.

**Comment by afollestad** [comment]
Any news on anything you've tried?

**Comment by GHEEV** [comment]
Hey! Here is reverse. I'm using your library but my theme is transparent default. My dialog buttons is missing Roboto fonts and the single choice are themed like Android 2.3... What is wrong?

            new MaterialDialog.Builder(getActivity())
                    .title("Para qual numero deseja ligar?")
                    .theme(Theme.LIGHT)
                    .items(parts)
                    .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallback() {
                        @Override
                        public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                            final Intent intent = new Intent(Intent.ACTION_DIAL);
                            intent.setData(Uri.parse("tel:"+String.valueOf(text)));
                            startActivity(intent);
                        }
                    })
                    .positiveText(R.string.call_button)
                    .negativeText(R.string.cancel_button)
                    .show();

Is in a fragment and the activity is extended to Activity. And I tried change the color of buttons programatically but the color does't match :(

![screenshot_2015-03-19-00-35-48](https://cloud.githubusercontent.com/assets/6901088/6724082/2111fabc-cdd0-11e4-8060-feec0f95d906.png)

**Comment by lupajz** [comment]
No the problem was I was getting transparent background on my components like listview for example without having any dialog in project, but just pasting dependecy to gradle file. I use https://github.com/neevek/Paginize lib for my project as it is convinient for me to not work with fragments and things around them. Guess that was the problem. Anyway I solved it by specifing each components missing background color manualy as I don't have time to look into it thoroughly. Will mail u if I get time to  investigate the problem.

**Comment by afollestad** [comment]
@GHEEV are you using AppCompat to theme your Activity? Styling for radio buttons is derived from your Activity theme during layout inflation. I don't deal with that myself.

AppCompat also will color your UI controls with whatever your `colorAccent` attribute is set to in your Activity theme.

**Comment by GHEEV** [comment]
I change to AppCompat, but the action button fonts (positive and negative buttons) didn't change...

**Comment by afollestad** [comment]
@GHEEV I wouldn't expect them to change below Lollipop. Roboto Medium was introduced as a system font with API 21. Below API 21, it will use Roboto Bold.

**Comment by GHEEV** [comment]
Ok so, thanks for that! :)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
