### ISSUE TITLE
PreferenceManager.setDefaultValues wont work with MaterialEditTextPreference

### ISSUE THREAD

**Issue by fredyrincon** [afollestad/material-dialogs#337]
Hi,

I have just noticed that when trying to set the default values of the SharedPreferences the normal behavior is that the key preferences would be set by using the code below. However, using it with a MaterialEditTextPreference it wont set the value as a expected. For MaterialListPreference seems to be working.

```Java
PreferenceManager.setDefaultValues(context.getApplicationContext(), R.xml.pref_debug_advanced, true);
```

Great Job by the way!!

Thank you.

**Comment by afollestad** [comment]
I'm hoping https://github.com/afollestad/material-dialogs/commit/024598a196c7e44f1cc1ffd45a6730b30c8607c0 fixes this.

Thanks!

**Comment by fredyrincon** [comment]
Let me know when you going to publish again. And I will give a try of it. 

Thank you.

**Comment by afollestad** [comment]
I'll need to test it before publishing, I don't want to spam users with unnecessary updates and use up versions too quickly, haha

**Comment by fredyrincon** [comment]
Thanks cool mate!! 
Not a problem.

**Comment by afollestad** [comment]
Let me know if the new release fixes it

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.6

**Comment by fredyrincon** [comment]
All good. It works perfect. Thank you!!
Once again great job.
