### ISSUE TITLE
AppCompat version

### ISSUE THREAD

**Issue by Soarry** [afollestad/material-dialogs#340]
In build.gradle you are using latest appcompat version 22.0.0. But this one has bugs like: https://code.google.com/p/android/issues/detail?id=159703.

Please switch to version 21.0.3, where it is OK. For example, see another dialog lib (https://github.com/avast/android-styled-dialogs), where they are also using v21.0.3.

Otherwise I cant use your lib.

**Comment by afollestad** [comment]
Sorry, I'm sticking with the latest. A new AppCompat will be out eventually.

**Comment by Soarry** [comment]
May I know why?
