### ISSUE TITLE
mipmap support

### ISSUE THREAD

**Issue by ZaLeXemre** [afollestad/material-dialogs#341]
You should add mipmap support for icon drawable.

**Comment by afollestad** [comment]
There's no difference in retrieving these. MipMaps just allow you to use `getDrawableForDensity` rather than only `getDrawable`.

**Comment by afollestad** [comment]
So you can manually use `icon(Drawable)` yourself.

**Comment by ZaLeXemre** [comment]
But you can not assign R.mipmap.ic_smthg  to icon. I mean it is not possible to use     icon(R.mipmap.ic_smthg)

**Comment by afollestad** [comment]
Yes, but there's no way to determine whether an integer represents a regular drawable or a mipmap. I could add a `iconMipmap` method but it would require additional parameters. At this point, it's easier if you manually get the `Drawable` yourself.
