### ISSUE TITLE
Change progress Color

### ISSUE THREAD

**Issue by hateum** [afollestad/material-dialogs#342]
How can I change progress color ?
Is that possible to implement that Feature ?

**Comment by afollestad** [comment]
Progress bar colors are derived from your theme's `colorAccent` attribute automatically. That's a Lollipop feature. Below Lollipop, I manually change the color with a color filter, but that's not reliable on Gingerbread.

It's better to keep it consistent with Lollipop.

**Comment by afollestad** [comment]
I decided to implement this for the next release: https://github.com/afollestad/material-dialogs/commit/92eac3e5541f4066a52eaf496ed75c82d28c5af2

**Comment by hateum** [comment]
Cool,
So with this, I don't need to implement a custom view with custom progress

**Comment by afollestad** [comment]
This is now possible

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
