### ISSUE TITLE
ListPreference should throw IllegalStateException on wrong initalization

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#343]
MaterialListPreference should check (like android does) if values are initialized correctly.

I.e android ListPreference throws this exception:
<code>java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.</code>

Which is helpful. I didnt specify values, so your ListPreference just showed me the entries, but didnt save which one was chosen. So immediately failing fast seems to be a good solution.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.6
