### ISSUE TITLE
Dialogs theming wrong

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#344]
Latest version (didnt test previous one) does the theming wrong.
When setting the Theme to dark (Theme.AppCompat instead of Theme.AppCompat.Light.DarkActionBar), the dialogs get weridly themed. Elements (like seekbar etc get the correct theme, but background and mainelements (Title, buttons etc) contain their LightTheme color.
AlertDialog.Builder themes correctly. Attached a screenshot showing an AlertDialog build by the builder **ontop** of a Material Dialog

![screenshot_2015-03-18-17-33-07](https://cloud.githubusercontent.com/assets/743462/6713850/48952dce-cd95-11e4-9992-494ac25c4f11.png)

**Comment by afollestad** [comment]
For now you have to explicitly set the dialog dark theme through global theming or the Builder method.

**Comment by Ph1b** [comment]
Do you know how to retrieve the necessary values from the AppCompat theme?

**Comment by afollestad** [comment]
I don't know of any good way to check for a light or dark theme. The accent
colors are already retrieved from your theme, the title and content should
be.

Feel free to make attempts yourself. I'm a little busy at the moment.

**Comment by afollestad** [comment]
Themes are auto detected with the new release: https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
