### ISSUE TITLE
Buttons have their own background

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#348]
It looks like buttons have their own background, rather than having maybe a transparent background with the ripple/selector over that.

It creates a bad experience for dialogs with custom backgrounds IMO

![2015-03-19 01 05 02](https://cloud.githubusercontent.com/assets/1361086/6726411/2ff66d66-cdd4-11e4-87a1-7e56911be1d1.png)

**Comment by afollestad** [comment]
Well, below Lollipop it's necessary.

It'll have to be removed for pre-Lollipop selectors by adding custom selectors. I actually do not use my own custom selector on Lollipop (I can't remember if I do below either), I use Android's default.

**Comment by afollestad** [comment]
Oh disregard the above, I only use the stock selector for stacked buttons.

**Comment by afollestad** [comment]
Well, like I said above, it's not possible to not have the background on pre-Lollipop. For Lollipop, I don't think the ripple will render correctly unless there is a background. So unfortunately I don't think too much can be done about this, other than using a custom action button selector from global theming or the builder that lightens it up a bit.

**Comment by hzsweers** [comment]
It'd be nice to have a chance to respond before you close the issue. I think it can be done by simply having a transparent background. I'll look at this weekend

**Comment by afollestad** [comment]
Well, the action buttons aren't actually buttons. They're TextViews with
rounded inset selectors.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.7
