### ISSUE TITLE
Attribute has already been defined error

### ISSUE THREAD

**Issue by ZephZeph** [afollestad/material-dialogs#354]
I don't know what happened but today when I rebuilt my project I got an error with the attrs.xml of the library. 
![screenshot_2015-03-22-11-36-35](https://cloud.githubusercontent.com/assets/11370310/6767900/031f46bc-d088-11e4-8e6a-094a3fe4c918.png)

**Comment by afollestad** [comment]
I wouldn't completely trust AIDE to work correctly. But that usually happens if a library is referenced twice.

**Comment by ZephZeph** [comment]
Yeah you're right. I actually removed the library from my project and re-added it but AIDE failed(bug) to remove the reference to the original library. thanks
