### ISSUE TITLE
List item sizing doesn't follow 48dp grid

### ISSUE THREAD

**Issue by maniac103** [afollestad/material-dialogs#355]
See this comparison screenshot taken on a device set to 408dpi: https://drive.google.com/file/d/0B0hmLAh3l4oHZDVYblNlQklyeUk/view?usp=sharing

On the left is the stock ListPreference, which lays out the items in a 122px = (122 * 408 / 160) 48dp grid. On the right there's the MaterialListPreference, which uses a 132px = 52dp grid.
Also there's additional margin between radio button and text that isn't present in ListPreference.

Is there a specific reason for deviating from the 48dp grid?

Additionally (but less important from my POV) the title padding seems a little large with 24 vs. 18dp.

**Comment by afollestad** [comment]
Well, not everything the stock dialogs do are correct design-guidelines wise. There isn't enough space between the radio button and text in the stock version, there should be at least 16dp between all UI elements IMO. 

But I'll look at the other spacing issues, thank you

**Comment by afollestad** [comment]
I should add, dialogs should have a top/left/right padding of 24dp, and a bottom padding of 8dp: http://www.google.com/design/spec/components/dialogs.html#dialogs-specs

I don't think the stock alert dialog is following that, unless my eyes deceive me.

**Comment by afollestad** [comment]
I made the list items 48dp in minimum height. However, I confirmed that the other padding dimensions are indeed correct when you match them with the design guidelines specs (I used dspec to generate this spacing/keyline layout):

![screen shot 2015-03-22 at 7 46 54 pm](https://cloud.githubusercontent.com/assets/1820165/6772452/6088fb38-d0cc-11e4-852f-40dfc602bb4b.png)

**Comment by maniac103** [comment]
For the dialog title, I agree. I'm not sure whether I follow the argument for the radio button spacing though. Having 16dp spacing between UI elements is a good idea (in order to provide enough spacing for separating touch targets), but in this particular case, we're dealing with only one UI element (in terms of interaction). This is why the spacing feels too much to me: it looks like the text doesn't really belong to the radio button.

**Comment by afollestad** [comment]
Well, the stock list dialogs don't space that correctly either. Check out this image from the design guidelines:

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7YzI3dnI2ZE5QN1E/components_dialogs_content2.png

**Comment by maniac103** [comment]
Arguably this is a mistake though, looking at the 'Simple dialogs' example below that: http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7VlBxRUNLdk5ZbU0/components_dialogs_simple1.png

Subjectively it looks plain ugly ;)

**Comment by afollestad** [comment]
Personally I think the simple dialogs example is how it should be. I like symmetry and separation.

**Comment by afollestad** [comment]
I agree that the link above yours looks ugly though, there's wayy too much space there.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.5.0
