### ISSUE TITLE
About editText design in dialog

### ISSUE THREAD

**Issue by arslanaybars** [afollestad/material-dialogs#356]
I added editText in my dialog but i cant design my dialog, i cant set margin,padding, witdh.

I need to improve my design, but i cant use in java related methods.
http://developer.android.com/reference/android/widget/EditText.html

        LayoutInflater inflater = MainActivity.this.getLayoutInflater();
        final EditText etIP = new EditText(MainActivity.this);
        etIP.setText(SERVER_IP);
        etIP.setHint(getString(R.string.enter_server_ip));
        new AlertDialog.Builder(MainActivity.this)
                .setTitle(getString(R.string.set_ip))
                .setView(etIP)

**Comment by afollestad** [comment]
You're using an AlertDialog in your code so it's not related to this library.

Also, setting margins from code is a Java issue, not an issue specific to this library either.
