### ISSUE TITLE
min API

### ISSUE THREAD

**Issue by jemshit** [afollestad/material-dialogs#357]
What is min API version supported?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/library/build.gradle

**Comment by jemshit** [comment]
comment on here http://stackoverflow.com/a/26721975/3736955 says 14, write this min 8 to initial page https://github.com/afollestad/material-dialogs

**Comment by afollestad** [comment]
That's old old comment

**Comment by afollestad** [comment]
People can see what the current min SDK is from the Gradle file. ☺
