### ISSUE TITLE
Limiting max of choices selected in MultiChoice

### ISSUE THREAD

**Issue by ivanviragine** [afollestad/material-dialogs#358]
Not exactly an issue, but a feature request: what about adding the ability for setting a maximum of checks on a MultiChoice dialog?
I have a list of 5 options, but you can only check 2 of them.
Thanks!

**Comment by afollestad** [comment]
I implemented a way to do this with the latest commit: https://github.com/afollestad/material-dialogs/commit/1b24402bfe5b622a65e1ed11c43a3cbbf1e25931

Basically, single choice and multi choice list callbacks will allow you to return false if you don't want selection to be allowed, or true to allow it. There's an example in the sample project to further explain what I mean. 

This will be available in today's release in a bit.

**Comment by ivanviragine** [comment]
Thanks a lot!

**Comment by afollestad** [comment]
No problem!

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.5.0
