### ISSUE TITLE
customview RecyclerView height

### ISSUE THREAD

**Issue by jemshit** [afollestad/material-dialogs#359]
1) I set custom view which is linear layout and it has RecyclerView, when it is empty height of dialog fills screen, why is that ? How to fix
![dialog](https://cloud.githubusercontent.com/assets/1948828/6807412/01c6d1b0-d257-11e4-8492-773c7828e042.png)

2) Although i use .dividerColorRes(R.color.blueLight) there is no divider below title?

**Comment by afollestad** [comment]
Sorry, RecyclerViews cause issues. That's why I use a ListView for list dialogs. 

RecyclerViews currently don't measure themselves correctly, thus making the dialog fill the screen. Dividers are shown when it detects the view is scrollable.
