### ISSUE TITLE
RecyclerView Runtime Error

### ISSUE THREAD

**Issue by jemshit** [afollestad/material-dialogs#360]
After i use this dependency and library i get error on my RecyclerView which is Not related to dialog. Furthermore my RecyclerView is on different activity, not where i use material-dialogs. The error occurs when i delete last item from RecyclerView adapter. Error is <a href="http://stackoverflow.com/questions/29241676/android-recyclerview-last-item-remove-runtime-error"> here</a> .
I guess problem may be dependency collusion ? Mine is also listed in above link. Any solution for this?

**Comment by afollestad** [comment]
I should note there's a new version of the library available. But as far as I know, it's not related. Maybe it's because you're using an old version of the support library, app conpat, or recycler view. They're all at version 22 since API 22 (Android 5.1) was released a week or two ago.

**Comment by jemshit** [comment]
i tried with v7:22 versions and it give error. Then i tried with v7:21 error is gone. Since this library uses v7:22 i get error if i use it. Is there any way to force project to use v7:21 or change dependency of library for my project?

**Comment by jemshit** [comment]
Ok, i did overwrite dependency to use v7:21 using <a href="http://stackoverflow.com/a/24768164/3736955">this</a> and i can use library as well now.

**Comment by afollestad** [comment]
I will be going back to 21.0.3 for now in the upcoming release

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.7.1
