### ISSUE TITLE
Title has very little padding

### ISSUE THREAD

**Issue by JackTrow** [afollestad/material-dialogs#364]
I'm currently using my real device running Lollipop and have used your basic usage sample code to launch a dialog within Android Studio. 

The dialog loads successfully however the problem is that the title has virtually no padding to the left or top, unlike the positive and negative buttons and how the title is shown in your images.

I added a theme to change its gravity to centre however it still has no padding from the top.

Everything else including content seems to have a nice amount of padding all the way round.

**Comment by afollestad** [comment]
Not quite sure what you mean (this is on a Nexus 6 with Lollipop)

![screenshot_2015-03-24-19-20-48](https://cloud.githubusercontent.com/assets/1820165/6815977/03185dbe-d25b-11e4-82cd-c0a5215a74dc.png)

**Comment by JackTrow** [comment]
Maybe an image might of been more clear

![screenshot_2015-03-25-00-27-20](https://cloud.githubusercontent.com/assets/4717298/6816046/e51a5f1c-d285-11e4-825e-d5f3f9aa9ecd.png)

**Comment by JackTrow** [comment]
With the following code implementation,

import com.afollestad.materialdialogs.MaterialDialog;

new MaterialDialog.Builder(this)
                .title("Title")
                .content("Content")
                .positiveText("Positive")
                .negativeText("Negative")
                .show();

**Comment by afollestad** [comment]
Are you overriding any global attributes in styles.xml? e.g. `fitsSystemWindows`?

**Comment by afollestad** [comment]
Cause I started developing this library on a Nexus 5 and have a Nexus 6 now, no one else has reported these issues for a while. The last time someone did, it was an attribute in styles.xml messing with the dialog window.

**Comment by JackTrow** [comment]
Knew it must of been something simple!

I had the following line in my styles.xml,

<item name="android:fitsSystemWindows">true</item>

It was in my v21 folder and isn't actually needed so was just an easy remove.

![Uploading Screenshot_2015-03-25-00-35-51.png . . .]()

Its looking as it should!

Thank you!

**Comment by afollestad** [comment]
Glad I could help, no problem!

**Comment by JackTrow** [comment]
Knew it must of been something simple!

I had the following line in my styles.xml,

true

It was in my v21 folder and isn't actually needed so was just an easy remove.

![screenshot_2015-03-25-00-35-51](https://cloud.githubusercontent.com/assets/4717298/6816171/67390218-d287-11e4-8e76-3fd61c1b23c2.png)

Its looking as it should!

Thank you!

**Comment by afollestad** [comment]
Glad I could help, no problem!

**Comment by afollestad** [comment]
I see you're trying to fix that XML now showing, GitHub considers that literal HTML. You have to wrap in in syntax XML syntax highlighting (see the link above).

**Comment by JackTrow** [comment]
I could see it was parsing it as xml, I tried to reword what I said without the code but you beat me to it.

Which is even better, thanks!
