### ISSUE TITLE
is there a way to change TextView's font in MaterialDialog?

### ISSUE THREAD

**Issue by doyonghoon** [afollestad/material-dialogs#366]
In terms of consistency of look&feel, the font in Dialog is not an exception. Is there any plan to provide a public access of `title TextView` to be fully customizable, or adding a changeable font feature? thanks.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#typefaces

There's already built in support for custom Typefaces. Otherwise you can subclass MaterialDialog.Builder and have access to protected members.
