### ISSUE TITLE
The layout is inefficent

### ISSUE THREAD

**Issue by molikto** [afollestad/material-dialogs#368]
You have put all the stuffs in one layout, thus make the inflation time too long

**Comment by afollestad** [comment]
You're right, I'm almost done with a pretty large change to the library to help with this.

**Comment by afollestad** [comment]
In case you didn't see the new release yet:

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.0

**Comment by afollestad** [comment]
One more: https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.1

**Comment by afollestad** [comment]
The new release is another massive improvement to layout efficiency: https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
