### ISSUE TITLE
Leaked window when showing dialog in onActivityResult

### ISSUE THREAD

**Issue by RubyDerBoss** [afollestad/material-dialogs#370]
I show a Dialog when I receive a result from another Activity. I get the following exception:
MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@41669a08 that was originally added here
It seems to be an Android bug: http://stackoverflow.com/questions/10114324/show-dialogfragment-from-onactivityresult
Is there a way for you to fix it or should I implement some kind of workaround?

**Comment by afollestad** [comment]
As far as I know there's no way to fix it, dialogs attach themselves to an Activity's Window, if no initialized window is available then the dialog won't be showable/dismissable.

I'd recommend the workarounds they talk about on that question.

**Comment by lionelkermesse** [comment]
Hello,
I'm still having the same issue of Leaked window when showing after activityResult. Please can you give me some advices on how to fix that or how to work around the issue. I tried many think unfortunately without success

**Comment by reancool** [comment]
I'm still having the same issue 。。。
