### ISSUE TITLE
Question (Or Feature) - Buttons Location

### ISSUE THREAD

**Issue by TurKurT656** [afollestad/material-dialogs#375]
Hello,
TnQ for this awesome library. can we change the location of flat buttons to left side ? I'm using RTL language and i can change the text directions. But i dont know how to send the buttons to left size

**Comment by afollestad** [comment]
This is is a duplicate issue. Please search the existing close issues for an answer.

**Comment by afollestad** [comment]
To be more specific: https://github.com/afollestad/material-dialogs/issues/326

**Comment by afollestad** [comment]
This will be improved in the next update.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.7.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
