### ISSUE TITLE
AppCompat progress bar coloring doesn't work on Samsung devices?

### ISSUE THREAD

**Issue by caarmen** [afollestad/material-dialogs#377]
On a 4.4 device, the progress bar uses the custom color (it's magenta in the demo app).  However, on a device with 5.0.1, the progress bar appears as blue.

**Comment by afollestad** [comment]
Are you sure? This is the demo app on my Nexus 6.

![screenshot_2015-03-29-17-02-04](https://cloud.githubusercontent.com/assets/1820165/6887997/6e8bbb62-d635-11e4-99ed-5e9d287322c3.png)

**Comment by caarmen** [comment]
Hello,

This is the demo app from the Play Store, on an S4 with 5.0.1.
![device-2015-03-30-003342](https://cloud.githubusercontent.com/assets/1731388/6888137/b61de7c2-d674-11e4-936d-9ed867525634.png)
![device-2015-03-30-003457](https://cloud.githubusercontent.com/assets/1731388/6888136/b61da5be-d674-11e4-8d13-a82f4737efd0.png)

**Comment by caarmen** [comment]
Maybe this is an issue on 5.0.1 but not 5.1...

**Comment by afollestad** [comment]
Hmmm. That may be an issue with Samsung's custom Android skin overriding AppCompat. The progress bar is automatically colored by AppCompat (using the `colorAccent` attribute in `styles.xml`). It works on every 5.0+ device I've used.

**Comment by afollestad** [comment]
This is on a 5.0 emulator, also. I suspect your issue is related to Samsung.

![screen shot 2015-03-29 at 9 09 08 pm](https://cloud.githubusercontent.com/assets/1820165/6889241/fdbab0a0-d657-11e4-9d48-4d1d0c70c924.png)

**Comment by afollestad** [comment]
I'll keep this open to see if anyone finds a solution, but as far as I know it's a Samsung issue. There's actually a lot of Samsung-related issues with AppCompat (e.g. apps will crash if they don't use certain Proguard rules).

**Comment by teslacoil** [comment]
Samsung's seekbar ignores tint as well and is blue, I work around it using a custom seekbar style (basically the AppCompat style for pre-21, however I copied the animations back in), I imagine the same could be done for the progressbar.

**Comment by afollestad** [comment]
I actually decided to make the progress color customizable (with methods and a global theming attribute): https://github.com/afollestad/material-dialogs/commit/92eac3e5541f4066a52eaf496ed75c82d28c5af2

I had been using color filters below Lollipop to force the accent color to be applied. It obviously wasn't needed on Lollipop, but it appears to work perfectly on Lollipop and below to dynamically change theme colors. I haven't tested it on very low APIs like Gingerbread, yet. But this will resolve this issue since it defaults to using the `colorAccent` theme value.

**Comment by afollestad** [comment]
This should be fixed with version 0.7.0.0, you can use `widgetColor` or the variants of it (or even the global theming attribute).

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0

**Comment by imSathish** [comment]
Add this 2 line in style it will worrked for me
<item name="android:indeterminateTintMode">src_in</item>
        <item name="android:indeterminateTint">@color/colorAccent</item>
