### ISSUE TITLE
When button text is updated, other button visibility test is reset -- execution path dependency

### ISSUE THREAD

**Issue by inteist** [afollestad/material-dialogs#379]
- make neutral button gone
- set different text for negative button 

the neutral button re-appears

current workaround - move the code that manages the visibility of the button **after** any update to the text

should be an easy fix

**Comment by afollestad** [comment]
To hide an action button, set its text to null using the `setActionButton()` method. Changing visibility manually is not reliable.

**Comment by inteist** [comment]
Why is visibility status unreliable? Is that because the library is written this way or some other reason?

I can see it in the code that null hides the button.  
- why it was designed like this?

Suggested fix:
overload `invalidateActions()` with `invalidateActions(MASK)` the default no params method will combine all the 3 button masks and make a call to `incalidateActions(COMBINED_MASK)` while the `setActionButton` becomes:

```java
  public final void setActionButton(@NonNull DialogAction which, CharSequence title) {
        switch (which) {
            default:
                mBuilder.positiveText = title;
                invalidateActions(POSITIVE_BTN_MASK);
                break;
            case NEUTRAL:
                mBuilder.neutralText = title;
                invalidateActions(POSITIVE_NTRL_MASK);
                break;
            case NEGATIVE:
                mBuilder.negativeText = title;
                invalidateActions(POSITIVE_NEG_MASK);
                break;
        }
    }
```

The invalidateActions() adds a check for a MASK before doing updates for the buttons. 

This may not be the best solution but it should work with minimal changes to the flow/structure and may be even a bit more efficient as only views required to be updated will be updated. 

If you like it I can implement it and submit a pull.

Let me know.

**Comment by afollestad** [comment]
Because of how the library is set up.

Having that only in `setActionButton()` isn't the most reliable either, because a user could still get access to the button from `getActionButton()`. 

Using a mask is better, but there's other causes where the actions will be invalidated and there's no way to know if the previous visibility state was set by the user or by the library itself. The only completely reliable way is by setting the text to null.

**Comment by inteist** [comment]
That's a bad solution because this is an unexpected side effect in Android world and getting rid of a view by setting it to null is not common (to the best of my knowledge).

Not sure I follow 100% but I trust you know what you are talking about still should be fixed. Why not fix it - it should not be too hard and will most likely result in a better, more modular architecture.

**Comment by afollestad** [comment]
Well, yeah, there must be a better solution. But passing a mask to `invaidateActions()` won't quite do it since the method is used in 3 other places and could be invoked at any time.

![screen shot 2015-03-30 at 9 57 35 am](https://cloud.githubusercontent.com/assets/1820165/6899041/5d0cd536-d6c3-11e4-9e08-db9849f67cdc.png)

**Comment by afollestad** [comment]
Actually, no, I take that back. Using a mask might actually fix it completely.

**Comment by inteist** [comment]
:)

**Comment by inteist** [comment]
I believe I need to point out that I only looked at the source code for a few minutes and a better solution is quite possible.

**Comment by afollestad** [comment]
I think your solution might work, it'd be a good idea to test it with different cases though. 

My next class (I'm a college student) is starting now but I'll get back to this later.

**Comment by afollestad** [comment]
@inteist can you check if the latest code fixes your issue?

**Comment by afollestad** [comment]
I'm getting to the bottom of it right now, it's almost ready.

**Comment by afollestad** [comment]
This should work perfectly now, I just tested it a bit.

https://github.com/afollestad/material-dialogs/commit/4e37d0bd6c5edd22e9a2b2e4234e5449aa0c4278

**Comment by afollestad** [comment]
One more: https://github.com/afollestad/material-dialogs/commit/1bbbd800227227f5f05f66615b8915b4ea97babe

I'll have an update out in a few hours, most likely.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.7.0

**Comment by inteist** [comment]
How well tested is it?

I am afraid I can't go ahead with not very stable version. 

I can help test it but right now I don't really have a lot of time to dedicate to it. 

You should think about creating a test suit to automatically test edge cases on various OSes. Since it backports to so many OS versions it is pretty important to have a coherent experience.

**Comment by afollestad** [comment]
I tested it pretty thoroughly. Would you rather have the behavior not work at all for your case? Lol. But yeah it seemed to work perfectly on my end. 

I don't have a lot of time either, I'm a college student and I'm an employed dev. 

Usually I use the sample project with emulators but this specific case didn't apply so I used my own temporary test code.

**Comment by afollestad** [comment]
I should add that XDA featured this update today

**Comment by inteist** [comment]
Since I did not lock in the version, it auto updated. I will take a look.

After reading the release notes, if I understand correctly, any change will require call to invalidateActions()... That's better in terms of stability of predictability but I am not sure it made the library better in terms of usage. Someone could be wondering why nothing happens after changing the visibility but not making the call for invalidateActions() that's my $0.02

**Comment by afollestad** [comment]
You don't need to call that method if you change button text with
setDialogAction(), since it makes a call to invalidateActions() for you.

There is no other way. There's no way of knowing when the user changes
visibility. If you hide the positive action button, the negative action
button will go over the neutral button since invalidateActions() sets the
negative action's LayoutParams.
