### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by logicalstep** [afollestad/material-dialogs#382]
Sorry for being a complete nubbin, but the instructions (readme) don't actually show how to install this library in you project. I'm confused when downloading the latest version which folder I should put where in my project in Android Studio.
I've added plenty of .Lib libraries, so I'm familiar with that, but could you explain more explicitly, what need to go where in the ReadMe please?

It'll be one of those things that is probably an 'ahhh yes, obviously' kind of moments.

Many thanks in advance!

**Comment by afollestad** [comment]
The Gradle dependency is used in Android Studio:

https://github.com/afollestad/material-dialogs#gradle-dependency-jcenter

**Comment by logicalstep** [comment]
I think you're assuming people like me, know as much as people like you. and you are missing a big problem for new devs who want to use your library...like me :)

I understand that I have to add the dependency to Gradle (same as a .Lib file)
The question is when I download your source file from here, it looks like this:

\material-dialogs-0.6.7.0\material-dialogs-0.6.7.0\

![masterialdialogscreen](https://cloud.githubusercontent.com/assets/11743687/6929402/5a1aa7e2-d7f2-11e4-87ea-60135b135195.png)

Which folder do I put where in my project?
What's the hierarchy?

Thanks again.

**Comment by afollestad** [comment]
You don't download the source at all. You place the string you see in the README inside build.gradle of your app.

You may wanna look into how Gradle works, this will only work in Android Studio, also. If you're using Eclipse, it requires extra steps since it's no longer Google's official Android IDE.

**Comment by afollestad** [comment]
Similar to this

![screen shot 2015-03-31 at 4 29 09 pm](https://cloud.githubusercontent.com/assets/1820165/6929767/1c708ecc-d7c3-11e4-8508-6b83d617ee0c.png)

**Comment by logicalstep** [comment]
Nope, I'm using Android Studio.
I see, so it will download the library for me?
Where does it store it in Android Studio?

Just reading through this to get an idea of Gradle:
http://igorpopov.io/2014/05/01/understanding-gradle/

Thanks for your patience.

**Comment by afollestad** [comment]
Sorry, this isn't the best place to learn how Android Studio works. I'm a busy college student.

But yeah, Android Studio will download all of your library dependencies, where doesn't really matter. They're automatically made available in your project. 

If you want to look at the library code and run the sample, then you can download the entire project and import it as a Gradle project. But if you're referencing just the library, copying and pasting that line and syncing your project is all that's needed.

**Comment by logicalstep** [comment]
I appreciate the help you have given so far, so many thanks.

I'm actually making progress now. Looking through your issues, it appears I have a similar situation to another user, where my project was imported into Android Studio and originally using Maven, not  jcenter().

So I'm going to work through solving that, and hopefully it'll all start working.

Thanks again.

**Comment by logicalstep** [comment]
Got it working.
changed to jCenter in build.gradle from Maven.
Downloaded latest build tools and sdk using sdk manager.

Thanks again, for this great library!

**Comment by afollestad** [comment]
Good to hear, no problem!
