### ISSUE TITLE
ProgressDialog Progress Color

### ISSUE THREAD

**Issue by PLAYER1953** [afollestad/material-dialogs#384]
Is it possible to set progress dialog indeterminate progress color?

**Comment by afollestad** [comment]
I decided to implement this for the next release: https://github.com/afollestad/material-dialogs/commit/92eac3e5541f4066a52eaf496ed75c82d28c5af2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
