### ISSUE TITLE
Default text size for the text-only dialog should be 16sp not 18sp

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#388]
The original Android 5.0/5.1 text content style is `TextAppearance.Material.Subhead`, which resolves to 

        <item name="textSize">@dimen/text_size_subhead_material</item>
        <item name="fontFamily">@string/font_family_subhead_material</item>
        <item name="textColor">?attr/textColorPrimary</item>

and the value of `text_size_subhead_material` is `16sp`. The MaterialDialogs look really huge on 320dp screen because it's using 18sp as the default text size. It should be 16sp if you want to follow the original dialogs.

**Comment by afollestad** [comment]
You're right, thanks

**Comment by Falcon5f** [comment]
I think it would be better to change a list item text size too, `md_listitem_textsize` to `16sp` instead `18sp`. Also `md_listitem_height` and `md_listitem_control_margin` change to smaller value to be more consistent.

**Comment by afollestad** [comment]
Made the list item font smaller: https://github.com/afollestad/material-dialogs/commit/2a00c167e1872fd139e9df8cf8746b4b9973799a

The other values are not wrong.

**Comment by Falcon5f** [comment]
Ok, that's right. Thank you.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.7.2
