### ISSUE TITLE
adapt text style to AlertDialog default

### ISSUE THREAD

**Issue by agrajaghh** [afollestad/material-dialogs#391]
I compared the original AlertDialog and MaterialDialog running on Android 5 (Nexus 4):

**AlertDialog:**
![alertdialog](https://cloud.githubusercontent.com/assets/5296073/6989136/64d9f076-da58-11e4-9ffa-2131c5cc8532.png)

**MaterialDialog:**
![materialdialog](https://cloud.githubusercontent.com/assets/5296073/6989234/76aafcc2-da59-11e4-9e5f-8e1c6d7b6f05.png)

Is it possible to change the space between the lines to the same value like in AlertDialog? Also `md_title_color` and `md_content_color` doesn't seem to read the default values from `android:textColorPrimary` and `android:textColorSecondary` during my test. Just the scrollbar used the color from `android:textColorSecondary`.

Here is the code I used:
````java
AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);
builder.setTitle("Lorem ipsum dolor");
builder.setMessage("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
  public void onClick(DialogInterface dialog, int id) {

  }
});
builder.show();

new MaterialDialog.Builder(MainActivity.this)
                  .title("Lorem ipsum dolor")
                  .content("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.")
                  .negativeText("Cancel")
                  .show();
````
and this is in the theme:
````
    <item name="android:textColorPrimary">#ffff0000</item>   <!-- red -->
    <item name="android:textColorSecondary">#ff0000ff</item> <!-- blue -->
````

**Comment by afollestad** [comment]
Currently, I don't change the title or content text color unless the user explicitly does through `Builder` methods. However, that's a good point, I'll use those system attributes as the default colors.

The stock Alert Dialog doesn't do everything from the design guidelines 100% correctly, FYI. Do you mean the margin between the dividers when the content is scrollable?

**Comment by afollestad** [comment]
The reason those attributes aren't used is because it bases the color used for the title/content/list items on the dialog theme (Theme.Light or Theme.Dark). It doesn't rely on the Activity theme, which will give the wrong value if the dialog theme is inverted.

**Comment by afollestad** [comment]
I made the dialog derive the title, content, and list item color from the system attributes by default. But this will cause issues if you use the dark theme for a dialog in an Activity that uses a light theme (the text won't be visible), or vice versa. https://github.com/afollestad/material-dialogs/commit/7a96180c7f51a3152f28fa35d5b2f0b3651343e3

**Comment by afollestad** [comment]
It will now adapt based on the theme combination between the dialog and Activity theme, it will use the inverse versions of those two system attributes if needed: https://github.com/afollestad/material-dialogs/commit/8633fc1661df55a3451c99b9122d3024466c0a08

**Comment by afollestad** [comment]
To add more details to support the current spacing (if you scroll down a bit, they have specific values that should be used for padding/margin): http://www.google.com/design/spec/components/dialogs.html#dialogs-specs

This is what dialogs look like with the latest commit (not in a current release version yet):

![screen shot 2015-04-03 at 11 29 37 pm](https://cloud.githubusercontent.com/assets/1820165/6991433/bc0dc7b8-da59-11e4-9e32-1d38cdc837f8.png)

**Comment by agrajaghh** [comment]
Thanks for the quick fix!

I tried it out, but the spacing between the content text lines is still bigger than in AlertDialog :(

Its now reading the values from `android:textColorPrimary` and `android:textColorSecondary` for me. But if these values are not set in the theme, the text is displayed in gray in MaterialDialog not in black like in AlertDialog. So perhaps the standard value should be changed?
