### ISSUE TITLE
Remaining fixes for 0.7.0.0

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#395]
Images and content to explain on the original PR: https://github.com/afollestad/material-dialogs/pull/392

**Comment by teslacoil** [comment]
Initial fixes in https://github.com/afollestad/material-dialogs/pull/396

**Comment by teslacoil** [comment]
Let's migrate the discussion of the padding here, from the pull request I commented:

For the padding, the examples in google's spec do have the 24dp padding
above content on dialogs without titles. It's hard to measure the dialog
without buttons but I agree it's less than 24dp. Unfortunately they don't
show any examples of no title and no buttons.

If we respect the 24dp above content with no title but use only 8/12dp on
the bottom when there are no buttons, a no title no button dialog will look
off balanced.
We could do 24dp total padding above the content if there is no title but
has buttons, and 8dp total padding above and below content, if there is no
title and no buttons. I don't really like the inconsistency, but I do agree
the 24dp padding feels excessive at times.

The change in the button selector seems to be one of your changes, as I
don't see it on my commit but do see it after pulling the latest.

---

After some more thought, the problem with using just 8dp when no title and no button bar is that text content dialogs would look off. Doing 8dp for no title, no button bar, lists would work, but it makes it harder to decide what to do for custom content.

**Comment by afollestad** [comment]
Hmm, I'll have to look into this again more tomorrow. 

Thanks for the quick initial fixes too.

One solution to make verify measurements are correct is to use the app [Keyline Pushing](https://play.google.com/store/apps/details?id=com.faizmalkani.keylines), or the library [dspec](https://github.com/lucasr/dspec). Although I guess it's pretty easy to tell by eye if these values are correct or not.

The neutral button definitely has too much padding to the start of it though, there's a pretty big offset from the content keyline. There should only be 16dp there. The guidelines do show the big margin values being used above and below the list, but that just looks odd to me for some reason.

**Comment by afollestad** [comment]
Copying this image over from the original PR for reference (for the stacked buttons layout issue).

![md1](https://cloud.githubusercontent.com/assets/1820165/6999333/870f81d2-dbcb-11e4-96f4-0eb47fe6c70a.png)

**Comment by teslacoil** [comment]
That was (or at least should've been) fixed in https://github.com/teslacoil/material-dialogs/commit/d6dd29edda20a403363477d135a8e543cd66ec2b . I'd been testing with auto-stacking and forgot to test against force stacking.

**Comment by teslacoil** [comment]
> The neutral button definitely has too much padding to the start of it though, there's a pretty big offset from the content keyline.

Where are you seeing this? For me, the neutral dialog in the sample app has the same amount of padding to the start of the neutral button as there is at the end of the positive button, and it's 16dp from the dialog border to the edge of the selector.

For the no title, no button bar dialog, I'm leaning towards just using the 8dp padding applied to the list/content/etc. With the full padding, the client can't reduce it, with only the content padding the client can always increase that to 24dp if they chose (as the client always controls if the title and buttons are visible). The only problem is if they chose 24dp and it's running on a small screen device so it scrolls.

**Comment by afollestad** [comment]
Disregard, it appears to have went away luckily.

Sounds good, I think that will work best.

**Comment by afollestad** [comment]
So it looks like the only major thing left before 0.7.0.0 is this stuff. This is gonna be a very large update with all this new layout and theming stuff that we've implemented.

**Comment by teslacoil** [comment]
Here's what I propose. Dialog Edge Padding is white space between content and dialog edge (if applicable)

Content Type | Title | Buttons | Dialog Edge Padding | Dialog Edge Padding
------------ | ------------- | ------------- | ------------- | -------------
Text | N | N | 24 | 24
List | N | N | 8 | 8
List | Y | N | x | 24
List | N  | Y | 24 | x
Scrolling List | * | * | 8 | 8

(Custom is treated the same as list)

The justification is that things look off balance if there is a lot of padding at the top or bottom but not the other, so a no title list with buttons has a lot of white space around the button (to match the specs) and only 8dp at the top looks weird. Likewise a title has a lot of whitespace, so only 8dp to the bottom looks weird.

Examples:
![List notitle button](http://teslacoilsw.com/tmp/md/list_notitle_buttons.png)

![List title nobuttons](http://teslacoilsw.com/tmp/md/list_title_nobuttons.png)

![List notitle nobuttons](http://teslacoilsw.com/tmp/md/list_notitle_nobuttons.png

**Comment by afollestad** [comment]
On a side note, you have very nicely formatted comments lol.

But I think it looks great in those screenshots, I definitely see what you mean about the whitespace in different situations. It looks very symmetrical now.

**Comment by teslacoil** [comment]
The whitespace here still feels a bit strong, but this is to spec (16dp between content and button, 6dp between button touch zone and touch feedback, total of 22dp)

![List Single Choice](http://teslacoilsw.com/tmp/md/list_single_choice.png)

**Comment by afollestad** [comment]
Somehow #403 stopped the top divider that shows when you scroll down (and the divider above the button bar when the content is scrollable) from working :o

**Comment by teslacoil** [comment]
I think that's from the theme changes, not https://github.com/afollestad/material-dialogs/pull/403 . I see the dividers in my branch which is from before the theme changes.

**Comment by afollestad** [comment]
Oh odd, well I just fixed some crashes and theme issues via https://github.com/afollestad/material-dialogs/commit/0f6dbba34aef3ab49e3a7f7f060ae66ab83ed020, I'll see if it works now

**Comment by afollestad** [comment]
Yep, it works now!

Do you guys think there's anything else major left to be done before release 0.7.0.0?

**Comment by teslacoil** [comment]
I think it looks good. There's a minor fix still needed for the dividers ( https://github.com/afollestad/material-dialogs/issues/397#issuecomment-90206988 ) , but even if 0.7.0.0 was released without that I don't think it's a huge deal as it can always be fixed in a .1 update.

**Comment by afollestad** [comment]
Yeah, people are discouraged to use RecyclerViews as they force dialogs to be full height anyways. I don't anyone will really notice right away, but it'll be a good future fix to make everything perfect.

**Comment by afollestad** [comment]
@teslacoil @plusCubed do you guys think we should limit the height of dialogs?

![md](https://cloud.githubusercontent.com/assets/1820165/7011373/16917e3a-dc6e-11e4-8fc8-852d978f8cf1.png)

**Comment by teslacoil** [comment]
I don't think so, unless Google does or the spec says something about maximum dialog height.

In this case I agree it looks silly, but that's partially because we're not really looking at the content (unless you read latin I guess) and we're expecting it to scroll. For scrollable dialogs, or even dialogs that fill the space with information we care about, I think full size on the N6 is fine. I think adding an option for max height is more work (and future maintenance as well) then it's worth and making it mandatory means we have to pick a size in a non-arbitrary way. Also an option could be confusing as a developer might try using it to enlarge the dialog, but on 4.x the dialog size (and position) is restricted by the dialog background's shadows, which are controlled by the OEM.

Though it is unfortunate the padding between the dialog bottom and navbar doesn't match the padding between the left/right edges of the screen and the dialog edges.

**Comment by teslacoil** [comment]
I think one of the recent changes broke dialog fragments 
"    java.lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
            at android.app.DialogFragment.onActivityCreated(DialogFragment.java:474)"

Looking into it further but wanted to post to postpone the release while I confirm

**Comment by afollestad** [comment]
Hmmmm, yeah that's a good point. Oddly enough, it wasn't as tall before the recent changes for padding fixes. I'm not sure what could've possibly broken this.

Where does that crash happen? It's working fine from the folder selector dialog in the sample project.

**Comment by plusCubed** [comment]
Another thing: the text size was made smaller to match stock, but I think now it's smaller than stock text size. I'll check.

**Comment by teslacoil** [comment]
@afollestad I think it was just as tall, it's just the text size was larger until a change before the padding change. But I could be wrong. When working on the MDRootLayout I was comparing screenshots between the previous release and mine and noticed the smaller text size, then started comparing to previous master and mine and the text size was the same.

The crash I'm seeing is Nova's Edit Shortcut dialog, which is a complex case as it has a crazy animation (On Prime, Drag app from drawer to Edit, then tap on the New Group, It's broken in the current beta, but it does a circular reveal animation to basically a second dialog. Implementation is tricky.).

On 5.1 I see:
                        E  java.lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
                        E      at android.app.DialogFragment.onActivityCreated(DialogFragment.java:474)
                        E      at android.app.Fragment.performActivityCreated(Fragment.java:2061)
                        E      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
                        E      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                        E      at android.app.BackStackRecord.run(BackStackRecord.java:833)
                        E      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                        E      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                        E      at android.os.Handler.handleCallback(Handler.java:739)
                        E      at android.os.Handler.dispatchMessage(Handler.java:95)
                        E      at android.os.Looper.loop(Looper.java:211)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5321)
                        E      at java.lang.reflect.Method.invoke(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:372)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

Which is from DialogFragment's:

    if (!mDialog.takeCancelAndDismissListeners("DialogFragment", this, this)) {
        throw new IllegalStateException(
            "You can not set Dialog's OnCancelListener or OnDismissListener");
    }

public boolean takeCancelAndDismissListeners(String msg, final OnCancelListener cancel,
            final OnDismissListener dismiss) {
        if (mCancelAndDismissTaken != null) {
            mCancelAndDismissTaken = null;
        } else if (mCancelMessage != null || mDismissMessage != null) {
            return false;
        }
        
        setOnCancelListener(cancel);
        setOnDismissListener(dismiss);
        mCancelAndDismissTaken = msg;
        
        return true;
    }


So it appears that it happens because there is already a cancel/dismiss listener set which is true. I'll try to figure out why folder chooser works but mine doesn't.

**Comment by afollestad** [comment]
Yeah someone told me I should make the text size smaller to match stock, I believe I copied what Android's internal dimensions were but they could be wrong.

I think a workaround for the crash would be to only set the internal dismiss and cancel listeners when the user is specifically using an input dialog, but then that causes some needed logic changes (since the user's set callbacks won't be forwarded, they'll be directly set to the base dialog).

**Comment by teslacoil** [comment]
FolderChooser is a support fragment, I'm using a native fragment, that's the difference, switching FolderChooser to use native fragments causes the crash.

**Comment by afollestad** [comment]
Oh, right, I see. I'm currently brainstorming a bit.

**Comment by afollestad** [comment]
Oh, right, I see. I'm currently brainstorming a bit.

I have an idea.

**Comment by teslacoil** [comment]
Is the only current use for the overridden listeners to hide the keyboard? The comments for Dialog.dismiss suggest using onStop to cleanup, I didn't realize Dialog's had an onStop, but it sounds like  an appropriate place to hide the keyboard if it works.

**Comment by afollestad** [comment]
Oooh, good idea. Thanks

**Comment by afollestad** [comment]
@teslacoil https://github.com/afollestad/material-dialogs/commit/99571a5f7473cfcea74da0822be163778b5962dd should fix it

**Comment by teslacoil** [comment]
Yup, looks good!

**Comment by plusCubed** [comment]
@afollestad About the text size, do we follow Material Design guidelines or stock? More specifically, the guidelines picture shows the text being 18sp, while stock is 16sp. The actual written guidelines though say it's supposed to be 16sp. The title is 20sp on both ends, so there's no question there - I'll change that.
On a related note, the action button should have a minimum width of 64dp according to the guidelines, but stock and currently material-dialogs has only 56dp (when accounted for 4dp padding on both sides).

**Comment by afollestad** [comment]
@plusCubed not 100% sure that they're currently correct, I tried to match the guidelines (not the dialog guidelines but just general guidelines and title and content text size).

**Comment by afollestad** [comment]
It does look like the guidelines use 20sp though.

**Comment by afollestad** [comment]
Also, there's 4dp external padding and 8dp internal padding for action buttons, I think what we're currently doing there is correct **other than the min width needing to be 64dp**.

![screen shot 2015-04-06 at 4 34 44 pm](https://cloud.githubusercontent.com/assets/1820165/7012955/f2380c0e-dc7a-11e4-8679-61b882a2451e.png)
![screen shot 2015-04-06 at 4 34 24 pm](https://cloud.githubusercontent.com/assets/1820165/7012958/f5afa252-dc7a-11e4-8311-d5e20ae4dd19.png)

**Comment by afollestad** [comment]
Alright so now that the divider visibility stuff was fixed, all that's left before the release (as far as I know) is the text size. What'd you guys think? Should we increase the title or content size?

**Comment by plusCubed** [comment]
@afollestad Oh, I already changed the title size in the pull request. I thought that was determined to be 20sp. Is that fine? For the content size, I think it's fine for now. If you can contact anyone at Google or something it might be good idea to ask since it's a spec thing.

**Comment by afollestad** [comment]
Oh, awesome. Yeah that's fine.

Adam Powell tends to respond rather quickly on Google+, otherwise there's Roman Nurik and a few others. But I think it should be fine for now.
