### ISSUE TITLE
Wrong theme when using custom view

### ISSUE THREAD

**Issue by plusCubed** [afollestad/material-dialogs#399]
This can be seen by scrolling the Custom View demo - even though it's a Light dialog, the overscroll effects are white instead of gray (it thinks it has a dark theme). After messing around a bit, it seems to be caused by the android.app.Dialog superclass creating a new ContextThemeWrapper not using the MD_Dark or MD_Light theme.

**Comment by afollestad** [comment]
Ohhh, good catch. Using the super constructor with a theme parameter might fix this problem.

**Comment by afollestad** [comment]
Can you check if this fixes it? https://github.com/afollestad/material-dialogs/commit/33a400604147a373fc6eccdd65f41fa9bd29a147

I have to go to class, but I'll get back to this later.

**Comment by plusCubed** [comment]
Huh, it seems to fix it, but now the dialog width and some padding is messed up.

**Comment by afollestad** [comment]
Oh yeah, you mean the padding below the action buttons?

**Comment by afollestad** [comment]
I wonder if the dialog theme is now somehow overriding the padding @teslacoil's code sets?

**Comment by teslacoil** [comment]
This isn't related to the MDRootLayout change, but I've seen it before. Previously I attempted to replace the dialog background so the corners and shadows would be consistent on <5.0, however doing so with a custom dialog theme messed up the horizontal padding. It's a mess. AlertDialog chooses a theme like this:

    static int resolveDialogTheme(Context context, int resid) {
        if (resid == THEME_TRADITIONAL) {
            return com.android.internal.R.style.Theme_Dialog_Alert;
        } else if (resid == THEME_HOLO_DARK) {
            return com.android.internal.R.style.Theme_Holo_Dialog_Alert;
        } else if (resid == THEME_HOLO_LIGHT) {
            return com.android.internal.R.style.Theme_Holo_Light_Dialog_Alert;
        } else if (resid == THEME_DEVICE_DEFAULT_DARK) {
            return com.android.internal.R.style.Theme_DeviceDefault_Dialog_Alert;
        } else if (resid == THEME_DEVICE_DEFAULT_LIGHT) {
            return com.android.internal.R.style.Theme_DeviceDefault_Light_Dialog_Alert;
        } else if (resid >= 0x01000000) {   // start of real resource IDs.
            return resid;
        } else {
            TypedValue outValue = new TypedValue();
            context.getTheme().resolveAttribute(com.android.internal.R.attr.alertDialogTheme,
                    outValue, true);
            return outValue.resourceId;
        }
    }

Those styles are indeed private so we can't extend them. They reference and private layout so we can't reference it. The layout has private view ids, so we can't recreate it.

I think we can fix the overscroll issue by making sure we always inflate our views with a ContextThemeWrapper, but the actual dialog (and thus dialog.getContext()) should stay the system default. I can take a look.

**Comment by afollestad** [comment]
Oh yeah, good idea, that's a quick change

**Comment by afollestad** [comment]
The two previous commits should hopefully fix it now, all inflation is done with LayoutInflaters created with the theme wrapper.

**Comment by afollestad** [comment]
Now the action buttons got messed up, lol. It's like taking bricks out of the base of a house.

**Comment by plusCubed** [comment]
With the latest fixes, the dialog background color is still bugged. Pass in Theme.DARK for any of the demo dialogs and the dialog background is light. Quick fix or no?

**Comment by afollestad** [comment]
Yeah I should be able to fix that quickly, good catch

**Comment by afollestad** [comment]
@plusCubed fixed in https://github.com/afollestad/material-dialogs/commit/048308fced7ac46094f52efe9cd308c3b9fd07c8

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0
