### ISSUE TITLE
Determinate (Seek Bar) Progress Dialogs in AsyncTask

### ISSUE THREAD

**Issue by crysan** [afollestad/material-dialogs#400]
Hi!
Err: You can only set the dialog's progress from the UI thread.
I understand that Progress Dialogs in AsyncTask does not work?

    private class updateAllAuthors extends AsyncTask<String, Void, String> {
        MaterialDialog dialog;

        protected void onPreExecute() {
            super.onPreExecute();
            dialog = new MaterialDialog.Builder(getActivity())
                    .content(R.string.dialog_loading)
                    //.progress(true, 0)
                    .progress(false, 70, false)
                    .show();
        }

        @Override
        protected String doInBackground(String... params) {
        dialog.setProgress(20);
        return null;
       }
       .....................

**Comment by theenderer** [comment]
If you want to update progress from an AsyncTask on the UI thread, use onProgressUpdate. Something like:

private class updateAllAuthors extends AsyncTask<String, Integer, Void> {
    MaterialDialog dialog;

    protected void onPreExecute() {
        dialog = new MaterialDialog.Builder(getActivity())
                .content(R.string.dialog_loading)
                //.progress(true, 0)
                .progress(false, 70, false)
                .show();
    }

    @Override
    protected Void doInBackground(String... params) {
    publishProgress(20)
    return null;
   }

@Override
     protected void onProgressUpdate(Integer... values) {
    dialog.setProgress(values[0]);
    }
   .....................

**Comment by crysan** [comment]
Tried. Unfortunately the same error.

**Comment by crysan** [comment]
STOP! Slightly upgraded and it worked! 
Thank you!
