### ISSUE TITLE
Materia-Dialogs cancelable in a dialog fragment

### ISSUE THREAD

**Issue by arfod** [afollestad/material-dialogs#401]
Hi,
I think to have found a little bug.
I wrapped your Material Dialog in a DialogFragment, the same way you do in FolderSelectionDialog.
Even if I set cancelable to false to the builder or the Material Dialog in this scenario, the dialog always closes when I touch outside its window or click the back button.
Bye

**Comment by arfod** [comment]
Don't mind...in that scenario (in a DialogFragment) you have to use the "setCancelable()" method of the DialogFragment class itself.
Bye

**Comment by tbruyelle** [comment]
Good to know, but not sure if this wouldn't be improved.

**Comment by afollestad** [comment]
This is an Android framework issue, it has nothing to do with the library itself.

You can't directly use `setCancelable(boolean)` on an `AlertDialog` or plain `Dialog` in a `DialogFragment`.
