### ISSUE TITLE
dismiss() && show()

### ISSUE THREAD

**Issue by jemshit** [afollestad/material-dialogs#407]
1)How to dismiss dialog, i don't use positive and negative buttons. I couldn't find function like .dismiss() ? i have this:
MaterialDialog.Builder md=new MaterialDialog.Builder(this);
md.title("..");
2)i show dialog before i start background async task. Then i want to update content inside background task, i tried myterialDialog.content("") .show(); but did not work. How to change content later?

**Comment by ZephZeph** [comment]
There should be a dismiss function as I have used it in my app as well. If you can't find it, try to edit the MaterialDialog class and add a dismiss function if it's not there. But then again, it should be there.

**Comment by jemshit** [comment]
@ZephZeph there is MaterialDialog and MaterialDialog.Builder. I was using MaterialDialog.Builder and it doesn't have dismiss(). Now i try to use MaterialDialog and it has dismiss() but, now i cant call methods like .typeface() .How to get advantages of both ?

**Comment by jemshit** [comment]
ok, i used this and worked:
` MaterialDialog md=new MaterialDialog.Builder(getActivity())
                    .title("")
                    .typeface("")
                    .content("")
                    .show();`
Then i can call `md.setContent()` or `md.dismiss()` from anywhere.

**Comment by afollestad** [comment]
This was already in the README and it's no different than an AlertDialog, BTW.

**Comment by jemshit** [comment]
Still don't know difference between calling `show()` methods of `Builde`r and `Dialog` itself

**Comment by afollestad** [comment]
`show()` of `MaterialDialog` is actually `show()` from `AlertDialog`. The other `show()` is a convenience method from `Builder`:

```java
public MaterialDialog build() {
    return new MaterialDialog(this);
}

public MaterialDialog show() {
    MaterialDialog dialog = build();
    dialog.show();
    return dialog;
}
```

I should note that this structure is exactly the same as `AlertDialog` and `AlertDialog.Builder`. This is not new to this library.

**Comment by afollestad** [comment]
`dismiss()` is also an `AlertDialog` method. This library just builds upon `AlertDialog` and redoes how the view construction and layout works.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
