### ISSUE TITLE
Dialog Theme on Android API Level 10 (2.3)

### ISSUE THREAD

**Issue by RobertoIDL** [afollestad/material-dialogs#410]
Hi,

Any idea what's the right way to apply the theme to older versions of Android? Everything seems to work fine from 4.0 and above using:

<item name="md_dark_theme">false</item>

But it gets ignore on 2.3

Thanks in advance.

R.

**Comment by afollestad** [comment]
Looks like you didn't use XML code formatting above.

**Comment by RobertoIDL** [comment]
Sorry!

```xml
<item name="md_dark_theme">false</item>
```

**Comment by afollestad** [comment]
Thank you, I'll take a look at this later

**Comment by FongMi** [comment]
md_widget_color is not working on Single Choice List, It is always black, but my accent color is amber.

**Comment by afollestad** [comment]
@FongMi if you're using Android 5.0, that's an API 21 issue. Google fixed it with 5.1 (API 22). Note that it doesn't work below API 21, also.

**Comment by afollestad** [comment]
I'll double check that it works though.

**Comment by afollestad** [comment]
Fixed the dialog theme on API 10

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.1

**Comment by afollestad** [comment]
This will be further improved with the upcoming release

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0

**Comment by RobertoIDL** [comment]
All working fine so far using version 0.7.1.0

Thanks for the hard work.
