### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by prechtelm** [afollestad/material-dialogs#411]
Hi,
I tried to add your project but the grade build shows 117 errors. All are like that: "No resource found that matches the given name: attire 'android:actionModeShareDrawable'." and occur in
- app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v11/values.xml
- app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v14/values.xml
- app/build/intermediates/exploded-aar/com.afollestad/material-dialogs/0.7.0.0/res/values/values.xml
- app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v21/values.xml

Any idea how to fix that?

**Comment by afollestad** [comment]
Well, it's an AppCompat issue.

If you're using a different AppCompat version that what the library uses, you need to upgrade your app, or use {force=true} in your app to overwrite the version this library uses.

**Comment by prechtelm** [comment]
How do I change my AppCompat? never changed it in android studio

**Comment by afollestad** [comment]
You may wanna learn a bit more about Android Studio if you don't know how Gradle dependencies work. It's in `build.gradle`.

**Comment by prechtelm** [comment]
Thanks for your help! it is working now!
