### ISSUE TITLE
Change color of the Text Select Handle in the input dialog

### ISSUE THREAD

**Issue by Hoolycraap** [afollestad/material-dialogs#412]
Is it possible to change the color of the Text Select Handle in the Input Dialog like it is in the Custom View Dialog?
![2015-04-07 18 46 02](https://cloud.githubusercontent.com/assets/5994414/7030935/7ea19e60-dd68-11e4-8829-873caeeaaff7.png)
![2015-04-07 18 46 18](https://cloud.githubusercontent.com/assets/5994414/7030938/852a5768-dd68-11e4-8fec-557109adfca0.png)

**Comment by afollestad** [comment]
That's not a library feature, that's part of the Material theme on API 21+ or AppCompat for all API levels.

**Comment by Hoolycraap** [comment]
I use AppCompat but it's still not colored, it only works if i use a custom view.

**Comment by afollestad** [comment]
Make sure you're passing an `Activity` context to your dialog builder.

**Comment by Hoolycraap** [comment]
I do and the edittext itself is colored, only the Text Select Handle isn't, like in the first screenshot i posted.

**Comment by afollestad** [comment]
Hmm, well there's not really much I can do. That's handled by the Android framework, not me.

If you're not using Android 5.0 or above, there might be an issue there.

**Comment by afollestad** [comment]
Oh sorry, didn't look into at those screenshots long enough (since I'm doing homework). It's very odd that it's not the right color when you're on Lollipop. But like I said, that's handled by the framework so there shouldn't be an issue.

**Comment by Hoolycraap** [comment]
I'm doing this with a custom view now, is it possible to use a content message AND a custom view?

**Comment by afollestad** [comment]
No, you'll need to put a TextView in there

**Comment by afollestad** [comment]
Wait! I found a bug related to this that will fix this issue @Hoolycraap

**Comment by Hoolycraap** [comment]
Ok, when are you going to release the fix?

**Comment by afollestad** [comment]
ASAP, there's a few other small things going into this release too.

**Comment by afollestad** [comment]
Currently the issue here is theme being used for the dialog.

In `MaterialDialog`'s constructor:

```java
protected MaterialDialog(Builder builder) {
        super(DialogInit.getTheme(builder));
        mBuilder = builder;
        final LayoutInflater inflater = LayoutInflater.from(getThemedContext());
        view = (MDRootLayout) inflater.inflate(DialogInit.getInflateLayout(builder), null);
        DialogInit.init(this);
}
```

In `DialogInit.getTheme()`:

```java
public static ContextThemeWrapper getTheme(MaterialDialog.Builder builder) {
        boolean darkTheme = builder.theme == Theme.DARK;
        if (!darkTheme) {
            darkTheme = DialogUtils.resolveBoolean(builder.context, R.attr.md_dark_theme, false);
            builder.theme = darkTheme ? Theme.DARK : Theme.LIGHT;
        }
        return new ContextThemeWrapper(builder.context, darkTheme ? R.style.MD_Dark : R.style.MD_Light);
}
```

The dialog is still using the `Context` that you pass to the `Builder`, but I think `MD_Dark` and `MD_Light` are overidding `colorAccent` or something. I'm currently doing homework so I'll have to look at this later.

@plusCubed @teslacoil

**Comment by afollestad** [comment]
As a work around, I made the default accent colors in the dialog themes black (for light dialogs) and white (for dark dialogs). It looks significantly better than the Material theme's default teal.

**Comment by afollestad** [comment]
The only place you notice this is the input dialog, because all other dialogs use views that don't show small theming issues like this or use views that theme themselves with library code.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.1

**Comment by afollestad** [comment]
A lot of this will be improved with the next update also

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0
