### ISSUE TITLE
Title and content text colors always get overridden by textColorPrimaryInverse and textColorSecondaryInverse

### ISSUE THREAD

**Issue by JoseTotiRodriguez** [afollestad/material-dialogs#413]
If you see the code below the md_title_color and md_content_color theme attributes always get ignored because the builder will always have a Dark or Light theme, therefore always overriding the builder colors with textColorPrimaryInverse and textColorSecondaryInverse. I had to revert back to 0.6.7.2 for now. 

```
if (!builder.titleColorSet) {
            final int titleColorFallback = DialogUtils.resolveColor(builder.context, android.R.attr.textColorPrimary);
            builder.titleColor = DialogUtils.resolveColor(builder.context, R.attr.md_title_color, titleColorFallback);
            if (DialogUtils.isColorDark(builder.titleColor)) {
                if (builder.theme == Theme.DARK)
                    builder.titleColor = DialogUtils.resolveColor(builder.context, android.R.attr.textColorPrimaryInverse);
            } else if (builder.theme == Theme.LIGHT)
                builder.titleColor = DialogUtils.resolveColor(builder.context, android.R.attr.textColorPrimaryInverse);
        }
        if (!builder.contentColorSet) {
            final int contentColorFallback = DialogUtils.resolveColor(builder.context, android.R.attr.textColorSecondary);
            builder.contentColor = DialogUtils.resolveColor(builder.context, R.attr.md_content_color, contentColorFallback);
            if (DialogUtils.isColorDark(builder.contentColor)) {
                if (builder.theme == Theme.DARK)
                    builder.contentColor = DialogUtils.resolveColor(builder.context, android.R.attr.textColorSecondaryInverse);
            } else if (builder.theme == Theme.LIGHT)
                builder.contentColor = DialogUtils.resolveColor(builder.context, android.R.attr.textColorSecondaryInverse);
        }
```

**Comment by afollestad** [comment]
Good catch, fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.1

**Comment by JoseTotiRodriguez** [comment]
That fixes that issue but won't it still override any color set in "?android:textColorPrimary"? In the docs it says that if md_title_color is not set its supposed to use that as fallback. Right now its still using textColorPrimaryInverse, which might be different.

**Comment by afollestad** [comment]
No, if you don't set your own from the global attribute, it will use
textColorPrimary. If it it determines that textColorPrimary will not be
visible over the dialog background (e.g black on black), it will use
textColorPrimaryInverse. An example of where that would happen is if your
Activity used a light theme, and you used the dark dialog theme; the
primary color of a light activity is a dark shade of gray, which would not
be visible over a dark dialog.

**Comment by JoseTotiRodriguez** [comment]
Ok yeah you're right. Cheers.

**Comment by DaCardinal** [comment]
Same issue here I'm using build '0.7.3.2' and whenever I try to set the titleColorRes() and the contentColorRes() for some reason, both take the color of titleColorRes()

**Comment by afollestad** [comment]
@DaCardinal this issue is closed, and it's completely unrelated to that.

I have no issues in 0.7.3.2 with contentColor being overwritten though. This is from the sample project's themed dialog:

![screen shot 2015-05-07 at 9 06 31 am](https://cloud.githubusercontent.com/assets/1820165/7517075/7c1acf3a-f498-11e4-8047-9b8d2467b579.png)
