### ISSUE TITLE
ProgressDialog without title

### ISSUE THREAD

**Issue by Zaldroc** [afollestad/material-dialogs#414]
I think the ProgressDialog without a title is to small compared to the standard ProgressDialog

![2015-04-07 23 17 05](https://cloud.githubusercontent.com/assets/5994414/7035935/7e379a4e-dd8e-11e4-90a6-7bb566a0f8c3.png)

![2015-04-07 23 21 17](https://cloud.githubusercontent.com/assets/5994414/7035916/4a733baa-dd8e-11e4-8a11-d60721539414.png)

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.1
