### ISSUE TITLE
Input Dialogs String prefill

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#417]
Hi Aidan,
can you please add ability to put String or CharSequence as hint or prefill?

**Comment by afollestad** [comment]
It's already there

**Comment by TomasValenta** [comment]
You are right,
I have tried only this combination:

    .input(0, input_prefill, new MaterialDialog.InputCallback()

but this is correct and working:

    .input(null, input_prefill, new MaterialDialog.InputCallback()

Sorry for this stupid mistake ;)
