### ISSUE TITLE
Single choice list view regression API 16 v0.7

### ISSUE THREAD

**Issue by myanimal** [afollestad/material-dialogs#418]
On API 16 there seems to be a problem with the icon colour (selected and not-selected) for single-choice list view dialogs. Correct colours are used on API 22.

Setting `md_widget_color` changes the selected colour correctly, but the selected colour is not derived from `colorAccent`.

In the image below, version 0.6.7.2 is on the left and looks correct. Version 0.7.0.1 is on the right and has the incorrect (inverse?) colours for the circular checkbox-like thing.

![material-dialogs-list](https://cloud.githubusercontent.com/assets/1039823/7045546/5c57a2f4-ddff-11e4-806a-b34a5b40a2c3.png)

**Comment by afollestad** [comment]
Are you changing the dialog theme with the Builder's theme method? Black is the default color for the light theme, white is the default for the dark theme. 

Widget color only works for API 21 and above.

**Comment by afollestad** [comment]
The only issue I would expect here is that you manually changed the dialog background color, but there could also somehow be a bug.

**Comment by afollestad** [comment]
I should note that Material teal is the default `colorAccent` value in the Material theme or AppCompat, that's why it used to be there.

**Comment by myanimal** [comment]
The dialog theme is set to dark in styles.xml. On 0.7 it picks up the dark theme correctly, so setting the theme explicitly has no effect (same results with it set to black theme vs not setting any theme in xml).

`colorAccent` is set to #3ADBBC using AppCompat dark theme.

Perhaps using a `TintRadioButton` from AppCompat instead of a standard `RadioButton` would apply the correct tinting for API < 21?

**Comment by afollestad** [comment]
Well, that's a good idea, but those views only pull the tint colors directly from your Activity theme. However, I might try to sub-class them later to pull out the custom values dynamically.

**Comment by afollestad** [comment]
Commenting as a note to myself.

The `tintDrawable` method in `TintManager` (line 135) needs to be overridden and changed to use a custom color rather than extracting colors from theme attributes:

https://android.googlesource.com/platform/frameworks/support/+/c497221ee0e2e873f49653ff1a046df2e5276759/v7/appcompat/src/android/support/v7/internal/widget/TintManager.java

**Comment by afollestad** [comment]
I actually believe PR https://github.com/afollestad/material-dialogs/pull/416 will solve this

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0

**Comment by myanimal** [comment]
Perfect, works as expected in 0.7.1.0. Thanks for the quick response!
