### ISSUE TITLE
Widget colors

### ISSUE THREAD

**Issue by nicolausYes** [afollestad/material-dialogs#420]
Am I missed something, is it suppose to work now?

I've updated from 0.6.3.1 to 0.7.0.1 and it seems to be broken. 
Widget colors (radio buttons, checkboxes) have to be colorAccent (for AppCompat) or android:colorAccent (for the Material theme) but they are always black.

Defining global theming attribute md_widget_color doesn't work.

In the sample application on google play they are black too.

**Comment by afollestad** [comment]
This has already been fixed and will be in the next update.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0
