### ISSUE TITLE
API 10 progress bars not tinted correctly with new MDTintHelper – need to backport drawables

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#421]
@plusCubed we might need to copy custom drawables over from AppCompat or something, the default progress drawables do not work for color filtering on low API levels, lol.

![screen shot 2015-04-08 at 11 51 44 am](https://cloud.githubusercontent.com/assets/1820165/7050256/acb6ecb0-dde5-11e4-8a67-183f6d7c22ac.png)
![screen shot 2015-04-08 at 11 51 48 am](https://cloud.githubusercontent.com/assets/1820165/7050257/adcd0382-dde5-11e4-8b4a-5a7befb08ce3.png)

**Comment by afollestad** [comment]
Forgot to include the input dialog too, it uses the default `colorAccent` value but the tint manager doesn't seem to change it

![screen shot 2015-04-08 at 12 11 31 pm](https://cloud.githubusercontent.com/assets/1820165/7050645/748dd526-dde8-11e4-8d5e-adcefb0148f9.png)

@plusCubed

**Comment by afollestad** [comment]
I actually believe @teslacoil mentioned something about using custom progress drawables in Nova.

**Comment by plusCubed** [comment]
EditText bug fixed. For the progress drawables, I think the only option is backporting them from lollipop (since the AppCompat library doesn't have it yet).

**Comment by afollestad** [comment]
Sweet, and yeah I think that's the only solution.

We may wanna add elevation shadows to the window backgrounds on API 10.

**Comment by afollestad** [comment]
API 22 uses animated vectors for a few of the progress drawables, by the looks it it. So I think something slightly older will have to be used (e.g. the Holo drawables).

**Comment by plusCubed** [comment]
I pushed a compromise of sorts - use the multiply porterduff mode on API10 or less. The determinate progress bar will probably not look so great with other colors not similar to the gingerbread orange (e.g. if OEM chose blue, blue+pink = some muddy color not pink). The indeterminate one should work fine if it's grey as in stock, but OEM drawables can mess it up.

![untitled](https://cloud.githubusercontent.com/assets/6379975/7053906/9e9bdb7e-dded-11e4-8a21-2b7eed4e6c39.png)

**Comment by afollestad** [comment]
Cool, thanks. That shouldn't be too much of an issue since no one _should_ be using Gingerbread anymore anyways, lol.

**Comment by plusCubed** [comment]
Note to self/others: the AppCompat `TintCheckBox` theming is broken on API 10 and below (everywhere, not just material-dialogs). As a workaround, if you support API 10 and use a `CheckBox` widget anywhere in your app (other than the multiple choice dialog b/c it's done for you), call `MDTintHelper.setCheckBoxTint(checkbox, accentcolor)` to set the correct drawables. This can be seen in the sample app (509cb91dcf4983b691a6e09b127774fa22d0f2f8) for the custom view demo.
