### ISSUE TITLE
No dividers in long Multi Choice Dialog

### ISSUE THREAD

**Issue by Zaldroc** [afollestad/material-dialogs#422]
If you use a Multi Choice Dialog with a long content, there is no divider above the action buttons.

**Comment by afollestad** [comment]
This is working fine for me. The divider goes away at the bottom when you scroll to the bottom.

Can you reproduce this @plusCubed?

**Comment by afollestad** [comment]
E.g. at the top:

![screen shot 2015-04-08 at 2 03 50 pm](https://cloud.githubusercontent.com/assets/1820165/7053070/33640aba-ddf8-11e4-9af4-5405337c4da6.png)

To the bottom:

![screen shot 2015-04-08 at 2 03 59 pm](https://cloud.githubusercontent.com/assets/1820165/7053076/39b227b2-ddf8-11e4-82c4-aecb1d14a6ad.png)

**Comment by Zaldroc** [comment]
![screenshot_2015-04-08-21-33-50](https://cloud.githubusercontent.com/assets/5994414/7053658/210e90a8-de37-11e4-8fae-bb9ca12e170c.png)

Maybe it's because of the content message?

**Comment by afollestad** [comment]
Hmmm, that's possible.

I can take a look later, or @plusCubed probably could if he's not busy.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.0

**Comment by Zaldroc** [comment]
There's a divider at the bottom now but not at the top.
![screenshot_2015-04-09-14-33-28](https://cloud.githubusercontent.com/assets/5994414/7066743/e1187998-dec5-11e4-8707-1f936fa05f07.png)

**Comment by afollestad** [comment]
That's correct behavior. The bottom has a divider because the content right
before the divider can scroll. At the top, the text view is not scrollable.
