### ISSUE TITLE
这个在eclipse中怎么导入呀?

### ISSUE THREAD

**Issue by lifetin** [afollestad/material-dialogs#425]
搞了半天不会.郁闷...
这个好像是as打包的吧?

**Comment by afollestad** [comment]
Sorry I'm not fluent in Mandarin. Any issues related to Eclipse are duplicates though.

**Comment by lifetin** [comment]
I need a Eclipse file.
Or is jar complete package has not

**Comment by afollestad** [comment]
Sorry, no. You can't use JARs with Android library projects, JARs can't include resources, only code. You need to import it as a library project or use the Gradle dependency from Android Studio.
