### ISSUE TITLE
MaterialEditTextPreference getDialog returns null

### ISSUE THREAD

**Issue by eduplus** [afollestad/material-dialogs#427]
It would be nice to have a reference to the dialog, for example could do similar thing that the first answer does in this thread: 

http://stackoverflow.com/questions/4762027/edittextpreference-disable-buttons

I have it working as expected with EditTextPreference, but when I switch to MaterialEditTextPreference it will crash due to getDialog returning null.

**Comment by afollestad** [comment]
Good catch, fixed
