### ISSUE TITLE
Title is white(invisible) with Theme.LIGHT

### ISSUE THREAD

**Issue by osrl** [afollestad/material-dialogs#428]
```java
new MaterialDialog.Builder(this)
         .theme(Theme.LIGHT)
         .title("Bilgi")
//       .titleColor(Color.BLACK)
         .content(R.string.info_content)
         .positiveText(android.R.string.ok)
         .show();
```

I use above code to create the Dialog but the title color is white.

**Comment by afollestad** [comment]
Well, the sample project uses mostly light dialogs. It works fine. You
probably have an issue in your Activity theme somewhere.

**Comment by afollestad** [comment]
Do you override `textColorPrimary` in your Activity theme?

**Comment by afollestad** [comment]
This is the sample project, with a dialog basically identical to the one that would be made above:

![md1](https://cloud.githubusercontent.com/assets/1820165/7068894/2f0a01ec-de9b-11e4-8eae-9784e00017a5.png)

**Comment by osrl** [comment]
I did override `textColorPrimary `. Thanks
