### ISSUE TITLE
Can't set items gravity

### ISSUE THREAD

**Issue by msaudicse** [afollestad/material-dialogs#429]
MaterialDialog dialog =
                new MaterialDialog.Builder(context)
                        .title(R.string.manage)
                        .titleGravity(GravityEnum.CENTER)
                        .items(R.array.profile_options)
                        .itemsGravity(GravityEnum.CENTER)
                        .typeface(typeface, typeface)
                        .itemsCallback(callback).build();

can't resolve method itemsGravity

**Comment by afollestad** [comment]
Can't resolve it? That means you're not using a new version of the library

**Comment by msaudicse** [comment]
What a fast response. Thank you.
