### ISSUE TITLE
Loading fonts

### ISSUE THREAD

**Issue by gdbgeek** [afollestad/material-dialogs#432]
Aidan, thanks for this awesome library. I am using the library with Basic4Android (www.b4x.com).

Basic4Android lower cases all asset names so the font wont load unless I alter TypefaceHelper.java to lower case the font name like so;

                Typeface t = Typeface.createFromAsset(
                        c.getAssets(), String.format("fonts/%s.ttf", name).toLowerCase());

Would it be a huge deal if you lower cased all font names in the assets folder and the font loader in DialogInit.java? If you did that I wouldnt need to alter TypefaceHelper.java.

        // Check if default library fonts should be used
        if (!builder.useCustomFonts) {
            if (builder.mediumFont == null)
                builder.mediumFont = TypefaceHelper.get(dialog.getContext(), "roboto-medium");
            if (builder.regularFont == null)
                builder.regularFont = TypefaceHelper.get(dialog.getContext(), "roboto-regular");
        }

Thanks heaps.

Trevor

**Comment by afollestad** [comment]
You can explicitly set your own Typeface instances with `typeface(Typeface, Typeface)` rather than using `typeface(String, String)` if that's the issue.

The uppercase file names are correct naming conventions
