### ISSUE TITLE
design of progress dialog on gingerbread

### ISSUE THREAD

**Issue by agrajaghh** [afollestad/material-dialogs#433]
I'm not sure if it's really a bug, just close it if it's intended...

The circle progress indicator doesn't look material wise on gingerbread. Some "sharp" progress indicator without the fading would look better I think
![progress_light](https://cloud.githubusercontent.com/assets/5296073/7079285/af107718-df22-11e4-892c-c0064a9e3c22.png)

**Comment by afollestad** [comment]
Right now, this is intended. Unfortunately there's no easy way around this, so this is the best that could be done for such an old Android version. People should be encouraged to stop using Gingerbread anyways.

**Comment by afollestad** [comment]
I should mention that's just Gingerbread's regular progress drawable with a color filter added to it.

**Comment by agrajaghh** [comment]
okay I see. But Is it possible to use the background color for the darker color? This would get closer to the material design I guess...

regarding GB: you're right, I hate it... But unfortunately there are still too many GB devices out there...

**Comment by agrajaghh** [comment]
just saw you can just set one color, forget what I said...
