### ISSUE TITLE
Gravity bug for RTL languages.

### ISSUE THREAD

**Issue by Reza-Rg** [afollestad/material-dialogs#434]
I know that Google recommend using `END` and `START` for gravity instead of `LEFT` and `RIGHT`, but actually there is a bug in some android versions that cause gravity fail setting when text is RTL.
So, could you please add `LEFT` and `RIGHT` Gravity to `GravityEnum` for RTL languages?

An image from android 4.1.1 on Genymotion emulator and device:

![screenshot 2015-04-10 13 32 39](https://cloud.githubusercontent.com/assets/3043068/7084939/69e3bc30-df87-11e4-8f49-3b33fc40a6cd.png)

and this image same app and code when on android 4.4.4 on Genymotion emulator and device: 

![screenshot 2015-04-10 13 32 43](https://cloud.githubusercontent.com/assets/3043068/7084970/8a0119f4-df87-11e4-9647-c04b7b7d9f59.png)

You can reproduce this bug, using this code :

                           
                    new MaterialDialog.Builder(MainActivity.this)
                            .titleGravity(GravityEnum.END)
                            .contentGravity(GravityEnum.END)
                            .title("چقدر عجله داری بابا!")
                            .content("این ویژگی در نسخه‌ی بعدی فعال خواهد شد! برو بعدن بیا!")
                            .positiveText("باشه. :(")
                            .negativeText("چه بهد")
                            .typeface("iran_sans_bold","iran_sans")
                            .callback(new MaterialDialog.ButtonCallback() {
                                @Override
                                public void onPositive(MaterialDialog dialog) {
                                    Log.wtf("+","shod");
                                }

                                @Override
                                public void onNegative(MaterialDialog dialog) {
                                    Log.wtf("-","shod");
                                }
                            })
                            .show();

and both images will be in opposite direction while using `GravityEnum.Start`.

**Comment by teslacoil** [comment]
Android 4.1 doesn't fully support RTL. It sounds like you want to work around this Android 4.1 limitation by using Gravity.END for RTL languages on 4.1 (which is exactly the same as RIGHT on 4.1) and Gravity.START on > 4.1.
Using Gravity.RIGHT everywhere would sacrifice non-RTL languages

**Comment by afollestad** [comment]
Hmm, I thought 4.1 was the first API level to start full RTL support but
maybe I'm wrong. But yeah my intention was to not support explicit right
and left gravities since devs need to be conscious of RTL support these
days.

**Comment by Reza-Rg** [comment]
But actually I had no difficulties for RTL texts in my apps since API 8 by using Right and Left Gravity (Except some HTC Models), but after android 4.0.0 , I haven't seen any problem in RTL Text, when using Left and Right Gravity. But now, I notices that using Gravity END and START does not work on some android distribution (and not only 4.1, I've seen this issue in a device with android 4.2 too)

So, what you guess is a good solution?

And by the way, it's so hard to be a developer in ME countries! Apart from RTL Problem, we also face date and currency conversion problem in different android version, other than sanction and ... :|

**Comment by afollestad** [comment]
We fall back to left and right on old devices that don't support start and
end. The library automatically does this for you.

**Comment by Reza-Rg** [comment]
Great.
Waiting for update!
Thanks. :)

**Comment by afollestad** [comment]
What? This is current behavior.

**Comment by Reza-Rg** [comment]
I misunderstood your comment, and I thought a fix would be provided. So, the only solution is that myself add LEFT and RIGHT Gravity for my situation?

**Comment by Reza-Rg** [comment]
I read `GravityEnum.java`  and `DialogInit.java`  codes again, and I guess I found where the bug is.
As you mentioned the library automatically change `END` and `START` Gravity to `RIGHT` and `LEFT` based on if android version is lower than 4.2 or not using this code :

            private static final boolean HAS_RTL = Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1;

    public int getGravityInt() {
        switch (this) {
            case START:
                return HAS_RTL ? Gravity.START : Gravity.LEFT;
            case CENTER:
                return Gravity.CENTER_HORIZONTAL;
            case END:
                return HAS_RTL ? Gravity.END : Gravity.RIGHT;
            default:
                throw new IllegalStateException("Invalid gravity constant");
        }
    }


it should be working, but problem occurs in `DialogInit.java ` after setting Gravity, when trying to set text alignment using this code:


            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                //noinspection ResourceType
                dialog.content.setTextAlignment(builder.contentGravity.getTextAlignment());
            }


Why should set TextAlignment, when without it Gravity works fine for both RTL and LTR Languages?

For example, when text is RTL and Gravity is `END` in all version text should be on Right (and text is on right side before setting textAlignment), but after setting text alignment, text goes to Left side (which should not).

Right?

**Comment by Reza-Rg** [comment]
I also read this issue #256 and it seems you had problem with textAlignment before, I guess it's the same problem and revert using textAlignment would solve it! :)

**Comment by tux-world** [comment]
resolve this problem?

**Comment by HamedGh** [comment]
@Reza-Rg 
I wrote this code to solve the problem:
`
        public static boolean isRTL() {
		return isRTL(Locale.getDefault());
	}

	public static boolean isRTL(Locale locale) {
		final int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
		return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
				directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
	}
	public void showLogoutDialog(){

		boolean HAS_RTL = Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1;

		GravityEnum dir,btnDir;

		if (HAS_RTL){
			if (isRTL()) {
				dir = GravityEnum.START;
				btnDir = GravityEnum.START;
			} else {
				dir = GravityEnum.START;
				btnDir = GravityEnum.END;
			}
		}else {
			dir = GravityEnum.END;
			btnDir = GravityEnum.END;
		}
		new MaterialDialog.Builder(this)
				.titleGravity(dir)
				.contentGravity(dir)
				.buttonsGravity(btnDir)
...

}
`
