### ISSUE TITLE
Hide radio buttons

### ISSUE THREAD

**Issue by treylon** [afollestad/material-dialogs#435]
Hey I was wondering if there is a way to hide the radio buttons of a list dialog without using a custom view or a custom adapter?

**Comment by afollestad** [comment]
Radio buttons are only there for single choice dialogs.

**Comment by treylon** [comment]
I think you misunderstood my question. I was trying to achieve something like that, but without the icons:

![dailog](https://cloud.githubusercontent.com/assets/10380579/7088079/782cda7e-df91-11e4-8a57-bc56e8eeedda.png)

**Comment by afollestad** [comment]
You need to make a custom list adapter, radio buttons are hard coded into the single choice dialog list item layout.

**Comment by afollestad** [comment]
Look at the custom adapter example in the sample project
