### ISSUE TITLE
Pre-Select item in single selection dialog

### ISSUE THREAD

**Issue by taar1** [afollestad/material-dialogs#436]
I couldn't figure out how to preselect an item in a radio list dialog (single choice). I checked the sample code and couldn't find anything, even though in the demo app the single choice dialog already has one item preselected when opening.
How can I achieve this? Thanks.

MaterialDialog.Builder materialBuilder = new MaterialDialog.Builder(getActivity());
        materialBuilder.title(dialogTitle)
                .items(R.array.mailing_channels)
                .widgetColorRes(R.color.postYellowDark)
                .positiveColorRes(R.color.defaultTextColor)
                .positiveText(R.string.okay);
        return materialBuilder.build();

**Comment by afollestad** [comment]
You must not be reading the README tutorial or sample project closely enough. 

`itemsCallbackSingleChoice`
