### ISSUE TITLE
Ability to choose MaterialEditTextPreference EditText implementation

### ISSUE THREAD

**Issue by eduplus** [afollestad/material-dialogs#438]
In MaterialEditTextPreference the dialog uses default EditText implementation, which is not having material dialog -like error messages, and the "old style" error messages come over the buttons:

![material_dialog_edittext_problem](https://cloud.githubusercontent.com/assets/2563512/7092293/241f7c66-dfb9-11e4-8436-8b4d00876a5e.png)

It would be really nice to be able to choose or replace the default implementation with custom one. We are using in our project this one: [MaterialEditText](https://github.com/rengwuxian/MaterialEditText) Their implementation has a nice error handling which looks like this: 
![MaterialEditText error](https://github.com/rengwuxian/MaterialEditText/raw/master/images/helper_error_text.png)

It would be really nice to be able to choose/replace this implementation to be used within MaterialEditTextPreference. It would not go over the dialog buttons.

**Comment by afollestad** [comment]
You can subclass MaterialEditTextPreference to do this.
