### ISSUE TITLE
MaterialDialog closeв automatically?

### ISSUE THREAD

**Issue by crysan** [afollestad/material-dialogs#442]
Hi!
            new MaterialDialog.Builder(MainActivity.this)
                    .title(R.string.dialog_loading)
                    .customView(R.layout.dialog_update_author, false)
                    .autoDismiss(false)
                    .show();

By clicking on the MaterialDialog window not closes. 
However, when you click on an empty area Activity window closes automatically. 
How can this be solved?

**Comment by intrications** [comment]
@crysan 

Try setting `.cancelable(false)`.

`autoDismiss` stops the dialog closing automatically when you click on one of the buttons.

**Comment by crysan** [comment]
Yes!
