### ISSUE TITLE
After update I lost theming

### ISSUE THREAD

**Issue by emartynov** [afollestad/material-dialogs#444]
I've updated to latest 0.7.1.3 and after run I see that background and text changed colours:

![screenshot 2015-04-13 12 34 20](https://cloud.githubusercontent.com/assets/295424/7113998/8090ba92-e1d9-11e4-9770-3be9c23c1826.png)

I'm still using `AlertDialog` wrapper.
I've also tried `<item name="md_dark_theme">false</item>` but without success.

Just for comparison here is what I saw before:
![screenshot 2015-04-13 13 13 35](https://cloud.githubusercontent.com/assets/295424/7114573/eaf66b66-e1de-11e4-8c1d-145bbd45d044.png)

**Comment by afollestad** [comment]
I'll try to get this fixed.

The reason why this happens: when you construct a `Builder`, it sets a default theme (Light or Dark) based on the `?android:textColorPrimary` attribute of your Activity. If it's light (e.g. a shade of white), it guesses the Activity is using a dark theme. If it's dark (e.g. a shade of gray), it guesses the Activity is using a light theme. `DialogInit` checks if you set `md_dark_theme`, but the default value is false, so it assumes if `md_dark_theme` is false that you didn't override the default theme in the `Builder`.

**Comment by emartynov** [comment]
Thanks for commenting. Just one thing for me is not obvious. If I set `md_dark_theme` to `false` in my theme I still get dark dialogs. I don't get from your explanation is it as expected or an issue.

**Comment by afollestad** [comment]
Basically, setting it to false has no effect because it's assuming that's the default value and it doesn't override the default theme that the `Builder` loads. But yes, it's a bug.

**Comment by afollestad** [comment]
This is now fixed with https://github.com/afollestad/material-dialogs/commit/c39b09e0cefbf98282c1a8ba216b6c60038bd373, an update will come today

**Comment by emartynov** [comment]
Thanks!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.0
