### ISSUE TITLE
Single Choice List Dialog as DialogFragment and implement it in Fragment subclass

### ISSUE THREAD

**Issue by h0aX14** [afollestad/material-dialogs#445]
Here is my subclass of DialogFragment

```java
public class AB extends DialogFragment {

    public interface ABListener {
        void A();
        void B();
    }
 
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        return new MaterialDialog.Builder(getActivity())
                .title("title")
                .items(R.array.array_ab)
                .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                        switch (which) {
                            case 0:
                                ((ABListener) getActivity()).A();
                                return true;
                            case 1:
                                        ((ABListener) getActivity()).B();
                                return true;
                        }
                        return false;
                    }
                })
                .positiveText(R.string.choose)
                .build();
    }
}
```

I call this dialog as follows in Fragment subclass
              
            new AB().show(getActivity().getFragmentManager(), "tag");

and implement those two interface methods in that Fragment subclass and I get errors like ClassCastException 

Please help!

**Comment by afollestad** [comment]
See the sample project, there's two DialogFragment examples

**Comment by h0aX14** [comment]
@afollestad

I tried taking their reference. ImI'm stistill getgetting wrrorserrors forfor sinflesingle xhoichoice list dialog. 
Can you please provide sample code? 
Thanks in advance

**Comment by afollestad** [comment]
The only thing I could think of is the Activity not implementing `ABListener`.

**Comment by h0aX14** [comment]
@afollestad, I have implemented ABListener, still I get class cast exception error when any list item is selected

**Comment by afollestad** [comment]
@h0aX14 can you paste the LogCat error here?

**Comment by h0aX14** [comment]
@afollestad , sorry for the delay(exams on)
java.lang.ClassCastException: com.abc.MainActivity cannot be cast to com.abc.AB$ABListener
            at com.abc.AB$1.onSelection(AB.java:47)
            at com.afollestad.materialdialogs.MaterialDialog.sendSingleChoiceCallback(MaterialDialog.java:760)
            at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:782)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by afollestad** [comment]
It's alright. And yeah, that's definitely an error on your side. It says `com.abc.MainActivity` can not be cast to `com.abc.AB$ABListener` meaning it doesn't implement the interface.

**Comment by h0aX14** [comment]
@afollestad ,I'm implementing that interface in a fragment subclass

**Comment by afollestad** [comment]
Well you can't do that with the way you setup the dialog.

**Comment by h0aX14** [comment]
@afollestad , can you help me out ? This would be useful for all when they are working with fragments subclass and dialogfragment

**Comment by afollestad** [comment]
The only way with your current implementation is to implement the interface in your Activity, and forward it to the Fragment.

But sorry, I can't help today, I have exams in a few minutes.
