### ISSUE TITLE
On a non intermediate ProgressDialog move the progress numbers below the ProgressBar

### ISSUE THREAD

**Issue by git-commit** [afollestad/material-dialogs#448]
Using the ProgressDialog on Android Lollipop with material design puts the percentage and the counter below the ProgressBar [1].
Using your excellent library puts them next to the ProgressBar [2].
I like the percentage being on the right, but would like the values to be below the progress bar (closer to "stock" material design).

[1] ![1](https://cloud.githubusercontent.com/assets/3263955/7134162/8ad2bf66-e29a-11e4-89ea-615c6710fff8.png)

[2] ![2](https://cloud.githubusercontent.com/assets/3263955/7134161/8ad28eba-e29a-11e4-98d5-1f41969458a6.png)

**Comment by afollestad** [comment]
Good idea, done for the next update

**Comment by git-commit** [comment]
Great :smiley:
I see that you are sticking to the *official* way regarding text placement. Just out of curiousity, do you want to adhere to the official dialogs as much as possible or would you consider differences and improvements acceptable?

**Comment by afollestad** [comment]
I try to match them as much as possible, revised guidelines were actually published yesterday to include more information: http://www.google.com/design/spec/components/dialogs.html#dialogs-specs

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.0
