### ISSUE TITLE
MaterialListPreference is not recreated and leaks

### ISSUE THREAD

**Issue by jmartingit** [afollestad/material-dialogs#449]
If I change the device orientation when a MaterialListPreference is on screen, it is not recreated and the logcat shows a leaked window error. Should I do anything in particular to prevent this?

Note: I'm not using the other preference material dialogs, so I don't know if they have the same problem.

A million thanks again for this library and your commitment.

**Comment by afollestad** [comment]
This is an Android issue, more than it's a library issue.

One solution is to use DialogFragments, but this library is mimicking the stock preference dialogs (sub classing them to be more specific).

**Comment by jmartingit** [comment]
Well, the fact that the dialog is not recreated doesn't bother me much. In the end it's a preference and it can be clicked again after the orientation change, so that's not a problem.

But what worries me is the leak issue. Using the MaterialListPreference directly from the library shouldn't lead to a leak.

I guess the solution might come from forcing a dismiss on the material dialog when the activity tries to recreate the preference. On a different preference I had to subclass ListPreference for other things and the only place where I could add a recreation detection is overriding onSaveInstanceState.

The stock ListPreference doesn't leave much room for operation, but at least its doable. Consider adding a dismiss on that method in the library to avoid the leak if you see it fit.

**Comment by afollestad** [comment]
Well it looks like the developer of AcDisplay fixed this in https://github.com/afollestad/material-dialogs/commit/f342429633559cb448b32b27fec845c8aa2997d6, but it may've not completely worked

**Comment by afollestad** [comment]
Nevermind, he only partially fixed it. I find the source and fixed it.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.0

**Comment by jmartingit** [comment]
Brilliant!!! Many many thanks!!! ;)
