### ISSUE TITLE
Prevent dialog closing when clicking outside the dialog

### ISSUE THREAD

**Issue by ido567** [afollestad/material-dialogs#450]
Please add the option to prevent closing the dialog when the user clicks outside it.

**Comment by alorma** [comment]
You can achieve that with Bulider.cancelable(false);

**Comment by afollestad** [comment]
@ido567 did you read the documentation?

**Comment by ido567** [comment]
I read the entire README.md, most of the developers won't read more than that :\
So it will be a good idea to put it option there

**Comment by afollestad** [comment]
It should be assumed the cancelable method is there since MaterialDialog extends Dialog, Dialog's are a system API which include `setCancelable()`. The `Builder` also includes a `cancelable()` method.

I'll add a small snippet about this though.

**Comment by afollestad** [comment]
The README is the only documentation there is, btw. The sample project is also very easy to understand but there's nothing related to cancelable in there at the moment.
