### ISSUE TITLE
Dialog with list && edit text

### ISSUE THREAD

**Issue by alorma** [afollestad/material-dialogs#453]
Hi.

Nice work adding InputType to edit text dialog.

I want to use the list dialog, with an option to add custom option, how can i achieve that? Using custom view? but then i "lost" the colours and all pretty stuff from MaterialDialogs.

Thanks

**Comment by afollestad** [comment]
Yeah you'd need a custom view.

Custom colors are applied to EditTexts and other views using `MDTintHelper`. You don't need that if you use AppCompat though.

**Comment by afollestad** [comment]
AppCompat colors the UI with the `colorAccent` attribute, to be specific.
