### ISSUE TITLE
Input: Focus on end of line

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#455]
When starting a dialog containing an input, the cursor automatically jumps to the start of the line.

It would be great to have it start at the end of the line, so users can start writing / deleting without the distraction of having to move the cursor to the end.

**Comment by afollestad** [comment]
This isn't the case for me. Yesterday's update did the opposite.

**Comment by Ph1b** [comment]
Okay, thats funny that you just made that change yesterday. I was at 0.7.2.0 ^^

Keep up the good work

**Comment by afollestad** [comment]
Oh cool :)

The girl is my girlfriend, lol
