### ISSUE TITLE
Library should run fine with font assets missing

### ISSUE THREAD

**Issue by vovkab** [afollestad/material-dialogs#456]
Is it possible to remove fonts from aar?
If for example I want to use default or my own font, it would be nice to save 300kb apk size.

Maybe separate font and library in different aar's?

**Comment by afollestad** [comment]
Sorry, there's no current way to do that as far as I know.

**Comment by vovkab** [comment]
Maybe keep this ticket as feature request?

**Comment by afollestad** [comment]
You can currently customize fonts, but there's no way to remove fonts from a published library without removing them for everybody (to reduce size). That's not quite a feature, just a change.

**Comment by vovkab** [comment]
Maybe you can make that if font is missing, library would fallback to default system font?

I will check maybe we could use shrink resource via gradle to remove this fonts in compile time, but we will need library to expect this behavior and handle it correctly.

**Comment by afollestad** [comment]
Roboto is only a system font on newer API levels. It's included in this library so that older API levels get to use it too. Newer API levels tend to update Roboto too, so even API levels that had Roboto get new Roboto updates with this library.

**Comment by vovkab** [comment]
What I'm saying, is if assets folder is gone, can we make library act appropriately?
Right now I guess it will crash.

**Comment by afollestad** [comment]
Ohhh, it would require more suppressing that crash to make it work. Internal library code distributes the fonts to many different views.

**Comment by vovkab** [comment]
Something like this:
If (font is missing) return TypeFace.NORMAL
There is no need to change all views, just TypefaceManager

**Comment by afollestad** [comment]
That doesn't solve the issue though.

I'm not planning on removing the fonts from the library itself, because most developers will be too lazy to include them in their own app and don't bother reading documentation.

**Comment by vovkab** [comment]
Again, as I explained it above, you don't need to remove fonts.
But if they are gone, library should be fine with it.

**Comment by afollestad** [comment]
The fonts are hardcoded into the library. You can't remove them once Gradle downloads them.

The only way you could be removing them is if you fork this repository and remove them yourself.

**Comment by vovkab** [comment]
It is not important when and how they will be removed.
What is - library should be fine without them.

**Comment by afollestad** [comment]
Hmm, good point

**Comment by alorma** [comment]
well... make things protected against some basic components... sounds weird.

It's something like

String words = "my code";
If (words != null) ...

That have no sense

**Comment by afollestad** [comment]
Yeah, those were my thoughts too

**Comment by vovkab** [comment]
@alorma as per my first suggestion - make fonts pluggable, this would also be fine with me.

**Comment by alorma** [comment]
That't different from fonts not exist i think.

You can plug a font, but default are still there

**Comment by afollestad** [comment]
The commit that closes this catches the runtime exception thrown when the assets aren't found, and returns null in that case. Keep in mind that all fonts will look the same throughout every dialog if you remove them.

**Comment by gdbgeek** [comment]
From what I've seen an exception is thrown if the included font assets cant be found.

As per my issue (https://github.com/afollestad/material-dialogs/issues/432) I was getting an exception as my IDE was lower casing the font names (and hence they arent able to be loaded).

**Comment by afollestad** [comment]
@gdbgeek yeah, this issue is already closed

**Comment by vovkab** [comment]
@alorma not really.
Roboto is there only to support old pre api14. Since most of the apps this days targeting min 14 or even 15, there is no point to keep fonts inside library. 
Thous few people who still need support for api8, probably already have roboto fonts packaged in their assets, so now they are doubled, or don't care about fonts. They can ignore it or plug with one just one more line.

@afollestad thanks, looks like null should be fine, looks like textview fallback to default style.

**Comment by vovkab** [comment]
Btw, looks like TypeFacemanager is limited, it only accepts ttf, while there also otf and etc...

**Comment by afollestad** [comment]
@vovkab that's by design. There's a variation of `typeface` in `MaterialDialog#Builder` that takes `Typeface` instances. `TypefaceHelper` is only for internal library use.
