### ISSUE TITLE
To preserve string res formatting, Builder#content(int) impl should not use getString but getText

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#458]
If I have a resource

    <string name='s'><b>Bold</b> <i>Italic</i></string>

and then I call

    new MaterialDialog.Builder(context).content(R.string.s)

the formattings on the string is removed, because the implementation of `content()` is `getString(resId)` not `getText(resId)`, which preserves formatting. 

Implementations of AlertDialog.Builder, TextView#setText(int) and so on, all uses getText() instead of getString().

**Comment by afollestad** [comment]
That formatting doesn't get preserved even with `getText()`, unless you wrap it in `Html.fromHtml()`, as far as I know.

```java
CharSequence content = Html.fromHtml(context.getString(R.string.s));
new MaterialDialog.Builder(context).
    .content(content)
    ...
    .show();
```

**Comment by yukuku** [comment]
No, it works without any Html.fromHtml. The key is that string resources
MAY contain formatting, but when we retrieve the resource, we can either
use getString, which omits all formatting, and returns a String, or
getText, which preserves all formatting, and returns a CharSequence
implementation, which has the characters plus formatting tags.

I can send you an example project if you need it.

**Comment by alorma** [comment]
Code example will be awesome!

**Comment by afollestad** [comment]
@yukuku well I use formatted char sequences quite a lot, including in 3 production apps I've made and 2 apps I've made for others.

getString() doesn't omit formatting, it returns the literal string. I wasn't aware that getText() loads the HTML formatting though.

**Comment by afollestad** [comment]
Done

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.3
