### ISSUE TITLE
MultiChoiceItems is not work

### ISSUE THREAD

**Issue by st7105** [afollestad/material-dialogs#460]
...
final boolean[] checks;
...

dialog.setMultiChoiceItems(list, checks, new DialogInterface.OnMultiChoiceClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which, boolean isChecked) {
                ...
            }
        });

'checks' is not change after close dialog.

**Comment by afollestad** [comment]
That's not quite how Java works, or this library. See the README or sample project.

**Comment by st7105** [comment]
Before it is work, but after include library and switch to AlertDialogWrapper is not work.

**Comment by st7105** [comment]
builder.itemsCallbackMultiChoice(selectedIndicesArr, new MaterialDialog.ListCallbackMultiChoice() {
                @Override
                public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
                    /* which is a list of selected indices */
                    List<Integer> whichList = Arrays.asList(which);
                    if (checkedItems != null) {
                        for (int i = 0; i < checkedItems.length; i++) {
                            /* save old state */
                            boolean oldChecked = checkedItems[i];
                            /* Record new state */
                            checkedItems[i] = whichList.contains(i);
                            /* Fire the listener if it changed */
                            if (oldChecked != checkedItems[i]) {
                                listener.onClick(dialog, i, checkedItems[i]);
                            }
                        }
                    }
                    return true;
                }
            });

I think is not good solution.

**Comment by afollestad** [comment]
The checked items get passed in `Integer[] which`, you can not modify the preselection (`selectedIndicesArr`) because Java does not pass primitive arrays as references.

**Comment by afollestad** [comment]
Not really sure what you have an issue with here. It works fine for everybody else.
