### ISSUE TITLE
Dialog to input password does not work as expected

### ISSUE THREAD

**Issue by vmihalachi** [afollestad/material-dialogs#461]
Hi, this line is not sufficient to make the dialog input be hidden

```
.inputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)
```

I have also needed to add this

```
dialog.getInputEditText().setTransformationMethod(PasswordTransformationMethod.getInstance());
```

Could you make that the dialog automatically does this if as an input type you specify password?

**Comment by afollestad** [comment]
There's more masks required, this is a framework issue more than it's a library issue

**Comment by vmihalachi** [comment]
Don't understand what you mean by "There's more masks required", could you explain me?

**Comment by afollestad** [comment]
Oh sorry I wasn't actually at my computer when I initially read this.

I remember using pretty much the same thing (http://stackoverflow.com/a/9893496) before, and it worked fine. You're saying you needed the transformation to make it work?

**Comment by vmihalachi** [comment]
Exactly, I think I saw the same link. Without the transformation the text is not hidden.

**Comment by afollestad** [comment]
It actually works completely fine for me, without setTransformationMethod, if I move setting the inputType to the bottom after setting everything else up for the EditText. However, I will put setTransformationMethod in there just in case it doesn't work on some devices.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.3

**Comment by vmihalachi** [comment]
Thanks! :)
