### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by chongivan** [afollestad/material-dialogs#462]
According to the [docs](http://www.google.com/design/spec/components/dialogs.html#dialogs-specs), there should be a **8dp** padding at the bottom, which is absent now.

![dialog](http://i.imgur.com/gjYnWWV.jpg)

**Comment by afollestad** [comment]
Well, 8dp with non-list dialogs. With list dialogs, a larger value is used:

![screenshot_2015-04-18-01-50-39](https://cloud.githubusercontent.com/assets/1820165/7214340/702fe618-e56d-11e4-94a8-aacc6f64e7ab.png)

**Comment by chongivan** [comment]
Currently, the padding is not there for list dialogs.

Would you be adding it? 

Thanks =)

**Comment by afollestad** [comment]
It is on my end, the current implementation (MDRootLayout) was actually implemented by Nova Launcher's dev.

It's possible it's an issue with the API level you're testing on, but it works fine on 4.4.4, 5.0, and 5.1 (and lower API levels I tested with emulators before).

**Comment by chongivan** [comment]
Im on 4.3, Samsung Note 2. 

Small issue then.

Thanks for the lib, it's great.
