### ISSUE TITLE
Shadow unavailable for pre-Lollipop

### ISSUE THREAD

**Issue by javmarina** [afollestad/material-dialogs#464]
Some weeks ago, dialogs had a nice shadow as borders that gave the idea of elevation. However, now dialogs don't have shadows at all, and background outside dialog is not darkened. I'm using Xperia Z with Android 4.4.4
You can see in the screenshot that dialog background is exactly the same as activity background (the icons on the navigation bar are just from a Xperia theme).
PS: open animation now looks worse (alpha instead of resize), but it follows Material Design guidelines...
![screenshot_2015-04-18-19-46-51](https://cloud.githubusercontent.com/assets/2737599/7216577/7945faac-e604-11e4-9b18-d6186489903f.png)

**Comment by afollestad** [comment]
Hmmm. It works fine on stock KitKat because the background fades. Sony's implementation must not do that for whatever reason.

**Comment by afollestad** [comment]
Can you check if this helps? I don't have access to a Sony device

https://github.com/afollestad/material-dialogs/commit/00c9c04133b42020ddeb08f63412ab1588307179

**Comment by RadiationX** [comment]
No shadow
![s50419-191133](https://cloud.githubusercontent.com/assets/5782280/7219748/4282ee02-e6c8-11e4-924e-6da2ea4f0f1d.jpg)

In real application
![s50419-173122](https://cloud.githubusercontent.com/assets/5782280/7219751/6aea00ba-e6c8-11e4-916f-cd198ba31e8d.jpg)
![s50419-173126](https://cloud.githubusercontent.com/assets/5782280/7219752/6ee28eee-e6c8-11e4-8452-dd945ae42976.jpg)

Also no animation increase dialogue. Device Meizu MX3 Android 4.4.4

**Comment by afollestad** [comment]
It appears the new AppCompat update has some new themes that will aid in theming dialogs before Lollipop.

**Comment by javmarina** [comment]
Well, it might be a Sony problem but the issue still isn't resolved. Strangely, this also happens when I use AppCompat 22.1 instead of this library. I have opened a new issue, see https://code.google.com/p/android/issues/detail?id=170111

**Comment by afollestad** [comment]
This library actually uses AppCompat 22.1's themes at the base.
