### ISSUE TITLE
jCenter issue

### ISSUE THREAD

**Issue by sashatinkoff** [afollestad/material-dialogs#467]
Hey mate!

First of all I'd like to tell you that you work on great library! Thank you!
I found out that I can't include your library in the project and I suspect that it is because the library accidentally got removed from jCenter. Can you specify the approximate date when it will be solved?

**Comment by afollestad** [comment]
Thank you.

Yeah, like the large header at the top of the README says, it accidentally got removed. No idea how long they'll take.

**Comment by alorma** [comment]
We can download it and use as an aar?

**Comment by afollestad** [comment]
As a temporary work around, add this inside repositories { }

```Gradle
maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
```

**Comment by afollestad** [comment]
The library is back on jCenter now
