### ISSUE TITLE
Input dialog?

### ISSUE THREAD

**Issue by druidamix** [afollestad/material-dialogs#468]
Hi,
Can you add generic question,input,etc dialogs?

Thanks.

**Comment by Rainer-Lang** [comment]
Could you give an example (maybe an image)?

**Comment by druidamix** [comment]
Dialog with an edittext to enter numbers,float or text. Now I'm doing it with a custom view, but it's a bit tedious.
It's a suggestion.

Thanks.

**Comment by egor-n** [comment]
Is [this](https://github.com/afollestad/material-dialogs#input-dialogs) not what you are looking for?

**Comment by druidamix** [comment]
Sorry!!!
You are right.

I didn't see it :(
