### ISSUE TITLE
DrawableCompat from updated Google libraries now supports backwards compatible tint lists

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#470]
MDTintHelper is no longer needed

**Comment by alorma** [comment]
Neither dialogs, now there is a SupportDialog :o!

Will you update lib to use this as base?

**Comment by afollestad** [comment]
AppCompatDialog is just an AlertDialog wrapper, MaterialDialog does not extend AlertDialog, it extends the base Dialog class.

I don't believe AppCompatDialog actually uses full Material theming below Lollipop, either.

@alorma

**Comment by alorma** [comment]
http://android-developers.blogspot.com.es/2015/04/android-support-library-221.html?m=1

As i read there, all widgets are now converted to AppCompat, and also with dialogs.

Maybe this lib can make BaseDialog uses AppCompatDialog to expand functionalities.

**Comment by afollestad** [comment]
It does that at inflation time, yeah. But there wouldn't be any benefits since this library already does the tinting that AppCompat would do.

AlertDialog was recently removed from MaterialDialog's base, too.

**Comment by afollestad** [comment]
One of the guys who contributes told me there is however new dialog themes that will make dialogs look good overall on older API levels (animations and shadows).
