### ISSUE TITLE
Full Screen Dialog Theme

### ISSUE THREAD

**Issue by logicalstep** [afollestad/material-dialogs#471]
How do we create full screen dialogs? I want to cover the top and keep hidden the bottom Nav bars.

In AlertDialog.Builder I can use the below to get it to happen:

 builder2 = new AlertDialog.Builder(this, android.R.style.Theme_Holo_Light_NoActionBar_Fullscreen); //full screen dialog

I tried a few combination of the above in your builder, but none work.

Thanks in advance.

**Comment by afollestad** [comment]
There's currently no plans for full screen dialogs. You also shouldn't use Holo themes for anything anymore, AppCompat should be used instead.

It is however very easy to create full-screen dialogs as seen in the design guidelines with just an Activity whose Toolbar has an 'X' icon for home up navigation. 

http://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs

**Comment by logicalstep** [comment]
So you're saying I should use an activity?
AlertBuilder looks simpler to me, especially when the information is just text and a dismiss button but I understand the flexibility of using an activity.
Seems like a lot more complexity, resources and overhead to me??

**Comment by afollestad** [comment]
Well, an Activity may actually use less resources. Material Dialogs has
quite a lot of variables that are declared during the life cycle of a
dialog.

An Activity is simpler, once you get it setup.

**Comment by capcoman** [comment]
This works for me:

dialog.dialogBehavior.setBackgroundColor(
                loader!!.view,
                Color.TRANSPARENT,
                0f
            )
