### ISSUE TITLE
Android studio didn't find

### ISSUE THREAD

**Issue by yy1300326388** [afollestad/material-dialogs#472]
I use the Android studio add support, the result can't find my add is```com.afollestad:material-dialogs:0.6.3.1```

**Comment by davidschreiber** [comment]
It seems this version is not hosted anymore. Also, the version from the README.md is not available via Central Maven. Here is a list of hosted library versions: http://repo.spring.io/libs-release-remote/com/afollestad/material-dialogs/

This worked for me:

     compile 'com.afollestad:material-dialogs:0.6.5.2'

**Comment by davidschreiber** [comment]
Okay, version `0.6.5.2` is empty at all. I now use 

    compile 'com.afollestad:material-dialogs:0.6.4.7'

which seems to work.

**Comment by cheenu** [comment]
Quick question - where to add this line 

`maven { url 'https://dl.bintray.com/drummer-aidan/maven' }` ?

If I add it here 

`allprojects {
    repositories {
        maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
        jcenter()
    }
}`

then I get errors stating it failed to find the Android Support library dependencies.

**Comment by afollestad** [comment]
In your individual app module

**Comment by afollestad** [comment]
@cheenu the library is back on jCenter now

**Comment by cheenu** [comment]
Thanks!

**Comment by yy1300326388** [comment]
@davidschreiber  Thanks!
