### ISSUE TITLE
Add support for global typefaces

### ISSUE THREAD

**Issue by squeeish** [afollestad/material-dialogs#474]
I've to set my typeface for every dialog that I show. It will be nice to have support for global typefaces in addition to the existing colour ones!

**Comment by afollestad** [comment]
Unfortunately, there's no good way to do this. I actually tried, but when an app enables Proguard, it appears string attributes (e.g. the name of a font file) get obfuscated and the string isn't readable.

**Comment by afollestad** [comment]
Maybe there's another reason why it happens, but I'm looking into it more.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.0

**Comment by squeeish** [comment]
Great update. Thank you!

**Comment by svenjacobs** [comment]
`disableDefaultFonts()` was removed in commit cffd86e. It would be nice if a minor version update of this library don't break compilation. In the future please mark such methods as deprecated, maybe doing nothing anymore, and give users of this library the chance to remove usages gracefully. Deprecated methods could then be removed in the next version after this one. Thank you!

**Comment by svenjacobs** [comment]
Also it would be nice if the README mentions how to set the font via theming. It only states

> There's a global theming attribute available to automatically apply fonts to every Material Dialog in your app, also.

By looking at the diff I found out that the attribute names are `md_medium_font` and `md_regular_font`.

**Comment by afollestad** [comment]
It shouldn't be expected that changes like that will be made when the
library isn't at version 1.0. Leaving it would be completely useless, since
the Roboto fonts were unbundled and that method wouldn't do anything
anymore.

There's a global theming attributes section that lists all of the attribute
names.

**Comment by svenjacobs** [comment]
> Leaving it would be completely useless, since the Roboto fonts were unbundled and that method wouldn't do anything anymore.

That's right. It wouldn't do anything anymore. But it would be marked `@deprecated` and users could remove usages to it before it gets removed in the next version.
