### ISSUE TITLE
vector drawables

### ISSUE THREAD

**Issue by tonyp** [afollestad/material-dialogs#476]
When trying out your amazing library I noticed that icon() won't seamlessly accept vector drawables (Android 5.0+).

Easy workaround:

    .icon(getResources().getDrawable(R.drawable.my_vector_drawing)))

That works totally fine, I just wondered if the library couldn't accept drawables here, too - and automatically handle `recycle()` when the dialog gets dismissed.

**Comment by afollestad** [comment]
Well, that code is identical to what the actual logic for `icon(int)` is. The only difference is that `ResourcesCompat` is used since `getResources().getDrawable(int)` is deprecated.

So there shouldn't be no issues with `icon(int)` accepting vector drawables.

**Comment by afollestad** [comment]
Also, recycle? You only recycle bitmaps, you don't recycle drawables. Garbage collection does that.

**Comment by afollestad** [comment]
To be more specific about `icon(int)`: https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L577

**Comment by tonyp** [comment]
Thanks for the quick answer.
The compiler complains when trying to use `.icon()` with `R.drawable.vectorDrawable` as this represents a Builder rather than int object.

Regarding recycle: I had in mind you can recycle drawables when there's absolutely no need for them anymore to keep the application heap low. This might only apply to Bitmaps, though.

**Comment by afollestad** [comment]
Oh I see. Not sure why that'd happen, but I can guarantee that the warning can be ignored.

But yeah, you can't manually recycle drawables :)

**Comment by tonyp** [comment]
Oh wait, now I finally got it. You linked to `.iconRes()` rather than `.icon()`, which does exactly what I wanted.

I used `icon()` as that's the one you mentioned here for displaying an icon:
https://github.com/afollestad/material-dialogs#displaying-an-icon
