### ISSUE TITLE
Add support for multiple input boxes

### ISSUE THREAD

**Issue by KTachibanaM** [afollestad/material-dialogs#477]

**Comment by afollestad** [comment]
You should use a custom view.

**Comment by KTachibanaM** [comment]
Wrote a simple custom Builder that wraps a custom view with a vertical array of text inputs, in case anyone sees and needs it :)

https://gist.github.com/KTachibanaM/9e274670c8dbb7d19d8a

**Comment by carlastabile** [comment]
Thanks @KTachibanaM, I actually used part of your code and modified it according to my needs. Pretty useful and simple!

**Comment by vajiralasantha** [comment]
Hi  @KTachibanaM, are you able to tell me how to use your class correctly? I used following code for testing. It shows two text fields but wont show any OK or Cancel buttons. Can you please tell me what am I missing?

My code:
```
 new MultiInputMaterialDialogBuilder(this)
                .addInput(0,0)
                .addInput(0,0)
                .inputs(new MultiInputMaterialDialogBuilder.InputsCallback() {
                    @Override
                    public void onInputs(MaterialDialog dialog, List<CharSequence> inputs, boolean allInputsValidated) {
                        text.setText(inputs.get(0));
                    }
                })
                .title("some title")
                .build().show();
```

Thanks.

**Comment by KTachibanaM** [comment]
@vajiralasantha You will still need to add buttons explicitly. See https://github.com/afollestad/material-dialogs#basic-dialog
