### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by caarmen** [afollestad/material-dialogs#478]
This is not an "issue", so sorry for polluting the issue list.

Just want to say thanks for a great library!  I was thinking of getting rid of this library in my project, now that appcompat introduced the AppCompatDialog.  But, appcompat doesn't support ProgressDialogs or preferences (EditTextPreference etc), whereas material-dialogs does.  So, I'm still using it :)

**Comment by afollestad** [comment]
Thank you :)
