### ISSUE TITLE
Restore older version(s) in jCenter

### ISSUE THREAD

**Issue by mendhak** [afollestad/material-dialogs#480]
I understand that jCenter accidentally removed your uploads.  Could you please restore a few older versions in your jCenter?  For example we're using 0.6.3.1, we can upgrade later but don't have the resources right now.

Thanks

**Comment by afollestad** [comment]
Sorry, no, I don't keep old versions around.

Pre 0.7 versions shouldn't be used any ways though.

**Comment by agrajaghh** [comment]
@afollestad even 0.7.2.1 is missing (which was still working with appcompat v21). Please don't delete old versions from jCenter

**Comment by ishufuri** [comment]
Same for me, CI warned me that most of my projects won't build anymore, and upgrading appcompat to 22 requires to fix the themes in all these projects, which would be quite a hassle. 
Please reupload and keep atleast the latest version which still depends on appcompat v21, so we have compatibilty here.

**Comment by ponz** [comment]
I suffered same problem with @ishufuri. (the appcompat/theme issue).
So I fixed(?) this problems by finding aar file of older version in gradle cache directory.

In my case.
Gradle service directory path / caches/modules-2/files-2.1/com.afollestad/material-dialogs/0.6.3.5
if there's any cached build machine, may the cached library can be found.

Then, create new module (importing aar) and add dependency.

**Comment by afollestad** [comment]
@ishufuri I didn't delete them, the entire library was removed from jCentee by accident.

You should be using the latest at all times though while the library is not yet at version 1.0.

**Comment by ishufuri** [comment]
@afollestad Well, that's bad news. In this case I'll have to update my stuff. Luckily it's just some bulk-editing of the style for most of the projects. 

For anyone else having the error: _AppCompat does not support the current theme features_
Removing the `android:windowActionBar` field in the style and setting the style parent to a `NoActionBar`-variant has helped getting the project running again.

**Comment by gang018** [comment]
@ponz Can you please provide an .aar file?

**Comment by afollestad** [comment]
I highly discourage using an old version like that. It's full of bugs and incompatibility issues with hundreds of devices and countless Android versions.

The current version is 0.8.5.0.

**Comment by afollestad** [comment]
And it's hosted on JitPack.io, not Bintray or that Maven service they partner with.
