### ISSUE TITLE
Implement possibility to set the selectAllOnFocus property of the input field on an Input Dialog

### ISSUE THREAD

**Issue by osiris86** [afollestad/material-dialogs#483]
Sometimes I want to already select the prefill so that the user can quickly overwrite the default value without the need to previously delete the prefill value.

**Comment by afollestad** [comment]
You can use `getInputEditText()` after you build the dialog and perform selection on that.

**Comment by osiris86** [comment]
That won`t work because in MaterialDialog#onShow you set the selection: 
```Java
input.setSelection(input.getText().length());
```
This overwrites everything I do previously...

**Comment by afollestad** [comment]
Oh yeah, you're right.

Well I just changed when it's done with this commit: https://github.com/afollestad/material-dialogs/commit/1795e4599800fb3fd079981280f046191e846819

Basically, the on show listener will be called after the selection is initially set, allowing you to select all when the on show listener is called.

**Comment by afollestad** [comment]
This should help https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.0
