### ISSUE TITLE
Problem with running :app:dexDebug for latest version 0.7.2.8

### ISSUE THREAD

**Issue by tommytcchan** [afollestad/material-dialogs#486]
I am using support-v4 and appcompat-v7 in my project, and I have this in my build.gradle:

```
    compile ('com.afollestad:material-dialogs:0.7.2.8') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
```

However it is giving me an error. 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.8.0_05/bin/java'' finished with non-zero exit value 2

Does anyone know this is happening?

**Comment by afollestad** [comment]
Well, I don't use v4 I use v13 of the support library.

You shouldn't need to exclude at all as long as you're using 22.1.1 of AppCompat and the Support Library in your own app.

**Comment by tommytcchan** [comment]
@afollestad it still gives me the same error if I don't exclude anything. I'm using the following in my build.gradle:

```
    compile 'com.android.support:support-v4:22.1.1@aar'
    compile 'com.android.support:appcompat-v7:22.1.1@aar'
```

any ideas?

**Comment by afollestad** [comment]
Sorry, I have no idea. I use this library in many production apps and I've never had any issues like that.

I'd try cleaning your project, if you have a lot of libraries referenced you may need to enable multi-dex.

**Comment by Kiwifed0r** [comment]
The problem is not related to this library. I had the same problem and multi-dex fixed it.
