### ISSUE TITLE
Input dialog – support for max length, and display current/max indicator

### ISSUE THREAD

**Issue by waltervr** [afollestad/material-dialogs#487]
Hi,
Very impressed with your work here, I'm looking for the ability to set maxLength for the text and/or tell the user how many characters left have to enter.

PD: I've used a custom UI to do that, but it would be much better to implement using your library.

Best Regards,
Walter

**Comment by afollestad** [comment]
I'm assuming you mean in the input dialog, good idea.

**Comment by waltervr** [comment]
Sorry for the confusion, but yeah, that's what I meant!

**Comment by afollestad** [comment]
Since stopping the user from typing altogether wasn't working too well (the user could still continue to type and suggestions on the keyboard would change, even though nothing actually went into the input field).

So, I made it so that the positive action button (which submits input) gets disabled if the user goes over the maximum length. I also made it so you pass an 'error color' in which is used on the current/max indicator and the color of the input field itself when the user goes over the max (indigo is used here but you could use red or any other color).

![shamulmy47iafollestad04282015123735](https://cloud.githubusercontent.com/assets/1820165/7376186/9edbe712-eda3-11e4-96fc-7691262162ec.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.0

**Comment by waltervr** [comment]
Hey there, I got couple of things:
1. When loading the dialog the first time, it doesn't calculate the available text using the prefill, just calculates according to the maxLength selected.
2. After the max length was reached, I got the disabled submit button, however when I deleted some characters to fit, the button was not enabled.

I'm attaching 2 screenshots for each issue. 
Regards
![inputcount](https://cloud.githubusercontent.com/assets/1737635/7383499/acf8caec-eddd-11e4-926b-ce35cc9ff8fb.png)
![submitdisabled](https://cloud.githubusercontent.com/assets/1737635/7383500/ad3af3e0-eddd-11e4-93dd-b6351367f2e7.png)

**Comment by plusCubed** [comment]
@afollestad I... don't think this should be included in material dialogs. There are material edit text libraries out there that provide this functionality while following the guidelines closely. People who want this functionality can just use those libraries.

**Comment by plusCubed** [comment]
Specifically this one: https://github.com/rengwuxian/MaterialEditText
I guess what I'm trying to say is this is a feature of the edittext, not of the dialog.

**Comment by afollestad** [comment]
@plusCubed well, the code is relatively simplistic in Material Dialogs. It doesn't add too much bulk and it's a common thing used in a lot input dialogs.

**Comment by afollestad** [comment]
I fixed the first point in that comment, but I'm unable to reproduce the second one.

@waltervr

**Comment by waltervr** [comment]
@plusCubed you are right, however I would say that if I can avoid using multiple libraries I would do that, using a library just for the EditText doesn't seem to me a good approach.
Regards

**Comment by plusCubed** [comment]
@afollestad @waltervr I understand. The counter doesn't match the design guidelines though, regardless. I'll fix it right now.

**Comment by afollestad** [comment]
Oh yeah, I didn't notice there were guidelines for that until now

http://www.google.com/design/spec/components/text-fields.html#text-fields-character-counter

**Comment by plusCubed** [comment]
Done. Also added the default to be the red color specified here: http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors.

**Comment by waltervr** [comment]
@afollestad, in the second one, I did went over the maxLength until got the red colored input and then started erasing.

**Comment by afollestad** [comment]
Yeah, that works fine for me

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.1

**Comment by waltervr** [comment]
@afollestad I found the reason why it was not working for me, I did not added the .positiveText() property when creating my dialog. After I did that, finally everything worked as expected. I looked into your instructions here:
https://github.com/afollestad/material-dialogs#input-dialogs but didn't find any reference of that small detail. Do you think that's really necessary? or is it just a rare coincidence?

**Comment by waltervr** [comment]
@afollestad Seems like the latest update .4.2 removed the feature of counting the prefill text as part of the total text to be entered? 
Screen capture here: https://goo.gl/8Xf84Y

**Comment by afollestad** [comment]
@waltervr that isn't quite what the issue there is; it is counting the prefill, that's why the counter shows the correct length. The input is just disabled by default when it shouldn't be. Looking into it.

**Comment by afollestad** [comment]
Fixed in https://github.com/afollestad/material-dialogs/commit/490df6e9e79d18ef924feb9cdbf11fec4d7ebf20.

An update won't go out until https://github.com/afollestad/material-dialogs/issues/534 is resolved though.
