### ISSUE TITLE
InputType not working

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#492]
The inputType does not seem to do anything.

```java
new MaterialDialog.Builder(getActivity())
    .title(R.string.bookmark_edit_title)
    .inputType(InputType.TYPE_TEXT_FLAG_CAP_SENTENCES)
    .input("hint", "prefill", false, new MaterialDialog.InputCallback() {
        @Override
        public void onInput(MaterialDialog materialDialog, CharSequence charSequence) {

        }
    })
    .positiveText(R.string.dialog_confirm)
    .show();
```

It does not matter if it is this, or                 `.inputType(InputType.TYPE_TEXT_FLAG_CAP_SENTENCES | InputType.TYPE_TEXT_FLAG_AUTO_COMPLETE | InputType.TYPE_TEXT_FLAG_AUTO_CORRECT)` or whatever, I just always get a don't do anything edittext.

Using:
```Gradle
compile 'com.afollestad:material-dialogs:0.7.2.8'
```

**Comment by afollestad** [comment]
Well first of all, cleaned up your comment a bit to use Java and Gradle syntax highlighting (indentation doesn't do that).

**Comment by afollestad** [comment]
See the input dialog in the sample project, just switch our password for cap sentences.

**Comment by afollestad** [comment]
I should note what you pass in is passed directly to the EditText, this is related to the Android framework itself, not this library.

**Comment by afollestad** [comment]
Actually, you don't even need to look at the sample project, it's already in the README:

https://github.com/afollestad/material-dialogs#input-dialogs

**Comment by Ph1b** [comment]
Was there something wrong how I used it?

For me it is just not working, like I wrote.

When using                                       

` InputType.TYPE_TEXT_FLAG_CAP_SENTENCES | InputType.TYPE_TEXT_FLAG_AUTO_CORRECT

on a normal EditText, above my keyboard (google keyboard) appears a suggestion of words. When I do it like done above, no suggestions are displayed. Even tough cap sentences works.

**Comment by afollestad** [comment]
When you pass in the inputType from a layout, Android automatically handles flags like this. Setting the `inputType` programmatically is a bit different than how it works in XML.

You need the first flag that's shown in the README and sample project. 

But again, `inputType()` in this library is a shortcut to `EditText.setInputType()`. This library doesn't do anything else with it.

**Comment by afollestad** [comment]
E.g. ```java
InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_CAP_WORDS
```

**Comment by Ph1b** [comment]
Oh sorry. Could not find anything in the documentation that you have to set TYPE_CLASS_TEXT first, where you dont have to set it in xml. Thanks for making that clear to me.

**Comment by afollestad** [comment]
It's displayed in the input dialog example in the README :)

![screen shot 2015-04-29 at 1 02 05 pm](https://cloud.githubusercontent.com/assets/1820165/7397738/0e6f2e00-ee70-11e4-9996-9a780c88aba4.png)

But you're welcome. I guess it's not too obvious that you have to do that, but I'm assuming people know what's necessary since that's an Android mechanism.

**Comment by AllanWang** [comment]
Old thread, but if you'd like, an `.inputAutoCorrect()` option that will add `TYPE_CLASS_TEXT` and `TYPE_TEXT_FLAG_AUTO_CORRECT` seems to be a nice option. It's true that we should know to add the `TYPE_CLASS_TEXT` flag but it isn't very apparent in the javadocs when we know that auto correct doesn't happen without the auto correct flag.
