### ISSUE TITLE
EditText with limit, entering space doesn't count until a letter is entered afterwards

### ISSUE THREAD

**Issue by msutherland4807** [afollestad/material-dialogs#493]
As in title. e.g. I have a dialog with limit 30, if the 30th character is a letter, I can put a space after, in 31, and Save still enabled

**Comment by afollestad** [comment]
I don't have any issues with the submit button being enabled when it shouldn't be.

Not counting trailing spaces is intended behavior. However since it's unintuitive I'll remove it.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/commit/bae5347c72a1679169a96388ace74b61bbfd7b14

**Comment by msutherland4807** [comment]
Fair enough. I just added a `trim()` to my callback as workaround

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.2
