### ISSUE TITLE
Building A Dialog with ViewPager

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#494]
Hello,

  I'm fighting to build a material-dialog with an inside ViewPager. Do you see any issue to do that or do you have any example ?

**Comment by afollestad** [comment]
You're putting a view pager in a dialog? You shouldn't do that

**Comment by afaucogney** [comment]
Hello,

 Yes this was my intention. Why not ?
We can do that with traditional Dialog, as for example http://stackoverflow.com/questions/13334733/viewpager-fragmentpageradapter-inside-a-dialogfragment-gets-illegalargumentex

**Comment by afollestad** [comment]
Because a Dialog window doesn't have a fragment manager. Fragment managers are in an Activity which has a window separate from the dialog. 

If you really needed to you can do a fragment transaction on a custom view for this library, but you shouldn't.

**Comment by sirvon** [comment]
@afaucogney did you ever get a viewpager in the dialog to fully work?

**Comment by ljcleyba** [comment]
So what was the conclusion on this problem? I am encountering this as well.
