### ISSUE TITLE
Samsung Galaxy S4 with Android 5.0.1

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/material-dialogs#495]
This is how a dialog looks like in a S4 with 5.0.1 but with 4.4.2 it looks ok.
Please resolve this problem.
![11178468_908398322539356_368046319_n](https://cloud.githubusercontent.com/assets/10342283/7438310/bff37018-f06a-11e4-91cf-f516d6a3daab.jpg)

**Comment by afollestad** [comment]
This isn't an issue with this library

**Comment by afollestad** [comment]
You most likely have fitsSystemWindows on globally in styles.XML or something
