### ISSUE TITLE
switch progress dialog between indeterminate

### ISSUE THREAD

**Issue by AlexMercier** [afollestad/material-dialogs#496]
Hello.
How i can change indeterminated progress dialog to not indeterminate?
for example: i start download file, but before it i need get some info about file like size and etc...
i want create progress dialog, set it to indeterminate mode, get file info, set indeterminated to false, update  max file size to setMaxProgress(..) and start download.

now i use 2 dialogs:
1 create progress-indeterminated dialog.
2 get info
3 dismis first dialog
4 create second not indeterminated progress  dialog

but it would be easier if you could make some method for this,  like setIndeterminate(false);
Thanks.

**Comment by afollestad** [comment]
You can't once the dialog is shown, the layout is determined when it's first built.
