### ISSUE TITLE
Validation of input

### ISSUE THREAD

**Issue by WojciechKo** [afollestad/material-dialogs#501]
Is there any way to validate input and until it's not valid, disable OK button?

**Comment by afollestad** [comment]
To keep the library simple, no.

But you can do that by calling `alwaysCallInputCallback()`, which will cause the input callback to be invoked whenever the user changes their input (without pressing submit). 

You can manually enable or disable the positive action based on whether you determine the input is valid or not from the input callback.

**Comment by WojciechKo** [comment]
That was fast :)
Thanks for reply, it works like a charm
