### ISSUE TITLE
Dialog Close whenever i tab outside

### ISSUE THREAD

**Issue by samsoft00** [afollestad/material-dialogs#507]
Great library, Please i need help. whenever i tab outside the dialog, it will close the dialog... how can i disable this? i want to close when use click Cancel OR Okay

**Comment by afollestad** [comment]
This isn't an issue with this library, you need `setCancelable(boolean)` (http://developer.android.com/reference/android/app/Dialog.html#setCancelable(boolean)). There's a convenience method in the the `Builder` too (`cancelable(boolean)`).
