### ISSUE TITLE
Issue with simpleListItems

### ISSUE THREAD

**Issue by DaCardinal** [afollestad/material-dialogs#508]
I've set my title color and item color to two different colors but when I run my app both are the same. The title color is the showing on both. Using build '0.7.3.2'. I experienced this while using the simpleItemList(). As per my code you can see I've set the colors of the itemColorRes() to white but it's taking the color of the titleColorRes(). I tried using just a Basic Dialog and that worked okay. I've attached that image too.
@afollestad Could you take a look at this? 
 
![screen shot 2015-05-07 at 3 27 29 pm](https://cloud.githubusercontent.com/assets/6160366/7524072/9a000332-f4cd-11e4-8a7d-7683ec45ac2d.png)

![screen shot 2015-05-07 at 3 24 17 pm](https://cloud.githubusercontent.com/assets/6160366/7524031/622d663e-f4cd-11e4-9d8a-9ee1ca00f619.png)
![screen shot 2015-05-07 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/6160366/7524032/623eb07e-f4cd-11e4-8c14-8bfdf2a949f1.png)

**Comment by DaCardinal** [comment]
@afollestad just tried the same thing in one of your latest sample got the same result. Is there a work around this? I want the title color to be different from the list items. Here is a screenshot using your latest MaterialDialog sample. 

![screen shot 2015-05-07 at 3 43 31 pm](https://cloud.githubusercontent.com/assets/6160366/7524508/85d2fcb8-f4d0-11e4-8924-302b5cda9adb.png)

**Comment by afollestad** [comment]
Oh so the title color overrides the list item color?

**Comment by afollestad** [comment]
Looking into it now, thank you

**Comment by afollestad** [comment]
This was an issue with `MaterialSimpleListAdapter`

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.3
