### ISSUE TITLE
EditText in the MaterialEditTextPreference not tinted.

### ISSUE THREAD

**Issue by Xyaren** [afollestad/material-dialogs#509]
![image](https://cloud.githubusercontent.com/assets/5864045/7536422/a4baa394-f587-11e4-84e0-ab6a4334b581.png)

![image](https://cloud.githubusercontent.com/assets/5864045/7536457/ea24b23a-f587-11e4-82f2-157a5f6eb9b0.png)

Tested with 0.7.3.1 & 0.7.3.3

I Think it is since the usage of AppComaptActivity instead of ActionBarActivity

**Comment by afollestad** [comment]
Tinted from what? It pulls the color from the `colorAccent` (AppCompat) attribute.

**Comment by afollestad** [comment]
I made it pull from `android.R.attr.colorAccent` rather than only `R.attr.colorAccent` now too (on Lollipop). There's no stock XML attribute for setting accent colors, so this class does not allow customization. You need to specify the color in your Activity Material/AppCompat theme.

If you want more customization, you can use a regular input dialog and manually save the value.

**Comment by Xyaren** [comment]
Does this mean the EditText will still use the Holo style ? 
There is no way to use a material style EditText ?

My accent color (R.attr.colorAccent) is set correctly. 
![image](https://cloud.githubusercontent.com/assets/5864045/7546385/1396cc78-f5d5-11e4-9fb9-9256ccbdd18a.png)

It worked a few weeks ago.

**Comment by afollestad** [comment]
Oh, you're talking about the handle, not the EditText itself

**Comment by afollestad** [comment]
I realized R.attr.colorAccent was also getting overridden by android.R.attr.colorAccent on Lollipop, I fixed that too.

Not sure why the handle is white though.

**Comment by Xyaren** [comment]
The handle is just a small bug i dont really care of.
The screenshot in't from lollipop though...
The screenshots are from JellyBean (4.4.4) and is showing a holo styled EditText (blue underline). The first screenshot is from your example app , showing that it isn't an error within my own project.

**Comment by afollestad** [comment]
For now, you'll need to add `android:colorAccent` to your v21 Activity theme. `colorAccent` (AppCompat) is being overwritten, it's fixed but the next release won't be available quite yet.

**Comment by afollestad** [comment]
For the handle, you must be missing an attribute in your theme, or an attribute is set to white. I think it might use `android:textColorHighlight`.

**Comment by Xyaren** [comment]
I'm not using v21. Screenshots are made with my HTC running on API v19

**Comment by afollestad** [comment]
Hmm, well this is running on stock Lollipop with a API 19 emulator.

It might be an HTC issue.

![screen shot 2015-05-08 at 7 01 54 pm](https://cloud.githubusercontent.com/assets/1820165/7547528/c1e449de-f5b4-11e4-9309-7286746df9a6.png)

**Comment by afollestad** [comment]
Oops, I meant stock Android with an API 19 emulator

**Comment by Xyaren** [comment]
Any other EditText in my normal layout files, used in Fragments and AppCompActivites are working and having the material style with correct tinting.

**Comment by plusCubed** [comment]
@afollestad @Xyaren I think I know the issue with the lollipop styling. Fixing.

**Comment by plusCubed** [comment]
Fixed in 990933e269b599cd2b6a22c67d876de574ba88dc

**Comment by Xyaren** [comment]
provide me the updated sample apk and i'll test it on my HTC :)

**Comment by afollestad** [comment]
Thanks @plusCubed, I can confirmed it's fixed.

I won't have an APK until a library release goes out in a bit.

**Comment by Xyaren** [comment]
Sounds great ! Thank your very much! 
Awesome API!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.4

Thank you

**Comment by Xyaren** [comment]
Can confirm it's working too.
