### ISSUE TITLE
Possible future update : SimpleListItem()

### ISSUE THREAD

**Issue by DaCardinal** [afollestad/material-dialogs#511]
I'ev been playing around with the simpleListItem() and added a few things to it. I was able to add an image overlay to the images to the left of the items when clicked and also gave it the feature of selecting multiple list items or just one. I've a class already prepared but don't really know where it would go. Would be glad to share it. Heres an image demonstrating what i've done with the SimpleListItem()

![screen shot 2015-05-08 at 4 58 57 pm](https://cloud.githubusercontent.com/assets/6160366/7545552/f8410528-f5a3-11e4-8685-0a61354d2285.png)

**Comment by afollestad** [comment]
Simple list item isn't a concept I made, it's from the design guidelines:

http://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs

You mean something like this? (this is a color chooser from my app, Cabinet)

![cabinetgrid](https://cloud.githubusercontent.com/assets/1820165/7545892/6490cb88-f59e-11e4-8c92-13d46d26466b.png)

**Comment by DaCardinal** [comment]
Something like that but choosing multiple items. The one you have closes after the first input

**Comment by afollestad** [comment]
Well, you'd need to implement it on your own. That adapter is just a basic implementation that mimics the dialog from the guidelines. It's not meant to add extra features.

**Comment by afollestad** [comment]
If you want, I can provide the custom view I use in Cabinet (that draws the check mark and border).

**Comment by afollestad** [comment]
This is the `CircleView` implementation I use in Cabinet:

https://gist.github.com/afollestad/9161c6efcd75d676d242

You'd need to provide a drawable in place if `R.drawable.ic_check`.
