### ISSUE TITLE
Handle color for EditText is wrong in MaterialEditTextPreference

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#512]
![screen shot 2015-05-08 at 7 01 54 pm](https://cloud.githubusercontent.com/assets/1820165/7547532/dd897ef2-f5b4-11e4-9cbe-5bfd4668253b.png)

**Comment by plusCubed** [comment]
Should be fixed in 990933e269b599cd2b6a22c67d876de574ba88dc
