### ISSUE TITLE
Workaround framework memory leak

### ISSUE THREAD

**Issue by teslacoil** [afollestad/material-dialogs#513]
Square released LeakCanary today which is awesome https://github.com/square/leakcanary

One leak it reports is related to Handlers and Dialogs, which we should consider working around but maybe that's beyond the scope of this library.

https://github.com/square/leakcanary/blob/master/library/leakcanary-android/src/main/java/com/squareup/leakcanary/AndroidExcludedRefs.java#L126
      // Prior to ART, a thread waiting on a blocking queue will leak the last dequeued object
      // as a stack local reference.
      // So when a HandlerThread becomes idle, it keeps a local reference to the last message it
      // received. That message then gets recycled and can be used again.
      // As long as all messages are recycled after being used, this won't be a problem, because
      // there references are cleared when being recycled.
      // However, dialogs create template Message instances to be copied when a message needs to be
      // sent. These Message templates holds references to the dialog listeners, which most likely
      // leads to holding a reference onto the activity in some way. Dialogs never recycle their
      // template Message, assuming these Message instances will get GCed when the dialog is GCed.
      // The combination of these two things creates a high potential for memory leaks as soon
      // as you use dialogs. These memory leaks might be temporary, but some handler threads sleep
      // for a long time.

      // Hack: to fix this, you could post empty messages to the idle handler threads from time to
      // time. This won't be easy because you cannot access all handler threads, but a library
      // that is widely used should consider doing this for its own handler threads.

Their proposed fix helps, but since in most apps using material-dialogs, all dialogs will be through us, we might be able to use reflection to get the cancel/dismiss/show messages and scrub the obj ourselves.

I'm not sure if it's a good idea or not, as using reflection is always hacky and it might break something or cause weird bugs. There's also not a great time to do it, some dialogs are reused, so doing it onDismiss is too eager. Adding a finalizer is not ideal. We could do it onDismiss and reinstate them in show(), but it might need a bit of testing to get right.

**Comment by afollestad** [comment]
Saw that library, it looks very nice.

The easiest solution would be to just remove the use of Handlers, it would only affect thread safety of some of the modifier methods but that only came with a recent update.

**Comment by teslacoil** [comment]
bee2ae6 does not work around the issue.

The issue comes from the framework's Dialog.java mCancelMessage, mDismissMessage and mShowMessage not being properly cleaned before being recycled, so they hold a reference and the Message ends up held by a background HandlerThread anywhere else in the project. Such threads could sleep a long time and hold a reference to the dialog the whole time.

From app developer's point of view, they can try to work around it by posting idle messages to their HandlerThreads. From libraries that use HandlerThreads, they should try the same.

Material-dialogs is a unique case in that it's actually handling dialogs. But it means we might be able to clean those Messages before they're recycled.

**Comment by afollestad** [comment]
Ohhh, okay, I see

**Comment by afollestad** [comment]
I can take care of this, I think I have a good solution

**Comment by afollestad** [comment]
@teslacoil do you think this'll do it? https://github.com/afollestad/material-dialogs/commit/5a30e76574a44c3706bf75d42ce5de9ee56673ce

**Comment by afollestad** [comment]
One more https://github.com/afollestad/material-dialogs/commit/f7d09c4ae1aa11ae4745e115205be43f5fef5b13

**Comment by teslacoil** [comment]
I'm not sure what the behavior would be if a dialog is reshown (I don't
think it's common, but I think it's allowed) after dismissing once. Also
can use Dialog.class directly rather than getSuperClass and should only do
this on <= 21 as it's been fixed in the framework.

I'd like to dig a bit deeper to understand how the messages are improperly
recycled and figure out the best way to test the fix (as it won't happen
everytime), but won't have a chance to do that for a while.

**Comment by afollestad** [comment]
I looked into `Dialog`'s source code and the messages are created with the callback setters (e.g. setOnDismissListener). Thus I set all the listeners if necessary (since the ones that user specify are still stored in the `Builder` object) when the dialog is shown, every time.

**Comment by afollestad** [comment]
I looked into Dialog's source code and the messages are created with the callback setters (e.g. setOnDismissListener). Thus I set all the listeners if necessary (since the ones that user specify are still stored in the Builder object) when the dialog is shown, every time. That way the Messages are recreated every time the dialog is shown, and destroyed everytime the dialog is stopped/dismissed.

**Comment by afollestad** [comment]
I think a small issue came from the current code, dialog fragments must hook into the listeners or something. A user reported a Dialog Fragment re-opens its dialog after orientation change now, even after the user manually dismissed it.

**Comment by deinlandel** [comment]
I can confirm the reappearing of a dialog after orientation change (although I thought it was a DialogFragment bug). To work around this, I had to call `DialogFragment.dismiss();` method in every dialog's button callback, and also override DialogFragment's method like this:
```java
    /**
     * You have to dismiss through fragment method, and you have to do it manually EVERYWHERE!
     * "onDismiss" callbacks are NOT working for some reason.
     */
    @Override
    public void onCancel(DialogInterface dialog) {
        dismiss();
        onDismiss(dialog);
    }
```

**Comment by Gybra** [comment]
After opening a dialog and then dismissing it, MaterialDialog does not remove che listeners as you can see from this hprof screenshot

<img width="619" alt="screen shot 2015-08-02 at 18 09 22" src="https://cloud.githubusercontent.com/assets/1799993/9026928/a7f452be-3941-11e5-9046-9db4d5a66341.png">

**Comment by afollestad** [comment]
@Gybra removing the listeners is not a solution; it prevents the dialog from being able to be shown again after dismissal.

**Comment by Gybra** [comment]
So how can i free that resources? It keeps a strong reference on memory and it is not garbage collected. I already tried by simulating the GC event from Android Studio

**Comment by Ph1b** [comment]
Is [this](https://gist.github.com/Ph1b/896b51de4a9f5fc1dcf0) the same leak?
![screenshot_2015-08-04-22-49-45](https://cloud.githubusercontent.com/assets/743462/9072387/25ea70e4-3afb-11e5-9fb2-703bc78b2a46.png)

**Comment by afollestad** [comment]
@Ph1b yep, the dialog listener messages aren't released. Not from `MaterialDialog`, but `android.app.Dialog`. It's a known Android framework issue.

I tried methods of clearing these `Message` objects using refactoring, but there's no good time to do so and it caused a lot of weird issues.

**Comment by hzsweers** [comment]
Could the examples here help? https://corner.squareup.com/2015/08/a-small-leak.html

**Comment by afollestad** [comment]
@hzsweers that's useful info, but unfortunately this leak is deep within the Android framework itself. Dialogs don't destroy the Message objects used for various listeners, manually clearing them prevents dialogs from being re-used.

**Comment by afollestad** [comment]
A major case in which a dialog is re-used is `DialogFragments`. The fragments save and restore instance states, removing the listeners would destroy the ability for that to work.

Not sure if there's any good solution for this, or if it's truly needed.

**Comment by hzsweers** [comment]
Users should be mindful of this in their dialogfragment implementations
IMO. We do for ours, and are very careful not to leak things.

**Comment by afollestad** [comment]
Which is why the `android.app.Dialog` Messages cannot be nullified by this library.
