### ISSUE TITLE
Single Choice List Dialogs on API >= 21 is not animating

### ISSUE THREAD

**Issue by ponnex** [afollestad/material-dialogs#514]
When using Single Choice List Dialogs, the last Item of the radio button on API >= 21 is not animating :D

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.4.0

**Comment by ponnex** [comment]
yaaaaaaaaaaaaaay! :D thanks for thiiiis! hehe

**Comment by AkshayPathak** [comment]
There is a weird color issue occurring on the last radio button after the update. It does not seem to change the exterior circle color like the rest of them. Your sample project also has this issue.

**Comment by afollestad** [comment]
@AkshayPathak no issues with that on my end

**Comment by AkshayPathak** [comment]
I don't think you understood what I was trying to say. Let me elaborate: when you click the single choice button on your sample application, the selected option is Instagram. When you click Twitter and then back to Instagram, the exterior circle stays green. The same happens with Google Plus. When you click Facebook and then Instagram, the color of the exterior circle stays grey. Is this intended? Thanks for your help.

**Comment by afollestad** [comment]
I understand what you mean, but again I can't reproduce that.

This issue here is specifically for API 21 and above. Are you using an API level below Lollipop?

**Comment by AkshayPathak** [comment]
Oh I see. The problem is on my end. Thanks so much though!

**Comment by afollestad** [comment]
@AkshayPathak I just double checked below Lollipop (in a KitKat emulator) and I have no issues there either.

Make sure you're using the latest version of the library.

**Comment by AkshayPathak** [comment]
Ok thanks so much!
