### ISSUE TITLE
Can I set custom corner radius value?

### ISSUE THREAD

**Issue by MewX** [afollestad/material-dialogs#515]
I found default theme(dark) dialog had a 90 degree corner radius.
Can I set custom corner radius "dp" value?

**Comment by afollestad** [comment]
Not without modifying the themes in styles.XML of the library.

**Comment by plusCubed** [comment]
Hmm.... the 90 degree angle seems to happen because setting a background color overrides the default rounded background in the AppCompat styles. Fixing.

**Comment by plusCubed** [comment]
Fixed.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.4.0
