### ISSUE TITLE
Dialogs reappear on Orientation Change

### ISSUE THREAD

**Issue by RubenGees** [afollestad/material-dialogs#517]
With the new Version 0.7.4.0 Dialogs in DIalogFragments reappear on OrientationChanges. It doesn't happen on Version 0.7.3.4.

**Comment by afollestad** [comment]
That's the main purpose of using a dialog fragment. That's expected and intended Android framework behavior.

**Comment by RubenGees** [comment]
Okay, thank you. How can I prevent the DIalog from reopening if it was explicit closed by the user?
This is a Dialog I use in my App: https://github.com/RubenGees/Vocabletrainer/blob/master/app/src/main/java/com/rubengees/vocables/dialog/EvaluationDialog.java

**Comment by afollestad** [comment]
Oh, it re-opens? I might have an idea of why.

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.4.1
