### ISSUE TITLE
Multi-Line in input Dialog

### ISSUE THREAD

**Issue by ialex90** [afollestad/material-dialogs#519]
Hi,

I am trying to implement a input dialog and all works perfect but I need have a multi-line input, is possible it? I tried this:
                            .inputType(InputType.TYPE_TEXT_FLAG_MULTI_LINE)
                            .inputType(InputType.TYPE_TEXT_FLAG_IME_MULTI_LINE)

but doesn't work, I know I can customize a layout and inject it but I wonder if with this code is possible...

MaterialDialog dialog = new MaterialDialog.Builder(this)
                            .title("New Comment")
                            .backgroundColor(Color.WHITE)
                            .titleColor(Color.parseColor(color))
                            .contentColorRes(R.color.colorPrimaryDialogText)
                            .positiveColor(Color.parseColor(color))
                            .widgetColorRes(android.R.color.transparent)
                            .inputMaxLength(127)
                            .positiveText(R.string.submit)
                            .input(R.string.new_comment_hint, 0, false, new MaterialDialog.InputCallback() {
                                @Override
                                public void onInput(MaterialDialog dialog, CharSequence newComment) {
                                }
                            })
                            .inputType(InputType.TYPE_TEXT_FLAG_MULTI_LINE)
                            .build();
                            
                            dialog.show();

**Comment by afollestad** [comment]
There's another issue similar to this, maybe identical, but you need another flag in there. This isn't an issue with this library, you should look into programmatically setting edit text input types on StackOverflow.

**Comment by hawklike** [comment]
The solved issue here: #451
