### ISSUE TITLE
Cannot resolve method dismiss() in Background Task

### ISSUE THREAD

**Issue by jmztaylor** [afollestad/material-dialogs#521]
Maybe I am just overlooking something or just completely insane right now.  But I am getting this message when I set it up this way.    

    public class BackgroundTask extends AsyncTask<Void, Void, Void> {
            private MaterialDialog.Builder dialog;

        public BackgroundTask(MainActivity activity) {
            dialog = new MaterialDialog.Builder(activity);
            dialog.content("Doing something, please wait.");
        }

        @Override
        protected void onPreExecute() {
            dialog.show();
        }

        @Override
        protected void onPostExecute(Void result) {
            dialog.dismiss();
        }

        @Override
        protected Void doInBackground(Void... params) {
            // Do something long here
        }
    }

Now if I do it like this, dismiss() exists.

        new MaterialDialog.Builder(activity)
                 .content("Doing something, please wait.")
                 .show()
                 .dismiss();

**Comment by afollestad** [comment]
`dismiss()` is a method of `android.app.Dialog`, not `com.afollestad.materialdialogs.MaterialDialog#Builder`.

In other words, you call dismiss on the Dialog created by the `Builder` with `build()`, not the `Builder` itself.

**Comment by afollestad** [comment]
`dialog.show()` also returns the `MaterialDialog` instance.

```java
MaterialDialog.Builder builder = // ...

// Option one

MaterialDialog dialog = builder.build();
dialog.show();

// Option two

MaterialDialog dialog = builder.show();
```

**Comment by afollestad** [comment]
By the way, I edited your original comment to include Java syntax highlighting. Indentation doesn't do that.

**Comment by jmztaylor** [comment]
Yup.  Makes sense.  Thank you very much
