### ISSUE TITLE
Is it possible to customise the dialog width or add this feature to the lib?

### ISSUE THREAD

**Issue by 2BAB** [afollestad/material-dialogs#523]
As the [Material Design Spec](http://www.google.com/design/spec/components/dialogs.html#) shown, dialogs have two sizes of horizontal-margin (24dp or 48dp). This lib only provides 24dp by default, but I think 48dp is also a useful choice in some conditions. I have tried ``dialog.getWindow().setAttributes()`` to fix it, and I wonder whether it can be better.

Thanks.

**Comment by afollestad** [comment]
Duplicate.
