### ISSUE TITLE
MaterialDialogBuilder.input allowEmptyInput parameter does not work

### ISSUE THREAD

**Issue by vanniktech** [afollestad/material-dialogs#525]
Just check the sample application and you can see that I am able to press submit when the text field is empty and allowEmptyInput is set to false.

As far as I remember this started happening when the inputMaxLength function was added.

**Comment by afollestad** [comment]
Looks like someone else broke this with a pull request from a week or two ago, luckily it's a simple fix

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.4.1
