### ISSUE TITLE
Issue with input dialog allowEmpty

### ISSUE THREAD

**Issue by ialex90** [afollestad/material-dialogs#527]
Hi,

First, congratulations for this library, men.

My issue is with I want to show an input dialog and I want use maxLenght, until here, it's ok, there is a property to show the positive button disabled as default, ok, but if you write and erase all, the positive button should be disable (the same if you write more characters that allow with maxLength).

So, is there any way to get that if the user write and then, erase all, the positive button come back to disabled??

Thanks :)

**Comment by afollestad** [comment]
This was fixed in a previous release.

**Comment by ialex90** [comment]
Ok, Thanks, but I don't know where i can find the solution, in which release? Sorry, but I'm starting to use external libraries.

**Comment by afollestad** [comment]
The README file (the content you see on the main page of this repository) lists the current version.

**Comment by ialex90** [comment]
Thank you so much, the next time I will read that before to ask :+1:

**Comment by afollestad** [comment]
You're welcome ☺
