### ISSUE TITLE
Change text of positive button after validation

### ISSUE THREAD

**Issue by frmz** [afollestad/material-dialogs#529]
So let's say i have a custom view form that does some stuff that needs to connect to the internet (like searching values), so I'd like to have the positive button to show "search" initially and then, if search is successful shot "save". I did not find a way to do this.

What i could do is maybe use a neutral button for "search" and then use alwaysCallInputCallback() to enable the save once search is done but this is a bit less intuitive or use a button just below the search dialog created somehow.

I cannot trigger the search on text change because it takes too much, i even need to display a progress.

This project is awesome btw.

**Comment by afollestad** [comment]
The sample project's first custom view example shows how to manipulate the view. But there's some API stuff for this:

https://github.com/afollestad/material-dialogs#getting-and-setting-action-buttons

**Comment by frmz** [comment]
Sorry was RTFM, i just looked at the code, thanks.
