### ISSUE TITLE
Feature - Material Color Chooser Dialog

### ISSUE THREAD

**Issue by vanniktech** [afollestad/material-dialogs#530]
Is there something planned on a Material Color Chooser Dialog? That's the only [description](http://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider) that I've found.

![Material Color Chooser Dialog](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7dDFpcFo0V2JLS2c/components_sliders_continuous5.png)

**Comment by afollestad** [comment]
No, that's left out for simplicity. There's a basic color chooser in the sample project, but all implementations will require a custom view.
