### ISSUE TITLE
Icon of MaterialSimpleListItem disappear when scrolling.

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#531]
I made a dialog with a x0 items based on `MaterialSimpleListItem`.
Some item hold a icon, some not. When I scrolled the list, icons which are hidden because of the scrolling wont re appeared when scrolled back. The icon kept on the screen are ok.

Additionally the first item that should hold an icon doesn't. Every item that should hold icon + are hidden, do not!

Item instantiation is done the same way for every item:

```java
 adapter.add(
    new MaterialSimpleListItem.Builder(context)
    .content(topic.getMainTripName())
    .icon(context.getResources().getDrawable(R.drawable.medal_selected))
    .build());
```

**Comment by afollestad** [comment]
Well, using `context.getResources()` here is unnecessary. Just use `.icon(R.drawable.medal_selected)`.

But I'll look into this.

**Comment by afollestad** [comment]
I'm unable to reproduce any issues related to this.
