### ISSUE TITLE
Dialog with imageView

### ISSUE THREAD

**Issue by MuhamedFathy** [afollestad/material-dialogs#532]
Can i put `ImageView` in that dialog?

**Comment by afollestad** [comment]
Read the available documentation (in the README) or sample project.

**Comment by MuhamedFathy** [comment]
@afollestad I got it, but i need to add that image from `BitMap` because it's generated by the user, and your method only force me to assign a specified image!
Is there anyway?!

**Comment by afollestad** [comment]
No it doesn't, you can get a reference to the ImageView later. Again, the
documentation shows all of this.
