### ISSUE TITLE
How to remove padding in custom view and disable title?

### ISSUE THREAD

**Issue by azizimusa** [afollestad/material-dialogs#533]
as this code :

boolean wrapInScrollView = true;
new MaterialDialog.Builder(this)
        .customView(R.layout.custom_view, wrapInScrollView)
        .positiveText(R.string.positive)
        .show();

In my custom_view.xml, i have custom title using textedit, and also applied background color. The problem is, MaterialDialog creating padding on all side. So how do I remove the padding?

**Comment by afollestad** [comment]
Pass false for wrapInScrollView and handle scrolling yourself.

**Comment by azizimusa** [comment]
tried that. But the title  padding is still there.

**Comment by afollestad** [comment]
Oh, yeah you can't remove title padding. It used the Material Design
Guidelines specs.

**Comment by hendraanggrian** [comment]
@afollestad hey there, quick question, what about bottom padding?

![screenshot_1483349461](https://cloud.githubusercontent.com/assets/11507430/21586940/163da026-d109-11e6-9496-e3c7833dd213.png)
