### ISSUE TITLE
Multiple line EditText Dialog

### ISSUE THREAD

**Issue by REWKyleB** [afollestad/material-dialogs#541]
Is it possible to make a multi-line EditText dialog?

**Comment by afollestad** [comment]
This is a duplicate.

**Comment by tommytcchan** [comment]
@afollestad sorry but what is the duplicate issue? I'm finding that I can't set a multi line edittext when I use a custom layout, any pointers would be great thanks.

**Comment by afollestad** [comment]
I misunderstood the question, I think. I thought he meant more than one input field. 

You can make an EditText multi line through the input type. The XML attribute indirectly does that. So you don't actually need a custom view. Search StackOverflow how to make an EditText multi line programatically. 

MaterialDialog has a `getEditText()` method.

**Comment by tommytcchan** [comment]
@afollestad thanks for the quick reply! I actually need a custom view since I have other elements in the dialog. I'm programmatically adding the edittext (wrapped in a relative layout with description):

```
    EditText editText = new EditText(context);
    editText.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, context.getResources
        ().getDimensionPixelSize(R.dimen.dp_80)));
    editText.setId(R.id.auto_respond_text);
    editText.setEms(10);
    editText.setGravity(Gravity.LEFT | Gravity.TOP);
    editText.setInputType(InputType.TYPE_TEXT_FLAG_MULTI_LINE);
    editText.setHorizontallyScrolling(false);
    layout.addView(editText);
```
I've tried to set a definitive height (80dp), but it doesn't expand the edittext

screenshot: http://screencloud.net/v/A3DB

**Comment by afollestad** [comment]
@tommytcchan I think you're missing a flag from the input type, this is actually a common issue people have on Android.

**Comment by tommytcchan** [comment]
@afollestad sorry you are totally correct, it has to do with the way I'm initializing the edittext. sorry about that!
