### ISSUE TITLE
Unselected radio buttons in MaterialListPreference, EditText in MaterialEditTextPreference is invisible with non-AppCompat theme

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#542]
When trying to use `MaterialListPreference` in a preference activity derived from `PreferenceActivity` (not appcompat), the unselected option buttons are not visible. Tested in Android 5.1 and 4.1.

![image](https://cloud.githubusercontent.com/assets/1407837/7815928/fa898824-03fd-11e5-9b33-0042a750c6d0.png)

**Comment by afollestad** [comment]
It happens with EditTexts too, thanks for reporting this

**Comment by afollestad** [comment]
However I don't think too much can be done about this. 

AppCompat is vital to theming views (and their backgrounds), this library is built around and on top of AppCompat.

@plusCubed do you think there's anything simple we can really do about this?

**Comment by plusCubed** [comment]
Use an AppCompatPreferenceActivity - it's not included in the AppCompat library, but you can just download it from the official demos here: https://github.com/android/platform_development/blob/master/samples/Support7Demos/src/com/example/android/supportv7/app/AppCompatPreferenceActivity.java
