### ISSUE TITLE
Extra top padding when using customview

### ISSUE THREAD

**Issue by ffallah** [afollestad/material-dialogs#543]
Hi,
Thanks for this great library.
I am using cutomview to show an image inside a dialog, here is my code :
```java
new MaterialDialog.Builder(this)
                .neutralText("SNOOZE")
                .theme(Theme.LIGHT)
                .customView(R.layout.alarm_dlg, false)
                .cancelable(false);
```

alarm_dlg.xml :
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:scaleType="centerCrop"
        android:layout_marginTop="0dp"
        android:id="@+id/imageView"
        android:src="@drawable/burst_landscape"
        android:layout_gravity="top" />
</LinearLayout>
```
But there is an extra top padding :
![extra-top-padding](https://cloud.githubusercontent.com/assets/9332653/7827690/71569e32-0454-11e5-987e-b03e8c744cc0.png)

Based on documentation, there should be no padding when using customviews and scrolling set to false. am I doing something wrong ?

**Comment by Fleker** [comment]
That padding is for the title, although I'm not sure if it can be removed.

**Comment by ffallah** [comment]
Well, if there is no title, I don't think there should be a padding for it. especially if you are using a custom view.

**Comment by Murphybro2** [comment]
I raised an issue too regarding this, the owner said that's how it's intended to work

**Comment by afollestad** [comment]
@Murphybro2 this isn't the same.

The padding in your issue is for list dialogs. This issue is for custom views with no title.

**Comment by Fleker** [comment]
To add to the OP, if you use a custom view without any buttons, you'll get a similarly odd pattern on the bottom.

**Comment by afollestad** [comment]
Working on this now

**Comment by afollestad** [comment]
Should be fixed in the latest commit.

**Comment by afollestad** [comment]
An update was made available late last night:

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.0

**Comment by ffallah** [comment]
Thank you for the update. I can confirm the issue is resolved.

**Comment by RalucaPostelnicu** [comment]
Hello, i've seen that this issue has been fixed on may. But right now that extra spacing on a dialog with no title and buttons but a list, is still visible. Is it posibile to remove somehow that extra padding?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/customview/DialogCustomViewExt.kt#L50

**Comment by afollestad** [comment]
```kotlin
    custom view(..., noVerticalPadding = false)
```

**Comment by pateljigar7210** [comment]
View customView = materialDialog.getCustomView();
        customView.setPadding(0,0,0,0);
        assert customView != null;
