### ISSUE TITLE
Margins on all dialogs?

### ISSUE THREAD

**Issue by Murphybro2** [afollestad/material-dialogs#544]
Hey, just been trying out you MaterialDialog, for the most part it's fantastic! However I've noticed that all the dialogs have margins around them and are therefore bigger! I'll attach a couple of images below showing a list with a single item in. The first picture will be using AlertDialog, the second will be using MaterialDialog. Take note of the top and bottom of the box, I selected them as I screenshot so you can clearly see the difference.

![screenshot_2015-05-27-20-10-27 1](https://cloud.githubusercontent.com/assets/12631827/7845177/37369f46-04ad-11e5-98c7-f245b989e1a8.png)

![screenshot_2015-05-27-20-15-07 1](https://cloud.githubusercontent.com/assets/12631827/7845179/3f72beb0-04ad-11e5-8faf-f07a231eb120.png)

Thanks!

**Comment by afollestad** [comment]
This is intended behavior

**Comment by Murphybro2** [comment]
Why? Makes the alerts bigger than they need to be!

**Comment by afollestad** [comment]
I should add that the developer of Nova Launcher actually implemented the padding logic here and I agree with his decision for aesthetics.

**Comment by brianmuse** [comment]
Found this thread via search. Agree with @Murphybro2 that it is a little bit odd to be breaking parity with the native UI behavior. The padding sometimes feels awkward, especially with dialogs that do not have titles. 

For example, is this how a time picker dialog is intended to look?

![padding](https://cloud.githubusercontent.com/assets/548885/8110913/aa1b80d2-102c-11e5-8f4d-d54c55484eb0.png)

**Comment by afollestad** [comment]
@brianmuse this is unrelated to custom view dialogs like that. That was in another issue that had already been resolved; make sure you're using a new version of the library.

**Comment by brianmuse** [comment]
Ah, gotcha. Thanks for the speedy response, I'll look into updating the library!
