### ISSUE TITLE
how to change title background color

### ISSUE THREAD

**Issue by pasaneramusugoda** [afollestad/material-dialogs#547]
is there a way to change background color of the dialog title?

**Comment by afollestad** [comment]
The font color? Yes. The background color of the view? No.

**Comment by pasaneramusugoda** [comment]
Is there any plans to enhance the library for that or is there any workaround to get that done in the library?

**Comment by afollestad** [comment]
No, this library is intended to use Material Design guidelines. Having a background color different than the dialog itself doesn't follow the guidelines, and looks weird IMO.

**Comment by pasaneramusugoda** [comment]
Ok. thanks :+1:
