### ISSUE TITLE
Change of colorAccent for version 21 and more

### ISSUE THREAD

**Issue by vijaykd** [afollestad/material-dialogs#548]
Hi, 

First of all your library is really great. 

I have a small issue. I am using the simple Material Dialog indeterminate progress bar I am trying to change the color of progress bar. 

I am using android:Theme.Holo.Light.DarkActionBar and trying to change the progress bar color. On my Galaxy nexus the change of color works but when I try the same on Nexus 5 which has 5.1.1 it is not working.

Here is what I have tried:

new MaterialDialog.Builder(this)
					.content(getResources().getString(R.string.registersigningup))
					.progress(true, 0)
					.show();

  <style name="AppBaseTheme" parent="android:Theme.Holo.Light.DarkActionBar">
        <item name="colorAccent">@color/orangeColor</item>
    </style>

Any idea why this happening?

**Comment by afollestad** [comment]
You need to use AppCompat themes in your Activity, not Holo themes.

**Comment by afollestad** [comment]
`colorAccent` is the AppCompat version of `android:colorAccent` which only works on Lollipop. AppCompat is backwards compatible Material theming.

**Comment by vijaykd** [comment]
What if I don't want to use AppCompat like for Galaxy Nexus (4.3) it is working...as I have to change lot of things in my project if I use AppCompat (Actionbar, Drawable etc)

**Comment by afollestad** [comment]
Sorry, a lot of this library is built on AppCompat and it's vital for UI theming. AppCompat uses most of the Material theme back to Gingerbread, including coloring EditTexts, CheckBoxes, etc. There's no way for this library to manually do that without including a lot more resources which take up extra space.

It's not very hard to switch, you just extend `AppCompatActivity` instead of `Activity`, and switch the themes in `styles.xml`. Any uses of `getActionBar()` become `getSupportActionBar()`.

**Comment by vijaykd** [comment]
Yes. I have already tried it and didn't work for me. Actionbar title doesn't show up properly. I have white background and black text in the existing and after I change everything - The actionbar becomes big, ActionBarDrawerToggle is looking for toolbar etc. :(

**Comment by afollestad** [comment]
I'd recommend looking through your theme for anything that you don't need.

**Setting the action bar color:** the `colorPrimary` styles.xml attribute
**Setting the status bar color:** the `colorPrimaryDark` styles.xml attribute
**UI elements like inputs and other fields:** the `colorAccent` styles.xml attribute

`ActionBarDrawerToggle` doesn't need a `Toolbar`, there's another constructor that doesn't take a toolbar. I think it might need AppCompat to work though.

**Comment by vijaykd** [comment]
Hmm.. Let me check on it again! Thanks! Hope it works on existing without any issues. Thanks!
