### ISSUE TITLE
MaterialDialogPreference is missing

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#549]
This is more like enhancement. Other than the 3 Material preferences, we should have `MaterialDialogPreference`, for users to override in place of `DialogPreference`.

A simple example I tried that seems to work fine is 
https://gist.github.com/yukuku/99faed8f8bf48bb33294

**Comment by afollestad** [comment]
An update was made available late last night:

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.0
