### ISSUE TITLE
Select item that is choosen

### ISSUE THREAD

**Issue by vijaykd** [afollestad/material-dialogs#551]
Hi,

I have two questions:

1. Is it possible to change only the color of progress bar? tried to changed on styles.xml but didn't work?

2. I am looking for a way to select an item that is chosen in Single choice dialog box...? As of now there is no option to do that.  Is this possible? even the sample app chooses default value when I return back after selection?

Thanks!

**Comment by afollestad** [comment]
Read the documentation in the README.
