### ISSUE TITLE
Dialog width does not follow the specs.

### ISSUE THREAD

**Issue by danielfaust** [afollestad/material-dialogs#552]
I don't know if this applies specwise to all dialogs, but at least the simple dialog does not follow the specs.

According to the specs whe width should wrap the content, but in 56dp steps, with a minimum of 5 x 56dp.

I'm mentioning this, because when I use a simple dialog on a Nexus 7 its width is almost as wide as the entire screen (in portrait mode), which is clearly not in accordance with the specs. It's as if margin_left and margin_right are defining the dialog's width, which is wrong.

http://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs

Other than that, it's a really great library.

**Comment by afollestad** [comment]
Well, the only thing that page lists is the width of a simple dialog on a phone. It doesn't say anything about tablets, or regular dialogs, so there's not too much I can unless they add more information to the guidelines.

**Comment by deinlandel** [comment]
Voting on this.
Okay, maybe not the guidelines, but I simply CANNOT set dialog with to wrap_content, or to a fixed size. Even when using a custom view.

**Comment by danielfaust** [comment]
Yes, even if it isn't explicitly in the spec, and, @afollestad I apologize for pointing out a wrong thing, I think that implementing this feature would be no waste of time, as it should only be a matter of time when the spec includes more info on this.

It looks so wrong on a tablet that I had to move over to a feature-reduced popup menu.

**Comment by Ph1b** [comment]
Im not sure if this is material design specifications, but at least for my personal design specifications this looks totally weird. This dialog has a custom view with a framelayout set to `wrap_content` containing an ImageView set to ` wrap_content`

![screenshot_2015-06-06-21-15-55](https://cloud.githubusercontent.com/assets/743462/8021053/9bf1d22a-0c91-11e5-954d-d069a0bf26cb.png)

**Comment by Ph1b** [comment]
This one is wiithout a custom view and has the same too-wide layout.

![Uploading Screenshot_2015-06-06-21-22-04.png…]()

**Comment by Ph1b** [comment]
A nexus 7 has a screen width of 600dp. So according to [this](http://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs) where they use 5x56 dp = 280dp, thats  less than half of the screen width. 

Im not sure but one of [these](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B0J8hsRkk91LNTgxRXh4YW5rSjA/Layout_Tablet_Whiteframe.ai) could be interpreted to have 8*56dp=448dp, which would be about 75%.

Right now we are at... 90%?

**Comment by afollestad** [comment]
@plusCubed have an ideas for this?

**Comment by afollestad** [comment]
@plusCubed @teslacoil have any ideas for this?

**Comment by traninho** [comment]
Same here. I cannot achieve a dialog's width to be wrapped by a content's width.

**Comment by diogo10** [comment]
I came across with this bug too....when I use a customView work well.

**Comment by danielfaust** [comment]
@diogo10 Thanks, I will check this out.
On a note aside, I noticed that on a Nexus 7 in the YouTube app the filter dialog for searches, the one that pops up when pressing the slashed triangle on the top right after entering a search allowing you to refine the search also expands itself to fill the screen, instead of wrapping the content.
So this may be a hint that Google hasn't yet taken enough care on defining the behaviour of the dialogs.
If the customView allows one to wrap the dialog's content as a workaround, then it may be better to wait until Google decides what to do.

**Comment by plusCubed** [comment]
@afollestad I am able to modify the dialog width by changing the insetRight and insetLeft attributes of the dialog background, so it is definitely possible to modify the width. Right now, the AppCompat library's background style uses a 16dp inset on all sides of the dialog. The lack of specs for tablet layouts (and details for dialogs on mobile - it looks quite ridiculous with 40dp padding on both sides as specified by the guidelines) makes me want to wait for Google before doing anything though.

As for the wrap_content thing, all layout attributes for the root view of custom views are ignored (I believe). @Ph1b 

In the mean time, for anyone who wants to change the width, call `getWindow().setLayout(width, height)` on the `MaterialDialog` instance (keep in mind the 16dp inset is still applied). I wouldn't recommend doing this unless you know how to implement ALL the factors (screen width and height, content width and height, etc).

**Comment by hzsweers** [comment]
@plusCubed is it possible to see what insets AppCompat uses for different screen sizes, or do they not use `insetRight` and `insetLeft`? I agree that it's frustrating that Google offers little-to-no tablet information in the Material spec

**Comment by plusCubed** [comment]
@hzsweers We are using AppCompat's backgrounds, and I believe they only have one definition for all screen sizes (which is 16dp inset on all sides).

**Comment by hzsweers** [comment]
I see. We might have a couple of contacts at google on the MD team that we can reach out to on this, I'll shake some trees and report back. In the meantime, it would probably be safe to categorize insets for phones, 7" tablets, and 9"+ tablets to keep things simple. What do you think?

**Comment by plusCubed** [comment]
@hzsweers Thanks in advance. I don't know what to set for the insets for 7" and 9"+ though - it seems ambiguous to just assume some numbers. There is also a mechanism that I haven't fully investigated yet - if you turn a phone to landscape, something (OS/dialog theme/dialog style..? - IDK) limits the width.

**Comment by hzsweers** [comment]
So talked with our contact, and they gave us some guidelines:

> We haven't established max widths of dialogs or bottom sheets. Instead, for the sake of flexibility, we simply determine width based on content needs and using increments (either 56dp for small screens, or 64dp for large screens). 

> For example, this dialog from spec is 5x width, or 280dp.

![](https://cloud.githubusercontent.com/assets/1361086/8608618/55a7002c-2651-11e5-8531-76658e72556d.png)

> You can see [here](http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-incremental-keylines), in the metrics and keylines section of the Material Design spec, that we can use increments to determine multiple aspects of a layout, this way the size of various structural components relate to each other.

Regarding items with variable width and can fit to the container of the parent (text, gridviews, etc):

> What I would suggest is a combination of the increments described, and an understanding of appropriate line length based on the content. 

> There is a section in spec under typography that talks about appropriate [line length](http://www.google.com/design/spec/style/typography.html#typography-other-typographic-guidelines) if you scroll down in the section a bit. 

I put together this gist of some examples: https://gist.github.com/hzsweers/eb76c43f1a4536173af4

I think ultimately what we should do is just go with the width settings of the system dialogs. Open source, so we should hopefully be able to dig in and find them. Target that size, and allow custom views in the dialog to request a wider view if necessary (layoutparams + results of their onMeasure).

What do you think?

**Comment by freezy** [comment]
> I am able to modify the dialog width by changing the insetRight and insetLeft attributes of the dialog
> background, so it is definitely possible to modify the width.

@afollestad: Got more detailed instructions how to do that?

**Comment by plusCubed** [comment]
@hzsweers Sorry for getting back to you so late - kinda forgot about this :S I think that's a good idea - I'll get started on that. Perhaps in the future we can do something with the line length.

@freezy If you are willing to fork the repo, what you can do is get a copy of `abc_dialog_material_background_light.xml` from the appcompat library sources, and modify the insetLeft/insetRight. Then set that as the `android:windowBackground` attribute of the material-dialog theme. I don't recommend doing this - if you're just looking for a more optimized tablet layout, as I said above, I'll be working on that :)

**Comment by freezy** [comment]
Thanks for the info. I thought it would somehow be possible without a modified build. I fiddled with `MaterialDialog#getView()` but couldn't get it to display at a given width.

Future solutions to this problem would be very welcome. Thanks for giving it a thought!

**Comment by hzsweers** [comment]
We had a hangout with members of the material team on Tuesday and they're
going to look at improving the guidelines in Themis regard. In the
meantime, we agreed it's probably best to define upper and lower bounds for
width in accordance with the spec for line length, so I think we should
shoot for that.

Proposed rules:

* If a custom view and it wraps its content, try to wrap around the view's
intrinsic width (measure first and set the rest of the dialog's dimensions
accordingly)
* If custom view and match/fill parent, then fall back to line length
(maybe discourage this though)
* If no custom view (I.e. The built-in stuff), all fall back to line length
bounds. Message-only especially can benefit from this.
* after calculating desired line length and dialog width, set horizontal
margins accordingly to force this size. Use a density-specific Boolean
resources to resolve screen sizes and choose line lengths accordingly.

Thoughts?

**Comment by hzsweers** [comment]
We had a hangout with members of the material team on Tuesday and they're
going to look at improving the guidelines in Themis regard. In the
meantime, we agreed it's probably best to define upper and lower bounds for
width in accordance with the spec for line length, so I think we should
shoot for that.

Proposed rules:

* If a custom view and it wraps its content, try to wrap around the view's
intrinsic width (measure first and set the rest of the dialog's dimensions
accordingly)
* If custom view and match/fill parent, then fall back to line length
(maybe discourage this though)
* If no custom view (I.e. The built-in stuff), all fall back to line length
bounds. Message-only especially can benefit from this.
* after calculating desired line length and dialog width, set horizontal
margins accordingly to force this size. Use a density-specific Boolean
resources t

**Comment by plusCubed** [comment]
@hzsweers That sounds like a good plan. How should the line lengths and specific specs for that be though? Reading the guidelines, there doesn't seem to be a hard, fast spec - there's the 60 characters per line, then the "short lines" guideline (which seems to point at about 30 characters per line). 

I think the simplest way to go about this would be to calculate the width for an optimal number of characters vs line length ratio (with lower/upper limits for the dialog width). In other words, the height vs width of a body of text. I have no idea whether that is an approved way under the material guidelines though. The optimal height vs width (# of char vs line length) ratio would also need to be determined.

The other option is to follow the guideline more closely and determine a cutoff for the number of characters for a text to be considered "short" and "normal".

Either way, we would also need to take into account other languages - which makes me think this all needs to be either configurable or highly advanced to be able to calculate the line length correctly for all languages. Although using the first option, the optimal height vs width would probably work for most languages if we calculate the measured height vs width instead of using the # of characters.

What do you think?

**Comment by hzsweers** [comment]
I think we can be flexible regarding "short" lines. If it's below a certain number of characters, just assume it's a short message and measure accordingly. Default to the 60 character length though.

I think the character size won't really be a worry across languages though. We can revisit if people bring it up, but otherwise I think we can get probably 95% of what we want with behavior just with the simple approach.

So to be clear, my suggestion is:

* Default to 60 char line length + normal horizonal insets as dialog width
* If message is less than, say, 45 chars (we can test to see what looks best), then use the narrower line spec.

**Comment by deinlandel** [comment]
What about custom layouts? Is it possible to just "wrap content" for them?

**Comment by hzsweers** [comment]
if they wrap content, we can just use its given size. Onus is on the user to be intelligent about their custom views. If they say match/fill parent, then just limit it to the upper bound we defined above

**Comment by hzsweers** [comment]
Actually, I have a new idea that's much simpler. Notification panel has strict dimens for its sizes on different screen sizes, and it just so happens that this looks like it's about right. Maybe we can just steal them?

Example: https://android.googlesource.com/platform/frameworks/base/+/13522a2/packages/SystemUI/res/values-sw600dp/dimens.xml

See `notification_panel_width`

**Comment by hzsweers** [comment]
Boom: https://github.com/afollestad/material-dialogs/pull/640

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.8.0

**Comment by deinlandel** [comment]
What about the ability to set dialog width to "wrap_content"?

**Comment by hzsweers** [comment]
The solution I pull requested covers probably 95% of all use cases for
dialogs. If you really need something that needs dynamic width, then you
probably shouldn't be using dialogs IMO. The main issue here was always
that dialogs took full width on tablets, which this solves. If someone can
come up with a good solution for reliably measuring custom view content
before the dialog is shown, I'm all for it. Until then, I think this is
enough.

**Comment by plusCubed** [comment]
Man, I can't believe I missed how Android system dialogs did the width. So, in the latest AppCompat 23.1.0, as Chris Banes writes here: https://plus.google.com/+ChrisBanes/posts/TX817XUewtF, the AppCompat dialog width was fixed, so I went to re-investigate. Turns out, there were just different screen width dimension resources in Android lollipop+ for the windowMinWidthMajor and windowMinWidthMinor properties, and they added them into the latest AppCompat.

Anyway, final resolution to this issue in 56b19673fccd84597067ea62aa657f15a397f395, reverting back to using the AppCompat styles for width.

**Comment by afollestad** [comment]
@plusCubed good find!

**Comment by afollestad** [comment]
@plusCubed here's a side by side of Material Dialogs (on the left) and a stock Marshmallow AlertDialog (on the right). Looks like it's working fine now!

![comparison](https://cloud.githubusercontent.com/assets/1820165/10555057/409c7ea6-742f-11e5-98ca-42226f02cc7d.jpeg)

But, the heights are slightly different, but it looks like the AppCompat AlertDialog doesn't really follow the guidelines perfectly.
