### ISSUE TITLE
MultiChoice checkboxes not applying theme

### ISSUE THREAD

**Issue by josalvdel1** [afollestad/material-dialogs#553]
Hi, 

I'm using a dialog as the following snippet of code. My theme is `Theme.AppCompat.NoActionBar` so I'm put `Theme.Light` to customize the dialog. The content is ok, but the checkboxes unpressed styled remains with dark theme (white color). 

Could you take a look?

Thank you.

```java
    eventMultiDialog = new MaterialDialog.Builder(getActivity())
                .title(R.string.choose_tasks_c)
                .titleColorRes(R.color.app_blue)
                .theme(Theme.LIGHT)
                .widgetColorRes(R.color.app_green)
                .items(R.array.task_mock_items)//TODO replace with data from service
                .itemsCallbackMultiChoice(new Integer[]{}, new MaterialDialog.ListCallbackMultiChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog materialDialog, Integer[] integers, CharSequence[] charSequences) {

                        return true;
                    }
                })
                .positiveText(R.string.done_u)
                .positiveColorRes(R.color.app_green)
                .build();
```

**Comment by afollestad** [comment]
Unfortunately not too much can be done about that.

The dialog is inflated with whatever theme you specify with the `theme(Theme)` Builder method (or `LIGHT` by default). If the dialog view was inflated using the Activity theme, then there would be a lot of visual issues (e.g. wrong colors for scroll indicators and other elements).

**Comment by alorma** [comment]
You can use the ContextThemeWrapper to inflate your layout within a specific theme

**Comment by afollestad** [comment]
@alorma that's what used to be done, but like I said above, it causes many visual issues.

**Comment by afollestad** [comment]
Actually, I have an idea

**Comment by afollestad** [comment]
@alorma not sure why I didn't think of using a different context to inflate the individual list item layouts before.

This issue is fixed in https://github.com/afollestad/material-dialogs/commit/c5e79ec6d2c1bd5c5fc63007f11e85a6167c613c.

**Comment by alorma** [comment]
@afollestad nice!

**Comment by josalvdel1** [comment]
Thank you for the work! But it still working in the bad way. Is there any workaround to solve this? What context do you suggest to use? Thank you!

**Comment by afollestad** [comment]
@josalvdel1 you haven't gotten the fix yet, it's not published

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.3
