### ISSUE TITLE
Indeterminate progress dialog on Android 5.0

### ISSUE THREAD

**Issue by stelmik** [afollestad/material-dialogs#555]
There is a problem with indeterminate progress dialog on Android 5.0 (tested on Samsung Galaxy S4 and S5 with Android 5.0).
The problem is: circle drawable is not visible (but content text is visible).
On Android 2.3 and 4.0 it is OK.

You can try "Progress Dialog (indeterminate)" from sample application on Android 5.0 to see the problem.

**Comment by afollestad** [comment]
I develop primarily on Lollipop and the M Developer Preview. It works fine on Android 5.0, 5.1, and M.

![shamumpz44qafollestad06042015120322](https://cloud.githubusercontent.com/assets/1820165/7989808/c6de8a6e-0ab1-11e5-8296-ac44d53bfe78.png)

**Comment by afollestad** [comment]
This may be a Samsung issue.

**Comment by stelmik** [comment]
It not Samsung issue.

To reproduce:
Go to **Settings** -> **Developer options** (set it to **On**),
then set **Animator duration scale** perference in **Developer options** section to value **Off**.

After that you don't see any animated circles on this device (doesn't matter if it is Samsung, LG, emulator, etc). On all of devices you don't see the animated elements.

Maybe it is possible to check above settings and try to solve it?
