### ISSUE TITLE
shows again after dismiss() call 

### ISSUE THREAD

**Issue by rakshitsoni02** [afollestad/material-dialogs#556]
after showing  progress dialog and dismiss  it  shows again.

**Comment by afollestad** [comment]
Same way it's done with a regular dialog. show()

**Comment by afollestad** [comment]
Sorry I misunderstood what you said, initially. But I can't reproduce that issue. Are you using at least version 0.7.5.0?

**Comment by rakshitsoni02** [comment]
In a sync task when i am showing progress dialog in pre execute  and in
post method i call dismiss and  the dialog also dismiss that time and in
automatically visible again ,.

**Comment by afollestad** [comment]
That's still not very clear.

But again, check that you're using a new version of the library. I've never run into that issue.

**Comment by rakshitsoni02** [comment]
Okay thanks
