### ISSUE TITLE
TextInputLayout

### ISSUE THREAD

**Issue by RubenGees** [afollestad/material-dialogs#557]
It would be great if you could include the new TextInputLayout from the Design Library. (or make it optional) I think it looks really cool and fits very good into Material Design.
http://android-developers.blogspot.de/2015/05/android-design-support-library.html

**Comment by afollestad** [comment]
For input dialogs?

I thought about it, but it's not really necessary. Integrating an entire library for one component that can be easily reproduced with a little code isn't necessary.

**Comment by RubenGees** [comment]
Hmm, okay. Then you recommend to make a custom view for that?

**Comment by afollestad** [comment]
If you need something more than what the input dialogs in the library already provide, that would be necessary

**Comment by RubenGees** [comment]
Yes, okay. Thank you for the anwer :)
