### ISSUE TITLE
Dialog doesn't keep it's state after orientation change

### ISSUE THREAD

**Issue by krialix** [afollestad/material-dialogs#558]
![dialog](https://cloud.githubusercontent.com/assets/5319782/7994693/11f30bcc-0b18-11e5-85d0-69439a45f0cf.gif)

**Comment by afollestad** [comment]
That's not an issue specific to this library. That's how dialogs work on Android.

You can wrap dialogs in a `DialogFragment` to survive orientation change. See the color chooser and folder chooser examples in the sample project.
