### ISSUE TITLE
Calling setProgress before showing dialog cause NPE crash

### ISSUE THREAD

**Issue by arcao** [afollestad/material-dialogs#559]
Hi,

I found bug in 0.7.5.2 when call dialog.setProgress(...) method before call dialog.show() method.

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
            at com.afollestad.materialdialogs.MaterialDialog.setProgress(MaterialDialog.java:1337)

Example code:
```java
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
				.progress(false, 1)
				.negativeText(R.string.cancel_button)
				.build();
...
dialog.setProgress(-1);
...
dialog.show();
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.3
