### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by benkibbey** [afollestad/material-dialogs#560]
I'm not sure if this is related to material-dialogs but it seems to be. I get this FC when building an app that requires material-dialogs:

E/AndroidRuntime( 8288): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/afollestad/materialdialogs/R$color;
E/AndroidRuntime( 8288):        at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>
[...]
E/AndroidRuntime( 8288): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.afollestad.materialdialogs.R$color" on path: DexPathList[[zip file "/data/app/org.tvheadend.tvhclient-1/base.apk"],nativeLibraryDirectories=[/data/local/lib, /vendor/lib, /system/lib]]

I'm using Eclipse to build TVHclient since it doesn't support the gradle build system. I've added the gradle-built material-dialogs jar to the build path and all seems fine in Eclipse (no relevant warnings). The R$color symbol seems to be defined in appcompat-7 but not in com.afollestad.materialdialogs.

**Comment by afollestad** [comment]
You can't use JARs for Android Libraries, JARs only contain Java.

**Comment by afollestad** [comment]
You need AARs. Eclipse doesn't support that by default, Andorid Studio does.
