### ISSUE TITLE
no method to dismiss Circular Progress Dialog

### ISSUE THREAD

**Issue by vaibhavtaylor** [afollestad/material-dialogs#563]
i cant find any method or way to dismiss the dialog when my background work is done. Using asyn task      
i call dialog in onPreExecute but cant dismiss automatically the dialog in onPostExe method. Please can you help me out with this

**Comment by afollestad** [comment]
Same as any other dialog, `dismiss()`

**Comment by afollestad** [comment]
dismiss happens to be a method of `android.app.Dialog`, it's inherited from the Android framework.

**Comment by vaibhavtaylor** [comment]
there is no dismiss method present in your library when i try to call it on MaterialDialog.Builder object. i dont want it to dismiss via listener, i want it dismiss when background activity is done. i.e. to call a dismiss method in onPostExecute.

**Comment by alorma** [comment]
You can't dismiss a dialog from Builder, just not call to .show()  method

**Comment by vaibhavtaylor** [comment]
But after my download has been completed then how do i just dismiss the progress dialog. cant find any method for that

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
