### ISSUE TITLE
Android 5.0.2 - Single Choice List Dialog Radio button bug

### ISSUE THREAD

**Issue by edvardasast** [afollestad/material-dialogs#564]
Radio button leave at selected color when choose another item.

```java
       new MaterialDialog.Builder(getActivity())
                    .theme(Theme.LIGHT)
                    .title(R.string.delete_items)
                    .items(R.array.items)
                    .itemsCallbackSingleChoice(0, new MaterialDialog.ListCallbackSingleChoice() {
                        @Override
                        public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence                   text) {

                            return true; // allow selection
                        }
                    })
                    .positiveText(R.string.delete)
                    .show();
```

Video how it looks:
https://youtu.be/rZ0Y8Z7tF9Y

**Comment by afollestad** [comment]
This used to happen to me, but I fixed it. I'm guessing you're either using an old version of the library, or it's an issue with the version of Android you're using (e.g. Samsung TouchWiz).

**Comment by edvardasast** [comment]
I use latest library version and HTC ONE with android version 5.0.2  I test it on Nexus5 with android 5.1 and there is no bug on nexus.

**Comment by afollestad** [comment]
I actually believe this was a bug that I also experienced on Android 5.0.2, but it went away with Android 5.1+

**Comment by richardaum** [comment]
Android Version 5.0.2, Library Version 0.7.6.0.  Problem was solved until here?

**Comment by afollestad** [comment]
@richardaum `MDTintHelper`, which is a shortcut to some AppCompat utilities. This bug only occurs on Android 5.0.2 as far as I know, Google fixed the issue on 5.1 and above.

**Comment by edvardasast** [comment]
Android Version 5.0.2, Library Version 0.7.6.0. Problem was solved until
here?

Problem still exist.

2015-07-13 20:50 GMT+03:00 Richard Lopes <notifications@github.com>:

> Android Version 5.0.2, Library Version 0.7.6.0. Problem was solved until
> here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/564#issuecomment-121004468>
> .
>



-- 
Pagarbiai
Edvardas Astrauskas

**Comment by afollestad** [comment]
@edvardasast the problem exists specifically on Android 5.0.2, like I said above I don't think I can do anything to fix it. Android 5.1 exists now, and the M Developer Preview.

**Comment by richardaum** [comment]
Isn't there any kind of work around to make this display correctly? Overriding a method...

Em 14/07/2015 12:21, Aidan Follestad <notifications@github.com> escreveu:
@edvardasast the problem exists specifically on Android 5.0.2, like I said above I don't think I can do anything to fix it. Android 5.1 exists now, and the M Developer Preview.

---

**Comment by afollestad** [comment]
@richardaum I haven't found any

**Comment by richardaum** [comment]
Is this a problemas with coloring radiobuttons natively or is this introduced by using Compat libraries?

Em 14/07/2015 12:40, Aidan Follestad <notifications@github.com> escreveu:
@richardaum I haven't found any

---

**Comment by afollestad** [comment]
@richardaum coloring is done using AppCompat's coloring features, with the exception of a progress bars.
