### ISSUE TITLE
Extend MaterialListPreference for custom list_items

### ISSUE THREAD

**Issue by StanislavChumarin** [afollestad/material-dialogs#565]
All of implemented Material*Preferences does not call to onPrepareDialogBuilder which makes hard to make customizations to dialogs.
Example: use custom Adapter for ListView in MaterialListPreference.

**Comment by afollestad** [comment]
This library cannot do that.

The signature is:

```java
protected void onPrepareDialogBuilder(AlertDialog.Builder builder);
```

MaterialDialogs does not use `AlertDialog.Builder`, it uses `MaterialDialog.Builder`.
