### ISSUE TITLE
Cannot override button color if attribute already set

### ISSUE THREAD

**Issue by s73v3r** [afollestad/material-dialogs#566]
If you have colors set in your theme for things like the Positive Button(md_positive_color), then you are not able to override these settings for one dialog.

```java
mBuilder.positiveColor = DialogUtils.resolveColor(mBuilder.context, R.attr.md_positive_color, mBuilder.positiveColor);
```

Should probably have the last two arguments reversed in order to allow dialogs to override the set style if needed.

**Comment by s73v3r** [comment]
Reversing the arguments probably isn't the way to go. But the point still stands: If I set a color in the builder, that should override a color set in the theme.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.6
