### ISSUE TITLE
ProgressBarDialog - Indeterminate not working

### ISSUE THREAD

**Issue by gintechsystems** [afollestad/material-dialogs#569]
The progressbar widget does not move at all when I set .progress(true, 0) it just shows the widget. Is there anyway to resolve this right now? I can change my accentColor fine but cannot seem to get indeterminate to work, do I have to set the animation myself?

**Comment by afollestad** [comment]
I've tested it from API 14 to API 22 and it works fine. What Android version?

**Comment by gintechsystems** [comment]
5.1.1 Nexus 6, it just sits there and does nothing, very strange. I was thinking it may be the device if anything but not sure how to resolve the issue.

**Comment by afollestad** [comment]
I have Nexus 6 and it works completely fine. I actually don't modify anything about the Progress Bar for Lollipop and and above so there should be no issue.

**Comment by gintechsystems** [comment]
That could be the issue, I am using this code:

defaultLoginProgressDialog = new MaterialDialog.Builder(login_activity)
                        .content("Authenticating...")
                        .progress(true, 0)
                        .cancelable(false).build();
                defaultLoginProgressDialog.show();

**Comment by afollestad** [comment]
Idk, I'm sorry, there's really not much I can do. This would be an issue of `android.widget.ProgressBar` not working correctly.

![shamumpz44qafollestad06102015101657](https://cloud.githubusercontent.com/assets/1820165/8086228/ddeb55be-0f59-11e5-93d5-eb6db6ccb779.gif)
