### ISSUE TITLE
LayoutDirection - RTL support

### ISSUE THREAD

**Issue by whitehawks** [afollestad/material-dialogs#570]
I have read the README file from top to bottom, yet i couldnt find anything regarding layout direction, so I just want to clarify whether it is possible for me to apply rtl support for dialog boxes if so could you please add a small tutorial on how to apply rtl to dialog boxes to the README file.

**Comment by afollestad** [comment]
There's no setting for it, RTL is applied automatically for Android versions that support it (4.2 Jellybean and above, I believe). I thoroughly tested it before and it works like it should.

Keep in mind Android automatically applies RTL layouts on devices with RTL languages, so your entire phone has to be switched to a language like Arabic.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
