### ISSUE TITLE
setContent() method call throw a NullPointerException

### ISSUE THREAD

**Issue by Piasy** [afollestad/material-dialogs#571]
When I keep a reference of a created(and shown) MaterialDialog, and when I want to change the content of this dialog and re-show it, a NullPointerException is thrown in the method setContent.
```java
public final void setContent(final CharSequence newContent) {
        this.mHandler.post(new Runnable() {
            public void run() {
                MaterialDialog.this.content.setText(newContent);
                MaterialDialog.this.content.setVisibility(TextUtils.isEmpty(newContent)?8:0);
            }
        });
    }
```
The `this.mHandler` is null.

Is this a bug or do I use MaterialDialog in a wrong way? When I want to reuse a created and shown dialog but with different content, what should I do?

**Comment by afollestad** [comment]
Make sure you're using a new version of the library, first.

But `mHandler` is initialized when you first build the dialog (specifically in the constructor of the `MaterialDialog` class). The only way it could become null in the latest code is if it was garbage collected.

However, I will add a check that will re-initialize it if necessary.

**Comment by afollestad** [comment]
Actually, nevermind. `setContent()` doesn't use mHandler in the first place, you must have a very old version of the library.

**Comment by Piasy** [comment]
Sorry, I'm using the version 0.7.3.2. The latest 0.7.5.5 has a build error.

**Comment by afollestad** [comment]
The latest is 0.7.5.6, published this morning. There's no build errors.

On Fri, Jun 12, 2015, 11:03 AM Xu Jianlin <notifications@github.com> wrote:

> Sorry, I'm using the version 0.7.3.2. The latest 0.7.5.5 has a build error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/571#issuecomment-111536259>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by Piasy** [comment]
Great!

**Comment by afollestad** [comment]
There weren't any build errors before either, lol. Not in the library
itself at least.

On Fri, Jun 12, 2015, 11:22 AM Xu Jianlin <notifications@github.com> wrote:

> Great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/571#issuecomment-111543189>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by Piasy** [comment]
#576 still exist with version 0.7.5.6

**Comment by afollestad** [comment]
@Piasy I didn't say it was fixed

**Comment by Piasy** [comment]
Well, I thought I misunderstand your last comment. :)
