### ISSUE TITLE
Indeterminate seekbar progress dialog

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#572]
Unlike with Android default API's, it seems that I can't have an indeterminate "seekbar" progress dialog.

This is really useful for example when downloading a file: if the network become unavailable, we put the seekbar in "indeterminate" state unless network is back.

Am I wrong and it's possible to do that? (if yes, how?)

If not, would it be possible to implement that feature?

Thanks a lot, wonderful library.

**Comment by afollestad** [comment]
Read the README tutorial on the front page, or view the parameter names of the `progress()` method.

**Comment by StephaneDupont** [comment]
There's nothing about indeterminate seekbar in the README tutorial.

"This will display the classic progress dialog with a spinning circle"
"If a dialog is not indeterminate, it displays a horizontal progress bar that increases up until a max value."

I'm not talking about an indeterminate spinner, I'm talking about an indeterminate horizontal progress bar. It seems that I can have either an indeterminate spinner or a determinate horizontal progress bar. What about indeterminate horizontal progress bar?

**Comment by StephaneDupont** [comment]
In other words, what it seems we can't do with the library is once we have a progress dialog with an horizontal progress bar, being able to call (when we lose network connectivity for example):

dialog.setIndeterminate(true);
