### ISSUE TITLE
Support Library 22.2.0 is buggy

### ISSUE THREAD

**Issue by AAverin** [afollestad/material-dialogs#573]
There is a known issue with Support Library 22.2.0: https://code.google.com/p/android/issues/detail?id=175086
Hopefully soon it will be fixed, but for now - is there an option to go back to 22.1.1?

**Comment by afollestad** [comment]
Sorry no, previous versions weren't too much better. 22.2.0 is actually better than a recent version, I will update the library as soon as a new version is released though.

**Comment by AAverin** [comment]
Ok, so looks like we stuck without Material dialogs until Google fixes the library.
We can't use Design Support Library because of the bug in 22.2.0, and we can't use your library for the same reason=(

**Comment by afollestad** [comment]
Well, one solution may be to force the old version from your app.

```Gradle
compile('com.android.support:appcompat-v7:22.1.1){
    force = true
}
```

From my understanding, this will overwrite the versions used in any libraries you depend on for your main app module.

**Comment by AAverin** [comment]
Depends on your implementation, but basically I started searching for the solution because v7.AlertDialog in 22.1.1 has a weird bug with a shadow.

**Comment by afollestad** [comment]
Well you can force any version
