### ISSUE TITLE
For create signed apk

### ISSUE THREAD

**Issue by parasghasadiyas** [afollestad/material-dialogs#575]
Error:A problem occurred configuring project ':Application'.
> A problem occurred configuring project ':Material dialog'.
   > Cannot access first() element from an empty List

**Comment by afollestad** [comment]
This is a Cradle issue that I suspect Google needs to solve.

**Comment by dinhhieuac** [comment]
I have a problem like you
Error:A problem occurred configuring project ':sample'.
> A problem occurred configuring project ':library_material_dialogs'.
   > Cannot access first() element from an empty List

When you export apk from 
https://play.google.com/store/apps/details?id=com.afollestad.materialdialogssample

You using Eclipse or Android studio?
