### ISSUE TITLE
Indeterminate horizontal seekbar progress dialog

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#577]
Sorry for creating a new issue for that, but the previous issue I've reported as been marked as invalid, I can't reopen it, and as it has been closed, I'm not sure you read my comments after you've closed it.

Can you read my last comments and look at it again please? https://github.com/afollestad/material-dialogs/issues/572

I'm pretty sure it's not invalid. Maybe it's a feature you don't want to implement, but if it's the case, can you tell me? Because that's the missing feature preventing me to migrate to this library: for a file download, if network is unavailable, we should be able to put an horizontal seekbar dialog in indeterminate state (not with a spinner!), as we can with default Android APIs.

Thank you.

**Comment by afollestad** [comment]
Sorry, I misunderstood what you meant originally. 

One thing to note is that the stock API is a separate class from the main dialog. However this is useful, so I implemented it for the next update.

**Comment by StephaneDupont** [comment]
Thank you!
