### ISSUE TITLE
setProgressNumberFormat()

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#578]
Is there an alternative to `ProgressDialog.setProgressNumberFormat()` method in your library? (can't find it if there's one).

http://developer.android.com/reference/android/app/ProgressDialog.html#setProgressNumberFormat(java.lang.String)

**Comment by StephaneDupont** [comment]
Thank you!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.6.0
