### ISSUE TITLE
setIndeterminate() in the MaterialDialog class

### ISSUE THREAD

**Issue by StephaneDupont** [afollestad/material-dialogs#579]
Thank you for the two previous issues I posted, and sorry to post one again :)

If I understand correctly, with d297287290fa8fbd7e8b58c7ac4177e68482f5e0 commit, we can now have an indeterminate horizontal seek bar via the Builder.

The thing is the main use of this is for example when we use a ProgressDialog to download a file, and while we initialize the download, or when the network is suddenly unavailable, we put the dialog in "indeterminate" state while waiting for the network to be back. With Android API's, we do it like that:

```
downloadingProgressDialog.setProgressStyle(ProgressDialogPro.STYLE_HORIZONTAL);
downloadingProgressDialog.setProgressNumberFormat("%1dMB/%2dMB");

public void onDownloadStateChanged(int newState) {
switch (newState) {
	case IDownloaderClient.STATE_IDLE:
	case IDownloaderClient.STATE_CONNECTING:
	case IDownloaderClient.STATE_FETCHING_URL:
		downloadingProgressDialog.setIndeterminate(true);
		break;

	case IDownloaderClient.STATE_DOWNLOADING:
		downloadingProgressDialog.setIndeterminate(false);

	// etc...
}
}

public void onDownloadProgress(DownloadProgressInfo progress) {
	downloadingProgressDialog.setIndeterminate(false);
	downloadingProgressDialog.setMax((int) (progress.mOverallTotal/(1024*1024)));
	downloadingProgressDialog.setProgress((int) (progress.mOverallProgress/(1024*1024)));*
}
```

Can we do that with your last commit? (it seems we can't because we can only set things in the builder, we can't change the indeterminate state while the dialog is already shown. Or is there something I didn't see?)

**Comment by afollestad** [comment]
Sorry, this can't be done. You'll need to dismiss the old dialog and display a new one.

Layouts are determined at runtime currently, changing that will require a lot of code changes and layout inflations aren't the most efficient thing.

**Comment by StephaneDupont** [comment]
Ok, thank you anyway, keep up the good work!
