### ISSUE TITLE
Possible MaterialDialogPreference bug

### ISSUE THREAD

**Issue by deinlandel** [afollestad/material-dialogs#581]
I am trying to implement my custom preference using `MaterialDialogPreference`.

As per guidelines, I am trying to save preference data in `onDialogClosed(boolean positiveResult)` method. Problem is, this method never gets called when dialog is dismissed (in any way, by clicking on OK, CANCEL, etc.). As far I as I can see, the reason is `MaterialDialogPreference` is not setting itself as a button callback and/or dismiss listener when it creates the dialog.

**Comment by deinlandel** [comment]
Here's the (ugly) workaround that fixes the behavior:
```java
    @Override
    protected void showDialog(Bundle state) {
        super.showDialog(state);
        MaterialDialog dialog = (MaterialDialog) getDialog();
        dialog.setOnDismissListener(this);
        dialog.getBuilder().callback(new MaterialDialog.ButtonCallback() {
            @Override
            public void onPositive(MaterialDialog dialog) {
                onClick(dialog, DialogInterface.BUTTON_POSITIVE);
            }

            @Override
            public void onNegative(MaterialDialog dialog) {
                onClick(dialog, DialogInterface.BUTTON_NEGATIVE);
                super.onNegative(dialog);
            }                  
        });
    }
```

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
