### ISSUE TITLE
Button positioning when dialog isn't scrollable on small screens in landscape

### ISSUE THREAD

**Issue by danielmuu** [afollestad/material-dialogs#582]
Hey, 

the pictures show you that on the Nexus 4 the "CHOOSE" button has no bottom padding in landscape mode, but it should have because the dialog isn't scrollable. I tested it on the Nexus 7 and there it has the right behaviour with a padding under the button. Maybe there is small calculating mistake. 

![nexus4](https://cloud.githubusercontent.com/assets/10696844/8241984/abc80dd4-160c-11e5-97da-29b9129a54fb.png)
![nexus7](https://cloud.githubusercontent.com/assets/10696844/8241985/abdc8ea8-160c-11e5-9296-0c504ce144f3.png)

**Comment by danielmuu** [comment]
Hey,

i think the material design guidelines are adjusted here. I can't find the difference between a scrollable and an non-scrollable dialog anymore. Booth should have now the same padding.

https://www.google.com/design/spec/components/dialogs.html#dialogs-specs

**Comment by afollestad** [comment]
The dividers and padding are different in scrollable dialogs:

![components_dialogs_updates8](https://cloud.githubusercontent.com/assets/1820165/8611742/58862644-268b-11e5-8884-c7e86af52807.png)

I'll look into the padding issue.

**Comment by afollestad** [comment]
The dialog isn't scrollable in either of those pictures you have though, if they were the dividers would be visible.

**Comment by danielmuu** [comment]
Ok cool. The guidelines makes it now easier to implement. The button bar has now everytime a height of 52dp. No more removing of padding when dialog is scrollable.

**Comment by afollestad** [comment]
Not really sure what you mean. The guidelines have not changed since this library was updated.

The padding isn't removed either.

**Comment by afollestad** [comment]
Portrait:

![portrait](https://cloud.githubusercontent.com/assets/1820165/8631607/988e3f32-2740-11e5-8c23-1f0062e71388.png)

Landscape:

![landscape](https://cloud.githubusercontent.com/assets/1820165/8631610/9bf32d0e-2740-11e5-94f9-ad38ba77d475.png)

**Comment by afollestad** [comment]
@plusCubed @teslacoil have either of you noticed any bugs related to padding being cancelled out by limited screen height?

**Comment by plusCubed** [comment]
@afollestad I recall encountering something like this, but I don't remember when that happened (might've been fixed, might've not been, IDK). I'll test it out.

**Comment by danielmuu** [comment]
@afollestad Here is what you wrote in your dimens.xml

        >When dialog is large enough to scroll, some padding is removed to make space and
        >keep things symmetrical.
        >Reduced paddings are:
        > 8dp above content if there is no title (0dp when scrolled)
        > 8dp below content if there is no button bar (0dp when scrolled)
        > 8dp between content and button bar
        > **0dp below button bar**

0dp below button bar ist now 8dp. The padding isn't removed anymore.

**Comment by afollestad** [comment]
That's most likely out dated from before the library was almost completely
redone with the help of Nova Launcher's dev. He changed quite a bit of
logic related to this stuff around.

On Sat, Jul 11, 2015 at 5:35 AM danielmuu <notifications@github.com> wrote:

> @afollestad <https://github.com/afollestad> Here is what you wrote in
> your dimens.xml
>
>     >When dialog is large enough to scroll, some padding is removed to make space and
>     >keep things symmetrical.
>     >Reduced paddings are:
>     > 8dp above content if there is no title (0dp when scrolled)
>     > 8dp below content if there is no button bar (0dp when scrolled)
>     > 8dp between content and button bar
>     > **0dp below button bar**
>
> 0dp below button bar ist now 8dp. The padding isn't removed anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/582#issuecomment-120603084>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment]
Changed title to reflect a *possible* bug with screens that don't have much height.

**Comment by afollestad** [comment]
It would be helpful if someone could try to reproduce this issue again, and possibly find a fix, since I don't have any small devices and virtual machines are currently broken on my Mac.
