### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by ranjeetlbsimds07** [afollestad/material-dialogs#583]
Hello ,
I import project in eclipse and
 import android-support-v7-appcompat and 
import google-play-services_lib and 
import library and I use the material design 
And I am getting error 
\res\values-v21\styles.xml:16: error: Error: No resource found that matches the given name: attr 'colorAccent'
and res\values-v21\styles.xml:14: error: Error: No resource found that matches the given name: attr 'colorPrimary'
and res\values-v21\styles.xml:15: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark' and res\values-v21\styles.xml:13: error: Error: No resource found that matches the given name: attr 'windowActionBar'.
Please help me how to fix error.

Thanks

**Comment by afollestad** [comment]
You should be using Android Studio, nor Eclipse.

**Comment by ranjeetlbsimds07** [comment]
Yes , I use Android Studio.
