### ISSUE TITLE
NoClassDefFoundError com.afollestad.materialdialogs.R$color

### ISSUE THREAD

**Issue by SoAddicted** [afollestad/material-dialogs#585]
I get the following error while running an application on Android 4.4.4 (using genymotion emulator)
`java.lang.NoClassDefFoundError: com.afollestad.materialdialogs.R$color`

no problems on 5.0

Any ideas?

**Comment by afollestad** [comment]
@SoAddicted how are you integrating the library? That's not an issue with the library itself, it's an issue with how you're referencing it.

**Comment by SoAddicted** [comment]
@afollestad The problem was that I didn't added support library for multidex and thus I got errors on pre 5.0 devices.

Thanks anyway!
