### ISSUE TITLE
Error:(2) Attribute "track" has already been defined

### ISSUE THREAD

**Issue by songbaoqiang** [afollestad/material-dialogs#586]
Error:(2) Attribute "track" has already been defined
Error:(2) Attribute "thumbTextPadding" has already been defined
Error:(2) Attribute "switchTextAppearance" has already been defined
Error:(2) Attribute "switchMinWidth" has already been defined
Error:(2) Attribute "switchPadding" has already been defined
Error:(2) Attribute "switchStyle" has already been defined

**Comment by songbaoqiang** [comment]
compile ('com.afollestad:material-dialogs:0.7.6.0')

**Comment by afollestad** [comment]
This is most likely a issue with you including different versions of a library such as AppCompat in your library than what this library uses. Those aren't attributes of this library.
