### ISSUE TITLE
MultiChoice List Dialog not preserving checkbox state even using a DialogFragment

### ISSUE THREAD

**Issue by ferrannp** [afollestad/material-dialogs#588]
I wanted my Dialog window not to leak on Activity destroy so I created a custom DialogFragment:

```java
public class MultiChoiceDialogFragment extends DialogFragment{

    private String title;
    private int arrayId;
    private String positiveText;

    public static MultiChoiceDialogFragment newInstance(String title, int arrayId, String positiveText) {
        MultiChoiceDialogFragment multiChoiceDialogFragment = new MultiChoiceDialogFragment();
        Bundle bundle = new Bundle(3);
        bundle.putString("title", title);
        bundle.putInt("arrayId", arrayId);
        bundle.putString("positive", positiveText);
        multiChoiceDialogFragment.setArguments(bundle);
        return multiChoiceDialogFragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        title = getArguments().getString("title");
        arrayId = getArguments().getInt("arrayId");
        positiveText = getArguments().getString("positive");
    }

    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {

        return new MaterialDialog.Builder(getActivity())
                .title(title)
                .items(arrayId)
                .itemsCallbackMultiChoice(null, new MaterialDialog.ListCallbackMultiChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
                        //TODO
                        return true;
                    }
                })
                .positiveText(positiveText)
                .show();
    }
}
```

When I rotate my device, the dialog continues showing which is good but, the selected checkboxes are reseted. I believe Android should preserve them if they actually have an id. Am I missing something here?

---

Ok found a workaround:

Use `setRetainInstance(true);` and create a field like `private Integer[] selected`. Then:

```java
.itemsCallbackMultiChoice(selected, new MaterialDialog.ListCallbackMultiChoice() {
   @Override
    public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
        selected = which;
            return true;
        }
    })
   .alwaysCallMultiChoiceCallback()
```

Although I am not sure if this is the best way to achieve it.

**Comment by afollestad** [comment]
Updated your comment to use syntax highlighting. I'll look into this now.

**Comment by afollestad** [comment]
@ferrannp since `onCreateDialog(Bundle)` is always called in `DialogFragment`; you need to pass the currently selected indices in the `DialogFragment`'s saved instance state.

However, when I attempted to do that, `DialogFragment` calls `onCreateDialog(Bundle)` twice for some reason, and the instance state is null the second time. So using `setRetainInstance(true)` is the best solution for now.

**Comment by ferrannp** [comment]
Hello @afollestad, on the other hand, we should not use `setRetainInstance` for a fragment that has UI. It should only be used with a fragment that returns `null` when `onCreateView` is called, if not, we can leak views. `setRetainInstance` is more meant for fragments that can do network operation for examples and then communicate it to an activity (so it does not need UI).

Therefore, for me this still looks like a bug.

**Comment by bijumittu** [comment]
I am new in this so please guide me how to store multiple selected items into sharedpreferences and retrieve those clickable value on update query to clickable
