### ISSUE TITLE
Cancelable is not working

### ISSUE THREAD

**Issue by euri16** [afollestad/material-dialogs#591]
Hi, im having an issue with this library, im building the Dialog like this:

<code>
mDialog = new MaterialDialog.Builder(getActivity())
                    .title(title)
                    .content(message)
                    .cancelable(false)
                    .autoDismiss(false)
                    .build();
</code>

But it dismisses anyway when I click outside the dialog.

**Comment by SimonKinds** [comment]
I can confirm this running CyanogenMod with version 5.0.2 on Samsung Galaxy S5.

Interestingly enough it worked fine when I ran Samsungs own ROM, but after I flashed CM yesterday it stopped working.

**Comment by afollestad** [comment]
Unfortunately this is most likely an issue with the individual ROMs. The value of `cancelable(boolean)` is passed directly to the `android.app.Dialog` at the base of a `MaterialDialog`, there's no custom implementation for that.

**Comment by mtwn105** [comment]
@afollestad please help me how to dismiss the material dialog's progress dialog when its operation is completed.

**Comment by euri16** [comment]
I ran that code in my HTC One X, is not rooted nor have a third-party ROM.

**Comment by SimonKinds** [comment]
@euri16 Did cancable work for you or not?

**Comment by euri16** [comment]
@SimonKinds as you can see I was the one who opened this issue.

**Comment by SimonKinds** [comment]
@euri16 I'm sorry, I was not paying attention to who opened it. My bad.

**Comment by SimonKinds** [comment]
@mtwn105 I would recommend using an [AsyncTask](http://developer.android.com/reference/android/os/AsyncTask.html) and then dismiss it in [onPostExecute](http://developer.android.com/reference/android/os/AsyncTask.html#onPostExecute%28Result%29).

**Comment by SimonKinds** [comment]
I did some research, and it seems that [Dialog.setCancelable](http://developer.android.com/reference/android/app/Dialog.html#setCancelable%28boolean%29) only affects back-presses (this does not work on my device). If you want to make sure the user can not cancel the dialog by pressing outside the dialog you should use [Dialog.setCanceledOnTouchOutside](http://developer.android.com/reference/android/app/Dialog.html#setCanceledOnTouchOutside%28boolean%29) (this does work on my device).

So simply build the MaterialDialog with the builder and then call setCanceledOnTouchOutside on the created Dialog.

**Comment by afollestad** [comment]
@euri16 updated your comment to use correct GitHub code formatting and syntax highlighting (you don't use HTML tags).

I've added the solution by @SimonKinds, it will be available in the next release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
