### ISSUE TITLE
Is it possible to create a dialog with 2 input edit texts?

### ISSUE THREAD

**Issue by boggogo** [afollestad/material-dialogs#594]
I was looking for a way how to create a dialog with 2 input edit texts using this library,but I could not find such option. Maybe I did not see it, but if it is available could you show me how I can do that please?

**Comment by afollestad** [comment]
With a custom view

**Comment by boggogo** [comment]
By custom do you mean extending one of the dialogs of this library ? :)

**Comment by afollestad** [comment]
No, custom views are a feature like they are for stock dialogs. See the
README on the front page of this library.

On Fri, Jun 26, 2015, 11:56 AM Georgi Koemdzhiev <notifications@github.com>
wrote:

> By custom do you mean extending one of the dialogs of this library ? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/594#issuecomment-115758577>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by boggogo** [comment]
Got it, thank you very much for your time. Keep up the good work :+1:
