### ISSUE TITLE
Too many nullables

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#595]
I think the library uses too many nullables. For example, here I'm explicitly setting a custom view. So it is not null. Of cause it only returns not null if I did set a custom view. So the way it works now I have to suppress many lint warnings which makes the code unreadable.

![bildschirmfoto 2015-06-29 um 11 11 14](https://cloud.githubusercontent.com/assets/743462/8404739/b77855c6-1e4f-11e5-9330-d3d22d665b3e.png)

**Comment by hzsweers** [comment]
It forces you to code defensively, and the library can't guarantee that the result won't be null if there's any case where it does.

**Comment by afollestad** [comment]
Yeah, the usage there is valid.
