### ISSUE TITLE
Invisible EditText in MaterialEditTextPreference

### ISSUE THREAD

**Issue by Remasky** [afollestad/material-dialogs#596]
I have a MaterialEditTextPreference in PreferenceFragment. But edittext is invisible and instead of that shows white textview with content from android:title.

MaterialListViewPreference works very well. 

Does anyone know what is wrong with that?

![2015_06_30_09 22 57](https://cloud.githubusercontent.com/assets/6693497/8425872/b435f2c2-1f0a-11e5-9710-7f6ee5c0cc6f.png)

I forgot to add. Keyboard is showing on automatically after open preference. It looks like this. Tried on Samsung Galaxy S5 mini - API19 and LG P880 - API15.

**Comment by Remasky** [comment]
updated

**Comment by hzsweers** [comment]
@Remasky what happens if you change `textColorPrimary` attributes in your themes/styles?

**Comment by Remasky** [comment]
@hzsweers nothing... the same colors as above

**Comment by hzsweers** [comment]
Ah, then I'm out of ideas again :/

**Comment by Remasky** [comment]
Do you think it can be caused by PreferenceFragment?

**Comment by hzsweers** [comment]
Doubtful, that kind of issue sounds like theme/style problems.

**Comment by Remasky** [comment]
I delete android:textColor and color of "Imię" was also changed. Look at this.

<style name="MainTheme" parent="@android:style/Theme.Holo.Light">
  <item name="android:textColor">@color/white</item>  // DELETED AND COLOR CHANGED TO BLACK
  ..
</style>

<style name="MyPreferenceTheme" parent="MainTheme">
  <item name="android:windowBackground">@drawable/bg</item>
  <item name="android:textColor">@color/selectors</item>
  <item name="android:textColorPrimary">#ffff0000</item>
  ...
</style>

**Comment by Remasky** [comment]
Ok, I found it. Theme.Holo.Light was messing up. I changed to "Theme.AppCompat.Light.NoActionBar" and add Toolbar from AppCompatActivity - everything seems ok. Thanks for advice about "themes/styles".
