### ISSUE TITLE
How to Dismiss Progress Dialog? 

### ISSUE THREAD

**Issue by mtwn105** [afollestad/material-dialogs#597]
@afollestad How to dismiss the Material Dialog's Progress Dialog when operation is completed. Thanks.

**Comment by afollestad** [comment]
With the `dismiss()` method. Same as a stock Dialog.

**Comment by afollestad** [comment]
Look at the README file and sample project.

**Comment by mtwn105** [comment]
But there is no such method. I am showing dialog.show() & after operation is completed in background, I want dismiss the dialog. But there is no dialog.dismiss() method

**Comment by afollestad** [comment]
There is, MaterialDialog inherits android.app.Dialog. The Builder instance
is not a dialog itself.

On Mon, Jun 29, 2015, 5:34 PM mtwn105 <notifications@github.com> wrote:

> But there is no such method. I am showing dialog.show() & after operation
> is completed in background, I want dismiss the dialog. But there is no
> dialog.dismiss() method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/597#issuecomment-116868308>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment]
Again, look at the README file or sample project. That's what it's for.

On Mon, Jun 29, 2015, 6:00 PM Aidan Follestad <drummer.aidan@gmail.com>
wrote:

> There is, MaterialDialog inherits android.app.Dialog. The Builder instance
> is not a dialog itself.
>
> On Mon, Jun 29, 2015, 5:34 PM mtwn105 <notifications@github.com> wrote:
>
>> But there is no such method. I am showing dialog.show() & after operation
>> is completed in background, I want dismiss the dialog. But there is no
>> dialog.dismiss() method
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/afollestad/material-dialogs/issues/597#issuecomment-116868308>
>> .
>>
> --
>
> Best regards,
>
> Aidan Follestad,
> http://aidanfollestad.com
> 651-528-1662
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by mtwn105** [comment]
Ok I am sending the code.

//operation started
MaterialDialog.Builder dialog new MaterialDialog.Builder(MainActivity.this);
dialog.title="Operation Started";
dialog .content="Please Wait...";
dialog .progress(true,0);
dialog .cancelable(false);
dialog .show();

//After some time when
//Operation Completed

dialog.title="Operation Completed";
dialog.neutraltext="Dismiss";
dialog.show();

But when I click Dismiss, the second dialog dismisses but first one can't.

**Comment by afollestad** [comment]
```java
MaterialDialog.Builder builder = new MaterialDialog.Builder(this)
    .title(R.string.title)
    .content(R.string.content)
    .progress(true, 0)
    .cancelable(false);
MaterialDialog dialog = builder.show();
// do work
dialog.dismiss();
```

**Comment by afollestad** [comment]
`MaterialDialog.Builder` is not a dialog, `build()` and `show()` of `MaterialDialog.Builder` return a `MaterialDialog`. This is how `AlertDialog.Builder` from the stock framework works too.

**Comment by mtwn105** [comment]
Oh is it so simple. Thanks a lot for your time. Excellent libraries from
you.
