### ISSUE TITLE
Clear Multi Choice List Dialog selection

### ISSUE THREAD

**Issue by Servus7** [afollestad/material-dialogs#604]
Im using following code to clear the selection of a Multi Choice List Dialog:
```Java
@Override
public void onNeutral(MaterialDialog dialog) {
    super.onNeutral(dialog);
    dialog.setSelectedIndices(new Integer[0]);
 }
```
The problem is that with a new choice the colors of the CheckBox no longer match their state (see attached screenshot). Instead, the colors of the previous selection are displayed. If you scroll a CheckBox out of view and in again, everything is like it should be.

![screenshot_2015-07-04-19-03-51](https://cloud.githubusercontent.com/assets/9412633/8508836/43c761a4-2281-11e5-9d99-ba833ebfd5d2.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
