### ISSUE TITLE
Show dialog from service

### ISSUE THREAD

**Issue by gingafazi** [afollestad/material-dialogs#606]
if we want to show dialog from service, we must set the dialog with:

```java
dialog.getWindow().setType(WindowManager.LayoutParams.TYPE_SYSTEM_ALERT);
```

But this can be done only after the dialogue appeared and in fact the dialog crash because the setting must be set before the dialog appears.

Is there a way that I do not know or we can show the system dialog in another way ?

**Comment by gingafazi** [comment]
I have an idea.
Now for setup show/cancel/dismiss listeners we must do this:

```java
.showListener(new DialogInterface.OnShowListener() {
        @Override
        public void onShow(DialogInterface dialog) {
        }
    })
    .cancelListener(new DialogInterface.OnCancelListener() {
        @Override
        public void onCancel(DialogInterface dialog) {
        }
    })
    .dismissListener(new DialogInterface.OnDismissListener() {
        @Override
        public void onDismiss(DialogInterface dialog) {
        }
    })
```
If you add an preShow listener?
Like this:
```java
@Override
        public void onPreShow(DialogInterface dialog) {

        }
```
And now we can set the system dialog like this:
```java
@Override
        public void onPreShow(DialogInterface dialog) {
              dialog.getWindow().setType(WindowManager.LayoutParams.TYPE_SYSTEM_ALERT);
        }
```
What do you think about it?

**Comment by gingafazi** [comment]
I solved the problem.. I modified the library builder in this way:
I have added a boolean variable:
```java
protected boolean systemDialog = false;
```
I have added a function who set the variable like this:
```java
public Builder systemDialog() {
            this.systemDialog = true;
            return this;
        }
```
And finally i have modified the show() function like this:
before:
```java
@UiThread
        public MaterialDialog show() {
            MaterialDialog dialog = build();
            dialog.show();
            return dialog;
        }
```
after:
```java
@UiThread
        public MaterialDialog show() {
            MaterialDialog dialog = build();
            if(systemDialog) dialog.getWindow().setType(WindowManager.LayoutParams.TYPE_SYSTEM_ALERT);
            dialog.show();
            return dialog;
        }
```

**Comment by afollestad** [comment]
Stock AlertDialogs can't be shown from a service either; they're not designed to. But I'll look into the solution you used.

**Comment by afollestad** [comment]
Since a permission is needed (according to http://stackoverflow.com/a/4344760/309644), I don't think it's a good idea to have this as a feature of the library. Those who really need to do this can use that method on the window like you'd have to do with a stock `AlertDialog` anyways.
