### ISSUE TITLE
changing color of progress bar inside dialog

### ISSUE THREAD

**Issue by Obsttube** [afollestad/material-dialogs#607]
I want to change progress bar color in dialog, i use "progressbar.getIndeterminateDrawable()
                .setColorFilter(Color.parseColor("#fcc865"), PorterDuff.Mode.SRC_IN);" for normal progress bar but i want do set color of dialog's bar, can you add it?

**Comment by afollestad** [comment]
Read the README or look at the sample project.

**Comment by Obsttube** [comment]
ok, i've found it :)
