### ISSUE TITLE
Integrate a ViewFlipper in a customerView with GestureDetector

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#609]
Hi,

 I would like to do a MaterialDialog with a ViewFlipper inside. To do this, I need to define a customView (done), but also add a GestureDetector that I will bind with onTouchEvent (that I should override from MaterialDialog) to be able to flip left and right.

![](http://img1.mobile-patterns.com/img/full/1420569635912-2015-01-05%2006.44.47.png)

My issue is about the builder, that I didn't succeed to extends, so I planed to instantiate the Dialog without the builder. However it not having all method available to do so, isn't it ?

Please advise me on : extending Builder | getting the onTouchEvent | defining a customView wo the Builder.

Thanks

**Comment by afollestad** [comment]
This library wasn't designed to allow construction without the Builder.

**Comment by afaucogney** [comment]
@afollestad ok thanks, so how can I do, if I can ? (eg getting the onTouchEvent)

**Comment by afollestad** [comment]
The only thing I can think of is subclassing a View class, and using it inside of your custom view.
