### ISSUE TITLE
ProgressBarDialog is not showing the circle

### ISSUE THREAD

**Issue by chaimleu** [afollestad/material-dialogs#610]
Hi, 
I am using this class and have tried to create ProgressBarDialog with progressIndeterminate circle.
The dialog was opened but there was no Indeterminate circle.
That's is my code:

```java
new MaterialDialog.Builder(this)
                .title(R.string.UserActivity_Login)
                .content(R.string.UserActivity_Login)
                .progress(true, 1)
                .progressIndeterminateStyle(true)
                .show();
```

and the style markup:

```xml
<style name="Theme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/indigo</item>
        <item name="colorPrimaryDark">@color/indigo_dark</item>
        <item name="colorAccent">@color/material_teal_500</item>
</style>
```

Any idea why is it happening?

EDIT: The problem was the `progressIndeterminateStyle(true)` deleted it and it's working now.
You can close this issue;

**Comment by afollestad** [comment]
You can close it yourself, too.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
