### ISSUE TITLE
Indeterminate Progress Dialogs does not occur properly on Android Lollipop

### ISSUE THREAD

**Issue by divanshugarg** [afollestad/material-dialogs#611]
On my Moto G having Android Lollipop, The Indeterminate Progress Dialogs does not occur properly. The circle in the dialog does not rotate indefinitely as it should. Please look into this.

**Comment by afollestad** [comment]
This library was developed on Lollipop, it works fine for me on Lollipop and the M Developer Preview.

**Comment by afollestad** [comment]
Make sure you're using the latest version of the library.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
