### ISSUE TITLE
why pull the latest version then complie ERROR:first() element from an empty List

### ISSUE THREAD

**Issue by colarking** [afollestad/material-dialogs#614]
Error:A problem occurred configuring project ':library'.
Cannot access first() element from an empty List

i had update the SDK and the build tools

**Comment by colarking** [comment]
console :--> gradle assenbleDebug --debug --stacktrace

13:02:46.044 [ERROR] [org.gradle.BuildExceptionReporter] 
13:02:46.045 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:02:46.046 [ERROR] [org.gradle.BuildExceptionReporter] 
13:02:46.110 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
13:02:46.110 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':library'.
13:02:46.110 [ERROR] [org.gradle.BuildExceptionReporter] > Cannot access first() element from an empty List
13:02:46.111 [ERROR] [org.gradle.BuildExceptionReporter] 
13:02:46.111 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
13:02:46.112 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':library'.
13:02:46.112 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
13:02:46.113 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
13:02:46.113 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
13:02:46.113 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
13:02:46.114 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:85)
13:02:46.114 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
13:02:46.114 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
13:02:46.115 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
13:02:46.115 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
13:02:46.115 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
13:02:46.115 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
13:02:46.116 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
13:02:46.116 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
13:02:46.116 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
13:02:46.117 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
13:02:46.117 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
13:02:46.117 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
13:02:46.117 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
13:02:46.118 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
13:02:46.118 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
13:02:46.118 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
13:02:46.119 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
13:02:46.119 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
13:02:46.119 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
13:02:46.119 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
13:02:46.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
13:02:46.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
13:02:46.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
13:02:46.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
13:02:46.121 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
13:02:46.121 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
13:02:46.121 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
13:02:46.121 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty List
13:02:46.122 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.AndroidArtifacts$_javadocJar_closure2.doCall(AndroidArtifacts.groovy:24)
13:02:46.122 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
13:02:46.122 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
13:02:46.122 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
13:02:46.123 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:492)
13:02:46.123 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:874)
13:02:46.123 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.Project$task$6.call(Unknown Source)
13:02:46.123 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.AndroidArtifacts.javadocJar(AndroidArtifacts.groovy:21)
13:02:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.AndroidArtifacts$javadocJar$0.callCurrent(Unknown Source)
13:02:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.AndroidArtifacts.all(AndroidArtifacts.groovy:10)
13:02:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.Artifacts$all.call(Unknown Source)
13:02:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.ReleasePlugin$_attachArtifacts_closure1_closure3_closure4.doCall(ReleasePlugin.groovy:30)
13:02:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
13:02:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:61)
13:02:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.PolymorphicDomainObjectContainerConfigureDelegate._configure(PolymorphicDomainObjectContainerConfigureDelegate.java:46)
13:02:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:73)
13:02:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.ReleasePlugin$_attachArtifacts_closure1_closure3.doCall(ReleasePlugin.groovy:25)
13:02:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
13:02:46.218 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
13:02:46.219 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
13:02:46.219 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:68)
13:02:46.219 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
13:02:46.220 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
13:02:46.220 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.publish.internal.DefaultPublishingExtension.publications(DefaultPublishingExtension.java:48)
13:02:46.220 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.publish.internal.DefaultPublishingExtension_Decorated.publications(Unknown Source)
13:02:46.221 [ERROR] [org.gradle.BuildExceptionReporter]        at com.novoda.gradle.release.ReleasePlugin$_attachArtifacts_closure1.doCall(ReleasePlugin.groovy:24)
13:02:46.221 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
13:02:46.221 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
13:02:46.221 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureNow(ExtensionsStorage.java:183)
13:02:46.222 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.get(ExtensionsStorage.java:162)
13:02:46.222 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage.getAsMap(ExtensionsStorage.java:50)
13:02:46.222 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.getProperties(DefaultConvention.java:168)
13:02:46.222 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.getProperties(CompositeDynamicObject.java:130)
13:02:46.223 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject$4.create(AbstractProject.java:743)
13:02:46.223 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject$4.create(AbstractProject.java:741)
13:02:46.223 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:166)
13:02:46.224 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.getProperties(AbstractProject.java:741)
13:02:46.224 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.TaskManager.createPreprocessResourcesTask(TaskManager.java:576)
13:02:46.224 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.LibraryTaskManager$7.call(LibraryTaskManager.java:203)
13:02:46.224 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.LibraryTaskManager$7.call(LibraryTaskManager.java:200)
13:02:46.224 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:02:46.225 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.LibraryTaskManager.createTasksForVariantData(LibraryTaskManager.java:199)
13:02:46.225 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:433)
13:02:46.225 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager$2.call(VariantManager.java:277)
13:02:46.225 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager$2.call(VariantManager.java:274)
13:02:46.225 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:02:46.226 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.Recorder$record.call(Unknown Source)
13:02:46.226 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.Recorder$record.call(Unknown Source)
13:02:46.226 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:69)
13:02:46.226 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:273)
13:02:46.226 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy:481)
13:02:46.227 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy)
13:02:46.227 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
13:02:46.227 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:02:46.227 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
13:02:46.227 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:480)
13:02:46.228 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:413)
13:02:46.228 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
13:02:46.228 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
13:02:46.228 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:02:46.229 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
13:02:46.229 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13.doCall(BasePlugin.groovy:412)
13:02:46.229 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
13:02:46.229 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
13:02:46.229 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter]        ... 30 more
13:02:46.230 [ERROR] [org.gradle.BuildExceptionReporter] 
13:02:46.231 [LIFECYCLE] [org.gradle.BuildResultLogger] 
13:02:46.231 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
13:02:46.231 [LIFECYCLE] [org.gradle.BuildResultLogger] 
13:02:46.232 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 14.469 secs
13:02:46.255 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).

**Comment by afollestad** [comment]
This is an issue with the bintray-release plugin.

**Comment by nguyenvancuongit** [comment]
Error:A problem occurred configuring project ':library'.
Cannot access first() element from an empty List

@colarking sorry when troulbe you, how did you do to resolved this? thanks you

**Comment by afollestad** [comment]
@nguyenvancuongit I didn't, I'm waiting on version 3.3 of the Bintray Release plugin; @hzsweers made a pull request to fix the issue.
