### ISSUE TITLE
How to get EditText input

### ISSUE THREAD

**Issue by Will42** [afollestad/material-dialogs#616]
Hey! Your Material Dialog is working awesome, but I just need a little help. I am trying to get the text from my EditText within a custom layout I use for the dialog, butI keep getting the following error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
            at owensetiawan.friendlymatch.todolist.MainActivity$1.onPositive(MainActivity.java:94)
            at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:321)
This is my dialog code:
public void addNote(View view) {
        EditText editTitle, editContent;

        taskTitleText = "";
        taskContentText = "";
        // Creates dialog for creating a new task
        MaterialDialog dialog = new MaterialDialog.Builder(this)
                .title("Add Note")
                .customView(R.layout.activity_add_screen, false)
                .positiveText("Create")
                .negativeText("Can't remember")
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {

                        // Creates a new Info item for the note
                        Info dialogInfo = new Info();
                        dialogInfo.setTitle(taskTitleText);
                        dialogInfo.setContent(taskContentText);

                        tasks.add(dialogInfo);
                        adapter.notifyDataSetChanged();
                    }
                })
                .build();

        editTitle = (EditText)dialog.getCustomView().findViewById(R.id.noteTitle);
        editContent = (EditText)dialog.getCustomView().findViewById(R.id.noteContent);

        editTitle.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                taskTitleText = s.toString();
                positiveButton.setEnabled(taskTitleText.trim().length() > 0);
            }

            @Override
            public void afterTextChanged(Editable s) {
            }
        });
        editContent.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                taskContentText = s.toString();
                positiveButton.setEnabled(true);
            }

            @Override
            public void afterTextChanged(Editable s) {
            }
        });

        // To access your database, instantiate your subclass of SQLiteOpenHelper:
        TaskDBHelper dbHelper = new TaskDBHelper(MainActivity.this);
        // Gets the data repository in write mode
        SQLiteDatabase db = dbHelper.getWritableDatabase();
        ContentValues contentValues = new ContentValues();
        contentValues.put(TaskContract.Columns.NOTE_TITLE, taskTitleText);
        contentValues.put(TaskContract.Columns.NOTE_CONTENT, taskContentText);

        db.insertWithOnConflict(TaskContract.TABLE, null, contentValues, SQLiteDatabase.CONFLICT_IGNORE);

        updateUI();
        dialog.show();
        positiveButton.setEnabled(false);
    }
Any help would be awesome!

**Comment by afollestad** [comment]
Why are you created a Dialog Into instance?

**Comment by afollestad** [comment]
Those methods should be called on the dialog passed as a parameter to the callback, not something you just created.
