### ISSUE TITLE
Single Choice Dialog with wrong coloring when selecting items

### ISSUE THREAD

**Issue by richardaum** [afollestad/material-dialogs#617]
Steps: 
1. Create a Single Choice Dialog with three items. 
2. Select the first one. 
3. After select another one. 
4. Radio stroke color is wrong. Stroke color must be gray (or default color for disabled options).

![](mtp://[usb:003,005]/Interno/Pictures/Screenshots/Screenshot_2015-07-13-13-39-15.png)
![](mtp://[usb:003,005]/Interno/Pictures/Screenshots/Screenshot_2015-07-13-13-39-19.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/564
