### ISSUE TITLE
The ability to provide a custom StateListDrawable for action buttons

### ISSUE THREAD

**Issue by AzureusSme** [afollestad/material-dialogs#618]
[To be specified]

**Comment by afollestad** [comment]
This isn't very specific

**Comment by afollestad** [comment]
With the code that hasn't been published as a release, you can already use a state list for the color of the action buttons. Not sure where you would *need* state list drawables.

**Comment by AzureusSme** [comment]
I mean, provide to the Builder a StateListDrawable programmatically, not from res.

Like:

StateListDrawable states = new StateListDrawable();

    states.addState(new int[] {android.R.attr.stateNotNeeded}, R.drawable.btn_off); 
    states.addState(new int[] {android.R.attr.state_pressed, android.R.attr.state_enabled},R.drawable.btn_off);
    states.addState(new int[] {android.R.attr.state_focused, android.R.attr.state_enabled},R.drawable.btn_on);
    states.addState(new int[] {android.R.attr.state_enabled}, R.drawable.btn_on);

Then:

MaterialDialog D = new MaterialDialog.Builder(A)
                              [...]
                              .btnSelector(states, DialogAction.POSITIVE)
                              [...].build();

Add a btnSelector(StateListDrawable state, DialogAction which) method.

**Comment by afollestad** [comment]
Updated your comment to format the code and provide syntax highlighting correctly.

-------

The library used to allow `Drawable` instances to be passed there, but there are weird issues that come out of it. You can try it if you want (using a fork of the library).
