### ISSUE TITLE
I cannot get version 0.7.7.0 from jCenter

### ISSUE THREAD

**Issue by jijunpeng** [afollestad/material-dialogs#619]
I cannot get version 0.7.7.0 from jCenter, but the library's version is 0.7.7.0

**Comment by AzureusSme** [comment]
Not yet uploaded, i think.

![captura de pantalla 93](https://cloud.githubusercontent.com/assets/8404410/8670002/b02a621a-29de-11e5-933e-5c69a3dabc2a.png)

**Comment by afollestad** [comment]
It hasn't been released

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
