### ISSUE TITLE
Input custom validation is overridden by empty/max len checks

### ISSUE THREAD

**Issue by SpaceJoe** [afollestad/material-dialogs#620]
Hi,
if I enable custom validation AND empty/max len check on input element the result of my callback (i.e. disable positive action) is overridden.
The lib probably should && the current status or invoke the callback, when alwaysCallInputCallback is set, after empty/max len checks.
The workaround to perform empty/max len check in the callback works but the current len/max len text and coloring is lost.
Note that invalidateInputMinMaxIndicator gets the result of empty check and && with it.

Thanks

**Comment by afollestad** [comment]
This has alreaey been fixed but not published.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
