### ISSUE TITLE
MaterialDialogPreference not working correctly

### ISSUE THREAD

**Issue by xsorifc28** [afollestad/material-dialogs#621]
Using `public class CustomDialogPreference extends MaterialDialogPreference` in a `<PreferenceScreen>`  like: 

    <com.app.package.CustomDialogPreference  
            android:dialogMessage="@string/preference_dialog_message_clear_likes"
            android:dialogTitle="@string/preference_dialog_title_clear_likes"
            android:key="@string/pref_key_clearLikes"
            android:negativeButtonText="@android:string/cancel"
            android:positiveButtonText="@android:string/ok"
            android:summary="@string/preference_dialog_pref_summary_clear_likes"
            android:title="@string/preference_dialog_title_clear_likes" />

shows the dialog, however, does not return true/false or set the preference value.

Using `public class CustomDialogPreference extends DialogPreference` works fine, I can see a toast that shows if OK or Cancel was selected.

**Comment by xsorifc28** [comment]
<com.afollestad.materialdialogs.prefs.MaterialDialogPreference
    ...

also does not work.

**Comment by afollestad** [comment]
If you look at the stock `DialogPreference` source, you'd see it also doesn't save any values.

**Comment by xsorifc28** [comment]
The issue with `DialogPreference` can be fixed by: 

    public class CustomDialogPreference extends DialogPreference {

        public CustomDialogPreference(Context context, AttributeSet attrs) {
            super(context, attrs);
        }

        @Override
        protected void onDialogClosed(boolean positiveResult) {
            super.onDialogClosed(positiveResult);
            persistBoolean(positiveResult);
        }
    }

When I extended `MaterialDialogPreference`, the onDilalogClosed wouldn't get called prior to v0.7.7

However, 

    public class CustomDialogPreference extends MaterialDialogPreference {

        public CustomDialogPreference(Context context, AttributeSet attrs) {
            super(context, attrs);
        }

        @Override
        protected void onDialogClosed(boolean positiveResult) {
            super.onDialogClosed(positiveResult);
            persistBoolean(positiveResult);
        }
    }

with the XML preference 
    <com.afollestad.materialdialogs.prefs.MaterialDialogPreference
    ...
    />

works just fine.

**Comment by afollestad** [comment]
Updated your comment for syntax highlighting; indentation doesn't do that.

**Comment by afollestad** [comment]
However, I didn't intend to modify the behavior of `DialogPreference` in this library.

The stock `DialogPreference` doesn't do that, so this library won't either. http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/preference/DialogPreference.java#401
