### ISSUE TITLE
MaterialListPreference save value 2x. Second value is wrong.

### ISSUE THREAD

**Issue by ormoru** [afollestad/material-dialogs#622]
I have this xml code

<com.afollestad.materialdialogs.prefs.MaterialListPreference
        android:key="DateFormatShow"
        android:title="@string/pref_date_format_show"
        android:defaultValue="dd.MM. yyyy HH:mm"
        android:entries="@array/date_format"
        android:entryValues="@array/date_format"/>

I try android:persistent="true", android:persistent="false" and without th

If I use it, always I see first value from entries. In debug mode I see, that is called function setValue with right value as parameter. Preference is right stored and I see right selected item. If debug continue, I see that is anew called function setValue. This time always with value 0. And this value is saved into preferences and I see first item from entries always. In real life this is very quickly, therefore I think that it does not work. Second called overwrite my preference with 0.

Question is:
Why is called setValue a second time?

**Comment by afollestad** [comment]
If you follow the stack trace you can see where it's being invoked from. This is now fixed for the next release, thanks for reporting it.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.7.0
