### ISSUE TITLE
Basic listview with icon

### ISSUE THREAD

**Issue by anticafe** [afollestad/material-dialogs#626]
![image](https://cloud.githubusercontent.com/assets/340836/8888763/5aeae13e-32e5-11e5-89f8-bcb2ad4ea29e.png)

I know it's easy to create similar dialog, with icon on the left, and text on the right. But, could you please create such built-in dialog?

**Comment by afollestad** [comment]
See the README and sampl3 project. You need to use a custom adapter. Or a simple list dialog.
