### ISSUE TITLE
Request for setting canceledOnTouchOutside property regardless of cancelable property

### ISSUE THREAD

**Issue by Gerard-Gutierrez** [afollestad/material-dialogs#630]
I'm trying to add a cancelable Dialog in my app, I want to cancel it touching the back button but avoid cancelling through touching outside the Dialog.

Is it possible?
Thank you for this library, it's useful.

**Comment by afollestad** [comment]
Set it on the `Dialog` instance. `MaterialDialog` inherits `android.app.Dialog`. It's no different.
