### ISSUE TITLE
please add .setCancelable(false); to dialogs

### ISSUE THREAD

**Issue by Obsttube** [afollestad/material-dialogs#631]
as here: http://stackoverflow.com/questions/20038229/eula-can-be-skipped-by-pressing-back-button-android
I have problem in EULA. user can use back button and not accept EULA.
The normal dialog has this option, but yours not.

**Comment by afollestad** [comment]
```java
MaterialDialog dialog = // ...
dialog.setCancelable(false);
```

**Comment by afollestad** [comment]
`MaterialDialog` is a `Dialog`, there's nothing you can do to a stock Dialog that you can't do with this library.
