### ISSUE TITLE
ClassCastException in MaterialDialog.<init>

### ISSUE THREAD

**Issue by ireneduke** [afollestad/material-dialogs#632]
I got this crash report on a SAMSUNG SM-G900F device running Android 5.0:

```shell
java.lang.ClassCastException: com.afollestad.materialdialogs.internal.MDRootLayout cannot be cast to com.afollestad.materialdialogs.internal.MDRootLayout
Exception Backtrace:
1	com.afollestad.materialdialogs.MaterialDialog.<init>	MaterialDialog.java, line 86
2	com.afollestad.materialdialogs.MaterialDialog$Builder.build	MaterialDialog.java, line 1101
3	com.afollestad.materialdialogs.MaterialDialog$Builder.show	MaterialDialog.java, line 1106
4	com.package.package.ui.common.ErrorDialogFragment.onCreateDialog	ErrorDialogFragment.java, line 54
5	android.support.v4.app.DialogFragment.getLayoutInflater	DialogFragment.java, line 308
6	android.support.v4.app.FragmentManagerImpl.moveToState	FragmentManager.java, line 955
7	android.support.v4.app.FragmentManagerImpl.moveToState	FragmentManager.java, line 1138
8	android.support.v4.app.BackStackRecord.run	BackStackRecord.java, line 740
9	android.support.v4.app.FragmentManagerImpl.execPendingActions	FragmentManager.java, line 1501
10	android.support.v4.app.FragmentManagerImpl$1.run	FragmentManager.java, line 458
11	android.os.Handler.handleCallback	Handler.java, line 739
12	android.os.Handler.dispatchMessage	Handler.java, line 95
13	android.os.Looper.loop	Looper.java, line 145
14	android.app.ActivityThread.main	ActivityThread.java, line 5834
15	java.lang.reflect.Method.invoke	
16	java.lang.reflect.Method.invoke	Method.java, line 372
17	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	ZygoteInit.java, line 1388
18	com.android.internal.os.ZygoteInit.main	ZygoteInit.java, line 1183
```

I'm not sure what's causing it, but looking at the code it seems like that cast may not be necessary. Could it be removed? I'm happy to submit a pull request if it's helpful.

**Comment by afollestad** [comment]
Looks like it could be another infamous Samsung issue.

Line 1101 and 1106 do not exist in `MaterialDialog.java`, and errors do not occur in Java when you cast a class to itself.

**Comment by afollestad** [comment]
The only other thing it could be is you using a very old version of the library before dialog initialization code was moved to a different class. There's only 578 lines in `MaterialDialog.java`.

**Comment by ireneduke** [comment]
Yeah, sorry, I'm using version 0.7.5.1 of this library. Would this be fixed in the latest version?

**Comment by afollestad** [comment]
Not 100% sure, but that log wouldn't apply to any version above 0.7.6.0; the latest is 0.7.7.0.

Let me know if there's a new log for the same issue.

**Comment by ireneduke** [comment]
Seems like this cast is still in the constructor in the latest version of the library, so it's likely still an issue. I'll update the library version for now, but I won't be able to provide another stack trace unless I get new crash reports from users.

**Comment by afollestad** [comment]
You mean here? https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L90

This code runs on multiple product apps of mine that have over 100,000 downloads; I've never had any issues with it.

**Comment by afollestad** [comment]
Sorry, production*

**Comment by DIYwei** [comment]
I also meet this problem with the version "0.8.5.9".According to the infos from user,it happens on the device of SM-G900F and SM-G900M with 5.0 os.Can this issue have a better solution?Thank you.
Fatal Exception: java.lang.ClassCastException
com.afollestad.materialdialogs.internal.MDRootLayout cannot be cast to com.afollestad.materialdialogs.internal.MDRootLayout
com.afollestad.materialdialogs.MaterialDialog. (MaterialDialog.java:95)
com.afollestad.materialdialogs.MaterialDialog$Builder.build (MaterialDialog.java:1335)
com.arcsoft.perfect365.common.themes.dialog.DialogManager.createGetDialog (DialogManager.java:239)

**Comment by afollestad** [comment]
Sorry, there's nothing I can do. Casting an object to what it already is does not cause an error.

There is something wrong on Samsung's end, which isn't too unusual (it happens a lot).

**Comment by DIYwei** [comment]
Yes，the amount of the issue is not a lot.So it doesn't happen every time.And the number of affected users is also acceptable. Thank you for replying.
