### ISSUE TITLE
Failed to resolve:  compile 'com.afollestad:material-dialogs:0.4.3'

### ISSUE THREAD

**Issue by nishant-git** [afollestad/material-dialogs#635]
you removed SimpleCallback and Callback interface !!!!

**Comment by afollestad** [comment]
You're about 4 months behind.

**Comment by nishant-git** [comment]
I migrated one of my old project and builted on new pc / new android studio(without cached) which caused me this error. Its bad practices to deleting things rather than deprecating it.  
Thanks.

**Comment by Anth06ny** [comment]
+1 with nishant-git
I have project with Tag and versionning.
I have to change something an old version of my project and your version 0.7.8.+ wis remove.
The probleme is your next version 0.8.+ need v23

**Comment by tbruyelle** [comment]
> The probleme is your next version 0.8.+ need v23

Fuck yeah, you make me loose a lot of time by deleting old version of your library. Do you know 23 is a version you specifically may not want to use because it requires runtime permissions compatibility.

**Comment by Anth06ny** [comment]
+1

**Comment by tbruyelle** [comment]
Found a version that don't rely on 23 at jcenter 

https://bintray.com/drummer-aidan/maven/material-dialogs/0.7.9.1/view#files/com/afollestad/material-dialogs/0.7.9.1

Be quick before the guy deletes it :P

**Comment by afollestad** [comment]
@tbruyelle do you realize I use JitPack.io now? You can reference any commit in the entire commit history from Gradle, not just version numbers. You could reference specific commits for old versions. 

Although old versions are buggy.

**Comment by afollestad** [comment]
And this API mentioned above was deprecated for quite some time, it was finally removed with a major release. Which is normal practice.

**Comment by tbruyelle** [comment]
Improving and deprecating code doesn't hurt me of course, but you shouldn't remove old versions of your library from the maven repos, even if they're buggy.
 
Sometimes you just want to apply a small fix to an old project, and when you have to upgrade a significant part of the code because of a missing third part library, it's really a bad surprise.

**Comment by afollestad** [comment]
That's not why they were removed. Bintray doesn't give unlimited storage space for free. I'm no longer using them anyways.

**Comment by afollestad** [comment]
Anyone having issues with the JitPack depdendency, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
