### ISSUE TITLE
Proposal: Split library into core and commons modules

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#642]
Similar to how we do our [BottomSheet](https://github.com/flipboard/bottomsheet) library and the direction that RxAndroid is taking now. 

Since the library has grown a fair bit with a lot of extra resources and custom implementations, I think it would make sense to split the library into `core` and `commons` modules. `Core` would just be the main dialog code and necessary components for the core features, and `commons` would include the custom ready-out-of-the-box implementations people can use if they want (prefs, progress, color picker, etc). 

This could then also open the door for others to contribute their own custom implementations to commons if they want, without the ambiguity of wondering if it really belongs in the library.

Thoughts?

**Comment by AzureusSme** [comment]
+1

**Comment by afollestad** [comment]
I would assume this would require some heavy API changes, moving methods from the current `Builder` to their own classes.

**Comment by hzsweers** [comment]
Possibly. Give me a day or two and I'll try to put together a more structure proposal of what would go where.

**Comment by Rainer-Lang** [comment]
Sounds very interesting.

**Comment by hzsweers** [comment]
Sorry late on this, completely forgot :/ 

Here's what I propose:

Commons:
* entire prefs package
* entire progress package
* entire simplelist package
* ColorChooserDialog

Core:
* everything else
  * Move ThemeSingleton to internal package

This would include proper resource separation as well. The sample app would obviously depend on both, and the commons module would obviously depend on the core module

**Comment by afollestad** [comment]
@hzsweers the current repo code has been updated to contain `core` and `commons` modules.

The v7 prefs stuff will be a bit more complicated since they are very, very different from stock preferences. There's a compat PreferenceManager that handles dialogs, rather than the dialogs being shown from within the preference classes themselves. 

ThemeSingleton needs to stay public, I use it in a few of my apps.

**Comment by afollestad** [comment]
Oh you meant the package called `internal`, good idea.

**Comment by afollestad** [comment]
The progress package however won't be able to be easily moved, though. The layouts and everything are deeply integrated into `MaterialDialog` and `DialogInit`. It's not worth moving into new classes, and it's very commonly used among the people who use it.

**Comment by hzsweers** [comment]
Fair enough

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
