### ISSUE TITLE
Optional Icons in ListPreferences?

### ISSUE THREAD

**Issue by Tomblarom** [afollestad/material-dialogs#647]
Would it be possible to make icons optional addable?

    <com.afollestad.materialdialogs.prefs.MaterialListPreference
            android:entries="@array/preference_values"
            android:entryValues="@array/preference_values"
    -->     android:entryIcons="@array/preference_icon"
            android:key="unused_key01"
            android:layout="@layout/preference_custom"
            android:persistent="true"
            android:summary="@string/list_pref_desc"
            android:title="@string/list_pref_title" />

**Comment by afollestad** [comment]
It'd be easier to make a subclass of `MaterialListPreference` and use a custom adapter.

The prefix wouldn't be `android:` either, it would be a custom prefix.
