### ISSUE TITLE
readability of single coice lists with long texts

### ISSUE THREAD

**Issue by NeverGivinUp** [afollestad/material-dialogs#648]
I need to display a single choice list with 5 items. The text of the items is rather long -- 4 to 7 lines on my Motorola Moto E. The radio buttons are vertically centered on the text. (android:gravity="center_vertical" of the radio buttons in res/layout/md_listitem_singlechoice.xml). As a result  it is very hard for the user to understand where one item begins and the next one ends.

It would be a great help, if I could configure the gravity or if it was TOP by default.

**Comment by afollestad** [comment]
This doesn't sound like it's really related to this library, as much as trying to do too much in a dialog.

You could use a custom list adapter that modifies text size and gravity, though.

**Comment by NeverGivinUp** [comment]
Hey Aidan,

Thanks for looking at this. I could do this using a custom list adapter and a custom view, but it would be so much easier for me if you'd put ```android:gravity="top" ``` instead of ```android:gravity="center_vertical"``` on the radio buttons in res/layout/md_listitem_singlechoice.xml. I don't think there would be an impact on existing views, which have only one line of text per item.

Why do you think I'm trying to do too much in a dialog. What option would you recommend?

Thanks,
Navid

**Comment by afollestad** [comment]
The current gravity is center_vertical because that's what stock dialogs use, and that's what the Material guidelines specify (which is the purpose of this library).

If items are too long for a dialog, you could put them in a basic Activity that displays a list and uses Activity results.
