### ISSUE TITLE
java.lang.IllegalArgumentException:

### ISSUE THREAD

**Issue by vipulasri** [afollestad/material-dialogs#649]
I am getting this error everytime.

    java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{10dfb84a V.E..... R....... 0,0-683,573} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:386)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:312)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
       at android.app.Dialog.dismissDialog(Dialog.java:341)
       at android.app.Dialog$1.run(Dialog.java:120)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by afollestad** [comment]
Look through the 4 or 5 duplicate issues.

**Comment by vipulasri** [comment]
i am unable to find the duplicate one's help me find one

**Comment by afollestad** [comment]
This is one of a few: https://github.com/afollestad/material-dialogs/issues/393

That error has nothing to do with this library itself, that's a general Android error that means your dialog is not attached to a valid window (Activity).

**Comment by vipulasri** [comment]
Thanxx, but how do i dismiss a dialog with following code : 

    MaterialDialog.Builder builder = new MaterialDialog.Builder(getActivity());
                builder.content("Login");
                builder.positiveText("Ok");
                builder.callback(new MaterialDialog.ButtonCallback() {
                @Override
                public void onPositive(MaterialDialog dialog) {
                });
                builder.show();

**Comment by afollestad** [comment]
Read the documentation.

These questions are related to this library, it works the same way an `AlertDialog` and `AlertDialog.Builder `work.

**Comment by afollestad** [comment]
Read the documentation.

These questions aren't related to this library, it works the same way an `AlertDialog` and `AlertDialog.Builder `work.

**Comment by vipulasri** [comment]
I modified my code according to native <code>AlertDialog</code> and also implemented <code>@Override
    public void onPause() {

        if ((dialog != null) && dialog.isShowing())
            dialog.dismiss();
        dialog = null;

        super.onPause();
    }</code> 

still i am getting this error.

**Comment by afollestad** [comment]
```java
MaterialDialog.Builder builder = // ...
MaterialDialog dialog = builder.build();
dialog.show();
dialog.dismiss();
```

Or

```java
MaterialDialog.Builder builder = // ...
MaterialDialog dialog = builder.show();
dialog.dismiss();
```

**Comment by vipulasri** [comment]
i am doing the same thing. still this error is reoccurring.

**Comment by afollestad** [comment]
Like I've said above, these aren't related to this library. 

You should search the error on Google, it's a pretty common issue.

**Comment by vipulasri** [comment]
i have searched google for it and tried every possible solution. still not able to resolve this issue. Thank you anyways.

**Comment by afollestad** [comment]
The error means the Activity you're showing the dialog in is not open. E.g. after `onPause()` or before `onCreate()`.
