### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by taherhek** [afollestad/material-dialogs#652]
I use RTL direction and I need to use dialog box with gravity of right, however there isn't such an option in your GravityEnum. Also it does not contain CENTER_HORIZONTAL gravity which you've used in your demo code (https://github.com/afollestad/material-dialogs#gravity) .
So how is it possible to change the gravity to right?

**Comment by afollestad** [comment]
Are you not familiar with how gravity works on Android Jellybean and above?

Left is replaced with start, right is replaced with end. I updated the README, that was a typo.

**Comment by afollestad** [comment]
On RTL devices, right and left get flipped around automatically. Start becomes right instead of left, and end becomes left instead of right.
