### ISSUE TITLE
Preference Dialogs with the new v7 Support lib

### ISSUE THREAD

**Issue by PaulWoitaschek** [afollestad/material-dialogs#655]
I suggest to add preferences (like MaterialListPreference) that extend from ````android.support.v7.preference.ListPreference```` instead of ````android.preference.ListPreference```` so the library works with the latest AppCompat [Preference Library](http://developer.android.com/reference/android/support/v14/preference/PreferenceFragment.html).

**Comment by afollestad** [comment]
I don't really think this will change anything. I'd assume the major difference is that the v7 version uses `AlertDialogCompat` from AppCompat, which will get the same result this library does for the most part.

**Comment by Ph1b** [comment]
Im still not sure what google did there. They added a v14 and a v7 preference class. The way it works now the regular PreferenceFragment does not have themed preferences.
So I guess till now it was not possible to have materialized settings before lollipop. As far as I understood it they added these so the preferences will be themed.
But that way the new PreferenceFragment is a support lib fragment and thus your Preference-Dialogs etc cannot be used.

**Comment by afollestad** [comment]
I'm assuming this requires an additional dependency that would increase the overall size of the library?

**Comment by afollestad** [comment]
I can't seem to find any related imports.

**Comment by Ph1b** [comment]
Well, you have the [v7](http://developer.android.com/tools/support-library/features.html#v7-preference) and the [v14](http://developer.android.com/tools/support-library/features.html#v14-preference).

There is a [v14 PreferenceFragment](http://developer.android.com/reference/android/support/v14/preference/PreferenceFragment.html)
and a [v7 PreferenceFragmentCompat](http://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat.html).
Of cause this will increase the library size, but without these packages there won't be themed preferences on any app if I understood it correctly.

**Comment by afollestad** [comment]
Well Material Dialogs uses its own dialogs, pulling theme attributes on its own. I think support preferences would just being doing what this library already does.

**Comment by Ph1b** [comment]
But the PreferenceFragmentCompat is a appcompat fragment. This I cannot use it as I use your preference dialog classes.

Something like this, where I use your classes declared by xml
````        MaterialListPreference themePreference = (MaterialListPreference) findPreference(getString(R.string.pref_key_theme));
`````
Won't be possible as findPreference returns a v7 Preference and not a normal one (like your MaterialListPreference).

**Comment by afollestad** [comment]
Well this will probably have to wait until https://github.com/afollestad/material-dialogs/issues/642 is complete.

I can't include more libraries as dependencies in this one.

**Comment by afollestad** [comment]
So I looked into this a bit more, and it's a bit more complex than changing extended classes (between packages).

The new compat preference classes completely change the way everything is handled. Rather than the preference classes showing their own dialog, a central Preference Manager class is invoked to display dialogs. The preference classes no longer register and unregister themselves from Activity dismissal listeners, the preference manager must do that too. I'm not yet sure if severing the connection to the preference manager (in order to display custom dialogs) is a good idea.

**Comment by afollestad** [comment]
Closing this for now.
