### ISSUE TITLE
Support fragment on dialog?

### ISSUE THREAD

**Issue by mrhuythien** [afollestad/material-dialogs#656]
It's very good if it support fragment in dialog.

**Comment by afollestad** [comment]
Use a custom view.

**Comment by mrhuythien** [comment]
It really a custom view. But i want to replace fragment on custom view. It not posiable.

**Comment by afollestad** [comment]
That's a limitation of dialogs

On Sat, Aug 22, 2015, 12:27 AM mrhuythien <notifications@github.com> wrote:

> It really a custom view. But i want to replace fragment on custom view. It
> not posiable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/656#issuecomment-133636949>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by lancevalour** [comment]
It is possible actually.

You can put a fragment in your custom view.

However, when I set the custom view with a fragment in it, there is a very small dialog below the actual dialog. So every time I press back button to dismiss the dialog, there is a small dialog not dismissed. 

I use AlertDialog with a fragment custom view and it is fine.

Not sure if it is a bug or not.
