### ISSUE TITLE
Animate dialog entry exit

### ISSUE THREAD

**Issue by vhenriques** [afollestad/material-dialogs#660]
How do i add animations to the dialog
example i want to make it slide-in on create and slide out on dismiss

**Comment by afollestad** [comment]
Search StackOverflow

**Comment by vhenriques** [comment]
i did search but didnt find much
sorry tho for the noob question
cheers for the great lib

**Comment by Rainer-Lang** [comment]
@vhenriques Search at github for FlexibleAdapter and then look at class EditItemDialog. There is slide in and out.
