### ISSUE TITLE
Lowercase Button Text

### ISSUE THREAD

**Issue by spaine** [afollestad/material-dialogs#662]
Button text in the dialog like negative, positive buttons is in all caps even though my string are not. Is there a way to change this?

Thanks!

**Comment by afollestad** [comment]
Currently, no. Since the Material design guidelines show capital action buttons, this library forces it. https://www.google.com/design/spec/components/dialogs.html

**Comment by ColacX** [comment]
.myButton {
  text-transform: none;
}
