### ISSUE TITLE
Is there way to set selected Item in List Dialog?

### ISSUE THREAD

**Issue by y2kshane** [afollestad/material-dialogs#663]
I read the read me and sample project ...and most of the issues but i cant find a way to set selected item in normal list dialog(not Single Choice List) . I used setSelectedIndex but it didn't work

  ```java
MaterialDialog pickupFloorDialog;
 pickupFloorDialog.setSelectedIndex(1);
   pickupFloorDialog = new MaterialDialog.Builder(this)
                .items(floors)
                .itemsCallback(new MaterialDialog.ListCallback() {
                    @Override
                    public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                        selectedPickupFloor=which;
                        lblPickupFloorSelector.setText(floors[which]);
                    }
                }).build();
```

**Comment by afollestad** [comment]
That's currently not a function of this library.

**Comment by afollestad** [comment]
If you need to change selector states, you can use a custom adapter to specify custom list item layouts. From there, you can use `getListView()` to modify selector states of list items.
