### ISSUE TITLE
ColorChooserDialog additions

### ISSUE THREAD

**Issue by marbat87** [afollestad/material-dialogs#666]
Hi,

It would be nice having also a "CANCEL" button in ColorChooser dialog, in order to be able to close the dialog without confirming the choosed color.

Also is there a way to localize/customize buttons' text? My phone localization is Italian, but I see buttons with English text.

What do you think about this?
Thanks in advance

**Comment by afollestad** [comment]
You can now manually set labels in version 0.7.9.1
