### ISSUE TITLE
Material Progress Indeterminated not showing progress bar on some android version

### ISSUE THREAD

**Issue by MatteCarra** [afollestad/material-dialogs#667]
Material Progress Indeterminated doesn't show progress bar on some android version like Api 18
![device-2015-08-30-154915](https://cloud.githubusercontent.com/assets/11074527/9567533/2f29d936-4f2f-11e5-84ba-c907470d5e11.png)

**Comment by afollestad** [comment]
This is the second duplicate of this issue. Read open issues. 

https://github.com/afollestad/material-dialogs/issues/636

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
