### ISSUE TITLE
[Feature Request] Ability to set max-height of scrollview wrapper for customView

### ISSUE THREAD

**Issue by tigerhawkvok** [afollestad/material-dialogs#669]
What I'd picture is something like:

```java
MaterialDialog foo = new MaterialDialog.Builder()
  .customView(R.id.customViewResource, true)
  .maxCustomViewHeight(INT_OR_DOUBLE) // Double as percent of viewport (eg, 0.5), int as dp
  .show();
```

My scenario is I have a very tall custom view to create new users, and I'd like it to be sized so that when the keyboard shows, the whole dialog is still visible.

Another option would be something like an "alwaysFit" parameter, that resizes the dialog when the available space changes, or even a manual call to `refit()` or something.

Of course, the `alwaysFit()` scenario is more-or-less equivalent to calling 

```java
foo.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
```

 after the fact.

**Comment by afollestad** [comment]
The current behavior is how Android dialogs behave. 

If you need a long form, e.g. for creating new users, you probably shouldn't be using a dialog; you should be using a simple Activity.

**Comment by tigerhawkvok** [comment]
Fair enough.
