### ISSUE TITLE
Missing dismiss() method

### ISSUE THREAD

**Issue by EpsilonOrionis** [afollestad/material-dialogs#670]
Hi, I've created an instance of material dialog, but I can't invoke the dismiss() method when it isn't no longer needed.

**Comment by afollestad** [comment]
MaterialDialog.Builder is not a dialog, MaterialDialog is.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)

**Comment by EpsilonOrionis** [comment]
Thank you, for everything.
