### ISSUE TITLE
How to handle orientation change when autodismiss is off?

### ISSUE THREAD

**Issue by NeverGivinUp** [afollestad/material-dialogs#671]
Android closes the dialog  unhappy - it logs an error android.view.WindowLeaked - when autoDismiss is turned off and the user changes the phones orientation. 

If users of material-dialogs do not need to worry about that of if we need to do something about that, some documentation in the readme would be welcome. Currently the readme only comments on the cases where an action button is pressed or the user selects a list item.

**Comment by afollestad** [comment]
That's not an issue with this library, that's how dialogs on Android work.

Use a `DialogFragment`.
