### ISSUE TITLE
Android Studio : Cannot build project with : android - compileSdkVersion 23

### ISSUE THREAD

**Issue by manfromshadow** [afollestad/material-dialogs#672]
Hello, i would like to use Your library but i faced with the following problem:

Whein i synced the project with actualized app.gradle file and tried to build the project i get following error:

```Gradle
:app:dexDebug
AGPBI: {"kind":"simple","text":"UNEXPECTED TOP-LEVEL EXCEPTION:","sources":[{}]}
AGPBI: {"kind":"simple","text":"com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:189)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.run(Main.java:277)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.main(Main.java:245)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.Main.main(Main.java:106)","sources":[{}]}


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

app.gradle file looks following:
```Gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        applicationId "com.xxx.yyy.zzz"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
    packagingOptions {
        exclude 'LICENSE.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
}

repositories {
    jcenter()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://jitpack.io" }
    maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.google.android.gms:play-services:7.8.0'
    compile 'com.mcxiaoke.volley:library:1.0.18'
    compile 'com.orhanobut:logger:1.11'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.android.support:design:23.0.0'
    // UI TESTING DEPENDENCIES
    androidTestCompile 'com.android.support:support-annotations:23.0.0'
    androidTestCompile 'com.android.support.test:runner:0.3'
    androidTestCompile 'com.android.support.test:rules:0.3'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-intents:2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-web:2.2'
    androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-contrib:2.2'
    // ORM DATABASE DEPENDENCIES
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    // STETHO CORE
    compile 'com.facebook.stetho:stetho:1.1.1'
    compile 'com.facebook.stetho:stetho-urlconnection:1.1.1'
    compile 'com.facebook.stetho:stetho-okhttp:1.1.1'
    // GOOGLE ANALYTICS
    compile 'com.google.android.gms:play-services-analytics:7.8.0'
    // JODA TIME FOR ANDROID
    compile 'net.danlew:android.joda:2.8.2'
    // MATERIAL DIALOGS
    compile 'com.afollestad:material-dialogs:0.7.9.1'

}
```

And message in the gradle build is following:
```Gradle
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2
```

How can i solve it this issue please?

**Comment by manfromshadow** [comment]
I think that this issue is related to the   buildToolsVersion 23.0.0 or compile 'com.android.support:design:23.0.0'. Because the last mentioned library was updated today. And without using the 


dependencies {
    compile 'com.afollestad:material-dialogs:0.7.9.1'
}

Can be whole project compiled without the exceptions.

**Comment by afollestad** [comment]
0.7.9.1 didn't change anything related to Gradle, it only added some features to the `ColorChooserDialog`.

I have not had any issues related to Gradle or Build Tools in any of the production apps I use this library in, so unfortunately there's not too much I can do.

**Comment by PGMacDesign** [comment]
I am having the same issue. It looks like it is related to the fact that the project references
"    <style name="Base.Theme.AppCompat.Light" parent="Base.V23.Theme.AppCompat.Light"/>
    <style name="Base.V23.Theme.AppCompat" parent="Base.V22.Theme.AppCompat">"
which if you are running 22, this will error out. I am trying to change things to 23, but I am having a host of compatability issues with other libraries and have already wasted 2/3 of my day with Android Studio. Is it possible to use a previous version of this so we can avoid the API 23 issues until Google fixes them?

**Comment by PGMacDesign** [comment]
I was able to get things to work by using this: compile 'com.afollestad:material-dialogs:0.7.8.1' 
instead of the current version as anything after that used the API lvl 23. Just as a heads up

**Comment by manfromshadow** [comment]
@PGMacDesign  Thank You, it seems to be working for now but i hope that this issue will be resolved in next update.

**Comment by afollestad** [comment]
0.7.9.0 and 0.7.9.1 both use Build Tools v23 and SDK v23, I have no issues. 

It must be something specific to your setup, e.g. your dependencies using conflicting versions.

**Comment by slidenerd** [comment]
I confirm the presence of this error, thanks for your suggestions in advance
![snap 2015-10-16 at 11 35 40](https://cloud.githubusercontent.com/assets/5139030/10534775/0fd097f6-73fa-11e5-99f9-b1ba00d2dd9d.png)

**Comment by AzureusSme** [comment]
Omg, Slidenerd. ♥

**Comment by slidenerd** [comment]
AzureusSme, it seems you are from YouTube :+1:

**Comment by AzureusSme** [comment]
Yeah, i'm from youtube. Your videos are great. Keep up the nice work. Greetings from México. :D

**Comment by AzureusSme** [comment]
Slidenerd, for me its working fine with the last SDK Updates and the last build of Material Dialogs.

![captura de pantalla 170](https://cloud.githubusercontent.com/assets/8404410/10535215/75bd0684-73a6-11e5-8cd7-695bac970980.png)

**Comment by slidenerd** [comment]
thanks for the image AzureusSme, i am running into a GC overflow, there are some differences in your app vs mine, for starters you dont have the APT plugin, perhaps that is interfering with this whole transitive dependency thing? your fb sdk is 4.5, mine is 4.7, i also have realm and parceler in addition to this, when I remove this library from dependency , everything works , if I add this the build works but the execution doesn't. I could add this entire repo as a library project dependency and perhaps it would work that but that is kinda unfair in some cases depending on the T&C of the license under which developers build libraries. besides i ll have to replicate its transitive dependency as a library project as well and that is going to be a lot of headache to display 1 simple dialog :+1: lets see what the lib maker says

**Comment by AzureusSme** [comment]
Yeah, could be some mess with the other dependencies. Hope you can make it work!

**Comment by slidenerd** [comment]
I think I found the error, appcompat v7 and support v4!!! i think it may fix this problem :1234:

**Comment by AzureusSme** [comment]
I think support v4 comes by default. I mean, i can use support v4 without adding it to the dependencies.

**Comment by slidenerd** [comment]
That wasn't the problem either, I finally fixed, there were 2 issues, 1 the gradle build version was not uptodate, 2) i had to configure dexOptions to support 4g of ram in the javaMaxHeapSize, now its working :+1:  thanks for your help mate , I owe you one
