### ISSUE TITLE
RTL support has issues

### ISSUE THREAD

**Issue by amulyakhare** [afollestad/material-dialogs#674]
In our app, we support both LTR and RTL locales. So when users switch between locales, all the layouts are rendered RTL or LTR accordingly. The material dialogs however do not follow the layout direction correctly.

Problem Screenshot from my app (material-dialogs):
![sample_md](https://cloud.githubusercontent.com/assets/643983/9679753/f14e1750-5323-11e5-956a-fbfc55bf4e8a.png)

Correct Screenshot from Facebook app:
![sample_fb](https://cloud.githubusercontent.com/assets/643983/9679765/0767bf64-5324-11e5-9cee-44e789fca139.png)

As you can notice, the position and order of buttons should change depending on the layout direction (RTL or LTR), but this does not work automatically at this moment. I have gone through RTL related tickets and can't seem to find a solution to the problem mentioned above.

**Comment by afollestad** [comment]
It looks like you're using Gingerbread in those screenshots? RTL support does not natively exist below Android Jellybean.

**Comment by afollestad** [comment]
Although it happens on Android 6.0 Marshmallow with RTL forced.

@teslacoil looks like we may've missed something in the layout code?

**Comment by fangzhzh** [comment]
@afollestad hi, we tested this on Lolipop

**Comment by afollestad** [comment]
@fangzhzh yeah, I tested it on Marshmallow. 

I'll solve the issue when I have more time.

**Comment by afollestad** [comment]
Fixed:
![md](https://cloud.githubusercontent.com/assets/1820165/9724458/51f7daa2-559d-11e5-932a-57c67767f804.png)
Again, native RTL support only exists on API 17 (Android 4.2 Jellybean) and above.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
