### ISSUE TITLE
white color for search view after updating the library from 0.6.3.2 to 0.7.9.0

### ISSUE THREAD

**Issue by gitton** [afollestad/material-dialogs#676]
white color for edit text ,search view and also for drop down menu text item  with latest update to 0.7.9.0.

when trying to build with 0.6.3.2 it is showing  library can't be resolved

**Comment by afollestad** [comment]
Well first of all, you were 100-200 versions behind, maybe more. The latest is 0.7.9.1.

I'm assuming you're *not* using AppCompat in your Activity theme, which is required. You have to also have the `colorAccent` attribute set to a color, if you're not using global theming attributes or manually setting accent/widget colors from the dialog builder.
