### ISSUE TITLE
Indeterminate progress doesn't work correctly on API 5.0

### ISSUE THREAD

**Issue by ZhangPeibin** [afollestad/material-dialogs#680]
Hi,Thanks for your great lib.But I have a question when using Indeterminate progress.
The question's details :the progress can not scroll .I use the same code that your example used.

```java
public static MaterialDialog showIndeterminateProgressDialog(final FragmentActivity fragmentActivity, 
    int resId, DialogInterface.OnCancelListener cancelListener) {
        MaterialDialog.Builder builder = new MaterialDialog.Builder(fragmentActivity)
                .theme(Theme.LIGHT)
               // .title(R.string.app_name)
                .content(resId)
                .cancelable(false)
                .progress(true, 0)
                .progressIndeterminateStyle(false)
                .cancelListener(cancelListener);
        return builder.show();
}
```

but it doesn't work on my project ! 
It was 0.7.6.0 version for your lib.
One more thing,Thanks for your help!

**Comment by afollestad** [comment]
Should be fixed for Android 4.0+ in the upcoming release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0

**Comment by afollestad** [comment]
New important update related to this: https://github.com/afollestad/material-dialogs/releases/tag/0.8.1.0
