### ISSUE TITLE
ColorChooserDialog in Fragment

### ISSUE THREAD

**Issue by creperju** [afollestad/material-dialogs#683]
Hi, i implement a button in Activity which extends Fragment, but i can't apply AppCompatActivity in field, how to work it?

Here my code, thanks

```java
public class Inicio extends Fragment {
...
getActivity().findViewById(R.id.ejemploColor).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new ColorChooserDialog.Builder((AppCompatActivity)getActivity()
                         ...
```

**Comment by afollestad** [comment]
You need to pass the name of the Activity class, rather than just `AppCompatActivity`. If your Activity was called `MainActivity`:

```java
new ColorChooserDialog.Builder((MainActivity) getActivity(), R.string.title)
        ...
        .show();
```

The construction specifies that it requires an `AppCompatActivity` which implements `ColorCallback`.

**Comment by creperju** [comment]
Woow!! It's works, thanks a lot!!
