### ISSUE TITLE
'No resource found that matches the given name'  Issues

### ISSUE THREAD

**Issue by brownidj** [afollestad/material-dialogs#684]
/Users/****/*****/*****/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.0/res/values-v23/values-v23.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/dev_stuff/android-sdk-macosx/build-tools/23.0.1/aapt'' finished with non-zero exit value 1
Information:BUILD FAILED

**Comment by afollestad** [comment]
I have no build issues. 

By the look of the error, Android Studio is looking in the wrong folder (AppCompat 23.0.0 != 23.0.1).

**Comment by afollestad** [comment]
Make sure you have the latest updates from the SDK Manager.

**Comment by brownidj** [comment]
Thanks for that - I hadn't updated my compileSdkVersion. Super quick response!

**Comment by afollestad** [comment]
No problem!

**Comment by srujan7** [comment]
Even I am having the same issue. Unable to find any way to resolve it.

**Comment by XinqingHappy** [comment]
me too 


******/MainActivity/build/intermediates/res/merged/release/values-v23/values-v23.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
    
******/MainActivity/build/intermediates/res/merged/release/values-v23/values-v23.xml:34: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
    
******/MainActivity/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
******/MainActivity/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
