### ISSUE TITLE
ColorChooserDialog on Gingerbread with RTL?

### ISSUE THREAD

**Issue by jehad-suliman** [afollestad/material-dialogs#685]
![198452 27004140721843963](https://cloud.githubusercontent.com/assets/4346294/9831398/aa5d784a-595e-11e5-8b4b-f5e15b17296e.jpg)

its looks like this when using RTL

**Comment by afollestad** [comment]
It has nothing to do with RTL:

![md](https://cloud.githubusercontent.com/assets/1820165/9833615/890f446c-5962-11e5-9456-d7b40f92da97.png)

Unfortunately, I think it's a compatibility issue with Android 2.x that I can't fix.

**Comment by jehad-suliman** [comment]
its With Rtl because i tested it on 4.4 Samsung S5

in English its perfect 
but if you changed the language to Arabic or Hibro 
you can see the deference

**Comment by afollestad** [comment]
Well, evidently it's not, because I just tested it.

I'm guessing it's related to something else, e.g. in Samsung's firmware.

**Comment by afollestad** [comment]
Well, evidently it's not, because I tested it as shown above.

I'm guessing it's related to something else, e.g. the version of Android you're using (Gingerbread shouldn't be used by anyone anymore).

**Comment by mkonicek** [comment]
React Native requires API 16+, Gingerbread is API 10. Are you sure you're running the app on Gingerbread?

**Comment by afollestad** [comment]
@mkonicek I'm not sure what you're talking about, this library and issue have nothing to do with React Native
