### ISSUE TITLE
Option to set inputMinLength

### ISSUE THREAD

**Issue by Gerlot** [afollestad/material-dialogs#686]
Hi!
I really like the library, and use it extensively in the applications I develop. Currently I'm working on a passcode input dialog, and I found that I can specify "inputMaxLength" to a MaterialDialog.Builder, but there is no "inputMinLength", which would be useful for my use-case (the passcode must have exactly a specified lenght).

Could you add an "inputMinLength" setting, which validates the input the same way as the "inputMaxLength" (disabling the positive button and colouring the EditText red, or the specified color, when not having enough characters entered, and displaying the character count as well)?

**Comment by afollestad** [comment]
`inputMaxLength()` will be deprecated in favor of a new method called `inputRange()` in version 8.0.0.

It will allow a min and max length to be specified.

**Comment by Gerlot** [comment]
That's awesome, thank you!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
