### ISSUE TITLE
java.lang.ClassCastException: android.widget.ImageView cannot be cast to android .widget.CompoundButton

### ISSUE THREAD

**Issue by lokeshgrkumar** [afollestad/material-dialogs#687]
```Gradle
at com.afollestad.materialdialogs.simplelist.MaterialSimpleListAdapter.getView(Unknown Source)
```

We have used ImageView in Material Dialog and we are seeing this crash on our live app.

**Comment by afollestad** [comment]
Not 100% what the problem is here.

`MaterialSimpleListAdapter` has to explicitly be set to a dialog as a custom adapter. That adapter is working fine when tested via the sample project, also:

![md](https://cloud.githubusercontent.com/assets/1820165/9856623/6d08f9b4-5adb-11e5-91c6-ed3dfe3077e6.png)

Simple dialogs are a specific style of dialog mentioned in Google's Material design guidelines: https://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs

**Comment by afollestad** [comment]
Not 100% what the problem is here.

Simple dialogs are a specific style of dialog mentioned in Google's Material design guidelines: https://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs

`MaterialSimpleListAdapter` has to explicitly be set to a dialog as a custom adapter. That adapter is working fine when tested via the sample project, also:

![rsz_md](https://cloud.githubusercontent.com/assets/1820165/9856686/cd394d0c-5adb-11e5-87a2-9ead40cf2311.png)

**Comment by afollestad** [comment]
It still works whether or not I choose to include both an icon and text for each item.

See the sample project if you want to know how this adapter is used.

```java
final MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(this);
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content("username@gmail.com")
        .icon(R.drawable.ic_circle_darker)
        .build());
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content("user02@gmail.com")
        .icon(R.drawable.ic_circle_darker)
        .build());
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content(R.string.add_account)
        .icon(R.drawable.ic_circle_lighter)
        .build());

new MaterialDialog.Builder(this)
        .title(R.string.set_backup)
        .adapter(adapter, new MaterialDialog.ListCallback() {
            @Override
            public void onSelection(MaterialDialog dialog, View itemView, int which, CharSequence text) {
                MaterialSimpleListItem item = adapter.getItem(which);
                showToast(item.getContent().toString());
            }
        })
        .show();
```

**Comment by lokeshgrkumar** [comment]
Hi Aidan,

Below is the retrace of the crash we are seeing on our developer account on
the play store.
Below that is the code we have written to implement that in onBackPressed()
of our activity.
We have implemented Basic(icon) dialog.
I tested with my Nexus 5 and it works. I am assuming that for a few Samsung
galaxy devices it crashes as per play store device.
If you get any idea from the logs below, please help us.
As of now we reverted to basic without icon dialog.
Awaiting your response.

java.lang.ClassCastException: android.widget.ImageView cannot be cast to
android
.widget.CompoundButton
        at
com.afollestad.materialdialogs.simplelist.MaterialSimpleListAdapter.g
etView(Unknown Source)
        at android.widget.AbsListView.obtainView(AbsListView.java:2627)
        at
android.widget.ListView.measureHeightOfChildren(ListView.java:1259)
        at android.widget.ListView.onMeasure(ListView.java:1171)
        at android.view.View.measure(View.java:16831)
        at
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16831)
        at
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
        at
android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.jav
a:1410)
        at
android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:16831)
        at
com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(Unknow
n Source)
        at android.view.View.measure(View.java:16831)
        at
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16831)
        at
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
        at
android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.jav
a:1410)
        at
android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:16831)
        at
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at
com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(Phon
eWindow.java:2586)
        at android.view.View.measure(View.java:16831)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2189)
        at
android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1327)
        at
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1535)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
        at
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:636
4)
        at
android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)

        at android.view.Choreographer.doCallbacks(Choreographer.java:591)
        at android.view.Choreographer.doFrame(Choreographer.java:561)
        at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographe
r.java:777)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5419)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit
.java:1046)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
        at dalvik.system.NativeStart.main(Native Method)


new MaterialDialog.Builder(this)
                    .title(getString(R.string.exit_dialog_title))

.titleColor(getResources().getColor(R.color.textColorPrimary))
                    .titleGravity(GravityEnum.START)
                    .iconRes(R.drawable.ic_play_store_header)
                    .maxIconSize(140)
                    .customView(R.layout.buy_dialog, false)
                    .positiveText(R.string.iab_buy)
                    .negativeText(R.string.remind_later)
                    .neutralText(R.string.rate_us)
                    .cancelable(false)
                    .callback(new MaterialDialog.ButtonCallback() {
                        @Override
                        public void onPositive(MaterialDialog dialog) {
                            super.onPositive(dialog);
                            if
(GeneralUtil.haveNetworkConnection(HomePage.this) && iabHelper != null)
                                iabHelper.launchPurchaseFlow(HomePage.this,
ATAApp.ITEM_SKU, 10001,
                                        mPurchaseFinishedListener);
                            dialog.dismiss();
                        }

                        @Override
                        public void onNegative(MaterialDialog dialog) {
                            super.onNegative(dialog);

appPreferences.setProDialogLimit(appPreferences.getProDialogCount() + 1);
                            appPreferences.setProDialogCount(0);
                            dialog.dismiss();
                            onBackPressed();
                        }

                        @Override
                        public void onNeutral(MaterialDialog dialog) {
                            super.onNeutral(dialog);
                            rateUs();
                        }
                    })
                    .theme(Theme.LIGHT)
                    .show();

On Mon, Sep 14, 2015 at 11:00 PM, Aidan Follestad <notifications@github.com>
wrote:

> It still works whether or not I choose to include both an icon and text
> for each item.
>
> See the sample project if you want to know how this adapter is used.
>
> final MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(this);
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content("username@gmail.com")
>         .icon(R.drawable.ic_circle_darker)
>         .build());
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content("user02@gmail.com")
>         .icon(R.drawable.ic_circle_darker)
>         .build());
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content(R.string.add_account)
>         .icon(R.drawable.ic_circle_lighter)
>         .build());
> new MaterialDialog.Builder(this)
>         .title(R.string.set_backup)
>         .adapter(adapter, new MaterialDialog.ListCallback() {
>             @Override
>             public void onSelection(MaterialDialog dialog, View itemView, int which, CharSequence text) {
>                 MaterialSimpleListItem item = adapter.getItem(which);
>                 showToast(item.getContent().toString());
>             }
>         })
>         .show();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/687#issuecomment-140153436>
> .
>



-- 
LOKESH KUMAR G.R.
+919886123339
Bangalore.

**Comment by afollestad** [comment]
The Java code you specified there does not use a `MaterialSimpleListAdapter` so that can't be the correct code or the cause.

Please use syntax highlighting when you post code, though: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by lokeshgrkumar** [comment]
Hi,

My bad, I was looking at the wrong code since I am maintaining this app and
the developer is no longer working here.
Below is the code for your reference. It seems legit to my eyes. If you
find anything suspicious please point me towards the same.
Thanks in advance.
The crash log from play store is available in the previous emails
exchanged, so I have not attached it again.
The only difference in code I see, is that we have not declared the adapter
as final.

MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(this);
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content(R.string.facebook)
        .icon(R.drawable.ic_facebook)
        .build());
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content(R.string.twitter)
        .icon(R.drawable.ic_twitter)
        .build());
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content(R.string.google_plus)
        .icon(R.drawable.ic_google_plus)
        .build());
adapter.add(new MaterialSimpleListItem.Builder(this)
        .content(R.string.website)
        .icon(R.drawable.ic_web)
        .build());

new MaterialDialog.Builder(this)
        .title(R.string.find_us_on)
        .adapter(adapter, new MaterialDialog.ListCallback() {
            @Override
            public void onSelection(MaterialDialog dialog, View itemView,
                                    int which, CharSequence text) {

                switch (which) {
                    case 0:
                        String fbWebUri = getString(R.string.fb_web_uri);
                        String fbAppUri = getString(R.string.fb_app_uri);
                        Intent intent = new Intent();
                        intent.setAction(Intent.ACTION_VIEW);
                        intent.setData(Uri.parse(fbAppUri));

                        // If Facebook application is installed, use that else
                        // launch the default browser
                        PackageManager packageManager = getPackageManager();
                        List<ResolveInfo> list = packageManager
                                .queryIntentActivities(intent,
                                        PackageManager.MATCH_DEFAULT_ONLY);
                        if (list.size() == 0) {
                            intent.setData(Uri.parse(fbWebUri));
                        }
                        startActivity(intent);
                        break;

                    case 1:
                        startActivity(new Intent(Intent.ACTION_VIEW,
                                Uri.parse(getString(R.string.twitter_uri))));
                        break;

                    case 2:
                        startActivity(new Intent(
                                Intent.ACTION_VIEW,

Uri.parse(getString(R.string.google_plus_uri))));
                        break;

                    case 3:
                        startActivity(new Intent(Intent.ACTION_VIEW, Uri
                                .parse(getString(R.string.web_uri))));
                        break;
                }
            }
        })
        .theme(Theme.LIGHT)
        .show();


On Tue, Sep 15, 2015 at 8:31 PM, Aidan Follestad <notifications@github.com>
wrote:

> The Java code you specified there does not use a MaterialSimpleListAdapter
> so that can't be the correct code or the cause.
>
> Please use syntax highlighting when you post code, though:
> https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/687#issuecomment-140421343>
> .
>



-- 
LOKESH KUMAR G.R.
+919886123339
Bangalore.

**Comment by lokeshgrkumar** [comment]
Also do I need to use the commons dependency as I am using
MaterialSimpleListAdapter in the project. It is working without that
dependency but on your github page I see that we need to use
this dependency.


compile 'com.afollestad.material-dialogs:commons:0.8.0.0@arr'


On Fri, Sep 18, 2015 at 11:00 AM, Lokesh Kumar <lokeshgrkumar@gmail.com>
wrote:

> Hi,
>
> My bad, I was looking at the wrong code since I am maintaining this app
> and the developer is no longer working here.
> Below is the code for your reference. It seems legit to my eyes. If you
> find anything suspicious please point me towards the same.
> Thanks in advance.
> The crash log from play store is available in the previous emails
> exchanged, so I have not attached it again.
> The only difference in code I see, is that we have not declared the
> adapter as final.
>
> MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(this);
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content(R.string.facebook)
>         .icon(R.drawable.ic_facebook)
>         .build());
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content(R.string.twitter)
>         .icon(R.drawable.ic_twitter)
>         .build());
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content(R.string.google_plus)
>         .icon(R.drawable.ic_google_plus)
>         .build());
> adapter.add(new MaterialSimpleListItem.Builder(this)
>         .content(R.string.website)
>         .icon(R.drawable.ic_web)
>         .build());
>
> new MaterialDialog.Builder(this)
>         .title(R.string.find_us_on)
>         .adapter(adapter, new MaterialDialog.ListCallback() {
>             @Override
>             public void onSelection(MaterialDialog dialog, View itemView,
>                                     int which, CharSequence text) {
>
>                 switch (which) {
>                     case 0:
>                         String fbWebUri = getString(R.string.fb_web_uri);
>                         String fbAppUri = getString(R.string.fb_app_uri);
>                         Intent intent = new Intent();
>                         intent.setAction(Intent.ACTION_VIEW);
>                         intent.setData(Uri.parse(fbAppUri));
>
>                         // If Facebook application is installed, use that else
>                         // launch the default browser
>                         PackageManager packageManager = getPackageManager();
>                         List<ResolveInfo> list = packageManager
>                                 .queryIntentActivities(intent,
>                                         PackageManager.MATCH_DEFAULT_ONLY);
>                         if (list.size() == 0) {
>                             intent.setData(Uri.parse(fbWebUri));
>                         }
>                         startActivity(intent);
>                         break;
>
>                     case 1:
>                         startActivity(new Intent(Intent.ACTION_VIEW,
>                                 Uri.parse(getString(R.string.twitter_uri))));
>                         break;
>
>                     case 2:
>                         startActivity(new Intent(
>                                 Intent.ACTION_VIEW,
>                                 Uri.parse(getString(R.string.google_plus_uri))));
>                         break;
>
>                     case 3:
>                         startActivity(new Intent(Intent.ACTION_VIEW, Uri
>                                 .parse(getString(R.string.web_uri))));
>                         break;
>                 }
>             }
>         })
>         .theme(Theme.LIGHT)
>         .show();
>
>
> On Tue, Sep 15, 2015 at 8:31 PM, Aidan Follestad <notifications@github.com
> > wrote:
>
>> The Java code you specified there does not use a
>> MaterialSimpleListAdapter so that can't be the correct code or the cause.
>>
>> Please use syntax highlighting when you post code, though:
>> https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/afollestad/material-dialogs/issues/687#issuecomment-140421343>
>> .
>>
>
>
>
> --
> LOKESH KUMAR G.R.
> +919886123339
> Bangalore.
>



-- 
LOKESH KUMAR G.R.
+919886123339
Bangalore.

**Comment by lokeshgrkumar** [comment]
We fixed it,

Thank you for your time and support. Much appreciated.
We used to Gravity.END to fix the RTL issue.

On Fri, Sep 18, 2015 at 11:43 AM, Lokesh Kumar <lokeshgrkumar@gmail.com>
wrote:

> Also do I need to use the commons dependency as I am using
> MaterialSimpleListAdapter in the project. It is working without that
> dependency but on your github page I see that we need to use
> this dependency.
>
>
> compile 'com.afollestad.material-dialogs:commons:0.8.0.0@arr'
>
>
> On Fri, Sep 18, 2015 at 11:00 AM, Lokesh Kumar <lokeshgrkumar@gmail.com>
> wrote:
>
>> Hi,
>>
>> My bad, I was looking at the wrong code since I am maintaining this app
>> and the developer is no longer working here.
>> Below is the code for your reference. It seems legit to my eyes. If you
>> find anything suspicious please point me towards the same.
>> Thanks in advance.
>> The crash log from play store is available in the previous emails
>> exchanged, so I have not attached it again.
>> The only difference in code I see, is that we have not declared the
>> adapter as final.
>>
>> MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(this);
>> adapter.add(new MaterialSimpleListItem.Builder(this)
>>         .content(R.string.facebook)
>>         .icon(R.drawable.ic_facebook)
>>         .build());
>> adapter.add(new MaterialSimpleListItem.Builder(this)
>>         .content(R.string.twitter)
>>         .icon(R.drawable.ic_twitter)
>>         .build());
>> adapter.add(new MaterialSimpleListItem.Builder(this)
>>         .content(R.string.google_plus)
>>         .icon(R.drawable.ic_google_plus)
>>         .build());
>> adapter.add(new MaterialSimpleListItem.Builder(this)
>>         .content(R.string.website)
>>         .icon(R.drawable.ic_web)
>>         .build());
>>
>> new MaterialDialog.Builder(this)
>>         .title(R.string.find_us_on)
>>         .adapter(adapter, new MaterialDialog.ListCallback() {
>>             @Override
>>             public void onSelection(MaterialDialog dialog, View itemView,
>>                                     int which, CharSequence text) {
>>
>>                 switch (which) {
>>                     case 0:
>>                         String fbWebUri = getString(R.string.fb_web_uri);
>>                         String fbAppUri = getString(R.string.fb_app_uri);
>>                         Intent intent = new Intent();
>>                         intent.setAction(Intent.ACTION_VIEW);
>>                         intent.setData(Uri.parse(fbAppUri));
>>
>>                         // If Facebook application is installed, use that else
>>                         // launch the default browser
>>                         PackageManager packageManager = getPackageManager();
>>                         List<ResolveInfo> list = packageManager
>>                                 .queryIntentActivities(intent,
>>                                         PackageManager.MATCH_DEFAULT_ONLY);
>>                         if (list.size() == 0) {
>>                             intent.setData(Uri.parse(fbWebUri));
>>                         }
>>                         startActivity(intent);
>>                         break;
>>
>>                     case 1:
>>                         startActivity(new Intent(Intent.ACTION_VIEW,
>>                                 Uri.parse(getString(R.string.twitter_uri))));
>>                         break;
>>
>>                     case 2:
>>                         startActivity(new Intent(
>>                                 Intent.ACTION_VIEW,
>>                                 Uri.parse(getString(R.string.google_plus_uri))));
>>                         break;
>>
>>                     case 3:
>>                         startActivity(new Intent(Intent.ACTION_VIEW, Uri
>>                                 .parse(getString(R.string.web_uri))));
>>                         break;
>>                 }
>>             }
>>         })
>>         .theme(Theme.LIGHT)
>>         .show();
>>
>>
>> On Tue, Sep 15, 2015 at 8:31 PM, Aidan Follestad <
>> notifications@github.com> wrote:
>>
>>> The Java code you specified there does not use a
>>> MaterialSimpleListAdapter so that can't be the correct code or the
>>> cause.
>>>
>>> Please use syntax highlighting when you post code, though:
>>> https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/afollestad/material-dialogs/issues/687#issuecomment-140421343>
>>> .
>>>
>>
>>
>>
>> --
>> LOKESH KUMAR G.R.
>> +919886123339
>> Bangalore.
>>
>
>
>
> --
> LOKESH KUMAR G.R.
> +919886123339
> Bangalore.
>



-- 
LOKESH KUMAR G.R.
+919886123339
Bangalore.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/693

**Comment by afollestad** [comment]
This crash will be fixed in the next release.

**Comment by afollestad** [comment]
This is fixed now https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.1
