### ISSUE TITLE
List with filter

### ISSUE THREAD

**Issue by auchri** [afollestad/material-dialogs#689]
I want to create a list dialog with a filter.

That means I want a text input field above the list. When I enter "a", only items which begin with "a" are displayed.

Is there and easy way to create such a dialog without copy/paste the layout from the ListView to my custom dialog?

**Comment by afollestad** [comment]
You'll need a custom view.

**Comment by auchri** [comment]
Yes, I know.

But I made it, it wasn't as much copy/paste as I expected.
