### ISSUE TITLE
New gradle deps not working

### ISSUE THREAD

**Issue by delvv** [afollestad/material-dialogs#691]
I'm already using Jitpack for other projects, so that's not the problem.  I tried referencing it as:
compile 'com.afollestad:material-dialogs:core:0.8.0.0'
and with the jitpack style:
compile 'com.github.afollestad:material-dialogs:core:0.8.0.0'
Neither seem to be working, the packages just aren't found.
Just wanted to let you know promptly!

**Comment by afollestad** [comment]
I know, I'm working on it, thanks

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0
