### ISSUE TITLE
Crash on Samsung device

### ISSUE THREAD

**Issue by nguyenhoangtoan1203** [afollestad/material-dialogs#692]
When i run on tablet Samsung, my app is crashed when i build a progress dialog:

```java
new MaterialDialog.Builder(context)
    .content(R.string.loading)
    .progress(true, 0)
    .build();
```

I see log, it show: Fatal Exception: android.view.InflateException Binary XML file line #19: Error inflating class TextView

This logs:

```Gradle
java.lang.Integer.invalidInt (Integer.java:138)
	android.content.res.TypedArray.getInt (TypedArray.java:254)
	android.widget.TextView. (TextView.java:997)
	android.support.v7.widget.AppCompatTextView. (AppCompatTextView.java:44)
	android.support.v7.widget.AppCompatTextView. (AppCompatTextView.java:40)
	android.support.v7.internal.app.AppCompatViewInflater.createView (AppCompatViewInflater.java:103)
	android.support.v7.app.AppCompatDelegateImplV7.createView (AppCompatDelegateImplV7.java:802)
	android.support.v7.app.AppCompatDelegateImplV7.onCreateView (AppCompatDelegateImplV7.java:832)
	android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView (LayoutInflaterCompatHC.java:44)
	android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:675)
	android.view.LayoutInflater.rInflate (LayoutInflater.java:746)
	android.view.LayoutInflater.parseInclude (LayoutInflater.java:830)
	android.view.LayoutInflater.rInflate (LayoutInflater.java:736)
	android.view.LayoutInflater.inflate (LayoutInflater.java:489)
	android.view.LayoutInflater.inflate (LayoutInflater.java:396)
	android.view.LayoutInflater.inflate (LayoutInflater.java:352)
	com.afollestad.materialdialogs.MaterialDialog. (MaterialDialog.java:88)
	com.afollestad.materialdialogs.MaterialDialog$Builder.build (MaterialDialog.java:1153)
```

I using version 0.7.6.0.

Can you help me verify it ?  Thanks a lot.

**Comment by afollestad** [comment]
Version 0.7.6.0 is very, very old, so unfortunately no, I can't verify it

On Fri, Sep 18, 2015, 12:38 AM nguyenhoangtoan1203 <notifications@github.com>
wrote:

> When i run on tablet Samsung, my app is crashed when i build a progress
> dialog:
> new
> MaterialDialog.Builder(context).content(R.string.loading).progress(true,
> 0).build();
>
> I see log, it show: Fatal Exception: android.view.InflateException Binary
> XML file line #19
> <https://github.com/afollestad/material-dialogs/issues/19>: Error
> inflating class TextView
>
> This logs:
>
> java.lang.Integer.invalidInt (Integer.java:138)
> android.content.res.TypedArray.getInt (TypedArray.java:254)
> android.widget.TextView. (TextView.java:997)
> android.support.v7.widget.AppCompatTextView. (AppCompatTextView.java:44)
> android.support.v7.widget.AppCompatTextView. (AppCompatTextView.java:40)
> android.support.v7.internal.app.AppCompatViewInflater.createView
> (AppCompatViewInflater.java:103)
> android.support.v7.app.AppCompatDelegateImplV7.createView
> (AppCompatDelegateImplV7.java:802)
> android.support.v7.app.AppCompatDelegateImplV7.onCreateView
> (AppCompatDelegateImplV7.java:832)
> android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView
> (LayoutInflaterCompatHC.java:44)
> android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:675)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:746)
> android.view.LayoutInflater.parseInclude (LayoutInflater.java:830)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:736)
> android.view.LayoutInflater.inflate (LayoutInflater.java:489)
> android.view.LayoutInflater.inflate (LayoutInflater.java:396)
> android.view.LayoutInflater.inflate (LayoutInflater.java:352)
> com.afollestad.materialdialogs.MaterialDialog. (MaterialDialog.java:88)
> com.afollestad.materialdialogs.MaterialDialog$Builder.build
> (MaterialDialog.java:1153)
>
> I using version 0.7.6.0.
>
> Can you help me verify it ? Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/692>.
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by nguyenhoangtoan1203** [comment]
I checked your source code, and i think android:paddingStart in textview of layout is root cause. It can make crashed on same devices. My device is Samsung Galaxy Tab!

**Comment by afollestad** [comment]
Newer build tools splits your layouts automatically so that those are only
used on the API levels that support it. That can't be the issue.

On Fri, Sep 18, 2015, 3:26 AM nguyenhoangtoan1203 <notifications@github.com>
wrote:

> I checked your source code, and i think android:paddingStart in textview
> of layout is root cause. It can make crashed on same devices. My device is
> Samsung Galaxy Tab!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/692#issuecomment-141380183>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment]
I updated the original comment for syntax highlighting.

It appears this issue is specific to Samsung, like many bugs in the Android ecosystem are (unfortunately): https://code.google.com/p/android/issues/detail?id=60055

**Comment by afollestad** [comment]
I haven't been able to reproduce the issue. 

But make sure you're using a new version of Build Tools, like the version used by this library. Build Tools should separate resource files into two separate versions (for RTL support and non-RTL support).
