### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by deivitaka** [afollestad/material-dialogs#694]
For some reason I can't add this to my gradle.

Error:(34, 13) Failed to resolve: com.github.afollestad:material-dialogs:0.8.0.0

I tried both:
compile 'com.afollestad.material-dialogs:core:0.8.0.0@aar' and
compile 'com.afollestad.material-dialogs:core:0.8.0.0'

**Comment by akbarsha03** [comment]
@deivitaka the project has been moved from bintray to jitpack. please add the following to your main project build.gradle

```

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

```

**Comment by deivitaka** [comment]
Oh, I do have added them, but now that I checked I found out that I added them under buildscript. My bad!

**Comment by timrae** [comment]
@afollestad It would be appreciated if you could please stop deleting uploaded releases, as it breaks the build process. This is bad for our CI, and it's even worse for potential developers or hackers that want to compile our project from source.

**Comment by afollestad** [comment]
@timrae as mentioned in the other issue you mentioned me in, Bintray is no longer used anyways.

**Comment by cooervo** [comment]
this worked for me:

http://stackoverflow.com/a/32900570/4031815

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
