### ISSUE TITLE
Cannot find symbol class Material Dialog

### ISSUE THREAD

**Issue by elsennov** [afollestad/material-dialogs#695]
I compile the sdk using version 22. It keeps saying "cannot find symbol class Material Dialog". Is it because the library compiled using version 23?
Can i use this library but compiling the sdk using version 22? Thanks.

**Comment by afollestad** [comment]
Sorry, no. You will have to update in order to use new versions.

**Comment by elsennov** [comment]
Oh that's ok. So, what version of this library that i can use with sdk 22?
