### ISSUE TITLE
Proper-styled single-choice list with custom adapter

### ISSUE THREAD

**Issue by AAverin** [afollestad/material-dialogs#696]
Not really an issue but maybe a suggestion.
I have custom Objects that aren't strings, but still would like to display a single-choice list.
I tried setting custom ArrayAdapter<MyClass>, but radiobuttons selection doesn't work when using android.R.layout.simple_list_item_single_choice, and also UI doesn't follow Material Design specs - radiobutton is on the right from the text.
Anyways.
Would be nice to have a proper-styled resource to use for radio-lists and a fix for radio-buttons on custom adapters to work.

**Comment by afollestad** [comment]
If you use a custom adapter, selection has to be handled manually. So you want to be able to convert custom objects to strings (e.g. via `toString()`)?

Have you actually read the specs? They're on the right.

https://www.google.com/design/spec/components/dialogs.html#dialogs-behavior

**Comment by afollestad** [comment]
Sorry, left*

**Comment by afollestad** [comment]
I don't really think converting objects to strings is something that needs to be in the library. You could construct your own array fairly easy, `CharSequence` and `String` are interchangeable.
