### ISSUE TITLE
Commons module gradle setup

### ISSUE THREAD

**Issue by TheFinestArtist** [afollestad/material-dialogs#697]
I don't think setting up gradle with commons module works.

```java
dependencies {
    compile 'com.afollestad.material-dialogs:commons:0.8.0.0@arr'
}
```

**Comment by koesie10** [comment]
It should say `@aar` instead of `@arr`.

**Comment by jeetdholakia** [comment]
How did you guys figure this out? I can't get this to work...

**Comment by afollestad** [comment]
@jeetdholakia https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by jeetdholakia** [comment]
Thanks,  i followed all of that , the problem was that i didnt add a maven dependency
