### ISSUE TITLE
AppCompatActivity Crash

### ISSUE THREAD

**Issue by krazdax5** [afollestad/material-dialogs#701]
This is what I get:
```
java.lang.NoSuchMethodError: No static method getColor(Landroid/content/Context;I)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat'
```

When I use (**this** is a v7 AppCompatActivity):
```java
new MaterialDialog.Builder(this)
    .content(R.string.SomeContent)
    .progress(true, 0)
    .show();
```

Is there something I'm missing? I just upgraded the library from 0.7.8 to 0.8.0.1. It was working before.

**Comment by afollestad** [comment]
Hmm. Make sure you're using version `23.0.1` of Google libs (AppCompat, Support Library, etc.) in your own app.

**Comment by krazdax5** [comment]
Ok. Thanks for your quick response. I'll look into this and share the results.

**Comment by krazdax5** [comment]
Alright. It worked. I think I didn't see the line saying that it the version 0.8 required the SDK 23. Fortunately, you were there! Thanks for your help.

**Comment by neelayak** [comment]
Hey I am using your and it really good  but I stuck with a problem as now the on attach method is deprecated then how can I use the file dialog in my app I tried the following code
`@Override
    public void onAttach(Context context) {
        super.onAttach(context);
        
        context1=this.getActivity();
    }`
and using the context but still i am getting the error I followed this [link](https://stackoverflow.com/questions/32798224/use-material-dialog-in-fragment) .
