### ISSUE TITLE
Problem about adding a preference screen to a drawer fragment

### ISSUE THREAD

**Issue by TYZRPVX** [afollestad/material-dialogs#702]
I want to add a preference screen to a drawer fragment

```
public static class SettingsFragment extends PreferenceFragment {
        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            addPreferencesFromResource(R.xml.preferences);
        }
    }
```

```

 //"Theme item"
PreferenceFragment pf = new SettingsFragment();
getSupportFragmentManager().beginTransaction()
      .replace(R.id.fragment_container, pf).commit();
```

but IDE prompts that replace function  2nd arg wrong type. many thanks if you help me fix this problem.

**Comment by afollestad** [comment]
This code is in no way related to this library.

**Comment by afollestad** [comment]
But you're probably using a non-support library Fragment with the support Fragment Manager.

**Comment by TYZRPVX** [comment]
There is be an Error:Failed to find: `com.afollestad.material-dialogs:commons:0.8.0.1` today.
