### ISSUE TITLE
NoClassDefFoundError - RecyclerView

### ISSUE THREAD

**Issue by elsennov** [afollestad/material-dialogs#703]
I tried 0.8.0.1, and this occured

```Gradle
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/RecyclerView;
09-21 01:27:33.197 29057-29057/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:424)
09-21 01:27:33.197 29057-29057/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:343)
```

**Comment by afollestad** [comment]
Hmmmm. 

Do you use `RecyclerView` in your app? Make sure you're using version `23.0.1`, it could be interfering with the version the library uses.

**Comment by elsennov** [comment]
There is no recycler view, but I am using NavigationView from 'com.android.support:design:23.0.1'. Could it be a problem?
Yes i compiled the sdk using 23.0.1 version. There is no problem if i use 0.7.9.1

**Comment by afollestad** [comment]
If you're using Build Tools 23.0.1 too, I'm not really sure what the issue could be. 

I'm using the latest in 5 or so production apps with no issue.

**Comment by elsennov** [comment]
Have you tried alongside with com.android.support:design:23.0.1?

**Comment by afollestad** [comment]
I have, I've used it with many different combinations of dependencies. Very odd.

**Comment by elsennov** [comment]
Here is the complete log,

``09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/RecyclerView;
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:424)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:343)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2076)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1833)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1058)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5796)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:211)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5317)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.aql.tabunginfaq.dev-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:424) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:343) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.View.layout(View.java:15686) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4967) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2076) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1833) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1058) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5796) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:211) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5317) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.RecyclerView
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:     		... 34 more
09-21 02:01:49.665 26732-26732/com.aql.tabunginfaq.dev E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available``

**Comment by boivie-at-sony** [comment]
MDRootLayout.class, line 424:

            } else if(view instanceof RecyclerView) {

If the project doesn't include the recyclerview jar, this class isn't defined.

So right now, this project depends on "com.android.support:recyclerview-v7"

**Comment by elsennov** [comment]
That's it, thanks man! It finally works, after i add 'com.android.support:recyclerview-v7' into my build.gradle.
I saw on the build.gradle within the core, it's already included. But, why is it not included automatically after i add 'com.afollestad.material-dialogs:core:0.8.0.1@aar'? Hmmm.

**Comment by afollestad** [comment]
It should be, or at least it's supposed to be included automatically.

On Sun, Sep 20, 2015, 2:15 PM Elsen Novraditya <notifications@github.com>
wrote:

> That's it, thanks man! It finally works, after i add
> 'com.android.support:recyclerview-v7' into my build.gradle.
> I saw on the build.gradle within the core, it's already included. But, why
> is it not included automatically after i add
> 'com.afollestad.material-dialogs:core:0.8.0.1@aar'? Hmmm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/703#issuecomment-141822003>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by plusCubed** [comment]
@afollestad I recently found out that if a library is specified by @aar, its dependencies won't be resolved unless you add the transitive=true property. Should we remove @aar from the readme?

**Comment by afollestad** [comment]
@plusCubed ohhh, I was wondering what that property is for.

We need to keep `@aar` cause I'm using JitPack.io now. I'll update the README to include the transitive property. I noticed MaterialDrawer (https://github.com/mikepenz/MaterialDrawer) requires that property too.

**Comment by afollestad** [comment]
@elsennov rather than including the RecyclerView dependency in your own app, just use this:

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.0.1@aar') {
    transitive = true
}
```

**Comment by elsennov** [comment]
@afollestad Yes, i have updated it. Thanks all!
