### ISSUE TITLE
Hello how close the dialogue without the button

### ISSUE THREAD

**Issue by SuleymanovTat** [afollestad/material-dialogs#704]
builder = new MaterialDialog.Builder(this);
        builder.title(R.string.connect)
                .content(R.string.go_check)
                .progress(true, 0)
                .cancelable(false)
                .progressIndeterminateStyle(false)
                .show();

//builder.dismiss no work.....

**Comment by afollestad** [comment]
It's no different than a regular `AlertDialog`. You don't use the Builder to dismiss, you use the Dialog.

**Comment by afollestad** [comment]
`show()` and `build()` both return a `MaterialDialog` just like the regular `AlertDialog.Builder` does.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
