### ISSUE TITLE
issue subclassing MaterialDialog and MaterialDialog.Builder

### ISSUE THREAD

**Issue by inteist** [afollestad/material-dialogs#705]
I need to make sure dialogs do not overlap each other (they can with the current implementation if invoked in a row). I managed this in my own code but this did not look like the right solution. So I decided to extend MaterialDialog. I was going to do a pull request but I wasn't sure how relevant this would be to others since and I wanted to test it a bit and to my surprise there seems to be a problem with what seems like 100% legit (and very simple) subclassing implementation so I suspect the problem lies somewhere deeper in the library this is why I file it as an issue. I apologize in advance if that is something I overlooked but as you will see the implementation is pretty simple and straightforward and I can't imagine how it could be the subclassing issue. 

Here's the code:

```java

import android.content.Context;
import android.content.DialogInterface;
import android.support.annotation.NonNull;

import com.afollestad.materialdialogs.MaterialDialog;
import com.comitic.android.util.CLog;


public class OneAtATimeMaterialDialog extends MaterialDialog {

    private static boolean hasActiveDialogOnScreen = false;

    protected OneAtATimeMaterialDialog(MaterialDialog.Builder builder) {
        super(builder);
    }


    @Override
    public void show() {
        if (!hasActiveDialogOnScreen) {
            hasActiveDialogOnScreen = true;
            super.show();
        }
    }



//             ____        _ _     _
//            |  _ \      (_) |   | |
//            | |_) |_   _ _| | __| | ___ _ __
//            |  _ <| | | | | |/ _` |/ _ \ '__|
//            | |_) | |_| | | | (_| |  __/ |
//            |____/ \__,_|_|_|\__,_|\___|_|
//

    public static class Builder extends MaterialDialog.Builder {

        public Builder(@NonNull Context context) {
            super(context);

            dismissListener(new OnDismissListener() {
                @Override
                public void onDismiss(DialogInterface dialog) {
                    hasActiveDialogOnScreen = false;
                }
            });
        }

        @Override
        public MaterialDialog.Builder dismissListener(@NonNull final OnDismissListener listener) {

            return super.dismissListener(new OnDismissListener() {
                @Override
                public void onDismiss(DialogInterface dialog) {
                    hasActiveDialogOnScreen = false;
                    listener.onDismiss(dialog);
                }
            });
        }


        @Override
        public MaterialDialog build() {
            super.build();
            OneAtATimeMaterialDialog d = new OneAtATimeMaterialDialog(this);
            return d;
        }


        @Override
        public MaterialDialog show() {
            if (!hasActiveDialogOnScreen) {
                hasActiveDialogOnScreen = true;
                return super.show();
            }
            else {
                CLog.w("MD - has active dialog showing - not showing and returning null");
                return null;
            }
        }
    }



}

```

### Stack trace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{PACKAGE.ACTIVITY}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
```

```
 at com.afollestad.materialdialogs.MaterialDialog.(MaterialDialog.java:91)
 at MYPACKAGE.UI.element.dialog.OneAtATimeMaterialDialog.(OneAtATimeMaterialDialog.java:18)
```

the line `91` in the lib is:

```
DialogInit.init(this);
```

I am using the 0.7.8.0 and I checked out the `v0.7.8.0` and given the err message it does all make sense that this would be the problematic line.

### NOTES:
In our internal testing we did not encounter any problems. Only when we released the app to the wild we started seeing this. But it is not very rare. We had a LOT of crash reports. Devices/OS seem to vary so this is not device/os specific. Not sure why we did not see this in our internal testing.

Hope you can shed some light on this and hopefully we can get it fixed quickly. 

Let me know if you want me to do a pull request, although it might be easier if you just incorporate this into the lib. I think it is very useful and saves quite a bit of code while actually using the lib in an app since you don't have to track whether there is another dialog showing already. And you can always have the default behavior by instantiating the default class.

**Comment by afollestad** [comment]
It might be helpful to see more of the stack trace. But I can look into this later. 

I don't think it would be necessary to put this into the library. I should also note that 0.7.8.0 isn't the latest release.

**Comment by afollestad** [comment]
Actually that info will be enough.

**Comment by inteist** [comment]
Aidan, thanks for the prompt reply as always.

We are well aware that this is not the latest release. We do not feel comfortable releasing bleeding edge to production. We periodically upgrade the library and make sure we run the tests. It is not too old of a release either and while I suspected you may suggest we should use the latest version and see if the problem exists there, given that we did not see this in our internal testing this would be impossible and given the simplicity of subclassing, as I mentioned it def. looks like the problem is somewhere inside the lib. Maybe you did not expect people to subclass MaterialDialog class. 

Btw, maybe there is a better way to implement what we need, I'd appreciate if you point me into the right direction. But again, the subclassing is pretty straightforward.

Thanks!

**Comment by inteist** [comment]
a little more info to make it easier for you to follow:

the 18-th line is the 
```
    protected OneAtATimeMaterialDialog(MaterialDialog.Builder builder) {
        super(builder); // <---- problem is here, 18-th LINE 
    }
```

```

    @SuppressLint("InflateParams")
    protected MaterialDialog(Builder builder) {
        super(builder.context, DialogInit.getTheme(builder));
        mHandler = new Handler();
        mBuilder = builder;
        final LayoutInflater inflater = LayoutInflater.from(builder.context);
        view = (MDRootLayout) inflater.inflate(DialogInit.getInflateLayout(builder), null);
        DialogInit.init(this);  // <----- HERE, LINE 91
    }
```

**Comment by afollestad** [comment]
@inteist I'm not able to reproduce this issue, there's no crash.

0.7.8.0 is actually relatively old now, so it probably was fixed before.

**Comment by inteist** [comment]
@afollestad 
I mentioned that this is not easily reproducible. We could not reproduce it as well but from a few thousand users, we received 500 crash reports in less than 12 hours.

I believe this has something to do with how you construct the dialog view. Maybe you do not dispose of something or try to reuse something and so when super is called, it tries to reconstruct the existing dialog and crashes with ` The specified child already has a parent. You must call removeView() on the child's parent first.`

- Any thoughts on this? 

We can try to update to the latest version but since this looks to be something really basic, I doubt it would resolve our issue.

- Do you see any problems with our subclassing?

**Comment by afollestad** [comment]
Well, the current version is 0.8.0.1 and it's now hosted on JitPack.io instead of jCenter. If I remember correctly, 0.7.9.x may or may not have changed something related to view inflation.

But, `DialogInit.init(this)` handles inflating views and adding them into the dialog view. As long as `init()` isn't invoked multiple times, there shouldn't be any issues with views being added when they already are owned by another parent.

**Comment by inteist** [comment]
So

1. We updated to 0.8.0.1 – SAME
2. We know how to reproduce the problem:

```java
        new OneAtATimeMaterialDialog.Builder(this)
                .title("title 1")
                .content("content 1")
                .positiveText("pos")
                .negativeText("neg")
                .cancelable(false)
                .build().show();

        new OneAtATimeMaterialDialog.Builder(this)
                .title("title 2")
                .customView(R.layout.custom_dialog_body, true)
                .negativeText("neg")
                .positiveText("pos")
                .cancelable(false)
                .build().show();
```

This:   `customView(R.layout.custom_dialog_body, true)` in dialog 2 seems to be the problem if it's just string with `content(String s)` then no problem.

custom view can probably be any view (we used this very simple one)

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:animateLayoutChanges="true"
              android:layout_width="match_parent"
              android:layout_height="match_parent">

    <TextView
        android:id="@+id/reminder_prompt"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@string/reminder_add_suggestion"
        android:textSize="16sp" />

</LinearLayout>
```

**Comment by inteist** [comment]
and it looks like we found the problem. It was indeed in our subclass. Sorry for the trouble.

**Comment by afollestad** [comment]
Glad you were able to figure it out

**Comment by mori-honest** [comment]
This issue is happening with custom layout given to the `.custom(View , boolean)` method with the latest release (v0.8.5.0).This is my code:

     
        View dialogView = getLayoutInflater().inflate(R.layout.dialog_details, null, false);
        mPriceDetailsDialog = new MaterialDialog.Builder(this)
                .positiveText(R.string.ok)
                .title(R.string.price_details)
                .customView(dialogView, false);

        questionMarkTextView.setOnClickListener(v -> mPriceDetailsDialog.show());

The first time user clicks and tries to show the dialog it works fine but the secound time it crashes the app:

    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:4273)
            at android.view.ViewGroup.addView(ViewGroup.java:4123)
            at android.view.ViewGroup.addView(ViewGroup.java:4095)
            at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:331)
            at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1289)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1294)

**Comment by afollestad** [comment]
@mori-honest hmm, weird. That should never happen. I implemented a workaround just in case though. You can reference the associated commit:

```Gradle
compile('com.github.afollestad.material-dialogs:core:af108e6045@aar') {
    transitive = true
}
```

If you're using `commons` too, the version should match that of the `core` module.
