### ISSUE TITLE
Add material - dialogs appear the following error

### ISSUE THREAD

**Issue by yy1300326388** [afollestad/material-dialogs#706]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         https://jitpack.io/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         flowerpotapp_ble:app:unspecified
         flowerpotapp_ble:app:unspecified > flowerpotapp_ble:hhcc_common:unspecified
   > Could not find com.android.support:support-annotations:23.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar
         https://jitpack.io/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom
         https://jitpack.io/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar
     Required by:
         flowerpotapp_ble:app:unspecified > com.afollestad.material-dialogs:core:0.8.0.0
   > Could not find com.android.support:support-v4:23.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
         https://jitpack.io/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://jitpack.io/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
     Required by:
         flowerpotapp_ble:app:unspecified > com.afollestad.material-dialogs:core:0.8.0.0
   > Could not find com.android.support:recyclerview-v7:23.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         https://jitpack.io/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         https://jitpack.io/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
     Required by:
         flowerpotapp_ble:app:unspecified > com.afollestad.material-dialogs:core:0.8.0.0
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         https://jitpack.io/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/Users/zsl/Downloads/android/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         flowerpotapp_ble:app:unspecified > com.afollestad.material-dialogs:core:0.8.0.0

**Comment by afollestad** [comment]
Use the Android SDK Manager on your laptop.
