### ISSUE TITLE
FolderSelectorDialog Addition

### ISSUE THREAD

**Issue by nicholaswilde** [afollestad/material-dialogs#707]
Now that you've broken up the project into core and commons components, I'd like to have a folder selector dialog added to commons, similar to the one in your example app.

**Comment by afollestad** [comment]
Will be in the next release in a few minutes

**Comment by nicholaswilde** [comment]
Thanks!

**Comment by afollestad** [comment]
You're welcome! There's a new section in the README for usage

https://github.com/afollestad/material-dialogs/releases/tag/0.8.1.0

**Comment by yudhir** [comment]
Is it possible to have it display Files too. preferably through builder.  File is the common abstraction for both files and folder.

**Comment by afollestad** [comment]
@yudhir no, it's called Folder Chooser Dialog for a reason. 

You could copy the FolderChooserDialog class and modify it pretty easily though.
