### ISSUE TITLE
Indeterminate progress drawable not visible

### ISSUE THREAD

**Issue by ashughes** [afollestad/material-dialogs#708]
I just updated to v0.8.0.1 and the indeterminate progress drawable is either not there, or it's invisible, or it's same color as the light dialog background. I also tested v0.8.0.0 with the same result. If I go back to v0.7.9.1, it works correctly. I tested on both M Preview 3 and Android 5.0.

**Comment by afollestad** [comment]
Odd. It works 100% of the time for me on 5.0 and 6.0.

**Comment by DreaminginCodeZH** [comment]
This should be the progurad issue DreaminginCodeZH/MaterialProgressBar#1, which is mentioned in #636.

Because `ObjectAnimator`s call by reflection, we need to manually configure proguard to ignore these classes before we have the `@Keep` annotation, as in [here](https://github.com/DreaminginCodeZH/MaterialProgressBar#proguard). A notice can be added to the README of this project.

**Comment by SandroMachado** [comment]
In my case I can confirm it is a proguard issue. Adding `-keep class com.afollestad.materialdialogs.** { *; }` to my proguard-rules.pro fixed the issue.

**Comment by ashughes** [comment]
I am indeed using proguard and I can confirm that adding the proguard rule fixes this issue.

Is it necessary to keep the entire library? Or is there a more targeted proguard rule that would suffice?

**Comment by SandroMachado** [comment]
Just this worked for me:
```
-keep class com.afollestad.materialdialogs.internal.progress.** { *; }
```

**Comment by afollestad** [comment]
There's gotta be a better way, there's a lot of people already using this release and most people won't know they need to include proguard rules.

**Comment by ashughes** [comment]
I haven't verified this, but the Google Play Services documentation makes it sound like they include their proguard rules in the library itself, so the implementing project does not need to. See the note below the table breaking down the different parts of Google Play Services on this page: https://developers.google.com/android/guides/setup

> Note: ProGuard directives are included in the Play services client libraries to preserve the required classes. The Android Plugin for Gradle automatically appends ProGuard configuration files in an AAR (Android ARchive) package and appends that package to your ProGuard configuration. During project creation, Android Studio automatically creates the ProGuard configuration files and build.gradle properties for ProGuard use. To use ProGuard with Android Studio, you must enable the ProGuard setting in your build.gradle buildTypes. For more information, see the ProGuard guide.

**Comment by afollestad** [comment]
@ashughes oh wow, it'd be great if that works.

Can someone test if including the `keep` rule in the `core` module's proguard-rules.pro file works?

This will use the commit I just made:

```
dependencies {
    compile('com.afollestad.material-dialogs:core:2c8b12b824@aar') {
        transitive = true
    }
}
```

**Comment by SandroMachado** [comment]
Hum, not working here. 
The indeterminate progress drawable stills not visible using the import with the commit hash.

**Comment by afollestad** [comment]
I think I figured out why: http://stackoverflow.com/a/30801516

One second, I'll have another commit to try in a second.

**Comment by afollestad** [comment]
How about this?

```java
dependencies {
    compile('com.afollestad.material-dialogs:core:b65f1056b4@aar') {
        transitive = true
    }
}
```

**Comment by ashughes** [comment]
I'm still waiting for my gradle to sync so I can test it, but I was just looking at the commit and saw that you might have added more to `build.gradle` than is needed. I found these links:

https://plus.google.com/+IanLake/posts/1HfDuFFkMXG
https://gist.github.com/danielgomezrico/0e860960590af04d3a45

It sounds like all is needed for a library is that single `consumerProguardFiles` line. Rather than enabling proguard in both the debug and release builds.

Also, I saw that you changed the proguard rules. It seems like `-keep class com.afollestad.materialdialogs.internal.progress.** { *; }` would be the least "intrusive".

**Comment by afollestad** [comment]
For now, I was testing it with debug too, to make sure it works.

If I only include `-keep class com.afollestad.materialdialogs.internal.progress.** { *; }`, I get a bunch of errors saying that various classes and interfaces throughout the library cannot be found.

**Comment by ashughes** [comment]
Hmm. The `b65f1056b4 commit did not work for me.

**Comment by ashughes** [comment]
I was reading http://stackoverflow.com/a/27052696/287575 and I'm wondering if the issue is because you're including `minifyEnabled true`. Can you try removing the `buildTypes` section and just add the single `consumerProguardFiles 'proguard-rules.pro'` line to `defaultConfig` and I can test that?

**Comment by afollestad** [comment]
@ashughes 

```Gradle
dependencies {
    compile('com.afollestad.material-dialogs:core:354cbe9316@aar') {
        transitive = true
    }
}
```

**Comment by ashughes** [comment]
That worked! :)

**Comment by ashughes** [comment]
From how I understand it, the `consumerProguardFiles` only needs to include the rules that are necessary for *this* library, no need to include `proguard-android.txt` as the application using the library will do this.

And since `-keep class com.afollestad.materialdialogs.internal.progress.** { *; }` seemed to work before, I would suggest changing your `proguard-rules.pro` file to just include this line.

Here's some more links I found on the topic from the Google team:

http://stackoverflow.com/a/22639821/287575
https://android.googlesource.com/platform/tools/build/+/ef84df96b7b1a26a96a37506d95e3d427ee830ed/tests/libProguardConsumerFiles
https://groups.google.com/forum/#!topic/adt-dev/BUIV_FDpq28

I would also suggest mentioning in your README that the proguard rules are taken care of by the library.

I'm really excited that this is possible! Will make it much easier to deal with dependencies and proguard in the future.

**Comment by afollestad** [comment]
@ashughes thanks for all the information!

Just to make sure everything is alright for a release, can you test this one more time?

```Gradle
dependencies {
    compile('com.afollestad.material-dialogs:core:8d203ec223@aar') {
        transitive = true
    }
}
```

**Comment by SandroMachado** [comment]
@afollestad it is working fine for me (8d203ec223).

**Comment by ashughes** [comment]
Yup, it's working! :)

I just had one more comment after looking through the commit. It shouldn't be necessary to reference `progress-proguard.txt` in the sample app's `build.gradle` since that's already done by the core library.

**Comment by afollestad** [comment]
@ashughes woops, that's supposed to reference the sample app's own proguard file (which contains some rules that fix common Samsung issues with AppCompat).

Thanks for the help!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.1.0

**Comment by SandroMachado** [comment]
Great work :+1:

**Comment by afollestad** [comment]
Looks like another related issue popped 

https://github.com/afollestad/material-dialogs/issues/714
