### ISSUE TITLE
Change Button ripple color

### ISSUE THREAD

**Issue by Anth06ny** [afollestad/material-dialogs#709]
How can I change the ripple color ?
It's gray.
The button is the color of ColorAccent, it's ok but for the ripple ?

Thank you

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#selectors

**Comment by Anth06ny** [comment]
I have to create selector, I can not just pass the color?

**Comment by afollestad** [comment]
Yeah, changing the color that only applies above Lollipop wasn't a
necessary feature IMO.

You may want to look into the theme attribute that ripples get their color
from. You can change it globally in your app if you wanted to.

On Wed, Sep 23, 2015, 10:06 AM Anth06ny <notifications@github.com> wrote:

> I have to create selector, I can not just pass the color?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/709#issuecomment-142632641>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by Anth06ny** [comment]
I already change the ripple color in all application
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
       <item name="colorButtonNormal">@color/color_composant_main</item>
        
        <item name="colorAccent">@color/color_composant_main</item>
        <item name="colorControlNormal">@color/color_composant_main</item>
        <item name="colorControlActivated">@color/color_composant_main_highlighted</item>
        <item name="colorControlHighlight">@color/color_composant_main_highlighted</item>
 </style>

But it's not apply on your library

**Comment by afollestad** [comment]
In the next release, it will correctly use the `colorControlHighlight` value for ripples. 

I'll actually just add a way to manually set it, too. Thanks for the suggestion.

**Comment by afollestad** [comment]
When I publish the next release, it will respect the `controlColorHighlight` attribute from your Activity theme.

You will also be able to use a new `md_btn_ripple_color` attribute specifically for this library, and you'll be able to set it from the `Builder` (`buttonRippleColor(int)`, `buttonRippleColorRes(int)`, `buttonRippleColorAttr(int)`).

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.1.0

**Comment by Anth06ny** [comment]
Thanks for your reactivity.

**Comment by Anth06ny** [comment]
Be carreful it's "colorControlHighlight" and not "controlColorHighlight" in your release text.

It's working great job
