### ISSUE TITLE
Parallax effect

### ISSUE THREAD

**Issue by ekuleshov** [afollestad/material-dialogs#710]
It would be neat to be able to enable a parallax effect on material dialogs. So, an active dialog would move slightly in response to tilting device, so you could see behind it.

**Comment by afollestad** [comment]
I don't think this is a necessary feature.

You could probably implement it yourself with a subclass or something.

**Comment by ekuleshov** [comment]
I would if I'd know how to approach that... Too bad you find it not interesting.

**Comment by afollestad** [comment]
Things that aren't commonly used by many shouldn't go directly in the library, it increases the size of the library thus increasing the size of other people's apps.

I'm not sure if it's possible, but you'd need to use the accelerometer to monitor device rotation (which consumes battery), and then you'd need to move the dialog around on the screen using X and Y coordinates based on the sensor data.
