### ISSUE TITLE
JitPack issue

### ISSUE THREAD

**Issue by ashughes** [afollestad/material-dialogs#711]
I'm really puzzled how this was working before, but your gradle dependencies for JitPack are missing the "github" portion:

```
compile('com.github.afollestad.material-dialogs:core:0.8.1.0@aar') {
    transitive = true
}
compile('com.github.afollestad.material-dialogs:commons:0.8.1.0@aar') {
    transitive = true
}
```

I was previously using what you had in your README before the latest release (with "github" between "com" and "afollestad"), but it kept not finding the latest release. After I changed the dependencies to the above lines, everything work correctly.

**Comment by afollestad** [comment]
`com.afollestad` is my custom domain, it redirects to the same as above. No issues on my end.

**Comment by afollestad** [comment]
https://jitpack.io/#afollestad/material-dialogs

**Comment by ashughes** [comment]
Ah, I didn't realize you could do that. Makes sense. It's working for me now. The issue was just with the latest build, so I'm guessing the custom domain just takes a little longer for some reason...

**Comment by afollestad** [comment]
That's possible, although it worked for me seconds after publishing :)

You're welcome!
