### ISSUE TITLE
Failed to add project

### ISSUE THREAD

**Issue by f3r10** [afollestad/material-dialogs#713]
Hello
I tried to add the project but I get this error:

Error:(42, 13) Failed to resolve: com.afollestad.material-dialogs:core:0.8.0.1

Any suggestions??
Thanks

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
