### ISSUE TITLE
Indeterminate progress drawable still not visible in v0.8.1.0

### ISSUE THREAD

**Issue by zouliping** [afollestad/material-dialogs#714]
I have tested on Android 4.4.4 and 5.1.1, indeterminate progress drawable was not showed as expected. As [#708](https://github.com/afollestad/material-dialogs/issues/708) mentioned, it should work, but this problem still existed in my devices.

And In my logcat, some error log appeared when material dialog first showed.

```Gradle
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.afollestad.materialdialogs.MaterialDialog.getButtonSelector
```

In my gradle file,

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.1.0@aar') {
    transitive = true
}
```

I already cleaned cache, and ran `gradle clean` to get the latest version.

Is there some wrong with me?

**Comment by afollestad** [comment]
@zouliping can you check if this version fixes the issue for you?

```Gradle
compile('com.afollestad.material-dialogs:core:2e4f388992@aar') {
    transitive = true
}
```

**Comment by zouliping** [comment]
No, it is still invisible. But the error log disapppeared.

**Comment by doc-rj** [comment]
I'm seeing this as well:

09-28 10:32:31.340  10451               dalvikvm  E  Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.afollestad.materialdialogs.MaterialDialog.getButtonSelector
09-28 10:32:31.340  10451               dalvikvm  W  VFY: unable to resolve instanceof 183 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/afollestad/materialdialogs/MaterialDialog;
09-28 10:32:31.340  10451               dalvikvm  D  VFY: replacing opcode 0x20 at 0x006f
09-28 10:32:31.340  10451               dalvikvm  E  Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.afollestad.materialdialogs.MaterialDialog.getButtonSelector
09-28 10:32:31.340  10451               dalvikvm  W  VFY: unable to resolve instanceof 183 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/afollestad/materialdialogs/MaterialDialog;
09-28 10:32:31.340  10451               dalvikvm  D  VFY: replacing opcode 0x20 at 0x00b3
09-28 10:32:31.340  10451               dalvikvm  E  Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.afollestad.materialdialogs.MaterialDialog.getButtonSelector
09-28 10:32:31.340  10451               dalvikvm  W  VFY: unable to resolve instanceof 183 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/afollestad/materialdialogs/MaterialDialog;
09-28 10:32:31.340  10451               dalvikvm  D  VFY: replacing opcode 0x20 at 0x00f9
09-28 10:32:31.340  10451               dalvikvm  I  Could not find method android.view.ViewGroup.<init>, referenced from method com.afollestad.materialdialogs.internal.MDRootLayout.<init>
09-28 10:32:31.340  10451               dalvikvm  W  VFY: unable to resolve direct method 12587: Landroid/view/ViewGroup;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
09-28 10:32:31.340  10451               dalvikvm  D  VFY: replacing opcode 0x70 at 0x0001
09-28 10:32:31.344  10451               dalvikvm  I  Could not find method android.widget.TextView.<init>, referenced from method com.afollestad.materialdialogs.internal.MDButton.<init>
09-28 10:32:31.344  10451               dalvikvm  W  VFY: unable to resolve direct method 13446: Landroid/widget/TextView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
09-28 10:32:31.344  10451               dalvikvm  D  VFY: replacing opcode 0x70 at 0x0000

**Comment by afollestad** [comment]
@doc-rj the commit in a comment above fixes that error.

**Comment by doc-rj** [comment]
Thanks. Will that commit make it into an "official" point release soon?

**Comment by afollestad** [comment]
@doc-rj well the issue creator said it made that error go away but it still doesn't work. So it's not quite ready yet.

**Comment by afollestad** [comment]
I haven't been able to reproduce this issue.

**Comment by zouliping** [comment]
@afollestad This is newest result. All my test on your latest version 0.8.2.0.

In Nexus 7 with Android 5.1.1:
If I set parameters,  like `md_background_color, md_title_color, md_content_color, md_positive_color, md_negative_color, md_widget_color`, the drawable won't show.
If all parameters are not been set, the drawable is visible.

And in MI 3 with Android 4.4.4:
The drawable is invisible whether the parameters was being set or not.

Hope these information would help.

**Comment by zouliping** [comment]
@afollestad  Sorry, it would be my mistake. When data loads quickly(just one or two second), the drawable is going to show but the dialog is being dismissed. So it looks like the drawable is invisible. When data loads slowly, it is ok.
