### ISSUE TITLE
Error com.afollestad.material-dialogs:core:0.8.0.1 grable not he is going

### ISSUE THREAD

**Issue by SuleymanovTat** [afollestad/material-dialogs#716]
Error:(47, 13) Failed to resolve: com.afollestad.material-dialogs:core:0.8.0.1
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by afollestad** [comment]
View the many duplicates of this issue and the README.

**Comment by SuleymanovTat** [comment]
Thank you

**Comment by romero18** [comment]
Hello There,
iam having the problem and i cant solve it anyone can assist me please, error below,

Error:(26, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.8.1

**Comment by afollestad** [comment]
@romero18 that's not the correct format:

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.5.8@aar') {
    transitive = true
}
```

You should be using `com.github.afollestad.material-dialigs:core` for the core module,  and `com.github.afollestad.material-dialigs:commons` for the commons module. The latest version is 0.8.5.8, and you need `@aar` at the end of the dependency. This is all shown on the front page of this repository.

**Comment by romero18** [comment]
@afollestad Thank you 
iam still geting the same error 

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.traex.rippleeffect:library:1.3'
    compile 'com.makeramen:roundedimageview:2.1.1'
    compile('com.github.afollestad.material-dialogs:core:0.8.5.8@aar') {
        transitive = true
    }
    compile 'com.github.ksoichiro:android-observablescrollview:1.5.2'
    compile project(':material_preferences_library')
    compile 'com.lsjwzh:materialloadingprogressbar:0.5.6-RELEASE'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'net.i2p.android.ext:floatingactionbutton:1.10.0'
    compile 'com.mikepenz:iconics-core:1.7.4@aar'
    compile 'com.mikepenz:google-material-typeface:1.2.0.1@aar'
    compile 'com.github.mrengineer13:snackbar:1.2.0'
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.google.android.gms:play-services:7.8.0'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile project(':circular_bar_pager_library')
}

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by thuantran293** [comment]
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
    maven { url "https://jitpack.io" }
    maven { url 'https://maven.fabric.io/public' }
    jcenter()
}

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode rootProject.versionCode
        versionName rootProject.versionName
        multiDexEnabled = true
    }

//     before release need to enable Crashlytics

    signingConfigs {
        release {
            storeFile file(property('prodStoreFile'))
            storePassword property('prodStorePassword')
            keyAlias property('prodKeyAlias')
            keyPassword property('prodKeyPassword')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            ext.enableCrashlytics = true
            signingConfig signingConfigs.release
            buildConfigField "String", "APP_ID", property('prodAppID')
            buildConfigField "String", "AUTH_KEY", property('prodAuthKey')
            buildConfigField "String", "AUTH_SECRET", property('prodAuthSecret')
            buildConfigField "String", "ACCOUNT_KEY", property('prodAccountKey')
            buildConfigField "String", "PUSH_REGISTRATION_APP_ID", property('prodPushRegistrationAppID')
            buildConfigField "String", "TWITTER_KEY", property('prodTwitterDigitsConsumerKey')
            buildConfigField "String", "TWITTER_SECRET", property('prodTwitterDigitsConsumerSecret')
            resValue "string", "twitterDigitsApiKey", property('prodTwittedDigitsApiKey')
            resValue "string", "facebookAppId", property('prodFacebookAppID')
        }

        debug {
            debuggable true
            ext.enableCrashlytics = false
            versionNameSuffix ' (debug)'
            buildConfigField "String", "APP_ID", property('devAppID')
            buildConfigField "String", "AUTH_KEY", property('devAuthKey')
            buildConfigField "String", "AUTH_SECRET", property('devAuthSecret')
            buildConfigField "String", "ACCOUNT_KEY", property('devAccountKey')
            buildConfigField "String", "PUSH_REGISTRATION_APP_ID", property('devPushRegistrationAppID')
            buildConfigField "String", "TWITTER_KEY", property('devTwitterDigitsConsumerKey')
            buildConfigField "String", "TWITTER_SECRET", property('devTwitterDigitsConsumerSecret')
            resValue "string", "twitterDigitsApiKey", property('devTwittedDigitsApiKey')
            resValue "string", "facebookAppId", property('devFacebookAppID')
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    lintOptions {
        abortOnError false
    }

    applicationVariants.all { variant ->
        changeApkFileName(variant)
    }
}

dependencies {
    compile project(':Q-municate_core')

    compile "com.android.support:multidex:${rootProject.multiDexVersion}"
    compile "com.android.support:appcompat-v7:${rootProject.supportVersion}"
    compile "com.android.support:design:${rootProject.supportVersion}"
    compile "com.android.support:recyclerview-v7:${rootProject.supportVersion}"

    compile "com.google.android.gms:play-services-base:${rootProject.googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-gcm:${rootProject.googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-analytics:${rootProject.googlePlayServicesVersion}"

    compile "com.nostra13.universalimageloader:universal-image-loader:${rootProject.universalImageLoaderVersion}"
    compile 'com.flurry.android:analytics:6.2.0'
    compile "com.jakewharton:butterknife:${rootProject.butterknifeVersion}"
    compile "com.afollestad:material-dialogs:${rootProject.materialDialogsVersion}"
    compile "com.github.orangegangsters:swipy:${rootProject.swipyRecyclerviewVersion}@aar"
    compile "com.timehop.stickyheadersrecyclerview:library:${rootProject.stickylistheadersRecyclerViewVersion}@aar"
    compile "com.rockerhieu.emojicon:library:${rootProject.emojiconVersion}"
    compile "com.soundcloud.android:android-crop:${rootProject.cropVersion}@aar"
    compile "com.afollestad:material-dialogs:0.9.9.4"
    compile('com.android.support:cardview-v7:23.4.0') {
        force = true
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.6.2@aar') {
        transitive = true;
    }
}

def changeApkFileName(variant) {
    variant.outputs.each { output ->
        def file = output.outputFile
        def newName = 'QMUN_Android_v.' + rootProject.versionName + '_c.' + rootProject.versionCode + '-' + variant.buildType.name + '.apk'
        output.outputFile = new File(file.parent, newName)
    }
}

I do it the same you, but android studio was error "Failed to resolve: com.afollestad:meterial-dialogs:0.9.4"
