### ISSUE TITLE
How can I change the ui when a materialDialog has been built?

### ISSUE THREAD

**Issue by Leaking** [afollestad/material-dialogs#719]
I want to show Indeterminate progress in a materialDialog when I send request to the server,After i get data from the network I want to replace the Indeterminate progress with a single-choice list.

How can I change the ui when a materialDialog has been built

**Comment by afollestad** [comment]
This is kind of a duplicate of another very old issue, but you can't.

You'll need to dismiss the first dialog and show a second.
