### ISSUE TITLE
Element is not allowed here in prerference xml.

### ISSUE THREAD

**Issue by vertigra** [afollestad/material-dialogs#721]
Hello. After update 0.7.9.1 -> 0.8.1.0 android studio issues warnings in xml preferences  "Element (element name) is not allowed here". For all preferences element. But all works (dont`t fully test).

**Comment by afollestad** [comment]
You should read the change log for 0.8.0.0

**Comment by afollestad** [comment]
To be more specific, you need the *commons* package.

**Comment by vertigra** [comment]
Thank you, I use it. Added  for element.
