### ISSUE TITLE
No strings.xml in commons exploded aar

### ISSUE THREAD

**Issue by daniele-athome** [afollestad/material-dialogs#722]
I'm using latest Android Studio (canary channel) with latest SDK build tools (same configuration as your library, but with target sdk 23), and got errors when assembling with proguard:

```Gradle
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_done_label' in program class com.afollestad.materialdialogs.commons.R$string
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_back_label' in program class com.afollestad.materialdialogs.commons.R$string
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_cancel_label' in program class com.afollestad.materialdialogs.commons.R$string
```

And then, after the long stacktrace, this one (which I guess is a conseguence of the above):

```Gradle
Error:Execution failed for task ':app:packageGoogleplayDebug'.
> Unable to compute hash of /home/daniele/Development/kontalk/androidclient-master/app/build/intermediates/classes-proguard/googleplay/debug/classes.jar
```

I'm using your library latest versions:

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.1.0@aar') {
  transitive = true
}
compile('com.afollestad.material-dialogs:commons:0.8.0.1@aar') {
  transitive = true
}
```

I've noticed that when I look into the build/intermediates/exploded-aar directory, I can't find strings.xml in commons, which should contains those values. The only directory in res I can find in there is layout.

The sources I'm using are hosted here, this is the commit tree:
https://github.com/kontalk/androidclient/tree/b24eda33e732810edace6980eabd4c47d2cb109a

Thanks for this great library by the way!

**Comment by daniele-athome** [comment]
Introducing strings.xml manually into exploded-aar leads to unpredictable behaviour such as mixing resource IDs and crashes :-(

**Comment by daniele-athome** [comment]
A very dirty workaround for proguard:

```
-dontwarn com.afollestad.materialdialogs.color.**
```

To be used obviously only if you don't use the color picker dialog.

**Comment by afollestad** [comment]
Unfortunately I can't reproduce this issue. There must be something wrong on your end.

I use this library is 5 production apps, a few use the color chooser, a few don't.

**Comment by daniele-athome** [comment]
I'm sorry, I can't give you any more data right now. I'll reopen the issue if I can find out something. Thanks anyway.

**Comment by romulof** [comment]
I'm having exactly the same problem here.
```
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_done_label' in program class com.afollestad.materialdialogs.commons.R$string
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_back_label' in program class com.afollestad.materialdialogs.commons.R$string
Warning:com.afollestad.materialdialogs.color.ColorChooserDialog$Builder: can't find referenced field 'int md_cancel_label' in program class com.afollestad.materialdialogs.commons.R$string
```

**Comment by romulof** [comment]
I just found out the problem. On readme.md you say:

```
dependencies {
    compile('com.afollestad.material-dialogs:core:0.8.1.0@aar') {
        transitive = true
    }
}
```

and

```
dependencies {
    compile('com.afollestad.material-dialogs:commons:0.8.0.1@aar') {
        transitive = true
    }
}
```

The versions are mismatching, so I changed to 8.1.0 on both and problem solved.

**Comment by daniele-athome** [comment]
I can't believe I've missed that. Thanks @romulof, I'll try it again later today.
