### ISSUE TITLE
Floating search dialog

### ISSUE THREAD

**Issue by rshah** [afollestad/material-dialogs#723]
Is it possible to create floating search dialog like in Google I/O 2015 app?
I imagine this might be related to custom title view for dialog.

**Comment by afollestad** [comment]
Not 100% sure what you mean, but this library is only intended to implement Materialized versions of AlertDialogs. Nothing more.

**Comment by rshah** [comment]
I'm trying to display search dialog like in Google I/O 2015 app.
Like in this screenshot.
http://i.stack.imgur.com/sTgSN.jpg

For the content, i think it's possible to use custom view for the dialog.
But i'm not sure about the top part which contains "Search session". 
Wether it should be a custom title view or make it part of the custom view as in the dialog content too.

**Comment by afollestad** [comment]
Oh okay, that'd require you to make a custom view. It wouldn't be too difficult actually ☺

**Comment by rshah** [comment]
I see, thank you very much.
