### ISSUE TITLE
Build error after I bump version to 0.8.1.0

### ISSUE THREAD

**Issue by riyaz** [afollestad/material-dialogs#725]
When I bump the version of MD i get below error, I use support libs with version `23.0.1`

```
Module 'com.afollestad:material-dialogs:0.8.1.0' depends on one or more Android Libraries but is a jar
```

**Comment by afollestad** [comment]
Read here: https://github.com/afollestad/material-dialogs#core

**Comment by riyaz** [comment]
Opps I missed `@aar`. Thanks
