### ISSUE TITLE
try to build dialog twice

### ISSUE THREAD

**Issue by agromilo** [afollestad/material-dialogs#728]
Hi,
I build material dialog on resume,  show in needed case, dismiss by pause or user action.
But have next strange behavior:
1. create MaterialDialog as MaterialDialog.Builder.build() on resume ny activity
2. show dialog by MaterialDialog.show()
3. dismiss dialog and start new activity
4. do something in new activity and close it
5. step1 again
6. step2 again
and get "MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden." (100% reproduce)

this is not reproduce if show other dialog before original.

What I do incorrectly ?

**Comment by afollestad** [comment]
This exception occurs from an Android error: http://stackoverflow.com/questions/4343393/badtokenexception

There's nothing I can do to change it.

It means your dialog tries attaching to a `Context` that isn't an `Activity`, or an `Activity` that isn't fully visible or was recently closed. I'd recommend using a `DialogFragment` to wrap your `Dialog`, that should help avoid this.

**Comment by agromilo** [comment]
Found for decision:
- create dialog on start activity and set check dialog for null:
@Override
public void onStart() {
        super.onStart();
        if(dialog== null) {
                dialog = MaterialDialog.Builder.build()
        }
}

- remove create on resume

bug is not reproduce more

**Comment by hardikramoliya** [comment]
I have created dialog onCreate method : 

Builder mdMash = new MaterialDialog.Builder(mContext)
.title("Start Mash").titleGravity(GravityEnum.CENTER)
.contentGravity(GravityEnum.CENTER).cancelable(false)
.content("").positiveText("OK").negativeText(null)
.callback(new MaterialDialog.ButtonCallback() {
@Override
public void onPositive(MaterialDialog dialog) {
						dialog.dismiss();
	}
	});

mdMash.show();

But every time i got this error on only Android (6.0 - marshmallow). why this happens?

10-13 19:32:53.357: W/System.err(25519): com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
10-13 19:32:53.357: W/System.err(25519): 	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1375)
10-13 19:32:53.357: W/System.err(25519): 	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1360)
10-13 19:32:53.358: W/System.err(25519): 	at com.sessions.ACT_ActiveSession$ActiveSessionExpanDrawerAdapter$6.onClick(ACT_ActiveSession.java:4802)
10-13 19:32:53.358: W/System.err(25519): 	at android.view.View.performClick(View.java:5198)
10-13 19:32:53.358: W/System.err(25519): 	at android.view.View$PerformClick.run(View.java:21147)
10-13 19:32:53.358: W/System.err(25519): 	at android.os.Handler.handleCallback(Handler.java:739)
10-13 19:32:53.358: W/System.err(25519): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 19:32:53.358: W/System.err(25519): 	at android.os.Looper.loop(Looper.java:148)
10-13 19:32:53.358: W/System.err(25519): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-13 19:32:53.358: W/System.err(25519): 	at java.lang.reflect.Method.invoke(Native Method)
10-13 19:32:53.358: W/System.err(25519): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-13 19:32:53.358: W/System.err(25519): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jjvargas** [comment]
I had the same problem,  I was using the ApplicationContext rather than the Activity itself as a Context. What is your mContext ?

**Comment by agromilo** [comment]
try to move creating alert from onCreate to onStart or onResume as in my original case.

**Comment by cyberrob** [comment]
With an activity containing fragment and the __fragment showing the dialog__ like this

````
@Override
public void onResume() {
    super.onResume();
    if (loadingDialog == null) {
        loadingDialog = UIUtils.getLoadingDialog(getActivity(), getString(R.string.api_loading), false);
    }
    
    //if(isVisible())
    loadingDialog.show();
}

````
First time the dialog will show, everything works fine. But the second time  `loadingDialog.show();` will crash the app. 

With breakpoint I found 
- the first time `isVisible()` is true 
- but second time `isVisible()` is false!  

which is why the app crash. Add `isVisible()` check could be a solution.

**Comment by raquezha** [comment]
I've used "NameOfActivity.this" on context parameter and it worked!

**Comment by eleree** [comment]
@raquezha works for me.

**Comment by MSF-Jarvis** [comment]
@raqueza, thanks, worked for me too! I had been stuck on this for about a week lol

**Comment by somehand** [comment]
I resolved it by confirm that Activity hasWindowFocus. because i only got the context, in the fragment, instead of exactly which Activity it is.
```
if (((Activity) mContext).hasWindowFocus()) {
			mDialog.show();
		}
```

**Comment by pixelbendr** [comment]
try `if(context instanceof Activity){ //show dialog}`

**Comment by JosueSaul20** [comment]
Thank you @raquezha
