### ISSUE TITLE
Error Checks before closing Dialog

### ISSUE THREAD

**Issue by pixelbendr** [afollestad/material-dialogs#731]
Am using google new material design text input layout as custom view and I want to validate input before closing the dialog however when I click the positive button the dialog closes without validation. How do I control the dialog not closing till I want it to?

**Comment by Servus7** [comment]
Take a look at the Readme.md

*"If autoDismiss is turned off, then you must manually dismiss the dialog in the callback. Auto dismiss is on by default."*

Set autoDismiss to false when creating the Dialog:
``` java
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .autoDismiss(false)
                .build();
```

Later you can close the dialog by calling dismiss on the instance:
``` java
materialDialog.dismiss();
```

**Comment by pixelbendr** [comment]
Thanks for this.

**Comment by pixelbendr** [comment]
Please one more thing, how do I show the keyboard when the dialog is showing.

**Comment by Servus7** [comment]
This question is not specific for the material dialogs. Please try to find a solution using google or StackOverflow next time. For examle: http://stackoverflow.com/a/2418314

**Comment by pixelbendr** [comment]
ok. thanks
