### ISSUE TITLE
How set the Radius Corner of the dialog

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#732]
Hi,
  I override the md_bg_corner_radius in my project dimension, but there is still a white backgroung behind. Probably the Dialog backround shape. Who to do to just use a specific shape only for the md_dialog without changing else. I set the whole configuration in my AppTheme as described in the readMe.

**Comment by afollestad** [comment]
You can currently change the background color of dialogs, but changing the radius isn't planned.

**Comment by afaucogney** [comment]
Ok, but do you have a idea if I can override something to succeed doing that, even if the way is not perfect.

**Comment by afollestad** [comment]
@afaucogney this line might help you: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/DialogInit.java#L81

**Comment by bab55z** [comment]
hi guys i found a simple workaround
`<dimen name="md_action_corner_radius" tools:override="true">10dp</dimen>
    <dimen name="md_bg_corner_radius" tools:override="true">6dp</dimen>`
