### ISSUE TITLE
Make item checked 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [afollestad/material-dialogs#733]
How to make Radio button checked when I show dialog  
I changed your library a little to do that but I wonder if you provide this feature ??
Thanks for great lib :+1:

**Comment by afollestad** [comment]
You should read the README on the front page or look at the same project.

**Comment by mahmoud-elnaggar** [comment]
this line from README 
.itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {

first parameter is selected index but I'm using itemsCallbackSingleChoice that hasn't selectedIndex parameter so I asked about it 
it seems I'm using an older version , Right ??

**Comment by afollestad** [comment]
Yeah I'm guessing you have an old version of the library or something.
