### ISSUE TITLE
Add ability to specify item IDs when making a List Dialog

### ISSUE THREAD

**Issue by timrae** [afollestad/material-dialogs#734]
If I want to build a list dialog that has a variable number of items, then I currently need to internally keep track of which item the position variable `which` corresponds to in the ListCallback. It would be nice if we could give the strings that we provide some identifiers to enable a pattern like this:

```java
new MaterialDialog.Builder(this)
        .title(R.string.title)
        .items(R.array.items, R.array.itemIds)
        .itemsCallback(new MaterialDialog.ListCallback() {
            @Override
            public void onSelection(MaterialDialog dialog, View view, int which, int itemId, CharSequence text) {
                switch (itemId) {
                
                }
            }
        })
        .show();
```

**Comment by afollestad** [comment]
I don't think this is a necessary feature to have in the library.

I'd recommend making a simple custom adapter implementation for your dialogs that holds IDs for items. Otherwise, you could also keep a separate array of IDs that you can re-associate by index later.

**Comment by timrae** [comment]
@afollestad
I disagree, most APIs have this kind of functionality (including all of the standard Android APIs). The way I originally said to do it was pretty dumb (I was just trying to get across the concept), so I've edited the code in my question to an actual suggested API. 

If you do it this way, all you need to do is add a few methods to the builder and change a few lines in `DefaultAdapter` to something like this:

``` java
    @Override
    public long getItemId(int position) {
        // not sure if this is even necessary, I haven't really thought about it
        if (dialog.mBuilder.itemIds != null) {
            return dialog.mBuilder.itemIds[index];
        else {
            return position;
        }
    }

    @SuppressLint("WrongViewCast")
    @Override
    public View getView(final int index, View view, ViewGroup parent) {
        if (view == null)
            view = LayoutInflater.from(dialog.getContext()).inflate(layout, parent, false);

        TextView tv = (TextView) view.findViewById(R.id.title);

        // All of the other stuff in this method

        view.setTag(index + ":" + dialog.mBuilder.items[index]);
        if (dialog.mBuilder.itemIds != null) {
            view.setId(dialog.mBuilder.itemIds[index]);
        }

        // All of the other stuff in this method

        return view;
    }
```

**Comment by afollestad** [comment]
@timrae I added this functionality with the latest commits. You can reference them through Gradle with the commit hash:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core: cedc34bdce@aar') {
        transitive = true
    }
}
```

I added some details to the README here: https://github.com/afollestad/material-dialogs#assigning-ids-to-list-item-views

**Comment by afollestad** [comment]
@timrae I added this functionality with the latest commits. You can reference them through Gradle with the commit hash:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:cedc34bdce@aar') {
        transitive = true
    }
}
```

I added some details to the README here: [Assigning IDs to List Item Views](https://github.com/afollestad/material-dialogs#assigning-ids-to-list-item-views)

**Comment by timrae** [comment]
Thank you!!!
