### ISSUE TITLE
Enhancement request: Get a Material Dialog's current instance that is showing over an activity?

### ISSUE THREAD

**Issue by dhiraj** [afollestad/material-dialogs#736]
There is no central way to get to the current dialog that is showing, or I have not been able to figure out a way to do this. I've had to manually code up a central Material Dialog instance in my Application subclass, and then global methods to check and dismiss any current material dialog instance when any Activity is stopping (because otherwise it leaks), or when a new dialog needs to be shown. I show a modal Material Dialog spinner while my Internet fetch operation is ongoing.

Is there any way to determine if any dialog is showing over an Activity? Alternatively, if there's a way to get use Material Dialogs in a... singleton way?

Or can they be auto-dismissed when the Activity context is dying, the way that say image fetching libraries (like Universal Image Loader) would stop downloading an image when the cell that the image is going to be displayed on is going to be recycled?

**Comment by afollestad** [comment]
You'll have to make your own implementation for this.

Either using a singleton in your `Activity`:

```java
public class MainActivity extends Activity {

    private static MaterialDialog mDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mDialog = new MaterialDialog.Builder(this)
                .title("Hello")
                .content("Hi")
                .dismissListener(new DialogInterface.OnDismissListener() {
                    @Override
                    public void onDismiss(DialogInterface dialog) {
                        mDialog = null;
                    }
                }).build();
    }
}
```

Or you could use `DialogFragments`:

```java
public class MainActivity extends Activity {

    private final static String TAG = "[MY_DIALOG]";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MyDialog dialog = MyDialog.create("Hello", "Hi");
        dialog.show(getFragmentManager(), TAG);
    }

    private MyDialog getActiveDialog() {
        return (MyDialog) getFragmentManager().findFragmentByTag(TAG);
    }

    /*
     *  DialogFragment class, could go in a separate file
     */
    public static class MyDialog extends DialogFragment {

        public static MyDialog create(String title, String content) {
            MyDialog dialog = new MyDialog();
            Bundle args = new Bundle();
            args.putString("title", title);
            args.putString("content", content);
            dialog.setArguments(args);
            return dialog;
        }

        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            return new MaterialDialog.Builder(getActivity())
                    .title(getArguments().getString("title"))
                    .content(getArguments().getString("content"))
                    .build();
        }
    }
}
```

A big plus to DialogFragments is that they survive orientation changes; they remain open when you rotate your phone, and the arguments (in the `Bundle` remain so the dialog can rebuild itself).

**Comment by afollestad** [comment]
Notice the `getActiveDialog()` method in the second example retrieves the Dialog from the Activity's `FragmentManager`. It can be null if the dialog hasn't be shown yet.

**Comment by crysan** [comment]
You can bring advanced example of creating and working with DialogFragment customView?
