### ISSUE TITLE
How to create a simple Yes or No dialog

### ISSUE THREAD

**Issue by nologinatgit** [afollestad/material-dialogs#738]
The documentation is very verbose but I can't find any working example of how to create a Yes or No dialog.

I can set the button's text:
<pre>
new MaterialDialog.Builder(this)
        .title(R.string.title)
        .content(R.string.content)
        .positiveText(R.string.agree)
        .negativeText(R.string.disagree)
        .show();
</pre>
But this does nothing with the selection.

I could set a callback:

<pre>
new MaterialDialog.Builder(this)
    .onPositive(new MaterialDialog.SingleButtonCallback() {
        @Override
        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
            // TODO
        }
    });
</pre>

This does not work anymore as of version 0.8.1. as it couldn't find onPositive and SingleButtonCallback.

>Error:(191, 39) error: cannot find symbol class SingleButtonCallback

Later in the documentation, only lists and checkboxes are used in the dialogs.

So, how could I create a _simple_ dialog with callbacks?

**Comment by afollestad** [comment]
The README mentions that will be introduced with version 0.8.2. 

There's a method called `callback()` before that version.
