### ISSUE TITLE
Library not sync

### ISSUE THREAD

**Issue by gurmailclabs** [afollestad/material-dialogs#739]
I am trying 
compile 'com.afollestad:material-dialogs:0.7.8.1' in my project but its failed to sync. I don't want to use new one because its deprecate HTTP. So please suggest me how can I resolve this issue.

Thanks

**Comment by afollestad** [comment]
Sorry, you'll have to use a newer version.

**Comment by afollestad** [comment]
You can actually reference commits, this will give you 0.7.8.1:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:69fe2f0@aar') {
        transitive = true
    }
}
```

But I wouldn't recommend using older versions.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by JuneBuug** [comment]
I am trying to sync compile 'com.afollestad:material-dialogs:0.7.8.1', 
and android studio said that could not find the library. 
I already added jcenter() and maven { url "https://jitpack.io"} , but it still says . 

So i tried to use upper version, which also gives me another error( could not use string sth. it occured in v23/values-23.xml).

**Comment by afollestad** [comment]
Well that's a very old version so there's not much I can do.

**Comment by thuantran293** [comment]
i am trying to sync compile 'com.afollestad.material-dialogs:core:0.9.4.4' 
i already do the same you, but android studio still could'n find the library. 
could you help me?

**Comment by Naveentp** [comment]
compile('com.github.afollestad.material-dialogs:core:0.7.9.1@aar') {
        transitive = true
    }

This solved my issue

**Comment by afollestad** [comment]
@Naveentp 0.7.9.1 is very old and you're subjecting yourself to bugs and other problems by using an old version. Not to mention using JitPack instead of jCenter to resolve the dependency.
