### ISSUE TITLE
Lists have an extra divider between them that wasn't there in previous versions.

### ISSUE THREAD

**Issue by Phascinate** [afollestad/material-dialogs#74]
Hi! Love the library. I've noticed that in a recent build lists have a divider between them. The sample app on the Play Store doesn't have a divider, but the sample APK here on Github does. It's probably just a very easy to fix issue.

![screenshot_2014-12-02-12-25-37](https://cloud.githubusercontent.com/assets/6421610/5267356/7db27bee-7a1e-11e4-88b5-5ec15b3131b2.png)

**Comment by abselt** [comment]
please make this a feauter so any one can disable/enable dividers between list items

**Comment by afollestad** [comment]
That's not part of the Material guidelines so you'll need a custom adapter.
