### ISSUE TITLE
0.7.8.0 removed from jCenter

### ISSUE THREAD

**Issue by trevorrjohn** [afollestad/material-dialogs#741]
Hey, so we are using an older version and it was recently removed from jCenter for some reason. Is there a specific reason for this?

**Comment by afollestad** [comment]
Sorry, jCenter was causing a lot of problems so I switched to JitPack.io a while ago.

**Comment by trevorrjohn** [comment]
thanks, sorry I missed that in the readme.

**Comment by afollestad** [comment]
@trevorrjohn I definitely wouldn't recommend using such an old version, but if you really need to use 0.7.8.0 you can reference the specific commit. 0.7.8.1 is basically 0.7.8.0 with some vital improvements:

```Gradle
compile('com.afollestad.material-dialogs:core:69fe2f0@aar') {
        transitive = true
}
```

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.
