### ISSUE TITLE
Question about list

### ISSUE THREAD

**Issue by ehdtkqorl123** [afollestad/material-dialogs#742]
Hi, I have a quick question about the list in the Material Dialog.
If the height of entire content views in the listview is greater than the height of the listview, I see a light gray line is drawn while scrolling up and down.
This lone only appears in the middle, and it goes away when the scroll reaches top or bottom.
I wonder how this part is implemented. Thanks!

**Comment by afollestad** [comment]
That magic all happens in `MDRootLayout`: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/internal/MDRootLayout.java

This class is used as the root view in dialogs. It speeds up view drawing and avoids a lot of glitches, and it performs some logic like the divider visibility. It was mostly developed by the developer of Nova Launcher, though. He's contributed a lot.
