### ISSUE TITLE
ID for colorChooserDialog to use multiple dialogs in one activity

### ISSUE THREAD

**Issue by MDXDave** [afollestad/material-dialogs#743]
Currently it is only possible to determinate if the colorChooseDialog is the accent color or it is not, it would be helpful if you can define an id for any dialog to distinguish between the dialogs.

**Comment by afollestad** [comment]
@MDXDave I added this in the latest commit.

The `ColorChooserDialog` will automatically use 1 of 3 tags based on if it's a primary, accent, or custom dialog. I also added a utility method to make it easier:

```java
ColorChooserDialog primary = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_PRIMARY);

ColorChooserDialog accent = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_ACCENT);

ColorChooserDialog custom = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_CUSTOM);
```

If you don't want to wait, you can reference the latest commit through Gradle for *core* and *commons* like this:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:f423baf7cc@aar') {
        transitive = true
    }
}

dependencies {
    compile('com.afollestad.material-dialogs:commons:f423baf7cc@aar') {
        transitive = true
    }
}
```

**Comment by afollestad** [comment]
@MDXDave I added this in the latest commit.

The `ColorChooserDialog` will automatically use 1 of 3 tags based on if it's a primary, accent, or custom dialog. I also added a utility method to make it easier:

```java
ColorChooserDialog primary = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_PRIMARY);

ColorChooserDialog accent = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_ACCENT);

ColorChooserDialog custom = ColorChooserDialog.findVisible(this, ColorChooserDialog.TAG_CUSTOM);
```

If you don't want to wait, you can reference the latest commit through Gradle for *core* and *commons* like this:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:f423baf7cc@aar') {
        transitive = true
    }
    compile('com.afollestad.material-dialogs:commons:f423baf7cc@aar') {
        transitive = true
    }
}
```
