### ISSUE TITLE
how to dismiss

### ISSUE THREAD

**Issue by tellfa** [afollestad/material-dialogs#745]
i want use Progress Dialog , but i can't dismis this. 
please help me

my code :     m_dialog.title("بارگذاری")
                    .titleColorRes(R.color.accentColor)
                    .content("لطفا شکیبا باشید")
                    .contentColorRes(R.color.activity_bg_color)
                    .backgroundColorRes(R.color.dialog_color_black)
                    .progress(true, 0)
                    .show();

**Comment by afollestad** [comment]
This is a duplicate of many other issues.

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs[(https://github.com/afollestad/material-dialogs#dismissing-dialogs)

**Comment by afollestad** [comment]
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
