### ISSUE TITLE
md_listitem_singlechoince is broken for multi-line items

### ISSUE THREAD

**Issue by AAverin** [afollestad/material-dialogs#746]
Text starts clipping with current listitem_singlechoice implementation.
This version fixed it for me:

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:descendantFocusability="blocksDescendants"
    tools:gravity="start|center_vertical"
    android:minHeight="@dimen/md_listitem_height"
    android:paddingLeft="@dimen/md_dialog_frame_margin"
    android:paddingStart="@dimen/md_dialog_frame_margin"
    android:paddingRight="@dimen/md_dialog_frame_margin"
    android:paddingEnd="@dimen/md_dialog_frame_margin">

    <RadioButton
        android:id="@+id/control"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:clickable="false"
        android:gravity="center_vertical"
        android:focusable="false"
        android:focusableInTouchMode="false" />

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        tools:text="Item"
        android:gravity="center_vertical"
        android:textSize="@dimen/md_listitem_textsize"
        android:paddingLeft="@dimen/md_listitem_control_margin"
        android:paddingStart="@dimen/md_listitem_control_margin"
        tools:ignore="NewApi,RtlSymmetry" />

</LinearLayout>
```

**Comment by afollestad** [comment]
I've updated your comment for syntax highlighting.

Could you provide a screenshot to help explain what you mean?

**Comment by AAverin** [comment]
I've already fixed the issue in my code. I was using your md_ element to create a radio list in the dialog, and the issue was that elements did not properly align to center vertically. That was resulting in text clipping for 2 Lome stings in the list. 
Changing layout to what I posted here solved the issue

**Comment by afollestad** [comment]
Basically like this? https://github.com/afollestad/material-dialogs/issues/748

**Comment by AAverin** [comment]
Yes, that might be related.
Although Material design specification doesn't say much about multi-line elements in a radio or checkbox lists in dialogs.
Anyways, current implementation looked very weird, with 2-line elements clipping at the bottom and starting in the middle of the box, instead of 1/3 from the top border.

**Comment by afollestad** [comment]
I'll consider this part of the other issue, and I'll make improvements for the next release.

**Comment by AAverin** [comment]
Sure.
I already resolved my issue, just wanted to mention it here so it would be fixed in later releases
