### ISSUE TITLE
List rows should  resize with multiline text

### ISSUE THREAD

**Issue by surahul** [afollestad/material-dialogs#748]
Google over [here](https://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs) suggests to change row size for wrapped list items, but the library does not supports this

**Comment by afollestad** [comment]
Actually, it does:

![shamumra58kafollestad10082015134622](https://cloud.githubusercontent.com/assets/1820165/10376330/fed02620-6dc2-11e5-9f45-46e67ea4bc84.png)

But this is after I improved spacing a bit. And I'll be implementing better support for multi-line single and multi choice dialogs before the next release.

**Comment by surahul** [comment]
Yeah but the padding is more for single line, see this:



![screenshot_2015-10-09-00-39-12](https://cloud.githubusercontent.com/assets/4014692/10376981/5caeba44-6e1e-11e5-909f-d3d6eed17d90.png)

**Comment by afollestad** [comment]
Not really sure what you mean. The screenshot I posted is of the latest code, not in any release.

**Comment by afollestad** [comment]
Basic list items and single/multi choice list items will look better with multi-line text now.

**Comment by afollestad** [comment]
By the way, `MaterialSimpleListAdapter` is intended for dialogs with icons, like:

![Image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3ekxYS1BqcEVmaDA/components_dialogs_simple3.png) 

From the guidelines. If you want a dialog with only text, use basic list dialogs.
