### ISSUE TITLE
Ripple on Android M

### ISSUE THREAD

**Issue by NielsMasdorp** [afollestad/material-dialogs#749]
I'm getting these weird effects on my Nexus 5 running Android M. I'm using 0.8.2.0. When I press an item in a list dialog or buttons in dialogs there is no ripple, only a partially selected state. When I slide my finger off the item/button the ripple shows for a split second.

**Comment by afollestad** [comment]
This isn't something I have control over. I've experienced that on both Lollipop and Marshmallow, and in other apps.

**Comment by NielsMasdorp** [comment]
You're right, I just found out it seems as this happens on normal animations as well (not always though) very weird. I'll close this.
