### ISSUE TITLE
Indeterminate Progress Dialogs,the  circle is hazy under build version 19

### ISSUE THREAD

**Issue by TrueStew** [afollestad/material-dialogs#750]
![hazyone](https://cloud.githubusercontent.com/assets/13217450/10389534/1ee0752c-6ea5-11e5-9334-8a78985be620.jpg)
![normal](https://cloud.githubusercontent.com/assets/13217450/10389540/298320ba-6ea5-11e5-9936-869502026096.jpg)

(first one is hazy,and the second one is normal :D)

when i use the Indeterminate Progress Dialog in login activity ,the circle is very hazy , the phone's version is 4.2.

but  4.4 or 5.0 is normal.

this question happened after you change the 0.7.5  to 0.8.2.0

**Comment by afollestad** [comment]
This is probably related to this library: https://github.com/DreaminginCodeZH/MaterialProgressBar

But I'll be updating the used classes soon.
