### ISSUE TITLE
Error while building with 0.8.2.0@aar 

### ISSUE THREAD

**Issue by yudhir** [afollestad/material-dialogs#754]
I am getting this error. 
Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.afollestad.materialdialogs'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

Which I can see in my  app/build/intermediate/explodedaar/
There are 2 folder :E:\CollegeMIS\app\build\intermediates\exploded-aar\com.afollestad\material-dialogs\0.7.6.0
and E:\CollegeMIS\app\build\intermediates\exploded-aar\com.afollestad.material-dialogs\commons and core

Build tools 23.0.1  Target api 23

**Comment by yudhir** [comment]
build.gradle 
 
compile('com.afollestad.material-dialogs:commons:0.8.2.0@aar') {
        transitive = true
    }

**Comment by yudhir** [comment]
top level build.gradle

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

**Comment by afollestad** [comment]
Generally that shouldn't go in all projects, it should go in your module gradle file

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.
