### ISSUE TITLE
Add option to force keyboard to open

### ISSUE THREAD

**Issue by squeeish** [afollestad/material-dialogs#755]
The keyboard auto-opening behavior for input dialog is awesome. But I have a custom view with 2 EditTexts and I'd like to replicate this behaviour. Does anyone have any ideas? Passing the ID of one of the EditTexts to the following code doesn't work:

    InputMethodManager imm = (InputMethodManager) mContext.getSystemService(Context.INPUT_METHOD_SERVICE);
    imm.showSoftInput(editText, InputMethodManager.SHOW_IMPLICIT);

**Comment by afollestad** [comment]
I'd recommend looking at the code instead of opening an issue.

**Comment by squeeish** [comment]
Thanks for the tip. For the benefit of others: I looked at the DialogUtils class and found `showKeyboard` and just emulated the behaviour.
