### ISSUE TITLE
Consider adding ability to set ColorCallback through ColorChooserDialog Builder

### ISSUE THREAD

**Issue by omacranger** [afollestad/material-dialogs#758]
I've managed to add this in a few times by building a custom class based off the ColorChooserDialog, with some very minimal modifications. It seems like a fairly simple process and will make it more consistent with the other dialogs (being able to set onPositive, for example).

**Comment by afollestad** [comment]
I didn't do this for a reason:

It's a `DialogFragment`, so it survives orientation changes. Interface instances cannot be passed through the saved instance state and restored later.

When the Activity implements the callback, it can restore the callback reference when the Activity reattaches after orientation change.
