### ISSUE TITLE
adding this library causing build error "You need to use a Theme.AppCompat theme (or descendent) "

### ISSUE THREAD

**Issue by evgenyh** [afollestad/material-dialogs#760]
build.gradle
android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 22
===================================

same error with
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23

**Comment by ishanthukral** [comment]
I'm running into the same issue. How were you able to resolve it? Thanks.

**Comment by afollestad** [comment]
Your Activity themes all have to be based on the AppCompat themes.

**Comment by ishanthukral** [comment]
My `styles.xml` file currently looks like this

`
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
</style>
`

Should I be adding a separate theme for dialogs? Apologies if my questions are a little naive, I'm still fairly new to Android. 

Thanks again.
