### ISSUE TITLE
onCancel(DialogInterface dialog) gets called together with show()

### ISSUE THREAD

**Issue by krokyze** [afollestad/material-dialogs#762]
My code is something like this:
```java
materialDialog = new MaterialDialog.Builder(MainActivity.this)
                    .title(R.string.dialog_time_ended_title)
                    .items(R.array.dialog_time_ended_list)
                    .cancelable(true)
                    .cancelListener(new DialogInterface.OnCancelListener() {
                        @Override
                        public void onCancel(DialogInterface dialog) {
                            // DO SOMETHING HERE
                        }
                    })
                    .itemsCallback(new MaterialDialog.ListCallback() {
                        @Override
                        public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                           // DO SOMETHING HERE
                        }
                    })
                    .build();
```

I'm building dialog in activity onStart() method and use it later, but when I call show() it calls onCancel method too. Is this some kind of bug?

**Comment by afollestad** [comment]
@krokyze well, the cancel listener and `show` method are both handled by `android.app.Dialog`. None of that logic is handled by this library. 

So if I had to guess, it would be a Android framework issue or an issue with your device.

**Comment by afollestad** [comment]
The show/cancel/dismiss listener example in the sample project works on my Nexus 6, also:

https://play.google.com/store/apps/details?id=com.afollestad.materialdialogssample

**Comment by krokyze** [comment]
@afollestad previously was having this on Galaxy S5, tested on Galaxy S3 and the same result. The thing is that cancellistner works, when I cancel the dialog, but it get's called on show() too.

**Comment by afollestad** [comment]
Sorry, I don't think there's anything I can about this. The cancel listener isn't part of my own logic, it's up to the device implementation (which can change with different manufacturers).
