### ISSUE TITLE
Application creashing on Android 4.4 version

### ISSUE THREAD

**Issue by mohanishn123** [afollestad/material-dialogs#763]
Caused by: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl

I am using GCM therefore also getting following issue :

java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gcm.GcmReceiver: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl

How to solve this ?

**Comment by afollestad** [comment]
Do it yourself, that has nothing to do with this library.
