### ISSUE TITLE
Question: Filter with basic list

### ISSUE THREAD

**Issue by seba123neo** [afollestad/material-dialogs#764]
Hi, I'm using the library a long time and is excellent.

I need to make a list (like the basic list), but with a filter (on a EDITTEXT).

I wonder how this can be done using what the library offers.

Thanks.

**Comment by afollestad** [comment]
You can use a custom layout for this, just put an EditText above a ListView in a LinearLayout, and use it as the dialog custom view. You'll need a custom adapter set to the ListView, obviously.

**Comment by seba123neo** [comment]
yes, I imagined that was the way, but ask just in case...

I thought it was possible to add a control to the basic list, and use the adapter from the list that the library offers.

**Comment by afollestad** [comment]
Sorry, no, you'll have to use a custom view. I can't add too many small pre-made dialog types to the library.

**Comment by seba123neo** [comment]
Thanks, you can close this issue...
