### ISSUE TITLE
Gradle Script failing to compile

### ISSUE THREAD

**Issue by mmkgitpush456** [afollestad/material-dialogs#767]
I apologize as, based on previous commentary, this seems like a recurring theme.  

I followed the instructions from the README regarding configuration.  However, gradle is still failing to compile, providing the 'Failed to resolve' message.

I don't know if this matters, but I am currently using the following versions for the application in gradle and I am trying to configure with your most recent build from the readme.
compile 'com.android.support:support-v4:22.2.0'
compile 'com.android.support:appcompat-v7:22.2.0'

Any assistance regarding this venture is much appreciated.  Thanks for your time.

**Comment by afollestad** [comment]
You'll probably need to use version 23.1.0 of Google's libraries, and use Build Tools 23.0.1. 

Otherwise there's not much I can do to help unfortunately.

**Comment by mmkgitpush456** [comment]
It continues to fail even with the most modern tools and libraries.  May I ask why this appears to be a recurring issue with the library?

**Comment by afollestad** [comment]
I've never been able to figure it out.

Every time I publish a release, I immediately reference it in all of my personal apps and employer's apps, and it works fine.

JitPack.io also reports that the latest version built successfully their servers: https://jitpack.io/#afollestad/material-dialogs

**Comment by afollestad** [comment]
I'd have to guess that most of the people who have these errors aren't setting up their Gradle files correctly.

**Comment by mmkgitpush456** [comment]
The reason I ask is because I am inheriting a project that is utilizing this library. 

Additionally, just as a reference, a blank android project will cause gradle to fail with the instructions provided in the README.  Are there any other configurations required besides the 2 steps listed?

**Comment by afollestad** [comment]
@mmkgitpush456 as long as it looks like this in your module build.gradle file (**not** your project's build.gradle file), there shouldn't be anything wrong:

<img width="517" alt="screen shot 2015-10-17 at 4 53 25 pm" src="https://cloud.githubusercontent.com/assets/1820165/10561476/a7397176-74ef-11e5-8355-608566e3c67f.png">

**Comment by mmkgitpush456** [comment]
Thanks, now it works.  The project is using an older version of the API.  The newest release seems to have some collisions with the styling, but that can saved for another day.  

The most important thing was just getting this guy to compile correctly.

I greatly appreciate your assistance on this matter.

**Comment by afollestad** [comment]
Great, glad it works!

**Comment by MFlisar** [comment]
If you want to force using your own support library version, something like following works as well:

    compile('com.afollestad.material-dialogs:core:0.8.2.0@aar') {
        transitive = true;
        exclude group: 'com.android.support', module: 'appcompat-v7';
    }
    compile('com.afollestad.material-dialogs:commons:0.8.2.0@aar') {
        transitive = true;
        exclude group: 'com.android.support', module: 'appcompat-v7';
    }

and include whatever suppor library version you need and want...

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
