### ISSUE TITLE
Please make 0.7.3.0 on maven, bintray, etc. usable again!

### ISSUE THREAD

**Issue by alice-margatroid** [afollestad/material-dialogs#769]
Cannot even compile Antox anymore since it was deleted recently.

https://github.com/Astonex/Antox/issues/693

**Comment by afollestad** [comment]
It's not coming back to Bintray. It's being hosted on JitPack.io, which automatically creates builds from GitHub using the tag/release system.

You shouldn't use a version that old, but if you really need to, find the commit ID. JitPack lets you reference commit IDs in your Gradle file.

**Comment by afollestad** [comment]
For an example:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:6e7bf4de8d@aar') {
        transitive = true
    }
}
```

I'm referencing the commit hash `6e7bf4de8d`, which is the most recent commit. If you can find a commit labeled 0.7.3.0, it can be referenced like the above.

**Comment by alice-margatroid** [comment]
Looks a bit different in my gradle file but:
    compile 'com.afollestad:material-dialogs:0.7.3.0'

The versions on https://jitpack.io/#afollestad/material-dialogs or I do not understand how to tell your package repository to create/host me the files for 0.7.3.0 this is important but okay, I tried to solve it myself and failed.

**Comment by afollestad** [comment]
Generally when someone says a library is *too new*, they're too lazy to update when they should 😉there's thousands of vital changes that you would be missing out on if you use an older version like that.

I went back in the commit history for this library and found the right commit:

<img width="945" alt="screen shot 2015-10-17 at 5 38 16 pm" src="https://cloud.githubusercontent.com/assets/1820165/10561598/e3ddd396-74f5-11e5-853e-89eb73cc6dde.png">

JitPack likes the first 10 characters of the commit ID:

<img width="1077" alt="screen shot 2015-10-17 at 5 41 26 pm" src="https://cloud.githubusercontent.com/assets/1820165/10561604/58528474-74f6-11e5-85ba-0e65158eb250.png">

You can reference 0.7.3.0 with this:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    // other dependencies here
    compile('com.afollestad.material-dialogs:core:66bf6645cf@aar') {
        transitive = true
    }
}
```

**Comment by alice-margatroid** [comment]
Thank you for so much useful help, tried various combinations now:
com.afollestad.material-dialogs:core:66bf6645cf@aar
com.github.afollestad:material-dialogs:66bf6645cf    <--- as suggested on their own site for use with gradle
with core an w/o, same with @aar, core, -SNAPSHOT and other combinations
none of them worked so far, but I'm overly tired and will figure a way out tomorrow

PS: the url to     maven { url "https://jitpack.io" } is there as well of course and it tries to fetch files from it, I just don't have the correct dependencies {    compile to make it work.

Dōshio.

**Comment by afollestad** [comment]
`com.github.afollestad` is the same as `com.afollestad`, I have a JitPack.io custom domains setup. Using @aar (Android Artifact) isn't optional in this case, without it the library wouldn't have any of the Android resources (e.g. layouts, dimensions, strings, etc.) that are needed to work.

I hope you can figure it out! In the past, sometimes using older version of Google's libs (like AppCompat) in your project can interfere. Make sure you're using version 23.1.0 of Google's libs, and Build Tools 23.0.1.

**Comment by ex3ndr** [comment]
Insane. We are unable to release libs that dependent on this library anymore. Bye.

**Comment by afollestad** [comment]
@ex3ndr taking it out on me does nothing. Blame it on JitPack.io. 

Bye.

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.
