### ISSUE TITLE
Failed to resolve: com.afollestad.material-dialogs:core:0.8.4.2

### ISSUE THREAD

**Issue by susheel17** [afollestad/material-dialogs#770]
I get this gradle error while trying to build. Please advise?

**Comment by afollestad** [comment]
See the other 3 or 4 issues that this is a duplicate of.

**Comment by susheel17** [comment]
Really sorry to start the issue. I added the maven dependency and that resolved the issue. Thanks again for creating a great library!

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
