### ISSUE TITLE
How to set Folder Chooser Dialog as uncancellable?

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#772]
Hi Aidan,

Is there a way to dismiss the Dialog only when a folder is chosen? Or better, can we (developers) have the possibility to choose whether the "Cancel" button should appear or not? I'm making an app to install Custom ROMs so I let users to choose the folder where they placed the ROM's zip file. The Dialog code is located in onCreate method so users must choose a folder before continuing. Could you help me? Thanks in advance!

**Comment by afollestad** [comment]
@peppe130 passing 0 for the cancel button should hide it, as long as you're using version 0.8.4.2 of the library.

Also, `FolderChooserDialog` is a `DialogFragment`, so you can call `setCancelable` on it.

```java
FolderChooserDialog dialog = new FolderChooserDialog.Builder(this)
    .cancelButton(0)
    .build();
dialog.setCancelable(false);
dialog.show();
```

**Comment by peppe130** [comment]
Perfect!!!!! Thank you very much!

**Comment by afollestad** [comment]
You're welcome!

**Comment by peppe130** [comment]
I found a bug! Also in root directory "/" the Dialog keep showing the three dots to get to parent folder. By pressing on them, the app crashes :)

**Comment by afollestad** [comment]
Weird, it doesn't happen to me 😮

![device-2015-10-19-124632](https://cloud.githubusercontent.com/assets/1820165/10585939/75d9dfb4-765f-11e5-887d-923c66f9f000.png)
