### ISSUE TITLE
Failed to resolve: com.afollestad.material-dialogs:commons:0.8.4.2

### ISSUE THREAD

**Issue by cwfei** [afollestad/material-dialogs#773]
unable to compile dependecy

here's my full build.grade

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.1"

        defaultConfig {
            applicationId "com.appsaur.tarucassist"
            minSdkVersion 17
            targetSdkVersion 23
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:23.0.1'
        compile 'com.android.support:design:23.0.1'
        compile 'com.flipboard:bottomsheet-core:1.4.3'
        compile 'com.flipboard:bottomsheet-commons:1.4.3'
        compile 'com.github.bumptech.glide:glide:3.6.1'
        compile 'com.gordonwong:material-sheet-fab:1.1'
        compile 'com.android.support:cardview-v7:23.0.+'
        compile 'com.android.support:recyclerview-v7:23.0.0'
        compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
        compile 'com.vstechlab.easyfonts:easyfonts:1.0.0'

        compile "com.android.support:support-v4:+"
        compile 'com.squareup.picasso:picasso:2.3.2'
        compile 'com.nineoldandroids:library:2.4.0'
        compile 'com.daimajia.slider:library:1.1.5@aar'

        compile('com.afollestad.material-dialogs:commons:0.8.4.2@aar') {
           transitive = true
        }

    }

**Comment by afollestad** [comment]
See the other 4-5 duplicates.

**Comment by afollestad** [comment]
To make it easier:

```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.afollestad.material-dialogs:core:69fe2f0@aar') {
        transitive = true
    }
}
```

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
