### ISSUE TITLE
Add color to existing primary colors

### ISSUE THREAD

**Issue by seba123neo** [afollestad/material-dialogs#774]
in my application allows the user to change the "theme" of the application through the ColorChooserDialog, this works perfect...

the colors I allows to select the user (without subs colors), are all primary colors(material primary colors 500) + a extra color #303030 (this is the dark material color).

only i need add "one" extra color to the existing primary  colors of the library.

but in the code, i need to define "all the colors" in the array of int[]

would be good to just set the color to add, and not all existing colors.

thanks.

**Comment by afollestad** [comment]
I don't plan on adding the ability to append colors to the existing palette.

But, you could copy the `int[]` and `int[][]` from the `ColorPalette` class and add your additional colors to them for use in your app. 

https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/java/com/afollestad/materialdialogs/color/ColorPalette.java
