### ISSUE TITLE
Styling Toolbar while editing text

### ISSUE THREAD

**Issue by subspider** [afollestad/material-dialogs#775]
We have a style to our Toolbar and I'm not able to style the tool bar so it matches. 
if there is answer please reply here:
http://stackoverflow.com/questions/33130136/custom-actionmode-bar-and-material-dialog-show-different

**Comment by afollestad** [comment]
That's a limitation of older API levels, I believe. 

I can't remember how I solved it in Cabinet. Do you remember, @plusCubed?

**Comment by plusCubed** [comment]
I don't remember specifically, but I believe it's overriding `?actionModeStyle` and `?android:actionModeStyle` that fixed it.

**Comment by afollestad** [comment]
@plusCubed right, thanks; hopefully that helps, @subspider. It's only really an issue below Lollipop, if I remember correctly.

**Comment by subspider** [comment]
Thanks for the tip it worked from v19 up @afollestad  and @plusCubed
