### ISSUE TITLE
Custom layouts in preferences are overridden

### ISSUE THREAD

**Issue by edellepi** [afollestad/material-dialogs#776]
Is there any way to apply a custom layout (instead of md_preference_custom.xml) to material dialogs widgets in preferences. This would be useful for instance to manage indenting of properties.

**Comment by afollestad** [comment]
http://stackoverflow.com/a/16109336/309644

**Comment by edellepi** [comment]
Thank you,

but the point is that my custom layout is apparently ignored.

**Comment by afollestad** [comment]
Oh yeah, I didn't notice that.

I'll have it fixed soon.

**Comment by afollestad** [comment]
Fixed for the next release
