### ISSUE TITLE
ColorChooserDialog has white horizontal lines on Gingerbread

### ISSUE THREAD

**Issue by seba123neo** [afollestad/material-dialogs#777]
In previous versions this did not happen...

(the vertical lines It comes from the focus of the camera)

![a](https://cloud.githubusercontent.com/assets/9873666/10589937/852beca8-7684-11e5-8ba8-40095836b99a.jpg)

**Comment by afollestad** [comment]
Unfortunately I have no idea what would cause that, and have no idea how it would be fixed.

But I'll leave it open. 

Gingerbread tends to have a lot of unfixable issues, like https://github.com/afollestad/material-dialogs/issues/685.

**Comment by afollestad** [comment]
I don't think anything can be done about this.
