### ISSUE TITLE
inputrangeres, -1, no max limit seem it doesn't work

### ISSUE THREAD

**Issue by druidamix** [afollestad/material-dialogs#780]
Hi,

In the documentation says:
>>If you pass 0 for the min length, there will be no min length. If you pass -1 for the max length, there >>will be no max length. If you don't pass a third parameter at all, it will default to Material red. 

![](http://s17.postimg.org/yw5vd2imn/screen.png)
The log says:
>>java.lang.IllegalArgumentException: Max length for input dialogs cannot be less than 1.

I'm doing something wrong?

Thanks.

**Comment by subspider** [comment]
Doesn't look like 

public Builder inputRange(@IntRange(from = 0, to = Integer.MAX_VALUE) int minLength,
                                  @IntRange(from = 1, to = Integer.MAX_VALUE) int maxLength) {
            return inputRange(minLength, maxLength, 0);
        }

        /**
         * @param errorColor Pass in 0 for the default red error color (as specified in guidelines).
         */
        public Builder inputRange(@IntRange(from = 0, to = Integer.MAX_VALUE) int minLength,
                                  @IntRange(from = 1, to = Integer.MAX_VALUE) int maxLength,
                                  @ColorInt int errorColor) {
            if (minLength < 0)
                throw new IllegalArgumentException("Min length for input dialogs cannot be less than 0.");
            if (maxLength < 1)
                throw new IllegalArgumentException("Max length for input dialogs cannot be less than 1.");

**Comment by afollestad** [comment]
Resource strings on Android can be negative. -1 could actually be a resource. 0 means null.

**Comment by afollestad** [comment]
0 means null here, not -1.

**Comment by afollestad** [comment]
Sorry, I misread the question in my first respond.

I'll have this fixed.
