### ISSUE TITLE
Proposal: basic dialog with option

### ISSUE THREAD

**Issue by bohoffi** [afollestad/material-dialogs#781]
Hi @afollestad,

first of all: your library is amazing.
I have a simple proposal: could you include the possibility to build a basic dialog with an option? It could look like the Runtime Permission request dialog (the one with the "never ask again" checkbox).
The handler could have a simple boolean param which indicates whether the checkbox was checked or not.

**Comment by afollestad** [comment]
Small dialogs like this should be created using custom layouts IMO, it's not worth increasing the size of the library for others when it's something not everyone would use.

It'd be pretty easy to copy the default dialog layout I have and add a checkbox to it, though.

**Comment by bohoffi** [comment]
I know that it could be achieved using custom layouts. 
It was just a proposal ;) 

I will use your proposal using a custom layout. 

Thank you for your quick reply
