### ISSUE TITLE
Changing ActionMode Color

### ISSUE THREAD

**Issue by subspider** [afollestad/material-dialogs#783]
after changing my ActionMode color I got and Error:

ttempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.getPadding(android.graphics.Rect)' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.getPadding(android.graphics.Rect)' on a null object reference
at android.widget.AbsListView.setSelector(AbsListView.java:3271)
at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:271)
at com.afollestad.materialdialogs.MaterialDialog.(MaterialDialog.java:91)

Was tested on Android 5

Maybe this http://stackoverflow.com/questions/27358989/error-in-switch-in-android-5-0

**Comment by afollestad** [comment]
The crash doesn't happen in my library, it's related to your selector XML.

**Comment by subspider** [comment]
So I just created the styles to override the themes MD_Dark and MD_Light and colouring the actionMode and was doing that can you tell me then what can I do ?
