### ISSUE TITLE
Positive and Negative button selectors are too close

### ISSUE THREAD

**Issue by joksa** [afollestad/material-dialogs#784]
If I put positive and negative button with selector like this

.......
.btnSelector(R.color.colorPrimary, DialogAction.POSITIVE)
.btnSelector(R.color.colorAccent, DialogAction.NEGATIVE)

They are joined with no space between.
When remove one selector everything looks good.

Cheers

**Comment by afollestad** [comment]
You need to use inset selector drawables. Look at the drawables in `core` or in the sample project.

https://github.com/afollestad/material-dialogs/blob/master/core/src/main/res/drawable/md_btn_selected.xml
