### ISSUE TITLE
Question : Can we show/hide progress dialog during runtime ?

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#792]
The question is simple, I think I'm on the good road (would you do the same way ?).

However I get an issue, because I'm just going one time in the "showListener", should I do something else ?

Here is the code I try to handle:

        MaterialDialog.Builder dialogBuilder;

        dialogBuilder = new MaterialDialog.Builder(this)
                .title("Super Dialog")
                .content("blananacldcla")
                .progress(false, 10)
                .negativeText("NON")
                .positiveText("OK")
                .neutralText("RESET")
                .contentGravity(GravityEnum.CENTER)
                .cancelable(false)
                .autoDismiss(false)
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        materialDialog.dismiss();
                    }
                })
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        if (progress < 10) {
                            progress++;
                        }
                    }
                })
                .onNeutral(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        progress = 0;
                    }
                })
                .showListener(new DialogInterface.OnShowListener() {
                    @Override
                    public void onShow(final DialogInterface dialog) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                runOnUiThread(new Runnable() {
                                    @Override
                                    public void run() {
                                        ((MaterialDialog) dialog).incrementProgress(1);
                                        if (progress == 10) {
                                            ((MaterialDialog) dialog).getContentView().setVisibility(View.VISIBLE);
                                            ((MaterialDialog) dialog).getProgressBar().setVisibility(View.GONE);
                                        } else {
                                            ((MaterialDialog) dialog).getContentView().setVisibility(View.GONE);
                                            ((MaterialDialog) dialog).getProgressBar().setVisibility(View.VISIBLE);
                                        }
                                    }
                                });
                            }
                        }).start();
                    }
                });

        dialogBuilder.show();

**Comment by afollestad** [comment]
android.app.Dialog has a `show()` and `dismiss()` method.

**Comment by afaucogney** [comment]
this is not question to show or hide the dialog, but only the progressBar item. Sorry if it wasn"t clear enough !

**Comment by afollestad** [comment]
Oh, that makes more sense.

When you build a MaterialDialog, its layout gets inflated once based on the dialog type (including the 3 different types of progress dialogs). So there wouldn't be a way to switch between different dialog types; hiding the individual views would be the best way to do it right now.

**Comment by afaucogney** [comment]
ok, you mean with something like that:

    public class MainActivity extends AppCompatActivity {
  
    int progress = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MaterialDialog.Builder dialogBuilder;


        dialogBuilder = new MaterialDialog.Builder(this)
                .title("Super Dialog")
                .content("blananacldcla")
                .progress(false, 10)
                .negativeText("NON")
                .positiveText("OK")
                .neutralText("RESET")
                .contentGravity(GravityEnum.CENTER)
                .cancelable(false)
                .autoDismiss(false)
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        materialDialog.dismiss();
                    }
                })
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        if (progress < 10) {
                            progress++;
                        }
                        update(materialDialog);
                    }
                })
                .onNeutral(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
                        progress = 0;
                        update(materialDialog);
                    }
                });

        dialogBuilder.show();

    }

    private void update(MaterialDialog dialog){
        ((MaterialDialog) dialog).setProgress(progress);
        if (progress == 10) {
            ((MaterialDialog) dialog).getContentView().setVisibility(View.VISIBLE);
            ((MaterialDialog) dialog).getProgressBar().setVisibility(View.GONE);
        } else {
            ((MaterialDialog) dialog).getContentView().setVisibility(View.GONE);
            ((MaterialDialog) dialog).getProgressBar().setVisibility(View.VISIBLE);
        }
    }
    }

**Comment by afaucogney** [comment]
this still show the progress label (100%) ? I think this is an issue.

**Comment by afaucogney** [comment]
![device-2015-10-28-153312](https://cloud.githubusercontent.com/assets/6554201/10791597/56b555f6-7d89-11e5-84dc-cfb3739687ac.png)

**Comment by afollestad** [comment]
It's better to just use two dialogs, that coordinate when they're shown and hidden.

**Comment by Najibsaurus** [comment]
it will happen when you dont reset the progress of material dialog.
set progress a nil value while `dismiss()` method.  
`materialDialog.setProgress(0);`
