### ISSUE TITLE
How can I display .input and .item ?

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#795]
Is there a way without CustomView ?

    new MaterialDialog.Builder(this)
                .title("Super Dialog")
                .items(new CharSequence[]{"Category", "Family"})
                .inputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)
                .input("Enter something", "", new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(MaterialDialog dialog, CharSequence input) {
                        // Do something
                    }
                }).show();

**Comment by afollestad** [comment]
No, you have to use a custom view for that
