### ISSUE TITLE
What is the intention of the progress bar ?

### ISSUE THREAD

**Issue by afaucogney** [afollestad/material-dialogs#796]
1/ Is it just for a "progress bar dialog", then switch to something else (other dialog or activity or whatever) ?
2/ Also possibility to use the progress bar during a async load of a list ?

Because if 2/ is valid, 
1/ I didn't succeed doing that, even if this a a general use case.
2/ I can even not putting in the same dialog (.item(...) with .progress), the getProgressBar return null.

Because showing nothing during load of data, I assume, this is not Ergo / MD compliant ?
https://www.google.com/design/spec/components/progress-activity.html#progress-activity-behavior 

a setItemProgress() in the same way as setProgress  would be nice.

**Comment by AzureusSme** [comment]
Omg.

**Comment by afaucogney** [comment]
@AzureusSme if what I said is not fair to ask, please just give me some knowledge that I can learn.

**Comment by afollestad** [comment]
You'll need to dismiss the progress dialog and show another to switch between dialog types, that's true with stock dialogs also. It's not intended to allow switching between multiple types in one dialog, the specific layout is inflated when you build it.

---

For loading with async data, yeah. That's more of a general Android question than a question for this library:

```java
final MaterialDialog dialog = new MaterialDialog.Builder(this)
   // setup...
   .build();
final Handler handler = new Handler();

new Thread(new Runnable() {
    public void run() {
        try {
            Thread.sleep(3000);
        } catch(Throwable ignored) { }
        handler.post(new Runnable() {
            public void run() {
                dialog.dismiss();
            }
        });        
    }
}).start();
```

You can avoid use of the `Handler` if you use `runOnUiThread(Runnable)` in an `Activity`, or `View.post(View)` on a View instance.
