### ISSUE TITLE
Bug in circle progressbar

### ISSUE THREAD

**Issue by sepehr-alipour** [afollestad/material-dialogs#798]
I use this library to show progress in getting data,in api 21 and above force with this bug  to showing progress: 
![screenshot_20151029-113218 2](https://cloud.githubusercontent.com/assets/6023851/10813118/c7c5145e-7e31-11e5-9a5c-d6042052359c.png)

**Comment by afollestad** [comment]
I don't fully understand what you mean. I develop exclusively on Lollipop and Marshmallow, there should be no issues with progress drawables. I also have tested below Lollipop and it was working.
