### ISSUE TITLE
Assign IDs to list items in String array

### ISSUE THREAD

**Issue by programmer-lucas** [afollestad/material-dialogs#799]
Hello,

Could you add an option to assign IDs to list items from a String array? Like this:

```java
new MaterialDialog.Builder(this)
        .itemsIds(R.array.itemIds)
        .show();
```

You could also pass a literal string array (`String[]`) in place of an array resource ID or `CharSequence[]`.

**Comment by afollestad** [comment]
I can't do that. Values from `itemsIds()` are assigned to the ID of views (e.g. `view.setId()`). You can't assign strings to view IDs.

**Comment by programmer-lucas** [comment]
There is no way to map the string arrays of values as id's in a public method in your Dialog material and it be passed, and then returned by the callback? The mapping done with the texts.

**Comment by afollestad** [comment]
The IDs are used from the `DefaultAdapter`, they're assigned to the view IDs, not as tags.

This feature was requested by someone else in the past, that's how it's intended to work now.

**Comment by afollestad** [comment]
Containing more variables in the dialog will increase the amount of memory it can use, and it would increase the size of the code. You should just use a custom adapter and keep track of the string map yourself.

**Comment by programmer-lucas** [comment]
Okay. Thank you for your help and quick return.
