### ISSUE TITLE
Do you have jar version of the library?

### ISSUE THREAD

**Issue by JenyaKirmiza** [afollestad/material-dialogs#801]
I want to use this library on eclipse. how can i do it?

**Comment by afollestad** [comment]
No, you can't use Android libraries from JARs. JARs do not contain Android resources like layouts, dimensions, strings, etc.

That's what AAR packages are for.

**Comment by afollestad** [comment]
There quite a few closed issues related to Eclipse, I believe other people had solutions for importing into Eclipse. I do not use Eclipse myself though, and I'd recommend not using it for Android dev.

https://github.com/afollestad/material-dialogs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+eclipse

**Comment by JenyaKirmiza** [comment]
thanks. I don't like eclipse either, but anyway the friend of mine asked me to add this awesome dialogs to eclipse. So thanks for help  i will search for solution in former issues about eclipse
