### ISSUE TITLE
How to import the library javadoc for Android Studio?

### ISSUE THREAD

**Issue by programmer-lucas** [afollestad/material-dialogs#802]
Is there a link to the javadoc of this library? Somehow I can see it without having to go in class at GitHub?

**Comment by plusCubed** [comment]
Should work for the next release: 1726e5b088baa180b353fed9a389c6f41942239b

**Comment by programmer-lucas** [comment]
Ok. I'm waiting. Thanks for your reply.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by programmer-lucas** [comment]
Thank you. I need to do something else besides using the library to have available javadoc? Are all methods and classes that are documented?
