### ISSUE TITLE
itemsCallbackMultiChoice behavior unintuitive

### ISSUE THREAD

**Issue by timrae** [afollestad/material-dialogs#803]
With the below code (and v0.8.3.0) the itemsCallback will *never* be called and I'll always end up with `doSomething(false, false);` irrespective of what the user chooses. 

```java
boolean mIncludeSched = false;
boolean mIncludeMedia = false;
MaterialDialog.Builder builder = new MaterialDialog.Builder(getActivity())
        .title(R.string.export)
        .content(getArguments().getString("dialogMessage"))
        .positiveText(android.R.string.ok)
        .negativeText(R.string.cancel)
        .cancelable(true)
        .items(items)
        .itemsCallbackMultiChoice(null,
                new MaterialDialog.ListCallbackMultiChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog materialDialog,
                                               Integer[] integers, CharSequence[] charSequences) {
                        mIncludeSched = false;
                        boolean mIncludeMedia = false;
                        for (int i = 0; i < integers.length; i++) {
                            switch (integers[i]) {
                                case INCLUDE_SCHED:
                                    mIncludeSched = true;
                                    break;
                                case INCLUDE_MEDIA:
                                    mIncludeMedia = true;
                                    break;
                            }
                        }
                        return true;
                    }
                })
        .onPositive(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                doSomething(mIncludeSched, mIncludeMedia);
                dismiss();
            }
        })
        .onNegative(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                dismiss();
            }
        });
return builder.show();
```

This is kind of consistent with the documentation which says:

> If you do not set a positive action button using positiveText(), the dialog will automatically call the multi choice callback when user presses the positive action button.

which indirectly implies the converse that `itemsCallbackMultiChoice` will not be called if a positive button is set, like I did with my code. 

If this isn't a bug, then it's an extremely unintuitive API. `itemsCallbackMultiChoice` should be called before onPositive() is called, regardless of whether I set `positiveText()`. Of course I can "fix" my code by setting `.alwaysCallMultiChoiceCallback()` in the builder, but you should not have the situation where the users choice is completely ignored.

**Comment by afollestad** [comment]
Try a newer version and let me know if it still happens.

0.8.5.0 was released recently, 0.8.4.2 and 0.8.4.0 came before that.

**Comment by afollestad** [comment]
Also, you don't need to call `dismiss()` in the action button methods. The dialog will *always* dismiss itself unless you disable `autoDismiss`.

**Comment by timrae** [comment]
Did you fix this bug in the new version, or you're just asking me to try it and see? If I update to 0.8.5.0 then it's going to try to force me to update to the latest support library, which has a bug that breaks my app. So I'm waiting for appcompat 23.1.1 before updating

**Comment by afollestad** [comment]
I may've, I remember hearing about something similar to this. It's been too long to know for sure (a month is a long time with release cycles).

**Comment by afollestad** [comment]
I'll double check though.

**Comment by timrae** [comment]
thanks

**Comment by afollestad** [comment]
Another quick tip, you should use android.R.string.cancel instead of R.string.cancel, Google handles all the localization that way 😉

**Comment by timrae** [comment]
Ah thanks.
Btw, I just checked with 0.8.5 and had the same problem

**Comment by afollestad** [comment]
You're right, I can reproduce it. Currently, the action button callbacks are called before the `itemsCallbackMultiChoice` callback. Logically it makes sense, the click of the action button triggers the selection callback.

**Comment by afollestad** [comment]
There's two options for you here:

1. Call `.alwaysCallMultiChoiceCallback()` on the `Builder`, it will cause the selection callback to be invoked every time you select or unselect a checkbox. You can keep track of the booleans until the action button is pressed.

2. Make a call to `doSomething(boolean, boolean)` on the last line of your callback. The callback is currently only called right after you press the action button, so it would have the same effect. You can remove the use of `onPositive` and `onNegative` altogether.

**Comment by timrae** [comment]
> Call .alwaysCallMultiChoiceCallback() on the Builder, it will cause the selection callback to be invoked every time you select or unselect a checkbox. You can keep track of the booleans until the action button is pressed.

Yes as I mentioned, I already know that this fixes the problem, but it's not intuitive. According to the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) your API users shouldn't have to scour through the documentation line by line to figure out how to get it to work.

How about deprecating `alwaysCallMultiChoiceCallback()` and adding a new method `alwaysCallMultiChoiceCallback(boolean b)` with the default set to true? Having the multi choice callback always called by default would be much more intuitive and would basically fix this issue.

> Make a call to doSomething(boolean, boolean) on the last line of your callback. The callback is currently only called right after you press the action button, so it would have the same effect. You can remove the use of onPositive and onNegative altogether.

This won't work for me because the dismiss() method in onNegative is a special method in my class that dismisses that also dismisses the context menu that the dialog was called from. I need custom onPostive() and onNegative() methods.

I doubt many people would want to not have the itemsCallbackMultiChoice called by default on every change of a checked state if that resulted in the checked states essentially getting ignored in the onPostive() onNegative() callbacks.

**Comment by afollestad** [comment]
You're the only one that's had any problems thinking the multi-selection API is "unintuitive". It's built to work the way it does on purpose, changing that now would change the expected behavior for many developers, including that of Nova and Action Launcher. In my opinion, a lot of people wouldn't want the selection result until after the user confirms it.

**Comment by afollestad** [comment]
And also, you don't have to "scour through the documentation line by line", I have an enormous document with organization and a table of contents to explain different components.

**Comment by timrae** [comment]
Sorry if I offended you, that wasn't my intention. Now that I've gotten my head around how you're intending it to be used, I can understand why you're saying that it's perfectly intuitive, but I have to disagree for the following reason:

In the docs you write that "multiple choice list dialogs are almost identical to regular list dialogs". But in the case of a list dialog we have a list and an action is taken in the onSelection() method when the list item is tapped. In the same way I'd expect the onSelection() method to be called whenever a checkbox item has been tapped, and tell me what the new checked state is, like an `OnCheckedChangeListener` in the standard Android API.

Since tapping a checkbox and tapping the positive button are two completely different things, I'd expect the API to have two different methods for dealing with this. onSelection() for dealing with checkbox taps, and onPostive() for dealing with positive button taps. Instead you have an onPositive() method that you don't intend the user to use at all, and you have the onSelection() method doing what the onPositive() method should be doing.

If you think the way you're doing it is perfectly intuitive, nobody else has complained, and it's too much hassle to change then I understand, I just thought I'd try to explain why it's an unintuitive API for me. If you don't plan on changing it then maybe you could update the documentation a bit to mention that onPositive() is not intended to be used in general.

**Comment by afollestad** [comment]
I do see your point, I'm gonna brainstorm this a bit.

**Comment by DurgaArunkumarSmitiv** [comment]
Hi I need to uncheck a single checkbox  alone if some other item is selected. Example everyday,Monday Tuesday etc.. Initially everyday is checked by default,now if i check Monday ,Everyday should be unchecked.I couldnt find any `OnCheckedChangeListener`.Kindly help me how can we do this.
