### ISSUE TITLE
Edit Text and single choice input

### ISSUE THREAD

**Issue by logicalstep** [afollestad/material-dialogs#804]
Hi,
Using your fantastic library.
I'm trying to add a single choice option with a text input box, but it doesn't seem to support that?
Can you confirm if the only way to do this is with a custom view?

Many thanks

**Comment by afollestad** [comment]
This is actually a duplicate of another issue, but yeah, that's the only way to do it. I can't include every possible view combination 😀

**Comment by logicalstep** [comment]
oh why not ;)
I've actually used the custom view anyway, it's just a lot more work to implement getting and setting of the custom view Views elements, but I've had good results.

Thanks again!
