### ISSUE TITLE
Shadows on pre-Lollipop versions

### ISSUE THREAD

**Issue by alexsmithfanning** [afollestad/material-dialogs#805]
MaterialDialogs doesn't have a drop shadow on dialogs for KitKat and below. I think it would make it look much nicer.

Great work by the way. Such an impressive library.

**Comment by afollestad** [comment]
Hmmmm, I remember @plusCubed contributing something that added that. Or we were allowing AppCompat to handle the shadows. Something may've changed, we'll have to look into it.

Thank you!

**Comment by alexsmithfanning** [comment]
I'm pretty sure that some old versions had it. I remember seeing it at some point.

**Comment by plusCubed** [comment]
I don't think I ever implemented such a thing (I did fix dimming the background behind the dialog I think). I believe we would need to fake the lollipop elevation system with drawables for shadows if we are to implement this.

**Comment by afollestad** [comment]
I don't really feel like this is an issue. This is what MD looks like in a KitKat emulator:

![2](https://cloud.githubusercontent.com/assets/1820165/10949656/b41876a4-82f9-11e5-96ed-d6e7eba2c67e.png)

**Comment by alexsmithfanning** [comment]
I don't really think its an issue either, but it adds more of the "material experience" with shadows.

I do have to admit, it still looks damn good.
