### ISSUE TITLE
Allow usercolorinput (false) not working?Help

### ISSUE THREAD

**Issue by iampawan** [afollestad/material-dialogs#807]
```gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
```

**Comment by afollestad** [comment]
I'll need a little more details, e.g. the code used to show the color chooser so I can see the combination of settings you used. 

Also, make sure you're using the latest version (0.8.5.0).

**Comment by iampawan** [comment]
new ColorChooserDialog.Builder(this, R.string.color_palette)
    .allowUserColorInput(false)
    .customButton(R.string.md_custom_label)
    .presetsButton(R.string.md_presets_label)
    .show();

Using this 
or
new ColorChooserDialog.Builder(this, R.string.color_palette)
    .allowUserColorInput(false)
    .titleSub(R.string.colors)
     .preselect(primaryPreselect)
    .show();

**Comment by iampawan** [comment]
When not using allowusercolorinput(false) then its working perfect

**Comment by iampawan** [comment]
i m using 8.4.2

**Comment by iampawan** [comment]
updation helped ... :) Thanks a lot

**Comment by afollestad** [comment]
I was just gonna say, I can't reproduce the issue 😀

Glad it works now!

**Comment by iampawan** [comment]
hahahaha ... well i know this is very difficult to produce any issue in this awesome library ..
Thanks to u ;)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1
