### ISSUE TITLE
ic_launcher.png duplication

### ISSUE THREAD

**Issue by fernandobperezm** [afollestad/material-dialogs#808]
The lib is carrying with a ic_launcher.png file making gradle.build to fail when android:icon is set to ic_launcher.png (default config).

This is the error:
>/home/fernandoperez/Desktop/SomeFolder/grade-manager/app/build/intermediates/res/merged/debug/drawable-hdpi/ic_launcher.png: error: Duplicate file.
>/home/fernandoperez/Desktop/SomeFolder/grade-manager/app/build/intermediates/res/merged/debug/drawable-hdpi-v4/ic_launcher.png: Original is here. The version qualifier may be implied.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/fernandoperez/Android/Sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

Making a rename of ic_launcher.png, Android Studio throws the following warning:
The resource @drawable/ic_launcher is defined outside of the project (in one of the libraries) and cannot be updated. This can change the behavior of the application.  Are you sure you want to do this?  Unhandled references: materiallist\1.2.0\res\drawable-hdpi-v4\ic_launcher.png materiallist\1.2.0\res\drawable-mdpi-v4\ic_launcher.png materiallist\1.2.0\res\drawable-xhdpi-v4\ic_launcher.png materiallist\1.2.0\res\drawable-xxhdpi-v4\ic_launcher.png

**Comment by afollestad** [comment]
Hmm, odd. Thousands of apps use this library and I've never received this error before.

I don't think it's directly related to this library.

**Comment by eneim** [comment]
Is there any chance you are using this: https://github.com/dexafree/MaterialList

But the old version. It clearly turns out that your problem caused by materiallist\1.2.0\res\drawable-xhdpi-v4\ic_launcher.png and so on. Try to fix it.
