### ISSUE TITLE
I need a help about credits?

### ISSUE THREAD

**Issue by iampawan** [afollestad/material-dialogs#812]
I have used ur libraray in my app. Now i want to upload this on playstore so how can i give credits to ur library so that my app get publish easily..
I know it can be silly but i am a newbie
Thanks

**Comment by AzureusSme** [comment]
+1

**Comment by afollestad** [comment]
Technically you don't have to give credits, but if you want to you can do so however you choose

**Comment by iampawan** [comment]
@afollestad thank you !!!
