### ISSUE TITLE
RGB textViews not updating when seekbar is updated (ColorChooserDialog) (8.5.0)

### ISSUE THREAD

**Issue by AdityaAnand1** [afollestad/material-dialogs#815]
When dragging either R,G or B sliders only the hex values are updated. The Alpha textview is updating just fine, but the R,G,B textViews don't seem to be even used anywhere.

<img width="526" alt="bug" src="https://cloud.githubusercontent.com/assets/13274079/11016564/dc0f5f38-85ab-11e5-89a8-791c17cb314c.png">

Even the following basic ColorChooserDialog is broken.

```java
new ColorChooserDialog.Builder(this, R.string.color_palette)
                .show();
```

I'm new to GitHub, so I'm not sure how this works. Although, I was able to fix it:

The seekBar change listener seems to be talking to the TextWatcher which is where the alpha textView is being updated. Just underneath is:

```java
int red = Color.red(mSelectedCustomColor);
mCustomSeekR.setProgress(red);
int green = Color.green(mSelectedCustomColor);
mCustomSeekG.setProgress(green);
int blue = Color.blue(mSelectedCustomColor);
mCustomSeekB.setProgress(blue);
```

Simply appending the following:

```java
mCustomSeekRValue.setText(String.format("%d", red));
mCustomSeekGValue.setText(String.format("%d", green));
mCustomSeekBValue.setText(String.format("%d", blue));
```

Just after the above snippet seems to fix it.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
