### ISSUE TITLE
'Cancel' button is not shown for custom color input.

### ISSUE THREAD

**Issue by AdityaAnand1** [afollestad/material-dialogs#817]
The color pallete dialog shows a cancel button.
<img width="205" alt="screenshot 2015-11-08 16 45 45" src="https://cloud.githubusercontent.com/assets/13274079/11020031/5f816a14-8638-11e5-8e55-f07e3f98cf48.png">

The custom input dialog does not.
<img width="204" alt="screenshot 2015-11-08 16 45 32" src="https://cloud.githubusercontent.com/assets/13274079/11020032/5fbc988c-8638-11e5-9266-6ee3760da5cf.png">

Not a exactly a bug, but consistency would be good :)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1
