### ISSUE TITLE
question about edit text dialog

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#820]
is it possible to add two edit text fields in input dialogs using a custom layout?
thanks:)

**Comment by afollestad** [comment]
This is a possible duplicate of multiple issues.

Are you asking if you can add multiple edit text fields to a custom layout. Why wouldn't you be able to?

**Comment by enricocid** [comment]
Done, thank You:)

![senza nome](https://cloud.githubusercontent.com/assets/7274841/11607397/06581af6-9b45-11e5-9f11-5410efd14903.png)

**Comment by ebrirad** [comment]
hey guy how you could solve this problem ... could you help me and write your code in here...

**Comment by enricocid** [comment]
You Can see my implementation here

https://github.com/enricocid/iven-feed-reader

https://github.com/enricocid/iven-feed-reader/blob/master-as/project/app/src/main/res/layout/add_feed_layout.xml


addFeed() method in https://github.com/enricocid/iven-feed-reader/blob/master-as/project/app/src/main/java/com/iven/lfflfeedreader/mainact/ListActivity.java
