### ISSUE TITLE
Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.0

### ISSUE THREAD

**Issue by icoo1985** [afollestad/material-dialogs#821]
Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.0
why?How to resolve?

compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
    }
repositories {
        maven { url "https://jitpack.io" }
        jcenter()
    }

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/818

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by roshaplus** [comment]
compile 'com.afollestad.material-dialogs:core:0.9.6.0'

**Comment by roshaplus** [comment]
compile 'com.afollestad.material-dialogs:core:0.8.6.1'
    compile 'com.afollestad.material-dialogs:commons:0.8.6.1'
