### ISSUE TITLE
Cant compile lib

### ISSUE THREAD

**Issue by adamvarhegyi** [afollestad/material-dialogs#822]
Hi, im trying to compile the lib and got the **following error:**

    Information:Gradle tasks [:DoToDoSenderApp:assembleDebug]
    Error:A problem occurred configuring project ':DoToDoSenderApp'.
    > Could not resolve all dependencies for configuration ':DoToDoSenderApp:_debugCompile'.
    > Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.
    Searched in the following locations:
    https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    Required by:
    DoToDo_as:DoToDoSenderApp:unspecified > DoToDo_as:DoToDoEssentials:unspecified
    Information:BUILD FAILED
    Information:Total time: 2.98 secs
    Information:1 error
    Information:0 warnings
    Information:See complete output in console

This is **my gradle file:**

    apply plugin: 'com.android.library'

    android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    }
    repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    }

    dependencies {

    compile 'com.android.support:appcompat-v7:23.+' //appcompat for navigation drawer
    compile 'com.android.support:design:23.+' //views
    compile 'com.android.support:support-v13:23.+' //views

    compile 'com.google.android.gms:play-services-gcm:8.1.0' //google gcm pushes
    compile 'com.google.android.gms:play-services-location:8.1.0' //google location functions
    compile 'com.google.android.gms:play-services-maps:8.1.0' //google maps

    compile 'com.facebook.android:facebook-android-sdk:4.6.0' //facebook lib
    compile 'de.hdodenhof:circleimageview:2.0.0' //circle image view
    compile 'com.squareup.picasso:picasso:2.5.2' //image downloader lib
    compile 'com.google.code.gson:gson:2.4' //gson for serialization
    compile 'com.squareup.okio:okio:1.6.0'  //okhttp dependency
    compile 'com.squareup.okhttp:okhttp:2.5.0'   //networking lib
    compile 'com.googlecode.libphonenumber:libphonenumber:5.5' //phone number library

    compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
    }

    compile fileTree(dir: 'libs', include: ['*.jar'])
    }

**I have added**

    maven { url "https://jitpack.io" } 

**as well as**

    compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
    }

(Gradle is in online mode)

What m i missin here, can you help me out?

**Comment by afollestad** [comment]
Do you realize there was literally just two duplicate issues with the same problem?

**Comment by afollestad** [comment]
You may want to report the issue to JitPack.io though

**Comment by adamvarhegyi** [comment]
At the time i posted there was 0 duplicates, and now also zero topics open about this problem.
I will report to jitpack.

**Comment by afollestad** [comment]
Two were posted yesterday, and one or two were a week or two ago 😉 thanks

**Comment by afollestad** [comment]
See if the latest release works https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by roshaplus** [comment]
compile 'com.afollestad.material-dialogs:core:0.8.6.1'
    compile 'com.afollestad.material-dialogs:commons:0.8.6.1'
