### ISSUE TITLE
Custom ColorChooserDialog not scrollable

### ISSUE THREAD

**Issue by InTwoMinds** [afollestad/material-dialogs#823]
Layout in md_stub_colorchooser_custom.xml has LinearLayout as root, thus is not scrollable.
Simple solution would be to wrap it in ScrollView.

Cheers!

**Comment by afollestad** [comment]
It's intended to not be scrollable, I don't think it would look too good if it was.

Is there a device it gets cut off on?

**Comment by InTwoMinds** [comment]
Yep, on devices with small screen, and what's more important on larger ones in landscape mode.
md_stub_colorchooser_grid.xml is scrollable and looks good in both orientations.

Maybe another layout for landscape with vertical bars to the right of current color and EditText would be more appealing, but AFAIK vertical seekbars are kind of a pain to implement.

**Comment by afollestad** [comment]
It turns out it's not as simple as just wrapping it in a ScrollView. Since it's in a dialog, measuring is a bit different. I'll keep trying different ways.

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1
