### ISSUE TITLE
None of the com.afollestad classes are found when switching from 0.8.1.0 to 0.8.5.0

### ISSUE THREAD

**Issue by mntgoat** [afollestad/material-dialogs#824]
When I switch from:

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.1.0@aar') {
        transitive = true
}

compile('com.afollestad.material-dialogs:commons:0.8.1.0@aar') {
        transitive = true
}
```
To:

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
}

compile('com.github.afollestad.material-dialogs:commons:0.8.5.0@aar') {
        transitive = true
}
```

I thought I had JitPack configured right when I was using 0.8.1.0 but maybe I didn't. 

I can see the 0.8.5.0 classes under build/intermidates/exploded-aar but my code just won't compile becuase it can't find those classes. 

Anyone else had this issue?

**Comment by afollestad** [comment]
I haven't had this issue in any of the production apps using the library.

Nothing appears to be wrong above. I'll be publishing a new release soon, so that'll hopefully help.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by mntgoat** [comment]
Thanks, I'll test that.

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by mntgoat** [comment]
I haven't tried again, I'll give it a try tomorrow and let you know.

**Comment by mntgoat** [comment]
Sadly that didn't help me. It is very strange. I can see your stuff under exploded-aar but when compiling the code just can't find your classes.

**Comment by afollestad** [comment]
Your app's proguard rules are probably interfering or something. You need to keep all Material Dialogs classes.

**Comment by mntgoat** [comment]
Got it fixed. It wasn't even getting to proguard, it was all compiler errors on all afollestad classes but the errors went away once I removed an import for `com.afollestad.materialdialogs.internal.progress`, which I'm not using anymore. 

Thanks for the help.
