### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v7.internal.text.AllCapsTransformationMethod

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#825]
Hi, 
I get this error every time I try to open a dialog in pre-lollipop device (2.3)

java.lang.NoClassDefFoundError: android.support.v7.internal.text.AllCapsTransformationMethod
11-14 17:58:27.989 15704-15704/com.iven.lfflfeedreader E/AndroidRuntime:     at com.afollestad.materialdialogs.internal.MDButton.setAllCapsCompat(MDButton.java:94)
11-14 17:58:27.989 15704-15704/com.iven.lfflfeedreader E/AndroidRuntime:     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:237)
11-14 17:58:27.989 15704-15704/com.iven.lfflfeedreader E/AndroidRuntime:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
11-14 17:58:27.989 15704-15704/com.iven.lfflfeedreader E/AndroidRuntime:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1289)
11-14 17:58:27.989 15704-15704/com.iven.lfflfeedreader E/AndroidRuntime:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1294)

I think the imports are incorrect because I can't import
android.support.v7.internal.text.AllCapsTransformationMethod
but android.support.v7.text.AllCapsTransformationMethod yes

thanks, sorry for my bad explanation xD

do You know how I can fix ?

**Comment by afollestad** [comment]
I'm assuming you're using version 23.1.1 of the support library?

**Comment by enricocid** [comment]
exactly:)

**Comment by afollestad** [comment]
It'll work whenever I release a new version of Material Dialogs that uses the new Support Library

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by enricocid** [comment]
thank You:)
