### ISSUE TITLE
Gravity tweaks

### ISSUE THREAD

**Issue by Thore1954** [afollestad/material-dialogs#826]
As everybody else also agree, This library is another one of those great tools for bringing the material feel and look for users, plus flexibility and efficiency for the developer in android applications.

In spite of being rapidly evolved and getting problems off the plate, there's an old small one, abandoned and almost forgotten issue which could easily sink the project if not payed attention any longer.

As other developers have also eventually mentioned, there's is a big mistake about the **Gravity** functionality which ships with this library:
* In our opinion, the whole idea of changing single components gravity inside the dialog is not what actually meant to be. changing the gravity, **then mirroring it** when switching from LTR to RTL (or vise versa) means completely ruining the design of the dialogs.
* When a developer, including you, wants to use material dialogs, he/she actually wants to use it as per official documentation. When changing the gravity comes into place (like gravity `center`), it means changing the whole design.
* The main problem is with the mirroring part. When a developer using the library, changes the gravity for example to `end`, the dialog components is right-aligned and then being left-aligned when the phone switches to a RTL language which is complete anti-pattern and anti what actually Locale-Specific gravity is meant to do.

We advise to:
* Either remove the whole single-component gravity changing functionality, and let it stay Left in LTR languages and being mirrored to right in RTL languages. (Similar to Appcompat)
* Or add the constants `start` for developers who are developing apps for both LTR and RTL languages, `left` for those wants they're dialog stay left-aligned in all locales and `right` for those that only develop applications for middle-east countries. (One step further the Appcompat)

**Comment by afollestad** [comment]
What users decide to do is up to them.

**Comment by Thore1954** [comment]
The long period of time that was taken since you saw this issue till now that only passed it by, indicates that some work was done but were unable resolving it.
Anyway, you're the owner.

**Comment by afollestad** [comment]
You're assumptions are wrong. I have a life on the weekends and I work 8-12 hours a day during the week as a software developer.

**Comment by afollestad** [comment]
So no, I read it and made a decision after reading it.
