### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by tellfa** [afollestad/material-dialogs#827]
Hi. how can i change font and set my custom font for items or content?
tnx

**Comment by afollestad** [comment]
There's a big tutorial on the front page.

**Comment by tellfa** [comment]
please send me link to tutorial. tnx

**Comment by afollestad** [comment]
It's the first thing you see when you browse to this project.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs

**Comment by iad24** [comment]
Hi @afollestad great lib here. The example on the custom font u have in the front page is thru themes. Is it possible to configure the fonts per dialog? and not using the theme?
