### ISSUE TITLE
Incorrect customView (PercentRelativeLayout)

### ISSUE THREAD

**Issue by astelmakh** [afollestad/material-dialogs#828]
PercentRelativeLayout
50% width left part | vertical_divider | 50% width right part

No words, just sample:
AlertDialog.Builder (android.support.v7.app.AlertDialog)
![image](https://cloud.githubusercontent.com/assets/15889116/11210972/178ca58c-8d3d-11e5-927d-2d8aecd419ee.png)
MaterialDialog.Builder (com.afollestad.materialdialogs.MaterialDialog)
![image](https://cloud.githubusercontent.com/assets/15889116/11210996/40ee2f90-8d3d-11e5-8c6e-3d691818fb58.png)

Thank's in advance.

**Comment by Spoetnic** [comment]
Personally I would solve this with a horizontal-LinearLayout, with 2 sub-layouts, both having weight 1, and width 0.

If you built your own Layout class, are you sure you overrode all the corrent methods?

**Comment by afollestad** [comment]
Set wrapInScrollView to false and use your own ScrollView.

**Comment by afollestad** [comment]
When `wrapInScrollView` is true (in `.customView(int, boolean)`), default content inset padding is added around your custom view on purpose.
