### ISSUE TITLE
jitpack not finding version 0.7.8.0

### ISSUE THREAD

**Issue by trevorrjohn** [afollestad/material-dialogs#829]
Not sure what is going on here but this github project has a release tag <https://github.com/afollestad/material-dialogs/releases/tag/v0.7.8.0> but it is not being found by jitpack. If you look at their releases for some reason they have a release tagged v0.7.8.1.0 which doesn't appear to be a tag (<https://jitpack.io/com/github/afollestad/material-dialogs/0.7.8.1.0/build.log>). Not sure what to do but this is a huge problem, if I can't fetch older versions. Obviously I could go to a submodule, but I would prefer not to.

**Comment by afollestad** [comment]
Well you're using two different tags fhsre. 0.7.8.1.0 and the version with a v in front of it are different. 

But those older releases were originally hosted on jCenter, I switched to JitPack for newer releases. Although JitPack should still find them in theory.

**Comment by afollestad** [comment]
You shouldn't be using old builds anyways, there's too many things that had to be fixed since then.

**Comment by trevorrjohn** [comment]
No but the issue is some of us still depend on build tools 22 and 0.8.0 requires 23.

**Comment by trevorrjohn** [comment]
Sorry bad grammar. But because I am still dependent on api build tools version 22 and cannot upgrade yet, I am stuck on the older support library which 0.8.0 requires.

**Comment by afollestad** [comment]
Sorry for the late response, you can reference old versions by commit hash ID, also.
