### ISSUE TITLE
Dialog Icon - getter for icon view

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#832]
I can't get the icon of the dialog and change it, can I?

I want to use the image loader I use everywhere else... Currently I display a default image and afterwards change the icon via reflection like following:

```java
MaterialDialog dialog = builder.build();
try {
            Field icon = dialog.getClass().getDeclaredField("icon");
            icon.setAccessible(true);
            ImageView ivIcon = (ImageView)icon.get(dialog);
            // load image into image view...
} catch (NoSuchFieldException e) {
            L.e(this, e);
} catch (IllegalAccessException e) {
            L.e(this, e);
}
```

**Comment by afollestad** [comment]
Well, a much cleaner solution would be:

```java
MaterialDialog dialog = builder.build();
ImageView icon = (ImageView) dialog.getView().findViewById(R.id.icon);
```

But I'll add a getter method.

**Comment by MFlisar** [comment]
Just did not know what's the id of the icon...

Another solution would be to add something like following to the builder as an addition:

    builder.icon(64, new IImageLoader()
        {
            public void onImageViewReady(ImageView iv)
            {
                // load image into iv... 
            }
        });

But your solution is good enough for me... Thanks

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
