### ISSUE TITLE
Failed to resolve: compile com.afollestad:material-dialogs:0.8.5.1

### ISSUE THREAD

**Issue by gurappa** [afollestad/material-dialogs#833]
Seems this is an old issue. I see it in Play store too.
Could you please help me resolving this issue ? I tried JitPack way of building it but same error.

Thanks,
Guru

**Comment by afollestad** [comment]
Sorry, my response will be the same as the other issues (some of which were from two days ago or so). It works fine for me so there's not too much I can do.

**Comment by afollestad** [comment]
JitPack says the latest version built fine, so make sure your build.gradle is setup correctly.

https://jitpack.io/#com.afollestad/material-dialogs

**Comment by gurappa** [comment]
Okay.
My build.gradle is all fine. I have no issues with that. In fact, there is not much we should setup. Setting up the repo url and dependency. I did this.
I have multiple other dependencies from github and are working fine.

**Comment by gurappa** [comment]
Hi,

I am not sure if this is the issue that everybody is facing but I could resolve by having same level of buildToolsVersion as that of compileSdkVersion in my gradle. Probably that could be the issue for others too. See the 3rd question and answer by ClarkXP here. http://stackoverflow.com/questions/33813640/android-progressdialog-position-issue-and-do-we-have-androids-progressdialog-fr.
This is the possible answer to this issue.

This may also be an issue : http://stackoverflow.com/questions/32900524/unable-to-update-gradle-dependency-for-a-library

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
