### ISSUE TITLE
Failed to resolve: com.github.afollestad.material-dialogs

### ISSUE THREAD

**Issue by longxianlin** [afollestad/material-dialogs#835]
terrible error

**Comment by longxianlin** [comment]
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}

then solved

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
