### ISSUE TITLE
Set palette view as default ColorChooserDialog

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#838]
Hi Aidan,

I'm implementing a ColorChooserDialog in my App. By the way the default view is always the custom one. How can I set as default the palette view? Thanks

**Comment by afollestad** [comment]
If you pass a preselected color it will default to the presets view. 

I'll try to improve this.

**Comment by peppe130** [comment]
Could you write an example please?

**Comment by afollestad** [comment]
There's an example in the README and sample project. 

Pass a preselected color which exists in the palette.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.2
