### ISSUE TITLE
Could not find com.github.afollestad.material-dialogs:core:3ebbc9549e

### ISSUE THREAD

**Issue by bgenchel** [afollestad/material-dialogs#839]
Hi! 

I realize this might be a 'clone' but it appears significantly different enough to me in that none of the advice given on the other threads helped. A bit of context, I am not the android dev on my project, but due to unforseen circumstances, I have been left that responsibility for the week and need to get the app compiling.

I have the following in my build.gradle: 

    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }

    compile('com.github.afollestad.material-dialogs:core:0.8.5.1@aar') {
        transitive = true;
    }

Aaand this is the error output: 

    Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.afollestad.material-dialogs:core:0.8.5.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
         https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
         https://oss.sonatype.org/content/repositories/snapshots/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         https://oss.sonatype.org/content/repositories/snapshots/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
         https://maven.fabric.io/public/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         https://maven.fabric.io/public/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
         file:/Users/macbook/Library/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         file:/Users/macbook/Library/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
         file:/Users/macbook/Library/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.pom
         file:/Users/macbook/Library/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.1/core-0.8.5.1.aar
     Required by:
         my-app:app:unspecified > my-app:devicesetup:0.1.3

**Comment by afollestad** [comment]
Sorry, this is the same as the many other related issues. 

I'd recommend reporting an issue for JitPack.io

**Comment by bgenchel** [comment]
I think the repo compiles on a different computer though; and I'm not sure what could possibly be wrong with my version, and why it's reporting this plugin specifically as the problem... 

Do I need to install the repo locally?

**Comment by afollestad** [comment]
No, it works just like a regular Gradle dependency. Android Studio uses jCenter (owned by Bintray) by default, Maven Central and JitPack are just alternatives.

I have quite a few libraries hosted on JitPack that are used in a few production apps so I'm not sure why some people have problems resolving dependencies. 😮

**Comment by AndroidGecko** [comment]
same issue

**Comment by AndroidGecko** [comment]
at your jitpack page it says jitpack unresponsive :(
https://jitpack.io/#afollestad/material-dialogs/0.8.5.1

**Comment by afollestad** [comment]
@AndroidGecko 
![screenshot_20151123-093215](https://cloud.githubusercontent.com/assets/1820165/11340771/227cf58c-91c5-11e5-808a-8ce475290b2e.png)

**Comment by AndroidGecko** [comment]
ok got it working.
was adding jitpack repo to buildscript instead of android repositories
the badge also changed to "working" after few refreshes

**Comment by afollestad** [comment]
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by TheLester** [comment]
You should use jCenter or Maven, JitPack is really pain in the ass

**Comment by afollestad** [comment]
I used jCenter before, it was a pain in the ass. That's why I use JitPack.

**Comment by afollestad** [comment]
E.g. https://bintray.com/drummer-aidan/maven/material-dialogs/view

**Comment by TheLester** [comment]
@afollestad I have a problem to resolve 'com.afollestad:material-dialogs:0.7.7.0' It failed. I need old version for some reasons. I tried to use com.afollestad:material-dialogs:commit_hash_for_0.7.7.0 - and i got ClassNotFoundException for RecyclerView in Runtime.

**Comment by afollestad** [comment]
@TheLester JitPack uses the first 10 characters of the full commit hash:

<img width="1009" alt="screen shot 2015-12-06 at 4 19 38 pm" src="https://cloud.githubusercontent.com/assets/1820165/11616006/327d428c-9c35-11e5-84e2-c621361b1819.png">

<img width="618" alt="screen shot 2015-12-06 at 4 20 08 pm" src="https://cloud.githubusercontent.com/assets/1820165/11616012/3cd3ce54-9c35-11e5-8227-9e4da9839dfd.png">

**Comment by afollestad** [comment]
@TheLester here's the commit for 0.7.7.0:

<img width="1068" alt="screen shot 2015-12-06 at 4 20 57 pm" src="https://cloud.githubusercontent.com/assets/1820165/11616020/5fbbb35a-9c35-11e5-9283-9c263a15272c.png">

So the Gradle dependency would be:

```Gradle
compile('com.github.afollestad:material-dialogs:a56d4278d8@aar') {
    transitive = true
}
```

The library was not split into `core` and `commons` at the time, so I'd assume it *should* work as it appears above (without the module declaration).

**Comment by afollestad** [comment]
Sorry for all the comments, lol. But I should note a few things:

1. `transitive` to automatically import all libraries this library depends on, if your app doesn't already do so.
2. If your app uses a different version of a Google lib (e.g. AppCompat) than what the version of this library you're using does, that tends to cause issues.
3. 0.7.7.0 is *very* old, and *very* buggy compared to newer versions.

**Comment by TheLester** [comment]
@afollestad Thanks, thats worked:
compile('com.github.afollestad:material-dialogs:a56d4278d8@aar') {
    transitive = true
}
But can i rely on this? I mean its ok that its old 0.7.7.0, I used just some basic stuff from there. Can be some issues with dependency with hash in the future cause of JitPack?

**Comment by afollestad** [comment]
@TheLester you're welcome. You'll be fine, the commit hashes will never change unless the commits go away (which doesn't happen unless the repository is rebased, which I will never do). 😁

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
