### ISSUE TITLE
DialogFragment dismissListener

### ISSUE THREAD

**Issue by fahimk** [afollestad/material-dialogs#840]
Creating a DialogFragment exactly how it's done in the examples. Touching outside of the dialog closes it, but does not call the dismissListener or cancelListener.

**Comment by afollestad** [comment]
That's a limitation of DialogFragments, `android.app.Dialog` dismiss listeners are ignored.

You override `onDismiss` or `onCancel` in your `DialogFragment` subclass.

**Comment by fahimk** [comment]
That worked, I needed to override the onDismiss and onCancel from DialogFragment. Thanks!
