### ISSUE TITLE
gradle problem resource name wrong

### ISSUE THREAD

**Issue by gielDevelop** [afollestad/material-dialogs#841]
barlength has been already defined

**Comment by afollestad** [comment]
This is one of the most unspecific issues I've ever had reported. This isn't a problem with my library.

Your app is probably using a different version of AppCompat (older) than what this library uses.

http://stackoverflow.com/questions/32441420/attribute-barlength-has-already-been-defined

**Comment by gielDevelop** [comment]
please read all discution, especially comment number 3 and up
https://code.google.com/p/android/issues/detail?id=22576

**Comment by gielDevelop** [comment]
please read all discution, especially comment number 3 and up
https://code.google.com/p/android/issues/detail?id=22576

2015-11-23 17:34 GMT-03:00 Aidan Follestad <notifications@github.com>:

**Comment by afollestad** [comment]
That doesn't apply, this library prefixes all attributes. None of them are remotely close to `barlength`. 

It has to be something else in your app, like mismatched library versions.
