### ISSUE TITLE
How to change textsize of dialog

### ISSUE THREAD

**Issue by Kevin-Misfit** [afollestad/material-dialogs#844]
How to change textsize of dialog

**Comment by afollestad** [comment]
Currently you can't, it uses Material specs.

**Comment by Kevin-Misfit** [comment]
All right , thank you

**Comment by anthonygq** [comment]
Are we able to change the text size in the items list for single choice dialogs or any text on the content area of the dialog?  Since the title text size can now be changed, wondering if the same could be done in the content area.  Thanks in advance.
