### ISSUE TITLE
Example of Full Screen DIalog

### ISSUE THREAD

**Issue by shubendra** [afollestad/material-dialogs#845]
I saw your example. Its very good. Can you please update it with Full Screen Material Dialog. I saw Preference Dialog. But its actually an activity. How can we make full screen dialog like
https://www.google.co.in/design/spec/components/dialogs.html#dialogs-full-screen-dialogs

**Comment by afollestad** [comment]
This has been asked before, a full screen dialog is just an Activity with a Toolbar, which will not be included in this library.
