### ISSUE TITLE
sample min sdk 8, but  library 'me.zhanghai...' use min 14 (in core)

### ISSUE THREAD

**Issue by mdzht** [afollestad/material-dialogs#846]
Hi Aidan,
I think your library won't work on 9 android api, because of 
compile 'me.zhanghai.android.materialprogressbar:library:1.1.4' use min api 14
I can't understand how it compiles.

**Comment by afollestad** [comment]
The library is used by thousands and it works fine. 

The progress bar library is only used on 14+.
