### ISSUE TITLE
IllegalStateException: You cannot set content() when you're using a custom view.

### ISSUE THREAD

**Issue by sergimola** [afollestad/material-dialogs#847]
Why is this restriction?
This used to work fine.

AlertDialogWrapper.Builder builder = new AlertDialogWrapper.Builder(getActivity());
builder.setMessage(mMessage);

**Comment by afollestad** [comment]
Because custom view dialogs and basic dialogs use completely different layouts for inflation speed and simplicity.

**Comment by holicz01** [comment]
how to fix it :( 
i speed a lot of time more than 3 hr
