### ISSUE TITLE
PreferenceDialog onDismiss issue

### ISSUE THREAD

**Issue by Morocat** [afollestad/material-dialogs#848]
Ran into an issue when dismissing a MaterialListPreference by clicking outside the dialog window. If the preference has not been changed previously via clicking a list option, it works fine but if the preference has been changed and then the user opens the preference again and dismisses it by clicking outside the window, the onPreferenceChange listener is then called. From looking at the callstack, it appears the issue comes from calling super.onDismiss(dialog) in the overriden onDismiss method in MaterialListPreference class. This creates a situation where the app thinks the positive button has been pressed, thereby triggering a call to onPreferenceChange.

To reproduce, create a MaterialListPreference, give it an onChange listener and some list items, run the app, open the dialog, choose an item, reopen the dialog, and dismiss it by clicking outside the dialog.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
