### ISSUE TITLE
Fix extra padding of MaterialListPreference

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/material-dialogs#849]
I'm not sure about this one but it seems when `MaterialListPreference` is used it provides some extra `padding` to the left.
Check the screenshot for getting it better. 
Note: The "Theme", "Default page" & "Lyrics Font Size" are using `MaterialListPreference`
![device-2015-12-01-172532](https://cloud.githubusercontent.com/assets/3120052/11500062/b999b054-9850-11e5-913f-22a234570257.png)

**Comment by afollestad** [comment]
Thank you

https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.2

**Comment by AkshayChordiya** [comment]
@afollestad Your welcome and are the best!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
