### ISSUE TITLE
Creating preferences programmatically causes NullPointerException

### ISSUE THREAD

**Issue by hschottm** [afollestad/material-dialogs#851]
Creating Preferences from code always causes a NullPointException in `PrefUtil.setLayoutResource` because the standard constructor doesn't add an initialized `AttributeSet`:

```java
    MaterialEditTextPreference myPreference = new MaterialEditTextPreference(getActivity());
```

this calls

```java
    init(context, null);
```

which calls

```java
    PrefUtil.setLayoutResource(this, null);
```

which will crash when it tries to call `getAttributeCount`on the null variable

```java
    for (int i = 0; i < attrs.getAttributeCount(); i++) {
```

Please add a null check for attrs in order to prevent these crashes for programmatically created preferences.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
