### ISSUE TITLE
MaterialListPreference doesn't save after 0.8.5.2

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/material-dialogs#852]
Hey @afollestad you released the v0.8.5.2 yesterday and `MaterialListPreference` doesn't work. I mean when I select an item in `MaterialListPreference` it doesn't actually save the value.
It seems like the the callback of pressing the item is missing. 

I'm trying to debug the issue. PS: I tried downgrading to v0.8.5.1 and it started working again.

**Comment by Morocat** [comment]
This issue was caused by the resolution to issue #848 which removed the super.onDismiss() call. The super function calls onDialogClosed(), which is what triggers the onChange listener.

**Comment by afollestad** [comment]
Undid #848 which fixes it.

**Comment by AkshayChordiya** [comment]
@afollestad Sweet!

**Comment by AkshayChordiya** [comment]
@afollestad When is v0.8.5.3 coming?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
