### ISSUE TITLE
MaterialEditTextPreference can not set Icon.

### ISSUE THREAD

**Issue by vertuxx** [afollestad/material-dialogs#854]
hi
I'm using MaterialEditTextPreference.

I try to programatically set Icon and set Dialog Icon.
then, Preference Screen was not shown Icon.
however, Opened Dialog shown Icon.

I lookup compared android-sdk/res/layout/preference.xml
and res/layout/md_preference_custom.xml.

has not view ImageView#android:id/icon

It is cause this to occur?

**Comment by vertuxx** [comment]
thank you.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
