### ISSUE TITLE
How to choose file using FolderChooser

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#855]
Hi,

I've implemented FolderChooser in my App. It works fine. Actually I have to choose first the folder and then I have to check if the file exists in that folder. How can I choose directly the file? I saw that FolderChooser lists only folders. Could you push a new update of the library with this feature? Thanks in advance

**Comment by afollestad** [comment]
It's intended specifically for folders; you could copy the class and make a custom file chooser pretty easily.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

There's a new `FileChooserDialog`.
