### ISSUE TITLE
Ability to not use the library's preference layout and fallback to the default

### ISSUE THREAD

**Issue by jmartingit** [afollestad/material-dialogs#856]
Hi Aidan,

I'm styling my preferences through styles.xml instead of custom layouts. The problem is since version 8.4.0 these styles are overriden by the library preference layout resource.

Is there any way I can avoid using the library layout without having to create a custom layout for my preferences? Or in other words, could it be possible to make the use of the library preference layout optional?

**Comment by afollestad** [comment]
What version are you using? This was fixed in release 0.8.5.0, the current is 0.8.5.2.

**Comment by afollestad** [comment]
To be more specific, the logic that prevents layouts from being overridden now is here:

https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/java/com/afollestad/materialdialogs/prefs/PrefUtil.java#L22

**Comment by jmartingit** [comment]
No, my problem is different. I'm not using a custom layout. I'm using attributes in styles.xml for my preferences. The problem stays in 0.8.5.2.

The problem is if I don't want to use the library layout, I'm forced to create a custom layout compulsorily. There's no other option. And setting a null custom layout doesn't help, because it overrides the styles too.

Maybe this could be bypassed with an attribute for the preference, indicating if we want to use the library layout or not.

**Comment by w3hacker** [comment]
+1

**Comment by afollestad** [comment]
Added a `app:useStockLayout="true"` attribute which will force preferences to use the stock layout (not override the layout).

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by jmartingit** [comment]
Thank you very much Aidan, I really appreciate it.
