### ISSUE TITLE
Collaboration: FileChooserDialog

### ISSUE THREAD

**Issue by jmartingit** [afollestad/material-dialogs#858]
Hi Aidan,

Based on your FolderChooserDialog, I made a FileChooserDialog that I needed for my app. I thought it would be nice to have a file chooser on the library, so the least I could do is share it with you in case you want to use it:

[FileChooserDialog.txt](https://github.com/afollestad/material-dialogs/files/52792/FileChooserDialog.txt)

These are the main differences from the folder chooser:
- I added the 'mimeType' method to the builder so it's possible to show only specific file types.
- I modified the 'listFiles' method to accept the mime type parameter and filter files accordingly.
- I created the 'fileIsMimeType' method for file type filtering.
- I deleted the choose button from the dialog; the user can navigate through the folders at will, and when he selects a file the dialog returns automatically.
- I updated the 'onSelection' method to make the callback and dismiss the dialog when the user selects a file.

Do with the class as you please and thanks for all your amazing work with this library.

**Comment by AkshayChordiya** [comment]
@jmartingit Seems nice. Make a pull request so that @afollestad can easily add it into the library.

**Comment by jmartingit** [comment]
@AkshayChordiya  Done! :)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/pull/861
