### ISSUE TITLE
Allow a separate callback class in ColorChooserDialog.Builder

### ISSUE THREAD

**Issue by LiquidPL** [afollestad/material-dialogs#859]
Right now, to create a color chooser dialog you need to specify an AppCompatActivity that implements ColorCallback.

However, I'm trying to implement this dialog in a Preference, and I would like to implement the callback there. Can you modify the dialog to make this possible?

**Comment by afollestad** [comment]
No, a callback instance wouldn't survive orientation changes. The color chooser is a DialogFragment.
