### ISSUE TITLE
Failed to resolve: com.afollestad:material-dialogs:a240bbe

### ISSUE THREAD

**Issue by bigfoot90** [afollestad/material-dialogs#860]
Hi, I'm compiling an app from https://github.com/mendhak/gpslogger,
but I'm having ```Error:(159, 13) Failed to resolve: com.afollestad:material-dialogs:a240bbe```

**Comment by afollestad** [comment]
@bigfoot90 that's not a valid commit hash for JitPack. JitPack uses the first 10 characters of the full commit ID. You should be using the `@aar` suffix too.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
