### ISSUE TITLE
Single choice List dialog setSelectedIndex not updating selection

### ISSUE THREAD

**Issue by davigotxi** [afollestad/material-dialogs#862]
I'm trying to update the selected item with the last selected item as mentioned in the documentation:
> If you want to preselect an item, pass an index 0 or greater in place of -1 in itemsCallbackSingleChoice(). Later, you can update the selected index using setSelectedIndex(int) on the MaterialDialog instance, if you're not using a custom adapter.

My code is as follows but calling setSelectedIndex does not seem to update the preselected item the next time I open the dialog:

```java
     return new MaterialDialog.Builder(getActivity())
                        .title(R.string.title)
                        .items(R.array.items)
                        .itemsCallbackSingleChoice(0, new MaterialDialog.ListCallbackSingleChoice() {
                            @Override
                            public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                editText.setText(text);
                                dialog.setSelectedIndex(which);
                                return true;
                            }
                        })
                        .show();
```

Am I doing something wrong?

**Comment by Morocat** [comment]
Once a dialog is dismissed it is destroyed so you will need to save which item was selected in a variable somewhere. Calling setSelectedIndex() from within the itemsCallback is redundant, as the item has already been selected and is generally used before the dialog is created. Once you've saved that index value, you can then use it in place of the 0 you're currently using.

**Comment by afollestad** [comment]
Like @Morocat said, `dialog.setSelectedIndex(which)` is redundant, that line should be removed.

Every time you show the dialog, you're setting the preselected index to 0.

**Comment by davigotxi** [comment]
thanks for the clarification, working now.
