### ISSUE TITLE
FolderChooserDialog in fragment

### ISSUE THREAD

**Issue by crysan** [afollestad/material-dialogs#863]
Hi!
In fragment

                new FolderChooserDialog.Builder(getActivity())
                        .chooseButton(R.string.md_choose_label) 
                        .initialPath("/sdcard/Download")  
                        .show();

getActivity()
or
this
not work.

**Comment by afollestad** [comment]
This is a duplicate of another issue.

Cast `getActivity()` to whatever your Activity class is called (e.g. `MainActivity`).

**Comment by crysan** [comment]
Fragment! is not activity :(

**Comment by afollestad** [comment]
@crysan I know, you're passing `getActivity()` from the `Fragment`.

**Comment by crysan** [comment]
getActivity() not work
I'm sorry, but I do not understand you
it turns out that Folder Chooser Dialog can not be opened in fragment?

**Comment by afollestad** [comment]
As my first comment mentions, you need to cast `getActivity()` from the `Fragment` to the name of your `Activity` class.

**Comment by crysan** [comment]
Example pls

**Comment by afollestad** [comment]
```java
MainActivity context = (MainActivity) getActivity();
new FolderChooserDialog.Builder(context)
                        .chooseButton(R.string.md_choose_label) 
                        .initialPath("/sdcard/Download")  
                        .show();
```

**Comment by afollestad** [comment]
You need to cast `Activity` to your class that implements the callback:

```java
MainActivity context = (MainActivity) getActivity();

new FolderChooserDialog.Builder(context)
    .chooseButton(R.string.md_choose_label) 
    .initialPath("/sdcard/Download")  
    .show();
```

**Comment by crysan** [comment]
This code is also not brought results.

**Comment by crysan** [comment]
http://i10.pixs.ru/storage/0/8/4/errpng_8377488_19790084.png

**Comment by afollestad** [comment]
@crysan `MainActivity` needs to implement `FolderChooserCallback`, this is discussed in the tutorial. 😉

**Comment by crysan** [comment]
Yes indeed!  Thank you!
However, what the return code is implemented in the interface of the activity?  What if I have a few fragments are used with FolderChooserDialog?
