### ISSUE TITLE
0.8.6.0 not on jitpack.io

### ISSUE THREAD

**Issue by PsyGik** [afollestad/material-dialogs#865]
Error:Could not find com.github.afollestad.material-dialogs:core:0.8.6.0.

https://jitpack.io/#com.afollestad/material-dialogs

Last version on jitpack is 0.8.5.2

Please confirm.

**Comment by AkshayChordiya** [comment]
@PsyGik Facing the same issue.
Waiting for @afollestad  to have a look at it.

**Comment by Spoetnic** [comment]
In my experience, it always takes about a day after a new release for jitpack to have it.
Check again tomorrow.

**Comment by afollestad** [comment]
It hasn't been released yet. JitPack doesn't have delays, it pulls directly from GitHub tags.

**Comment by afollestad** [comment]
Replaced the version in the README with `w.x.y.z`. You can see the current version with the JitPack.io badge in the README, as before.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
