### ISSUE TITLE
Hoping to release next version 

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/material-dialogs#867]
I'm waiting for next version where you have fixed the `MaterialListPreference` not saving the data.
The issue can be found here https://github.com/afollestad/material-dialogs/issues/852.
Thank you.

**Comment by afollestad** [comment]
Why did you open an issue for this?

**Comment by AkshayChordiya** [comment]
@afollestad I'm sorry but I'm eager for new version. And I replied quite a few times on previous issue page.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
