### ISSUE TITLE
Module 'com.afollestad:material-dialogs:0.8.5.2' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by CanGokdere** [afollestad/material-dialogs#869]
Just updated to android studio 1.5.1 and gradle 2.8, it is giving me this error, any ideas ?

**Comment by CanGokdere** [comment]
Compiling with @aar seemed to solve the issue

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by Aqua-Ye** [comment]
Problems appeared again with 0.8.6.2

`Error:Module 'com.afollestad.material-dialogs:commons:0.8.6.2' depends on one or more Android Libraries but is a jar`

**Comment by lai3d** [comment]
Me too. The same problem.

Module 'com.afollestad:material-dialogs:0.8.6.2' depends on one or more Android Libraries but is a jar
