### ISSUE TITLE
FileChooserDialog is not working

### ISSUE THREAD

**Issue by AlexMomotov** [afollestad/material-dialogs#875]
Can't figure out how to make it work. All folders shows up as empty, while all of them are full of files. Besides, looks like FileChooserDialog is not in library 0.8.5.2 yet: so I manualy copied it from git.

In any case, thank you for your work. Cool library.

**Comment by AlexMomotov** [comment]
whoops    

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /> `

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
