### ISSUE TITLE
Can not import project

### ISSUE THREAD

**Issue by chowaikong** [afollestad/material-dialogs#876]
I have try your method in the README, also I have try the method that JitPack.io shows(as picture below), but still not working, what's wrong?
![qq 20151216100831](https://cloud.githubusercontent.com/assets/2826726/11830118/fd5114e4-a3dc-11e5-9cd6-0b7548b97462.png)

**Comment by afollestad** [comment]
Sorry, there's not much I can do to answer this. I use what's shown in the README in a dozen apps and it works fine.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3
