### ISSUE TITLE
Custom dialog position

### ISSUE THREAD

**Issue by ray1984** [afollestad/material-dialogs#877]
Is it possible to display material-dialog like in image (taken him full width & specific height)?
![dialog_example](https://cloud.githubusercontent.com/assets/3238570/11864284/58e0a64c-a4ac-11e5-9340-8cc3f7d2a690.png)

**Comment by Spoetnic** [comment]
This is called a bottom-sheet, and I believe has very little in common with a dialog. Besides laying on top, not covering the entire window and having a 'shadowy' dark layer underneath. 

I'd very much advise against using dialogs for this feature

**Comment by afollestad** [comment]
Use Flipboard/bottomsheet.

**Comment by ray1984** [comment]
hmm, it seems useful

**Comment by afollestad** [comment]
It's not a dialog, a dialog is a completely separate component.

A bottomsheet is just a regular view that overlays other UI. https://github.com/Flipboard/bottomsheet

**Comment by afollestad** [comment]
Bottom sheet support has been implemented in 3.0.0-alpha1
