### ISSUE TITLE
Exception raised using imported modules

### ISSUE THREAD

**Issue by Morocat** [afollestad/material-dialogs#878]
After importing modules core and commons to work on a new pull request, attempting to use any MaterialPreference causes a rendering problem in the xml:

android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true

I've imported material-dialogs before and it worked fine so I'm not sure why it's not working now.

**Comment by afollestad** [comment]
Can you comment with the actual stack trace so I can find the line number?

**Comment by Morocat** [comment]
Well when I loaded it up this morning it began working fine and I've been unable to reproduce the issue. The error must have been on my end so I'm closing this issue for now.
