### ISSUE TITLE
Error:(30, 13) Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.1

### ISSUE THREAD

**Issue by Drashti-Patel** [afollestad/material-dialogs#880]
I tried all versions for import,but fail to build, please help me.

Thank You.

**Comment by afollestad** [comment]
See the many other duplicates and make sure you put the repository in the correct place.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by Drashti-Patel** [comment]
Here is my project's build.gradle

buildscript {
    repositories {
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}


Here is my app's build.gradle:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.solwininfotech.expensemanager"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile('com.github.afollestad.material-dialogs:commons:0.8.5.2@aar') {
        transitive = true
    }
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.0.+'
    compile 'com.android.support:cardview-v7:22.0.+'
    compile files('libs/itextpdf-5.2.1.jar')
    compile files('libs/hellocharts-library-1.5.8.jar')
}

Android studio Version: 1.4
JDK windows 7:  1.7.0_79

can't resolve library. Please help me.

**Comment by Drashti-Patel** [comment]
I tried all solutions you provide in duplicate issues.

**Comment by afollestad** [comment]
There's nothing I can do. You should ask JitPack: https://github.com/jitpack/jitpack.io/issues

**Comment by l3d00m** [comment]
Try to place it in the other build.gradle you have. Like it says in your snippet: Do not place your individual dependencies here.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
