### ISSUE TITLE
Preference Icon not showing up

### ISSUE THREAD

**Issue by Morocat** [afollestad/material-dialogs#881]
The preference icon that is displayed along with the title and summary in a preference screen does not show up only when using this package via 
compile('com.github.afollestad.material-dialogs:commons:0.8.5.2@aar') {
        transitive = true
    }

When I download and import the repository directly the icon shows up just fine. The icon is hidden in both the XML viewer as well as when running the program. No error is thrown so I cannot provide a callstack.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/issues/854

**Comment by afollestad** [comment]
Not released yet.
