### ISSUE TITLE
Cant seem to add this to my project

### ISSUE THREAD

**Issue by lancelinksp** [afollestad/material-dialogs#883]
Cant seem to add this to my project unless my target sdk version is 23. Any way around that? Thanks if you can help

**Comment by afollestad** [comment]
Sorry, I'm not aware of any workarounds.

On Sat, Dec 19, 2015, 11:29 PM lancelinksp <notifications@github.com> wrote:

> Cant seem to add this to my project unless my target sdk version is 23 Any
> way around that? Thanks if you can help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/883>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by lancelinksp** [comment]
Any chance you have an older jar for a version I can target sdk version 22?

**Comment by afollestad** [comment]
You can't use JARs for Android libraries, only AARs. You can reference old
commits by replacing the version name with the first 10 characters of a
commit ID.

On Sat, Dec 19, 2015, 11:33 PM lancelinksp <notifications@github.com> wrote:

> Any chance you have an older jar for a version I can target sdk version 22?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/883#issuecomment-166068809>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment]
That's a feature of JitPack.io, by the way.
