### ISSUE TITLE
Signle choice + edit text

### ISSUE THREAD

**Issue by lectricas** [afollestad/material-dialogs#884]
how?

new MaterialDialog.Builder(this)
                .title(R.string.close_dialog_title)
                .items(R.array.trip_types)
                .theme(Theme.LIGHT)
                .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                        /**
                         * If you use alwaysCallSingleChoiceCallback(), which is discussed below,
                         * returning false here won't allow the newly selected radio button to actually be selected.
                         **/
                        return true;
                    }
                })
                .positiveText(R.string.dialog_rate_ok)
                .inputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)
                .input(R.string.dialog_input_hint, R.string.dialog_input_prefill, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(MaterialDialog dialog, CharSequence input) {
                        // Do something
                    }
                })

                .show();

this doesn't work

**Comment by afollestad** [comment]
You need a custom view. You can't use multiple dialog types at the same time.
