### ISSUE TITLE
Clear MaterialSimpleListAdapter

### ISSUE THREAD

**Issue by ajdeguzman** [afollestad/material-dialogs#886]
How can I clear the adapter in order to set another items on it. I am trying to code like this:

```java
final MaterialSimpleListAdapter adapter = new MaterialSimpleListAdapter(mContext);
adapter.clear();
```

But it gives me an error.

**Comment by afollestad** [comment]
That class isn't meant to be modified, it pulls its items from `MaterialDialog`.
