### ISSUE TITLE
How to show the progress image left if no content

### ISSUE THREAD

**Issue by chushuangqi** [afollestad/material-dialogs#887]
![nfboy ntgbevyc7ewcw g](https://cloud.githubusercontent.com/assets/3992717/12028284/b777c6a6-ae0f-11e5-979b-67818dacac65.png)
The progress image will show right if no content. How to show it left?

**Comment by afollestad** [comment]
You should never have a progress dialog with no content in the first place. It goes against the guidelines this library follows.
