### ISSUE TITLE
can i reuse the dialog instance to show different content?

### ISSUE THREAD

**Issue by macarthor** [afollestad/material-dialogs#892]
hi community,

i've got several dialogs in my `Fragment`, and i use a fragment-global variable:

```java
private MaterialDialog mDialog = new MaterialDialog.Builder(getActivity())
    .build();
```

when i use...

```java
mDialog.show();
```

...later dialogs show the content of previous dialogs.

So, what if i wanna use ONLY ONE instance of MaterialDialog and show different content in it?

**Comment by afollestad** [comment]
Updated your description for correct code formatting and syntax highlighting. 

---

You can use the `setContent(CharSequence)` method which I believe is included in the documentation.

**Comment by macarthor** [comment]
@afollestad in my project, some dialogs have content but no title, while some have title but no content, while some are input dialogs, and some are list dialogs...

i wanna use only one instance for the dialog.

**Comment by afollestad** [comment]
Oh, you'll have to build a new dialog every time. Every dialog type has a separate layout that gets inflated when it's built.

**Comment by macarthor** [comment]
@afollestad got, thx~
