### ISSUE TITLE
using with support desing lib

### ISSUE THREAD

**Issue by mfpolat** [afollestad/material-dialogs#898]
In my app i am using this awasome lib with      compile 'com.android.support:design:23.0.1' and i get error 

Could not find class 'android.support.design.internal.NavigationMenuPresenter', referenced from method android.support.design.widget.NavigationView

When i delete 

compile('com.github.afollestad.material-dialogs:commons:0.8.5.0@aar') {
        transitive = true
    }
from build.gradle file it works i dont know if its a bug or not just need some help

**Comment by afollestad** [comment]
Well, first, you should be using 0.8.5.3:

```Gradle
compile('com.github.afollestad.material-dialogs:commons:0.8.5.3@aar') {
    transitive = true
}
```

But, you probably need to add rules to your app's Proguard file:

```
-dontwarn
-ignorewarnings
-keep class android.support.design.** { *; }Gradle
```

**Comment by mfpolat** [comment]
The result is the same . I still get same error

**Comment by LoreGr** [comment]
It happens to me as well. I "fixed" using

   compile('com.afollestad.material-dialogs:core:0.8.2.0@aar') {
        transitive = true
    }

**Comment by LiangCY** [comment]
Still get the same error
