### ISSUE TITLE
Use android.app.Activity, android.app.DialogFrament

### ISSUE THREAD

**Issue by mkonicek** [afollestad/material-dialogs#899]
`android.support.v4.app.Fragment` (used in a [few places](https://github.com/afollestad/material-dialogs/search?utf8=%E2%9C%93&q=v4.app.DialogFragment&type=Code)) is a backport of new the Fragment APIs added in Android version 11. It's a way to use the fragment APIs on very old Android versions (Gingerbread and below).

React Native has been using the "new" `android.app.Activity` since the first release:
https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/local-cli/generator-android/templates/package/MainActivity.java

Using the fragment APIs from the support library makes it difficult for new apps using `android.app.Activity` to use material-dialogs and other modules, discussion here: https://github.com/facebook/react-native/pull/5206

React Native itself requires API 16+ (depends on the [Choreographer](http://developer.android.com/intl/ru/reference/android/view/Choreographer.html) API) so supporting Gingerbread (API 10) and below is not possible with React Native apps in any case.

I don't think there's a reason to the APIs from the support library (`android.support.v4.app.Fragment`, `FragmentActivity` etc.) in new apps?

**Comment by afollestad** [comment]
This app use AppCompat for quite a few things, and most new apps should too, so AppCompatActivity/FragmentActivity usage is necessary.

**Comment by afollestad** [comment]
Even back to API 16, AppCompat is extremely useful and has a lot of features which are used.

**Comment by afollestad** [comment]
One more thing, this library is designed to be backwards compatible, so yes there's an obvious reason to use the Support versions.
