### ISSUE TITLE
Use FolderChooserDialog and FileChooserDialog in a Fragment

### ISSUE THREAD

**Issue by rebus007** [afollestad/material-dialogs#901]
It's possible to use this two chooser in a fragment? I don't find the way...

**Comment by jfabrix101** [comment]
Yes, you must pass as builder argoment "((YuourActivityClass)getActivity)"
where yourActivityClass must implements the FolderCallback interface.
In this method you can obtain the SharedPrefenrece and set the value for the file

I also suggest to you to maintain the reference to your fragment in your activity and in a "onFolderSelection" method call some method in your fragment to do some work  (as for example set the summary for the preference changing the file path as current value to give some feedback to user)

**Comment by jfabrix101** [comment]
I have made a modified version of FolderChooserDialog that allow to specify a separate Listener (useful in case of fragment) and a button for new folder.
See this issue - https://github.com/afollestad/material-dialogs/issues/872.

**Comment by afollestad** [comment]
There's nothing preventing it from working in a Fragment, although the callback goes to the Activity because the DialogFragment needs to attach to that. DialogFragments survive through orientation changes, even the callback (when it's the Activity).

**Comment by rebus007** [comment]
I solved it by putting callbacks in parent activity, thanks for the clarification.
