### ISSUE TITLE
height width with custom view

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [afollestad/material-dialogs#902]
How may I change the Height and Width of custom view ??

I have already set matchparent in xml but dialog always appeared with default behavior, I have already try following code after dialog.show()

dialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
but didnot work ...any body help to set dialog custom height and width

**Comment by afollestad** [comment]
Set it on the actual custom view. 

```java
dialog.getCustomView()
```

**Comment by abdulrahmanmajeed** [comment]
please send me the line how to do as I already try this but all in vain ....
dialogCaution.getCustomView().setLayoutParams(); and also set 
dialogCaution.getCustomView().setMinimumHeight(700);
dialogCaution.getCustomView().setMinimumWidth(700);

**Comment by jp1017** [comment]
so, what's your final valid codes? @abdulrahmanmajeed 

and how to set? @afollestad :smile:
