### ISSUE TITLE
Improvement - allow show once / dismiss forever warning dialogs

### ISSUE THREAD

**Issue by frmz** [afollestad/material-dialogs#903]
This is off course something that can be implemented with a simple wrapper (and this is what i am doing now) but it would be a nice addition to have an embedded way to do the following things:

  - Show a dialog only once providing an id, for example something like this will show the dialog only if now shown and dismissed already (MD will need to save a shared pref somewhere remembering this state)
```java
    Builder().showOnce(Config.MYWARNINGID)
```
  - Add an option to show a checkbox with "do not show this dialog again", again passing an ID that will do the same thing as above but with user selection
  - Add a way to know if dialog has been shown already or return null to show() if dialog is not created

**Comment by afollestad** [comment]
I don't think it's necessary to include that in the library itself
