### ISSUE TITLE
Indeterminate progress dialog only show spinner

### ISSUE THREAD

**Issue by sflanders** [afollestad/material-dialogs#905]
I'm curious is it possible to show only the spinner with everything else transparent.  I was able to accomplish this with the ProgressDialog but was unable to figure out a way to change the spinner color, so i've been looking for alternatives.

**Comment by afollestad** [comment]
This library is intended to follow the Material Design guidelines, doing that wouldn't follow the guidelines at all. 

You could try changing the background color through the Builder though.

**Comment by sflanders** [comment]
I don't see the progress dialog with spinner and text actually recommended in the guidelines.  It actually appears to use spinners or other graphic indicators that typically have no text and almost always transparent backgrounds with no borders around those graphic artifacts.  You can see most of this here:   https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

I tinkered around with your library and its much friendlier to use than the stock stuff.  :-)

**Comment by afollestad** [comment]
Well generally if you want to put a centered progress indicator, you'd just use a `ProgressBar` centered inside of your layout ;)

Such as:

```xml
<FrameLayout>

        <LinearLayout id="@+id/content">
        </LinearLayout>

        <ProgressBar layout_gravity="center" />

</FrameLayout>
```

**Comment by afollestad** [comment]
When it comes to dialogs, there is no example of any dialogs in the guidelines that do not have a white or dark gray background. A transparent dialog would be an anti-pattern in my opinion. :)

**Comment by sflanders** [comment]
Sounds good.  I'll look into that.  Thanks.

**Comment by GutoMartins019** [comment]
afollestad, thank you for your nice work, can you explain in more details how i use this <FrameLayout> to center de loading dialog?
