### ISSUE TITLE
How to use progress bar in asynkTask

### ISSUE THREAD

**Issue by MansoorJafari** [afollestad/material-dialogs#906]
Hello
I want use Material dialog for upload file to server and when set that for upload not work
 my code is:
in ProgressUpdate(param... progress){
 dialog.incrementProgress(progress[0]);
}

Thank you For giving advice.

**Comment by afollestad** [comment]
`setProgress(int)` is what you'd use there, not `incrementProgress(int)`.

**Comment by MansoorJafari** [comment]
Thank You Frinds.

**Comment by MansoorJafari** [comment]
Excuse me.
Can I use material dialog for play Video and show image or play sound?

Thank You

**Comment by afollestad** [comment]
With a custom view.
