### ISSUE TITLE
Building common library issue

### ISSUE THREAD

**Issue by TheFinestArtist** [afollestad/material-dialogs#907]
![screen shot 2016-01-17 at 10 18 39 pm](https://cloud.githubusercontent.com/assets/3123741/12377656/60af64ec-bd68-11e5-931d-3506f1285238.png)
![screen shot 2016-01-17 at 10 18 33 pm](https://cloud.githubusercontent.com/assets/3123741/12377657/60d55bac-bd68-11e5-9874-802e8b8aef52.png)

This issue took me days to find which dependency has problem.

**Comment by TheFinestArtist** [comment]
Works fine with `commons:0.8.5.2`

**Comment by afollestad** [comment]
Try using com.github.afollestad instead of com.afollestad.

**Comment by TheFinestArtist** [comment]
@afollestad Woks like a charm. Please let people know if you change the url. Thanks

**Comment by afollestad** [comment]
It's been like that for months, that's what's displayed in the README :)
