### ISSUE TITLE
fail to resolve

### ISSUE THREAD

**Issue by abbasfisal** [afollestad/material-dialogs#911]
hi tnx for lib

when i add your dep in my gradle this error appeared

Error:Failed to resolve: com.android.support:appcompat-v7:23.1.1

and

Error:Failed to resolve: com.android.support:recyclerview-v7:23.1.1

and
Error:Failed to resolve: com.android.support:support-v4:23.1.1

and 

Error:Failed to resolve: com.android.support:support-annotations:23.1.1

and i have this dep in gradle

    compile 'com.android.support:appcompat-v7:22.+'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:21.0.+'

**Comment by afollestad** [comment]
You need to use version 23.0.2 of all those libs.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
