### ISSUE TITLE
Add Material[File | Folder]ChooserPreference to commons

### ISSUE THREAD

**Issue by bkromhout** [afollestad/material-dialogs#919]
Hi, long time user of your library, works great.

I was thinking a couple weeks ago that it might be useful to add a couple more Material*Preference classes to the commons which use the File/Folder Chooser dialogs that the commons provides.

I meant to take a look at doing it myself, but sadly real life has gotten in the way and I'm likely not going to get around to it in the near future, so I figured I'd open an issue to suggest it.

Have a good day!

**Comment by afollestad** [comment]
I can't do that since the choosers are `DialogFragment`'s.
