### ISSUE TITLE
GitHub License icon missing in README.md

### ISSUE THREAD

**Issue by piotrek1543** [afollestad/material-dialogs#922]
It's next your project's README with missing image file. Please check the links

Cheers

**Comment by afollestad** [comment]
It's working fine on my end

![screenshot_20160123-165220](https://cloud.githubusercontent.com/assets/1820165/12533313/c0193664-c1f1-11e5-8dfd-22ff7017d919.png)

**Comment by piotrek1543** [comment]
![zrzut ekranu z 2016-01-24 00 02 14](https://cloud.githubusercontent.com/assets/11292212/12533352/d124c5b8-c22d-11e5-8625-40e1493aaa44.png)
