### ISSUE TITLE
Extra Checkable background on press for API <21

### ISSUE THREAD

**Issue by ervinmartirosyan** [afollestad/material-dialogs#925]
![device-2016-01-27-015126](https://cloud.githubusercontent.com/assets/14440541/12599289/57e79b12-c499-11e5-8f2a-02a1aa6726ae.png)
![device-2016-01-27-015158](https://cloud.githubusercontent.com/assets/14440541/12599291/5cb45f68-c499-11e5-8e54-05a84486a9c9.png)

**Comment by afollestad** [comment]
This can be fixed by setting the backgrounds of the radio buttons and check boxes to `@null` on API 21+. I'll fix it in a bit.

**Comment by ervinmartirosyan** [comment]
I have already fixed it. Making pull request just now
