### ISSUE TITLE
Seekbar

### ISSUE THREAD

**Issue by EpsilonOrionis** [afollestad/material-dialogs#932]
I added a custom view containing a seekbar, in the onPositive click dialog I want to get the seekbar value. How can I do this?

**Comment by TheFinestArtist** [comment]
1. Create the dialog using builder.
2. `dialog.getCustomView().findViewById(R.id.seekbar). setOnSeekBarChangeListener(you listener)`

**Comment by EpsilonOrionis** [comment]
**Thank you**
