### ISSUE TITLE
0.7.9.0 pulled from JitPack?

### ISSUE THREAD

**Issue by efung** [afollestad/material-dialogs#935]
Was the Maven artifact for the 0.7.9.0 release pulled from JitPack? It no longer resolves for us.

**Comment by afollestad** [comment]
JitPack works using tags on GitHub, so no.

**Comment by DanielJette** [comment]
Yeah, seems to be missing ... 
```
   > Artifact 'material-dialogs.aar (com.afollestad:material-dialogs:0.7.9.0)' not found.
     Searched in the following locations:
         https://jitpack.io/com/afollestad/material-dialogs/0.7.9.0/material-dialogs-0.7.9.0.aar
```

**Comment by afollestad** [comment]
JitPack will automatically rebuild from existing tags.

**Comment by DanielJette** [comment]
Well, apparently not for 0.7.9

**Comment by DanielJette** [comment]
It seems the tag `0.7.9.0` refers `0.8.5.2`, which might be the problem

**Comment by DanielJette** [comment]
![image](https://cloud.githubusercontent.com/assets/5921367/12819734/38f6d74e-cb2a-11e5-8d30-440e6d671193.png)

https://github.com/afollestad/material-dialogs/commit/245e2be343cd6e5cd1ad8020d14d12fe31e6313c

**Comment by efung** [comment]
According to https://jitpack.io/docs/ANDROID/ , the library's `build.gradle` should be defining `group` as `com.github.USERNAME`. But you've defined it as `com.afollestad`.

What is the proper Gradle dependency line we need, in order to get the `0.7.9.0` release?

I've tried the following, all with no success:

```
compile 'com.afollestad:material-dialogs:0.7.9.0'
compile 'com.github.afollestad:material-dialogs:0.7.9.0'
compile 'com.github.afollestad.material-dialogs:core:0.7.9.0'
```

**Comment by afollestad** [comment]
I have custom domains, you can use com.afollestad with all of my libraries.

**Comment by efung** [comment]
Ah, didn't know about JitPack [custom domains](https://github.com/jitpack/jitpack.io#custom-domain-name)

So… how can we use the `0.7.9.0` release then?

**Comment by afollestad** [comment]
It should work as seen in the README

**Comment by afollestad** [comment]
You may wanna check the tags to make sure the tag you're requesting exists.

**Comment by efung** [comment]
Absolutely: https://github.com/afollestad/material-dialogs/releases/tag/0.7.9.0

I've tried several variations on the group ID and artifact ID but no luck.

It **worked fine** up until a few days ago. That's what makes this so puzzling. This is what we had in our module's `build.gradle` in the dependencies:

```
compile 'com.afollestad:material-dialogs:0.7.9.0'
```

**Comment by afollestad** [comment]
Well, it looks like it's actually a build problem: https://jitpack.io/com/github/afollestad/material-dialogs/0.7.9.0/build.log

It's due to an out dated version of the Gradle plugin, you're probably going to upgrade to a newer version of the library.

**Comment by afollestad** [comment]
You can always check on the JitPack page:

![capture](https://cloud.githubusercontent.com/assets/1820165/12820955/f478ea1a-cb26-11e5-8d6c-5fbcbb1ab838.JPG)

**Comment by efung** [comment]
How are you displaying the older releases? When I go to https://jitpack.io/#afollestad/material-dialogs, all I see is:

<img width="603" alt="screen shot 2016-02-04 at 11 08 31 am" src="https://cloud.githubusercontent.com/assets/301094/12821034/a444081e-cb2f-11e5-9b9d-b904e91f2b87.png">

**Comment by afollestad** [comment]
If you click the "Builds" button, it tends to cycle through other builds in my experience

**Comment by DanielJette** [comment]
TIL

Thanks! That explains that, then. Thanks for your help.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
