### ISSUE TITLE
Position dialog below a button 

### ISSUE THREAD

**Issue by rahulrajeevan** [afollestad/material-dialogs#937]
Is there an option to position this dialog below a button . 

My requirement is to align dialog below a button as like in attached image 
![filter](https://cloud.githubusercontent.com/assets/5259427/12841805/89773458-cc14-11e5-8987-1ab9adc1daea.jpg)

Thanks in advance 

Rahul

**Comment by afollestad** [comment]
This library is intended for that. You can use a `PopupMenu` from the Android framework.
