### ISSUE TITLE
Suggestion - add bottom sheet style

### ISSUE THREAD

**Issue by MFlisar** [afollestad/material-dialogs#939]
I'm not sure if you consider this out of this libraries scope, but I think it would be a nice feature to allow to show the dialogs (like list dialogs or custom RecyclerView dialogs) easily as a bottom sheet as well...

Just an idea...

**Comment by afollestad** [comment]
Yeah, that's so dramatically different than a dialog that I think it belongs in a separate library. Especially since it would take a lot of extra code to implement.

I'd recommend using [bottomsheet](https://github.com/Flipboard/bottomsheet) by Flipboard.

**Comment by MFlisar** [comment]
*Update*

Now that the design library has the `android.support.design.widget.BottomSheetDialog`, maybe this point should be cosnidered again?

**Comment by afollestad** [comment]
It's been implemented in 3.0.0-alpha1
