### ISSUE TITLE
Keyboard isn't always automatically dismissed in Input Dialogs

### ISSUE THREAD

**Issue by dsdebastiani** [afollestad/material-dialogs#941]
When the dialog was closed, the keyboard doesn't automatically dismissed.
Tested on Android API 22.

I've followed the sample code:
```java
new MaterialDialog.Builder(this)
    .title(R.string.input)
    .inputRangeRes(2, 20, R.color.material_red_500)
    .input(null, null, new MaterialDialog.InputCallback() {
        @Override
        public void onInput(MaterialDialog dialog, CharSequence input) {
            // Do something
        }
    }).show();
```

**Comment by gingafazi** [comment]
I use this in my app for hide keyboard:

    InputMethodManager imm = (InputMethodManager) ((AppCompatActivity) context).getSystemService(Context.INPUT_METHOD_SERVICE);
    imm.hideSoftInputFromWindow(((AppCompatActivity) context).getCurrentFocus().getWindowToken(), 0);

**Comment by afollestad** [comment]
That's already used in the code for this library

**Comment by afollestad** [comment]
`DialogUtils.hideKeyboard()` is called here: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L1810

The `hideKeyboard()` method is here: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/util/DialogUtils.java#L222

---

I haven't experienced any problems with this but I'll leave the issue open in case anyone else has.

**Comment by TheFinestArtist** [comment]
Honestly, I had same problem. So I hided keyboard myself after input dialog is dismissed.

**Comment by rfazi** [comment]
After this line: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/util/DialogUtils.java#L224 i suggest to insert this:

```java
InputMethodManager imm = (InputMethodManager) builder.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
if (imm != null) imm.hideSoftInputFromWindow(dialog.getCurrentFocus().getWindowToken(), 0);
```

because this line:
`dialog.getCurrentFocus().getWindowToken()`
obviates all this:
```java
dialog.getInputEditText().post(new Runnable() {
            @Override
            public void run() {
                dialog.getInputEditText().requestFocus();
                InputMethodManager imm = (InputMethodManager) builder.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
                if (imm != null)
                    imm.hideSoftInputFromWindow(dialog.getInputEditText().getWindowToken(), 0);
            }
        });
```

**Comment by gorchg** [comment]
How about like this.

[ MateriaDialog.java ]
public Builder(@NonNull Activity activity) {
            this.context = activity;
          activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
...

[AlertDialogWrapper.java]
...
public Builder(@NonNull Activity activity) {
            builder = new MaterialDialog.Builder(activity);
        }
...

[ DialogUtils.java ]
public static void showKeyboard(DialogInterface di, final MaterialDialog.Builder builder) {
        final MaterialDialog dialog = (MaterialDialog) di;
        if (dialog.getInputEditText() == null) return;
        dialog.getInputEditText().post(new Runnable() {
            @Override
            public void run() {
                dialog.getInputEditText().requestFocus();
                InputMethodManager imm = (InputMethodManager) builder.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
                imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
            }
        });
    }

    public static void hideKeyboard(DialogInterface di, final MaterialDialog.Builder builder) {
        final MaterialDialog dialog = (MaterialDialog) di;
        if (dialog.getInputEditText() == null) return;
        dialog.getInputEditText().post(new Runnable() {
            @Override
            public void run() {
                dialog.getInputEditText().requestFocus();
                InputMethodManager imm = (InputMethodManager) builder.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
                if (imm != null) {
                    imm.hideSoftInputFromWindow(dialog.getInputEditText().getWindowToken(), 0);
                }
            }
        });
    }

My source is worked.

**Comment by afollestad** [comment]
@gorchg you really should use syntax highlighting and code formatting in GitHub comments. Otherwise it's impossible to read. I've updated your comment though.

I've made the small change @rfazi suggested though.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.

**Comment by cherry-wave** [comment]
I have the same problem, when returning to home screen with the devices' home button.
