### ISSUE TITLE
Ability to change Ripple Color of buttons or set themeoverlay for them (per button) on Lollipop

### ISSUE THREAD

**Issue by justjanne** [afollestad/material-dialogs#946]
According to the Material Design Guidelines, only the positive button should be in the accent color, and have a ripple color tinted in the accent color.

Currently I can change the text color separately, but changing the ripple color doesn’t seem to be possible yet.

**Comment by afollestad** [comment]
That's not true. https://www.google.com/design/spec/components/dialogs.html

You can use a custom selector if you want that behavior, though.
