### ISSUE TITLE
Dialog gets closed after screen orientation changes

### ISSUE THREAD

**Issue by anggrayudi** [afollestad/material-dialogs#947]
`FolderChooserDialog` and `ColorChooserDialog` always retain to show the dialog, even we change the screen oriantation on a device. But, if we use normal material dialogs, the dialog gets closed whenever we change the screen orientation. Seems that we need to save its state.

**Comment by afollestad** [comment]
That's not a bug. You have to put your dialogs in a DialogFragment.

**Comment by anggrayudi** [comment]
Ah, I just found a workaround. I downloaded your library and modify `MaterialDialog` class by using [Saving State technique](http://www.intertech.com/Blog/android-custom-view-tutorial-part-3-saving-state). With this, we don't need to put the dialog on `DialogFragment` anymore.

Here's my code to save and retrieve the state. You can copy it to your library.

    @Override
    public Bundle onSaveInstanceState() {
        Bundle superState = super.onSaveInstanceState();
        SavedState myState = new SavedState(superState);
        Bundle mBundle = new Bundle();
        mBundle.putSerializable("md_builder", getBuilder());
        myState.bundle = mBundle;
        dismiss();
        return mBundle;
    }

    @Override
    public void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        Bundle bundle = savedInstanceState.getBundle("md_builder");
        mBuilder = (Builder) bundle.getSerializable("md_builder");
        getBuilder().show();
    }

    private static class SavedState extends View.BaseSavedState {

        Bundle bundle;

        public SavedState(Parcelable superState) {
            super(superState);
        }

        private SavedState(Parcel in) {
            super(in);
            bundle = in.readBundle();
        }

        @Override
        public void writeToParcel(Parcel out, int flags) {
            super.writeToParcel(out, flags);
            out.writeBundle(bundle);
        }

        public static final Parcelable.Creator<SavedState> CREATOR = new Parcelable.Creator<SavedState>() {
            public SavedState createFromParcel(Parcel in) {
                return new SavedState(in);
            }

            public SavedState[] newArray(int size) {
                return new SavedState[size];
            }
        };
    }

And don't forget to make `Builder` class implements `Serializable`.

**Comment by crysan** [comment]
+1

**Comment by crysan** [comment]
Is it possible to release the next version of the library with this correction?

**Comment by afollestad** [comment]
No, that messes with the default behavior of a dialog. If you want dialogs that maintain themselves during orientation change, you wrap your dialog with a `DialogFragment`.

**Comment by Rainer-Lang** [comment]
@afollestad Is there a reason why the material-dialogs aren't already wrapped with DialogFragment?

**Comment by anggrayudi** [comment]
Hi @afollestad, can you make Material Dialogs uses DialogFragment by default? So that it can rotate without being closed.

Thanks.

**Comment by afollestad** [comment]
No, that would be too large of a change to do for the entire library. Everything would have to be redone.

**Comment by proninyaroslav** [comment]
@afollestad 
Hello. Can I pass SingleButtonCallback from the main fragment to a DialogFragment (that contains MaterialDialog)?
