### ISSUE TITLE
How to show first folders and then files in FileChooserDialog

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#950]
Could you add this option to FileChooserDialog? Thanks

**Comment by peppe130** [comment]
Thanks

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.
