### ISSUE TITLE
InputDialog does not open soft keyboard on 6.0 in certain cases

### ISSUE THREAD

**Issue by dirkam** [afollestad/material-dialogs#954]
If you start an activity when the device is locked with keyguard where user should input something in a dialog then soft keyboard won't open (not even when you focus and tap on the edittext field).

Steps to reproduce
1. OS: 6.0 (all other seem to work fine)
2. Create an Activity which shows an InputDialog (don't forget to use dismiss keyguard, show on lockscreen etc flags).
3. Use AlarmManager to trigger the start of this Activity.
4. Set your device to use some kind of lock mechanism (such as patter or PIN lock).
5. Press the power button on the device to make sure it goes to sleep.
6. When activity start, dialog will be shown but there is no way to type in anything as the keyboard is hidden.

Can someone confirm this please? I start to think that this issue is related to the Android system itself, but maybe there is a workaround.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.6

**Comment by dirkam** [comment]
May I ask if you have tested this? I still see the same issue with 0.8.5.6.
No keyboard at all on 6.0.x Android.

**Comment by afollestad** [comment]
I have, it works fine on my Nexus 5X and 6P.

**Comment by dirkam** [comment]
Are you sure that you have tried it while the phone was locked and in idle state? I'm just asking because this thing drives me crazy. Do you happen to have your test code somewhere where I could check it?

**Comment by dirkam** [comment]
Couldn't check this with 0.8.5.7 yet, but I believe that with 0.8.5.6 despite the change in code this issue still exists.

**Comment by dirkam** [comment]
Attached a sample app to test it.
[DialogKeyboardTest.zip](https://github.com/afollestad/material-dialogs/files/171999/DialogKeyboardTest.zip)

**Comment by dirkam** [comment]
Tested on Nexus 6 (6.0.1). If no lock screen lock is used then it works. With screen locks (PIN, pattern, etc.) the keyboard is not shown.
