### ISSUE TITLE
CancelListener on FileChooserDialog

### ISSUE THREAD

**Issue by jlelse** [afollestad/material-dialogs#955]
I really need to know when the FileChooserDialog was canceled. How can I achieve this?

**Comment by afollestad** [comment]
There isn't a good solution for this because it's a `DialogFragment`. Callbacks (interfaces) are not `Serializable` so they cannot be maintained through orientation change without passing it again when an `Activity` is recreated.

**Comment by jlelse** [comment]
Oh ok
