### ISSUE TITLE
Handle multiple FolderChooserDialog in same Activity

### ISSUE THREAD

**Issue by Ashish-Bansal** [afollestad/material-dialogs#956]
Hi,

Is there any way I can know which FolderChooserDialog called the callback onFolderSelection if there are more than one FolderChooserDialog builders in same activity ?

PS: I can do it by creating static member in my activity and changing it before creating any FolderChooserDialog but still I would like to confirm if there exists something in API which I am not aware of.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.

**Comment by Ashish-Bansal** [comment]
@afollestad Thanks for this addition!
