### ISSUE TITLE
Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

### ISSUE THREAD

**Issue by hzsweers** [afollestad/material-dialogs#960]
Looks like that icon was removed in appcompat 23.2.0, likely in favor of a vector icon

**Comment by novalu** [comment]
Same here. Cannot build project with new appcompat 23.2.0 and material-dialogs 0.8.5.4.

**Comment by mntgoat** [comment]
Just got this error as well. Guess I'll go back to 23.1.1

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.
