### ISSUE TITLE
Support Library 23.2.0, "No resource found that matches the given name"

### ISSUE THREAD

**Issue by jmodrako** [afollestad/material-dialogs#964]
There is an issue with 0.8.5.5 with Support Library 23.2.0. Also I can't get compile 0.8.5.4 with 23.2.0 on my side, following error occured:

"Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha')."

**Comment by JulienDev** [comment]
Same here

**Comment by AzureusSme** [comment]
Already reported, guys: https://github.com/jitpack/jitpack.io/issues/444

**Comment by marinica94** [comment]
How much can this take ?

**Comment by AzureusSme** [comment]
Use Support Library 23.1.1 and 0.8.5.4 until Jitpack update its support library.

**Comment by subinsebastien** [comment]
Affected by the same issue. Subscribing.

**Comment by AzureusSme** [comment]
Already fixed: https://github.com/jitpack/jitpack.io/issues/444#issuecomment-188675840

**Comment by jmodrako** [comment]
Closed.

**Comment by subinsebastien** [comment]
@AzureusSme :+1:

**Comment by carloxavier** [comment]
this seems to be back on v24.2.1

**Comment by nikunjgundaniya** [comment]
@carloxavier yeah, back again!

**Comment by FedericoPonzi** [comment]
Same problem here c:

**Comment by afollestad** [comment]
This issue here is specifically for Support 23.2.0, which is not supported.
