### ISSUE TITLE
minSdkVersion is not really 8

### ISSUE THREAD

**Issue by abusuioc** [afollestad/material-dialogs#965]
For v.0.8.5.5, at compile time, I get:

> Error:(5, 5) uses-sdk:minSdkVersion 8 cannot be smaller than version 14 declared in library >>[..]/applover-android/library/build/intermediates/exploded-aar/me.zhanghai.android.materialprogressbar/library/1.1.4/AndroidManifest.xml

Is there still a way to keep the minSdkVersion to 8?

**Comment by PDDStudio** [comment]
`/me.zhanghai.android.materialprogressbar/` is not a package of this repository's library

**Comment by abusuioc** [comment]
Well, I see a:
`compile 'me.zhanghai.android.materialprogressbar:library:1.1.5'`
in [https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle](https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle)

**Comment by webmaster128** [comment]
MaterialProgressBar is a dependency and MaterialProgressBar is API 14+ so we either need to remove the dependency or drop support for API 8–13.

One could fix/fork MaterialProgressBar to support lower APIs but is it really worth it? Would someone be willing to dig into that?

**Comment by afollestad** [comment]
The developer of MaterialProgressBar mentioned why he cannot support lower API versions.

I'm not really worried about this right now, especially since most of the world is using at least API 14 by now. If not, they're seriously stuck in the past.

**Comment by abusuioc** [comment]
Ok, makes sense.

Then I suggest to change the `minSdkVersion 8` to  `minSdkVersion 14` in [https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle](https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle)

Thanks a lot!
