### ISSUE TITLE
Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

### ISSUE THREAD

**Issue by draskosaric** [afollestad/material-dialogs#968]
Hi,

I upgraded Android Support Library to 23.2.0., but building failed with error message:

`Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').
`
It would be really great if you could solve this asap, or just explain how to do workaround(providing these drawables that we can just pust in `/res`, or something like this), since 23.2.0 brought very much needed feature of RecyclerView, but I can't use it because of this error. 

Thank you very much in advance!

**Comment by afollestad** [comment]
This is a duplicate of 5 other closed issues and was fixed in the current release

**Comment by draskosaric** [comment]
Sorry. Thanks!
