### ISSUE TITLE
Custom GridView

### ISSUE THREAD

**Issue by csbenz** [afollestad/material-dialogs#969]
How can I do if I want to show a custom GridView.
In the docs I understand how to show a custom view in the dialog, but how do I manage my GridView and the selected item? Do I have to use the ListView with custom adapter?

Awesome library by the way, thanks a lot.

**Comment by afollestad** [comment]
You have to setup the `GridView` or whatever independent from the dialog.

---

You can either pass an inflated View to the dialog that's setup, or pass a layout resource ID to the `Builder` and set it up after you build the dialog.

**Comment by csbenz** [comment]
OK thanks, will try!
