### ISSUE TITLE
Recent changes to soft keyboard behavior broke keyboard hide/show behavior

### ISSUE THREAD

**Issue by bkromhout** [afollestad/material-dialogs#971]
Hi, the commits added for 0.8.5.5 in attempts to fix soft keyboard show/hide behavior seem to have actually broken it. Whereas I had no issues with it before, now I see two issues:

* Using a simple input dialog, the keyboard is shown when the dialog opens, but when the positive button is clicked and the dialog is dismissed, they keyboard stays open
* Building off of the former issue, if the same dialog is opened again, **then** the keyboard is hidden, which is obviously the opposite of intended behavior (interestingly, however, the action of tapping the dialog's edittext in order to make the keyboard show seems to prevent the first issue from recurring; that is, they keyboard will be correctly hidden upon the dialog being dismissed)

[Here's a Dropbox link to a recording I made which demonstrates both issues.](https://dl.dropboxusercontent.com/u/50734541/Recording.mp4) The recording was made on a physical device (an LG G3) running Lollipop 5.1.1/API 22, but I can also reproduce it on an emulator running API levels 21, 22, and 23.

**Comment by devslava** [comment]
Unfortunately I have issue with keyboard behavior too.
But my issue is another. When input dialog opens, soft keyboard opens for a second and immediately closes. After that I am not able to get keyboard. Neither focus change nor clicking at the EditText have no effect.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.6

**Comment by Bill871** [comment]
I think that this is still broken in 0.8.5.6. Or at least the behavior changed and in my opinion the SHOW_IMPLICIT worked better:

- when you have an dialog with input text, the keyboard opens automatically, which is alright
- but when you tap an button to open another dialog over this one that does NOT have an input text, the keyboard now stays open (which in my opinion is wrong), in version 0.8.5.4 this worked correctly

**Comment by afollestad** [comment]
It works fine for me.
