### ISSUE TITLE
Drawable not found with last Support Library (23.2.0)

### ISSUE THREAD

**Issue by rascafr** [afollestad/material-dialogs#972]
Hey !

Today I update my Gradle scripts and SDK, and I got the followingError : 

`(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').`

I'm using core version, 0.8.5.0@aar. Someone knows where does it come from ?

Thanks in advance !

**Comment by afollestad** [comment]
See the many closed issues.
