### ISSUE TITLE
MaterialEditTextPreference issue

### ISSUE THREAD

**Issue by cassiobruzasco** [afollestad/material-dialogs#975]
Hi,

Im trying to use MaterialEditTextPreference in one of my projects and when I try to open the fragment which the Preferences is inserted, it crashes with a class not found error. Im compiling version 8.5.4

**Comment by afollestad** [comment]
Unable to reproduce.

You're using an old version of the library, too.

**Comment by cassiobruzasco** [comment]
What version should I use? Im following the tutorial on github

**Comment by afollestad** [comment]
The latest version is always shown at the top of the README documentation, and on JitPack

**Comment by cassiobruzasco** [comment]
Tested this issue agaim, follow below the output:

compile('com.github.afollestad.material-dialogs:core:0.8.5.6@aar') {
    transitive = true
}


08:04:10.449 8096-8096/AndroidRuntime: FATAL EXCEPTION: main

        Process:  PID: 8096

        android.view.InflateException: Binary XML file line #5: Error
inflating class
com.afollestad.materialdialogs.prefs.MaterialEditTextPreference

Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.afollestad.materialdialogs.prefs.MaterialEditTextPreference"


On Fri, Feb 26, 2016 at 8:21 PM, Aidan Follestad <notifications@github.com>
wrote:

> The latest version is always shown at the top of the README documentation,
> and on JitPack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/975#issuecomment-189523189>
> .
>



-- 
____________________
Cássio Nicolai Bruzasco

**Comment by afollestad** [comment]
The preference classes are in Commons. See the documentation.

**Comment by cassiobruzasco** [comment]
Thanks for your instruction. I was used to only use material dialogs that I
didnt even realised that Preferences was in another component.
Thanks very much and take care :)


On Mon, Feb 29, 2016 at 12:49 PM, Aidan Follestad <notifications@github.com>
wrote:

> The preference classes are in Commons. See the documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/issues/975#issuecomment-190264364>
> .
>



-- 
____________________
Cássio Nicolai Bruzasco
