### ISSUE TITLE
Failed to resolve: com.github.afollestad.material-dialogs:commons:0.8.5.6

### ISSUE THREAD

**Issue by bleckfisk** [afollestad/material-dialogs#976]
I'm just getting the same error all the time when syncing gradle. It both fails to resolve the commons and the core package.

Everything is set up as it should be per your instructions in the READ.ME file.

I'm using the latest support repository and libraries. 

`Error:(38, 13) Failed to resolve: com.github.afollestad.material-dialogs:commons:0.8.5.6`
`Error:(35, 13) Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.6`

with:

`Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
     Required by:
         MYAPP:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
               > peer not authenticated
   > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
     Required by:
         MYAPP:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
               > peer not authenticated`

**Comment by jitpack-io** [comment]
@bleckfisk which version of Gradle are you using? Upgrading to 2.11 may help https://github.com/jitpack/jitpack.io/issues/423#issuecomment-181856675

**Comment by bleckfisk** [comment]
@jitpack-io I'm using the default gradle wrapper provided by Android Studio and there have been no problems at all up til this point.

Tested to change the distriubutionUrl to the following, without success.

`distriubutionUrl=https\://services.gradle.org/distributions/gradle-2.11-all.zip`

**Comment by bleckfisk** [comment]
Okay. Downloaded Gradle 2.11 and set it up. It seems like it worked but now i'm getting error 

`Failed to resolve: me.zhanghai.android.materialprogressbar:library:1.1.4`

It says that Material dialogs core package requires that apparently.

**Comment by afollestad** [comment]
I've had no issues with this.

[MaterialProgressBar](https://github.com/DreaminginCodeZH/MaterialProgressBar) is hosted on jCenter though.

**Comment by llbuckshotll** [comment]
I'm getting the same error.
Error:Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.6
Tired using:
gradle 2.8 & 2.11
wrapper with 2.11 set.
distributionUrl=https\://services.gradle.org/distributions/gradle-2.11-all.zip

Nothing is working.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
