### ISSUE TITLE
How to custom MimeType in FileChooserDialog?

### ISSUE THREAD

**Issue by leveychen** [afollestad/material-dialogs#977]
I want to find the file endwith `.db` only,what can I do?

**Comment by afollestad** [comment]
Read the documentation.

**Comment by leveychen** [comment]
I read the documentation again, but no gains.
I dont know what is the `.db` file mimetype.
How to use it with file extension?

**Comment by anggrayudi** [comment]
Hi @leveychen, I also ask this feature to @afollestad, in issue #1088. Seems that he ignored this important feature. You can check the mime-type for `.db` file extension [here](http://www.freeformatter.com/mime-types-list.html), and see if it's there. On my search, there's no mime-type for `.db` file extension.

What the hell does he thinking about?
