### ISSUE TITLE
ColorChooser: fire "Done" action when user clicks on a color

### ISSUE THREAD

**Issue by csbenz** [afollestad/material-dialogs#979]
First of all, this app is wonderful!
As an enhancement, it would nice to have an option in the ColorChooser builder to get the following behavior:
When the user select a color, the Dialog is then dismissed and the callback is called, without having to press the "Done" button.

**Comment by afollestad** [comment]
I don't think that'd be too useful, especially when two levels of colors are displayed and the user may want to go back.
