### ISSUE TITLE
Failed to resolve com.github.afollestad.material-dialogs:commons:0.8.5.6

### ISSUE THREAD

**Issue by yatna** [afollestad/material-dialogs#981]
I did exactly as told in the readme. Still gradle is not able to resolve both common and core. also tried com.github.afollestad.material-dialogs:core:0.8.1.0 , but that too did not work.

Error:(56, 13) Failed to resolve: com.github.afollestad.material-dialogs:commons:0.8.5.6
Show in File
Show in Project Structure dialog

**Comment by tomiu** [comment]
+1

**Comment by afollestad** [comment]
Make sure you have the JitPack repository in the correct place, make sure you're using Gradle 2.11.

---

I won't be able to help much more than that. If you can't figure it out with the above, report it to JitPack's issue tracker.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
