### ISSUE TITLE
Problems with Support Library 23.2.0

### ISSUE THREAD

**Issue by EpsilonOrionis** [afollestad/material-dialogs#982]

**Comment by afollestad** [comment]
This isn't specific enough to be an issue.

**Comment by EpsilonOrionis** [comment]
I updated Google Support Library and now I get this error: 
![cattura](https://cloud.githubusercontent.com/assets/7190255/13382135/23e0ac1c-de6d-11e5-8974-d0d3ecc0a0c9.PNG)

**Comment by EpsilonOrionis** [comment]
Are you serious?

**Comment by coderkiran** [comment]
How to solve this issue :)
![screenshot - 02292016 - 07 33 28 am](https://cloud.githubusercontent.com/assets/15968059/13383807/fe5c9ed4-deb6-11e5-986b-2ad4e3f08912.png)

**Comment by afollestad** [comment]
It's most likely a problem with @jitpack, however it's building fine and I've had no problems with it.

https://jitpack.io/#afollestad/material-dialogs

**Comment by AzureusSme** [comment]
I have no problems, check your build.gradle.

**Comment by afollestad** [comment]
@coderkiran you put the `allprojects` in the wrong place.

**Comment by afollestad** [comment]
Read this documentation more carefully and read up on Gradle.

**Comment by coderkiran** [comment]
How to solve it? :)
```
Error:(29, 13) Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.1
<a href="openFile:/home/user/Android App/Benionline.com.np/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

```

![screenshot - 02292016 - 12 33 06 pm](https://cloud.githubusercontent.com/assets/15968059/13387614/ac61f406-dee0-11e5-88e4-a24bd91d8d6a.png)
![screenshot - 02292016 - 12 33 23 pm](https://cloud.githubusercontent.com/assets/15968059/13387615/af3175e4-dee0-11e5-8343-b17621679160.png)

**Comment by afollestad** [comment]
Try a new version of the library. I can't help any further.
