### ISSUE TITLE
Issues with older version of Material Dialogs 

### ISSUE THREAD

**Issue by Orbar** [afollestad/material-dialogs#984]
All previous versions of the library were overwritten with Version `0.8.5.4` of the library on Jitpack

see: 
https://github.com/afollestad/material-dialogs/releases?after=v0.7.5.9

This results in builds that depend on older versions of the library to suddenly pull in V23.2.0 of the support library. 

are you able to undo this artifact override on jitpack.io?

**Comment by tomiu** [comment]
+1

**Comment by afollestad** [comment]
I can't, but you could use old versions of the library through their commit ID (a feature of JitPack).

**Comment by Orbar** [comment]
How?
I would like to use 0.8.5.4? ie pre support 23.2
