### ISSUE TITLE
Incompatible with com.android.support:appcompat-v7:23.2.0

### ISSUE THREAD

**Issue by joongbay** [afollestad/material-dialogs#985]
Upgrading appcompat to 23.2.0 breaks gradle build.
..\build\intermediates\exploded-aar\com.afollestad.material-dialogs\core\0.8.4.2\res\values-v11\values-v11.xml
Error:(5, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

**Comment by afollestad** [comment]
You're using an old version of this library, and there are 4 or 5 existing closed issues which explain that.
