### ISSUE TITLE
Build Failed with new design lib 'com.android.support:design:23.2.0'

### ISSUE THREAD

**Issue by svareniem** [afollestad/material-dialogs#986]
Fails to compile with the latest Support Design library 'com.android.support:design:23.2.0'

```
BUILD FAILED
...
/Users/svareniem/git/CorgiApp/corgiapp/app/build/intermediates/res/merged/debug/values/values.xml
Error:(649) Attribute "srcCompat" has already been defined
...
```
In the `values.xml` line:
```
...
<declare-styleable name="AppCompatImageView"><attr name="android:src"/><attr format="reference" name="srcCompat"/></declare-styleable>
...
```
Material Dialogs latest version 0.8.5.6:
```
    compile('com.github.afollestad.material-dialogs:core:0.8.5.6@aar') {
        transitive = true
    }
```

No problem with version 21.1.1 'com.android.support:design:23.1.1'

**Comment by afollestad** [comment]
This isn't related to this library. 

Try cleaning your project and make sure you're using the same version of AppCompat in all of your projects.

**Comment by ErickPaul** [comment]
Anybody who got a solution to this problem?
Still bugging for days...
