### ISSUE TITLE
Support "support library" 23.2.0

### ISSUE THREAD

**Issue by fichna** [afollestad/material-dialogs#988]
Hi, I'm using this awesome library, but when i want to upgrade support library to 23.2 version build fails.
It's the same bug as described in [this stackoverflow case](http://stackoverflow.com/questions/35628572/update-support-library-23-2-0-build-bug/35628668)

**Comment by fichna** [comment]
Error is in file `\app\build\intermediates\exploded-aar\com.afollestad\material-dialogs\0.7.6.0\res\values-v11\values-v11.xml`

It says `Error:(5, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').`

**Comment by AzureusSme** [comment]
Please update the library to the latest version 0.8.5.6

**Comment by fichna** [comment]
Oh, sorry... I'm using this library only for `fernandodev/easy-rating-dialog` and there is bad dependency (version) in the library

Thanks
