### ISSUE TITLE
problems below Lollipop(API 21+)

### ISSUE THREAD

**Issue by Wood-Water-Peng** [afollestad/material-dialogs#989]
![qq 20160302171653](https://cloud.githubusercontent.com/assets/12949541/13455926/5474f5ba-e09b-11e5-90fa-10224a158505.png)
The problem occurs when the phone version below 21(version 4.0 is still popular)
can you help me figure out it

**Comment by afollestad** [comment]
I have no problems below Lollipop:

![capture](https://cloud.githubusercontent.com/assets/1820165/13736169/11d8543e-e980-11e5-81dc-f4ec26089d6f.JPG)

I'm guessing you either have a conflicting attribute in your `Activity` theme, or you're using a non-stock version of Android that interferes.
