### ISSUE TITLE
Error:(35, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.9.1

### ISSUE THREAD

**Issue by chethan1333** [afollestad/material-dialogs#990]

**Comment by bleckfisk** [comment]
Make sure you have: 

`repositories {
    mavenCentral()
}`

in your App gradle. Resolved my issue with syncing.

**Comment by afollestad** [comment]
Maven Central should have nothing to do with it.

As the README mentions, make sure this is in your root build.gradle file (not inside of your app module):

```Gradle
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

The `...` being whatever else was in there before, e.g. `mavenCentral()`.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency

**Comment by ArmandL7** [comment]
Thx, it works.
