### ISSUE TITLE
error while useing library with SDK version 22

### ISSUE THREAD

**Issue by pasaneramusugoda** [afollestad/material-dialogs#992]
Trying to use the library with SDK v22. But I'm getting below errors.

**Gradle:**
compileSdkVersion 22
buildToolsVersion "23.0.2"
minSdkVersion 16
targetSdkVersion 22
compile('com.github.afollestad.material-dialogs:commons:0.8.5.6@aar') { transitive = true }

**Errors:**
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(33) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by afollestad** [comment]
You need to use AppCompat 23.2.0 in your app.
