### ISSUE TITLE
 Android API 23.2.0 crashes the app for core-version-0.8.5.3

### ISSUE THREAD

**Issue by kshitizshakya** [afollestad/material-dialogs#994]
Android appcompat v4 - 23.2.0  is buggy.
Can you please revert it to the previous version.

**Comment by afollestad** [comment]
No, use an old version of this library.

**Comment by ashughes** [comment]
@afollestad The problem is **all** older versions of your library now use support library 23.2.0, since they all now point to commit 5383df8. Please see issue #999 for more info!

**Comment by afollestad** [comment]
I know. You can reference an old version by commit or use the new release that uses AppCompat 23.2.1.

**Comment by Tortel** [comment]
Or maybe just fix the tags
