### ISSUE TITLE
Retroactive commit?

### ISSUE THREAD

**Issue by abhijitnukalapati** [afollestad/material-dialogs#995]
Hello Aidan! I see a recent commit in many of the previous versions of the library (beginning from release - `v0.7.7.0 `) - https://github.com/afollestad/material-dialogs/commit/5ceb034345adc8e8b0ed94852b2e84845694e09c. It appears to be an update to the support library, but it was pushed specifically for the release - `0.8.5.5`. So, I am a little baffled. Could you please take a look? I am currently using `0.8.5.3` (which was released on Dec 18, 2015), but the dependency graph indicates that this version of library uses support lib `23.2.0`

```
+--- com.github.afollestad.material-dialogs:core:0.8.5.3
|    +--- com.android.support:support-v4:23.2.0 (*)
|    +--- me.zhanghai.android.materialprogressbar:library:1.1.4
|    |    +--- com.android.support:appcompat-v7:23.0.1 -> 23.2.0 (*)
|    |    \--- com.android.support:support-annotations:23.0.1 -> 23.2.0
|    +--- com.android.support:appcompat-v7:23.2.0 (*)
|    +--- com.android.support:support-annotations:23.2.0
|    \--- com.android.support:recyclerview-v7:23.2.0 (*)
```

**Comment by afollestad** [comment]
You'll need to reference those pre-8.0.0 versions by commit ID.

0.7.7.0 is here:

![capture](https://cloud.githubusercontent.com/assets/1820165/13586316/c285618c-e485-11e5-9b82-12a0cd84c84f.JPG)

Use `a56d4278d8` in place of a version number.

**Comment by abhijitnukalapati** [comment]
@afollestad thanks for the response. perhaps I was unclear, I am using `0.8.5.3` (and **not** `v0.7.7.0`), but see support lib `23.2.0` as part of the dependency graph. does that make more sense? 

Also, this might help too. On the [releases page](https://github.com/afollestad/material-dialogs/releases), all the tags say '4 commits to master since this release', which seems odd to me.

**Comment by afollestad** [comment]
This was intended.
