### ISSUE TITLE
Failed to resolve: com.github.afollestad.material-dialogs:commons:0.8.5.6

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/material-dialogs#997]
I can add and resolve the `core` package without any problems. However, the `commons` package fails with the error message mentioned in the title.

Jitpack is added to the root build.gradle as repository.

**Comment by ImTosS** [comment]
@PDDStudio Have the same issue even with com.github.afollestad.material-dialogs:core:0.8.5.6@aar... jitpack.io is added too into root gradle too. I solved temporarily downgrading to com.github.afollestad.material-dialogs:core:0.8.5.3@aar

**Comment by afollestad** [comment]
There's not much I can do, it's probably a JitPack issue.

Hopefully it works for you with the next release.

**Comment by afollestad** [comment]
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
