### ISSUE TITLE
All tags point to same commit (5383df8)!

### ISSUE THREAD

**Issue by ashughes** [afollestad/material-dialogs#999]
I don't know when this occurred, but all your tags now point to commit 5383df8. This breaks JitPack, so no matter what version you set, you always get commit 5383df8 (tag 0.8.5.6).

For example, if you look at the build logs for all the latest versions at https://jitpack.io/#afollestad/material-dialogs, you can see they're all using commit 5383df8. You can also see on the releases page that all tags point to commit 5383df8.

**Comment by JonathonFry** [comment]
Thanks for raising this, was scratching my head trying to figure out why it wasn't respecting the version number. This is definitely a blocker issue for anyone not pointing at the latest version.

**Comment by ashughes** [comment]
Yea, I only noticed because I happened to clear my local gradle cache and do a build, and all of a sudden I was depending on the new 23.2.0 support libraries.

I images this is going to be a huge issue for a lot of people if the tags can't be fixed since any older builds now point to the latest version.

The temporary workaround is to reference specific commits instead...

**Comment by ashughes** [comment]
Why was this closed? It still looks like all tags 0.8.5.6 and below point to the same commit (5383df8).

**Comment by abhijitnukalapati** [comment]
@ashughes this seems to have been intended, and there isn't an explanation from the author unfortunately - see thread here: https://github.com/afollestad/material-dialogs/issues/995

**Comment by ashughes** [comment]
@abhijitnukalapati That's unfortunate. I'd love to hear the reasoning behind it. There's no benefit I can think of for changing the tags. Only confusion and unnecessary time spent debugging for many developers.
